export interface BibleBook {
  id: number;
  slug: string;
  name: Record<string, string>;
  chapters: number;
  testament: "OT" | "NT";
}

export const bibleBooks: BibleBook[] = [
  // Ancien Testament
  { id: 1, slug: "genese", name: { fr: "Genèse", ht: "Jenèz", en: "Genesis" }, chapters: 50, testament: "OT" },
  { id: 2, slug: "exode", name: { fr: "Exode", ht: "Egzòd", en: "Exodus" }, chapters: 40, testament: "OT" },
  { id: 3, slug: "levitique", name: { fr: "Lévitique", ht: "Levitik", en: "Leviticus" }, chapters: 27, testament: "OT" },
  { id: 4, slug: "nombres", name: { fr: "Nombres", ht: "Nonb", en: "Numbers" }, chapters: 36, testament: "OT" },
  { id: 5, slug: "deuteronome", name: { fr: "Deutéronome", ht: "Deteronòm", en: "Deuteronomy" }, chapters: 34, testament: "OT" },
  { id: 6, slug: "josue", name: { fr: "Josué", ht: "Jozye", en: "Joshua" }, chapters: 24, testament: "OT" },
  { id: 7, slug: "juges", name: { fr: "Juges", ht: "Jij", en: "Judges" }, chapters: 21, testament: "OT" },
  { id: 8, slug: "ruth", name: { fr: "Ruth", ht: "Rit", en: "Ruth" }, chapters: 4, testament: "OT" },
  { id: 9, slug: "1samuel", name: { fr: "1 Samuel", ht: "1 Samyèl", en: "1 Samuel" }, chapters: 31, testament: "OT" },
  { id: 10, slug: "2samuel", name: { fr: "2 Samuel", ht: "2 Samyèl", en: "2 Samuel" }, chapters: 24, testament: "OT" },
  { id: 11, slug: "1rois", name: { fr: "1 Rois", ht: "1 Wa", en: "1 Kings" }, chapters: 22, testament: "OT" },
  { id: 12, slug: "2rois", name: { fr: "2 Rois", ht: "2 Wa", en: "2 Kings" }, chapters: 25, testament: "OT" },
  { id: 13, slug: "1chroniques", name: { fr: "1 Chroniques", ht: "1 Kwonik", en: "1 Chronicles" }, chapters: 29, testament: "OT" },
  { id: 14, slug: "2chroniques", name: { fr: "2 Chroniques", ht: "2 Kwonik", en: "2 Chronicles" }, chapters: 36, testament: "OT" },
  { id: 15, slug: "esdras", name: { fr: "Esdras", ht: "Esdras", en: "Ezra" }, chapters: 10, testament: "OT" },
  { id: 16, slug: "nehemie", name: { fr: "Néhémie", ht: "Neyemi", en: "Nehemiah" }, chapters: 13, testament: "OT" },
  { id: 17, slug: "esther", name: { fr: "Esther", ht: "Estè", en: "Esther" }, chapters: 10, testament: "OT" },
  { id: 18, slug: "job", name: { fr: "Job", ht: "Jòb", en: "Job" }, chapters: 42, testament: "OT" },
  { id: 19, slug: "psaumes", name: { fr: "Psaumes", ht: "Sòm", en: "Psalms" }, chapters: 150, testament: "OT" },
  { id: 20, slug: "proverbes", name: { fr: "Proverbes", ht: "Pwovèb", en: "Proverbs" }, chapters: 31, testament: "OT" },
  { id: 21, slug: "ecclesiaste", name: { fr: "Ecclésiaste", ht: "Eklezyas", en: "Ecclesiastes" }, chapters: 12, testament: "OT" },
  { id: 22, slug: "cantique", name: { fr: "Cantique des Cantiques", ht: "Kantik Kantik", en: "Song of Solomon" }, chapters: 8, testament: "OT" },
  { id: 23, slug: "esaie", name: { fr: "Ésaïe", ht: "Ezayi", en: "Isaiah" }, chapters: 66, testament: "OT" },
  { id: 24, slug: "jeremie", name: { fr: "Jérémie", ht: "Jeremi", en: "Jeremiah" }, chapters: 52, testament: "OT" },
  { id: 25, slug: "lamentations", name: { fr: "Lamentations", ht: "Lamantasyon", en: "Lamentations" }, chapters: 5, testament: "OT" },
  { id: 26, slug: "ezechiel", name: { fr: "Ézéchiel", ht: "Ezekyèl", en: "Ezekiel" }, chapters: 48, testament: "OT" },
  { id: 27, slug: "daniel", name: { fr: "Daniel", ht: "Danyèl", en: "Daniel" }, chapters: 12, testament: "OT" },
  { id: 28, slug: "osee", name: { fr: "Osée", ht: "Oze", en: "Hosea" }, chapters: 14, testament: "OT" },
  { id: 29, slug: "joel", name: { fr: "Joël", ht: "Jowèl", en: "Joel" }, chapters: 3, testament: "OT" },
  { id: 30, slug: "amos", name: { fr: "Amos", ht: "Amòs", en: "Amos" }, chapters: 9, testament: "OT" },
  { id: 31, slug: "abdias", name: { fr: "Abdias", ht: "Abdyas", en: "Obadiah" }, chapters: 1, testament: "OT" },
  { id: 32, slug: "jonas", name: { fr: "Jonas", ht: "Jonas", en: "Jonah" }, chapters: 4, testament: "OT" },
  { id: 33, slug: "michee", name: { fr: "Michée", ht: "Miche", en: "Micah" }, chapters: 7, testament: "OT" },
  { id: 34, slug: "nahum", name: { fr: "Nahum", ht: "Nawoum", en: "Nahum" }, chapters: 3, testament: "OT" },
  { id: 35, slug: "habacuc", name: { fr: "Habacuc", ht: "Abakik", en: "Habakkuk" }, chapters: 3, testament: "OT" },
  { id: 36, slug: "sophonie", name: { fr: "Sophonie", ht: "Sofoni", en: "Zephaniah" }, chapters: 3, testament: "OT" },
  { id: 37, slug: "aggee", name: { fr: "Aggée", ht: "Aje", en: "Haggai" }, chapters: 2, testament: "OT" },
  { id: 38, slug: "zacharie", name: { fr: "Zacharie", ht: "Zakari", en: "Zechariah" }, chapters: 14, testament: "OT" },
  { id: 39, slug: "malachie", name: { fr: "Malachie", ht: "Malachi", en: "Malachi" }, chapters: 4, testament: "OT" },
  // Nouveau Testament
  { id: 40, slug: "matthieu", name: { fr: "Matthieu", ht: "Matye", en: "Matthew" }, chapters: 28, testament: "NT" },
  { id: 41, slug: "marc", name: { fr: "Marc", ht: "Mak", en: "Mark" }, chapters: 16, testament: "NT" },
  { id: 42, slug: "luc", name: { fr: "Luc", ht: "Lik", en: "Luke" }, chapters: 24, testament: "NT" },
  { id: 43, slug: "jean", name: { fr: "Jean", ht: "Jan", en: "John" }, chapters: 21, testament: "NT" },
  { id: 44, slug: "actes", name: { fr: "Actes", ht: "Travay", en: "Acts" }, chapters: 28, testament: "NT" },
  { id: 45, slug: "romains", name: { fr: "Romains", ht: "Women", en: "Romans" }, chapters: 16, testament: "NT" },
  { id: 46, slug: "1corinthiens", name: { fr: "1 Corinthiens", ht: "1 Korentyen", en: "1 Corinthians" }, chapters: 16, testament: "NT" },
  { id: 47, slug: "2corinthiens", name: { fr: "2 Corinthiens", ht: "2 Korentyen", en: "2 Corinthians" }, chapters: 13, testament: "NT" },
  { id: 48, slug: "galates", name: { fr: "Galates", ht: "Galat", en: "Galatians" }, chapters: 6, testament: "NT" },
  { id: 49, slug: "ephesiens", name: { fr: "Éphésiens", ht: "Efezyen", en: "Ephesians" }, chapters: 6, testament: "NT" },
  { id: 50, slug: "philippiens", name: { fr: "Philippiens", ht: "Filipyen", en: "Philippians" }, chapters: 4, testament: "NT" },
  { id: 51, slug: "colossiens", name: { fr: "Colossiens", ht: "Kolosyen", en: "Colossians" }, chapters: 4, testament: "NT" },
  { id: 52, slug: "1thessaloniciens", name: { fr: "1 Thessaloniciens", ht: "1 Tesalonisyen", en: "1 Thessalonians" }, chapters: 5, testament: "NT" },
  { id: 53, slug: "2thessaloniciens", name: { fr: "2 Thessaloniciens", ht: "2 Tesalonisyen", en: "2 Thessalonians" }, chapters: 3, testament: "NT" },
  { id: 54, slug: "1timothee", name: { fr: "1 Timothée", ht: "1 Timote", en: "1 Timothy" }, chapters: 6, testament: "NT" },
  { id: 55, slug: "2timothee", name: { fr: "2 Timothée", ht: "2 Timote", en: "2 Timothy" }, chapters: 4, testament: "NT" },
  { id: 56, slug: "tite", name: { fr: "Tite", ht: "Tit", en: "Titus" }, chapters: 3, testament: "NT" },
  { id: 57, slug: "philemon", name: { fr: "Philémon", ht: "Filemon", en: "Philemon" }, chapters: 1, testament: "NT" },
  { id: 58, slug: "hebreux", name: { fr: "Hébreux", ht: "Ebre", en: "Hebrews" }, chapters: 13, testament: "NT" },
  { id: 59, slug: "jacques", name: { fr: "Jacques", ht: "Jak", en: "James" }, chapters: 5, testament: "NT" },
  { id: 60, slug: "1pierre", name: { fr: "1 Pierre", ht: "1 Pyè", en: "1 Peter" }, chapters: 5, testament: "NT" },
  { id: 61, slug: "2pierre", name: { fr: "2 Pierre", ht: "2 Pyè", en: "2 Peter" }, chapters: 3, testament: "NT" },
  { id: 62, slug: "1jean", name: { fr: "1 Jean", ht: "1 Jan", en: "1 John" }, chapters: 5, testament: "NT" },
  { id: 63, slug: "2jean", name: { fr: "2 Jean", ht: "2 Jan", en: "2 John" }, chapters: 1, testament: "NT" },
  { id: 64, slug: "3jean", name: { fr: "3 Jean", ht: "3 Jan", en: "3 John" }, chapters: 1, testament: "NT" },
  { id: 65, slug: "jude", name: { fr: "Jude", ht: "Jid", en: "Jude" }, chapters: 1, testament: "NT" },
  { id: 66, slug: "apocalypse", name: { fr: "Apocalypse", ht: "Apokalips", en: "Revelation" }, chapters: 22, testament: "NT" },
];
