// ANGLAIS GÉNÉRAL — le parcours du quotidien, de A1 à B1.
//
// Fichier de DONNÉES pures (aucun import) : english-course.ts le lit et en
// fabrique les exercices. Ajouter une leçon = ajouter un thème ici.
//
// Chaque thème : 8 mots + 5 phrases + une citation. Le générateur en tire
// 7 exercices variés.

export interface GTheme {
  slug: string;
  fr: string; ht: string;
  icon: string;
  verse: { en: string; fr: string; ref: string };
  words: [string, string, string][];
  sentences: [string, string, string][];
}

export interface GUnit {
  slug: string;
  cefr: "a1" | "a2" | "b1" | "b2" | "c1" | "c2";
  fr: string; ht: string;
  sfr: string; sht: string;
  color: string; icon: string;
  themes: GTheme[];
}

export const GENERAL_UNITS: GUnit[] = [
  // ═══════════ A1 — GRAND DÉBUTANT ═══════════
  {
    slug: "g-premiers-mots", cefr: "a1", color: "#16a34a", icon: "👋",
    fr: "Premiers mots", ht: "Premye mo yo", sfr: "Se présenter et saluer", sht: "Prezante tèt ou epi salye",
    themes: [
      { slug: "g-saluer", fr: "Saluer quelqu'un", ht: "Salye yon moun", icon: "🤝",
        verse: { en: "A friend loveth at all times.", fr: "L'ami aime en tout temps.", ref: "Proverbs 17:17" },
        words: [["hello", "bonjour", "bonjou"], ["goodbye", "au revoir", "orevwa"], ["please", "s'il vous plaît", "souple"], ["thank you", "merci", "mèsi"],
                ["yes", "oui", "wi"], ["no", "non", "non"], ["sorry", "pardon", "padon"], ["welcome", "bienvenue", "byenveni"]],
        sentences: [["Hello how are you", "Bonjour comment allez-vous", "Bonjou kijan ou ye"],
                    ["I am fine thank you", "Je vais bien merci", "Mwen byen mèsi"],
                    ["Nice to meet you", "Enchanté de vous rencontrer", "Kontan rankontre ou"],
                    ["See you tomorrow", "À demain", "Na wè demen"],
                    ["Have a good day", "Bonne journée", "Pase yon bon jounen"]] },
      { slug: "g-se-presenter", fr: "Se présenter", ht: "Prezante tèt ou", icon: "🪪",
        verse: { en: "I have called thee by thy name.", fr: "Je t'ai appelé par ton nom.", ref: "Isaiah 43:1" },
        words: [["name", "nom", "non"], ["my", "mon", "mwen"], ["from", "de", "soti"], ["live", "habiter", "rete"],
                ["old", "âgé", "gen laj"], ["speak", "parler", "pale"], ["country", "pays", "peyi"], ["city", "ville", "vil"]],
        sentences: [["My name is Peter", "Je m'appelle Peter", "Non mwen se Peter"],
                    ["I am from Haiti", "Je viens d'Haïti", "Mwen soti Ayiti"],
                    ["I live in the city", "J'habite en ville", "Mwen rete nan vil la"],
                    ["I speak French and Creole", "Je parle français et créole", "Mwen pale franse ak kreyòl"],
                    ["What is your name", "Comment vous appelez-vous", "Kijan ou rele"]] },
      { slug: "g-nombres", fr: "Les nombres", ht: "Nonb yo", icon: "🔢",
        verse: { en: "Teach us to number our days.", fr: "Enseigne-nous à compter nos jours.", ref: "Psalm 90:12" },
        words: [["one", "un", "youn"], ["two", "deux", "de"], ["three", "trois", "twa"], ["ten", "dix", "dis"],
                ["hundred", "cent", "san"], ["first", "premier", "premye"], ["number", "nombre", "nonb"], ["many", "beaucoup", "anpil"]],
        sentences: [["I have two brothers", "J'ai deux frères", "Mwen gen de frè"],
                    ["It costs ten dollars", "Cela coûte dix dollars", "Li koute dis dola"],
                    ["This is my first time", "C'est ma première fois", "Se premye fwa mwen"],
                    ["There are many people", "Il y a beaucoup de gens", "Gen anpil moun"],
                    ["I need three books", "J'ai besoin de trois livres", "Mwen bezwen twa liv"]] },
    ],
  },
  {
    slug: "g-famille-maison", cefr: "a1", color: "#0891b2", icon: "🏠",
    fr: "La famille et la maison", ht: "Fanmi ak kay", sfr: "Parler de ses proches", sht: "Pale de moun pa ou",
    themes: [
      { slug: "g-famille", fr: "La famille", ht: "Fanmi an", icon: "👨‍👩‍👧",
        verse: { en: "Honour thy father and thy mother.", fr: "Honore ton père et ta mère.", ref: "Exodus 20:12" },
        words: [["mother", "mère", "manman"], ["father", "père", "papa"], ["son", "fils", "pitit gason"], ["daughter", "fille", "pitit fi"],
                ["wife", "épouse", "madanm"], ["husband", "mari", "mari"], ["baby", "bébé", "tibebe"], ["grandmother", "grand-mère", "grann"]],
        sentences: [["This is my mother", "Voici ma mère", "Sa se manman m"],
                    ["I have one son", "J'ai un fils", "Mwen gen yon pitit gason"],
                    ["My wife is a teacher", "Ma femme est enseignante", "Madanm mwen se yon pwofesè"],
                    ["We love our family", "Nous aimons notre famille", "Nou renmen fanmi nou"],
                    ["My grandmother is kind", "Ma grand-mère est gentille", "Grann mwen janti"]] },
      { slug: "g-maison", fr: "Dans la maison", ht: "Nan kay la", icon: "🛋️",
        verse: { en: "Except the Lord build the house, they labour in vain.", fr: "Si l'Éternel ne bâtit la maison, ceux qui la bâtissent travaillent en vain.", ref: "Psalm 127:1" },
        words: [["house", "maison", "kay"], ["room", "chambre", "chanm"], ["kitchen", "cuisine", "kizin"], ["door", "porte", "pòt"],
                ["window", "fenêtre", "fenèt"], ["table", "table", "tab"], ["bed", "lit", "kabann"], ["water", "eau", "dlo"]],
        sentences: [["The kitchen is clean", "La cuisine est propre", "Kizin nan pwòp"],
                    ["Please close the door", "Ferme la porte s'il te plaît", "Fèmen pòt la souple"],
                    ["My house has three rooms", "Ma maison a trois chambres", "Kay mwen gen twa chanm"],
                    ["The water is cold", "L'eau est froide", "Dlo a frèt"],
                    ["I need a table and a bed", "J'ai besoin d'une table et d'un lit", "Mwen bezwen yon tab ak yon kabann"]] },
      { slug: "g-temps-jours", fr: "Le temps et les jours", ht: "Tan ak jou yo", icon: "📅",
        verse: { en: "This is the day which the Lord hath made.", fr: "C'est ici la journée que l'Éternel a faite.", ref: "Psalm 118:24" },
        words: [["today", "aujourd'hui", "jodi a"], ["tomorrow", "demain", "demen"], ["morning", "matin", "maten"], ["night", "nuit", "nwit"],
                ["week", "semaine", "semèn"], ["month", "mois", "mwa"], ["hour", "heure", "lè"], ["late", "en retard", "an reta"]],
        sentences: [["I work in the morning", "Je travaille le matin", "Mwen travay nan maten"],
                    ["See you next week", "À la semaine prochaine", "Na wè semèn pwochen"],
                    ["What time is it", "Quelle heure est-il", "Ki lè li ye"],
                    ["I am late today", "Je suis en retard aujourd'hui", "Mwen an reta jodi a"],
                    ["The meeting is tomorrow", "La réunion est demain", "Reyinyon an se demen"]] },
    ],
  },
  {
    slug: "g-manger-acheter", cefr: "a1", color: "#d97706", icon: "🛒",
    fr: "Manger et acheter", ht: "Manje ak achte", sfr: "Au marché et au restaurant", sht: "Nan mache ak restoran",
    themes: [
      { slug: "g-restaurant", fr: "Au restaurant", ht: "Nan restoran", icon: "🍽️",
        verse: { en: "Whether therefore ye eat, or drink, do all to the glory of God.", fr: "Soit que vous mangiez, soit que vous buviez, faites tout pour la gloire de Dieu.", ref: "1 Corinthians 10:31" },
        words: [["food", "nourriture", "manje"], ["drink", "boisson", "bwason"], ["menu", "menu", "meni"], ["order", "commander", "kòmande"],
                ["chicken", "poulet", "poul"], ["rice", "riz", "diri"], ["bill", "addition", "fakti"], ["hungry", "affamé", "grangou"]],
        sentences: [["I would like some water", "Je voudrais de l'eau", "Mwen ta renmen dlo"],
                    ["Can I see the menu", "Puis-je voir le menu", "Èske m ka wè meni an"],
                    ["The chicken is very good", "Le poulet est très bon", "Poul la trè bon"],
                    ["The bill please", "L'addition s'il vous plaît", "Fakti a souple"],
                    ["I am very hungry", "J'ai très faim", "Mwen grangou anpil"]] },
      { slug: "g-magasin", fr: "Faire les courses", ht: "Fè makèt", icon: "🛍️",
        verse: { en: "The Lord is my shepherd; I shall not want.", fr: "L'Éternel est mon berger, je ne manquerai de rien.", ref: "Psalm 23:1" },
        words: [["shop", "magasin", "magazen"], ["buy", "acheter", "achte"], ["price", "prix", "pri"], ["money", "argent", "lajan"],
                ["cheap", "bon marché", "bon mache"], ["expensive", "cher", "chè"], ["size", "taille", "gwosè"], ["change", "monnaie", "monnen"]],
        sentences: [["How much does it cost", "Combien ça coûte", "Konbyen li koute"],
                    ["It is too expensive", "C'est trop cher", "Li twò chè"],
                    ["I want to buy this", "Je veux acheter ceci", "Mwen vle achte sa a"],
                    ["Do you have a smaller size", "Avez-vous une taille plus petite", "Èske ou gen yon gwosè pi piti"],
                    ["Here is your change", "Voici votre monnaie", "Men monnen ou"]] },
      { slug: "g-couleurs", fr: "Couleurs et objets", ht: "Koulè ak objè", icon: "🎨",
        verse: { en: "Though your sins be as scarlet, they shall be as white as snow.", fr: "Quand vos péchés seraient comme le cramoisi, ils deviendront blancs comme la neige.", ref: "Isaiah 1:18" },
        words: [["red", "rouge", "wouj"], ["blue", "bleu", "ble"], ["white", "blanc", "blan"], ["black", "noir", "nwa"],
                ["big", "grand", "gwo"], ["small", "petit", "piti"], ["new", "neuf", "nèf"], ["beautiful", "beau", "bèl"]],
        sentences: [["The car is red", "La voiture est rouge", "Machin nan wouj"],
                    ["I like the blue one", "J'aime le bleu", "Mwen renmen ble a"],
                    ["This house is very big", "Cette maison est très grande", "Kay sa a trè gwo"],
                    ["She has a beautiful dress", "Elle a une belle robe", "Li gen yon bèl wòb"],
                    ["I need a new phone", "J'ai besoin d'un nouveau téléphone", "Mwen bezwen yon nouvo telefòn"]] },
    ],
  },

  // ═══════════ A2 — ÉLÉMENTAIRE ═══════════
  {
    slug: "g-travail", cefr: "a2", color: "#2563eb", icon: "💼",
    fr: "Le travail", ht: "Travay la", sfr: "Parler de son métier", sht: "Pale de metye ou",
    themes: [
      { slug: "g-metier", fr: "Mon métier", ht: "Metye mwen", icon: "🧑‍🔧",
        verse: { en: "Whatsoever ye do, do it heartily, as to the Lord.", fr: "Tout ce que vous faites, faites-le de bon cœur, comme pour le Seigneur.", ref: "Colossians 3:23" },
        words: [["work", "travail", "travay"], ["job", "emploi", "djòb"], ["office", "bureau", "biwo"], ["boss", "patron", "patwon"],
                ["team", "équipe", "ekip"], ["meeting", "réunion", "reyinyon"], ["salary", "salaire", "salè"], ["busy", "occupé", "okipe"]],
        sentences: [["I work in an office", "Je travaille dans un bureau", "Mwen travay nan yon biwo"],
                    ["My team is very good", "Mon équipe est très bonne", "Ekip mwen an trè bon"],
                    ["The meeting starts at nine", "La réunion commence à neuf heures", "Reyinyon an kòmanse a nèvè"],
                    ["I am busy this morning", "Je suis occupé ce matin", "Mwen okipe maten an"],
                    ["He is looking for a job", "Il cherche un emploi", "L ap chèche yon djòb"]] },
      { slug: "g-telephone", fr: "Au téléphone", ht: "Nan telefòn", icon: "📞",
        verse: { en: "Call unto me, and I will answer thee.", fr: "Invoque-moi, et je te répondrai.", ref: "Jeremiah 33:3" },
        words: [["call", "appeler", "rele"], ["answer", "répondre", "reponn"], ["message", "message", "mesaj"], ["wait", "attendre", "tann"],
                ["speak", "parler", "pale"], ["later", "plus tard", "pita"], ["number", "numéro", "nimewo"], ["hear", "entendre", "tande"]],
        sentences: [["Can I speak to the manager", "Puis-je parler au responsable", "Èske m ka pale ak responsab la"],
                    ["Please wait a moment", "Veuillez patienter un instant", "Tanpri tann yon ti moman"],
                    ["I will call you later", "Je t'appellerai plus tard", "M ap rele ou pita"],
                    ["I cannot hear you well", "Je ne t'entends pas bien", "Mwen pa tande ou byen"],
                    ["Leave me a message please", "Laisse-moi un message s'il te plaît", "Kite m yon mesaj souple"]] },
      { slug: "g-banque", fr: "À la banque", ht: "Nan bank la", icon: "🏦",
        verse: { en: "The rich ruleth over the poor, and the borrower is servant to the lender.", fr: "Le riche domine sur le pauvre, et celui qui emprunte est l'esclave de celui qui prête.", ref: "Proverbs 22:7" },
        words: [["bank", "banque", "bank"], ["account", "compte", "kont"], ["card", "carte", "kat"], ["cash", "espèces", "kach"],
                ["save", "épargner", "ekonomize"], ["send", "envoyer", "voye"], ["receive", "recevoir", "resevwa"], ["sign", "signer", "siyen"]],
        sentences: [["I want to open an account", "Je veux ouvrir un compte", "Mwen vle louvri yon kont"],
                    ["Can I pay with my card", "Puis-je payer par carte", "Èske m ka peye ak kat mwen"],
                    ["I need to send money", "Je dois envoyer de l'argent", "Mwen bezwen voye lajan"],
                    ["Please sign here", "Signez ici s'il vous plaît", "Tanpri siyen isit la"],
                    ["I save a little every month", "J'épargne un peu chaque mois", "Mwen ekonomize yon ti kras chak mwa"]] },
    ],
  },
  {
    slug: "g-sante-urgence", cefr: "a2", color: "#dc2626", icon: "🏥",
    fr: "Santé et urgences", ht: "Sante ak ijans", sfr: "Se faire comprendre quand ça compte", sht: "Fè yo konprann ou lè sa enpòtan",
    themes: [
      { slug: "g-hopital", fr: "À l'hôpital", ht: "Nan lopital", icon: "🩺",
        verse: { en: "I am the Lord that healeth thee.", fr: "Je suis l'Éternel qui te guérit.", ref: "Exodus 15:26" },
        words: [["doctor", "médecin", "doktè"], ["nurse", "infirmière", "enfimyè"], ["pain", "douleur", "doulè"], ["sick", "malade", "malad"],
                ["medicine", "médicament", "medikaman"], ["head", "tête", "tèt"], ["stomach", "estomac", "vant"], ["help", "aide", "èd"]],
        sentences: [["I need a doctor", "J'ai besoin d'un médecin", "Mwen bezwen yon doktè"],
                    ["My head hurts", "J'ai mal à la tête", "Tèt mwen ap fè m mal"],
                    ["I feel sick today", "Je me sens malade aujourd'hui", "Mwen santi m malad jodi a"],
                    ["Where is the hospital", "Où est l'hôpital", "Kote lopital la ye"],
                    ["Please help me", "Aidez-moi s'il vous plaît", "Tanpri ede m"]] },
      { slug: "g-transport", fr: "Se déplacer", ht: "Deplase", icon: "🚌",
        verse: { en: "He shall give his angels charge over thee, to keep thee in all thy ways.", fr: "Il ordonnera à ses anges de te garder dans toutes tes voies.", ref: "Psalm 91:11" },
        words: [["bus", "bus", "bis"], ["car", "voiture", "machin"], ["street", "rue", "lari"], ["left", "gauche", "gòch"],
                ["right", "droite", "dwat"], ["far", "loin", "lwen"], ["near", "près", "toupre"], ["ticket", "billet", "tikè"]],
        sentences: [["Where is the bus station", "Où est la gare routière", "Kote estasyon bis la ye"],
                    ["Turn left at the corner", "Tourne à gauche au coin", "Vire agoch nan kwen an"],
                    ["Is it far from here", "Est-ce loin d'ici", "Èske li lwen isit la"],
                    ["I need one ticket please", "Il me faut un billet s'il vous plaît", "Mwen bezwen yon tikè souple"],
                    ["The airport is very near", "L'aéroport est tout près", "Ayewopò a toupre"]] },
      { slug: "g-voyage", fr: "En voyage", ht: "An vwayaj", icon: "✈️",
        verse: { en: "The Lord shall preserve thy going out and thy coming in.", fr: "L'Éternel gardera ton départ et ton arrivée.", ref: "Psalm 121:8" },
        words: [["travel", "voyager", "vwayaje"], ["airport", "aéroport", "ayewopò"], ["passport", "passeport", "paspò"], ["hotel", "hôtel", "otèl"],
                ["luggage", "bagage", "malèt"], ["arrive", "arriver", "rive"], ["leave", "partir", "pati"], ["visit", "visiter", "vizite"]],
        sentences: [["I am travelling to New York", "Je voyage à New York", "M ap vwayaje pou New York"],
                    ["Here is my passport", "Voici mon passeport", "Men paspò mwen"],
                    ["What time does the plane leave", "À quelle heure part l'avion", "Ki lè avyon an pati"],
                    ["I have two bags", "J'ai deux bagages", "Mwen gen de malèt"],
                    ["We arrive in the evening", "Nous arrivons le soir", "Nou rive nan aswè"]] },
    ],
  },

  // ═══════════ B1 — INTERMÉDIAIRE ═══════════
  {
    slug: "g-conversation", cefr: "b1", color: "#7c3aed", icon: "💬",
    fr: "Conversation courante", ht: "Konvèsasyon chak jou", sfr: "Exprimer ses idées", sht: "Esprime lide ou",
    themes: [
      { slug: "g-opinion", fr: "Donner son avis", ht: "Bay opinyon ou", icon: "🗨️",
        verse: { en: "Let your speech be alway with grace.", fr: "Que votre parole soit toujours accompagnée de grâce.", ref: "Colossians 4:6" },
        words: [["think", "penser", "panse"], ["agree", "être d'accord", "dakò"], ["because", "parce que", "paske"], ["maybe", "peut-être", "petèt"],
                ["important", "important", "enpòtan"], ["difficult", "difficile", "difisil"], ["easy", "facile", "fasil"], ["true", "vrai", "vre"]],
        sentences: [["I think it is a good idea", "Je pense que c'est une bonne idée", "Mwen panse se yon bon lide"],
                    ["I agree with you", "Je suis d'accord avec toi", "Mwen dakò ak ou"],
                    ["It is difficult but possible", "C'est difficile mais possible", "Li difisil men li posib"],
                    ["Maybe we can try tomorrow", "Peut-être qu'on peut essayer demain", "Petèt nou ka eseye demen"],
                    ["This is very important to me", "C'est très important pour moi", "Sa a trè enpòtan pou mwen"]] },
      { slug: "g-passe", fr: "Parler du passé", ht: "Pale de tan pase", icon: "⏳",
        verse: { en: "Remember the days of old.", fr: "Souviens-toi des jours d'autrefois.", ref: "Deuteronomy 32:7" },
        words: [["was", "était", "te ye"], ["went", "est allé", "te ale"], ["saw", "a vu", "te wè"], ["yesterday", "hier", "yè"],
                ["ago", "il y a", "gen"], ["began", "a commencé", "te kòmanse"], ["finished", "a terminé", "te fini"], ["remember", "se souvenir", "sonje"]],
        sentences: [["I went to church yesterday", "Je suis allé à l'église hier", "Mwen te ale legliz yè"],
                    ["She was very happy", "Elle était très heureuse", "Li te trè kontan"],
                    ["We finished the work last week", "Nous avons terminé le travail la semaine dernière", "Nou te fini travay la semèn pase"],
                    ["I saw him two days ago", "Je l'ai vu il y a deux jours", "Mwen te wè l gen de jou"],
                    ["I remember that day well", "Je me souviens bien de ce jour", "Mwen sonje jou sa a byen"]] },
      { slug: "g-futur", fr: "Parler du futur", ht: "Pale de tan k ap vini", icon: "🔮",
        verse: { en: "I know the thoughts that I think toward you, thoughts of peace.", fr: "Je connais les projets que j'ai formés sur vous, projets de paix.", ref: "Jeremiah 29:11" },
        words: [["will", "va", "pral"], ["plan", "projet", "plan"], ["hope", "espérer", "espere"], ["next", "prochain", "pwochen"],
                ["soon", "bientôt", "byento"], ["start", "commencer", "kòmanse"], ["change", "changer", "chanje"], ["future", "avenir", "avni"]],
        sentences: [["I will start next month", "Je commencerai le mois prochain", "M ap kòmanse mwa pwochen"],
                    ["We hope to see you soon", "Nous espérons te voir bientôt", "Nou espere wè ou byento"],
                    ["What are your plans", "Quels sont tes projets", "Ki plan ou yo"],
                    ["Things will change", "Les choses vont changer", "Bagay yo pral chanje"],
                    ["I am going to study English", "Je vais étudier l'anglais", "M pral etidye anglè"]] },
    ],
  },
  {
    slug: "g-technologie", cefr: "b1", color: "#0d9488", icon: "💻",
    fr: "Technologie et études", ht: "Teknoloji ak etid", sfr: "Le vocabulaire d'aujourd'hui", sht: "Vokabilè jodi a",
    themes: [
      { slug: "g-internet", fr: "Internet et téléphone", ht: "Entènèt ak telefòn", icon: "📱",
        verse: { en: "Thy word is a lamp unto my feet.", fr: "Ta parole est une lampe à mes pieds.", ref: "Psalm 119:105" },
        words: [["phone", "téléphone", "telefòn"], ["internet", "internet", "entènèt"], ["email", "courriel", "imel"], ["password", "mot de passe", "modpas"],
                ["download", "télécharger", "telechaje"], ["screen", "écran", "ekran"], ["online", "en ligne", "anliy"], ["share", "partager", "pataje"]],
        sentences: [["I sent you an email", "Je t'ai envoyé un courriel", "Mwen voye yon imel ba ou"],
                    ["My phone has no internet", "Mon téléphone n'a pas internet", "Telefòn mwen pa gen entènèt"],
                    ["Please share the link", "Partage le lien s'il te plaît", "Pataje lyen an souple"],
                    ["I forgot my password", "J'ai oublié mon mot de passe", "Mwen bliye modpas mwen"],
                    ["The class is online today", "Le cours est en ligne aujourd'hui", "Klas la anliy jodi a"]] },
      { slug: "g-ecole", fr: "À l'école", ht: "Nan lekòl", icon: "🎓",
        verse: { en: "Apply thine heart unto instruction.", fr: "Applique ton cœur à l'instruction.", ref: "Proverbs 23:12" },
        words: [["school", "école", "lekòl"], ["teacher", "enseignant", "pwofesè"], ["student", "élève", "elèv"], ["book", "livre", "liv"],
                ["learn", "apprendre", "aprann"], ["study", "étudier", "etidye"], ["exam", "examen", "egzamen"], ["homework", "devoirs", "devwa"]],
        sentences: [["I study English every day", "J'étudie l'anglais chaque jour", "Mwen etidye anglè chak jou"],
                    ["The teacher explains very well", "L'enseignant explique très bien", "Pwofesè a esplike trè byen"],
                    ["I have an exam next week", "J'ai un examen la semaine prochaine", "Mwen gen yon egzamen semèn pwochen"],
                    ["Please read this book", "Lis ce livre s'il te plaît", "Li liv sa a souple"],
                    ["I finished my homework", "J'ai terminé mes devoirs", "Mwen fini devwa m"]] },
      { slug: "g-affaires", fr: "Les affaires", ht: "Biznis", icon: "📈",
        verse: { en: "The plans of the diligent lead surely to plenty.", fr: "Les projets de l'homme diligent mènent à l'abondance.", ref: "Proverbs 21:5" },
        words: [["business", "affaires", "biznis"], ["customer", "client", "kliyan"], ["sell", "vendre", "vann"], ["profit", "bénéfice", "benefis"],
                ["contract", "contrat", "kontra"], ["market", "marché", "mache"], ["grow", "croître", "grandi"], ["service", "service", "sèvis"]],
        sentences: [["We sell our products online", "Nous vendons nos produits en ligne", "Nou vann pwodwi nou anliy"],
                    ["The customer is waiting", "Le client attend", "Kliyan an ap tann"],
                    ["Our business is growing", "Notre entreprise grandit", "Biznis nou an ap grandi"],
                    ["Please read the contract", "Lisez le contrat s'il vous plaît", "Tanpri li kontra a"],
                    ["We offer a good service", "Nous offrons un bon service", "Nou ofri yon bon sèvis"]] },
    ],
  },
];
