import type { Lang } from "./translations";
import type { Study } from "./studies-data";

interface TeachingMsg { num: number; title: Record<Lang, string>; ref: string; body: Record<Lang, string> }
interface Teaching { id: string; tag: Record<Lang, string>; title: Record<Lang, string>; desc: Record<Lang, string>; messages: TeachingMsg[] }

// Séries d'enseignement — intégrées à l'Académie comme parcours « Enseignements ».
export const teachings: Teaching[] = [
  {
    id: "nature-dieu",
    tag: { fr: "Doctrine", ht: "Doktrin", en: "Doctrine", es: "Doctrina" },
    title: { fr: "La Nature de Dieu", ht: "Nati Bondye a", en: "The Nature of God", es: "La Naturaleza de Dios" },
    desc: { fr: "Une série de messages sur la trinité, la sainteté et la souveraineté de Dieu.", ht: "Yon seri mesaj sou trinite, sentete ak souverènte Bondye.", en: "A series of messages on the Trinity, holiness and sovereignty of God.", es: "Una serie de mensajes sobre la trinidad, la santidad y la soberanía de Dios." },
    messages: [
      {
        num: 1,
        title: { fr: "Dieu existe — Les preuves de la Bible", ht: "Bondye egziste — Prèv nan Bib la", en: "God Exists — Evidence from the Bible", es: "Dios Existe — Las Pruebas de la Biblia" },
        ref: "Hébreux 11:6",
        body: {
          fr: "La foi chrétienne commence par une conviction fondamentale : Dieu existe et il récompense ceux qui le cherchent. Hébreux 11:6 nous dit qu'il est impossible de plaire à Dieu sans la foi. Mais cette foi n'est pas un saut dans l'obscurité — elle est ancrée dans les témoignages de la création, de l'histoire et de la Parole de Dieu.\n\nLa création elle-même est un témoignage puissant. Le Psaume 19:1 déclare : « Les cieux racontent la gloire de Dieu. » Partout où nous regardons — la complexité d'une cellule vivante, l'ordre de l'univers, la conscience humaine — nous voyons les empreintes d'un Créateur intelligent et personnel.\n\nMais au-delà de la création, c'est la Bible qui nous révèle qui est Dieu. Elle ne cherche pas à prouver son existence — elle l'affirme dès la première ligne : « Au commencement, Dieu créa les cieux et la terre. » (Genèse 1:1). Votre foi n'est pas une illusion. Elle est ancrée dans une réalité éternelle.",
          ht: "Lafwa kretyen kòmanse ak yon konviksyon fondamantal : Bondye egziste epi li rekonpanse moun ki chèche li. Ebre 11:6 di nou ke li enposib pou plezi Bondye san lafwa. Men lafwa sa a pa yon sot nan fènwa — li anchore nan temwanyaj kreyasyon, listwa ak Pawòl Bondye.\n\nKreyasyon li menm se yon temwayaj pwisan. Sòm 19:1 deklare : « Syèl yo ap pale glwa Bondye. » Toupatou nou gade — konpleksite yon selil vivan, lòd linivè a, konsyans imen — nou wè tras yon Kreyatè entèlijan ak pèsonèl.\n\nMen anplis kreyasyon, se Bib la ki reveye nou ki Bondye ye. Li pa chèche pwouve egzistans li — li afime li depi premye liy : « Nan kòmansman, Bondye kreye syèl la ak tè a. » (Jenèz 1:1). Lafwa ou pa yon ilizyon. Li anchore nan yon reyalite etènèl.",
          en: "Christian faith begins with a fundamental conviction: God exists and he rewards those who seek him. Hebrews 11:6 tells us it is impossible to please God without faith. But this faith is not a leap into the dark — it is anchored in the testimonies of creation, history and God's Word.\n\nCreation itself is a powerful testimony. Psalm 19:1 declares: 'The heavens declare the glory of God.' Everywhere we look — the complexity of a living cell, the order of the universe, human consciousness — we see the fingerprints of an intelligent, personal Creator.\n\nBut beyond creation, it is the Bible that reveals to us who God is. It does not try to prove his existence — it affirms it from the very first line: 'In the beginning, God created the heavens and the earth.' (Genesis 1:1). Your faith is not an illusion. It is anchored in an eternal reality.",
          es: "La fe cristiana comienza con una convicción fundamental: Dios existe y recompensa a quienes lo buscan. Hebreos 11:6 nos dice que es imposible agradar a Dios sin fe. Pero esta fe no es un salto hacia la oscuridad — está anclada en los testimonios de la creación, la historia y la Palabra de Dios.\n\nLa creación misma es un poderoso testimonio. El Salmo 19:1 declara: «Los cielos cuentan la gloria de Dios.» Dondequiera que miremos — la complejidad de una célula viva, el orden del universo, la conciencia humana — vemos las huellas de un Creador inteligente y personal.\n\nPero más allá de la creación, es la Biblia la que nos revela quién es Dios. No intenta probar su existencia — la afirma desde la primera línea: «En el principio, Dios creó los cielos y la tierra.» (Génesis 1:1). Tu fe no es una ilusión. Está anclada en una realidad eterna.",
        },
      },
      {
        num: 2,
        title: { fr: "La Trinité — Un seul Dieu en trois personnes", ht: "Trinite a — Yon sèl Bondye an twa pèsòn", en: "The Trinity — One God in Three Persons", es: "La Trinidad — Un Solo Dios en Tres Personas" },
        ref: "Matthieu 28:19",
        body: {
          fr: "La doctrine de la Trinité est l'une des plus profondes et des plus mal comprises de la foi chrétienne. Dieu est Un dans son essence, mais il existe en trois personnes distinctes : le Père, le Fils et le Saint-Esprit. Ce n'est pas trois dieux — c'est un seul Dieu qui se révèle en trois personnes.\n\nJésus lui-même nous a donné cette formule : « Allez, faites des disciples de toutes les nations, les baptisant au nom du Père, du Fils et du Saint-Esprit. » (Matthieu 28:19). Remarquez : il dit « au nom » (singulier), pas « aux noms » (pluriel). Un seul nom, trois personnes.\n\nCette vérité a des implications pratiques pour notre vie spirituelle. Nous prions au Père (Matthieu 6:9), par le Fils (Jean 14:6) et dans la puissance du Saint-Esprit (Éphésiens 6:18). La Trinité n'est pas un concept théologique abstrait — c'est la réalité dans laquelle nous vivons notre relation avec Dieu.",
          ht: "Doktrin Trinite a se youn nan pi pwofon ak pi mal konprann nan lafwa kretyen. Bondye Se Youn nan esans li, men li egziste an twa pèsòn disteng : Papa a, Pitit la ak Sentespri a. Se pa twa bondye — se yon sèl Bondye ki reveye li an twa pèsòn.\n\nJezi li menm ban nou fòmil sa a : « Al fè disip nan tout nasyon yo, batize yo nan non Papa a, Pitit la ak Sentespri a. » (Matye 28:19). Remake : li di « non » (sengile), pa « non yo » (pliryèl). Yon sèl non, twa pèsòn.\n\nVerite sa a gen enplikasyon pratik pou lavi espirityèl nou. Nou priye Papa a (Matye 6:9), atravè Pitit la (Jan 14:6) ak nan pisans Sentespri a (Efezyen 6:18). Trinite a pa yon konsèp teyolojik abstré — se reyalite nou viv relasyon nou ak Bondye ladan l.",
          en: "The doctrine of the Trinity is one of the most profound and misunderstood in the Christian faith. God is One in his essence, but he exists in three distinct persons: the Father, the Son and the Holy Spirit. This is not three gods — it is one God who reveals himself in three persons.\n\nJesus himself gave us this formula: 'Go, make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit.' (Matthew 28:19). Notice: he says 'in the name' (singular), not 'in the names' (plural). One name, three persons.\n\nThis truth has practical implications for our spiritual life. We pray to the Father (Matthew 6:9), through the Son (John 14:6) and in the power of the Holy Spirit (Ephesians 6:18). The Trinity is not an abstract theological concept — it is the reality in which we live our relationship with God.",
          es: "La doctrina de la Trinidad es una de las más profundas e incomprendidas de la fe cristiana. Dios es Uno en su esencia, pero existe en tres personas distintas: el Padre, el Hijo y el Espíritu Santo. No son tres dioses — es un solo Dios que se revela en tres personas.\n\nEl mismo Jesús nos dio esta fórmula: «Id y haced discípulos de todas las naciones, bautizándolos en el nombre del Padre, del Hijo y del Espíritu Santo.» (Mateo 28:19). Nótese: dice «en el nombre» (singular), no «en los nombres» (plural). Un solo nombre, tres personas.\n\nEsta verdad tiene implicaciones prácticas para nuestra vida espiritual. Oramos al Padre (Mateo 6:9), por el Hijo (Juan 14:6) y en el poder del Espíritu Santo (Efesios 6:18). La Trinidad no es un concepto teológico abstracto — es la realidad en la que vivimos nuestra relación con Dios.",
        },
      },
      {
        num: 3,
        title: { fr: "La Sainteté de Dieu", ht: "Sentete Bondye a", en: "The Holiness of God", es: "La Santidad de Dios" },
        ref: "Ésaïe 6:1-8",
        body: {
          fr: "Ésaïe chapitre 6 nous offre l'une des visions les plus saisissantes de Dieu dans toute la Bible. Le prophète voit le Seigneur assis sur un trône élevé. Les séraphins proclament : « Saint, saint, saint est l'Éternel des armées ; toute la terre est pleine de sa gloire. » (Ésaïe 6:3).\n\nPourquoi répètent-ils « saint » trois fois ? Dans l'hébreu, la répétition d'un mot était la façon d'exprimer le superlatif absolu. « Saint, saint, saint » signifie que la sainteté est l'attribut fondamental de Dieu — il est infiniment, absolument, totalement saint.\n\nFace à cette sainteté, Ésaïe s'écrie : « Malheur à moi ! car je suis perdu ; car je suis un homme dont les lèvres sont impures. » La sainteté de Dieu révèle notre péché. Mais voici la bonne nouvelle : Dieu purifie ceux qui reconnaissent leur état. Il envoya un ange avec une braise pour purifier les lèvres d'Ésaïe. C'est une image parfaite de la grâce.",
          ht: "Ezayi chapit 6 ofri nou youn nan vizyon ki pi frappan sou Bondye nan tout Bib la. Pwofèt la wè Seyè a chita sou yon twòn wo. Serafin yo pwoklaime : « Sen, sen, sen se Seyè a dè lame yo ; tout tè a plen glwa li. » (Ezayi 6:3).\n\nPoukisa yo repete « sen » twa fwa ? Nan Ebre, repetisyon yon mo se te fason eksprime sipèlatif absoli. « Sen, sen, sen » vle di ke sentete se atribi fondamantal Bondye — li enfiniman, absòliman, totalman sen.\n\nFas ak sentete sa a, Ezayi rele : « Malè pou mwen ! paske mwen pèdi ; paske mwen se yon nonm ki gen lèv sal. » Sentete Bondye revele peche nou. Men men bon nouvèl la : Bondye pirifye moun ki rekonèt eta yo. Li voye yon zanj ak yon chabon pou pirifye lèv Ezayi yo. Se yon imaj pafè gras.",
          en: "Isaiah chapter 6 offers us one of the most striking visions of God in all the Bible. The prophet sees the Lord seated on a high throne. The seraphim proclaim: 'Holy, holy, holy is the LORD of hosts; the whole earth is full of his glory.' (Isaiah 6:3).\n\nWhy do they repeat 'holy' three times? In Hebrew, the repetition of a word was the way to express the absolute superlative. 'Holy, holy, holy' means that holiness is the fundamental attribute of God — he is infinitely, absolutely, totally holy.\n\nFaced with this holiness, Isaiah cries out: 'Woe is me! For I am lost; for I am a man of unclean lips.' God's holiness reveals our sin. But here is the good news: God purifies those who acknowledge their condition. He sent an angel with a burning coal to purify Isaiah's lips. It is a perfect image of grace.",
          es: "Isaías capítulo 6 nos ofrece una de las visiones más impresionantes de Dios en toda la Biblia. El profeta ve al Señor sentado en un trono elevado. Los serafines proclaman: «Santo, santo, santo es el SEÑOR de los ejércitos; toda la tierra está llena de su gloria.» (Isaías 6:3).\n\n¿Por qué repiten «santo» tres veces? En hebreo, la repetición de una palabra era la manera de expresar el superlativo absoluto. «Santo, santo, santo» significa que la santidad es el atributo fundamental de Dios — Él es infinita, absoluta y totalmente santo.\n\nAnte esta santidad, Isaías exclama: «¡Ay de mí! porque soy perdido; porque soy hombre de labios impuros.» La santidad de Dios revela nuestro pecado. Pero aquí están las buenas noticias: Dios purifica a quienes reconocen su condición. Envió un ángel con una brasa para purificar los labios de Isaías. Es una imagen perfecta de la gracia.",
        },
      },
    ],
  },
  {
    id: "foi-quotidienne",
    tag: { fr: "Vie Chrétienne", ht: "Lavi Kretyen", en: "Christian Life", es: "Vida Cristiana" },
    title: { fr: "Vivre par la Foi", ht: "Viv pa Lafwa", en: "Living by Faith", es: "Vivir por la Fe" },
    desc: { fr: "Comment marcher par la foi dans les décisions quotidiennes et les temps d'incertitude.", ht: "Kijan pou mache pa lafwa nan desizyon chak jou ak nan moman enkertitid.", en: "How to walk by faith in daily decisions and times of uncertainty.", es: "Cómo caminar por la fe en las decisiones diarias y en tiempos de incertidumbre." },
    messages: [
      {
        num: 1,
        title: { fr: "La foi, qu'est-ce que c'est vraiment ?", ht: "Lafwa, kisa sa rèlman ye ?", en: "Faith — What Is It Really?", es: "La Fe — ¿Qué es Realmente?" },
        ref: "Hébreux 11:1",
        body: {
          fr: "« Or la foi, c'est la substance des choses qu'on espère, la démonstration de celles qu'on ne voit pas. » (Hébreux 11:1). Cette définition biblique de la foi est profonde. Ce n'est pas une simple croyance intellectuelle ou un sentiment émotionnel — c'est une certitude qui agit.\n\nHébreux 11 nous présente les grands héros de la foi : Abel, Noé, Abraham, Moïse... Chacun d'eux a agi en se basant sur ce que Dieu avait dit, même quand les circonstances semblaient impossibles. Abraham a quitté son pays sans savoir où il allait. Noé a construit une arche sans jamais avoir vu de pluie.\n\nLa foi véritable n'est pas l'absence de doute — c'est le choix d'agir sur la Parole de Dieu malgré le doute. Chaque jour, vous avez l'occasion d'exercer cette foi dans les petites décisions : choisir l'honnêteté quand le mensonge serait plus facile, pardonner quand la rancœur semble justifiée, espérer quand les circonstances disent le contraire.",
          ht: "« Men lafwa, se la sibstans bagay nou espere yo, se demonstrasyon bagay nou pa wè yo. » (Ebre 11:1). Definisyon biblik lafwa sa a pwofon. Se pa yon kwayans entelektyèl senp oswa yon santiman emosyonèl — se yon sètitid ki aji.\n\nEbre 11 prezante nou gran ewo lafwa yo : Abel, Noe, Abraham, Moyiz... Chak youn te aji sou sa Bondye te di a, menm lè sikonstans yo te sanble enposib. Abraham te kite peyi li san li pa te konnen ki kote li t ap ale. Noe te bati yon bato san li pa janm wè lapli.\n\nLafwa veritab pa absan dout — se chwa pou aji sou Pawòl Bondye malgre dout la. Chak jou, ou gen opòtinite pou egzèse lafwa sa a nan ti desizyon yo : chwazi onètete lè manti t ap pi fasil, padone lè rankin sanble jistifye, espere lè sikonstans yo di opoze.",
          en: "\"Now faith is the substance of things hoped for, the evidence of things not seen.\" (Hebrews 11:1). This biblical definition of faith is profound. It is not a simple intellectual belief or an emotional feeling — it is a certainty that acts.\n\nHebrews 11 presents the great heroes of faith: Abel, Noah, Abraham, Moses... Each of them acted based on what God had said, even when circumstances seemed impossible. Abraham left his country without knowing where he was going. Noah built an ark without ever having seen rain.\n\nTrue faith is not the absence of doubt — it is the choice to act on God's Word despite doubt. Every day, you have the opportunity to exercise this faith in small decisions: choosing honesty when lying would be easier, forgiving when resentment seems justified, hoping when circumstances say otherwise.",
          es: "«Es, pues, la fe la certeza de lo que se espera, la convicción de lo que no se ve.» (Hebreos 11:1). Esta definición bíblica de la fe es profunda. No es una simple creencia intelectual o un sentimiento emocional — es una certeza que actúa.\n\nHebreos 11 nos presenta a los grandes héroes de la fe: Abel, Noé, Abraham, Moisés... Cada uno de ellos actuó basándose en lo que Dios había dicho, incluso cuando las circunstancias parecían imposibles. Abraham dejó su tierra sin saber a dónde iba. Noé construyó un arca sin haber visto jamás la lluvia.\n\nLa fe verdadera no es la ausencia de duda — es la elección de actuar sobre la Palabra de Dios a pesar de la duda. Cada día tienes la oportunidad de ejercer esta fe en las pequeñas decisiones: elegir la honestidad cuando la mentira sería más fácil, perdonar cuando el resentimiento parece justificado, esperar cuando las circunstancias dicen lo contrario.",
        },
      },
      {
        num: 2,
        title: { fr: "Quand Dieu semble silencieux", ht: "Lè Bondye sanble silansye", en: "When God Seems Silent", es: "Cuando Dios Parece Silencioso" },
        ref: "Psaumes 22:1-2",
        body: {
          fr: "Le Psaume 22 commence par ces mots déchirants : « Mon Dieu, mon Dieu, pourquoi m'as-tu abandonné ? » Ce sont les mots que Jésus lui-même a crié sur la croix. Si le Fils de Dieu a ressenti l'absence de Dieu, nous ne devrions pas être surpris quand nous traversons des moments de sécheresse spirituelle.\n\nLe silence de Dieu n'est pas son absence. Dans les moments où Dieu semble lointain, plusieurs choses se passent : il teste notre foi pour la renforcer, il nous invite à le chercher plus profondément, ou il travaille en coulisses de façon que nous ne voyons pas encore.\n\nDavid, après avoir exprimé son désespoir dans les premiers versets du Psaume 22, arrive à cette confession : « Car il n'a pas méprisé ni dédaigné la souffrance du misérable. » (v. 24). La foi mature reconnaît que Dieu est fidèle même quand les émotions disent le contraire. Continuez à vous présenter devant lui — le silence finira.",
          ht: "Sòm 22 kòmanse ak mo sa yo kite nan kè : « Bondye mwen, Bondye mwen, poukisa ou abandone mwen ? » Se mo sa yo menm Jezi te rele sou kwa a. Si Pitit Bondye te santi absans Bondye, nou pa ta dwe sezi lè nou travèse moman sekrès espirityèl.\n\nSilans Bondye pa absans li. Nan moman kote Bondye sanble lwen, plizyè bagay ap pase : li ap teste lafwa nou pou ranfòse li, li envite nou chèche li pi fon, oswa li ap travay dèyè koulise yon fason nou pa wè ankò.\n\nDavid, apre l te eksprime dezespwa li nan premye vèsè Sòm 22 yo, rive nan konfesyon sa a : « Paske li pa meprize ni dedaye soufrans malere a. » (v. 24). Lafwa mi rekonèt ke Bondye fidèl menm lè emosyon yo di opoze. Kontinye prezante devan li — silans lan ap fini.",
          en: "Psalm 22 begins with these heartbreaking words: 'My God, my God, why have you forsaken me?' These are the words that Jesus himself cried out on the cross. If the Son of God felt the absence of God, we should not be surprised when we go through moments of spiritual dryness.\n\nGod's silence is not his absence. In moments when God seems distant, several things are happening: he is testing our faith to strengthen it, he is inviting us to seek him more deeply, or he is working behind the scenes in ways we cannot yet see.\n\nDavid, after expressing his despair in the first verses of Psalm 22, arrives at this confession: 'For he has not despised or scorned the suffering of the afflicted one.' (v. 24). Mature faith recognizes that God is faithful even when emotions say otherwise. Keep presenting yourself before him — the silence will end.",
          es: "El Salmo 22 comienza con estas palabras desgarradoras: «Dios mío, Dios mío, ¿por qué me has abandonado?» Estas son las palabras que el mismo Jesús clamó en la cruz. Si el Hijo de Dios sintió la ausencia de Dios, no debería sorprendernos cuando atravesamos momentos de sequía espiritual.\n\nEl silencio de Dios no es su ausencia. En los momentos en que Dios parece lejano, varias cosas están ocurriendo: está poniendo a prueba nuestra fe para fortalecerla, nos está invitando a buscarlo más profundamente, o está trabajando entre bastidores de maneras que aún no podemos ver.\n\nDavid, después de expresar su desesperación en los primeros versículos del Salmo 22, llega a esta confesión: «Porque no menospreció ni abominó la aflicción del afligido.» (v. 24). La fe madura reconoce que Dios es fiel incluso cuando las emociones dicen lo contrario. Continúa presentándote ante Él — el silencio terminará.",
        },
      },
    ],
  },
  {
    id: "ecole-priere",
    tag: { fr: "Prière", ht: "Lapriyè", en: "Prayer", es: "Oración" },
    title: { fr: "L'École de la Prière", ht: "Lekòl Lapriyè a", en: "School of Prayer", es: "La Escuela de la Oración" },
    desc: { fr: "Les fondements bibliques d'une vie de prière efficace et persévérante.", ht: "Fondasyon biblik yon lavi lapriyè ki efikas ak pèseveran.", en: "The biblical foundations of an effective and persevering prayer life.", es: "Los fundamentos bíblicos de una vida de oración eficaz y perseverante." },
    messages: [
      {
        num: 1,
        title: { fr: "Pourquoi prier si Dieu sait déjà tout ?", ht: "Poukisa priye si Bondye deja konnen tout bagay ?", en: "Why Pray If God Already Knows Everything?", es: "¿Por Qué Orar si Dios Ya Sabe Todo?" },
        ref: "Matthieu 6:8",
        body: {
          fr: "C'est l'une des questions les plus fréquentes : si Dieu connaît déjà nos besoins avant même que nous les exprimions (Matthieu 6:8), pourquoi prier ? La réponse révèle la nature profonde de la prière.\n\nLa prière n'est pas principalement un mécanisme pour changer les circonstances — c'est un moyen de cultiver une relation intime avec Dieu. Un père aime entendre son enfant lui parler, pas parce qu'il ne sait pas ce dont l'enfant a besoin, mais parce que la relation elle-même a de la valeur.\n\nJésus lui-même priait constamment, et il savait tout ! Il passait des nuits entières en prière (Luc 6:12). La prière était son oxygène. Pour nous aussi, la prière est le moyen par lequel nous alignons notre cœur avec la volonté de Dieu, nous renforçons notre foi, et nous participons à l'œuvre de Dieu dans le monde. Ne cherchez pas seulement des réponses dans la prière — cherchez le Dieu qui répond.",
          ht: "Se youn nan kesyon ki pi frekant yo : si Bondye deja konnen bezwen nou yo anvan nou menm eksprime yo (Matye 6:8), poukisa priye ? Repons lan reveye nati pwofon lapriyè.\n\nLapriyè pa prensipalman yon mekanis pou chanje sikonstans — se yon mwayen pou kiltivre yon relasyon entim ak Bondye. Yon papa renmen tande pitit li ap pale avèk li, pa paske li pa konnen sa pitit la bezwen, men paske relasyon an li menm gen valè.\n\nJezi li menm te priye konstan, epi li te konnen tout bagay ! Li te pase lannwit antye nan lapriyè (Lik 6:12). Lapriyè se te oksijèn li. Pou nou tou, lapriyè se mwayen nou aliye kè nou ak volonte Bondye, nou ranfòse lafwa nou, epi nou patisipe nan travay Bondye nan mond lan. Pa chèche sèlman repons nan lapriyè — chèche Bondye ki repon.",
          en: "This is one of the most common questions: if God already knows our needs before we even express them (Matthew 6:8), why pray? The answer reveals the deep nature of prayer.\n\nPrayer is not primarily a mechanism to change circumstances — it is a means of cultivating an intimate relationship with God. A father loves to hear his child talk to him, not because he does not know what the child needs, but because the relationship itself has value.\n\nJesus himself prayed constantly, and he knew everything! He spent entire nights in prayer (Luke 6:12). Prayer was his oxygen. For us too, prayer is the means by which we align our hearts with God's will, strengthen our faith, and participate in God's work in the world. Do not only look for answers in prayer — look for the God who answers.",
          es: "Esta es una de las preguntas más frecuentes: si Dios ya conoce nuestras necesidades antes de que las expresemos (Mateo 6:8), ¿por qué orar? La respuesta revela la naturaleza profunda de la oración.\n\nLa oración no es principalmente un mecanismo para cambiar las circunstancias — es un medio para cultivar una relación íntima con Dios. Un padre ama escuchar a su hijo hablar con él, no porque no sepa lo que el hijo necesita, sino porque la relación en sí misma tiene valor.\n\nEl mismo Jesús oraba constantemente, ¡y lo sabía todo! Pasaba noches enteras en oración (Lucas 6:12). La oración era su oxígeno. Para nosotros también, la oración es el medio por el cual alineamos nuestro corazón con la voluntad de Dios, fortalecemos nuestra fe y participamos en la obra de Dios en el mundo. No busques solo respuestas en la oración — busca al Dios que responde.",
        },
      },
    ],
  },
  {
    id: "message-croix",
    tag: { fr: "Évangile", ht: "Levanjil", en: "Gospel", es: "Evangelio" },
    title: { fr: "Le Message de la Croix", ht: "Mesaj Kwa a", en: "The Message of the Cross", es: "El Mensaje de la Cruz" },
    desc: { fr: "Pourquoi la crucifixion est le centre de toute la théologie chrétienne.", ht: "Poukisa krisifiksyon an se sant tout teyoloji kretyen.", en: "Why the crucifixion is the center of all Christian theology.", es: "Por qué la crucifixión es el centro de toda la teología cristiana." },
    messages: [
      {
        num: 1,
        title: { fr: "La croix — scandale ou sagesse ?", ht: "Kwa a — skandal oswa sajès ?", en: "The Cross — Scandal or Wisdom?", es: "La Cruz — ¿Escándalo o Sabiduría?" },
        ref: "1 Corinthiens 1:18",
        body: {
          fr: "« Car la prédication de la croix est une folie pour ceux qui périssent ; mais pour nous qui sommes sauvés, elle est une puissance de Dieu. » (1 Corinthiens 1:18). Paul écrit ces mots dans un contexte où la croix était le symbole de la honte — une mort réservée aux criminels.\n\nLes Juifs demandaient des signes miraculeux. Les Grecs cherchaient la sagesse philosophique. Et Paul leur prêche un Messie crucifié — ce qui était un scandale pour les uns et une folie pour les autres. Pourtant c'est précisément là que réside la puissance de Dieu.\n\nPourquoi la croix ? Parce que le péché exige une peine, et la justice de Dieu ne peut être ignorée. Mais la grâce de Dieu a trouvé un moyen : Jésus, le parfait, a pris notre place. Il a subi la peine que nous méritions. La croix n'est pas un accident de l'histoire — c'est le plan éternel de Dieu pour réconcilier l'humanité avec lui-même.",
          ht: "« Paske pawòl kwa a se yon foli pou moun ki pèdi yo ; men pou nou menm ki sove yo, se yon pisans Bondye. » (1 Korentyen 1:18). Pòl ekri mo sa yo nan yon kontèks kote kwa a te senbòl wont — yon lanmò rezève pou kriminèl.\n\nJuif yo t ap mande siy mirakile. Grèk yo t ap chèche sajès filozofik. Epi Pòl preche yo yon Mesi krisifye — sa ki te yon skandal pou youn ak yon foli pou lòt. Sepandan se presisman la pisans Bondye chita.\n\nPoukisa kwa a ? Paske peche a mande yon penalite, epi jistis Bondye pa ka inyore. Men gras Bondye a jwenn yon mwayen : Jezi, ki pafè, te pran plas nou. Li sibi penalite nou te merite a. Kwa a pa yon aksidan listwa — se plan etènèl Bondye pou rekonsilye limanite ak li menm.",
          en: "\"For the word of the cross is folly to those who are perishing, but to us who are being saved it is the power of God.\" (1 Corinthians 1:18). Paul writes these words in a context where the cross was a symbol of shame — a death reserved for criminals.\n\nThe Jews were demanding miraculous signs. The Greeks were seeking philosophical wisdom. And Paul preaches to them a crucified Messiah — which was a scandal to some and folly to others. Yet it is precisely there that the power of God resides.\n\nWhy the cross? Because sin demands a penalty, and God's justice cannot be ignored. But God's grace found a way: Jesus, the perfect one, took our place. He bore the penalty we deserved. The cross is not an accident of history — it is God's eternal plan to reconcile humanity with himself.",
          es: "«Porque la palabra de la cruz es locura para los que se pierden; pero para los que se salvan, esto es, para nosotros, es poder de Dios.» (1 Corintios 1:18). Pablo escribe estas palabras en un contexto donde la cruz era símbolo de vergüenza — una muerte reservada para los criminales.\n\nLos judíos pedían señales milagrosas. Los griegos buscaban sabiduría filosófica. Y Pablo les predicaba a un Mesías crucificado — lo cual era escándalo para unos y locura para otros. Sin embargo, es precisamente allí donde reside el poder de Dios.\n\n¿Por qué la cruz? Porque el pecado exige una pena, y la justicia de Dios no puede ser ignorada. Pero la gracia de Dios encontró un camino: Jesús, el perfecto, tomó nuestro lugar. Él sufrió la pena que merecíamos. La cruz no es un accidente de la historia — es el plan eterno de Dios para reconciliar a la humanidad consigo mismo.",
        },
      },
    ],
  },
];

// Couleur (dégradé Tailwind) + icône sémantique par série.
const META: Record<string, { color: string; icon: string }> = {
  "nature-dieu":     { color: "from-cyan-500 to-blue-600",   icon: "couronne" },
  "foi-quotidienne": { color: "from-amber-500 to-yellow-600", icon: "foi" },
  "ecole-priere":    { color: "from-violet-500 to-purple-600", icon: "priere" },
  "message-croix":   { color: "from-red-500 to-rose-600",     icon: "croix" },
};

/** Séries d'enseignement converties en études de l'Académie (parcours « enseignements »). */
export const teachingStudies: Study[] = teachings.map((t) => ({
  slug: t.id,
  parcours: "enseignements",
  title: t.title,
  description: t.desc,
  icon: "",
  color: META[t.id]?.color ?? "from-cyan-500 to-blue-600",
  duration: `${t.messages.length * 6} min`,
  difficulty: { fr: "Intermédiaire", ht: "Entèmedyè", en: "Intermediate", es: "Intermedio" },
  youtubeId: "",
  sections: t.messages.map((m) => ({ title: m.title, content: m.body, verse: m.ref })),
  keyVerses: t.messages.map((m) => m.ref),
}));

/** Icône sémantique par série (pour STUDY_ICONS). */
export const teachingIcons: Record<string, string> = Object.fromEntries(
  Object.entries(META).map(([k, v]) => [k, v.icon]),
);
