import { CourseContent } from "./types";

const canva: CourseContent = {
  slug: "canva",
  intro: {
    fr: "Apprendre à créer des visuels professionnels avec Canva, même sans être graphiste : affiches, publications, logos et documents, directement depuis un navigateur ou ton téléphone.",
    ht: "Aprann kreye vizyèl pwofesyonèl ak Canva, menm si ou pa yon grafik : afich, piblikasyon, logo ak dokiman, dirèkteman depi yon navigatè oswa telefòn ou.",
    en: "Learn to create professional visuals with Canva, even without being a designer: posters, posts, logos and documents, right from a browser or your phone.",
    es: "Aprender a crear diseños profesionales con Canva, aunque no seas diseñador: carteles, publicaciones, logos y documentos, directamente desde un navegador o tu teléfono.",
  },
  modules: [
    {
      title: { fr: "Débuter avec Canva", ht: "Kòmanse ak Canva", en: "Getting started with Canva", es: "Empezar con Canva" },
      lessons: [
        {
          slug: "creer-son-compte",
          title: { fr: "Créer son compte et découvrir l'interface", ht: "Kreye kont ou epi dekouvri entèfas la", en: "Create your account and explore the interface", es: "Crear tu cuenta y descubrir la interfaz" },
          videoId: "",
          content: {
            fr: "Rends-toi sur canva.com ou installe l'application mobile, puis inscris-toi gratuitement avec ton adresse e-mail, ton compte Google ou Facebook. La version gratuite suffit largement pour débuter : tu accèdes à des milliers de modèles, de photos et de polices sans payer.\n\nUne fois connecté, l'écran d'accueil te propose une barre de recherche en haut. Tape ce que tu veux créer, par exemple « affiche », « logo » ou « publication Instagram ». Canva te montre alors des formats déjà aux bonnes dimensions. À gauche se trouve ton menu (Projets, Modèles, Éléments) et à droite ton espace de travail.\n\nPrends cinq minutes pour cliquer partout sans crainte : rien ne se casse. Crée un premier « design vierge » pour t'entraîner à déplacer un texte, une forme ou une image. C'est en manipulant que tu apprends le plus vite.",
            ht: "Ale sou canva.com oswa enstale aplikasyon mobil la, epi enskri gratis ak adrès imel ou, kont Google oswa Facebook ou. Vèsyon gratis la kont pou kòmanse : ou jwenn dè milye modèl, foto ak polis san peye.\n\nLè ou konekte, paj akèy la gen yon bar rechèch anlè. Tape sa ou vle kreye, pa egzanp « afich », « logo » oswa « piblikasyon Instagram ». Canva ap montre ou fòma ki deja gen bon dimansyon yo. Sou gòch ou gen meni ou (Pwojè, Modèl, Eleman) epi sou dwat espas travay ou.\n\nPran senk minit pou klike toupatou san pè : anyen pa kase. Kreye yon premye « design vid » pou pratike deplase yon tèks, yon fòm oswa yon imaj. Se lè ou manyen li ou aprann pi vit.",
            en: "Go to canva.com or install the mobile app, then sign up for free with your email address, Google or Facebook account. The free version is plenty to get started: you get thousands of templates, photos and fonts at no cost.\n\nOnce logged in, the home screen has a search bar at the top. Type what you want to make, such as \"poster\", \"logo\" or \"Instagram post\". Canva then shows you formats already in the right size. On the left is your menu (Projects, Templates, Elements) and on the right your workspace.\n\nSpend five minutes clicking everywhere without fear: nothing breaks. Create a first \"blank design\" to practise moving a text box, a shape or an image. You learn fastest by doing.",
            es: "Entra en canva.com o instala la aplicación móvil, y regístrate gratis con tu correo, tu cuenta de Google o Facebook. La versión gratuita basta de sobra para empezar: tienes miles de plantillas, fotos y fuentes sin pagar.\n\nUna vez dentro, la pantalla de inicio tiene una barra de búsqueda arriba. Escribe lo que quieres crear, por ejemplo «cartel», «logo» o «publicación de Instagram». Canva te muestra formatos ya con las medidas correctas. A la izquierda está tu menú (Proyectos, Plantillas, Elementos) y a la derecha tu espacio de trabajo.\n\nDedica cinco minutos a hacer clic por todas partes sin miedo: nada se rompe. Crea un primer «diseño en blanco» para practicar mover un texto, una forma o una imagen. Se aprende más rápido manipulando.",
          },
          keyPoints: {
            fr: ["S'inscrire gratuitement sur canva.com ou l'appli", "La barre de recherche donne le bon format", "Explorer sans peur : rien ne se casse", "Créer un design vierge pour s'entraîner à déplacer les éléments"],
            ht: ["Enskri gratis sou canva.com oswa aplikasyon an", "Bar rechèch la bay bon fòma a", "Eksplore san pè : anyen pa kase", "Kreye yon design vid pou pratike deplase eleman yo"],
            en: ["Sign up for free at canva.com or the app", "The search bar gives the right format", "Explore fearlessly: nothing breaks", "Create a blank design to practise moving elements"],
            es: ["Registrarse gratis en canva.com o la app", "La barra de búsqueda da el formato correcto", "Explorar sin miedo: nada se rompe", "Crear un diseño en blanco para practicar mover elementos"],
          },
          exercise: {
            fr: "Crée ton compte Canva gratuit, puis ouvre un « design vierge ». Ajoute un texte, une forme et une image, et entraîne-toi à les déplacer, agrandir et faire pivoter. Explore les menus de gauche (Modèles, Éléments, Téléchargements) pendant cinq minutes.",
            ht: "Kreye kont Canva gratis ou, epi louvri yon « design vid ». Ajoute yon tèks, yon fòm ak yon imaj, epi pratike deplase yo, agrandi yo ak vire yo. Eksplore meni gòch yo (Modèl, Eleman, Telechajman) pandan senk minit.",
            en: "Create your free Canva account, then open a \"blank design\". Add a text, a shape and an image, and practise moving, enlarging and rotating them. Explore the left menus (Templates, Elements, Uploads) for five minutes.",
            es: "Crea tu cuenta gratuita de Canva y abre un «diseño en blanco». Añade un texto, una forma y una imagen, y practica moverlos, agrandarlos y girarlos. Explora los menús de la izquierda (Plantillas, Elementos, Subidas) durante cinco minutos.",
          },
        },
        {
          slug: "utiliser-modeles",
          title: { fr: "Utiliser les modèles pour aller plus vite", ht: "Sèvi ak modèl pou ale pi vit", en: "Using templates to work faster", es: "Usar plantillas para ir más rápido" },
          videoId: "",
          content: {
            fr: "Le secret de Canva, ce sont les modèles : des designs déjà terminés que tu n'as plus qu'à personnaliser. Plutôt que partir d'une page blanche, cherche un modèle proche de ton besoin, clique dessus, et il s'applique à ton projet.\n\nEnsuite, tu remplaces simplement les éléments : clique sur un texte pour écrire le tien, clique sur une image pour la changer, ajuste les couleurs. Tout reste modifiable. Astuce : garde la mise en page qui fonctionne déjà et change seulement le contenu — c'est ainsi qu'on obtient un résultat propre rapidement.\n\nPar exemple, pour annoncer un événement d'église, tape « flyer événement », choisis un modèle, mets ta date, ton lieu et ta photo. En dix minutes tu as une affiche prête à partager. Note que certains modèles portent une couronne : ils sont réservés à la version payante, mais des milliers sont gratuits.",
            ht: "Sekrè Canva a se modèl yo : design ki deja fini ou sèlman bezwen pèsonalize. Olye pou kòmanse ak yon paj vid, chèche yon modèl ki pre bezwen ou, klike sou li, epi li aplike nan pwojè ou.\n\nApre sa, ou senpleman ranplase eleman yo : klike sou yon tèks pou ekri pa ou, klike sou yon imaj pou chanje l, ajiste koulè yo. Tout bagay ka modifye. Konsèy : kenbe estrikti ki deja mache a epi chanje sèlman kontni an — se konsa ou jwenn yon bon rezilta rapidman.\n\nPa egzanp, pou anonse yon aktivite legliz, tape « flyer aktivite », chwazi yon modèl, mete dat, kote ak foto ou. Nan dis minit ou gen yon afich pare pou pataje. Note kèk modèl gen yon kouwòn : yo rezève pou vèsyon peye a, men dè milye gratis.",
            en: "The secret of Canva is templates: finished designs you only need to personalise. Instead of starting from a blank page, search for a template close to your need, click it, and it applies to your project.\n\nThen you simply swap the elements: click a text to type your own, click an image to change it, adjust the colours. Everything stays editable. Tip: keep the layout that already works and change only the content — that is how you get a clean result quickly.\n\nFor example, to announce a church event, type \"event flyer\", pick a template, add your date, place and photo. In ten minutes you have a poster ready to share. Note that some templates carry a crown: those are reserved for the paid version, but thousands are free.",
            es: "El secreto de Canva son las plantillas: diseños ya terminados que solo tienes que personalizar. En lugar de empezar de una página en blanco, busca una plantilla cercana a lo que necesitas, haz clic y se aplica a tu proyecto.\n\nLuego solo cambias los elementos: haz clic en un texto para escribir el tuyo, en una imagen para cambiarla, ajusta los colores. Todo sigue siendo editable. Consejo: conserva la disposición que ya funciona y cambia solo el contenido — así logras un resultado limpio rápidamente.\n\nPor ejemplo, para anunciar un evento de iglesia, escribe «folleto evento», elige una plantilla, pon tu fecha, lugar y foto. En diez minutos tienes un cartel listo para compartir. Algunas plantillas llevan una corona: son de la versión de pago, pero miles son gratuitas.",
          },
          keyPoints: {
            fr: ["Partir d'un modèle plutôt que d'une page blanche", "Garder la mise en page, changer le contenu", "La couronne = payant, tout le reste est gratuit", "Personnaliser textes, images et couleurs sans casser la structure"],
            ht: ["Kòmanse ak yon modèl olye yon paj vid", "Kenbe estrikti a, chanje kontni an", "Kouwòn = peye, tout rès la gratis", "Pèsonalize tèks, imaj ak koulè san kase estrikti a"],
            en: ["Start from a template, not a blank page", "Keep the layout, change the content", "Crown = paid, everything else is free", "Personalise text, images and colours without breaking the structure"],
            es: ["Empezar de una plantilla, no de una página en blanco", "Conservar la disposición, cambiar el contenido", "La corona = de pago, lo demás es gratis", "Personalizar textos, imágenes y colores sin romper la estructura"],
          },
          exercise: {
            fr: "Cherche « flyer événement », choisis un modèle gratuit, et crée l'annonce d'un vrai événement (culte, réunion, anniversaire) : change le titre, la date, le lieu et une image. Objectif : une affiche prête en dix minutes.",
            ht: "Chèche « flyer aktivite », chwazi yon modèl gratis, epi kreye anons yon vrè aktivite (kilt, reyinyon, anivèsè) : chanje tit la, dat la, kote a ak yon imaj. Objektif : yon afich pare nan dis minit.",
            en: "Search \"event flyer\", pick a free template, and create the announcement for a real event (service, meeting, birthday): change the title, date, place and one image. Goal: a poster ready in ten minutes.",
            es: "Busca «folleto evento», elige una plantilla gratuita, y crea el anuncio de un evento real (culto, reunión, cumpleaños): cambia el título, la fecha, el lugar y una imagen. Objetivo: un cartel listo en diez minutos.",
          },
        },
        {
          slug: "formats-et-dimensions",
          title: { fr: "Choisir le bon format et redimensionner", ht: "Chwazi bon fòma a epi redimansyone", en: "Choosing the right size and resizing", es: "Elegir el formato correcto y redimensionar" },
          videoId: "",
          content: {
            fr: "Avant de créer, choisis le bon format. Une publication Instagram est carrée (1080×1080 px), une story est verticale (1080×1920), une affiche A4 est en portrait, une bannière Facebook est très large. Si tu pars du mauvais format, ton design sera coupé ou déformé au moment de le publier. Tape le nom du support dans la recherche de Canva et il te propose la bonne taille automatiquement.\n\nTu peux aussi définir des dimensions sur mesure. Depuis l'accueil, clique sur « Créer un design » puis « Taille personnalisée », et entre la largeur et la hauteur en pixels, centimètres ou millimètres. Utilise les pixels pour l'écran et les centimètres ou millimètres pour l'impression.\n\nUn même visuel sert souvent sur plusieurs supports. L'outil « Redimensionner » (bouton en haut, version payante) transforme ton design carré en story verticale en un clic. Sans la version payante, tu peux recréer le design dans le nouveau format en copiant-collant les éléments.\n\nPense à la « zone de sécurité » : garde le texte important loin des bords, car il peut être rogné selon l'écran ou l'imprimante. Pour l'impression, prévois quelques millimètres de marge (fond perdu) pour éviter un liseré blanc.",
            ht: "Anvan ou kreye, chwazi bon fòma a. Yon piblikasyon Instagram kare (1080×1080 px), yon story vètikal (1080×1920), yon afich A4 an pòtrè, yon banyè Facebook byen laj. Si ou pati ak move fòma a, design ou ap koupe oswa defòme lè ou pral pibliye l. Tape non sipò a nan rechèch Canva epi li pwopoze ou bon gwosè a otomatikman.\n\nOu ka defini dimansyon pa ou tou. Depi paj akèy la, klike sou « Kreye yon design » epi « Gwosè pèsonalize », epi antre lajè ak wotè a an piksèl, santimèt oswa milimèt. Sèvi ak piksèl pou ekran epi santimèt oswa milimèt pou enprime.\n\nMenm vizyèl la souvan sèvi sou plizyè sipò. Zouti « Redimansyone » (bouton anlè, vèsyon peye) transfòme design kare ou an story vètikal ak yon sèl klik. San vèsyon peye a, ou ka refè design lan nan nouvo fòma a lè ou kopye-kole eleman yo.\n\nPanse ak « zòn sekirite » a : kenbe tèks enpòtan an lwen bò yo, paske li ka koupe selon ekran oswa enprimant. Pou enprime, prevwa kèk milimèt maj (fon pèdi) pou evite yon liy blan.",
            en: "Before you create, pick the right size. An Instagram post is square (1080×1080 px), a story is vertical (1080×1920), an A4 poster is portrait, a Facebook banner is very wide. If you start in the wrong size, your design will be cropped or distorted when you publish it. Type the medium's name in Canva's search and it offers the right size automatically.\n\nYou can also set custom dimensions. From the home page, click \"Create a design\" then \"Custom size\", and enter the width and height in pixels, centimetres or millimetres. Use pixels for screen and centimetres or millimetres for print.\n\nThe same visual often serves several channels. The \"Resize\" tool (top button, paid version) turns your square design into a vertical story in one click. Without the paid version, you can rebuild the design in the new size by copying and pasting the elements.\n\nThink about the \"safe zone\": keep important text away from the edges, as it can be trimmed depending on the screen or printer. For print, allow a few millimetres of margin (bleed) to avoid a white line.",
            es: "Antes de crear, elige el formato correcto. Una publicación de Instagram es cuadrada (1080×1080 px), una historia es vertical (1080×1920), un cartel A4 es vertical, un banner de Facebook es muy ancho. Si empiezas con el formato equivocado, tu diseño se recortará o deformará al publicarlo. Escribe el nombre del soporte en la búsqueda de Canva y te ofrece el tamaño correcto automáticamente.\n\nTambién puedes definir medidas personalizadas. Desde el inicio, haz clic en «Crear un diseño» y luego «Tamaño personalizado», e introduce el ancho y el alto en píxeles, centímetros o milímetros. Usa píxeles para pantalla y centímetros o milímetros para impresión.\n\nUn mismo visual sirve a menudo para varios soportes. La herramienta «Redimensionar» (botón arriba, versión de pago) convierte tu diseño cuadrado en una historia vertical con un clic. Sin la versión de pago, puedes rehacer el diseño en el nuevo formato copiando y pegando los elementos.\n\nPiensa en la «zona segura»: mantén el texto importante lejos de los bordes, ya que puede recortarse según la pantalla o la impresora. Para imprimir, deja unos milímetros de margen (sangrado) para evitar una línea blanca.",
          },
          keyPoints: {
            fr: ["Choisir le format avant de créer (carré, story, A4...)", "Taille personnalisée en px pour l'écran, cm/mm pour l'impression", "« Redimensionner » adapte un design à un autre support", "Garder le texte loin des bords (zone de sécurité)"],
            ht: ["Chwazi fòma a anvan ou kreye (kare, story, A4...)", "Gwosè pèsonalize an px pou ekran, cm/mm pou enprime", "« Redimansyone » adapte yon design pou yon lòt sipò", "Kenbe tèks la lwen bò yo (zòn sekirite)"],
            en: ["Choose the size before creating (square, story, A4...)", "Custom size in px for screen, cm/mm for print", "\"Resize\" adapts a design to another channel", "Keep text away from the edges (safe zone)"],
            es: ["Elegir el formato antes de crear (cuadrado, historia, A4...)", "Tamaño personalizado en px para pantalla, cm/mm para imprimir", "«Redimensionar» adapta un diseño a otro soporte", "Mantener el texto lejos de los bordes (zona segura)"],
          },
          exercise: {
            fr: "Crée le même message dans deux formats : une publication carrée (1080×1080) et une story verticale (1080×1920). Observe comment tu dois déplacer le texte et l'image pour que chaque format reste équilibré.",
            ht: "Kreye menm mesaj la nan de fòma : yon piblikasyon kare (1080×1080) ak yon story vètikal (1080×1920). Gade kijan ou dwe deplase tèks ak imaj la pou chak fòma rete ekilibre.",
            en: "Create the same message in two sizes: a square post (1080×1080) and a vertical story (1080×1920). Notice how you must move the text and image so each format stays balanced.",
            es: "Crea el mismo mensaje en dos formatos: una publicación cuadrada (1080×1080) y una historia vertical (1080×1920). Observa cómo debes mover el texto y la imagen para que cada formato quede equilibrado.",
          },
        },
      ],
    },
    {
      title: { fr: "Textes, images et couleurs", ht: "Tèks, imaj ak koulè", en: "Text, images and colours", es: "Textos, imágenes y colores" },
      lessons: [
        {
          slug: "texte-et-polices",
          title: { fr: "Ajouter et soigner le texte", ht: "Ajoute epi swaye tèks la", en: "Adding and refining text", es: "Añadir y cuidar el texto" },
          videoId: "",
          content: {
            fr: "Pour ajouter du texte, clique sur « Texte » dans le menu de gauche, puis choisis « Ajouter un titre » ou une combinaison de polices déjà stylée. Un cadre apparaît : double-clique dedans pour écrire. Tu peux le déplacer, l'agrandir en tirant les coins, ou le faire pivoter.\n\nEn haut de l'écran, la barre d'outils te permet de changer la police, la taille, la couleur, et d'aligner le texte. Règle d'or : ne mets pas plus de deux ou trois polices différentes dans un même design, sinon cela devient brouillon. Utilise une police forte pour le titre et une police simple et lisible pour le reste.\n\nPour qu'un texte reste lisible sur une photo, ajoute un fond derrière lui ou assombris l'image. Pense aussi à la hiérarchie : le message le plus important doit être le plus gros. Un lecteur doit comprendre l'essentiel en une seconde.",
            ht: "Pou ajoute tèks, klike sou « Tèks » nan meni gòch la, epi chwazi « Ajoute yon tit » oswa yon konbinezon polis ki deja gen estil. Yon kad parèt : double-klike ladan l pou ekri. Ou ka deplase l, agrandi l lè ou rale kwen yo, oswa vire l.\n\nAnlè ekran an, bar zouti a pèmèt ou chanje polis, gwosè, koulè, epi aliyen tèks la. Règ dò : pa mete plis pase de oswa twa polis diferan nan menm design lan, sinon li vin dezòd. Sèvi ak yon polis fò pou tit la epi yon polis senp ki lizib pou rès la.\n\nPou yon tèks rete lizib sou yon foto, ajoute yon fon dèyè l oswa fè imaj la vin pi fonse. Panse tou ak yerachi : mesaj ki pi enpòtan an dwe pi gwo a. Yon lektè dwe konprann esansyèl la nan yon segonn.",
            en: "To add text, click \"Text\" in the left menu, then choose \"Add a heading\" or a ready-styled font combination. A box appears: double-click inside to type. You can move it, enlarge it by dragging the corners, or rotate it.\n\nAt the top of the screen, the toolbar lets you change the font, size, colour, and align the text. Golden rule: don't use more than two or three different fonts in one design, or it looks messy. Use a strong font for the title and a simple, readable one for the rest.\n\nTo keep text readable over a photo, add a background behind it or darken the image. Think about hierarchy too: the most important message should be the biggest. A reader should grasp the key point in one second.",
            es: "Para añadir texto, haz clic en «Texto» en el menú izquierdo, y elige «Añadir un título» o una combinación de fuentes ya estilizada. Aparece un cuadro: haz doble clic dentro para escribir. Puedes moverlo, agrandarlo tirando de las esquinas o girarlo.\n\nEn la parte superior, la barra de herramientas te deja cambiar la fuente, el tamaño, el color y alinear el texto. Regla de oro: no uses más de dos o tres fuentes distintas en un mismo diseño, o quedará desordenado. Usa una fuente fuerte para el título y una simple y legible para el resto.\n\nPara que un texto siga legible sobre una foto, añade un fondo detrás o oscurece la imagen. Piensa también en la jerarquía: el mensaje más importante debe ser el más grande. El lector debe entender lo esencial en un segundo.",
          },
          keyPoints: {
            fr: ["Double-cliquer dans le cadre pour écrire", "Maximum deux ou trois polices par design", "Le message clé = le texte le plus gros", "Rendre le texte lisible sur une photo (fond ou image assombrie)"],
            ht: ["Double-klike nan kad la pou ekri", "Maksimòm de oswa twa polis pa design", "Mesaj kle a = tèks ki pi gwo a", "Fè tèks la lizib sou yon foto (fon oswa imaj ki pi fonse)"],
            en: ["Double-click the box to type", "At most two or three fonts per design", "The key message = the biggest text", "Make text readable over a photo (background or darkened image)"],
            es: ["Doble clic en el cuadro para escribir", "Máximo dos o tres fuentes por diseño", "El mensaje clave = el texto más grande", "Hacer el texto legible sobre una foto (fondo o imagen oscurecida)"],
          },
          exercise: {
            fr: "Reprends ton affiche et travaille le texte : mets un titre en gros avec une police forte, ajoute un sous-titre lisible, et limite-toi à deux polices. Place le texte sur une photo et rends-le lisible en assombrissant l'image ou en ajoutant un fond.",
            ht: "Reprann afich ou epi travay tèks la : mete yon tit an gwo ak yon polis fò, ajoute yon soutit lizib, epi limite ou ak de polis. Mete tèks la sou yon foto epi fè l lizib lè ou fè imaj la pi fonse oswa ajoute yon fon.",
            en: "Take your poster and work on the text: put a large title in a strong font, add a readable subtitle, and limit yourself to two fonts. Place the text over a photo and make it readable by darkening the image or adding a background.",
            es: "Retoma tu cartel y trabaja el texto: pon un título grande con una fuente fuerte, añade un subtítulo legible, y limítate a dos fuentes. Coloca el texto sobre una foto y hazlo legible oscureciendo la imagen o añadiendo un fondo.",
          },
        },
        {
          slug: "images-et-elements",
          title: { fr: "Photos, icônes et éléments graphiques", ht: "Foto, ikòn ak eleman grafik", en: "Photos, icons and graphic elements", es: "Fotos, iconos y elementos gráficos" },
          videoId: "",
          content: {
            fr: "Le menu « Éléments » contient des millions de photos, icônes, formes, autocollants et lignes. Tape un mot dans la recherche (par exemple « prière », « musique », « flèche ») et fais glisser l'élément choisi sur ta page. Pour utiliser tes propres photos, va dans « Téléchargements » et importe-les depuis ton appareil.\n\nQuand tu ajoutes une image, tu peux la recadrer en double-cliquant dessus, la placer en arrière-plan, ou lui appliquer un filtre pour harmoniser les couleurs. Les icônes, elles, aident à illustrer une idée sans texte : une horloge pour l'heure, un téléphone pour le contact, une épingle pour le lieu.\n\nNe surcharge pas : un bon design respire. Laisse des espaces vides autour des éléments importants. Aligne tout proprement — Canva affiche des lignes roses qui t'aident à centrer et à aligner automatiquement les objets entre eux.",
            ht: "Meni « Eleman » gen dè milyon foto, ikòn, fòm, otokolan ak liy. Tape yon mo nan rechèch la (pa egzanp « lapriyè », « mizik », « flèch ») epi trennen eleman ou chwazi a sou paj ou. Pou sèvi ak pwòp foto ou, ale nan « Telechajman » epi enpòte yo depi aparèy ou.\n\nLè ou ajoute yon imaj, ou ka koupe l lè ou double-klike sou li, mete l an background, oswa aplike yon filtè pou amonize koulè yo. Ikòn yo menm ede ilistre yon lide san tèks : yon revèy pou lè, yon telefòn pou kontak, yon zepeng pou kote.\n\nPa chaje twòp : yon bon design respire. Kite espas vid otou eleman enpòtan yo. Aliyen tout bagay pwòp — Canva montre liy woz ki ede ou santre epi aliyen objè yo otomatikman.",
            en: "The \"Elements\" menu holds millions of photos, icons, shapes, stickers and lines. Type a word in the search (for example \"prayer\", \"music\", \"arrow\") and drag the chosen element onto your page. To use your own photos, go to \"Uploads\" and import them from your device.\n\nWhen you add an image, you can crop it by double-clicking, set it as background, or apply a filter to harmonise the colours. Icons help illustrate an idea without words: a clock for time, a phone for contact, a pin for location.\n\nDon't overload it: a good design breathes. Leave empty space around important elements. Align everything neatly — Canva shows pink lines that help you centre and auto-align objects to each other.",
            es: "El menú «Elementos» contiene millones de fotos, iconos, formas, pegatinas y líneas. Escribe una palabra en la búsqueda (por ejemplo «oración», «música», «flecha») y arrastra el elemento elegido a tu página. Para usar tus propias fotos, ve a «Subidas» e impórtalas desde tu dispositivo.\n\nCuando añades una imagen, puedes recortarla con doble clic, ponerla de fondo o aplicarle un filtro para armonizar los colores. Los iconos ayudan a ilustrar una idea sin texto: un reloj para la hora, un teléfono para el contacto, un pin para el lugar.\n\nNo recargues: un buen diseño respira. Deja espacios vacíos alrededor de los elementos importantes. Alinea todo con orden — Canva muestra líneas rosas que te ayudan a centrar y alinear los objetos entre sí automáticamente.",
          },
          keyPoints: {
            fr: ["Éléments : photos, icônes, formes à glisser sur la page", "Importer tes propres photos via « Téléchargements »", "Aérer et aligner grâce aux lignes roses", "Ne pas surcharger : laisser respirer le design"],
            ht: ["Eleman : foto, ikòn, fòm pou trennen sou paj la", "Enpòte pwòp foto ou via « Telechajman »", "Kite espas epi aliyen ak liy woz yo", "Pa chaje twòp : kite design lan respire"],
            en: ["Elements: photos, icons, shapes to drag onto the page", "Import your own photos via \"Uploads\"", "Give space and align with the pink guide lines", "Don't overload: let the design breathe"],
            es: ["Elementos: fotos, iconos, formas para arrastrar", "Importar tus propias fotos en «Subidas»", "Airear y alinear con las líneas rosas", "No recargar: dejar respirar el diseño"],
          },
          exercise: {
            fr: "Dans « Éléments », cherche trois icônes utiles (lieu, heure, contact) et ajoute-les à ton affiche. Importe une de tes propres photos via « Téléchargements » et recadre-la. Aligne le tout à l'aide des lignes roses.",
            ht: "Nan « Eleman », chèche twa ikòn itil (kote, lè, kontak) epi ajoute yo sou afich ou. Enpòte youn nan pwòp foto ou via « Telechajman » epi koupe l. Aliyen tout ak liy woz yo.",
            en: "In \"Elements\", search for three useful icons (place, time, contact) and add them to your poster. Import one of your own photos via \"Uploads\" and crop it. Align everything using the pink lines.",
            es: "En «Elementos», busca tres iconos útiles (lugar, hora, contacto) y añádelos a tu cartel. Importa una de tus propias fotos por «Subidas» y recórtala. Alinea todo con las líneas rosas.",
          },
        },
        {
          slug: "couleurs-et-marque",
          title: { fr: "Couleurs et identité de marque", ht: "Koulè ak idantite mak", en: "Colours and brand identity", es: "Colores e identidad de marca" },
          videoId: "",
          content: {
            fr: "Les couleurs transmettent une émotion : le bleu inspire la confiance, le rouge l'énergie, le vert la nature et la paix. Choisis deux ou trois couleurs principales et garde-les sur tous tes designs. Cette constance crée une identité reconnaissable, que ce soit pour ton église, ton commerce ou ton projet.\n\nPour changer une couleur dans Canva, sélectionne l'élément puis clique sur le carré de couleur en haut. Tu peux entrer un code couleur précis (par exemple #1E88E5) pour retrouver exactement la même teinte à chaque fois. Note tes codes couleurs quelque part pour les réutiliser.\n\nSi tu utilises Canva pour une organisation, l'outil « Kit de marque » te permet d'enregistrer ton logo, tes couleurs et tes polices au même endroit (certaines fonctions sont payantes). L'important est la cohérence : mieux vaut trois couleurs bien choisies partout qu'un arc-en-ciel différent à chaque affiche.",
            ht: "Koulè yo transmèt yon emosyon : ble bay konfyans, wouj bay enèji, vèt bay lanati ak lapè. Chwazi de oswa twa koulè prensipal epi kenbe yo sou tout design ou. Konstans sa a kreye yon idantite ou ka rekonèt, kit se pou legliz ou, komès ou oswa pwojè ou.\n\nPou chanje yon koulè nan Canva, seleksyone eleman an epi klike sou kare koulè a anlè. Ou ka antre yon kòd koulè presi (pa egzanp #1E88E5) pou jwenn menm koulè a chak fwa. Note kòd koulè ou yon kote pou reyitilize yo.\n\nSi ou sèvi ak Canva pou yon òganizasyon, zouti « Kit mak » pèmèt ou anrejistre logo, koulè ak polis ou nan menm kote (kèk fonksyon peye). Sa ki enpòtan se koyerans : li pi bon pou gen twa koulè byen chwazi toupatou pase yon lakansyèl diferan sou chak afich.",
            en: "Colours carry emotion: blue inspires trust, red energy, green nature and peace. Pick two or three main colours and keep them across all your designs. This consistency builds a recognisable identity, whether for your church, business or project.\n\nTo change a colour in Canva, select the element then click the colour square at the top. You can enter an exact colour code (for example #1E88E5) to get the same shade every time. Write your colour codes down somewhere to reuse them.\n\nIf you use Canva for an organisation, the \"Brand Kit\" tool lets you save your logo, colours and fonts in one place (some features are paid). What matters is consistency: three well-chosen colours everywhere beat a different rainbow on each poster.",
            es: "Los colores transmiten emoción: el azul inspira confianza, el rojo energía, el verde naturaleza y paz. Elige dos o tres colores principales y consérvalos en todos tus diseños. Esa constancia crea una identidad reconocible, ya sea para tu iglesia, tu negocio o tu proyecto.\n\nPara cambiar un color en Canva, selecciona el elemento y haz clic en el cuadro de color arriba. Puedes escribir un código de color exacto (por ejemplo #1E88E5) para lograr el mismo tono siempre. Anota tus códigos de color en algún lugar para reutilizarlos.\n\nSi usas Canva para una organización, la herramienta «Kit de marca» te permite guardar tu logo, colores y fuentes en un solo lugar (algunas funciones son de pago). Lo importante es la coherencia: mejor tres colores bien elegidos en todo que un arcoíris distinto en cada cartel.",
          },
          keyPoints: {
            fr: ["Choisir deux ou trois couleurs et s'y tenir partout", "Utiliser un code couleur (#) pour la même teinte à chaque fois", "La cohérence crée une identité reconnaissable", "Noter ses codes couleurs (#) pour les réutiliser"],
            ht: ["Chwazi de oswa twa koulè epi kenbe yo toupatou", "Sèvi ak yon kòd koulè (#) pou menm koulè a chak fwa", "Koyerans kreye yon idantite ou ka rekonèt", "Note kòd koulè ou yo (#) pou reyitilize yo"],
            en: ["Pick two or three colours and keep them everywhere", "Use a colour code (#) for the same shade each time", "Consistency builds a recognisable identity", "Note your colour codes (#) to reuse them"],
            es: ["Elegir dos o tres colores y mantenerlos en todo", "Usar un código de color (#) para el mismo tono siempre", "La coherencia crea una identidad reconocible", "Anotar tus códigos de color (#) para reutilizarlos"],
          },
          exercise: {
            fr: "Choisis trois couleurs pour ton projet (ou ton église) et note leurs codes (#). Applique-les à ton affiche : titre, fond, éléments. Vérifie que le résultat reste harmonieux et lisible.",
            ht: "Chwazi twa koulè pou pwojè ou (oswa legliz ou) epi note kòd yo (#). Aplike yo sou afich ou : tit, fon, eleman. Verifye rezilta a rete amonye epi lizib.",
            en: "Choose three colours for your project (or your church) and note their codes (#). Apply them to your poster: title, background, elements. Check that the result stays harmonious and readable.",
            es: "Elige tres colores para tu proyecto (o tu iglesia) y anota sus códigos (#). Aplícalos a tu cartel: título, fondo, elementos. Comprueba que el resultado siga siendo armonioso y legible.",
          },
        },
      ],
    },
    {
      title: { fr: "Mise en page, animation et identité", ht: "Mizanpaj, animasyon ak idantite", en: "Layout, animation and identity", es: "Composición, animación e identidad" },
      lessons: [
        {
          slug: "mise-en-page",
          title: { fr: "Mise en page : équilibre et alignement", ht: "Mizanpaj : ekilib ak aliyman", en: "Layout: balance and alignment", es: "Composición: equilibrio y alineación" },
          videoId: "",
          content: {
            fr: "La mise en page, c'est la façon d'organiser les éléments sur la page. Un bon design guide l'œil : d'abord le titre, puis l'image, puis les détails. Pour cela, joue sur la taille (le plus important est le plus gros) et la position (le haut et le centre attirent d'abord le regard).\n\nAligne tout proprement. Canva affiche des lignes violettes ou roses quand tes éléments sont alignés ou centrés : appuie-toi dessus. Utilise aussi le menu « Position » puis « Aligner » pour caler plusieurs objets sur le même bord. Un alignement soigné suffit à rendre un design professionnel.\n\nRespecte les espaces. Laisse des marges régulières autour du contenu et de l'air entre les blocs. Un design surchargé fatigue ; un design aéré respire et se lit facilement. La règle : dans le doute, enlève un élément plutôt que d'en ajouter.\n\nRegroupe ce qui va ensemble (proximité) : une date et un lieu proches l'un de l'autre, une légende collée à sa photo. Tu peux sélectionner plusieurs éléments et cliquer sur « Grouper » pour les déplacer ensemble sans casser la mise en page. Active la grille ou les règles (menu Fichier puis Afficher les règles) pour t'aider.",
            ht: "Mizanpaj la se fason pou òganize eleman yo sou paj la. Yon bon design gide je a : dabò tit la, apre imaj la, apre detay yo. Pou sa, jwe ak gwosè (sa ki pi enpòtan an se pi gwo a) ak pozisyon (anlè ak nan mitan atire je a dabò).\n\nAliyen tout bagay pwòp. Canva montre liy vyolèt oswa woz lè eleman ou yo aliyen oswa santre : apiye sou yo. Sèvi tou ak meni « Pozisyon » epi « Aliyen » pou mete plizyè objè sou menm bò a. Yon bon aliyman ase pou fè yon design parèt pwofesyonèl.\n\nRespekte espas yo. Kite maj regilye otou kontni an epi lè ant blòk yo. Yon design chaje twòp fatige ; yon design ki gen espas respire epi li fasil pou li. Règ la : nan dout, retire yon eleman olye ajoute youn.\n\nRasanble sa ki mache ansanm (pwoksimite) : yon dat ak yon kote pre youn ak lòt, yon lejand kole ak foto li. Ou ka seleksyone plizyè eleman epi klike « Gwoupe » pou deplase yo ansanm san kase mizanpaj la. Aktive griy la oswa règ yo (meni Fichye epi Montre règ yo) pou ede ou.",
            en: "Layout is how you arrange the elements on the page. A good design guides the eye: first the title, then the image, then the details. To do this, play with size (the most important is the biggest) and position (the top and centre catch the eye first).\n\nAlign everything neatly. Canva shows purple or pink lines when your elements are aligned or centred: lean on them. Also use the \"Position\" then \"Align\" menu to line up several objects on the same edge. Neat alignment alone makes a design look professional.\n\nRespect the spacing. Leave even margins around the content and air between the blocks. An overloaded design tires the eye; an airy design breathes and reads easily. The rule: when in doubt, remove an element rather than add one.\n\nGroup what belongs together (proximity): a date and place near each other, a caption stuck to its photo. You can select several elements and click \"Group\" to move them together without breaking the layout. Turn on the grid or rulers (File menu then Show rulers) to help you.",
            es: "La composición es la forma de organizar los elementos en la página. Un buen diseño guía la mirada: primero el título, luego la imagen, luego los detalles. Para ello, juega con el tamaño (lo más importante es lo más grande) y la posición (la parte superior y el centro atraen primero la mirada).\n\nAlinea todo con orden. Canva muestra líneas moradas o rosas cuando tus elementos están alineados o centrados: apóyate en ellas. Usa también el menú «Posición» y luego «Alinear» para ajustar varios objetos al mismo borde. Una buena alineación basta para que un diseño parezca profesional.\n\nRespeta los espacios. Deja márgenes regulares alrededor del contenido y aire entre los bloques. Un diseño recargado cansa; un diseño aireado respira y se lee con facilidad. La regla: ante la duda, quita un elemento en vez de añadir uno.\n\nAgrupa lo que va junto (proximidad): una fecha y un lugar cerca uno del otro, un pie de foto pegado a su imagen. Puedes seleccionar varios elementos y hacer clic en «Agrupar» para moverlos juntos sin romper la composición. Activa la cuadrícula o las reglas (menú Archivo y luego Mostrar reglas) para ayudarte.",
          },
          keyPoints: {
            fr: ["Guider l'œil par la taille et la position", "S'appuyer sur les lignes roses et « Aligner »", "Aérer : marges régulières, ne pas surcharger", "Grouper les éléments liés (proximité)"],
            ht: ["Gide je a ak gwosè ak pozisyon", "Apiye sou liy woz yo ak « Aliyen »", "Kite espas : maj regilye, pa chaje twòp", "Gwoupe eleman ki mache ansanm (pwoksimite)"],
            en: ["Guide the eye with size and position", "Lean on the pink lines and \"Align\"", "Give air: even margins, don't overload", "Group related elements (proximity)"],
            es: ["Guiar la mirada con el tamaño y la posición", "Apoyarse en las líneas rosas y «Alinear»", "Airear: márgenes regulares, no recargar", "Agrupar los elementos relacionados (proximidad)"],
          },
          exercise: {
            fr: "Reprends une affiche existante et améliore sa mise en page : aligne tous les textes sur un même bord, agrandis le titre, augmente les marges, et groupe la date avec le lieu. Compare l'avant et l'après.",
            ht: "Reprann yon afich ki egziste epi amelyore mizanpaj li : aliyen tout tèks sou menm bò a, agrandi tit la, ogmante maj yo, epi gwoupe dat la ak kote a. Konpare avan ak apre a.",
            en: "Take an existing poster and improve its layout: align all the text to one edge, enlarge the title, increase the margins, and group the date with the place. Compare before and after.",
            es: "Toma un cartel existente y mejora su composición: alinea todos los textos a un mismo borde, agranda el título, aumenta los márgenes y agrupa la fecha con el lugar. Compara el antes y el después.",
          },
        },
        {
          slug: "animations",
          title: { fr: "Animer un design et créer une vidéo", ht: "Anime yon design epi kreye yon videyo", en: "Animating a design and making a video", es: "Animar un diseño y crear un video" },
          videoId: "",
          content: {
            fr: "Canva permet d'animer tes designs pour capter l'attention sur les réseaux. Sélectionne un élément (ou toute la page), clique sur « Animer » en haut, et choisis un effet : apparition en fondu, glissement, zoom, rebond. Une animation légère rend une publication bien plus vivante qu'une image fixe.\n\nTu peux animer page par page pour créer une petite vidéo ou une story. Ajoute plusieurs pages, règle la durée de chacune (icône horloge en bas), et Canva enchaîne les transitions. Choisis une transition entre les pages (fondu, balayage) via le bouton situé entre deux vignettes.\n\nTu peux aussi ajouter de la musique et des vidéos. Le menu « Éléments » contient des clips vidéo et « Audio » propose des musiques libres de droits. Cale la musique sur la durée de ta vidéo. Attention à ne pas surcharger : une seule animation par élément suffit souvent.\n\nPour exporter une animation, va dans « Partager » puis « Télécharger » et choisis le format MP4 (vidéo) ou GIF. Le MP4 convient aux réseaux et à WhatsApp ; le GIF, plus léger, sert aux petites animations en boucle. Vérifie le rendu en lançant l'aperçu avant d'exporter.",
            ht: "Canva pèmèt ou anime design ou yo pou atire atansyon sou rezo sosyal. Seleksyone yon eleman (oswa tout paj la), klike sou « Anime » anlè, epi chwazi yon efè : aparisyon an fondi, glisman, zoom, rebondi. Yon animasyon lejè fè yon piblikasyon pi vivan pase yon imaj fiks.\n\nOu ka anime paj pa paj pou kreye yon ti videyo oswa yon story. Ajoute plizyè paj, regle dire chak (ikòn revèy anba), epi Canva anchennen tranzisyon yo. Chwazi yon tranzisyon ant paj yo (fondi, balaye) via bouton ki ant de vinyèt yo.\n\nOu ka ajoute mizik ak videyo tou. Meni « Eleman » gen klip videyo epi « Odyo » pwopoze mizik ki lib de dwa. Kale mizik la sou dire videyo ou. Fè atansyon pou ou pa chaje twòp : yon sèl animasyon pou chak eleman souvan ase.\n\nPou ekspòte yon animasyon, ale nan « Pataje » epi « Telechaje » epi chwazi fòma MP4 (videyo) oswa GIF. MP4 bon pou rezo sosyal ak WhatsApp ; GIF, pi lejè, sèvi pou ti animasyon an bouk. Verifye rezilta a lè ou lanse apèsi a anvan ou ekspòte.",
            en: "Canva lets you animate your designs to catch attention on social media. Select an element (or the whole page), click \"Animate\" at the top, and choose an effect: fade in, slide, zoom, bounce. A light animation makes a post far livelier than a still image.\n\nYou can animate page by page to make a short video or a story. Add several pages, set the duration of each (clock icon at the bottom), and Canva links the transitions. Choose a transition between pages (fade, wipe) via the button between two thumbnails.\n\nYou can also add music and video. The \"Elements\" menu holds video clips and \"Audio\" offers royalty-free music. Match the music to your video's length. Be careful not to overload: one animation per element is often enough.\n\nTo export an animation, go to \"Share\" then \"Download\" and choose MP4 (video) or GIF. MP4 suits social media and WhatsApp; GIF, lighter, is for small looping animations. Check the result by playing the preview before exporting.",
            es: "Canva te permite animar tus diseños para captar la atención en redes. Selecciona un elemento (o toda la página), haz clic en «Animar» arriba, y elige un efecto: aparición en fundido, deslizamiento, zoom, rebote. Una animación ligera hace una publicación mucho más viva que una imagen fija.\n\nPuedes animar página por página para crear un pequeño video o una historia. Añade varias páginas, ajusta la duración de cada una (icono de reloj abajo), y Canva encadena las transiciones. Elige una transición entre las páginas (fundido, barrido) con el botón entre dos miniaturas.\n\nTambién puedes añadir música y videos. El menú «Elementos» contiene clips de video y «Audio» ofrece músicas libres de derechos. Ajusta la música a la duración de tu video. Cuidado con no recargar: una sola animación por elemento suele bastar.\n\nPara exportar una animación, ve a «Compartir» y luego «Descargar» y elige el formato MP4 (video) o GIF. El MP4 sirve para redes y WhatsApp; el GIF, más ligero, para pequeñas animaciones en bucle. Comprueba el resultado con la vista previa antes de exportar.",
          },
          keyPoints: {
            fr: ["« Animer » applique un effet à un élément ou à la page", "Plusieurs pages + durées = mini-vidéo avec transitions", "Ajouter musique et clips via « Audio » et « Éléments »", "Exporter en MP4 (vidéo) ou GIF (boucle légère)"],
            ht: ["« Anime » aplike yon efè sou yon eleman oswa paj la", "Plizyè paj + dire = mini-videyo ak tranzisyon", "Ajoute mizik ak klip via « Odyo » ak « Eleman »", "Ekspòte an MP4 (videyo) oswa GIF (ti bouk lejè)"],
            en: ["\"Animate\" applies an effect to an element or the page", "Several pages + durations = mini-video with transitions", "Add music and clips via \"Audio\" and \"Elements\"", "Export as MP4 (video) or GIF (light loop)"],
            es: ["«Animar» aplica un efecto a un elemento o a la página", "Varias páginas + duraciones = mini-video con transiciones", "Añadir música y clips con «Audio» y «Elementos»", "Exportar en MP4 (video) o GIF (bucle ligero)"],
          },
          exercise: {
            fr: "Transforme une affiche fixe en publication animée : anime le titre avec un effet d'apparition, ajoute une deuxième page avec une transition, et une courte musique. Exporte le tout en MP4 et regarde le résultat.",
            ht: "Transfòme yon afich fiks an piblikasyon anime : anime tit la ak yon efè aparisyon, ajoute yon dezyèm paj ak yon tranzisyon, ak yon ti mizik. Ekspòte tout an MP4 epi gade rezilta a.",
            en: "Turn a still poster into an animated post: animate the title with a fade-in effect, add a second page with a transition, and a short piece of music. Export it all as MP4 and watch the result.",
            es: "Convierte un cartel fijo en una publicación animada: anima el título con un efecto de aparición, añade una segunda página con una transición y una música corta. Expórtalo todo en MP4 y observa el resultado.",
          },
        },
        {
          slug: "creer-un-logo",
          title: { fr: "Créer un logo et une identité visuelle", ht: "Kreye yon logo ak yon idantite vizyèl", en: "Creating a logo and visual identity", es: "Crear un logo y una identidad visual" },
          videoId: "",
          content: {
            fr: "Un logo est le symbole qui représente ton projet, ton commerce ou ton ministère. Dans Canva, tape « logo » pour partir d'un modèle, ou crée un design carré vierge. Un bon logo est simple : un symbole ou des initiales, un nom, et deux couleurs au maximum. Il doit rester lisible en tout petit comme en grand.\n\nCompose ton logo avec un élément graphique (une icône du menu « Éléments ») et le nom en dessous ou à côté. Choisis une police qui correspond à ton esprit : sérieuse, moderne, chaleureuse. Évite les détails trop fins qui disparaissent quand le logo est réduit sur un téléphone.\n\nDécline ensuite ton identité : garde les mêmes couleurs et la même police sur ta carte de visite, tes publications et ta bannière. Cette cohérence fait qu'on te reconnaît d'un coup d'œil. Note tes codes couleurs et le nom de tes polices pour les réutiliser partout.\n\nPour un logo, exporte en PNG avec « fond transparent » (option payante) afin de le poser sur n'importe quelle couleur. Sinon, exporte sur un fond neutre. Garde le fichier d'origine dans « Projets » pour pouvoir le modifier plus tard.",
            ht: "Yon logo se senbòl ki reprezante pwojè ou, komès ou oswa ministè ou. Nan Canva, tape « logo » pou pati ak yon modèl, oswa kreye yon design kare vid. Yon bon logo senp : yon senbòl oswa inisyal, yon non, epi de koulè maksimòm. Li dwe rete lizib ni piti ni gwo.\n\nKonpoze logo ou ak yon eleman grafik (yon ikòn nan meni « Eleman ») epi non an anba oswa akote. Chwazi yon polis ki koresponn ak lespri ou : serye, modèn, cho. Evite detay ki twò fen ki disparèt lè logo a redwi sou yon telefòn.\n\nApre sa, dekline idantite ou : kenbe menm koulè ak menm polis sou kat vizit ou, piblikasyon ou ak banyè ou. Koyerans sa a fè yo rekonèt ou nan yon sèl gade. Note kòd koulè ou ak non polis ou pou reyitilize yo toupatou.\n\nPou yon logo, ekspòte an PNG ak « fon transparan » (opsyon peye) pou ou ka mete l sou nenpòt koulè. Sinon, ekspòte sou yon fon net. Kenbe fichye orijinal la nan « Pwojè » pou ou ka modifye l pita.",
            en: "A logo is the symbol that represents your project, business or ministry. In Canva, type \"logo\" to start from a template, or create a blank square design. A good logo is simple: a symbol or initials, a name, and two colours at most. It must stay readable both very small and large.\n\nBuild your logo with a graphic element (an icon from the \"Elements\" menu) and the name below or beside it. Choose a font that matches your spirit: serious, modern, warm. Avoid fine details that vanish when the logo is shrunk on a phone.\n\nThen roll out your identity: keep the same colours and font on your business card, your posts and your banner. This consistency makes you recognisable at a glance. Note your colour codes and font names to reuse them everywhere.\n\nFor a logo, export as PNG with a \"transparent background\" (paid option) so you can place it on any colour. Otherwise, export on a neutral background. Keep the original file in \"Projects\" so you can edit it later.",
            es: "Un logo es el símbolo que representa tu proyecto, tu negocio o tu ministerio. En Canva, escribe «logo» para partir de una plantilla, o crea un diseño cuadrado en blanco. Un buen logo es simple: un símbolo o iniciales, un nombre y dos colores como máximo. Debe seguir siendo legible tanto pequeño como grande.\n\nCompón tu logo con un elemento gráfico (un icono del menú «Elementos») y el nombre debajo o al lado. Elige una fuente que corresponda a tu espíritu: seria, moderna, cálida. Evita los detalles demasiado finos que desaparecen cuando el logo se reduce en un teléfono.\n\nLuego despliega tu identidad: conserva los mismos colores y la misma fuente en tu tarjeta de visita, tus publicaciones y tu banner. Esa coherencia hace que te reconozcan de un vistazo. Anota tus códigos de color y los nombres de tus fuentes para reutilizarlos en todo.\n\nPara un logo, exporta en PNG con «fondo transparente» (opción de pago) para poder ponerlo sobre cualquier color. Si no, exporta sobre un fondo neutro. Conserva el archivo original en «Proyectos» para poder modificarlo más adelante.",
          },
          keyPoints: {
            fr: ["Un bon logo est simple : symbole, nom, deux couleurs max", "Lisible en petit comme en grand", "Décliner mêmes couleurs et police partout (cohérence)", "Exporter en PNG (fond transparent si possible)"],
            ht: ["Yon bon logo senp : senbòl, non, de koulè maksimòm", "Lizib ni piti ni gwo", "Dekline menm koulè ak polis toupatou (koyerans)", "Ekspòte an PNG (fon transparan si posib)"],
            en: ["A good logo is simple: symbol, name, two colours max", "Readable both small and large", "Reuse the same colours and font everywhere (consistency)", "Export as PNG (transparent background if possible)"],
            es: ["Un buen logo es simple: símbolo, nombre, dos colores máximo", "Legible tanto pequeño como grande", "Reutilizar los mismos colores y fuente en todo (coherencia)", "Exportar en PNG (fondo transparente si es posible)"],
          },
          exercise: {
            fr: "Crée un logo simple pour un projet réel (église, petit commerce, chaîne). Utilise une icône, un nom et deux couleurs. Puis pose ce logo sur une publication et une bannière pour vérifier qu'il reste lisible partout.",
            ht: "Kreye yon logo senp pou yon vrè pwojè (legliz, ti komès, chèn). Sèvi ak yon ikòn, yon non ak de koulè. Apre sa, mete logo sa a sou yon piblikasyon ak yon banyè pou verifye li rete lizib toupatou.",
            en: "Create a simple logo for a real project (church, small business, channel). Use an icon, a name and two colours. Then place this logo on a post and a banner to check it stays readable everywhere.",
            es: "Crea un logo simple para un proyecto real (iglesia, pequeño negocio, canal). Usa un icono, un nombre y dos colores. Luego coloca ese logo en una publicación y un banner para comprobar que sigue siendo legible en todas partes.",
          },
        },
      ],
    },
    {
      title: { fr: "Exporter, partager et imprimer", ht: "Ekspòte, pataje ak enprime", en: "Exporting, sharing and printing", es: "Exportar, compartir e imprimir" },
      lessons: [
        {
          slug: "exporter-et-partager",
          title: { fr: "Exporter, télécharger et partager", ht: "Ekspòte, telechaje ak pataje", en: "Exporting, downloading and sharing", es: "Exportar, descargar y compartir" },
          videoId: "",
          content: {
            fr: "Ton design est prêt ? Clique sur « Partager » en haut à droite, puis « Télécharger ». Canva te demande un format de fichier. Retiens la règle simple : PNG pour une image nette destinée à l'écran ou aux réseaux, JPG pour une photo plus légère, et PDF pour un document à imprimer (choisis « PDF Impression » pour la meilleure qualité).\n\nPour publier sur les réseaux sociaux, tu peux aussi partager directement depuis Canva vers Instagram, Facebook ou WhatsApp, ou même programmer la publication. Vérifie toujours ton design avant d'exporter : fautes d'orthographe, éléments qui dépassent, texte coupé au bord.\n\nEnfin, tu peux partager le lien de modification avec un collègue pour travailler à plusieurs sur le même design, comme dans un document partagé. Tous tes projets restent sauvegardés automatiquement dans ton compte : tu les retrouveras dans « Projets » sur n'importe quel appareil connecté.",
            ht: "Design ou pare ? Klike sou « Pataje » anwo adwat, epi « Telechaje ». Canva mande ou yon fòma fichye. Sonje règ senp sa a : PNG pou yon imaj klè pou ekran oswa rezo sosyal, JPG pou yon foto ki pi lejè, epi PDF pou yon dokiman pou enprime (chwazi « PDF Enprime » pou pi bon kalite).\n\nPou pibliye sou rezo sosyal, ou ka pataje dirèkteman depi Canva sou Instagram, Facebook oswa WhatsApp, oswa menm pwograme piblikasyon an. Toujou verifye design ou anvan ou ekspòte : fot òtograf, eleman ki depase, tèks ki koupe sou bò a.\n\nAnfen, ou ka pataje lyen modifikasyon an ak yon kòlèg pou travay plizyè moun sou menm design lan, tankou nan yon dokiman pataje. Tout pwojè ou rete sove otomatikman nan kont ou : ou ap jwenn yo nan « Pwojè » sou nenpòt aparèy ki konekte.",
            en: "Design ready? Click \"Share\" at the top right, then \"Download\". Canva asks for a file format. Remember the simple rule: PNG for a crisp image meant for screens or social media, JPG for a lighter photo, and PDF for a document to print (choose \"PDF Print\" for the best quality).\n\nTo post on social media, you can also share directly from Canva to Instagram, Facebook or WhatsApp, or even schedule the post. Always check your design before exporting: spelling mistakes, elements sticking out, text cut off at the edge.\n\nFinally, you can share the edit link with a colleague to work together on the same design, like a shared document. All your projects are saved automatically in your account: you will find them in \"Projects\" on any connected device.",
            es: "¿Diseño listo? Haz clic en «Compartir» arriba a la derecha, y luego «Descargar». Canva te pide un formato de archivo. Recuerda la regla sencilla: PNG para una imagen nítida destinada a pantalla o redes, JPG para una foto más ligera, y PDF para un documento a imprimir (elige «PDF Impresión» para la mejor calidad).\n\nPara publicar en redes sociales, también puedes compartir directamente desde Canva a Instagram, Facebook o WhatsApp, o incluso programar la publicación. Revisa siempre tu diseño antes de exportar: faltas de ortografía, elementos que sobresalen, texto cortado en el borde.\n\nPor último, puedes compartir el enlace de edición con un colega para trabajar entre varios en el mismo diseño, como en un documento compartido. Todos tus proyectos se guardan automáticamente en tu cuenta: los encontrarás en «Proyectos» en cualquier dispositivo conectado.",
          },
          keyPoints: {
            fr: ["PNG pour l'écran, JPG pour une photo légère, PDF pour imprimer", "Relire avant d'exporter : fautes et texte coupé", "Projets sauvegardés automatiquement et partageables", "Retrouver ses projets dans « Projets » sur tout appareil connecté"],
            ht: ["PNG pou ekran, JPG pou foto lejè, PDF pou enprime", "Reli anvan ekspòte : fot ak tèks koupe", "Pwojè sove otomatikman epi ou ka pataje yo", "Jwenn pwojè ou nan « Pwojè » sou nenpòt aparèy konekte"],
            en: ["PNG for screens, JPG for a light photo, PDF for printing", "Proofread before exporting: typos and cut text", "Projects saved automatically and shareable", "Find your projects in \"Projects\" on any connected device"],
            es: ["PNG para pantalla, JPG para foto ligera, PDF para imprimir", "Revisar antes de exportar: erratas y texto cortado", "Proyectos guardados automáticamente y compartibles", "Encontrar tus proyectos en «Proyectos» en cualquier dispositivo conectado"],
          },
          exercise: {
            fr: "Relis attentivement ton affiche (fautes, débordements). Télécharge-la en PNG pour les réseaux, puis en PDF pour l'impression. Partage le lien d'édition avec un ami pour qu'il la relise.",
            ht: "Reli afich ou byen (fot, eleman ki depase). Telechaje l an PNG pou rezo sosyal, epi an PDF pou enprime. Pataje lyen modifikasyon an ak yon zanmi pou l reli l.",
            en: "Proofread your poster carefully (typos, overflowing elements). Download it as PNG for social media, then as PDF for printing. Share the edit link with a friend so they can proofread it.",
            es: "Revisa tu cartel con atención (erratas, elementos que sobresalen). Descárgalo en PNG para redes, y en PDF para imprimir. Comparte el enlace de edición con un amigo para que lo revise.",
          },
        },
        {
          slug: "imprimer",
          title: { fr: "Préparer un design pour l'impression", ht: "Prepare yon design pou enprime", en: "Preparing a design for print", es: "Preparar un diseño para imprimir" },
          videoId: "",
          content: {
            fr: "Créer pour l'écran et pour le papier n'est pas tout à fait pareil. Pour imprimer, travaille en centimètres ou millimètres et pense à la qualité : les images doivent être nettes, pas floues. Évite d'agrandir une petite photo, elle deviendrait pixelisée à l'impression.\n\nPrévois le « fond perdu » (bleed) : étends le fond de ton design quelques millimètres au-delà du bord. Ainsi, si la découpe est légèrement décalée, il n'y aura pas de bande blanche. Dans Canva, active « Fichier » puis « Afficher les repères d'impression et fond perdu ». Garde le texte important à l'intérieur des repères.\n\nChoisis les bonnes couleurs. Les écrans utilisent le mode RVB, les imprimeries le mode CMJN : les couleurs très vives à l'écran peuvent paraître plus ternes sur papier. Certaines options d'impression Canva gèrent le CMJN. Fais un test d'impression si la couleur est cruciale.\n\nPour exporter, choisis « PDF Impression » : c'est le format attendu par la plupart des imprimeurs, avec la meilleure qualité et les repères. Tu peux aussi imprimer chez toi en PDF, ou commander directement via le service d'impression intégré de Canva, qui livre affiches, cartes et flyers.",
            ht: "Kreye pou ekran ak pou papye pa menm bagay nèt. Pou enprime, travay an santimèt oswa milimèt epi panse ak kalite : imaj yo dwe klè, pa flou. Evite agrandi yon ti foto, li ta vin gen piksèl lè ou enprime l.\n\nPrevwa « fon pèdi » a (bleed) : lonje fon design ou kèk milimèt pi lwen pase bò a. Konsa, si koupe a yon ti kras dekale, p ap gen bann blan. Nan Canva, aktive « Fichye » epi « Montre repè enprime ak fon pèdi ». Kenbe tèks enpòtan an anndan repè yo.\n\nChwazi bon koulè yo. Ekran yo sèvi ak mòd RVB, enprimri yo mòd CMJN : koulè byen vif sou ekran ka parèt pi tèn sou papye. Kèk opsyon enprime Canva jere CMJN. Fè yon tès enprime si koulè a enpòtan anpil.\n\nPou ekspòte, chwazi « PDF Enprime » : se fòma pifò enprimè ap tann, ak pi bon kalite ak repè yo. Ou ka enprime lakay ou an PDF tou, oswa kòmande dirèkteman via sèvis enprime ki entegre nan Canva a, ki livre afich, kat ak flyer.",
            en: "Creating for screen and for paper is not quite the same. To print, work in centimetres or millimetres and mind quality: images must be sharp, not blurry. Avoid enlarging a small photo, it would become pixelated in print.\n\nPlan for the \"bleed\": extend your design's background a few millimetres beyond the edge. That way, if the cut is slightly off, there is no white strip. In Canva, turn on \"File\" then \"Show print bleed and crop marks\". Keep important text inside the marks.\n\nChoose the right colours. Screens use RGB mode, print shops use CMYK: very bright colours on screen can look duller on paper. Some Canva print options handle CMYK. Do a test print if the colour is crucial.\n\nTo export, choose \"PDF Print\": it is the format most printers expect, with the best quality and the marks. You can also print at home as a PDF, or order directly through Canva's built-in print service, which delivers posters, cards and flyers.",
            es: "Crear para pantalla y para papel no es del todo lo mismo. Para imprimir, trabaja en centímetros o milímetros y cuida la calidad: las imágenes deben ser nítidas, no borrosas. Evita agrandar una foto pequeña, quedaría pixelada al imprimir.\n\nPrevé el «sangrado» (bleed): extiende el fondo de tu diseño unos milímetros más allá del borde. Así, si el corte queda un poco desviado, no habrá una franja blanca. En Canva, activa «Archivo» y luego «Mostrar sangrado y marcas de corte». Mantén el texto importante dentro de las marcas.\n\nElige los colores correctos. Las pantallas usan el modo RGB, las imprentas el modo CMYK: los colores muy vivos en pantalla pueden verse más apagados en papel. Algunas opciones de impresión de Canva manejan el CMYK. Haz una prueba de impresión si el color es crucial.\n\nPara exportar, elige «PDF Impresión»: es el formato que espera la mayoría de las imprentas, con la mejor calidad y las marcas. También puedes imprimir en casa en PDF, o pedir directamente con el servicio de impresión integrado de Canva, que entrega carteles, tarjetas y folletos.",
          },
          keyPoints: {
            fr: ["Travailler en cm/mm avec des images nettes", "Prévoir le fond perdu pour éviter les bandes blanches", "Écran = RVB, impression = CMJN (couleurs plus ternes)", "Exporter en « PDF Impression » pour l'imprimeur"],
            ht: ["Travay an cm/mm ak imaj ki klè", "Prevwa fon pèdi pou evite bann blan", "Ekran = RVB, enprime = CMJN (koulè pi tèn)", "Ekspòte an « PDF Enprime » pou enprimè a"],
            en: ["Work in cm/mm with sharp images", "Plan the bleed to avoid white strips", "Screen = RGB, print = CMYK (duller colours)", "Export as \"PDF Print\" for the printer"],
            es: ["Trabajar en cm/mm con imágenes nítidas", "Prever el sangrado para evitar franjas blancas", "Pantalla = RGB, impresión = CMYK (colores más apagados)", "Exportar en «PDF Impresión» para la imprenta"],
          },
          exercise: {
            fr: "Prépare un flyer A5 pour l'impression : active les repères et le fond perdu, étends le fond jusqu'au bord, garde le texte à l'intérieur des repères, et exporte-le en « PDF Impression ». Vérifie que tes images sont bien nettes.",
            ht: "Prepare yon flyer A5 pou enprime : aktive repè yo ak fon pèdi a, lonje fon an jiska bò a, kenbe tèks la anndan repè yo, epi ekspòte l an « PDF Enprime ». Verifye imaj ou yo byen klè.",
            en: "Prepare an A5 flyer for print: turn on the marks and bleed, extend the background to the edge, keep the text inside the marks, and export it as \"PDF Print\". Check that your images are nice and sharp.",
            es: "Prepara un folleto A5 para imprimir: activa las marcas y el sangrado, extiende el fondo hasta el borde, mantén el texto dentro de las marcas y expórtalo en «PDF Impresión». Comprueba que tus imágenes sean bien nítidas.",
          },
        },
        {
          slug: "collaborer-en-equipe",
          title: { fr: "Travailler à plusieurs sur un design", ht: "Travay plizyè moun sou yon design", en: "Working together on a design", es: "Trabajar entre varios en un diseño" },
          videoId: "",
          content: {
            fr: "Canva permet de travailler à plusieurs sur le même design, comme dans un document partagé. Clique sur « Partager », entre l'adresse e-mail de tes collègues, et choisis leur droit : « peut modifier » pour co-créer, « peut commenter » pour donner un avis, ou « peut consulter » pour seulement regarder.\n\nChacun voit les changements en temps réel. Pour discuter sans toucher au design, utilise les commentaires : sélectionne un élément, ajoute une note, et mentionne quelqu'un avec @ pour le prévenir. C'est idéal pour valider une affiche à distance avant de la publier.\n\nSi vous êtes une organisation ou une équipe (église, association), tu peux créer un « dossier » partagé où tout le monde retrouve les modèles, logos et visuels validés. Cela évite que chacun reparte de zéro et garde une image cohérente.\n\nAttention aux droits : ne donne le droit de modifier qu'aux personnes de confiance, car elles peuvent tout changer. Tu peux dupliquer un design (« Faire une copie ») avant de le confier, pour garder ton original intact. Rien n'est jamais perdu : Canva conserve un historique des versions que tu peux restaurer.",
            ht: "Canva pèmèt plizyè moun travay sou menm design lan, tankou nan yon dokiman pataje. Klike sou « Pataje », antre adrès imel kòlèg ou yo, epi chwazi dwa yo : « ka modifye » pou ko-kreye, « ka kòmante » pou bay yon avi, oswa « ka gade » pou senpleman gade.\n\nChak moun wè chanjman yo an tan reyèl. Pou diskite san manyen design lan, sèvi ak kòmantè yo : seleksyone yon eleman, ajoute yon nòt, epi mansyone yon moun ak @ pou avèti l. Sa ideyal pou valide yon afich adistans anvan ou pibliye l.\n\nSi nou se yon òganizasyon oswa yon ekip (legliz, asosyasyon), ou ka kreye yon « dosye » pataje kote tout moun jwenn modèl, logo ak vizyèl ki valide yo. Sa evite chak moun repati depi zewo epi kenbe yon imaj koyeran.\n\nFè atansyon ak dwa yo : bay dwa modifye a sèlman moun ou fè konfyans, paske yo ka chanje tout bagay. Ou ka double yon design (« Fè yon kopi ») anvan ou konfye l, pou kenbe orijinal ou entak. Anyen pa janm pèdi : Canva konsève yon istorik vèsyon ou ka restore.",
            en: "Canva lets several people work on the same design, like a shared document. Click \"Share\", enter your colleagues' email addresses, and choose their rights: \"can edit\" to co-create, \"can comment\" to give feedback, or \"can view\" to only look.\n\nEveryone sees the changes in real time. To discuss without touching the design, use comments: select an element, add a note, and mention someone with @ to alert them. It is ideal for approving a poster remotely before publishing it.\n\nIf you are an organisation or a team (church, association), you can create a shared \"folder\" where everyone finds the approved templates, logos and visuals. This stops each person starting from scratch and keeps a consistent image.\n\nMind the rights: only give edit rights to people you trust, since they can change everything. You can duplicate a design (\"Make a copy\") before handing it over, to keep your original intact. Nothing is ever lost: Canva keeps a version history you can restore.",
            es: "Canva permite que varias personas trabajen en el mismo diseño, como en un documento compartido. Haz clic en «Compartir», introduce el correo de tus colegas, y elige sus permisos: «puede editar» para co-crear, «puede comentar» para opinar, o «puede ver» para solo mirar.\n\nCada uno ve los cambios en tiempo real. Para debatir sin tocar el diseño, usa los comentarios: selecciona un elemento, añade una nota, y menciona a alguien con @ para avisarle. Es ideal para validar un cartel a distancia antes de publicarlo.\n\nSi sois una organización o un equipo (iglesia, asociación), puedes crear una «carpeta» compartida donde todos encuentran las plantillas, logos y visuales aprobados. Así evitas que cada uno empiece de cero y mantienes una imagen coherente.\n\nCuidado con los permisos: da el permiso de editar solo a personas de confianza, porque pueden cambiarlo todo. Puedes duplicar un diseño («Hacer una copia») antes de confiarlo, para conservar tu original intacto. Nada se pierde nunca: Canva guarda un historial de versiones que puedes restaurar.",
          },
          keyPoints: {
            fr: ["Partager avec des droits : modifier, commenter ou consulter", "Commenter et mentionner avec @ pour valider à distance", "Dossiers partagés pour une équipe cohérente", "Dupliquer avant de confier ; l'historique restaure les versions"],
            ht: ["Pataje ak dwa : modifye, kòmante oswa gade", "Kòmante epi mansyone ak @ pou valide adistans", "Dosye pataje pou yon ekip koyeran", "Double anvan ou konfye ; istorik la restore vèsyon yo"],
            en: ["Share with rights: edit, comment or view", "Comment and mention with @ to approve remotely", "Shared folders for a consistent team", "Copy before handing over; history restores versions"],
            es: ["Compartir con permisos: editar, comentar o ver", "Comentar y mencionar con @ para validar a distancia", "Carpetas compartidas para un equipo coherente", "Copiar antes de confiar; el historial restaura versiones"],
          },
          exercise: {
            fr: "Partage un design avec un ami ou un collègue en lui donnant le droit de commenter. Demande-lui un retour via un commentaire, réponds-y, puis applique une modification. Fais d'abord une copie pour garder ton original.",
            ht: "Pataje yon design ak yon zanmi oswa yon kòlèg pandan w ap ba li dwa pou kòmante. Mande l yon retou via yon kòmantè, reponn li, epi aplike yon modifikasyon. Fè yon kopi dabò pou kenbe orijinal ou.",
            en: "Share a design with a friend or colleague, giving them comment rights. Ask them for feedback via a comment, reply to it, then apply a change. Make a copy first to keep your original.",
            es: "Comparte un diseño con un amigo o colega dándole permiso para comentar. Pídele su opinión con un comentario, respóndele, y aplica una modificación. Haz primero una copia para conservar tu original.",
          },
        },
      ],
    },
  ],
};

export default canva;
