import { CourseContent } from "./types";

const chatgptIa: CourseContent = {
  slug: "chatgpt-ia",
  intro: {
    fr: "Comprendre l'intelligence artificielle et apprendre à utiliser ChatGPT au quotidien pour apprendre, écrire et travailler — avec discernement, en connaissant ses limites.",
    ht: "Konprann entèlijans atifisyèl epi aprann sèvi ak ChatGPT chak jou pou aprann, ekri ak travay — ak disèneman, pandan ou konnen limit li yo.",
    en: "Understand artificial intelligence and learn to use ChatGPT every day to learn, write and work — with discernment, knowing its limits.",
    es: "Comprender la inteligencia artificial y aprender a usar ChatGPT en el día a día para aprender, escribir y trabajar — con discernimiento, conociendo sus límites.",
  },
  modules: [
    {
      title: { fr: "Comprendre l'intelligence artificielle", ht: "Konprann entèlijans atifisyèl", en: "Understanding artificial intelligence", es: "Comprender la inteligencia artificial" },
      lessons: [
        {
          slug: "quest-ce-que-lia",
          title: { fr: "Qu'est-ce que l'intelligence artificielle ?", ht: "Kisa entèlijans atifisyèl ye ?", en: "What is artificial intelligence?", es: "¿Qué es la inteligencia artificial?" },
          videoId: "",
          content: {
            fr: "L'intelligence artificielle (IA) désigne des programmes informatiques capables d'accomplir des tâches qui demandaient autrefois un cerveau humain : comprendre du texte, reconnaître une image, traduire une langue ou répondre à une question. L'IA n'est pas magique et elle ne « pense » pas comme nous : elle calcule des probabilités à partir d'énormes quantités d'exemples.\n\nChatGPT est un type d'IA appelé « modèle de langage ». Il a été entraîné en lisant des milliards de phrases, et il a appris quels mots ont tendance à suivre quels autres. Quand tu lui écris, il devine le texte le plus probable en réponse, mot après mot. C'est pourquoi il écrit si naturellement, tout en pouvant se tromper.\n\nTu utilises probablement déjà l'IA sans le savoir : les suggestions de ton clavier, les recommandations de vidéos, les filtres anti-spam de ta boîte mail. Comprendre ce qu'est réellement l'IA t'aide à t'en servir comme d'un outil utile, ni comme d'un oracle infaillible, ni comme d'une menace mystérieuse.",
            ht: "Entèlijans atifisyèl (IA) se pwogram enfòmatik ki kapab fè travay ki te konn mande yon sèvo imen : konprann tèks, rekonèt yon imaj, tradui yon lang oswa reponn yon kesyon. IA pa majik e li pa « panse » tankou nou : li kalkile pwobabilite apati gwo kantite egzanp.\n\nChatGPT se yon kalite IA yo rele « modèl langaj ». Yo te antrene l lè l li milya fraz, epi li aprann ki mo gen tandans swiv ki lòt. Lè ou ekri l, li devine tèks ki pi pwobab la kòm repons, mo apre mo. Se poutèt sa li ekri tèlman natirèlman, menm si li ka fè erè.\n\nOu pwobableman deja sèvi ak IA san ou pa konnen : sijesyon klavye ou, rekòmandasyon videyo, filtè anti-spam nan bwat imel ou. Konprann sa IA ye reyèlman ede ou sèvi avè l kòm yon zouti itil, ni kòm yon oracle ki pa janm fè erè, ni kòm yon menas mistik.",
            en: "Artificial intelligence (AI) refers to computer programs able to do tasks that once required a human brain: understanding text, recognising an image, translating a language or answering a question. AI is not magic and it does not \"think\" like us: it calculates probabilities from huge amounts of examples.\n\nChatGPT is a type of AI called a \"language model\". It was trained by reading billions of sentences, and it learned which words tend to follow which. When you write to it, it guesses the most likely text in reply, word after word. That is why it writes so naturally, while still being able to get things wrong.\n\nYou probably already use AI without knowing it: your keyboard suggestions, video recommendations, the spam filters in your inbox. Understanding what AI really is helps you use it as a useful tool — neither as an infallible oracle nor as a mysterious threat.",
            es: "La inteligencia artificial (IA) designa programas informáticos capaces de realizar tareas que antes requerían un cerebro humano: comprender texto, reconocer una imagen, traducir un idioma o responder una pregunta. La IA no es magia y no «piensa» como nosotros: calcula probabilidades a partir de enormes cantidades de ejemplos.\n\nChatGPT es un tipo de IA llamado «modelo de lenguaje». Se entrenó leyendo miles de millones de frases, y aprendió qué palabras tienden a seguir a cuáles. Cuando le escribes, adivina el texto más probable como respuesta, palabra tras palabra. Por eso escribe con tanta naturalidad, aunque también puede equivocarse.\n\nProbablemente ya usas la IA sin saberlo: las sugerencias de tu teclado, las recomendaciones de videos, los filtros antispam de tu correo. Entender qué es realmente la IA te ayuda a usarla como una herramienta útil, ni como un oráculo infalible ni como una amenaza misteriosa.",
          },
          keyPoints: {
            fr: ["L'IA calcule des probabilités, elle ne « pense » pas", "ChatGPT devine le texte le plus probable, mot après mot", "On utilise déjà l'IA au quotidien sans s'en rendre compte", "Un outil utile : ni oracle infaillible, ni menace mystérieuse"],
            ht: ["IA kalkile pwobabilite, li pa « panse »", "ChatGPT devine tèks ki pi pwobab la, mo apre mo", "Nou deja sèvi ak IA chak jou san nou pa konnen", "Yon zouti itil : ni oracle ki pa fè erè, ni menas mistik"],
            en: ["AI calculates probabilities, it does not \"think\"", "ChatGPT guesses the most likely text, word by word", "We already use AI daily without realising it", "A useful tool: neither infallible oracle nor mysterious threat"],
            es: ["La IA calcula probabilidades, no «piensa»", "ChatGPT adivina el texto más probable, palabra a palabra", "Ya usamos la IA a diario sin darnos cuenta", "Una herramienta útil: ni oráculo infalible ni amenaza misteriosa"],
          },
          exercise: {
            fr: "Fais la liste de trois endroits où tu rencontres déjà l'IA dans ta journée (clavier, vidéos, spam, traduction). Puis demande à ChatGPT : « Explique-moi en trois phrases simples comment tu fonctionnes. » Compare sa réponse avec ce que tu viens d'apprendre.",
            ht: "Fè lis twa kote ou deja rankontre IA nan jounen ou (klavye, videyo, spam, tradiksyon). Apre sa, mande ChatGPT : « Eksplike m nan twa fraz senp kijan ou fonksyone. » Konpare repons li ak sa ou fèk aprann.",
            en: "List three places where you already meet AI in your day (keyboard, videos, spam, translation). Then ask ChatGPT: \"Explain in three simple sentences how you work.\" Compare its answer with what you have just learned.",
            es: "Haz una lista de tres lugares donde ya te encuentras con la IA en tu día (teclado, videos, spam, traducción). Luego pregunta a ChatGPT: «Explícame en tres frases simples cómo funcionas.» Compara su respuesta con lo que acabas de aprender.",
          },
        },
        {
          slug: "premiers-pas-chatgpt",
          title: { fr: "Premiers pas avec ChatGPT", ht: "Premye pa ak ChatGPT", en: "First steps with ChatGPT", es: "Primeros pasos con ChatGPT" },
          videoId: "",
          content: {
            fr: "Pour utiliser ChatGPT, rends-toi sur chat.openai.com ou installe l'application, puis crée un compte gratuit. Tu arrives sur une simple zone de discussion : tu écris ta question ou ta demande en bas, tu appuies sur Entrée, et la réponse s'affiche. Tu peux écrire dans ta langue, y compris en créole, en français ou en espagnol.\n\nLa conversation garde le fil : tu peux répondre « rends-le plus court » ou « explique autrement » sans tout réécrire, et ChatGPT tiendra compte de ce qui précède. Chaque nouvelle discussion, en revanche, repart de zéro : il ne se souvient pas d'une conversation à l'autre, sauf paramètres spécifiques.\n\nCommence par des demandes simples pour prendre l'habitude : « Explique-moi la photosynthèse comme à un enfant », « Corrige les fautes de ce message », « Donne-moi cinq idées de titres ». Plus tu pratiques, plus tu comprends comment formuler pour obtenir ce que tu veux.",
            ht: "Pou sèvi ak ChatGPT, ale sou chat.openai.com oswa enstale aplikasyon an, epi kreye yon kont gratis. Ou rive sou yon senp zòn diskisyon : ou ekri kesyon oswa demann ou anba, ou peze Antre, epi repons la parèt. Ou ka ekri nan lang ou, ki gen ladan kreyòl, franse oswa panyòl.\n\nKonvèsasyon an kenbe fil la : ou ka reponn « fè l pi kout » oswa « eksplike l yon lòt jan » san reekri tout bagay, epi ChatGPT ap konsidere sa ki te vini anvan. Men chak nouvo diskisyon repati depi zewo : li pa sonje yon konvèsasyon nan yon lòt, sof si gen paramèt espesifik.\n\nKòmanse ak demann senp pou pran abitid la : « Eksplike m fotosentèz tankou pou yon timoun », « Korije fot nan mesaj sa a », « Ban m senk lide tit ». Plis ou pratike, plis ou konprann kijan pou fòmile pou jwenn sa ou vle.",
            en: "To use ChatGPT, go to chat.openai.com or install the app, then create a free account. You land on a simple chat area: you type your question or request at the bottom, press Enter, and the answer appears. You can write in your own language, including Creole, French or Spanish.\n\nThe conversation keeps its thread: you can reply \"make it shorter\" or \"explain it another way\" without rewriting everything, and ChatGPT will take the earlier messages into account. Each new chat, however, starts from scratch: it does not remember from one conversation to another, unless specific settings are on.\n\nStart with simple requests to build the habit: \"Explain photosynthesis to me like I'm a child\", \"Fix the mistakes in this message\", \"Give me five title ideas\". The more you practise, the more you understand how to phrase things to get what you want.",
            es: "Para usar ChatGPT, entra en chat.openai.com o instala la aplicación, y crea una cuenta gratuita. Llegas a una simple zona de conversación: escribes tu pregunta o petición abajo, pulsas Enter y aparece la respuesta. Puedes escribir en tu idioma, incluidos el creole, el francés o el español.\n\nLa conversación mantiene el hilo: puedes responder «hazlo más corto» o «explícalo de otra manera» sin reescribir todo, y ChatGPT tendrá en cuenta lo anterior. Cada conversación nueva, en cambio, empieza de cero: no recuerda de una charla a otra, salvo con ajustes específicos.\n\nEmpieza con peticiones simples para tomar el hábito: «Explícame la fotosíntesis como a un niño», «Corrige las faltas de este mensaje», «Dame cinco ideas de títulos». Cuanto más practiques, mejor entenderás cómo formular para obtener lo que quieres.",
          },
          keyPoints: {
            fr: ["Compte gratuit sur chat.openai.com ou l'appli", "La conversation garde le fil, une nouvelle discussion repart de zéro", "Commencer par des demandes simples pour pratiquer", "Écrire dans sa langue : créole, français ou espagnol"],
            ht: ["Kont gratis sou chat.openai.com oswa aplikasyon an", "Konvèsasyon an kenbe fil, yon nouvo diskisyon repati depi zewo", "Kòmanse ak demann senp pou pratike", "Ekri nan lang ou : kreyòl, franse oswa panyòl"],
            en: ["Free account at chat.openai.com or the app", "The chat keeps its thread, a new chat restarts fresh", "Start with simple requests to practise", "Write in your own language: Creole, French or Spanish"],
            es: ["Cuenta gratuita en chat.openai.com o la app", "La conversación mantiene el hilo, una nueva empieza de cero", "Empezar con peticiones simples para practicar", "Escribir en tu idioma: creole, francés o español"],
          },
          exercise: {
            fr: "Crée ton compte gratuit et lance trois demandes simples dans ta langue : fais expliquer une notion à un enfant, corriger un message, et proposer cinq titres. Puis réponds « rends-le plus court » pour voir comment la conversation garde le fil.",
            ht: "Kreye kont gratis ou epi lanse twa demann senp nan lang ou : fè eksplike yon nosyon pou yon timoun, korije yon mesaj, epi pwopoze senk tit. Apre sa, reponn « fè l pi kout » pou wè kijan konvèsasyon an kenbe fil la.",
            en: "Create your free account and try three simple requests in your language: have it explain a concept to a child, fix a message, and suggest five titles. Then reply \"make it shorter\" to see how the conversation keeps its thread.",
            es: "Crea tu cuenta gratuita y lanza tres peticiones simples en tu idioma: que explique un concepto a un niño, corrija un mensaje, y proponga cinco títulos. Luego responde «hazlo más corto» para ver cómo la conversación mantiene el hilo.",
          },
        },
        {
          slug: "panorama-outils-ia",
          title: { fr: "Les différents outils d'IA", ht: "Diferan zouti IA yo", en: "The different AI tools", es: "Las diferentes herramientas de IA" },
          videoId: "",
          content: {
            fr: "ChatGPT n'est pas la seule IA. Il existe aujourd'hui une famille d'outils, chacun spécialisé. Les IA de texte (ChatGPT, Gemini, Claude) écrivent et répondent. Les IA d'image (comme celles intégrées à Canva, ou Midjourney) créent des visuels à partir d'une description. D'autres transcrivent la voix, traduisent, ou résument des vidéos.\n\nBeaucoup d'outils que tu utilises déjà intègrent l'IA sans le dire : le correcteur de ton téléphone, la traduction automatique, les sous-titres générés, la retouche photo. Reconnaître l'IA autour de toi t'aide à comprendre ce qu'elle sait faire — et à ne pas t'en méfier inutilement.\n\nLe point commun de ces outils : ils partent d'une consigne (un texte, une image, un son) et produisent un résultat probable. Ils ne comprennent pas le monde comme un humain ; ils reconnaissent des motifs. C'est pourquoi ils sont impressionnants sur des tâches courantes mais peuvent échouer sur des cas rares ou très précis.\n\nPour débuter, concentre-toi sur une IA de texte comme ChatGPT : c'est la plus polyvalente et la plus simple. Quand tu seras à l'aise, tu pourras explorer une IA d'image pour illustrer tes créations, ou un outil de traduction pour communiquer dans plusieurs langues. Choisis l'outil selon le besoin, pas l'inverse.",
            ht: "ChatGPT pa sèl IA a. Jodi a gen yon fanmi zouti, chak espesyalize. IA tèks yo (ChatGPT, Gemini, Claude) ekri epi reponn. IA imaj yo (tankou sa ki entegre nan Canva, oswa Midjourney) kreye vizyèl apati yon deskripsyon. Lòt transkri vwa, tradui, oswa rezime videyo.\n\nAnpil zouti ou deja sèvi entegre IA san yo pa di l : korektè telefòn ou, tradiksyon otomatik, sou-tit ki jenere, retouch foto. Rekonèt IA otou ou ede ou konprann sa li ka fè — epi pa mefye ou de li san rezon.\n\nSa tout zouti sa yo gen an komen : yo pati ak yon konsiy (yon tèks, yon imaj, yon son) epi yo pwodui yon rezilta pwobab. Yo pa konprann mond lan tankou yon imen ; yo rekonèt modèl. Se poutèt sa yo enpresyonan sou travay òdinè men yo ka echwe sou ka ki ra oswa trè presi.\n\nPou kòmanse, konsantre sou yon IA tèks tankou ChatGPT : se pi polivalan an epi pi senp lan. Lè ou alèz, ou ka eksplore yon IA imaj pou ilistre kreyasyon ou, oswa yon zouti tradiksyon pou kominike nan plizyè lang. Chwazi zouti a selon bezwen an, pa lòt jan.",
            en: "ChatGPT is not the only AI. Today there is a family of tools, each specialised. Text AIs (ChatGPT, Gemini, Claude) write and answer. Image AIs (like those built into Canva, or Midjourney) create visuals from a description. Others transcribe voice, translate, or summarise videos.\n\nMany tools you already use include AI without saying so: your phone's autocorrect, automatic translation, generated subtitles, photo retouching. Recognising the AI around you helps you understand what it can do — and not distrust it needlessly.\n\nWhat these tools have in common: they start from an instruction (a text, an image, a sound) and produce a likely result. They don't understand the world like a human; they recognise patterns. That is why they are impressive on common tasks but can fail on rare or very precise cases.\n\nTo start, focus on a text AI like ChatGPT: it is the most versatile and the simplest. Once you are comfortable, you can explore an image AI to illustrate your creations, or a translation tool to communicate in several languages. Choose the tool according to the need, not the other way round.",
            es: "ChatGPT no es la única IA. Hoy existe una familia de herramientas, cada una especializada. Las IA de texto (ChatGPT, Gemini, Claude) escriben y responden. Las IA de imagen (como las integradas en Canva, o Midjourney) crean visuales a partir de una descripción. Otras transcriben la voz, traducen, o resumen videos.\n\nMuchas herramientas que ya usas incorporan IA sin decirlo: el corrector de tu teléfono, la traducción automática, los subtítulos generados, el retoque de fotos. Reconocer la IA a tu alrededor te ayuda a entender lo que sabe hacer — y a no desconfiar de ella sin motivo.\n\nLo que estas herramientas tienen en común: parten de una instrucción (un texto, una imagen, un sonido) y producen un resultado probable. No entienden el mundo como un humano; reconocen patrones. Por eso son impresionantes en tareas corrientes pero pueden fallar en casos raros o muy precisos.\n\nPara empezar, concéntrate en una IA de texto como ChatGPT: es la más versátil y la más simple. Cuando te sientas cómodo, podrás explorar una IA de imagen para ilustrar tus creaciones, o una herramienta de traducción para comunicarte en varios idiomas. Elige la herramienta según la necesidad, no al revés.",
          },
          keyPoints: {
            fr: ["Des IA différentes : texte, image, voix, traduction", "Beaucoup d'applis intègrent déjà l'IA discrètement", "Toutes partent d'une consigne et produisent un résultat probable", "Débuter avec une IA de texte, puis élargir selon le besoin"],
            ht: ["Diferan IA : tèks, imaj, vwa, tradiksyon", "Anpil app deja entegre IA an silans", "Tout pati ak yon konsiy epi pwodui yon rezilta pwobab", "Kòmanse ak yon IA tèks, epi elaji selon bezwen"],
            en: ["Different AIs: text, image, voice, translation", "Many apps already include AI quietly", "All start from an instruction and produce a likely result", "Start with a text AI, then widen as needed"],
            es: ["Diferentes IA: texto, imagen, voz, traducción", "Muchas apps ya incorporan IA de forma discreta", "Todas parten de una instrucción y producen un resultado probable", "Empezar con una IA de texto, y ampliar según la necesidad"],
          },
          exercise: {
            fr: "Repère trois outils d'IA que tu utilises peut-être déjà (correcteur, traduction, recommandations, sous-titres). Puis teste une IA de texte et, si tu peux, un générateur d'image (dans Canva par exemple) avec la même idée, et compare ce que chacun produit.",
            ht: "Repere twa zouti IA ou petèt deja sèvi (korektè, tradiksyon, rekòmandasyon, sou-tit). Apre sa, teste yon IA tèks epi, si ou ka, yon jeneratè imaj (nan Canva pa egzanp) ak menm lide a, epi konpare sa chak pwodui.",
            en: "Spot three AI tools you may already use (autocorrect, translation, recommendations, subtitles). Then test a text AI and, if you can, an image generator (in Canva for example) with the same idea, and compare what each produces.",
            es: "Detecta tres herramientas de IA que quizá ya uses (corrector, traducción, recomendaciones, subtítulos). Luego prueba una IA de texto y, si puedes, un generador de imágenes (en Canva por ejemplo) con la misma idea, y compara lo que produce cada uno.",
          },
        },
      ],
    },
    {
      title: { fr: "Bien écrire ses consignes (prompts)", ht: "Byen ekri konsiy ou (prompt)", en: "Writing good prompts", es: "Escribir buenas instrucciones (prompts)" },
      lessons: [
        {
          slug: "ecrire-bon-prompt",
          title: { fr: "L'art d'écrire une bonne consigne", ht: "Atizay pou ekri yon bon konsiy", en: "The art of writing a good prompt", es: "El arte de escribir una buena instrucción" },
          videoId: "",
          content: {
            fr: "Un « prompt » est simplement la consigne que tu donnes à l'IA. La qualité de la réponse dépend directement de la qualité de ta demande. La règle de base : sois précis. Au lieu de « parle-moi du café », demande « explique en 5 phrases simples comment cultiver le café en Haïti, pour un débutant ».\n\nUne bonne consigne contient souvent quatre éléments : le rôle (« agis comme un professeur »), la tâche (« résume ce texte »), le contexte (« pour des élèves de 12 ans ») et le format voulu (« en trois points »). Tu n'as pas besoin des quatre à chaque fois, mais plus tu précises, meilleur est le résultat.\n\nN'hésite pas à dialoguer et à corriger : si la réponse ne convient pas, dis pourquoi. « C'est trop long », « ajoute un exemple concret », « écris-le dans un ton plus chaleureux ». Traiter ChatGPT comme un assistant à qui tu expliques clairement ce que tu veux donne toujours de meilleurs résultats.",
            ht: "Yon « prompt » se senpleman konsiy ou bay IA a. Kalite repons la depann dirèkteman de kalite demann ou. Règ debaz la : se presi. Olye « pale m de kafe », mande « eksplike nan 5 fraz senp kijan pou kiltive kafe an Ayiti, pou yon debitan ».\n\nYon bon konsiy souvan gen kat eleman : wòl la (« aji tankou yon pwofesè »), travay la (« rezime tèks sa a »), kontèks la (« pou elèv 12 an ») ak fòma ou vle a (« nan twa pwen »). Ou pa bezwen kat yo chak fwa, men plis ou presi, pi bon rezilta a.\n\nPa ezite dyaloge epi korije : si repons la pa bon, di poukisa. « Li twò long », « ajoute yon egzanp konkrè », « ekri l nan yon ton pi cho ». Trete ChatGPT tankou yon asistan ou eksplike klèman sa ou vle bay toujou pi bon rezilta.",
            en: "A \"prompt\" is simply the instruction you give the AI. The quality of the answer depends directly on the quality of your request. Basic rule: be specific. Instead of \"tell me about coffee\", ask \"explain in 5 simple sentences how to grow coffee in Haiti, for a beginner\".\n\nA good prompt often has four parts: the role (\"act as a teacher\"), the task (\"summarise this text\"), the context (\"for 12-year-old students\") and the wanted format (\"in three points\"). You don't need all four every time, but the more specific you are, the better the result.\n\nDon't hesitate to go back and forth and correct: if the answer doesn't fit, say why. \"It's too long\", \"add a concrete example\", \"write it in a warmer tone\". Treating ChatGPT as an assistant to whom you clearly explain what you want always gives better results.",
            es: "Un «prompt» es simplemente la instrucción que le das a la IA. La calidad de la respuesta depende directamente de la calidad de tu petición. Regla básica: sé preciso. En vez de «háblame del café», pide «explica en 5 frases simples cómo cultivar café en Haití, para un principiante».\n\nUna buena instrucción suele tener cuatro elementos: el rol («actúa como profesor»), la tarea («resume este texto»), el contexto («para alumnos de 12 años») y el formato deseado («en tres puntos»). No necesitas los cuatro cada vez, pero cuanto más preciso seas, mejor será el resultado.\n\nNo dudes en dialogar y corregir: si la respuesta no sirve, di por qué. «Es demasiado largo», «añade un ejemplo concreto», «escríbelo en un tono más cálido». Tratar a ChatGPT como un asistente al que le explicas claramente lo que quieres siempre da mejores resultados.",
          },
          keyPoints: {
            fr: ["Être précis : rôle, tâche, contexte, format", "Plus la consigne est claire, meilleure est la réponse", "Corriger en dialoguant : « trop long », « ajoute un exemple »", "Un assistant à qui on explique clairement ce qu'on veut"],
            ht: ["Se presi : wòl, travay, kontèks, fòma", "Plis konsiy la klè, pi bon repons la", "Korije nan dyaloge : « twò long », « ajoute yon egzanp »", "Yon asistan ou eksplike klèman sa ou vle"],
            en: ["Be specific: role, task, context, format", "The clearer the prompt, the better the answer", "Correct by dialoguing: \"too long\", \"add an example\"", "An assistant to whom you clearly explain what you want"],
            es: ["Ser preciso: rol, tarea, contexto, formato", "Cuanto más clara la instrucción, mejor la respuesta", "Corregir dialogando: «muy largo», «añade un ejemplo»", "Un asistente al que le explicas claramente lo que quieres"],
          },
          exercise: {
            fr: "Prends une question banale (« parle-moi du café ») et réécris-la en prompt précis avec les quatre éléments : rôle, tâche, contexte, format. Envoie les deux versions à ChatGPT et compare la qualité des réponses.",
            ht: "Pran yon kesyon senp (« pale m de kafe ») epi reekri l an yon prompt presi ak kat eleman yo : wòl, travay, kontèks, fòma. Voye de vèsyon yo bay ChatGPT epi konpare kalite repons yo.",
            en: "Take a plain question (\"tell me about coffee\") and rewrite it as a precise prompt with the four parts: role, task, context, format. Send both versions to ChatGPT and compare the quality of the answers.",
            es: "Toma una pregunta banal («háblame del café») y reescríbela como un prompt preciso con los cuatro elementos: rol, tarea, contexto, formato. Envía las dos versiones a ChatGPT y compara la calidad de las respuestas.",
          },
        },
        {
          slug: "contexte-et-exemples",
          title: { fr: "Donner du contexte et des exemples", ht: "Bay kontèks ak egzanp", en: "Giving context and examples", es: "Dar contexto y ejemplos" },
          videoId: "",
          content: {
            fr: "Après la structure d'un prompt, le deuxième secret est le contexte. L'IA ne connaît pas ta situation : plus tu la décris, plus la réponse te correspond. Au lieu de « écris un message d'invitation », précise « écris une invitation chaleureuse à un culte de jeunes, dimanche 15 h, ton amical, en créole ».\n\nDonne aussi des exemples de ce que tu veux. Si tu montres une phrase dans le style souhaité, l'IA l'imite. Par exemple : « Voici mon style habituel : [colle un texte]. Écris le nouveau message dans le même ton. » Cette technique, montrer un modèle, améliore énormément le résultat.\n\nTu peux fournir des données à traiter : colle un texte, une liste, un tableau, et demande d'agir dessus (« résume ceci », « classe ces idées », « corrige cette lettre »). L'IA travaille alors sur TA matière, pas sur des généralités. Sépare bien ta consigne de tes données pour éviter la confusion.\n\nEnfin, précise ce que tu ne veux pas : « sans mots compliqués », « pas plus de 100 mots », « n'invente pas de chiffres ». Fixer des limites claires évite les réponses hors sujet. Le contexte et les exemples transforment une réponse générique en réponse sur mesure.",
            ht: "Apre estrikti yon prompt, dezyèm sekrè a se kontèks la. IA a pa konnen sitiyasyon ou : plis ou dekri l, plis repons la koresponn ak ou. Olye « ekri yon mesaj envitasyon », presize « ekri yon envitasyon cho pou yon kilt jèn, dimanch 3 è, ton zanmitay, an kreyòl ».\n\nBay egzanp de sa ou vle tou. Si ou montre yon fraz nan estil ou vle a, IA a imite l. Pa egzanp : « Men estil abityèl mwen : [kole yon tèks]. Ekri nouvo mesaj la nan menm ton an. » Teknik sa a, montre yon modèl, amelyore rezilta a anpil.\n\nOu ka bay done pou trete : kole yon tèks, yon lis, yon tablo, epi mande pou aji sou li (« rezime sa a », « klase lide sa yo », « korije lèt sa a »). IA a travay sou MATERYÈL ou, pa sou jeneralite. Separe byen konsiy ou ak done ou pou evite konfizyon.\n\nAnfen, presize sa ou pa vle : « san mo konplike », « pa plis pase 100 mo », « pa envante chif ». Fikse limit klè evite repons ki soti nan sijè a. Kontèks ak egzanp transfòme yon repons jeneral an yon repons sou mezi.",
            en: "After a prompt's structure, the second secret is context. The AI does not know your situation: the more you describe it, the more the answer fits you. Instead of \"write an invitation message\", specify \"write a warm invitation to a youth service, Sunday 3pm, friendly tone, in Creole\".\n\nAlso give examples of what you want. If you show a sentence in the style you want, the AI imitates it. For example: \"Here is my usual style: [paste a text]. Write the new message in the same tone.\" This technique, showing a model, hugely improves the result.\n\nYou can supply data to work on: paste a text, a list, a table, and ask it to act on that (\"summarise this\", \"sort these ideas\", \"fix this letter\"). The AI then works on YOUR material, not on generalities. Clearly separate your instruction from your data to avoid confusion.\n\nFinally, say what you don't want: \"no complicated words\", \"no more than 100 words\", \"don't invent figures\". Setting clear limits prevents off-topic answers. Context and examples turn a generic answer into a tailor-made one.",
            es: "Después de la estructura de un prompt, el segundo secreto es el contexto. La IA no conoce tu situación: cuanto más la describas, más se ajustará la respuesta a ti. En vez de «escribe un mensaje de invitación», especifica «escribe una invitación cálida a un culto de jóvenes, domingo a las 15 h, tono amistoso, en creole».\n\nDa también ejemplos de lo que quieres. Si muestras una frase con el estilo deseado, la IA lo imita. Por ejemplo: «Este es mi estilo habitual: [pega un texto]. Escribe el nuevo mensaje con el mismo tono.» Esta técnica, mostrar un modelo, mejora muchísimo el resultado.\n\nPuedes aportar datos para procesar: pega un texto, una lista, una tabla, y pide que actúe sobre ello («resume esto», «clasifica estas ideas», «corrige esta carta»). La IA trabaja entonces sobre TU material, no sobre generalidades. Separa bien tu instrucción de tus datos para evitar confusiones.\n\nPor último, indica lo que no quieres: «sin palabras complicadas», «no más de 100 palabras», «no inventes cifras». Fijar límites claros evita respuestas fuera de tema. El contexto y los ejemplos convierten una respuesta genérica en una respuesta a medida.",
          },
          keyPoints: {
            fr: ["Décrire ta situation : public, ton, langue, objectif", "Montrer un exemple du style voulu (l'IA l'imite)", "Coller tes propres données pour un travail sur mesure", "Dire aussi ce que tu ne veux pas (longueur, style)"],
            ht: ["Dekri sitiyasyon ou : piblik, ton, lang, objektif", "Montre yon egzanp estil ou vle a (IA a imite l)", "Kole pwòp done ou pou yon travay sou mezi", "Di tou sa ou pa vle (longè, estil)"],
            en: ["Describe your situation: audience, tone, language, goal", "Show an example of the style you want (the AI imitates it)", "Paste your own data for tailor-made work", "Also say what you don't want (length, style)"],
            es: ["Describir tu situación: público, tono, idioma, objetivo", "Mostrar un ejemplo del estilo deseado (la IA lo imita)", "Pegar tus propios datos para un trabajo a medida", "Decir también lo que no quieres (longitud, estilo)"],
          },
          exercise: {
            fr: "Prends une demande vague que tu as déjà faite et enrichis-la : ajoute le public, le ton, la langue et une limite de longueur. Colle un exemple de ton style. Compare la réponse avec et sans ce contexte.",
            ht: "Pran yon demann vag ou te deja fè epi anrichi l : ajoute piblik la, ton an, lang lan ak yon limit longè. Kole yon egzanp estil ou. Konpare repons la ak epi san kontèks sa a.",
            en: "Take a vague request you have already made and enrich it: add the audience, the tone, the language and a length limit. Paste an example of your style. Compare the answer with and without this context.",
            es: "Toma una petición vaga que ya hayas hecho y enriquécela: añade el público, el tono, el idioma y un límite de longitud. Pega un ejemplo de tu estilo. Compara la respuesta con y sin ese contexto.",
          },
        },
        {
          slug: "usages-concrets",
          title: { fr: "Usages concrets pour apprendre et travailler", ht: "Itilizasyon konkrè pou aprann ak travay", en: "Practical uses for learning and working", es: "Usos concretos para aprender y trabajar" },
          videoId: "",
          content: {
            fr: "ChatGPT est un excellent compagnon d'apprentissage. Tu peux lui demander d'expliquer une notion difficile avec des mots simples, de te poser des questions pour réviser, ou de traduire un texte. Pour apprendre une langue, demande-lui de dialoguer avec toi et de corriger tes phrases au fur et à mesure.\n\nPour le travail, il fait gagner un temps précieux : rédiger un e-mail poli, résumer un long document, préparer le plan d'un discours, générer des idées pour un projet, ou reformuler un texte maladroit. Tu peux lui coller un texte et demander « corrige les fautes et améliore le style, sans changer le sens ».\n\nAu quotidien, il aide aussi à organiser : établir une liste de courses à partir d'un menu de la semaine, planifier un emploi du temps, expliquer une démarche administrative. L'idée n'est pas qu'il fasse tout à ta place, mais qu'il t'aide à démarrer plus vite et à ne pas rester bloqué devant une page blanche.",
            ht: "ChatGPT se yon ekselan konpayon aprantisaj. Ou ka mande l eksplike yon nosyon difisil ak mo senp, poze ou kesyon pou revize, oswa tradui yon tèks. Pou aprann yon lang, mande l dyaloge avè ou epi korije fraz ou yo pandan w ap ale.\n\nPou travay, li fè ou genyen anpil tan : ekri yon imel poli, rezime yon long dokiman, prepare plan yon diskou, jenere lide pou yon pwojè, oswa reformile yon tèks ki pa byen ekri. Ou ka kole yon tèks epi mande « korije fot yo epi amelyore estil la, san chanje sans lan ».\n\nChak jou, li ede tou pou òganize : fè yon lis makèt apati yon meni semèn, planifye yon orè, eksplike yon demach administratif. Lide a se pa pou l fè tout bagay nan plas ou, men pou l ede ou kòmanse pi vit epi pa rete bloke devan yon paj vid.",
            en: "ChatGPT is an excellent learning companion. You can ask it to explain a hard idea in simple words, to quiz you for revision, or to translate a text. To learn a language, ask it to chat with you and correct your sentences as you go.\n\nFor work, it saves precious time: writing a polite email, summarising a long document, preparing the outline of a speech, generating ideas for a project, or rephrasing an awkward text. You can paste in a text and ask \"fix the mistakes and improve the style, without changing the meaning\".\n\nDay to day, it also helps you organise: building a shopping list from a week's menu, planning a schedule, explaining an administrative procedure. The point is not for it to do everything for you, but to help you start faster and avoid getting stuck in front of a blank page.",
            es: "ChatGPT es un excelente compañero de aprendizaje. Puedes pedirle que explique una idea difícil con palabras simples, que te haga preguntas para repasar, o que traduzca un texto. Para aprender un idioma, pídele que dialogue contigo y corrija tus frases sobre la marcha.\n\nPara el trabajo, ahorra un tiempo valioso: redactar un correo cortés, resumir un documento largo, preparar el guion de un discurso, generar ideas para un proyecto, o reformular un texto torpe. Puedes pegarle un texto y pedir «corrige las faltas y mejora el estilo, sin cambiar el sentido».\n\nEn el día a día, también ayuda a organizar: hacer una lista de compras a partir de un menú semanal, planificar un horario, explicar un trámite administrativo. La idea no es que lo haga todo por ti, sino que te ayude a arrancar más rápido y a no quedarte bloqueado ante una página en blanco.",
          },
          keyPoints: {
            fr: ["Apprendre : expliquer simplement, réviser, traduire", "Travailler : e-mails, résumés, plans, reformulations", "T'aider à démarrer, pas tout faire à ta place", "Un point de départ pour ne pas rester bloqué devant la page blanche"],
            ht: ["Aprann : eksplike senp, revize, tradui", "Travay : imel, rezime, plan, reformilasyon", "Ede ou kòmanse, pa fè tout bagay pou ou", "Yon pwen depa pou pa rete bloke devan paj vid la"],
            en: ["Learn: explain simply, revise, translate", "Work: emails, summaries, outlines, rephrasing", "Help you start, not do everything for you", "A starting point to avoid getting stuck at the blank page"],
            es: ["Aprender: explicar simple, repasar, traducir", "Trabajar: correos, resúmenes, guiones, reformulaciones", "Ayudarte a arrancar, no hacerlo todo por ti", "Un punto de partida para no quedarte bloqueado ante la página en blanco"],
          },
          exercise: {
            fr: "Choisis une tâche réelle de ta semaine : un e-mail à écrire, un texte long à résumer, ou une langue à réviser. Fais-toi aider par ChatGPT, puis relis et ajuste le résultat pour qu'il te ressemble.",
            ht: "Chwazi yon vrè travay nan semèn ou : yon imel pou ekri, yon long tèks pou rezime, oswa yon lang pou revize. Fè ChatGPT ede ou, epi reli ak ajiste rezilta a pou l sanble ak ou.",
            en: "Choose a real task from your week: an email to write, a long text to summarise, or a language to revise. Get ChatGPT to help, then reread and adjust the result so it sounds like you.",
            es: "Elige una tarea real de tu semana: un correo por escribir, un texto largo por resumir, o un idioma por repasar. Deja que ChatGPT te ayude, luego relee y ajusta el resultado para que se parezca a ti.",
          },
        },
      ],
    },
    {
      title: { fr: "Limites, esprit critique et éthique", ht: "Limit, lespri kritik ak etik", en: "Limits, critical thinking and ethics", es: "Límites, sentido crítico y ética" },
      lessons: [
        {
          slug: "limites-verification",
          title: { fr: "Les limites de l'IA et la vérification", ht: "Limit IA ak verifikasyon", en: "The limits of AI and verification", es: "Los límites de la IA y la verificación" },
          videoId: "",
          content: {
            fr: "ChatGPT peut se tromper avec assurance. Il lui arrive d'« inventer » des faits, des dates, des citations ou des sources qui n'existent pas : on appelle cela des « hallucinations ». Comme il vise le texte le plus probable, pas la vérité, il peut te répondre une bêtise sur un ton parfaitement confiant.\n\nRègle d'or : vérifie toujours les informations importantes auprès d'une source fiable. Pour un chiffre, une loi, une donnée médicale ou historique, ne te fie pas à la première réponse — recoupe avec un site officiel, un livre ou un spécialiste. L'IA est aussi limitée dans le temps : elle peut ne pas connaître les événements très récents.\n\nUtilise-la comme un point de départ, pas comme le dernier mot. Elle est excellente pour dégrossir, expliquer, donner des pistes ; elle n'est pas une autorité. Garde toujours ton propre jugement : c'est toi qui décides ce qui est vrai, juste et adapté à ta situation.",
            ht: "ChatGPT ka fè erè ak asirans. Pafwa li « envante » done, dat, sitasyon oswa sous ki pa egziste : yo rele sa « alisinasyon ». Kòm li vize tèks ki pi pwobab la, pa verite a, li ka reponn ou yon betiz sou yon ton ki gen konfyans nèt.\n\nRèg dò : toujou verifye enfòmasyon enpòtan yo nan yon sous ki fyab. Pou yon chif, yon lwa, yon done medikal oswa istorik, pa fè premye repons la konfyans — konpare ak yon sit ofisyèl, yon liv oswa yon espesyalis. IA a gen limit tou nan tan : li ka pa konnen evènman ki fèk pase yo.\n\nSèvi avè l kòm yon pwen depa, pa kòm dènye mo a. Li ekselan pou degwose, eksplike, bay pis ; li pa yon otorite. Toujou kenbe pwòp jijman ou : se ou menm ki deside sa ki vre, jis epi adapte ak sitiyasyon ou.",
            en: "ChatGPT can be wrong with confidence. It sometimes \"invents\" facts, dates, quotes or sources that don't exist: these are called \"hallucinations\". Since it aims for the most likely text, not the truth, it can hand you nonsense in a perfectly confident tone.\n\nGolden rule: always check important information against a reliable source. For a figure, a law, a medical or historical fact, don't trust the first answer — cross-check with an official website, a book or an expert. The AI is also limited in time: it may not know very recent events.\n\nUse it as a starting point, not the final word. It is excellent for roughing things out, explaining, giving leads; it is not an authority. Always keep your own judgement: you are the one who decides what is true, right and suited to your situation.",
            es: "ChatGPT puede equivocarse con seguridad. A veces «inventa» hechos, fechas, citas o fuentes que no existen: se les llama «alucinaciones». Como busca el texto más probable, no la verdad, puede darte una tontería con un tono perfectamente seguro.\n\nRegla de oro: verifica siempre la información importante con una fuente fiable. Para una cifra, una ley, un dato médico o histórico, no te fíes de la primera respuesta — contrasta con un sitio oficial, un libro o un especialista. La IA también está limitada en el tiempo: puede no conocer los eventos muy recientes.\n\nÚsala como punto de partida, no como la última palabra. Es excelente para desbastar, explicar, dar pistas; no es una autoridad. Conserva siempre tu propio juicio: eres tú quien decide qué es verdadero, justo y adecuado a tu situación.",
          },
          keyPoints: {
            fr: ["L'IA peut « halluciner » : inventer faits et sources", "Vérifier les infos importantes auprès d'une source fiable", "Point de départ, pas dernier mot : garder son jugement", "L'IA est limitée dans le temps : elle ignore les événements récents"],
            ht: ["IA ka « alisine » : envante done ak sous", "Verifye enfòmasyon enpòtan nan yon sous fyab", "Pwen depa, pa dènye mo : kenbe jijman ou", "IA gen limit nan tan : li pa konnen evènman ki fèk pase"],
            en: ["AI can \"hallucinate\": invent facts and sources", "Check important info against a reliable source", "A starting point, not the final word: keep your judgement", "AI is limited in time: it doesn't know recent events"],
            es: ["La IA puede «alucinar»: inventar hechos y fuentes", "Verificar la información importante con una fuente fiable", "Punto de partida, no última palabra: conserva tu juicio", "La IA está limitada en el tiempo: ignora los eventos recientes"],
          },
          exercise: {
            fr: "Demande à ChatGPT une information vérifiable (une date, un chiffre, une citation). Puis vérifie-la avec une source fiable (site officiel, livre). Note si l'IA avait raison, et garde ce réflexe pour toute info importante.",
            ht: "Mande ChatGPT yon enfòmasyon ou ka verifye (yon dat, yon chif, yon sitasyon). Apre sa, verifye l ak yon sous fyab (sit ofisyèl, liv). Note si IA a te gen rezon, epi kenbe abitid sa a pou tout enfòmasyon enpòtan.",
            en: "Ask ChatGPT for a verifiable piece of information (a date, a figure, a quote). Then check it against a reliable source (official website, book). Note whether the AI was right, and keep this reflex for any important info.",
            es: "Pide a ChatGPT una información verificable (una fecha, una cifra, una cita). Luego verifícala con una fuente fiable (sitio oficial, libro). Anota si la IA tenía razón, y conserva ese reflejo para toda información importante.",
          },
        },
        {
          slug: "proteger-donnees",
          title: { fr: "Protéger ses données et sa vie privée", ht: "Pwoteje done ou ak vi prive ou", en: "Protecting your data and privacy", es: "Proteger tus datos y tu privacidad" },
          videoId: "",
          content: {
            fr: "Quand tu écris à une IA en ligne, ton message part sur des serveurs et peut être conservé pour améliorer le service. Traite donc ChatGPT comme un espace semi-public, pas comme un coffre-fort. La règle simple : ne partage jamais ce que tu ne dirais pas à un inconnu.\n\nNe saisis jamais de données très sensibles : mots de passe, codes bancaires, numéro de carte, pièces d'identité, informations médicales détaillées, ou secrets qui concernent d'autres personnes. Si tu dois faire travailler l'IA sur un texte personnel, retire ou remplace les noms et les chiffres sensibles avant de le coller.\n\nVérifie les réglages de confidentialité. Dans ChatGPT, tu peux souvent désactiver l'utilisation de tes conversations pour l'entraînement, et supprimer l'historique. Prends deux minutes pour explorer ces paramètres, surtout si tu utilises l'outil pour du travail contenant des informations d'autrui.\n\nProtège aussi les autres. Si tu écris au sujet d'un membre de ta famille, d'un paroissien ou d'un client, ne donne pas d'informations qui permettraient de l'identifier. Utiliser l'IA de façon responsable, c'est aussi respecter la vie privée des gens dont tu parles.",
            ht: "Lè ou ekri yon IA sou entènèt, mesaj ou ale sou sèvè epi li ka konsève pou amelyore sèvis la. Kidonk trete ChatGPT tankou yon espas semi-piblik, pa tankou yon kòfrefò. Règ senp lan : pa janm pataje sa ou pa ta di yon etranje.\n\nPa janm antre done ki trè sansib : modpas, kòd bankè, nimewo kat, pyès idantite, enfòmasyon medikal detaye, oswa sekrè ki konsène lòt moun. Si ou dwe fè IA travay sou yon tèks pèsonèl, retire oswa ranplase non ak chif sansib yo anvan ou kole l.\n\nVerifye paramèt konfidansyalite yo. Nan ChatGPT, ou ka souvan dezaktive itilizasyon konvèsasyon ou pou antrènman, epi efase istorik la. Pran de minit pou eksplore paramèt sa yo, sitou si ou sèvi ak zouti a pou travay ki gen enfòmasyon lòt moun.\n\nPwoteje lòt moun tou. Si ou ekri sou yon manm fanmi ou, yon pawasyen oswa yon kliyan, pa bay enfòmasyon ki ta pèmèt idantifye l. Sèvi ak IA yon fason responsab, se respekte vi prive moun ou pale sou yo tou.",
            en: "When you write to an online AI, your message goes to servers and may be kept to improve the service. So treat ChatGPT as a semi-public space, not a safe. The simple rule: never share what you would not tell a stranger.\n\nNever enter very sensitive data: passwords, bank codes, card numbers, ID documents, detailed medical information, or secrets that concern other people. If you must have the AI work on a personal text, remove or replace the sensitive names and figures before pasting it.\n\nCheck the privacy settings. In ChatGPT, you can often turn off the use of your conversations for training, and delete the history. Take two minutes to explore these settings, especially if you use the tool for work containing other people's information.\n\nProtect others too. If you write about a family member, a parishioner or a client, don't give information that would identify them. Using AI responsibly also means respecting the privacy of the people you talk about.",
            es: "Cuando escribes a una IA en línea, tu mensaje va a servidores y puede conservarse para mejorar el servicio. Así que trata ChatGPT como un espacio semipúblico, no como una caja fuerte. La regla simple: nunca compartas lo que no le dirías a un desconocido.\n\nNunca introduzcas datos muy sensibles: contraseñas, códigos bancarios, números de tarjeta, documentos de identidad, información médica detallada, o secretos que conciernen a otras personas. Si debes hacer que la IA trabaje sobre un texto personal, quita o reemplaza los nombres y cifras sensibles antes de pegarlo.\n\nRevisa los ajustes de privacidad. En ChatGPT, a menudo puedes desactivar el uso de tus conversaciones para el entrenamiento, y borrar el historial. Dedica dos minutos a explorar esos ajustes, sobre todo si usas la herramienta para trabajo que contiene información de otros.\n\nProtege también a los demás. Si escribes sobre un familiar, un feligrés o un cliente, no des información que permita identificarlo. Usar la IA de forma responsable es también respetar la privacidad de las personas de quienes hablas.",
          },
          keyPoints: {
            fr: ["IA en ligne = espace semi-public, pas un coffre-fort", "Jamais de mots de passe, codes bancaires, données médicales", "Anonymiser un texte avant de le coller", "Régler la confidentialité et respecter la vie privée d'autrui"],
            ht: ["IA sou entènèt = espas semi-piblik, pa yon kòfrefò", "Pa janm modpas, kòd bankè, done medikal", "Anonimize yon tèks anvan ou kole l", "Regle konfidansyalite epi respekte vi prive lòt moun"],
            en: ["Online AI = semi-public space, not a safe", "Never passwords, bank codes, medical data", "Anonymise a text before pasting it", "Set privacy and respect others' privacy"],
            es: ["IA en línea = espacio semipúblico, no una caja fuerte", "Nunca contraseñas, códigos bancarios, datos médicos", "Anonimizar un texto antes de pegarlo", "Ajustar la privacidad y respetar la de los demás"],
          },
          exercise: {
            fr: "Avant de coller un vrai texte dans l'IA, entraîne-toi à l'anonymiser : remplace les noms, adresses et numéros par des repères génériques (« Madame X », « la ville »). Puis ouvre les réglages de confidentialité de ChatGPT et repère l'option d'historique.",
            ht: "Anvan ou kole yon vrè tèks nan IA a, pratike anonimize l : ranplase non, adrès ak nimewo ak repè jeneral (« Madan X », « vil la »). Apre sa, louvri paramèt konfidansyalite ChatGPT epi jwenn opsyon istorik la.",
            en: "Before pasting a real text into the AI, practise anonymising it: replace names, addresses and numbers with generic markers (\"Mrs X\", \"the town\"). Then open ChatGPT's privacy settings and find the history option.",
            es: "Antes de pegar un texto real en la IA, practica anonimizarlo: reemplaza nombres, direcciones y números por marcadores genéricos («Señora X», «la ciudad»). Luego abre los ajustes de privacidad de ChatGPT y encuentra la opción de historial.",
          },
        },
        {
          slug: "usage-ethique",
          title: { fr: "Utiliser l'IA de façon éthique et responsable", ht: "Sèvi ak IA yon fason etik e responsab", en: "Using AI ethically and responsibly", es: "Usar la IA de forma ética y responsable" },
          videoId: "",
          content: {
            fr: "L'IA est un outil puissant : à toi de t'en servir avec honnêteté. Ne présente pas comme entièrement de toi un travail écrit à 100 % par une machine, surtout dans un cadre scolaire ou professionnel où l'honnêteté compte. Sers-t'en pour t'aider à réfléchir et à améliorer, pas pour tricher ou tromper.\n\nProtège aussi tes informations : ne partage jamais avec ChatGPT des données très sensibles comme des mots de passe, des numéros de carte bancaire ou les secrets d'autres personnes. Ce que tu écris peut être conservé pour améliorer le service. Traite l'IA comme un espace semi-public, pas comme un journal intime.\n\nEnfin, garde un regard critique et bienveillant. L'IA reflète les données sur lesquelles elle a été entraînée : elle peut reproduire des préjugés ou des erreurs de notre société. Utilise-la pour construire, apprendre et servir les autres, jamais pour nuire, manipuler ou diffuser de fausses informations. La technologie est neutre ; c'est l'usage que tu en fais qui est bon ou mauvais.",
            ht: "IA se yon zouti pwisan : se ou menm pou sèvi avè l ak onètete. Pa prezante kòm antyèman pa ou yon travay yon machin ekri 100 % , sitou nan yon kad lekòl oswa pwofesyonèl kote onètete konte. Sèvi avè l pou ede ou reflechi epi amelyore, pa pou twonpe oswa tronpe.\n\nPwoteje enfòmasyon ou tou : pa janm pataje ak ChatGPT done ki trè sansib tankou modpas, nimewo kat bankè oswa sekrè lòt moun. Sa ou ekri ka konsève pou amelyore sèvis la. Trete IA kòm yon espas semi-piblik, pa kòm yon jounal entim.\n\nAnfen, kenbe yon gade kritik e byenveyan. IA reflete done yo te antrene l sou yo : li ka repwodui prejije oswa erè nan sosyete nou. Sèvi avè l pou konstwi, aprann epi sèvi lòt moun, pa janm pou fè mal, manipile oswa gaye fo enfòmasyon. Teknoloji a net ; se itilizasyon ou fè avè l ki bon oswa move.",
            en: "AI is a powerful tool: it's up to you to use it honestly. Don't present as entirely your own a piece written 100% by a machine, especially in a school or professional setting where honesty matters. Use it to help you think and improve, not to cheat or deceive.\n\nProtect your information too: never share highly sensitive data with ChatGPT such as passwords, bank card numbers or other people's secrets. What you type may be kept to improve the service. Treat AI as a semi-public space, not a private diary.\n\nFinally, keep a critical and kind eye. AI reflects the data it was trained on: it can reproduce biases or errors from our society. Use it to build, learn and serve others, never to harm, manipulate or spread false information. Technology is neutral; it is the use you make of it that is good or bad.",
            es: "La IA es una herramienta poderosa: depende de ti usarla con honestidad. No presentes como totalmente tuyo un trabajo escrito al 100 % por una máquina, sobre todo en un contexto escolar o profesional donde la honestidad importa. Úsala para ayudarte a pensar y mejorar, no para hacer trampa o engañar.\n\nProtege también tu información: nunca compartas con ChatGPT datos muy sensibles como contraseñas, números de tarjeta bancaria o secretos de otras personas. Lo que escribes puede conservarse para mejorar el servicio. Trata la IA como un espacio semipúblico, no como un diario íntimo.\n\nPor último, mantén una mirada crítica y benévola. La IA refleja los datos con los que fue entrenada: puede reproducir prejuicios o errores de nuestra sociedad. Úsala para construir, aprender y servir a los demás, nunca para dañar, manipular o difundir información falsa. La tecnología es neutra; es el uso que le das lo que es bueno o malo.",
          },
          keyPoints: {
            fr: ["Rester honnête : s'aider de l'IA, pas tricher", "Ne jamais partager de données sensibles (mots de passe, etc.)", "La technologie est neutre : c'est ton usage qui compte", "Utiliser l'IA pour construire et servir, jamais pour nuire"],
            ht: ["Rete onèt : ede ou ak IA, pa twonpe", "Pa janm pataje done sansib (modpas, elatriye)", "Teknoloji a net : se itilizasyon ou ki konte", "Sèvi ak IA pou konstwi epi sèvi, pa janm pou fè mal"],
            en: ["Stay honest: use AI to help, not to cheat", "Never share sensitive data (passwords, etc.)", "Technology is neutral: your use is what matters", "Use AI to build and serve, never to harm"],
            es: ["Ser honesto: apoyarse en la IA, no hacer trampa", "Nunca compartir datos sensibles (contraseñas, etc.)", "La tecnología es neutra: lo que cuenta es tu uso", "Usar la IA para construir y servir, nunca para dañar"],
          },
          exercise: {
            fr: "Relis un texte que tu comptes présenter et demande-toi : qu'est-ce qui vient de moi, qu'est-ce qui vient de l'IA ? Réécris au moins une partie avec tes propres mots, et vérifie que tu n'as partagé aucune donnée sensible.",
            ht: "Reli yon tèks ou gen entansyon prezante epi mande tèt ou : kisa ki soti nan mwen, kisa ki soti nan IA ? Reekri omwen yon pati ak pwòp mo ou, epi verifye ou pa pataje okenn done sansib.",
            en: "Reread a text you plan to present and ask yourself: what comes from me, what comes from the AI? Rewrite at least part of it in your own words, and check that you shared no sensitive data.",
            es: "Relee un texto que piensas presentar y pregúntate: ¿qué viene de mí, qué viene de la IA? Reescribe al menos una parte con tus propias palabras, y comprueba que no compartiste ningún dato sensible.",
          },
        },
      ],
    },
    {
      title: { fr: "L'IA au service de la foi et du ministère", ht: "IA nan sèvis lafwa ak ministè", en: "AI in the service of faith and ministry", es: "La IA al servicio de la fe y el ministerio" },
      lessons: [
        {
          slug: "ia-etude-et-foi",
          title: { fr: "L'IA au service de l'étude et de la foi", ht: "IA nan sèvis etid ak lafwa", en: "AI in the service of study and faith", es: "La IA al servicio del estudio y la fe" },
          videoId: "",
          content: {
            fr: "L'IA peut devenir un outil d'étude précieux pour approfondir ta foi, à condition de garder ton discernement. Tu peux lui demander d'expliquer le contexte historique d'un passage, de définir un mot ancien, ou de résumer les grandes idées d'un livre biblique. C'est un point de départ pour creuser, pas une autorité spirituelle.\n\nElle aide aussi à préparer et organiser. Un responsable peut demander un plan d'étude, des questions de discussion pour un groupe, ou des idées d'illustration pour rendre un enseignement clair. « Propose cinq questions de discussion sur le thème du pardon, pour des adolescents » donne rapidement une base à retravailler.\n\nReste vigilant : l'IA peut se tromper, mélanger des références ou inventer une citation. Vérifie toujours dans le texte source et auprès de personnes de confiance. Ne délègue jamais ton étude personnelle ni ta prière à une machine : l'outil éclaire la réflexion, il ne la remplace pas.\n\nUtilise-la pour servir, pas pour paraître. L'objectif n'est pas de réciter des réponses toutes faites, mais de mieux comprendre et de mieux transmettre. Laisse l'IA dégrossir le travail technique (mise en forme, synthèse, traduction) pour libérer ton temps et ton cœur pour l'essentiel.",
            ht: "IA ka vin yon zouti etid presye pou apwofondi lafwa ou, depi ou kenbe disèneman ou. Ou ka mande l eksplike kontèks istorik yon pasaj, defini yon mo ansyen, oswa rezime gwo lide yon liv biblik. Se yon pwen depa pou fouye, pa yon otorite espirityèl.\n\nLi ede tou pou prepare epi òganize. Yon responsab ka mande yon plan etid, kesyon diskisyon pou yon gwoup, oswa lide ilistrasyon pou fè yon ansèyman klè. « Pwopoze senk kesyon diskisyon sou tèm padon an, pou adolesan » bay rapidman yon baz pou retravay.\n\nRete vijilan : IA ka fè erè, melanje referans oswa envante yon sitasyon. Toujou verifye nan tèks sous la epi ak moun ou fè konfyans. Pa janm delege etid pèsonèl ou ni lapriyè ou bay yon machin : zouti a eklere refleksyon an, li pa ranplase l.\n\nSèvi avè l pou sèvi, pa pou parèt. Objektif la se pa resite repons ki deja fèt, men pou pi byen konprann epi pi byen transmèt. Kite IA degwose travay teknik la (mizanfòm, sentèz, tradiksyon) pou libere tan ou ak kè ou pou sa ki esansyèl.",
            en: "AI can become a valuable study tool to deepen your faith, provided you keep your discernment. You can ask it to explain the historical context of a passage, define an old word, or summarise the main ideas of a biblical book. It is a starting point for digging deeper, not a spiritual authority.\n\nIt also helps to prepare and organise. A leader can ask for a study outline, discussion questions for a group, or illustration ideas to make a teaching clear. \"Suggest five discussion questions on the theme of forgiveness, for teenagers\" quickly gives a base to rework.\n\nStay watchful: AI can be wrong, mix up references or invent a quote. Always check in the source text and with trusted people. Never delegate your personal study or your prayer to a machine: the tool lights up reflection, it does not replace it.\n\nUse it to serve, not to show off. The goal is not to recite ready-made answers, but to understand better and transmit better. Let AI rough out the technical work (formatting, synthesis, translation) to free your time and your heart for what matters.",
            es: "La IA puede convertirse en una valiosa herramienta de estudio para profundizar tu fe, siempre que conserves tu discernimiento. Puedes pedirle que explique el contexto histórico de un pasaje, defina una palabra antigua, o resuma las grandes ideas de un libro bíblico. Es un punto de partida para profundizar, no una autoridad espiritual.\n\nTambién ayuda a preparar y organizar. Un responsable puede pedir un plan de estudio, preguntas de discusión para un grupo, o ideas de ilustración para hacer clara una enseñanza. «Propón cinco preguntas de discusión sobre el tema del perdón, para adolescentes» da rápidamente una base para retrabajar.\n\nMantente vigilante: la IA puede equivocarse, mezclar referencias o inventar una cita. Verifica siempre en el texto fuente y con personas de confianza. Nunca delegues tu estudio personal ni tu oración a una máquina: la herramienta ilumina la reflexión, no la reemplaza.\n\nÚsala para servir, no para aparentar. El objetivo no es recitar respuestas hechas, sino comprender mejor y transmitir mejor. Deja que la IA desbaste el trabajo técnico (formato, síntesis, traducción) para liberar tu tiempo y tu corazón para lo esencial.",
          },
          keyPoints: {
            fr: ["Expliquer contexte, mots et idées d'un passage", "Préparer plans, questions et illustrations", "Toujours vérifier : l'IA n'est pas une autorité spirituelle", "Un outil qui éclaire, ne remplace ni étude ni prière"],
            ht: ["Eksplike kontèks, mo ak lide yon pasaj", "Prepare plan, kesyon ak ilistrasyon", "Toujou verifye : IA pa yon otorite espirityèl", "Yon zouti ki eklere, pa ranplase ni etid ni lapriyè"],
            en: ["Explain context, words and ideas of a passage", "Prepare outlines, questions and illustrations", "Always verify: AI is not a spiritual authority", "A tool that lights up, replaces neither study nor prayer"],
            es: ["Explicar contexto, palabras e ideas de un pasaje", "Preparar planes, preguntas e ilustraciones", "Verificar siempre: la IA no es una autoridad espiritual", "Una herramienta que ilumina, no reemplaza ni estudio ni oración"],
          },
          exercise: {
            fr: "Choisis un thème (l'espérance, le pardon) et demande à l'IA cinq questions de discussion et un court résumé du contexte. Vérifie chaque élément dans ta source, corrige ce qui est inexact, et garde seulement ce qui est juste et utile.",
            ht: "Chwazi yon tèm (esperans, padon) epi mande IA a senk kesyon diskisyon ak yon ti rezime kontèks la. Verifye chak eleman nan sous ou, korije sa ki pa egzak, epi kenbe sèlman sa ki jis epi itil.",
            en: "Choose a theme (hope, forgiveness) and ask the AI for five discussion questions and a short summary of the context. Check each element in your source, correct what is inaccurate, and keep only what is true and useful.",
            es: "Elige un tema (esperanza, perdón) y pide a la IA cinco preguntas de discusión y un breve resumen del contexto. Verifica cada elemento en tu fuente, corrige lo inexacto, y conserva solo lo que es verdadero y útil.",
          },
        },
        {
          slug: "ia-pour-le-ministere",
          title: { fr: "L'IA pour le ministère et la communication", ht: "IA pou ministè ak kominikasyon", en: "AI for ministry and communication", es: "La IA para el ministerio y la comunicación" },
          videoId: "",
          content: {
            fr: "Au-delà de l'étude, l'IA fait gagner un temps précieux dans la vie pratique d'une église, d'une association ou d'un petit ministère. Elle peut rédiger l'annonce d'un événement, un message de bienvenue, une lettre de remerciement, ou reformuler un communiqué maladroit en quelques secondes.\n\nElle aide à communiquer dans plusieurs langues. Dans une communauté où l'on parle créole, français et espagnol, tu peux faire traduire une annonce ou un chant, puis faire relire par une personne qui maîtrise la langue. L'IA dégrossit, l'humain valide : c'est le bon partage des rôles.\n\nPour l'organisation, demande-lui de préparer l'ordre du jour d'une réunion, un planning de bénévoles, une liste de tâches pour un événement, ou des idées de publications pour les réseaux sociaux. Combine-la avec un outil comme Canva : l'IA écrit le texte, Canva crée le visuel.\n\nGarde toujours ta voix et ton cœur. Un message de foi touche parce qu'il est sincère, pas parce qu'il est parfait. Relis, personnalise, ajoute ton expérience : l'IA t'aide à écrire plus vite, mais le témoignage, la chaleur et l'authenticité viennent de toi.",
            ht: "Anwo etid la, IA fè ou genyen tan presye nan lavi pratik yon legliz, yon asosyasyon oswa yon ti ministè. Li ka ekri anons yon aktivite, yon mesaj byenvini, yon lèt remèsiman, oswa reformile yon kominike ki pa byen ekri nan kèk segonn.\n\nLi ede kominike nan plizyè lang. Nan yon kominote kote yo pale kreyòl, franse ak panyòl, ou ka fè tradui yon anons oswa yon chan, epi fè yon moun ki metrize lang lan reli l. IA a degwose, moun lan valide : se bon pataj wòl la.\n\nPou òganizasyon, mande l prepare lòd du jou yon reyinyon, yon planin benevòl, yon lis travay pou yon aktivite, oswa lide piblikasyon pou rezo sosyal. Konbine l ak yon zouti tankou Canva : IA a ekri tèks la, Canva kreye vizyèl la.\n\nToujou kenbe vwa ou ak kè ou. Yon mesaj lafwa touche paske li sensè, pa paske li pafè. Reli, pèsonalize, ajoute eksperyans ou : IA a ede ou ekri pi vit, men temwayaj, chalè ak otantisite soti nan ou.",
            en: "Beyond study, AI saves precious time in the practical life of a church, an association or a small ministry. It can write an event announcement, a welcome message, a thank-you letter, or rephrase a clumsy notice in seconds.\n\nIt helps you communicate in several languages. In a community where people speak Creole, French and Spanish, you can have an announcement or a song translated, then have someone fluent in the language proofread it. The AI roughs it out, the human validates: that is the right sharing of roles.\n\nFor organisation, ask it to prepare a meeting agenda, a volunteer schedule, a task list for an event, or post ideas for social media. Combine it with a tool like Canva: the AI writes the text, Canva creates the visual.\n\nAlways keep your voice and your heart. A message of faith touches because it is sincere, not because it is perfect. Reread, personalise, add your experience: the AI helps you write faster, but the testimony, the warmth and the authenticity come from you.",
            es: "Más allá del estudio, la IA ahorra un tiempo valioso en la vida práctica de una iglesia, una asociación o un pequeño ministerio. Puede redactar el anuncio de un evento, un mensaje de bienvenida, una carta de agradecimiento, o reformular un comunicado torpe en segundos.\n\nAyuda a comunicar en varios idiomas. En una comunidad donde se habla creole, francés y español, puedes hacer traducir un anuncio o un canto, y luego pedir a alguien que domine el idioma que lo revise. La IA desbasta, el humano valida: ese es el buen reparto de roles.\n\nPara la organización, pídele que prepare el orden del día de una reunión, un calendario de voluntarios, una lista de tareas para un evento, o ideas de publicaciones para redes. Combínala con una herramienta como Canva: la IA escribe el texto, Canva crea el visual.\n\nConserva siempre tu voz y tu corazón. Un mensaje de fe conmueve porque es sincero, no porque sea perfecto. Relee, personaliza, añade tu experiencia: la IA te ayuda a escribir más rápido, pero el testimonio, la calidez y la autenticidad vienen de ti.",
          },
          keyPoints: {
            fr: ["Rédiger annonces, messages de bienvenue, remerciements", "Traduire pour une communauté multilingue (puis faire relire)", "Organiser : ordre du jour, planning, idées de posts", "Garder ta voix : personnaliser, l'authenticité vient de toi"],
            ht: ["Ekri anons, mesaj byenvini, remèsiman", "Tradui pou yon kominote milti-lang (epi fè reli)", "Òganize : lòd du jou, planin, lide pòs", "Kenbe vwa ou : pèsonalize, otantisite soti nan ou"],
            en: ["Write announcements, welcome messages, thank-yous", "Translate for a multilingual community (then have it checked)", "Organise: agendas, schedules, post ideas", "Keep your voice: personalise, authenticity comes from you"],
            es: ["Redactar anuncios, mensajes de bienvenida, agradecimientos", "Traducir para una comunidad multilingüe (y hacerlo revisar)", "Organizar: orden del día, calendarios, ideas de posts", "Conservar tu voz: personalizar, la autenticidad viene de ti"],
          },
          exercise: {
            fr: "Rédige avec l'IA l'annonce d'un vrai événement de ta communauté, puis demande-lui de la traduire dans une deuxième langue. Relis, personnalise avec une phrase qui vient de toi, et prépare le visuel dans Canva.",
            ht: "Ekri ak IA a anons yon vrè aktivite kominote ou, epi mande l tradui l nan yon dezyèm lang. Reli, pèsonalize ak yon fraz ki soti nan ou, epi prepare vizyèl la nan Canva.",
            en: "Write, with the AI, the announcement of a real event in your community, then ask it to translate it into a second language. Reread, personalise with a sentence of your own, and prepare the visual in Canva.",
            es: "Redacta con la IA el anuncio de un evento real de tu comunidad, y pídele que lo traduzca a un segundo idioma. Relee, personaliza con una frase tuya, y prepara el visual en Canva.",
          },
        },
        {
          slug: "integrer-ia-au-quotidien",
          title: { fr: "Intégrer l'IA dans son quotidien avec sagesse", ht: "Entegre IA nan chak jou ak sajès", en: "Integrating AI into daily life wisely", es: "Integrar la IA en el día a día con sabiduría" },
          videoId: "",
          content: {
            fr: "Maintenant que tu connais les bases, l'enjeu est d'installer de bonnes habitudes. Choisis deux ou trois usages réguliers où l'IA t'aide vraiment : corriger tes messages, résumer tes lectures, préparer tes réunions. Mieux vaut bien maîtriser quelques usages que tout survoler.\n\nGarde toujours le bon ordre : l'IA propose, tu décides. Pour chaque réponse importante, demande-toi « est-ce vrai ? est-ce juste ? est-ce utile ? » Vérifie les faits, garde ce qui te correspond, jette le reste. Tu restes le responsable de ce que tu publies ou transmets.\n\nFixe-toi des limites saines. L'IA ne doit pas remplacer ta réflexion, tes relations ni ta créativité. Continue d'écrire, d'apprendre et de créer par toi-même : l'outil est là pour t'épauler, pas pour penser à ta place. Fais-en un serviteur, jamais un maître.\n\nEnfin, partage ce que tu apprends. Montre à un proche comment écrire un bon prompt, comment vérifier une info, comment protéger ses données. Une technologie bien comprise et bien utilisée peut vraiment aider ta famille, ton travail et ta communauté. À toi d'en faire un usage qui construit.",
            ht: "Kounye a ou konnen baz yo, defi a se enstale bon abitid. Chwazi de oswa twa itilizasyon regilye kote IA ede ou vrèman : korije mesaj ou, rezime lekti ou, prepare reyinyon ou. Li pi bon pou byen metrize kèk itilizasyon pase pou survole tout.\n\nToujou kenbe bon lòd la : IA pwopoze, ou deside. Pou chak repons enpòtan, mande tèt ou « èske li vre ? èske li jis ? èske li itil ? » Verifye done yo, kenbe sa ki koresponn ak ou, jete rès la. Ou rete responsab sa ou pibliye oswa transmèt.\n\nFikse limit ki sen. IA pa dwe ranplase refleksyon ou, relasyon ou ni kreyativite ou. Kontinye ekri, aprann epi kreye pou tèt ou : zouti a la pou soutni ou, pa pou panse nan plas ou. Fè l yon sèvitè, pa janm yon mèt.\n\nAnfen, pataje sa ou aprann. Montre yon pwòch kijan pou ekri yon bon prompt, kijan pou verifye yon enfòmasyon, kijan pou pwoteje done l. Yon teknoloji byen konprann epi byen itilize ka vrèman ede fanmi ou, travay ou ak kominote ou. Se ou ki pou fè yon itilizasyon ki konstwi.",
            en: "Now that you know the basics, the challenge is to build good habits. Choose two or three regular uses where AI really helps you: fixing your messages, summarising your reading, preparing your meetings. It is better to master a few uses well than to skim over everything.\n\nAlways keep the right order: AI proposes, you decide. For every important answer, ask yourself \"is it true? is it right? is it useful?\" Check the facts, keep what fits you, discard the rest. You remain responsible for what you publish or pass on.\n\nSet healthy limits. AI should not replace your thinking, your relationships or your creativity. Keep writing, learning and creating on your own: the tool is there to support you, not to think in your place. Make it a servant, never a master.\n\nFinally, share what you learn. Show someone close how to write a good prompt, how to check a piece of information, how to protect their data. A well-understood and well-used technology can really help your family, your work and your community. It is up to you to make a use of it that builds.",
            es: "Ahora que conoces lo básico, el reto es instalar buenos hábitos. Elige dos o tres usos regulares donde la IA te ayude de verdad: corregir tus mensajes, resumir tus lecturas, preparar tus reuniones. Es mejor dominar bien unos pocos usos que sobrevolarlo todo.\n\nMantén siempre el orden correcto: la IA propone, tú decides. Para cada respuesta importante, pregúntate «¿es verdad? ¿es justo? ¿es útil?» Verifica los datos, conserva lo que te corresponde, descarta el resto. Sigues siendo responsable de lo que publicas o transmites.\n\nPonte límites sanos. La IA no debe reemplazar tu reflexión, tus relaciones ni tu creatividad. Sigue escribiendo, aprendiendo y creando por ti mismo: la herramienta está para apoyarte, no para pensar en tu lugar. Hazla un servidor, nunca un amo.\n\nPor último, comparte lo que aprendes. Muestra a un ser querido cómo escribir un buen prompt, cómo verificar una información, cómo proteger sus datos. Una tecnología bien entendida y bien usada puede ayudar de verdad a tu familia, tu trabajo y tu comunidad. Depende de ti darle un uso que construya.",
          },
          keyPoints: {
            fr: ["Choisir deux ou trois usages réguliers et les maîtriser", "L'IA propose, tu décides : vrai ? juste ? utile ?", "Limites saines : ne pas remplacer réflexion et relations", "Partager ce qu'on apprend pour aider autour de soi"],
            ht: ["Chwazi de oswa twa itilizasyon regilye epi metrize yo", "IA pwopoze, ou deside : vre ? jis ? itil ?", "Limit ki sen : pa ranplase refleksyon ak relasyon", "Pataje sa ou aprann pou ede moun otou ou"],
            en: ["Choose two or three regular uses and master them", "AI proposes, you decide: true? right? useful?", "Healthy limits: don't replace thinking and relationships", "Share what you learn to help those around you"],
            es: ["Elegir dos o tres usos regulares y dominarlos", "La IA propone, tú decides: ¿verdad? ¿justo? ¿útil?", "Límites sanos: no reemplazar reflexión ni relaciones", "Compartir lo que aprendes para ayudar a quienes te rodean"],
          },
          exercise: {
            fr: "Note trois tâches de ta semaine où l'IA pourrait t'aider (un message, un résumé, une organisation). Teste-la sur les trois, vérifie chaque résultat, et garde seulement les usages qui t'ont vraiment fait gagner du temps.",
            ht: "Note twa travay nan semèn ou kote IA ta ka ede ou (yon mesaj, yon rezime, yon òganizasyon). Teste l sou twa yo, verifye chak rezilta, epi kenbe sèlman itilizasyon ki vrèman fè ou genyen tan.",
            en: "Note three tasks from your week where AI could help you (a message, a summary, an organisation). Test it on all three, check each result, and keep only the uses that truly saved you time.",
            es: "Anota tres tareas de tu semana donde la IA podría ayudarte (un mensaje, un resumen, una organización). Pruébala en las tres, verifica cada resultado, y conserva solo los usos que realmente te ahorraron tiempo.",
          },
        },
      ],
    },
  ],
};

export default chatgptIa;
