import { CourseContent } from "./types";

const creationWeb: CourseContent = {
  slug: "creation-web",
  intro: {
    fr: "Comprendre comment fonctionne un site web et apprendre, étape par étape, à créer et publier ton propre site simple : langages de base, nom de domaine, hébergement, pages, navigation, mobile, mise en ligne et référencement.",
    ht: "Konprann kijan yon sit entènèt fonksyone epi aprann, etap pa etap, kreye ak pibliye pwòp sit senp ou : lang de baz, non domèn, ebèjman, paj, navigasyon, mobil, mete an liy ak referansman.",
    en: "Understand how a website works and learn, step by step, to build and publish your own simple site: basic languages, domain name, hosting, pages, navigation, mobile, going live and search ranking.",
    es: "Comprender cómo funciona un sitio web y aprender, paso a paso, a crear y publicar tu propio sitio sencillo: lenguajes básicos, nombre de dominio, alojamiento, páginas, navegación, móvil, publicación y posicionamiento.",
  },
  modules: [
    {
      title: { fr: "Comprendre le fonctionnement d'un site", ht: "Konprann kijan yon sit fonksyone", en: "Understanding how a site works", es: "Comprender el funcionamiento de un sitio" },
      lessons: [
        {
          slug: "comment-fonctionne-un-site",
          title: { fr: "Comment fonctionne un site web ?", ht: "Kijan yon sit entènèt fonksyone ?", en: "How does a website work?", es: "¿Cómo funciona un sitio web?" },
          videoId: "",
          content: {
            fr: "Un site web est un ensemble de pages stockées sur un ordinateur toujours allumé et connecté à Internet, appelé « serveur ». Quand quelqu'un tape ton adresse dans son navigateur (Chrome, Safari…), celui-ci demande les pages au serveur, qui les renvoie, et le navigateur les affiche à l'écran.\n\nChaque page est écrite avec des langages simples : le HTML pour la structure (les titres, les paragraphes, les images), le CSS pour l'apparence (les couleurs, les polices, la mise en page), et parfois le JavaScript pour rendre la page interactive (un menu qui s'ouvre, un formulaire). Tu n'as pas besoin de tout maîtriser pour débuter : des outils modernes écrivent ce code pour toi.\n\nRetiens l'image : le serveur est comme un restaurant qui garde les plats prêts, le navigateur est le client qui vient les commander, et l'adresse web est simplement l'adresse du restaurant. Comprendre ce trajet t'aide à savoir de quoi tu as besoin pour mettre ton site en ligne.\n\nPour exister publiquement, un site a donc besoin de trois choses qui vont ensemble : une adresse (le nom de domaine), un espace où loger ses fichiers (l'hébergement), et les pages elles-mêmes. Les prochaines leçons vont détailler chacune de ces briques, mais garde cette vue d'ensemble en tête : elle t'évitera de te perdre dans les détails techniques.",
            ht: "Yon sit entènèt se yon ansanm paj ki estoke sou yon òdinatè ki toujou limen epi konekte ak Entènèt, yo rele « sèvè ». Lè yon moun tape adrès ou nan navigatè li (Chrome, Safari…), navigatè a mande paj yo bay sèvè a, sèvè a voye yo tounen, epi navigatè a montre yo sou ekran an.\n\nChak paj ekri ak lang senp : HTML pou estrikti a (tit, paragraf, imaj), CSS pou aparans (koulè, polis, mizanpaj), epi pafwa JavaScript pou fè paj la entèraktif (yon meni ki louvri, yon fòm). Ou pa bezwen metrize tout bagay pou kòmanse : zouti modèn ekri kòd sa a pou ou.\n\nSonje imaj sa a : sèvè a se tankou yon restoran ki kenbe manje pare, navigatè a se kliyan an ki vin kòmande yo, epi adrès web la se senpleman adrès restoran an. Konprann trajè sa a ede ou konnen kisa ou bezwen pou mete sit ou an liy.\n\nPou l egziste piblikman, yon sit bezwen twa bagay ki ale ansanm : yon adrès (non domèn nan), yon espas pou loje fichye li yo (ebèjman), ak paj yo menm. Leson ki vin apre yo pral detaye chak moso sa yo, men kenbe vizyon global sa a nan tèt ou : li ap anpeche ou pèdi nan detay teknik yo.",
            en: "A website is a set of pages stored on a computer that is always on and connected to the Internet, called a \"server\". When someone types your address into their browser (Chrome, Safari…), the browser requests the pages from the server, which sends them back, and the browser displays them on screen.\n\nEach page is written with simple languages: HTML for structure (titles, paragraphs, images), CSS for appearance (colours, fonts, layout), and sometimes JavaScript to make the page interactive (a menu that opens, a form). You don't need to master everything to start: modern tools write this code for you.\n\nRemember the image: the server is like a restaurant that keeps dishes ready, the browser is the customer who comes to order them, and the web address is simply the restaurant's address. Understanding this journey helps you know what you need to put your site online.\n\nTo exist publicly, a site therefore needs three things that go together: an address (the domain name), a space to house its files (hosting), and the pages themselves. The next lessons will detail each of these building blocks, but keep this overview in mind: it will stop you getting lost in technical details.",
            es: "Un sitio web es un conjunto de páginas almacenadas en una computadora siempre encendida y conectada a Internet, llamada «servidor». Cuando alguien escribe tu dirección en su navegador (Chrome, Safari…), el navegador pide las páginas al servidor, este las devuelve, y el navegador las muestra en pantalla.\n\nCada página se escribe con lenguajes simples: HTML para la estructura (títulos, párrafos, imágenes), CSS para la apariencia (colores, fuentes, diseño) y a veces JavaScript para hacer la página interactiva (un menú que se abre, un formulario). No necesitas dominarlo todo para empezar: las herramientas modernas escriben ese código por ti.\n\nRecuerda la imagen: el servidor es como un restaurante que mantiene los platos listos, el navegador es el cliente que viene a pedirlos, y la dirección web es simplemente la dirección del restaurante. Entender este recorrido te ayuda a saber qué necesitas para poner tu sitio en línea.\n\nPara existir públicamente, un sitio necesita entonces tres cosas que van juntas: una dirección (el nombre de dominio), un espacio donde alojar sus archivos (el alojamiento) y las páginas en sí. Las próximas lecciones detallarán cada uno de estos bloques, pero mantén esta visión de conjunto en mente: te evitará perderte en los detalles técnicos.",
          },
          keyPoints: {
            fr: ["Les pages sont stockées sur un serveur, le navigateur les affiche", "HTML = structure, CSS = apparence, JavaScript = interactivité", "Un site public a besoin de trois choses : adresse, hébergement, pages", "Les outils modernes écrivent le code à ta place"],
            ht: ["Paj yo estoke sou yon sèvè, navigatè a montre yo", "HTML = estrikti, CSS = aparans, JavaScript = entèraktivite", "Yon sit piblik bezwen twa bagay : adrès, ebèjman, paj", "Zouti modèn ekri kòd la pou ou"],
            en: ["Pages are stored on a server, the browser displays them", "HTML = structure, CSS = appearance, JavaScript = interactivity", "A public site needs three things: address, hosting, pages", "Modern tools write the code for you"],
            es: ["Las páginas se guardan en un servidor, el navegador las muestra", "HTML = estructura, CSS = apariencia, JavaScript = interactividad", "Un sitio público necesita tres cosas: dirección, alojamiento, páginas", "Las herramientas modernas escriben el código por ti"],
          },
          exercise: {
            fr: "Ouvre un site que tu aimes dans ton navigateur et fais un clic droit puis « Inspecter » (ou « Afficher le code source »). Repère au moins un titre (balise h1), un paragraphe et une image dans le code HTML. Sur une feuille, dessine le trajet d'une visite : ton navigateur, l'adresse tapée, le serveur, la page renvoyée.",
            ht: "Louvri yon sit ou renmen nan navigatè ou epi fè yon klik dwat apre sa « Enspekte » (oswa « Montre kòd sous la »). Jwenn omwen yon tit (baliz h1), yon paragraf ak yon imaj nan kòd HTML la. Sou yon fèy, desine trajè yon vizit : navigatè ou, adrès ou tape a, sèvè a, paj ki tounen an.",
            en: "Open a site you like in your browser and right-click, then \"Inspect\" (or \"View page source\"). Find at least one heading (h1 tag), one paragraph and one image in the HTML code. On a sheet, draw the journey of a visit: your browser, the typed address, the server, the returned page.",
            es: "Abre un sitio que te guste en tu navegador y haz clic derecho, luego «Inspeccionar» (o «Ver código fuente»). Localiza al menos un título (etiqueta h1), un párrafo y una imagen en el código HTML. En una hoja, dibuja el recorrido de una visita: tu navegador, la dirección escrita, el servidor, la página devuelta.",
          },
        },
        {
          slug: "choisir-son-outil",
          title: { fr: "Choisir le bon outil pour créer son site", ht: "Chwazi bon zouti pou kreye sit ou", en: "Choosing the right tool to build your site", es: "Elegir la herramienta adecuada para tu sitio" },
          videoId: "",
          content: {
            fr: "Il existe deux grandes façons de créer un site. La première : coder toi-même en HTML et CSS. C'est très formateur et gratuit, mais cela demande du temps d'apprentissage. La seconde : utiliser un constructeur visuel comme WordPress, Wix ou Google Sites, où tu glisses des blocs sans écrire de code.\n\nPour un premier site simple — une page de présentation, un site d'église, une petite vitrine de commerce — un constructeur visuel est souvent le choix le plus rapide. Wix et Google Sites sont faciles pour les débutants ; WordPress est plus puissant et très répandu, mais un peu plus technique.\n\nPose-toi trois questions pour choisir : Quel est le but du site (informer, vendre, présenter) ? Combien de temps peux-tu y consacrer ? As-tu un budget ou veux-tu rester gratuit ? Il n'y a pas de mauvais choix : commence simple, tu pourras toujours faire évoluer ton site plus tard.\n\nMéfie-toi de deux pièges. D'abord, ne passe pas des semaines à comparer les outils sans jamais commencer : le meilleur outil est celui avec lequel tu avances vraiment. Ensuite, vérifie que l'outil te laisse récupérer ton contenu et brancher ton propre nom de domaine, pour ne pas rester prisonnier d'une plateforme. Choisis-en un, ouvre un compte gratuit aujourd'hui, et fais tes premiers essais.",
            ht: "Gen de gwo fason pou kreye yon sit. Premye a : kode tèt ou an HTML ak CSS. Sa fòme ou anpil epi li gratis, men li mande tan pou aprann. Dezyèm nan : sèvi ak yon konstriktè vizyèl tankou WordPress, Wix oswa Google Sites, kote ou trennen blòk san ekri kòd.\n\nPou yon premye sit senp — yon paj prezantasyon, yon sit legliz, yon ti vitrin komès — yon konstriktè vizyèl souvan se chwa ki pi rapid la. Wix ak Google Sites fasil pou debitan ; WordPress pi pwisan epi trè popilè, men yon ti jan pi teknik.\n\nPoze tèt ou twa kesyon pou chwazi : Ki objektif sit la (enfòme, vann, prezante) ? Konbyen tan ou ka mete ladan l ? Èske ou gen yon bidjè oswa ou vle rete gratis ? Pa gen move chwa : kòmanse senp, ou ap toujou ka fè sit ou evolye pita.\n\nFè atansyon ak de pyèj. Premyèman, pa pase semèn ap konpare zouti san ou pa janm kòmanse : pi bon zouti a se sa ou reyèlman avanse avè l. Dezyèmman, verifye zouti a kite ou reprann kontni ou epi konekte pwòp non domèn ou, pou ou pa rete prizonye yon platfòm. Chwazi youn, ouvri yon kont gratis jodi a, epi fè premye eseye ou yo.",
            en: "There are two main ways to build a site. The first: code it yourself in HTML and CSS. It teaches a lot and is free, but it takes time to learn. The second: use a visual builder like WordPress, Wix or Google Sites, where you drag blocks without writing code.\n\nFor a first simple site — a presentation page, a church site, a small business shopfront — a visual builder is often the fastest choice. Wix and Google Sites are easy for beginners; WordPress is more powerful and very widespread, but a bit more technical.\n\nAsk yourself three questions to choose: What is the site's goal (inform, sell, present)? How much time can you give it? Do you have a budget or do you want to stay free? There is no wrong choice: start simple, you can always grow your site later.\n\nBeware of two traps. First, don't spend weeks comparing tools without ever starting: the best tool is the one you actually make progress with. Second, check that the tool lets you export your content and connect your own domain name, so you're not locked into one platform. Pick one, open a free account today, and make your first attempts.",
            es: "Existen dos grandes maneras de crear un sitio. La primera: programarlo tú mismo en HTML y CSS. Es muy formativo y gratis, pero requiere tiempo de aprendizaje. La segunda: usar un constructor visual como WordPress, Wix o Google Sites, donde arrastras bloques sin escribir código.\n\nPara un primer sitio sencillo — una página de presentación, un sitio de iglesia, un pequeño escaparate de negocio — un constructor visual suele ser la opción más rápida. Wix y Google Sites son fáciles para principiantes; WordPress es más potente y muy extendido, pero algo más técnico.\n\nHazte tres preguntas para elegir: ¿Cuál es el objetivo del sitio (informar, vender, presentar)? ¿Cuánto tiempo puedes dedicarle? ¿Tienes presupuesto o quieres quedarte en lo gratuito? No hay mala elección: empieza simple, siempre podrás hacer crecer tu sitio más adelante.\n\nCuidado con dos trampas. Primero, no pases semanas comparando herramientas sin empezar nunca: la mejor herramienta es aquella con la que realmente avanzas. Segundo, comprueba que la herramienta te permita exportar tu contenido y conectar tu propio nombre de dominio, para no quedar preso de una plataforma. Elige una, abre una cuenta gratuita hoy y haz tus primeros intentos.",
          },
          keyPoints: {
            fr: ["Coder soi-même (HTML/CSS) ou constructeur visuel (Wix, WordPress)", "Pour débuter, un constructeur visuel est le plus rapide", "Choisir selon le but, le temps et le budget", "Vérifie que tu peux brancher ton domaine et exporter ton contenu"],
            ht: ["Kode tèt ou (HTML/CSS) oswa konstriktè vizyèl (Wix, WordPress)", "Pou kòmanse, yon konstriktè vizyèl se pi rapid la", "Chwazi selon objektif, tan ak bidjè", "Verifye ou ka konekte domèn ou epi reprann kontni ou"],
            en: ["Code it yourself (HTML/CSS) or a visual builder (Wix, WordPress)", "To start, a visual builder is the fastest", "Choose based on goal, time and budget", "Check you can connect your domain and export your content"],
            es: ["Programarlo tú (HTML/CSS) o un constructor visual (Wix, WordPress)", "Para empezar, un constructor visual es lo más rápido", "Elegir según objetivo, tiempo y presupuesto", "Comprueba que puedes conectar tu dominio y exportar tu contenido"],
          },
          exercise: {
            fr: "Écris en une phrase le but de ton futur site et le type de visiteur visé. Puis liste deux outils qui te tentent (par exemple Google Sites et WordPress) et note, pour chacun, un avantage et un inconvénient pour ton cas. Décide-toi et ouvre un compte gratuit sur l'outil choisi dès aujourd'hui.",
            ht: "Ekri nan yon fraz objektif sit ou pral genyen an ak ki kalite vizitè ou vize. Apre sa, liste de zouti ki enterese ou (pa egzanp Google Sites ak WordPress) epi note, pou chak, yon avantaj ak yon dezavantaj pou ka pa ou. Deside epi ouvri yon kont gratis sou zouti ou chwazi a depi jodi a.",
            en: "Write in one sentence the goal of your future site and the kind of visitor you're targeting. Then list two tools that appeal to you (for example Google Sites and WordPress) and note, for each, one advantage and one drawback for your case. Decide and open a free account on the chosen tool today.",
            es: "Escribe en una frase el objetivo de tu futuro sitio y el tipo de visitante al que apuntas. Luego enumera dos herramientas que te atraigan (por ejemplo Google Sites y WordPress) y anota, para cada una, una ventaja y un inconveniente para tu caso. Decídete y abre una cuenta gratuita en la herramienta elegida hoy mismo.",
          },
        },
        {
          slug: "langages-html-css",
          title: { fr: "HTML et CSS : les deux langages de base", ht: "HTML ak CSS : de lang de baz yo", en: "HTML and CSS: the two basic languages", es: "HTML y CSS: los dos lenguajes básicos" },
          videoId: "",
          content: {
            fr: "Même si tu utilises un constructeur visuel, comprendre le HTML et le CSS te rend beaucoup plus autonome. Le HTML est la charpente de la page : il dit « ceci est un titre », « ceci est un paragraphe », « ceci est une image ». On écrit ces éléments avec des balises, comme <h1>Bienvenue</h1> pour un grand titre ou <p>Mon texte</p> pour un paragraphe.\n\nLe CSS, lui, s'occupe de l'apparence. Il répond à la question « à quoi ça ressemble ? » : la couleur du texte, la taille des lettres, l'espace autour des blocs, la couleur de fond. Par exemple, une règle CSS comme « color: navy » met le texte en bleu marine. Le HTML sans CSS, c'est une maison sans peinture ni décoration : solide, mais nue.\n\nRetiens la répartition des rôles : le HTML pose le contenu et son sens, le CSS habille ce contenu. Cette séparation est puissante, car tu peux changer toute l'apparence d'un site (les couleurs, les polices) sans toucher au texte lui-même. Les constructeurs visuels ne font rien d'autre : quand tu changes une couleur en cliquant, ils écrivent du CSS pour toi en coulisses.\n\nTu n'as pas besoin de tout apprendre par cœur. Connaître une dizaine de balises courantes (titre, paragraphe, lien, image, liste) et quelques propriétés CSS de base (couleur, taille, marge) suffit déjà pour comprendre ce qui se passe et corriger de petits détails. Le reste s'apprend au fur et à mesure, en observant le code des pages que tu aimes.",
            ht: "Menm si ou sèvi ak yon konstriktè vizyèl, konprann HTML ak CSS fè ou vin pi otonòm. HTML se chapant paj la : li di « sa a se yon tit », « sa a se yon paragraf », « sa a se yon imaj ». Ou ekri eleman sa yo ak baliz, tankou <h1>Byenveni</h1> pou yon gwo tit oswa <p>Tèks mwen</p> pou yon paragraf.\n\nCSS menm okipe aparans lan. Li reponn kesyon « ki jan sa sanble ? » : koulè tèks la, gwosè lèt yo, espas otou blòk yo, koulè fon an. Pa egzanp, yon règ CSS tankou « color: navy » mete tèks la an ble maren. HTML san CSS, se yon kay san penti ni dekorasyon : solid, men toutouni.\n\nSonje repatisyon wòl yo : HTML poze kontni an ak sans li, CSS abiye kontni sa a. Separasyon sa a pwisan, paske ou ka chanje tout aparans yon sit (koulè, polis) san ou pa manyen tèks la menm. Konstriktè vizyèl yo pa fè lòt bagay : lè ou chanje yon koulè ak yon klik, yo ekri CSS pou ou dèyè rido.\n\nOu pa bezwen aprann tout bagay pa kè. Konnen yon dizèn baliz kouran (tit, paragraf, lyen, imaj, lis) ak kèk pwopriyete CSS de baz (koulè, gwosè, maj) deja ase pou konprann sa k ap pase epi korije ti detay. Rès la aprann piti piti, lè ou obsève kòd paj ou renmen yo.",
            en: "Even if you use a visual builder, understanding HTML and CSS makes you far more independent. HTML is the frame of the page: it says \"this is a heading\", \"this is a paragraph\", \"this is an image\". You write these elements with tags, like <h1>Welcome</h1> for a big heading or <p>My text</p> for a paragraph.\n\nCSS handles appearance. It answers the question \"what does it look like?\": the text colour, the size of the letters, the space around blocks, the background colour. For example, a CSS rule like \"color: navy\" makes the text navy blue. HTML without CSS is a house with no paint or decoration: solid, but bare.\n\nRemember the division of roles: HTML lays out the content and its meaning, CSS dresses that content. This separation is powerful, because you can change a whole site's look (the colours, the fonts) without touching the text itself. Visual builders do nothing else: when you change a colour by clicking, they write CSS for you behind the scenes.\n\nYou don't need to learn everything by heart. Knowing about ten common tags (heading, paragraph, link, image, list) and a few basic CSS properties (colour, size, margin) is already enough to understand what's happening and fix small details. The rest you learn as you go, by looking at the code of pages you like.",
            es: "Aunque uses un constructor visual, entender HTML y CSS te hace mucho más autónomo. El HTML es el armazón de la página: dice «esto es un título», «esto es un párrafo», «esto es una imagen». Estos elementos se escriben con etiquetas, como <h1>Bienvenido</h1> para un título grande o <p>Mi texto</p> para un párrafo.\n\nEl CSS se encarga de la apariencia. Responde a la pregunta «¿cómo se ve?»: el color del texto, el tamaño de las letras, el espacio alrededor de los bloques, el color de fondo. Por ejemplo, una regla CSS como «color: navy» pone el texto en azul marino. HTML sin CSS es una casa sin pintura ni decoración: sólida, pero desnuda.\n\nRecuerda el reparto de papeles: el HTML coloca el contenido y su sentido, el CSS viste ese contenido. Esta separación es poderosa, porque puedes cambiar toda la apariencia de un sitio (los colores, las fuentes) sin tocar el texto en sí. Los constructores visuales no hacen otra cosa: cuando cambias un color con un clic, escriben CSS por ti entre bastidores.\n\nNo necesitas aprenderlo todo de memoria. Conocer una decena de etiquetas comunes (título, párrafo, enlace, imagen, lista) y unas pocas propiedades CSS básicas (color, tamaño, margen) ya basta para entender lo que ocurre y corregir pequeños detalles. El resto se aprende sobre la marcha, observando el código de las páginas que te gustan.",
          },
          keyPoints: {
            fr: ["HTML = la charpente et le sens du contenu (balises)", "CSS = l'apparence (couleurs, tailles, espaces)", "Séparer contenu et apparence permet de tout restyler sans réécrire", "Une dizaine de balises et quelques règles CSS suffisent pour débuter"],
            ht: ["HTML = chapant lan ak sans kontni an (baliz)", "CSS = aparans lan (koulè, gwosè, espas)", "Separe kontni ak aparans pèmèt restyle tout san reekri", "Yon dizèn baliz ak kèk règ CSS ase pou kòmanse"],
            en: ["HTML = the frame and meaning of content (tags)", "CSS = appearance (colours, sizes, spacing)", "Separating content and look lets you restyle without rewriting", "About ten tags and a few CSS rules are enough to start"],
            es: ["HTML = el armazón y el sentido del contenido (etiquetas)", "CSS = la apariencia (colores, tamaños, espacios)", "Separar contenido y apariencia permite reestilizar sin reescribir", "Una decena de etiquetas y unas reglas CSS bastan para empezar"],
          },
          exercise: {
            fr: "Sur un éditeur de texte simple, crée un fichier « page.html » avec un titre <h1>, deux paragraphes <p> et une image <img>. Ouvre-le dans ton navigateur pour le voir. Puis ajoute une petite balise <style> qui change la couleur du titre et la taille du texte, et recharge la page pour observer l'effet du CSS.",
            ht: "Sou yon senp editè tèks, kreye yon fichye « page.html » ak yon tit <h1>, de paragraf <p> ak yon imaj <img>. Louvri l nan navigatè ou pou wè l. Apre sa, ajoute yon ti baliz <style> ki chanje koulè tit la ak gwosè tèks la, epi rechaje paj la pou obsève efè CSS la.",
            en: "In a simple text editor, create a \"page.html\" file with an <h1> heading, two <p> paragraphs and an <img> image. Open it in your browser to see it. Then add a small <style> tag that changes the heading colour and the text size, and reload the page to observe the effect of CSS.",
            es: "En un editor de texto simple, crea un archivo «page.html» con un título <h1>, dos párrafos <p> y una imagen <img>. Ábrelo en tu navegador para verlo. Luego añade una pequeña etiqueta <style> que cambie el color del título y el tamaño del texto, y recarga la página para observar el efecto del CSS.",
          },
        },
      ],
    },
    {
      title: { fr: "Nom de domaine et hébergement", ht: "Non domèn ak ebèjman", en: "Domain name and hosting", es: "Nombre de dominio y alojamiento" },
      lessons: [
        {
          slug: "nom-de-domaine",
          title: { fr: "Le nom de domaine : l'adresse de ton site", ht: "Non domèn : adrès sit ou", en: "The domain name: your site's address", es: "El nombre de dominio: la dirección de tu sitio" },
          videoId: "",
          content: {
            fr: "Le nom de domaine, c'est l'adresse que les gens taperont pour venir chez toi, par exemple « moneglise.org » ou « boutiquemarie.com ». C'est ton adresse sur Internet, comme l'adresse d'une maison. Un bon nom est court, facile à écrire, facile à retenir et à prononcer.\n\nUn nom de domaine s'achète, généralement pour une somme modeste par an, auprès d'un « registraire » comme Namecheap, GoDaddy, OVH ou Google Domains. La terminaison a son importance : « .com » est la plus connue, « .org » convient aux associations et églises, et il existe des versions par pays. Vérifie sur le site du registraire si le nom que tu veux est disponible.\n\nConseils pratiques : évite les tirets et les chiffres qui prêtent à confusion à l'oral, préfère un nom en lien clair avec ton activité, et réserve-le vite si tu le trouves libre, car les bons noms partent vite. Tu peux réserver un domaine même avant d'avoir fini ton site.\n\nUne astuce simple pour tester un nom : dis-le à voix haute à quelqu'un au téléphone et demande-lui de l'écrire. Si la personne l'orthographie correctement du premier coup, ton nom est bon. S'il faut épeler chaque lettre, c'est qu'il est trop compliqué. Pense aussi à réserver, si tu peux, les variantes proches (le .com et le .org) pour protéger ta marque et éviter les confusions.",
            ht: "Non domèn nan se adrès moun ap tape pou vin lakay ou, pa egzanp « monegliz.org » oswa « boutikmari.com ». Se adrès ou sou Entènèt, tankou adrès yon kay. Yon bon non kout, fasil pou ekri, fasil pou sonje epi pou pwononse.\n\nOu achte yon non domèn, jeneralman pou yon ti kòb pa ane, nan men yon « registrè » tankou Namecheap, GoDaddy, OVH oswa Google Domains. Tèminezon an gen enpòtans li : « .com » se pi popilè a, « .org » bon pou asosyasyon ak legliz, epi gen vèsyon pa peyi. Verifye sou sit registrè a si non ou vle a disponib.\n\nKonsèy pratik : evite tirè ak chif ki bay konfizyon lè ou pale, pito yon non ki gen yon lyen klè ak aktivite ou, epi rezève l vit si ou jwenn li lib, paske bon non yo pati vit. Ou ka rezève yon domèn menm anvan ou fini sit ou.\n\nYon ti astis senp pou teste yon non : di l awotvwa bay yon moun nan telefòn epi mande l pou ekri l. Si moun nan ekri l kòrèkteman premye kou, non ou an bon. Si ou dwe eple chak lèt, sa vle di li twò konplike. Panse tou pou rezève, si ou kapab, varyant ki pre yo (.com ak .org) pou pwoteje mak ou epi evite konfizyon.",
            en: "The domain name is the address people will type to reach you, for example \"mychurch.org\" or \"mariashop.com\". It's your address on the Internet, like a house address. A good name is short, easy to write, easy to remember and to say.\n\nA domain name is bought, usually for a modest amount per year, from a \"registrar\" like Namecheap, GoDaddy, OVH or Google Domains. The ending matters: \".com\" is the best known, \".org\" suits associations and churches, and there are country versions. Check on the registrar's site whether the name you want is available.\n\nPractical tips: avoid dashes and numbers that confuse when spoken, prefer a name clearly linked to your activity, and book it quickly if it's free, because good names go fast. You can reserve a domain even before your site is finished.\n\nA simple trick to test a name: say it out loud to someone on the phone and ask them to write it down. If they spell it correctly first time, your name is good. If you have to spell out every letter, it's too complicated. Also consider reserving, if you can, the close variants (the .com and the .org) to protect your brand and avoid confusion.",
            es: "El nombre de dominio es la dirección que la gente escribirá para llegar a ti, por ejemplo «miiglesia.org» o «tiendamaria.com». Es tu dirección en Internet, como la dirección de una casa. Un buen nombre es corto, fácil de escribir, fácil de recordar y de pronunciar.\n\nUn nombre de dominio se compra, normalmente por una cantidad modesta al año, a un «registrador» como Namecheap, GoDaddy, OVH o Google Domains. La terminación importa: «.com» es la más conocida, «.org» conviene a asociaciones e iglesias, y existen versiones por país. Comprueba en el sitio del registrador si el nombre que quieres está disponible.\n\nConsejos prácticos: evita guiones y números que confunden al hablar, prefiere un nombre claramente ligado a tu actividad, y resérvalo rápido si lo encuentras libre, porque los buenos nombres se van rápido. Puedes reservar un dominio incluso antes de terminar tu sitio.\n\nUn truco simple para probar un nombre: dilo en voz alta a alguien por teléfono y pídele que lo escriba. Si lo deletrea correctamente a la primera, tu nombre es bueno. Si hay que deletrear cada letra, es demasiado complicado. Piensa también en reservar, si puedes, las variantes cercanas (el .com y el .org) para proteger tu marca y evitar confusiones.",
          },
          keyPoints: {
            fr: ["Le domaine = l'adresse de ton site (ex : monsite.com)", "S'achète chez un registraire (Namecheap, OVH…) à l'année", "Le choisir court, clair et le réserver vite s'il est libre", "Teste-le à l'oral : facile à écrire sous la dictée = bon nom"],
            ht: ["Domèn = adrès sit ou (egz : monsit.com)", "Ou achte l nan yon registrè (Namecheap, OVH…) pa ane", "Chwazi l kout, klè epi rezève l vit si li lib", "Teste l awotvwa : fasil pou ekri anba dikte = bon non"],
            en: ["The domain = your site's address (e.g. mysite.com)", "Bought from a registrar (Namecheap, OVH…) per year", "Choose it short, clear and book it fast if free", "Test it out loud: easy to write from dictation = a good name"],
            es: ["El dominio = la dirección de tu sitio (ej: misitio.com)", "Se compra a un registrador (Namecheap, OVH…) por año", "Elegirlo corto, claro y reservarlo rápido si está libre", "Pruébalo en voz alta: fácil de escribir al dictado = buen nombre"],
          },
          exercise: {
            fr: "Note cinq idées de noms de domaine pour ton projet. Va sur le site d'un registraire (Namecheap ou OVH) et vérifie lesquels sont disponibles. Choisis ton préféré, teste-le à voix haute avec un proche qui doit l'écrire, et note son prix annuel en .com et en .org.",
            ht: "Note senk lide non domèn pou pwojè ou. Ale sou sit yon registrè (Namecheap oswa OVH) epi verifye kilès ki disponib. Chwazi pi bon an, teste l awotvwa ak yon moun pre ou ki dwe ekri l, epi note pri li pa ane an .com ak an .org.",
            en: "Note five domain name ideas for your project. Go to a registrar's site (Namecheap or OVH) and check which ones are available. Choose your favourite, test it out loud with someone close who must write it down, and note its yearly price in .com and .org.",
            es: "Anota cinco ideas de nombres de dominio para tu proyecto. Ve al sitio de un registrador (Namecheap u OVH) y comprueba cuáles están disponibles. Elige tu favorito, pruébalo en voz alta con alguien cercano que deba escribirlo, y anota su precio anual en .com y en .org.",
          },
        },
        {
          slug: "hebergement",
          title: { fr: "L'hébergement : où vit ton site", ht: "Ebèjman : kote sit ou rete", en: "Hosting: where your site lives", es: "El alojamiento: donde vive tu sitio" },
          videoId: "",
          content: {
            fr: "Si le domaine est l'adresse, l'hébergement est le terrain et la maison : c'est l'espace, sur un serveur, où sont stockés les fichiers de ton site pour qu'ils soient accessibles 24 h/24. Sans hébergement, un domaine ne pointe vers rien. Tu loues cet espace auprès d'un « hébergeur ».\n\nSi tu utilises un constructeur comme Wix ou Google Sites, l'hébergement est déjà inclus : tu n'as rien à installer. Si tu passes par WordPress ou un site codé à la main, tu choisis un hébergeur (par exemple Hostinger, OVH, Infomaniak). Il existe même des offres gratuites pour de petits sites, comme Netlify, Vercel ou GitHub Pages, très pratiques pour débuter.\n\nDeux points de vigilance : vérifie que l'hébergement fournit le « HTTPS » (le petit cadenas de sécurité, souvent gratuit) et qu'il propose un support en cas de problème. Une fois l'hébergement en place, tu relies ton nom de domaine à cet espace, et ton adresse mène enfin à ton site.\n\nPour un premier site simple, ne surpaie pas. Les offres à petit prix ou gratuites suffisent largement pour quelques pages et un trafic modeste. Regarde surtout trois choses : l'espace de stockage (largement suffisant pour du texte et des images bien compressées), la vitesse de chargement, et la facilité de faire des sauvegardes. Tu pourras toujours changer d'hébergeur plus tard si ton site grandit vraiment.",
            ht: "Si domèn nan se adrès la, ebèjman se teren an ak kay la : se espas la, sou yon sèvè, kote fichye sit ou estoke pou yo aksesib 24è sou 24. San ebèjman, yon domèn pa pwente sou anyen. Ou lwe espas sa a nan men yon « ebèjè ».\n\nSi ou sèvi ak yon konstriktè tankou Wix oswa Google Sites, ebèjman deja enkli : ou pa gen anyen pou enstale. Si ou pase pa WordPress oswa yon sit ou kode ak men, ou chwazi yon ebèjè (pa egzanp Hostinger, OVH, Infomaniak). Genyen menm òf gratis pou ti sit, tankou Netlify, Vercel oswa GitHub Pages, ki trè pratik pou kòmanse.\n\nDe pwen pou fè atansyon : verifye ebèjman an bay « HTTPS » (ti kadna sekirite a, souvan gratis) epi li ofri sipò an ka pwoblèm. Yon fwa ebèjman an anplas, ou konekte non domèn ou ak espas sa a, epi adrès ou finalman mennen sou sit ou.\n\nPou yon premye sit senp, pa peye twòp. Òf a ti pri oswa gratis yo ase lajman pou kèk paj ak yon ti trafik. Gade sitou twa bagay : espas stokaj la (lajman ase pou tèks ak imaj byen konprese), vitès chajman, ak fasilite pou fè sovgad. Ou ap toujou ka chanje ebèjè pita si sit ou grandi vre.",
            en: "If the domain is the address, hosting is the land and the house: it's the space, on a server, where your site's files are stored so they are available 24/7. Without hosting, a domain points to nothing. You rent this space from a \"host\".\n\nIf you use a builder like Wix or Google Sites, hosting is already included: there's nothing to install. If you go through WordPress or a hand-coded site, you choose a host (for example Hostinger, OVH, Infomaniak). There are even free offers for small sites, like Netlify, Vercel or GitHub Pages, very handy to start with.\n\nTwo things to watch: check that the hosting provides \"HTTPS\" (the little security padlock, often free) and that it offers support in case of trouble. Once hosting is set up, you link your domain name to this space, and your address finally leads to your site.\n\nFor a first simple site, don't overpay. Low-cost or free offers are more than enough for a few pages and modest traffic. Look mainly at three things: the storage space (plenty for text and well-compressed images), loading speed, and how easy it is to make backups. You can always switch host later if your site really grows.",
            es: "Si el dominio es la dirección, el alojamiento es el terreno y la casa: es el espacio, en un servidor, donde se guardan los archivos de tu sitio para que estén accesibles las 24 horas. Sin alojamiento, un dominio no apunta a nada. Alquilas ese espacio a un «proveedor de alojamiento».\n\nSi usas un constructor como Wix o Google Sites, el alojamiento ya está incluido: no tienes que instalar nada. Si vas con WordPress o un sitio programado a mano, eliges un alojamiento (por ejemplo Hostinger, OVH, Infomaniak). Incluso hay ofertas gratuitas para sitios pequeños, como Netlify, Vercel o GitHub Pages, muy prácticas para empezar.\n\nDos puntos de atención: comprueba que el alojamiento ofrezca «HTTPS» (el candadito de seguridad, a menudo gratis) y que tenga soporte por si hay problemas. Una vez listo el alojamiento, enlazas tu nombre de dominio con ese espacio, y tu dirección por fin lleva a tu sitio.\n\nPara un primer sitio sencillo, no pagues de más. Las ofertas económicas o gratuitas bastan de sobra para unas páginas y un tráfico modesto. Fíjate sobre todo en tres cosas: el espacio de almacenamiento (de sobra para texto e imágenes bien comprimidas), la velocidad de carga y la facilidad para hacer copias de seguridad. Siempre podrás cambiar de alojamiento más adelante si tu sitio crece de verdad.",
          },
          keyPoints: {
            fr: ["L'hébergement = l'espace serveur qui stocke ton site", "Inclus avec Wix/Google Sites ; à part pour WordPress (offres gratuites possibles)", "Vérifier le HTTPS (cadenas) et le support", "Pour débuter, ne surpaie pas : regarde vitesse et sauvegardes"],
            ht: ["Ebèjman = espas sèvè ki estoke sit ou", "Enkli ak Wix/Google Sites ; apa pou WordPress (òf gratis posib)", "Verifye HTTPS (kadna) ak sipò a", "Pou kòmanse, pa peye twòp : gade vitès ak sovgad"],
            en: ["Hosting = the server space that stores your site", "Included with Wix/Google Sites; separate for WordPress (free offers exist)", "Check the HTTPS (padlock) and support", "To start, don't overpay: look at speed and backups"],
            es: ["El alojamiento = el espacio servidor que guarda tu sitio", "Incluido con Wix/Google Sites; aparte para WordPress (hay ofertas gratis)", "Comprobar el HTTPS (candado) y el soporte", "Para empezar, no pagues de más: mira velocidad y copias"],
          },
          exercise: {
            fr: "Selon l'outil que tu as choisi, détermine si l'hébergement est inclus ou à prendre à part. S'il est à part, compare deux offres (une payante comme Hostinger, une gratuite comme Netlify) et note pour chacune : le prix, l'espace, et si le HTTPS est fourni. Choisis celle qui convient à ton premier site.",
            ht: "Selon zouti ou chwazi a, detèmine si ebèjman an enkli oswa si ou dwe pran l apa. Si li apa, konpare de òf (youn ki peye tankou Hostinger, youn gratis tankou Netlify) epi note pou chak : pri a, espas la, ak si HTTPS la bay. Chwazi sa ki bon pou premye sit ou.",
            en: "Depending on the tool you chose, work out whether hosting is included or needs to be taken separately. If separate, compare two offers (a paid one like Hostinger, a free one like Netlify) and note for each: the price, the space, and whether HTTPS is provided. Choose the one that suits your first site.",
            es: "Según la herramienta que elegiste, determina si el alojamiento está incluido o hay que contratarlo aparte. Si es aparte, compara dos ofertas (una de pago como Hostinger, una gratuita como Netlify) y anota para cada una: el precio, el espacio y si incluye HTTPS. Elige la que convenga a tu primer sitio.",
          },
        },
        {
          slug: "relier-domaine-hebergement",
          title: { fr: "Relier le domaine à l'hébergement (et sécuriser)", ht: "Konekte domèn ak ebèjman (epi sekirize)", en: "Linking the domain to hosting (and securing it)", es: "Enlazar el dominio con el alojamiento (y asegurarlo)" },
          videoId: "",
          content: {
            fr: "Tu as une adresse (le domaine) et une maison (l'hébergement) : il faut maintenant les relier pour que taper ton adresse mène bien à ton site. Ce lien se fait grâce au « DNS », un système qui joue le rôle d'annuaire d'Internet : il traduit ton nom de domaine en l'emplacement réel de ton serveur, un peu comme un GPS traduit une adresse en coordonnées.\n\nConcrètement, dans l'espace de gestion de ton domaine, tu ajoutes des « enregistrements DNS » que ton hébergeur te fournit. Souvent c'est un enregistrement « A » (une adresse de serveur) ou « CNAME » (un renvoi vers un autre nom). Ne t'inquiète pas du vocabulaire : la plupart des hébergeurs donnent des instructions pas à pas, et beaucoup proposent même de connecter le domaine automatiquement en quelques clics.\n\nUn point important : les changements DNS ne sont pas toujours instantanés. Il faut parfois attendre de quelques minutes à quelques heures pour que ton adresse pointe partout dans le monde vers ton site. C'est normal, on appelle ça la « propagation ». Ne recommence pas dix fois la manipulation en pensant que ça a échoué : patiente, puis vérifie.\n\nEnfin, active le HTTPS, ce fameux cadenas dans la barre d'adresse. Il chiffre les échanges entre le visiteur et ton site, protège les données et rassure les gens ; Google le réclame aussi pour bien référencer. Chez la plupart des hébergeurs, il s'active gratuitement en un clic (souvent via « Let's Encrypt »). Sans HTTPS, les navigateurs affichent un avertissement « site non sécurisé » qui fait fuir les visiteurs.",
            ht: "Ou gen yon adrès (domèn nan) ak yon kay (ebèjman an) : koulye a fòk ou konekte yo pou lè ou tape adrès ou, li mennen sou sit ou vre. Lyen sa a fèt gras ak « DNS », yon sistèm ki jwe wòl anyè Entènèt la : li tradui non domèn ou an kote reyèl sèvè ou ye a, tankou yon GPS tradui yon adrès an kowòdone.\n\nKonkrèteman, nan espas jesyon domèn ou, ou ajoute « anrejistreman DNS » ebèjè ou ba ou. Souvan se yon anrejistreman « A » (yon adrès sèvè) oswa « CNAME » (yon renvwa sou yon lòt non). Pa enkyete ou pou vokabilè a : pifò ebèjè bay enstriksyon etap pa etap, epi anpil pwopoze menm konekte domèn nan otomatikman an kèk klik.\n\nYon pwen enpòtan : chanjman DNS pa toujou rapid. Pafwa fòk ou tann kèk minit rive kèk èdtan pou adrès ou pwente toupatou nan mond lan sou sit ou. Se nòmal, yo rele sa « pwopagasyon ». Pa refè manipilasyon an dis fwa paske ou panse li echwe : pran pasyans, epi verifye.\n\nAnfen, aktive HTTPS la, fame kadna nan bab adrès la. Li chifre echanj ant vizitè a ak sit ou, pwoteje done yo epi rasire moun ; Google mande l tou pou byen referanse. Nan pifò ebèjè, li aktive gratis an yon klik (souvan atravè « Let's Encrypt »). San HTTPS, navigatè yo montre yon avètisman « sit pa sekirize » ki fè vizitè sove.",
            en: "You have an address (the domain) and a house (the hosting): now you must link them so that typing your address really leads to your site. This link is made through \"DNS\", a system that acts as the Internet's directory: it translates your domain name into the real location of your server, a bit like a GPS turns an address into coordinates.\n\nIn practice, in your domain's management area, you add \"DNS records\" that your host provides. Often it's an \"A\" record (a server address) or a \"CNAME\" (a redirect to another name). Don't worry about the vocabulary: most hosts give step-by-step instructions, and many even offer to connect the domain automatically in a few clicks.\n\nAn important point: DNS changes are not always instant. Sometimes you have to wait from a few minutes to a few hours for your address to point to your site everywhere in the world. This is normal, it's called \"propagation\". Don't redo the whole thing ten times thinking it failed: be patient, then check.\n\nFinally, enable HTTPS, that famous padlock in the address bar. It encrypts the exchange between the visitor and your site, protects data and reassures people; Google also requires it for good ranking. With most hosts, it turns on for free in one click (often via \"Let's Encrypt\"). Without HTTPS, browsers show a \"not secure\" warning that scares visitors away.",
            es: "Tienes una dirección (el dominio) y una casa (el alojamiento): ahora hay que enlazarlos para que al escribir tu dirección lleve de verdad a tu sitio. Ese enlace se hace mediante el «DNS», un sistema que actúa como el directorio de Internet: traduce tu nombre de dominio a la ubicación real de tu servidor, un poco como un GPS traduce una dirección en coordenadas.\n\nEn concreto, en el espacio de gestión de tu dominio, añades «registros DNS» que te proporciona tu alojamiento. A menudo es un registro «A» (una dirección de servidor) o «CNAME» (un reenvío a otro nombre). No te preocupes por el vocabulario: la mayoría de los alojamientos dan instrucciones paso a paso, y muchos incluso ofrecen conectar el dominio automáticamente en unos clics.\n\nUn punto importante: los cambios de DNS no siempre son instantáneos. A veces hay que esperar de unos minutos a unas horas para que tu dirección apunte a tu sitio en todo el mundo. Es normal, se llama «propagación». No rehagas la operación diez veces creyendo que falló: ten paciencia y luego comprueba.\n\nPor último, activa el HTTPS, ese famoso candado en la barra de direcciones. Cifra el intercambio entre el visitante y tu sitio, protege los datos y da confianza a la gente; Google también lo exige para posicionar bien. En la mayoría de los alojamientos se activa gratis con un clic (a menudo mediante «Let's Encrypt»). Sin HTTPS, los navegadores muestran un aviso de «sitio no seguro» que ahuyenta a los visitantes.",
          },
          keyPoints: {
            fr: ["Le DNS relie ton domaine à ton hébergement (l'annuaire d'Internet)", "Ajoute les enregistrements (A/CNAME) fournis par ton hébergeur", "La propagation peut prendre de quelques minutes à quelques heures", "Active le HTTPS gratuit : sécurité, confiance et bon référencement"],
            ht: ["DNS konekte domèn ou ak ebèjman ou (anyè Entènèt la)", "Ajoute anrejistreman (A/CNAME) ebèjè ou bay yo", "Pwopagasyon ka pran kèk minit rive kèk èdtan", "Aktive HTTPS gratis la : sekirite, konfyans ak bon referansman"],
            en: ["DNS links your domain to your hosting (the Internet's directory)", "Add the (A/CNAME) records your host provides", "Propagation can take from a few minutes to a few hours", "Enable free HTTPS: security, trust and good ranking"],
            es: ["El DNS enlaza tu dominio con tu alojamiento (el directorio de Internet)", "Añade los registros (A/CNAME) que da tu alojamiento", "La propagación puede tardar de minutos a horas", "Activa el HTTPS gratuito: seguridad, confianza y buen posicionamiento"],
          },
          exercise: {
            fr: "Dans l'espace de gestion de ton domaine (ou de ton outil), trouve la section « DNS » ou « Domaines connectés ». Suis les instructions de ton hébergeur pour relier ton domaine, puis attends et vérifie que ton adresse ouvre bien ton site. Contrôle enfin que le cadenas HTTPS s'affiche dans la barre d'adresse.",
            ht: "Nan espas jesyon domèn ou (oswa zouti ou), jwenn seksyon « DNS » oswa « Domèn konekte » a. Swiv enstriksyon ebèjè ou pou konekte domèn ou, apre sa tann epi verifye adrès ou louvri sit ou vre. Anfen, kontwole kadna HTTPS la parèt nan bab adrès la.",
            en: "In your domain's management area (or your tool's), find the \"DNS\" or \"Connected domains\" section. Follow your host's instructions to link your domain, then wait and check that your address really opens your site. Finally, confirm the HTTPS padlock shows in the address bar.",
            es: "En el espacio de gestión de tu dominio (o de tu herramienta), busca la sección «DNS» o «Dominios conectados». Sigue las instrucciones de tu alojamiento para enlazar tu dominio, luego espera y comprueba que tu dirección abra de verdad tu sitio. Por último, verifica que el candado HTTPS aparezca en la barra de direcciones.",
          },
        },
      ],
    },
    {
      title: { fr: "Construire les pages du site", ht: "Konstwi paj sit la", en: "Building the site's pages", es: "Construir las páginas del sitio" },
      lessons: [
        {
          slug: "creer-une-page-simple",
          title: { fr: "Créer une première page simple", ht: "Kreye yon premye paj senp", en: "Building a first simple page", es: "Crear una primera página sencilla" },
          videoId: "",
          content: {
            fr: "Une page web efficace suit une structure claire, quel que soit l'outil. En haut, un en-tête avec ton nom ou ton logo et un menu. Ensuite, une grande section d'accueil qui dit en une phrase ce que tu proposes. Puis des sections qui détaillent : qui tu es, ce que tu offres, comment te contacter. Enfin, un pied de page avec tes coordonnées.\n\nDans un constructeur visuel, tu ajoutes chaque partie en glissant des blocs : un bloc titre, un bloc image, un bloc texte, un bloc bouton. Écris des textes courts et clairs. Mets une seule idée par section et un « bouton d'action » visible, par exemple « Nous contacter » ou « Voir les horaires ».\n\nSoigne trois choses qui font la différence : de bonnes images (nettes, bien cadrées), deux ou trois couleurs cohérentes, et un texte sans fautes. Vérifie surtout l'affichage sur téléphone, car la majorité des visiteurs viennent depuis leur mobile — la plupart des outils offrent un aperçu « mobile » d'un simple clic.\n\nPense au visiteur pressé qui décide en cinq secondes. Dès le haut de la page, il doit comprendre trois choses : ce que tu proposes, à qui c'est destiné, et quoi faire ensuite. Si ta section d'accueil répond à ces trois questions d'un coup d'œil, ta page est déjà réussie. Le reste ne fait qu'apporter des détails et rassurer.",
            ht: "Yon paj web efikas swiv yon estrikti klè, kèlkeswa zouti a. Anlè, yon antèt ak non ou oswa logo ou epi yon meni. Apre, yon gwo seksyon akèy ki di nan yon fraz sa ou pwopoze. Answit seksyon ki bay detay : ki moun ou ye, sa ou ofri, kijan pou kontakte ou. Anfen, yon pye paj ak kowòdone ou.\n\nNan yon konstriktè vizyèl, ou ajoute chak pati lè ou trennen blòk : yon blòk tit, yon blòk imaj, yon blòk tèks, yon blòk bouton. Ekri tèks kout epi klè. Mete yon sèl lide pa seksyon epi yon « bouton aksyon » ki vizib, pa egzanp « Kontakte nou » oswa « Wè orè yo ».\n\nSwaye twa bagay ki fè diferans : bon imaj (klè, byen kadre), de oswa twa koulè koyeran, epi yon tèks san fot. Sitou verifye afichaj sou telefòn, paske majorite vizitè yo soti sou mobil yo — pifò zouti bay yon apèsi « mobil » ak yon sèl klik.\n\nPanse ak vizitè prese a ki deside nan senk segonn. Depi anlè paj la, li dwe konprann twa bagay : sa ou pwopoze, pou ki moun li ye, ak kisa pou fè apre. Si seksyon akèy ou reponn twa kesyon sa yo nan yon sèl kout je, paj ou deja reyisi. Rès la sèlman bay detay epi rasire.",
            en: "An effective web page follows a clear structure, whatever the tool. At the top, a header with your name or logo and a menu. Then a large welcome section that says in one sentence what you offer. Then sections that give detail: who you are, what you offer, how to reach you. Finally, a footer with your contact details.\n\nIn a visual builder, you add each part by dragging blocks: a title block, an image block, a text block, a button block. Write short, clear text. Put one idea per section and a visible \"action button\", for example \"Contact us\" or \"See the schedule\".\n\nTake care of three things that make the difference: good images (sharp, well framed), two or three consistent colours, and text with no mistakes. Above all check the display on a phone, because most visitors come from mobile — most tools offer a \"mobile\" preview with a single click.\n\nThink of the hurried visitor who decides in five seconds. From the top of the page, they must understand three things: what you offer, who it's for, and what to do next. If your welcome section answers these three questions at a glance, your page is already a success. The rest only adds details and reassurance.",
            es: "Una página web eficaz sigue una estructura clara, sea cual sea la herramienta. Arriba, un encabezado con tu nombre o logo y un menú. Después, una gran sección de bienvenida que diga en una frase lo que ofreces. Luego secciones con detalle: quién eres, qué ofreces, cómo contactarte. Por último, un pie de página con tus datos.\n\nEn un constructor visual, añades cada parte arrastrando bloques: un bloque de título, uno de imagen, uno de texto, uno de botón. Escribe textos cortos y claros. Pon una sola idea por sección y un «botón de acción» visible, por ejemplo «Contáctanos» o «Ver horarios».\n\nCuida tres cosas que marcan la diferencia: buenas imágenes (nítidas, bien encuadradas), dos o tres colores coherentes, y un texto sin faltas. Sobre todo comprueba la visualización en el teléfono, porque la mayoría de los visitantes llegan desde el móvil — casi todas las herramientas ofrecen una vista previa «móvil» con un solo clic.\n\nPiensa en el visitante apurado que decide en cinco segundos. Desde lo alto de la página debe entender tres cosas: qué ofreces, para quién es y qué hacer después. Si tu sección de bienvenida responde a estas tres preguntas de un vistazo, tu página ya es un éxito. El resto solo añade detalles y da confianza.",
          },
          keyPoints: {
            fr: ["Structure claire : en-tête, accueil, sections, pied de page", "Une idée par section + un bouton d'action visible", "Le haut de page doit dire quoi, pour qui, et l'étape suivante", "Vérifier l'affichage sur téléphone : la plupart des visiteurs sont mobiles"],
            ht: ["Estrikti klè : antèt, akèy, seksyon, pye paj", "Yon lide pa seksyon + yon bouton aksyon vizib", "Anlè paj la dwe di kisa, pou ki moun, ak etap ki apre", "Verifye afichaj sou telefòn : pifò vizitè sou mobil"],
            en: ["Clear structure: header, welcome, sections, footer", "One idea per section + a visible action button", "The top must say what, for whom, and the next step", "Check the phone display: most visitors are on mobile"],
            es: ["Estructura clara: encabezado, bienvenida, secciones, pie", "Una idea por sección + un botón de acción visible", "La parte superior debe decir qué, para quién y el paso siguiente", "Comprobar la vista en el teléfono: la mayoría son móviles"],
          },
          exercise: {
            fr: "Crée la page d'accueil de ton site avec les quatre parties : en-tête (nom + menu), section d'accueil (une phrase claire + un bouton d'action), deux sections de détail, et un pied de page avec tes coordonnées. Limite-toi à deux ou trois couleurs. Puis passe en aperçu mobile et corrige ce qui déborde.",
            ht: "Kreye paj akèy sit ou ak kat pati yo : antèt (non + meni), seksyon akèy (yon fraz klè + yon bouton aksyon), de seksyon detay, ak yon pye paj ak kowòdone ou. Limite ou ak de oswa twa koulè. Apre sa, pase nan apèsi mobil epi korije sa ki depase.",
            en: "Create your site's home page with the four parts: header (name + menu), welcome section (one clear sentence + an action button), two detail sections, and a footer with your contact details. Limit yourself to two or three colours. Then switch to mobile preview and fix anything that overflows.",
            es: "Crea la página de inicio de tu sitio con las cuatro partes: encabezado (nombre + menú), sección de bienvenida (una frase clara + un botón de acción), dos secciones de detalle, y un pie de página con tus datos. Limítate a dos o tres colores. Luego pasa a la vista móvil y corrige lo que se desborde.",
          },
        },
        {
          slug: "structure-navigation",
          title: { fr: "Structure des pages et navigation", ht: "Estrikti paj yo ak navigasyon", en: "Page structure and navigation", es: "Estructura de páginas y navegación" },
          videoId: "",
          content: {
            fr: "Un site est rarement une seule page. Dès qu'il grandit, tu organises l'information en plusieurs pages : Accueil, À propos, Services (ou Produits), Contact. Cette organisation s'appelle l'arborescence : imagine un arbre dont l'accueil est le tronc et les autres pages, les branches. Une bonne arborescence est simple : un visiteur doit atteindre n'importe quelle information en deux ou trois clics maximum.\n\nLe menu de navigation est le fil qui relie ces pages. Place-le en haut, toujours au même endroit, avec des noms courts et évidents. Évite les intitulés vagues ou trop malins : « Contact » est meilleur que « Parlons-en », « Nos tarifs » est plus clair que « L'investissement ». Le visiteur ne doit jamais se demander où cliquer pour trouver ce qu'il cherche.\n\nSoigne les liens internes : depuis l'accueil, renvoie vers tes pages importantes ; depuis une page produit, propose un bouton vers le contact. Chaque page doit aussi indiquer clairement où l'on est (par exemple en surlignant l'onglet actif) et offrir un moyen de revenir à l'accueil, souvent en cliquant sur le logo. Un visiteur qui se sent « perdu » quitte le site.\n\nPense enfin à la page de contact, l'une des plus visitées. Mets-y l'essentiel sans le noyer : un moyen simple de te joindre (formulaire, e-mail, téléphone, WhatsApp), tes horaires si tu en as, et éventuellement une adresse ou une carte. Une navigation claire et une page de contact facile transforment un simple visiteur en client ou en message reçu.",
            ht: "Yon sit raman se yon sèl paj. Depi li grandi, ou òganize enfòmasyon an an plizyè paj : Akèy, Konsènan, Sèvis (oswa Pwodwi), Kontak. Òganizasyon sa a rele akborèsans lan : imajine yon pyebwa kote akèy la se twon an epi lòt paj yo se branch yo. Yon bon akborèsans senp : yon vizitè dwe rive sou nenpòt enfòmasyon nan de oswa twa klik maksimòm.\n\nMeni navigasyon an se fil ki konekte paj sa yo. Mete l anwo, toujou menm kote a, ak non kout epi evidan. Evite non ki vag oswa twò malen : « Kontak » pi bon pase « Ann pale », « Tarif nou » pi klè pase « Envestisman an ». Vizitè a pa dwe janm mande tèt li kote pou l klike pou l jwenn sa l ap chèche.\n\nSwaye lyen entèn yo : depi akèy la, voye sou paj enpòtan ou yo ; depi yon paj pwodwi, pwopoze yon bouton sou kontak la. Chak paj dwe endike klè kote nou ye (pa egzanp lè ou make ongle aktif la) epi ofri yon fason pou retounen sou akèy la, souvan lè ou klike sou logo a. Yon vizitè ki santi l « pèdi » kite sit la.\n\nAnfen, panse ak paj kontak la, youn nan pi vizite yo. Mete ladan l esansyèl la san ou pa neye l : yon fason senp pou jwenn ou (fòm, imel, telefòn, WhatsApp), orè ou si ou genyen, epi petèt yon adrès oswa yon kat. Yon navigasyon klè ak yon paj kontak fasil transfòme yon senp vizitè an kliyan oswa an mesaj resevwa.",
            en: "A site is rarely a single page. As soon as it grows, you organize the information into several pages: Home, About, Services (or Products), Contact. This organization is called the site structure: picture a tree whose home page is the trunk and the other pages the branches. A good structure is simple: a visitor should reach any information in two or three clicks at most.\n\nThe navigation menu is the thread linking these pages. Put it at the top, always in the same place, with short, obvious names. Avoid vague or too-clever labels: \"Contact\" beats \"Let's talk\", \"Our prices\" is clearer than \"The investment\". The visitor should never wonder where to click to find what they're looking for.\n\nTake care of internal links: from the home page, point to your important pages; from a product page, offer a button to contact. Each page should also clearly show where you are (for example by highlighting the active tab) and offer a way back to the home page, often by clicking the logo. A visitor who feels \"lost\" leaves the site.\n\nFinally, think about the contact page, one of the most visited. Put the essentials on it without drowning them: a simple way to reach you (form, email, phone, WhatsApp), your hours if you have them, and possibly an address or a map. Clear navigation and an easy contact page turn a mere visitor into a customer or a message received.",
            es: "Un sitio rara vez es una sola página. En cuanto crece, organizas la información en varias páginas: Inicio, Acerca de, Servicios (o Productos), Contacto. Esta organización se llama la estructura del sitio: imagina un árbol cuyo tronco es la página de inicio y las demás páginas son las ramas. Una buena estructura es simple: un visitante debe llegar a cualquier información en dos o tres clics como máximo.\n\nEl menú de navegación es el hilo que enlaza estas páginas. Ponlo arriba, siempre en el mismo lugar, con nombres cortos y evidentes. Evita etiquetas vagas o demasiado ingeniosas: «Contacto» es mejor que «Hablemos», «Nuestros precios» es más claro que «La inversión». El visitante nunca debe preguntarse dónde hacer clic para encontrar lo que busca.\n\nCuida los enlaces internos: desde el inicio, apunta a tus páginas importantes; desde una página de producto, ofrece un botón hacia el contacto. Cada página debe indicar con claridad dónde estás (por ejemplo resaltando la pestaña activa) y ofrecer una manera de volver al inicio, a menudo haciendo clic en el logo. Un visitante que se siente «perdido» abandona el sitio.\n\nPor último, piensa en la página de contacto, una de las más visitadas. Pon en ella lo esencial sin ahogarlo: una forma simple de localizarte (formulario, correo, teléfono, WhatsApp), tus horarios si los tienes, y quizás una dirección o un mapa. Una navegación clara y una página de contacto fácil convierten a un simple visitante en cliente o en un mensaje recibido.",
          },
          keyPoints: {
            fr: ["Organise le site en quelques pages claires (arborescence simple)", "Toute info doit être atteignable en 2-3 clics maximum", "Menu en haut, noms courts et évidents (pas d'intitulés « malins »)", "Soigne les liens internes et une page de contact facile"],
            ht: ["Òganize sit la an kèk paj klè (akborèsans senp)", "Tout enfòmasyon dwe rive nan 2-3 klik maksimòm", "Meni anwo, non kout epi evidan (pa non « malen »)", "Swaye lyen entèn yo ak yon paj kontak fasil"],
            en: ["Organize the site into a few clear pages (simple structure)", "Any info should be reachable in 2-3 clicks maximum", "Menu at top, short obvious names (no 'clever' labels)", "Care for internal links and an easy contact page"],
            es: ["Organiza el sitio en unas pocas páginas claras (estructura simple)", "Cualquier información debe alcanzarse en 2-3 clics máximo", "Menú arriba, nombres cortos y evidentes (sin etiquetas «ingeniosas»)", "Cuida los enlaces internos y una página de contacto fácil"],
          },
          exercise: {
            fr: "Dessine l'arborescence de ton site sur une feuille : l'accueil au centre, et autour les pages (À propos, Services/Produits, Contact). Écris les noms exacts du menu. Puis, dans ton outil, crée ces pages et relie-les par le menu du haut. Vérifie qu'en trois clics maximum on atteint chaque page, et que le logo ramène à l'accueil.",
            ht: "Desine akborèsans sit ou sou yon fèy : akèy la nan sant lan, epi otou paj yo (Konsènan, Sèvis/Pwodwi, Kontak). Ekri non egzak meni an. Apre sa, nan zouti ou, kreye paj sa yo epi konekte yo ak meni anwo a. Verifye an twa klik maksimòm ou rive sou chak paj, epi logo a mennen sou akèy la.",
            en: "Draw your site's structure on a sheet: the home page in the centre, and around it the pages (About, Services/Products, Contact). Write the exact menu names. Then, in your tool, create these pages and link them via the top menu. Check that every page is reachable in three clicks maximum, and that the logo returns to the home page.",
            es: "Dibuja la estructura de tu sitio en una hoja: el inicio en el centro y alrededor las páginas (Acerca de, Servicios/Productos, Contacto). Escribe los nombres exactos del menú. Luego, en tu herramienta, crea esas páginas y enlázalas con el menú superior. Comprueba que cada página se alcance en tres clics máximo y que el logo lleve al inicio.",
          },
        },
        {
          slug: "responsive-mobile",
          title: { fr: "Rendre son site lisible sur mobile (responsive)", ht: "Fè sit ou lizib sou mobil (responsive)", en: "Making your site readable on mobile (responsive)", es: "Hacer tu sitio legible en móvil (responsive)" },
          videoId: "",
          content: {
            fr: "Aujourd'hui, la majorité des gens visiteront ton site depuis leur téléphone. Un site « responsive » est un site qui s'adapte automatiquement à la taille de l'écran : sur ordinateur il affiche plusieurs colonnes côte à côte, sur mobile il les empile les unes sous les autres pour rester lisible. Ce n'est pas un luxe, c'est la base : un site illisible sur mobile perd la plupart de ses visiteurs.\n\nLa bonne nouvelle : la plupart des constructeurs (Wix, WordPress, Google Sites) sont responsives par défaut. Ton travail consiste surtout à vérifier et à ajuster. Utilise le bouton d'aperçu « mobile » de ton outil, ou ouvre simplement ton site sur ton propre téléphone. Regarde d'un œil critique : le texte est-il assez gros ? Les boutons sont-ils faciles à toucher avec le pouce ? Les images débordent-elles ?\n\nQuelques règles simples aident beaucoup. Garde un texte d'au moins 16 pixels pour qu'il reste lisible sans zoomer. Espace bien les boutons et les liens pour éviter les clics ratés. Évite les tableaux larges et les images énormes qui obligent à faire défiler horizontalement — un contenu ne devrait jamais déborder sur les côtés. Compresse tes images pour que la page se charge vite, surtout en connexion mobile.\n\nPense aussi « mobile d'abord » quand tu conçois : si l'essentiel de ton message tient bien sur un petit écran, il tiendra forcément sur un grand. Mets en premier ce qui compte le plus (ton offre, ton bouton d'action), et repousse les détails plus bas. Teste sur au moins deux téléphones différents si tu peux, car les tailles d'écran varient. Un site qui s'affiche parfaitement sur mobile inspire immédiatement confiance et sérieux.",
            ht: "Jodi a, majorite moun ap vizite sit ou depi telefòn yo. Yon sit « responsive » se yon sit ki adapte otomatikman ak gwosè ekran an : sou òdinatè li montre plizyè kolòn kòtakòt, sou mobil li anpile yo youn anba lòt pou l rete lizib. Se pa yon liks, se baz la : yon sit ki pa lizib sou mobil pèdi pifò vizitè li.\n\nBòn nouvèl la : pifò konstriktè (Wix, WordPress, Google Sites) responsive pa defo. Travay ou se sitou verifye epi ajiste. Sèvi ak bouton apèsi « mobil » zouti ou, oswa senpleman louvri sit ou sou pwòp telefòn ou. Gade ak yon je kritik : èske tèks la ase gwo ? Èske bouton yo fasil pou manyen ak pous la ? Èske imaj yo depase ?\n\nKèk règ senp ede anpil. Kenbe yon tèks omwen 16 piksèl pou l rete lizib san zoum. Byen espase bouton ak lyen yo pou evite move klik. Evite gwo tablo ak gwo imaj ki fòse ou fè defile sou kote — yon kontni pa ta dwe janm depase sou kote yo. Konprese imaj ou pou paj la chaje vit, sitou sou koneksyon mobil.\n\nPanse tou « mobil an premye » lè w ap konsevwa : si esansyèl mesaj ou byen tchembe sou yon ti ekran, l ap tchembe sou yon gwo tou. Mete an premye sa ki pi enpòtan (òf ou, bouton aksyon ou), epi pouse detay yo pi ba. Teste sou omwen de telefòn diferan si ou kapab, paske gwosè ekran yo varye. Yon sit ki afiche pafètman sou mobil bay konfyans ak seryozite touswit.",
            en: "Today, most people will visit your site from their phone. A \"responsive\" site is one that adapts automatically to the screen size: on a computer it shows several columns side by side, on mobile it stacks them one under the other to stay readable. This isn't a luxury, it's the baseline: a site that's unreadable on mobile loses most of its visitors.\n\nThe good news: most builders (Wix, WordPress, Google Sites) are responsive by default. Your job is mainly to check and adjust. Use your tool's \"mobile\" preview button, or simply open your site on your own phone. Look critically: is the text big enough? Are buttons easy to tap with a thumb? Do images overflow?\n\nA few simple rules help a lot. Keep text at least 16 pixels so it stays readable without zooming. Space buttons and links well to avoid mis-taps. Avoid wide tables and huge images that force horizontal scrolling — content should never spill off the sides. Compress your images so the page loads fast, especially on a mobile connection.\n\nAlso think \"mobile first\" when you design: if the core of your message fits well on a small screen, it will surely fit on a big one. Put what matters most first (your offer, your action button), and push details lower down. Test on at least two different phones if you can, because screen sizes vary. A site that displays perfectly on mobile instantly inspires trust and seriousness.",
            es: "Hoy, la mayoría de la gente visitará tu sitio desde su teléfono. Un sitio «responsive» es uno que se adapta automáticamente al tamaño de la pantalla: en computadora muestra varias columnas una al lado de otra, en móvil las apila una debajo de otra para seguir siendo legible. No es un lujo, es lo básico: un sitio ilegible en móvil pierde a la mayoría de sus visitantes.\n\nLa buena noticia: la mayoría de los constructores (Wix, WordPress, Google Sites) son responsive por defecto. Tu trabajo consiste sobre todo en comprobar y ajustar. Usa el botón de vista previa «móvil» de tu herramienta, o simplemente abre tu sitio en tu propio teléfono. Mira con ojo crítico: ¿el texto es bastante grande? ¿Los botones son fáciles de tocar con el pulgar? ¿Las imágenes se desbordan?\n\nUnas reglas simples ayudan mucho. Mantén el texto en al menos 16 píxeles para que sea legible sin ampliar. Espacia bien los botones y enlaces para evitar toques fallidos. Evita tablas anchas e imágenes enormes que obliguen a desplazarse en horizontal — un contenido nunca debería salirse por los lados. Comprime tus imágenes para que la página cargue rápido, sobre todo en conexión móvil.\n\nPiensa también «móvil primero» al diseñar: si lo esencial de tu mensaje cabe bien en una pantalla pequeña, cabrá seguro en una grande. Pon primero lo que más importa (tu oferta, tu botón de acción) y deja los detalles más abajo. Prueba en al menos dos teléfonos distintos si puedes, porque los tamaños de pantalla varían. Un sitio que se ve perfecto en móvil inspira confianza y seriedad de inmediato.",
          },
          keyPoints: {
            fr: ["Responsive = le site s'adapte à la taille de l'écran", "La plupart des visiteurs sont sur mobile : teste sur ton téléphone", "Texte lisible (≥ 16 px), boutons espacés, images compressées", "Conçois « mobile d'abord » : l'essentiel en haut, les détails en bas"],
            ht: ["Responsive = sit la adapte ak gwosè ekran an", "Pifò vizitè sou mobil : teste sou telefòn ou", "Tèks lizib (≥ 16 px), bouton byen espase, imaj konprese", "Konsevwa « mobil an premye » : esansyèl anwo, detay anba"],
            en: ["Responsive = the site adapts to the screen size", "Most visitors are on mobile: test on your phone", "Readable text (≥ 16 px), spaced buttons, compressed images", "Design 'mobile first': essentials on top, details below"],
            es: ["Responsive = el sitio se adapta al tamaño de la pantalla", "La mayoría de los visitantes están en móvil: prueba en tu teléfono", "Texto legible (≥ 16 px), botones espaciados, imágenes comprimidas", "Diseña «móvil primero»: lo esencial arriba, los detalles abajo"],
          },
          exercise: {
            fr: "Ouvre ton site sur ton propre téléphone et parcours chaque page. Note trois problèmes concrets (texte trop petit, image qui déborde, bouton trop proche d'un autre) et corrige-les dans l'aperçu mobile de ton outil. Compresse au moins une image lourde, puis recharge la page et vérifie qu'elle s'ouvre vite.",
            ht: "Louvri sit ou sou pwòp telefòn ou epi pase nan chak paj. Note twa pwoblèm konkrè (tèks twò piti, imaj ki depase, bouton twò pre yon lòt) epi korije yo nan apèsi mobil zouti ou. Konprese omwen yon imaj lou, apre sa rechaje paj la epi verifye li louvri vit.",
            en: "Open your site on your own phone and go through each page. Note three concrete problems (text too small, image overflowing, button too close to another) and fix them in your tool's mobile preview. Compress at least one heavy image, then reload the page and check it opens fast.",
            es: "Abre tu sitio en tu propio teléfono y recorre cada página. Anota tres problemas concretos (texto demasiado pequeño, imagen que se desborda, botón demasiado cerca de otro) y corrígelos en la vista móvil de tu herramienta. Comprime al menos una imagen pesada, luego recarga la página y comprueba que abra rápido.",
          },
        },
      ],
    },
    {
      title: { fr: "Publier et être trouvé", ht: "Pibliye epi vin jwenn", en: "Publishing and being found", es: "Publicar y ser encontrado" },
      lessons: [
        {
          slug: "publier-son-site",
          title: { fr: "Publier et vérifier son site", ht: "Pibliye epi verifye sit ou", en: "Publishing and checking your site", es: "Publicar y verificar tu sitio" },
          videoId: "",
          content: {
            fr: "Publier, c'est rendre ton site visible par tout le monde. Dans un constructeur, il suffit souvent de cliquer sur un bouton « Publier » : ton site devient accessible en ligne, d'abord sur une adresse fournie par l'outil, puis sur ton propre domaine une fois relié. Avant de publier, relis chaque page et clique sur tous les liens pour vérifier qu'ils fonctionnent.\n\nAvant la mise en ligne, passe une petite check-list. Chaque page a-t-elle un titre clair ? Les coordonnées sont-elles justes (numéro, e-mail, adresse) ? Les images s'affichent-elles toutes ? Le formulaire de contact envoie-t-il bien un message ? As-tu relu les textes pour éliminer les fautes ? Cette vérification de dix minutes t'évite de publier des erreurs que tout le monde verra.\n\nUn site publié n'est pas figé : tu peux le modifier quand tu veux, corriger une faute, ajouter une nouvelle page. Fais des sauvegardes régulières si ton outil le permet, surtout avant un grand changement. Ainsi, si une modification casse quelque chose, tu peux revenir en arrière sans stress.\n\nEnfin, teste ton site comme un vrai visiteur : ouvre-le dans un autre navigateur, sur un autre appareil, et même en navigation privée pour voir ce que voit quelqu'un qui ne te connaît pas. Demande à deux ou trois proches de le parcourir et de te dire, sans que tu les guides, s'ils comprennent ce que tu proposes et comment te contacter. Leurs hésitations te montreront exactement quoi améliorer.",
            ht: "Pibliye, se rann sit ou vizib pou tout moun. Nan yon konstriktè, souvan ou jis klike sou yon bouton « Pibliye » : sit ou vin aksesib an liy, dabò sou yon adrès zouti a bay, epi sou pwòp domèn ou yon fwa li konekte. Anvan ou pibliye, reli chak paj epi klike sou tout lyen pou verifye yo fonksyone.\n\nAnvan mete an liy, pase yon ti chèk-lis. Èske chak paj gen yon tit klè ? Èske kowòdone yo kòrèk (nimewo, imel, adrès) ? Èske tout imaj yo afiche ? Èske fòm kontak la voye yon mesaj vre ? Èske ou reli tèks yo pou retire fot ? Verifikasyon dis minit sa a anpeche ou pibliye erè tout moun ap wè.\n\nYon sit ki pibliye pa fikse : ou ka modifye l lè ou vle, korije yon fot, ajoute yon nouvo paj. Fè sovgad regilyèman si zouti ou pèmèt li, sitou anvan yon gwo chanjman. Konsa, si yon modifikasyon kase yon bagay, ou ka retounen an aryè san estrès.\n\nAnfen, teste sit ou tankou yon vrè vizitè : louvri l nan yon lòt navigatè, sou yon lòt aparèy, epi menm an navigasyon prive pou wè sa yon moun ki pa konnen ou wè. Mande de oswa twa moun pre ou pou pase nan li epi di ou, san ou pa gide yo, si yo konprann sa ou pwopoze ak kijan pou kontakte ou. Ezitasyon yo ap montre ou egzakteman sa pou amelyore.",
            en: "Publishing means making your site visible to everyone. In a builder, it's often just clicking a \"Publish\" button: your site goes online, first on an address provided by the tool, then on your own domain once linked. Before publishing, reread each page and click every link to check they work.\n\nBefore going live, run a short checklist. Does each page have a clear title? Are the contact details correct (number, email, address)? Do all images show up? Does the contact form actually send a message? Have you reread the texts to remove mistakes? This ten-minute check keeps you from publishing errors everyone will see.\n\nA published site is not frozen: you can change it whenever you want, fix a mistake, add a new page. Make regular backups if your tool allows it, especially before a big change. That way, if a change breaks something, you can roll back without stress.\n\nFinally, test your site like a real visitor: open it in another browser, on another device, and even in private browsing to see what someone who doesn't know you sees. Ask two or three friends to go through it and tell you, without your guidance, whether they understand what you offer and how to contact you. Their hesitations will show you exactly what to improve.",
            es: "Publicar es hacer tu sitio visible para todos. En un constructor, a menudo basta con hacer clic en un botón «Publicar»: tu sitio queda en línea, primero en una dirección que da la herramienta, y luego en tu propio dominio una vez enlazado. Antes de publicar, relee cada página y haz clic en todos los enlaces para comprobar que funcionan.\n\nAntes de la publicación, repasa una pequeña lista de control. ¿Cada página tiene un título claro? ¿Los datos de contacto son correctos (número, correo, dirección)? ¿Se muestran todas las imágenes? ¿El formulario de contacto envía de verdad un mensaje? ¿Releíste los textos para eliminar faltas? Esta revisión de diez minutos evita que publiques errores que todos verán.\n\nUn sitio publicado no queda congelado: puedes modificarlo cuando quieras, corregir una falta, añadir una página nueva. Haz copias de seguridad periódicas si tu herramienta lo permite, sobre todo antes de un gran cambio. Así, si una modificación rompe algo, puedes volver atrás sin estrés.\n\nPor último, prueba tu sitio como un visitante real: ábrelo en otro navegador, en otro dispositivo, e incluso en navegación privada para ver lo que ve alguien que no te conoce. Pide a dos o tres allegados que lo recorran y te digan, sin que los guíes, si entienden lo que ofreces y cómo contactarte. Sus dudas te mostrarán exactamente qué mejorar.",
          },
          keyPoints: {
            fr: ["Publier = un clic ; d'abord relire et tester tous les liens", "Passe une check-list : titres, coordonnées, images, formulaire", "Fais des sauvegardes avant les grands changements", "Fais tester ton site par des proches sans les guider"],
            ht: ["Pibliye = yon klik ; dabò reli epi teste tout lyen yo", "Pase yon chèk-lis : tit, kowòdone, imaj, fòm", "Fè sovgad anvan gwo chanjman yo", "Fè moun pre ou teste sit la san ou pa gide yo"],
            en: ["Publish = one click; first reread and test every link", "Run a checklist: titles, contact details, images, form", "Make backups before big changes", "Have friends test your site without your guidance"],
            es: ["Publicar = un clic; primero releer y probar todos los enlaces", "Repasa una lista: títulos, datos de contacto, imágenes, formulario", "Haz copias de seguridad antes de los grandes cambios", "Haz que allegados prueben tu sitio sin guiarlos"],
          },
          exercise: {
            fr: "Avant de publier, remplis une check-list écrite : titres de page, coordonnées exactes, images qui s'affichent, liens qui marchent, formulaire testé. Corrige tout ce qui cloche, puis clique sur « Publier ». Enfin, ouvre ton site en navigation privée et demande à un proche de le tester et de te dire ce qu'il a compris.",
            ht: "Anvan ou pibliye, ranpli yon chèk-lis ekri : tit paj, kowòdone egzak, imaj ki afiche, lyen ki mache, fòm teste. Korije tout sa ki pa bon, apre sa klike sou « Pibliye ». Anfen, louvri sit ou an navigasyon prive epi mande yon moun pre ou pou teste l epi di ou sa li konprann.",
            en: "Before publishing, fill in a written checklist: page titles, correct contact details, images displaying, working links, tested form. Fix everything that's off, then click \"Publish\". Finally, open your site in private browsing and ask someone close to test it and tell you what they understood.",
            es: "Antes de publicar, completa una lista de control escrita: títulos de página, datos de contacto correctos, imágenes que se muestran, enlaces que funcionan, formulario probado. Corrige todo lo que falle, luego haz clic en «Publicar». Por último, abre tu sitio en navegación privada y pide a un allegado que lo pruebe y te diga qué entendió.",
          },
        },
        {
          slug: "referencement-seo",
          title: { fr: "Le référencement de base (SEO)", ht: "Referansman de baz (SEO)", en: "Basic search ranking (SEO)", es: "El posicionamiento básico (SEO)" },
          videoId: "",
          content: {
            fr: "Le référencement, ou SEO, c'est l'ensemble des petites choses qui aident les moteurs de recherche comme Google à comprendre ton site et à le proposer aux bonnes personnes. Ce n'est pas de la magie ni un truc réservé aux experts : quelques réglages simples suffisent pour un premier site, et ils font une vraie différence pour être trouvé.\n\nCommence par les mots. Utilise les vrais mots que tes visiteurs taperaient. Si tu vends des gâteaux d'anniversaire à Port-au-Prince, ces mots exacts doivent apparaître dans tes titres et tes textes, pas seulement « nos délicieuses créations ». Mets-toi à la place du client : que taperait-il dans Google pour te trouver ? Écris pour lui, avec ses mots à lui.\n\nEnsuite, soigne trois éléments techniques mais faciles. Le titre de la page (la « balise title »), qui s'affiche dans l'onglet et dans les résultats de recherche : donne-lui un titre clair et unique par page. La description (la « meta description »), une ou deux phrases qui résument la page et donnent envie de cliquer. Et le texte alternatif des images (le « alt »), qui décrit chaque image — utile pour Google et pour les personnes malvoyantes.\n\nEnfin, sache que le meilleur SEO reste un bon contenu, utile et honnête, mis à jour régulièrement. Google favorise les sites qui répondent vraiment aux questions des gens. Ajoute progressivement des pages utiles, obtiens des liens depuis d'autres sites qui parlent de toi (un annuaire local, la page d'un partenaire), et sois patient : le référencement se construit sur plusieurs semaines, pas en un jour. Inscris aussi ton site dans « Google Search Console », un outil gratuit qui aide Google à trouver tes pages.",
            ht: "Referansman, oswa SEO, se ansanm ti bagay ki ede motè rechèch tankou Google konprann sit ou epi pwopoze l bay bon moun yo. Se pa maji ni yon bagay ki rezève pou ekspè : kèk ti reglaj senp ase pou yon premye sit, epi yo fè yon vrè diferans pou vin jwenn.\n\nKòmanse ak mo yo. Sèvi ak vrè mo vizitè ou yo ta tape. Si ou vann gato fèt nan Pòtoprens, mo egzak sa yo dwe parèt nan tit ak tèks ou yo, pa sèlman « bèl kreyasyon nou yo ». Mete tèt ou nan plas kliyan an : kisa li ta tape nan Google pou jwenn ou ? Ekri pou li, ak mo pa l yo.\n\nApre sa, swaye twa eleman teknik men fasil. Tit paj la (« baliz title » a), ki afiche nan ongle a ak nan rezilta rechèch yo : ba li yon tit klè epi inik pou chak paj. Deskripsyon an (« meta description » lan), yon oswa de fraz ki rezime paj la epi bay anvi klike. Ak tèks altènatif imaj yo (« alt » la), ki dekri chak imaj — itil pou Google ak pou moun ki pa wè byen.\n\nAnfen, konnen pi bon SEO a rete yon bon kontni, itil epi onèt, ki mete ajou regilyèman. Google favorize sit ki reponn vrèman kesyon moun yo. Ajoute piti piti paj itil, jwenn lyen depi lòt sit ki pale de ou (yon anyè lokal, paj yon patnè), epi pran pasyans : referansman konstwi sou plizyè semèn, pa nan yon jou. Enskri sit ou tou nan « Google Search Console », yon zouti gratis ki ede Google jwenn paj ou yo.",
            en: "Search ranking, or SEO, is all the small things that help search engines like Google understand your site and offer it to the right people. It's not magic nor something reserved for experts: a few simple settings are enough for a first site, and they make a real difference in being found.\n\nStart with words. Use the real words your visitors would type. If you sell birthday cakes in Port-au-Prince, those exact words should appear in your titles and texts, not just \"our delicious creations\". Put yourself in the customer's shoes: what would they type into Google to find you? Write for them, in their own words.\n\nNext, take care of three technical but easy elements. The page title (the \"title tag\"), which shows in the tab and in search results: give it a clear, unique title per page. The description (the \"meta description\"), one or two sentences summarizing the page and making people want to click. And the alternative text of images (the \"alt\"), which describes each image — useful for Google and for visually impaired people.\n\nFinally, know that the best SEO remains good content, useful and honest, updated regularly. Google favours sites that truly answer people's questions. Gradually add useful pages, get links from other sites that mention you (a local directory, a partner's page), and be patient: ranking builds over several weeks, not in a day. Also register your site in \"Google Search Console\", a free tool that helps Google find your pages.",
            es: "El posicionamiento, o SEO, es el conjunto de pequeñas cosas que ayudan a los buscadores como Google a entender tu sitio y ofrecerlo a las personas adecuadas. No es magia ni algo reservado a expertos: unos ajustes simples bastan para un primer sitio, y marcan una diferencia real para ser encontrado.\n\nEmpieza por las palabras. Usa las palabras reales que tus visitantes escribirían. Si vendes pasteles de cumpleaños en Puerto Príncipe, esas palabras exactas deben aparecer en tus títulos y textos, no solo «nuestras deliciosas creaciones». Ponte en el lugar del cliente: ¿qué escribiría en Google para encontrarte? Escribe para él, con sus propias palabras.\n\nDespués, cuida tres elementos técnicos pero fáciles. El título de la página (la «etiqueta title»), que aparece en la pestaña y en los resultados de búsqueda: dale un título claro y único por página. La descripción (la «meta description»), una o dos frases que resuman la página y den ganas de hacer clic. Y el texto alternativo de las imágenes (el «alt»), que describe cada imagen — útil para Google y para las personas con baja visión.\n\nPor último, has de saber que el mejor SEO sigue siendo un buen contenido, útil y honesto, actualizado con regularidad. Google favorece los sitios que responden de verdad a las preguntas de la gente. Añade poco a poco páginas útiles, consigue enlaces desde otros sitios que hablen de ti (un directorio local, la página de un socio), y ten paciencia: el posicionamiento se construye a lo largo de varias semanas, no en un día. Registra también tu sitio en «Google Search Console», una herramienta gratuita que ayuda a Google a encontrar tus páginas.",
          },
          keyPoints: {
            fr: ["Le SEO aide Google à comprendre et proposer ton site", "Emploie les vrais mots que tes clients taperaient", "Soigne le titre, la description et le texte alternatif des images", "Le meilleur SEO = un bon contenu utile ; sois patient"],
            ht: ["SEO ede Google konprann epi pwopoze sit ou", "Sèvi ak vrè mo kliyan ou yo ta tape", "Swaye tit, deskripsyon ak tèks altènatif imaj yo", "Pi bon SEO = yon bon kontni itil ; pran pasyans"],
            en: ["SEO helps Google understand and offer your site", "Use the real words your customers would type", "Care for the title, description and images' alt text", "The best SEO = good useful content; be patient"],
            es: ["El SEO ayuda a Google a entender y ofrecer tu sitio", "Usa las palabras reales que tus clientes escribirían", "Cuida el título, la descripción y el texto alternativo de las imágenes", "El mejor SEO = un buen contenido útil; ten paciencia"],
          },
          exercise: {
            fr: "Écris cinq mots ou expressions que ton client taperait dans Google pour trouver un site comme le tien. Vérifie qu'ils apparaissent dans tes titres et tes textes. Puis, pour ta page d'accueil, rédige un titre clair (balise title) et une description de deux phrases, et ajoute un texte alternatif à chacune de tes images.",
            ht: "Ekri senk mo oswa ekspresyon kliyan ou ta tape nan Google pou jwenn yon sit tankou pa ou. Verifye yo parèt nan tit ak tèks ou yo. Apre sa, pou paj akèy ou, ekri yon tit klè (baliz title) ak yon deskripsyon de fraz, epi ajoute yon tèks altènatif sou chak imaj ou.",
            en: "Write five words or phrases your customer would type into Google to find a site like yours. Check that they appear in your titles and texts. Then, for your home page, write a clear title (title tag) and a two-sentence description, and add alt text to each of your images.",
            es: "Escribe cinco palabras o expresiones que tu cliente escribiría en Google para encontrar un sitio como el tuyo. Comprueba que aparezcan en tus títulos y textos. Luego, para tu página de inicio, redacta un título claro (etiqueta title) y una descripción de dos frases, y añade un texto alternativo a cada una de tus imágenes.",
          },
        },
        {
          slug: "faire-connaitre-entretenir",
          title: { fr: "Faire connaître et entretenir son site", ht: "Fè sit ou konnen epi antretni l", en: "Promoting and maintaining your site", es: "Dar a conocer y mantener tu sitio" },
          videoId: "",
          content: {
            fr: "Un beau site que personne ne connaît reste vide. Une fois publié, ton travail consiste à faire venir les gens et à leur donner envie de revenir. Commence par le plus simple : mets ton adresse partout où tu es déjà présent — cartes de visite, signature d'e-mail, réseaux sociaux, flyers, vitrine, groupes WhatsApp. Chaque endroit où quelqu'un peut te croiser doit mener à ton site.\n\nLes réseaux sociaux et le bouche-à-oreille sont tes meilleurs alliés au début. Partage le lien avec un message clair (« Voici mon nouveau site, dites-moi ce que vous en pensez »). Demande à tes proches et premiers clients de le partager à leur tour. Si tu as une activité locale, inscris-toi dans les annuaires gratuits et sur « Google Business Profile » pour apparaître sur la carte quand on cherche près de chez toi.\n\nUn site vivant est un site qu'on met à jour. Reviens-y régulièrement : corrige une info qui a changé, ajoute une nouveauté, une photo récente, un témoignage de client. Un site figé depuis deux ans donne l'impression que l'activité s'est arrêtée. Même une petite mise à jour par mois montre que tu es actif et sérieux, et cela plaît autant aux visiteurs qu'à Google.\n\nEnfin, écoute et mesure. Regarde combien de personnes visitent (la plupart des outils affichent des statistiques simples), quelles pages plaisent, d'où viennent les visiteurs. Demande leur avis à ceux qui te contactent. Améliore ton site petit à petit selon ces retours plutôt que de tout refaire d'un coup. Un site se construit dans le temps, pas en un jour : chaque petit progrès régulier finit par payer.",
            ht: "Yon bèl sit pèsonn pa konnen rete vid. Yon fwa li pibliye, travay ou se fè moun vini epi ba yo anvi retounen. Kòmanse ak sa ki pi senp la : mete adrès ou toupatou kote ou deja prezan — kat vizit, siyati imel, rezo sosyal, flyer, vitrin, gwoup WhatsApp. Chak kote yon moun ka kwaze ou dwe mennen sou sit ou.\n\nRezo sosyal ak bouch a zòrèy se pi bon alye ou nan kòmansman. Pataje lyen an ak yon mesaj klè (« Men nouvo sit mwen, di mwen sa nou panse »). Mande moun pre ou ak premye kliyan ou pou pataje l tou. Si ou gen yon aktivite lokal, enskri nan anyè gratis yo ak sou « Google Business Profile » pou parèt sou kat la lè moun chèche toupre lakay ou.\n\nYon sit vivan se yon sit ou mete ajou. Retounen sou li regilyèman : korije yon enfòmasyon ki chanje, ajoute yon nouvote, yon foto resan, yon temwayaj kliyan. Yon sit ki fikse depi dezan bay enpresyon aktivite a rete. Menm yon ti mizajou pa mwa montre ou aktif epi serye, epi sa fè plezi ni vizitè yo ni Google.\n\nAnfen, koute epi mezire. Gade konbyen moun vizite (pifò zouti montre estatistik senp), ki paj ki fè plezi, ki kote vizitè yo soti. Mande opinyon moun ki kontakte ou. Amelyore sit ou piti piti selon reyaksyon sa yo olye pou ou refè tout ankò yon sèl kou. Yon sit konstwi nan tan, pa nan yon jou : chak ti pwogrè regilye fini pa peye.",
            en: "A beautiful site nobody knows about stays empty. Once published, your job is to bring people in and make them want to come back. Start with the simplest thing: put your address everywhere you're already present — business cards, email signature, social media, flyers, shop window, WhatsApp groups. Every place someone can meet you should lead to your site.\n\nSocial media and word of mouth are your best allies at the start. Share the link with a clear message (\"Here's my new site, tell me what you think\"). Ask your friends and first customers to share it in turn. If you have a local business, sign up in free directories and on \"Google Business Profile\" to appear on the map when people search near you.\n\nA living site is one you keep updated. Come back to it regularly: fix info that has changed, add something new, a recent photo, a customer testimonial. A site frozen for two years gives the impression the business has stopped. Even a small update each month shows you're active and serious, and that pleases visitors and Google alike.\n\nFinally, listen and measure. Look at how many people visit (most tools show simple statistics), which pages people like, where visitors come from. Ask for feedback from those who contact you. Improve your site little by little based on this feedback rather than redoing everything at once. A site is built over time, not in a day: each small, regular improvement ends up paying off.",
            es: "Un sitio bonito que nadie conoce queda vacío. Una vez publicado, tu trabajo es atraer a la gente y darle ganas de volver. Empieza por lo más simple: pon tu dirección en todos los sitios donde ya estás presente — tarjetas de visita, firma de correo, redes sociales, folletos, escaparate, grupos de WhatsApp. Cada lugar donde alguien pueda cruzarse contigo debe llevar a tu sitio.\n\nLas redes sociales y el boca a boca son tus mejores aliados al principio. Comparte el enlace con un mensaje claro («Este es mi nuevo sitio, dime qué te parece»). Pide a tus allegados y primeros clientes que lo compartan a su vez. Si tienes un negocio local, inscríbete en los directorios gratuitos y en «Google Business Profile» para aparecer en el mapa cuando la gente busca cerca de ti.\n\nUn sitio vivo es uno que se actualiza. Vuelve a él con regularidad: corrige una información que cambió, añade una novedad, una foto reciente, un testimonio de cliente. Un sitio congelado desde hace dos años da la impresión de que la actividad se detuvo. Incluso una pequeña actualización al mes muestra que estás activo y eres serio, y eso gusta tanto a los visitantes como a Google.\n\nPor último, escucha y mide. Mira cuántas personas visitan (la mayoría de las herramientas muestran estadísticas simples), qué páginas gustan, de dónde vienen los visitantes. Pide opinión a quienes te contactan. Mejora tu sitio poco a poco según estos comentarios en lugar de rehacerlo todo de golpe. Un sitio se construye con el tiempo, no en un día: cada pequeño progreso constante termina dando frutos.",
          },
          keyPoints: {
            fr: ["Mets ton adresse partout : cartes, réseaux, signature, flyers", "Réseaux sociaux + bouche-à-oreille ; annuaires locaux pour le local", "Mets ton site à jour régulièrement pour le garder vivant", "Mesure les visites et améliore petit à petit selon les retours"],
            ht: ["Mete adrès ou toupatou : kat, rezo, siyati, flyer", "Rezo sosyal + bouch a zòrèy ; anyè lokal pou lokal la", "Mete sit ou ajou regilyèman pou kenbe l vivan", "Mezire vizit yo epi amelyore piti piti selon reyaksyon"],
            en: ["Put your address everywhere: cards, socials, signature, flyers", "Social media + word of mouth; local directories for local", "Update your site regularly to keep it alive", "Measure visits and improve little by little from feedback"],
            es: ["Pon tu dirección en todas partes: tarjetas, redes, firma, folletos", "Redes sociales + boca a boca; directorios locales para lo local", "Actualiza tu sitio con regularidad para mantenerlo vivo", "Mide las visitas y mejora poco a poco según los comentarios"],
          },
          exercise: {
            fr: "Fais la liste de cinq endroits où tu vas ajouter l'adresse de ton site cette semaine (signature d'e-mail, profil de réseau social, carte de visite, groupe WhatsApp, vitrine). Publie une annonce avec le lien et demande à trois personnes de le partager. Enfin, planifie une petite mise à jour de ton site chaque mois dans ton agenda.",
            ht: "Fè lis senk kote ou pral ajoute adrès sit ou semèn sa a (siyati imel, pwofil rezo sosyal, kat vizit, gwoup WhatsApp, vitrin). Pibliye yon anons ak lyen an epi mande twa moun pou pataje l. Anfen, planifye yon ti mizajou sit ou chak mwa nan ajanda ou.",
            en: "List five places where you'll add your site's address this week (email signature, social media profile, business card, WhatsApp group, shop window). Post an announcement with the link and ask three people to share it. Finally, schedule a small update to your site every month in your calendar.",
            es: "Haz la lista de cinco lugares donde vas a añadir la dirección de tu sitio esta semana (firma de correo, perfil de red social, tarjeta de visita, grupo de WhatsApp, escaparate). Publica un anuncio con el enlace y pide a tres personas que lo compartan. Por último, programa una pequeña actualización de tu sitio cada mes en tu agenda.",
          },
        },
      ],
    },
  ],
};

export default creationWeb;
