import { CourseContent } from "./types";

const entrepreneuriat: CourseContent = {
  slug: "entrepreneuriat",
  intro: {
    fr: "Apprendre à lancer et faire grandir une activité de façon concrète : trouver une bonne idée, connaître son client, formuler sa valeur, bâtir un plan simple, gérer l'argent, vendre et gagner ses premiers clients — avec intégrité et esprit de service.",
    ht: "Aprann lanse ak fè yon aktivite grandi yon fason konkrè : jwenn yon bon lide, konnen kliyan w, fòmile valè w, bati yon plan senp, jere lajan an, vann epi genyen premye kliyan w yo — ak entegrite ak lespri sèvis.",
    en: "Learn to start and grow a business in a practical way: find a good idea, know your customer, state your value, build a simple plan, manage your money, sell and win your first customers — with integrity and a spirit of service.",
    es: "Aprender a lanzar y hacer crecer un negocio de forma concreta: encontrar una buena idea, conocer a tu cliente, formular tu valor, construir un plan sencillo, manejar el dinero, vender y ganar tus primeros clientes — con integridad y espíritu de servicio.",
  },
  modules: [
    {
      title: { fr: "Trouver et valider son idée", ht: "Jwenn ak valide lide w", en: "Finding and validating your idea", es: "Encontrar y validar tu idea" },
      lessons: [
        {
          slug: "trouver-une-bonne-idee",
          title: { fr: "Trouver une bonne idée de business", ht: "Jwenn yon bon lide biznis", en: "Finding a good business idea", es: "Encontrar una buena idea de negocio" },
          videoId: "",
          content: {
            fr: "Une bonne idée de business ne tombe pas du ciel : elle naît d'un problème réel que des gens veulent résoudre. Regarde autour de toi et demande-toi : « Qu'est-ce qui manque ? Qu'est-ce qui frustre les gens ? Qu'est-ce qu'ils paient déjà pour régler ? » Note tout dans un carnet pendant une semaine, sans filtre.\n\nCroise ensuite deux listes : ce que tu sais faire (tes compétences, ton expérience) et ce dont les gens ont besoin autour de toi. La meilleure idée se trouve souvent à l'intersection des deux. Par exemple, si tu cuisines bien et que beaucoup de collègues n'ont pas le temps de préparer leur déjeuner, il y a peut-être une activité de repas à emporter.\n\nAvant d'investir, teste ton idée à petite échelle. Parle à dix personnes qui pourraient acheter et demande-leur si elles paieraient vraiment. Si trois ou quatre disent « oui, où puis-je acheter ? », tu tiens une piste sérieuse.\n\nMéfie-toi de deux illusions courantes. La première : « personne ne le fait, donc c'est génial. » Parfois, si personne ne le fait, c'est qu'il n'y a pas de demande. La seconde : « tout le monde a déjà un concurrent, c'est mort. » Au contraire, la concurrence prouve qu'il y a un marché ; il te suffira de faire un peu mieux ou différemment. Une bonne idée n'a pas besoin d'être nouvelle, elle a besoin d'être utile et rentable.",
            ht: "Yon bon lide biznis pa tonbe sot nan syèl : li fèt nan yon pwoblèm reyèl moun vle rezoud. Gade otou w epi mande tèt ou : « Kisa ki manke ? Kisa ki fè moun anmède ? Kisa yo deja peye pou rezoud ? » Ekri tout bagay nan yon kaye pandan yon semèn, san filtre.\n\nApre sa, kwaze de lis : sa ou konn fè (konpetans ou, eksperyans ou) ak sa moun bezwen otou w. Pi bon lide a souvan jwenn kote de bagay sa yo kontre. Pa egzanp, si ou kwit manje byen epi anpil kòlèg pa gen tan pou prepare dine yo, gen dwa gen yon aktivite manje pou pote ale.\n\nAnvan ou envesti, teste lide w sou ti echèl. Pale ak dis moun ki ta ka achte epi mande yo si yo t ap peye vre. Si twa oswa kat di « wi, ki kote mwen ka achte ? », ou gen yon bon piste.\n\nFè atansyon ak de ilizyon kouran. Premye a : « pèsonn pa fè l, donk li ekselan. » Pafwa, si pèsonn pa fè l, se paske pa gen demann. Dezyèm nan : « tout moun deja gen yon konkiran, li fini. » Okontrè, konkirans lan pwouve gen yon mache ; ou jis bezwen fè yon ti jan pi byen oswa yon fason diferan. Yon bon lide pa bezwen nouvo, li bezwen itil epi rantab.",
            en: "A good business idea does not fall from the sky: it is born from a real problem people want solved. Look around you and ask: \"What is missing? What frustrates people? What are they already paying to fix?\" Write everything in a notebook for a week, without filtering.\n\nThen cross two lists: what you know how to do (your skills, your experience) and what people around you need. The best idea is often found at the intersection of the two. For example, if you cook well and many coworkers have no time to prepare lunch, there may be a takeaway meal business.\n\nBefore investing, test your idea on a small scale. Talk to ten people who might buy and ask if they would really pay. If three or four say \"yes, where can I buy?\", you have a serious lead.\n\nBeware of two common illusions. The first: \"nobody does it, so it's brilliant.\" Sometimes, if nobody does it, it's because there's no demand. The second: \"everyone already has a competitor, it's hopeless.\" On the contrary, competition proves there's a market; you just need to do it a little better or differently. A good idea doesn't have to be new, it has to be useful and profitable.",
            es: "Una buena idea de negocio no cae del cielo: nace de un problema real que la gente quiere resolver. Mira a tu alrededor y pregúntate: «¿Qué falta? ¿Qué frustra a la gente? ¿Por qué están pagando ya para resolverlo?» Anota todo en un cuaderno durante una semana, sin filtrar.\n\nLuego cruza dos listas: lo que sabes hacer (tus habilidades, tu experiencia) y lo que la gente a tu alrededor necesita. La mejor idea suele estar en la intersección de ambas. Por ejemplo, si cocinas bien y muchos compañeros no tienen tiempo de preparar su almuerzo, quizás haya un negocio de comida para llevar.\n\nAntes de invertir, prueba tu idea a pequeña escala. Habla con diez personas que podrían comprar y pregúntales si realmente pagarían. Si tres o cuatro dicen «sí, ¿dónde puedo comprar?», tienes una pista seria.\n\nDesconfía de dos ilusiones frecuentes. La primera: «nadie lo hace, así que es genial.» A veces, si nadie lo hace, es porque no hay demanda. La segunda: «todos ya tienen un competidor, no hay nada que hacer.» Al contrario, la competencia prueba que hay mercado; solo tendrás que hacerlo un poco mejor o distinto. Una buena idea no tiene que ser nueva, tiene que ser útil y rentable.",
          },
          keyPoints: {
            fr: ["Une bonne idée résout un problème réel que les gens veulent régler", "Cherche l'intersection entre tes compétences et les besoins autour de toi", "Teste avec 10 clients potentiels avant d'investir", "La concurrence prouve qu'il y a un marché : fais un peu mieux"],
            ht: ["Yon bon lide rezoud yon pwoblèm reyèl moun vle regle", "Chèche kote konpetans ou kontre ak bezwen moun otou w", "Teste ak 10 kliyan posib anvan ou envesti", "Konkirans pwouve gen yon mache : fè yon ti jan pi byen"],
            en: ["A good idea solves a real problem people want fixed", "Look for the intersection of your skills and the needs around you", "Test with 10 potential customers before investing", "Competition proves there's a market: do it a little better"],
            es: ["Una buena idea resuelve un problema real que la gente quiere solucionar", "Busca la intersección entre tus habilidades y las necesidades a tu alrededor", "Prueba con 10 clientes potenciales antes de invertir", "La competencia prueba que hay mercado: hazlo un poco mejor"],
          },
          exercise: {
            fr: "Pendant une semaine, note dans un carnet chaque problème ou frustration que tu observes autour de toi. À la fin, dresse deux colonnes : « ce que je sais faire » et « ce dont les gens ont besoin », et entoure les idées qui apparaissent dans les deux. Choisis-en une et parle-en à dix personnes pour savoir si elles paieraient.",
            ht: "Pandan yon semèn, note nan yon kaye chak pwoblèm oswa fristrasyon ou obsève otou w. Nan fen an, fè de kolòn : « sa m konn fè » ak « sa moun bezwen », epi antoure lide ki parèt nan tou de yo. Chwazi youn epi pale de li ak dis moun pou konnen si yo t ap peye.",
            en: "For a week, note in a notebook every problem or frustration you observe around you. At the end, make two columns: \"what I know how to do\" and \"what people need\", and circle the ideas that appear in both. Pick one and talk about it to ten people to find out if they would pay.",
            es: "Durante una semana, anota en un cuaderno cada problema o frustración que observes a tu alrededor. Al final, haz dos columnas: «lo que sé hacer» y «lo que la gente necesita», y rodea las ideas que aparezcan en ambas. Elige una y coméntala con diez personas para saber si pagarían.",
          },
        },
        {
          slug: "connaitre-son-client",
          title: { fr: "Connaître son client", ht: "Konnen kliyan w", en: "Knowing your customer", es: "Conocer a tu cliente" },
          videoId: "",
          content: {
            fr: "Tu ne vends pas « à tout le monde ». Le débutant qui veut plaire à tous ne parle vraiment à personne. Choisis un client précis : quel âge a-t-il, où vit-il, quel est son problème, combien peut-il payer ? Plus tu es précis, plus ton message devient clair et convaincant.\n\nPour vraiment connaître ton client, va lui parler. Pose des questions ouvertes : « Comment fais-tu aujourd'hui pour régler ce problème ? Qu'est-ce qui t'énerve le plus ? » Écoute deux fois plus que tu ne parles. Les mots exacts qu'il emploie deviendront les mots que tu utiliseras dans tes annonces et tes offres.\n\nÉcris ensuite le portrait de ton client idéal sur une feuille et garde-le sous les yeux. Avant chaque décision — un prix, un produit, une publicité — demande-toi : « Est-ce que ça aide vraiment cette personne ? » Servir sincèrement ton client, c'est déjà le meilleur marketing.\n\nApprends aussi à distinguer ce que le client dit de ce qu'il fait vraiment. Beaucoup diront « oui, super idée » pour te faire plaisir, mais ne sortiront jamais leur portefeuille. La seule preuve fiable, c'est l'argent : une précommande, un acompte, une promesse d'achat ferme. Écoute les mots, mais fie-toi surtout aux actes. Un client qui te contacte de lui-même ou revient une deuxième fois vaut mille compliments polis.",
            ht: "Ou pa vann « tout moun ». Debitan ki vle fè tout moun plezi a pa pale ak pèsonn tout bon. Chwazi yon kliyan presi : ki laj li genyen, ki kote li rete, ki pwoblèm li genyen, konbyen li ka peye ? Plis ou presi, plis mesaj ou vin klè e konvenkan.\n\nPou konnen kliyan w tout bon, ale pale avè l. Poze kesyon ouvè : « Ki jan ou fè jodi a pou regle pwoblèm sa a ? Kisa ki anmède w plis ? » Koute de fwa plis pase sa ou pale. Mo egzak li itilize yo ap vin mo ou pral itilize nan reklam ak òf ou yo.\n\nApre sa, ekri pòtre kliyan ideyal ou sou yon fèy epi kenbe l devan je w. Anvan chak desizyon — yon pri, yon pwodwi, yon reklam — mande tèt ou : « Èske sa ede moun sa a vre ? » Sèvi kliyan w ak tout kè w, se deja pi bon maketin ou ka fè.\n\nAprann tou fè diferans ant sa kliyan an di ak sa li reyèlman fè. Anpil moun ap di « wi, bèl lide » pou fè w plezi, men yo p ap janm soti bous yo. Sèl prèv ki fyab, se lajan : yon prekòmand, yon avans, yon pwomès achte fèm. Koute mo yo, men fye w sitou sou aksyon yo. Yon kliyan ki kontakte w poukont li oswa ki retounen yon dezyèm fwa vo mil konpliman poli.",
            en: "You do not sell \"to everyone.\" The beginner who wants to please everyone truly speaks to no one. Choose a specific customer: how old are they, where do they live, what is their problem, how much can they pay? The more specific you are, the clearer and more convincing your message becomes.\n\nTo really know your customer, go and talk to them. Ask open questions: \"How do you handle this problem today? What annoys you most?\" Listen twice as much as you speak. The exact words they use will become the words you use in your ads and offers.\n\nThen write a portrait of your ideal customer on a sheet and keep it in front of you. Before every decision — a price, a product, an ad — ask: \"Does this really help this person?\" Sincerely serving your customer is already the best marketing.\n\nAlso learn to tell what a customer says from what they actually do. Many will say \"yes, great idea\" to please you, but never open their wallet. The only reliable proof is money: a pre-order, a deposit, a firm promise to buy. Listen to the words, but trust the actions most. A customer who contacts you on their own or comes back a second time is worth a thousand polite compliments.",
            es: "No vendes «a todo el mundo». El principiante que quiere agradar a todos en realidad no le habla a nadie. Elige un cliente concreto: qué edad tiene, dónde vive, cuál es su problema, cuánto puede pagar. Cuanto más específico seas, más claro y convincente será tu mensaje.\n\nPara conocer de verdad a tu cliente, ve y habla con él. Haz preguntas abiertas: «¿Cómo resuelves hoy este problema? ¿Qué es lo que más te molesta?» Escucha el doble de lo que hablas. Las palabras exactas que usa serán las palabras que uses en tus anuncios y ofertas.\n\nLuego escribe el retrato de tu cliente ideal en una hoja y mantenlo a la vista. Antes de cada decisión — un precio, un producto, un anuncio — pregúntate: «¿Esto realmente ayuda a esta persona?» Servir con sinceridad a tu cliente ya es el mejor marketing.\n\nAprende también a distinguir lo que el cliente dice de lo que realmente hace. Muchos dirán «sí, gran idea» para complacerte, pero nunca sacarán la billetera. La única prueba fiable es el dinero: un pedido anticipado, un anticipo, una promesa firme de compra. Escucha las palabras, pero fíate sobre todo de los hechos. Un cliente que te contacta por su cuenta o vuelve una segunda vez vale mil cumplidos educados.",
          },
          keyPoints: {
            fr: ["Vise un client précis, pas « tout le monde »", "Parle à tes clients et écoute deux fois plus que tu ne parles", "Reprends leurs mots exacts dans tes offres et annonces", "Fie-toi aux actes (un achat) plus qu'aux compliments polis"],
            ht: ["Vize yon kliyan presi, pa « tout moun »", "Pale ak kliyan w epi koute de fwa plis pase sa ou pale", "Reprann mo egzak yo nan òf ak reklam ou yo", "Fye w sou aksyon (yon acha) plis pase konpliman poli"],
            en: ["Aim at a specific customer, not \"everyone\"", "Talk to your customers and listen twice as much as you speak", "Reuse their exact words in your offers and ads", "Trust actions (a purchase) more than polite compliments"],
            es: ["Apunta a un cliente concreto, no a «todo el mundo»", "Habla con tus clientes y escucha el doble de lo que hablas", "Reutiliza sus palabras exactas en tus ofertas y anuncios", "Fíate de los hechos (una compra) más que de los cumplidos"],
          },
          exercise: {
            fr: "Écris sur une feuille le portrait détaillé de ton client idéal : âge, lieu, problème principal, budget, mots qu'il emploie. Puis va poser trois questions ouvertes à cinq personnes qui lui ressemblent. Note leurs réponses avec leurs mots exacts et repère celui ou celle qui montre un vrai intérêt (prêt à payer, pas juste poli).",
            ht: "Ekri sou yon fèy pòtre detaye kliyan ideyal ou : laj, kote, pwoblèm prensipal, bidjè, mo li itilize. Apre sa, ale poze twa kesyon ouvè bay senk moun ki sanble avè l. Note repons yo ak mo egzak yo epi jwenn kilès ki montre yon vrè enterè (pare pou peye, pa jis poli).",
            en: "Write on a sheet the detailed portrait of your ideal customer: age, place, main problem, budget, words they use. Then go and ask three open questions to five people who resemble them. Note their answers in their exact words and spot the one who shows real interest (ready to pay, not just polite).",
            es: "Escribe en una hoja el retrato detallado de tu cliente ideal: edad, lugar, problema principal, presupuesto, palabras que usa. Luego ve a hacer tres preguntas abiertas a cinco personas que se le parezcan. Anota sus respuestas con sus palabras exactas y detecta a quien muestra un interés real (dispuesto a pagar, no solo educado).",
          },
        },
        {
          slug: "proposition-de-valeur",
          title: { fr: "Formuler sa proposition de valeur", ht: "Fòmile pwopozisyon valè w", en: "Stating your value proposition", es: "Formular tu propuesta de valor" },
          videoId: "",
          content: {
            fr: "La proposition de valeur, c'est la réponse claire à la question que se pose tout client : « Pourquoi t'acheter à toi plutôt qu'à un autre, ou plutôt que de ne rien faire ? » Ce n'est pas la liste de tes produits, c'est le bénéfice concret qu'ils apportent. Les gens n'achètent pas une perceuse, ils achètent un trou dans le mur ; ils n'achètent pas ton pain, ils achètent un bon petit-déjeuner rapide pour leur famille.\n\nUne proposition de valeur solide tient en une phrase simple : « J'aide [tel client] à [obtenir tel résultat] grâce à [ton offre]. » Par exemple : « J'aide les mamans occupées du quartier à nourrir leurs enfants sainement grâce à des plats maison livrés à midi. » Cette phrase te force à être clair sur qui tu sers, ce que tu apportes, et comment.\n\nPour la rendre convaincante, appuie-toi sur ce qui te rend différent : plus rapide, plus proche, plus fiable, plus chaleureux, plus adapté à un besoin précis. Tu n'as pas besoin d'être le meilleur du monde, juste le meilleur choix pour ce client-là, dans ta zone, à cet instant. La différence peut être toute simple : un service souriant, une livraison le dimanche, un produit adapté au goût local.\n\nEnfin, teste ta phrase sur de vraies personnes. Dis-la à voix haute à quelqu'un de ta cible et observe sa réaction. S'il répond « ah oui, ça m'intéresse, comment ça marche ? », tu tiens quelque chose. S'il fronce les sourcils ou dit « je ne comprends pas trop », simplifie encore. Une bonne proposition de valeur se comprend en cinq secondes, sans explication. C'est elle que tu mettras en haut de ta page, sur ta carte et dans ta bouche à chaque rencontre.",
            ht: "Pwopozisyon valè a, se repons klè a kesyon chak kliyan poze : « Poukisa pou m achte nan men w olye yon lòt, oswa olye m pa fè anyen ? » Se pa lis pwodwi w yo, se benefis konkrè yo pote. Moun pa achte yon dril, yo achte yon twou nan mi an ; yo pa achte pen w, yo achte yon bon ti dejene rapid pou fanmi yo.\n\nYon pwopozisyon valè solid kenbe nan yon fraz senp : « Mwen ede [tèl kliyan] pou [jwenn tèl rezilta] gras ak [òf ou]. » Pa egzanp : « Mwen ede manman okipe nan katye a bay pitit yo manje ki sen gras ak plat lakay ki livre a midi. » Fraz sa a fòse w vin klè sou ki moun ou sèvi, sa ou pote, ak kijan.\n\nPou fè l konvenkan, apiye sou sa ki fè w diferan : pi rapid, pi pre, pi fyab, pi cho, pi adapte ak yon bezwen presi. Ou pa bezwen pi bon nan mond lan, jis pi bon chwa pou kliyan sa a, nan zòn ou, nan moman sa a. Diferans lan ka tou senp : yon sèvis souriyan, yon livrezon dimanch, yon pwodwi adapte ak gou lokal la.\n\nAnfen, teste fraz ou sou vrè moun. Di l awotvwa bay yon moun nan sib ou epi obsève reyaksyon l. Si li reponn « a wi, sa enterese m, kijan sa mache ? », ou gen yon bagay. Si li fwonse sousi oswa di « m pa twò konprann », senplifye plis. Yon bon pwopozisyon valè konprann nan senk segonn, san eksplikasyon. Se li ou pral mete anwo paj ou, sou kat ou epi nan bouch ou nan chak rankont.",
            en: "The value proposition is the clear answer to the question every customer asks: \"Why buy from you rather than someone else, or rather than doing nothing?\" It's not the list of your products, it's the concrete benefit they bring. People don't buy a drill, they buy a hole in the wall; they don't buy your bread, they buy a quick, good breakfast for their family.\n\nA strong value proposition fits in a simple sentence: \"I help [this customer] to [get this result] through [your offer].\" For example: \"I help busy mothers in the neighbourhood feed their children healthily through home-cooked meals delivered at noon.\" This sentence forces you to be clear about who you serve, what you bring, and how.\n\nTo make it convincing, lean on what makes you different: faster, closer, more reliable, warmer, better suited to a specific need. You don't need to be the best in the world, just the best choice for that customer, in your area, at that moment. The difference can be very simple: friendly service, Sunday delivery, a product suited to the local taste.\n\nFinally, test your sentence on real people. Say it out loud to someone in your target and watch their reaction. If they answer \"oh yes, that interests me, how does it work?\", you have something. If they frown or say \"I don't quite get it\", simplify further. A good value proposition is understood in five seconds, without explanation. It's the one you'll put at the top of your page, on your card and in your mouth at every meeting.",
            es: "La propuesta de valor es la respuesta clara a la pregunta que se hace todo cliente: «¿Por qué comprarte a ti y no a otro, o en lugar de no hacer nada?» No es la lista de tus productos, es el beneficio concreto que aportan. La gente no compra un taladro, compra un agujero en la pared; no compra tu pan, compra un buen desayuno rápido para su familia.\n\nUna propuesta de valor sólida cabe en una frase simple: «Ayudo a [tal cliente] a [obtener tal resultado] mediante [tu oferta].» Por ejemplo: «Ayudo a las madres ocupadas del barrio a alimentar sanamente a sus hijos mediante platos caseros entregados al mediodía.» Esta frase te obliga a ser claro sobre a quién sirves, qué aportas y cómo.\n\nPara hacerla convincente, apóyate en lo que te hace diferente: más rápido, más cercano, más fiable, más cálido, más adaptado a una necesidad concreta. No necesitas ser el mejor del mundo, solo la mejor opción para ese cliente, en tu zona, en ese momento. La diferencia puede ser muy sencilla: un servicio amable, una entrega el domingo, un producto adaptado al gusto local.\n\nPor último, prueba tu frase con personas reales. Dila en voz alta a alguien de tu público y observa su reacción. Si responde «ah sí, me interesa, ¿cómo funciona?», tienes algo. Si frunce el ceño o dice «no lo entiendo bien», simplifica más. Una buena propuesta de valor se entiende en cinco segundos, sin explicación. Es la que pondrás en lo alto de tu página, en tu tarjeta y en tu boca en cada encuentro.",
          },
          keyPoints: {
            fr: ["La valeur = le bénéfice concret, pas la liste des produits", "Formule : « J'aide [client] à [résultat] grâce à [offre] »", "Différencie-toi : le meilleur choix pour CE client, ici, maintenant", "Une bonne phrase se comprend en 5 secondes, sans explication"],
            ht: ["Valè = benefis konkrè a, pa lis pwodwi yo", "Fòmil : « Mwen ede [kliyan] pou [rezilta] gras ak [òf] »", "Diferansye w : pi bon chwa pou KLIYAN sa a, isit, kounye a", "Yon bon fraz konprann nan 5 segonn, san eksplikasyon"],
            en: ["Value = the concrete benefit, not the product list", "Formula: \"I help [customer] to [result] through [offer]\"", "Differentiate: the best choice for THIS customer, here, now", "A good sentence is understood in 5 seconds, no explanation"],
            es: ["El valor = el beneficio concreto, no la lista de productos", "Fórmula: «Ayudo a [cliente] a [resultado] mediante [oferta]»", "Diferénciate: la mejor opción para ESTE cliente, aquí, ahora", "Una buena frase se entiende en 5 segundos, sin explicación"],
          },
          exercise: {
            fr: "Écris ta proposition de valeur avec la formule : « J'aide [tel client] à [obtenir tel résultat] grâce à [ton offre]. » Réécris-la trois fois pour la rendre plus courte et plus concrète. Puis dis-la à voix haute à trois personnes de ta cible et note leur première réaction : ont-elles compris et été intéressées en cinq secondes ?",
            ht: "Ekri pwopozisyon valè w ak fòmil la : « Mwen ede [tèl kliyan] pou [jwenn tèl rezilta] gras ak [òf ou]. » Reekri l twa fwa pou fè l pi kout epi pi konkrè. Apre sa, di l awotvwa bay twa moun nan sib ou epi note premye reyaksyon yo : èske yo konprann epi enterese nan senk segonn ?",
            en: "Write your value proposition using the formula: \"I help [this customer] to [get this result] through [your offer].\" Rewrite it three times to make it shorter and more concrete. Then say it out loud to three people in your target and note their first reaction: did they understand and get interested within five seconds?",
            es: "Escribe tu propuesta de valor con la fórmula: «Ayudo a [tal cliente] a [obtener tal resultado] mediante [tu oferta].» Reescríbela tres veces para hacerla más corta y concreta. Luego dila en voz alta a tres personas de tu público y anota su primera reacción: ¿entendieron y se interesaron en cinco segundos?",
          },
        },
      ],
    },
    {
      title: { fr: "Bâtir un plan simple", ht: "Bati yon plan senp", en: "Building a simple plan", es: "Construir un plan sencillo" },
      lessons: [
        {
          slug: "plan-simple-une-page",
          title: { fr: "Un plan d'affaires sur une page", ht: "Yon plan biznis sou yon paj", en: "A one-page business plan", es: "Un plan de negocio en una página" },
          videoId: "",
          content: {
            fr: "Tu n'as pas besoin d'un document de cinquante pages pour démarrer. Un bon plan tient sur une seule page et répond à six questions : Que vends-tu ? À qui ? Quel problème résous-tu ? Combien ça coûte à produire ? À quel prix vends-tu ? Comment les clients vont-ils te trouver ? Si tu peux répondre clairement, tu es prêt à commencer.\n\nFixe-toi un objectif concret et mesurable pour les 90 premiers jours. Par exemple : « obtenir 10 clients payants » ou « vendre 100 unités ». Un objectif flou comme « réussir » ne guide aucune action. Un objectif chiffré te dit chaque matin ce que tu dois faire.\n\nGarde ce plan vivant : il n'est pas gravé dans la pierre. Chaque mois, relis-le et ajuste ce qui ne marche pas. Le but n'est pas d'avoir un plan parfait, mais d'avoir une direction claire et d'avancer un pas à la fois.\n\nUne fois le grand objectif fixé, découpe-le en petites actions de la semaine. « 10 clients en 90 jours » devient : cette semaine, contacter 15 personnes, préparer un échantillon, publier une annonce. Un grand rêve fait peur et paralyse ; une petite action se fait tout de suite. Chaque dimanche soir, écris les trois actions concrètes de la semaine à venir. C'est cette discipline modeste, répétée, qui transforme un plan sur papier en une vraie entreprise.",
            ht: "Ou pa bezwen yon dokiman senkant paj pou kòmanse. Yon bon plan kenbe sou yon sèl paj epi li reponn sis kesyon : Kisa w ap vann ? Pou ki moun ? Ki pwoblèm w ap rezoud ? Konbyen li koute pou pwodwi l ? A ki pri w ap vann ? Kijan kliyan yo pral jwenn ou ? Si ou ka reponn klè, ou pare pou kòmanse.\n\nFikse yon objektif konkrè e ki ka mezire pou 90 premye jou yo. Pa egzanp : « jwenn 10 kliyan k ap peye » oswa « vann 100 inite ». Yon objektif ki pa klè tankou « reyisi » pa gide okenn aksyon. Yon objektif ak chif di w chak maten sa ou dwe fè.\n\nKenbe plan sa a vivan : li pa grave nan wòch. Chak mwa, reli l epi ajiste sa ki pa mache. Objektif la se pa gen yon plan pafè, men gen yon direksyon klè epi avanse yon pa alafwa.\n\nYon fwa gwo objektif la fikse, koupe l an ti aksyon pou semèn nan. « 10 kliyan nan 90 jou » vin : semèn sa a, kontakte 15 moun, prepare yon echantiyon, pibliye yon anons. Yon gwo rèv fè pè epi paralize ; yon ti aksyon fèt touswit. Chak dimanch swa, ekri twa aksyon konkrè pou semèn k ap vini an. Se disiplin modès sa a, ki repete, ki transfòme yon plan sou papye an yon vrè antrepriz.",
            en: "You do not need a fifty-page document to start. A good plan fits on a single page and answers six questions: What do you sell? To whom? What problem do you solve? How much does it cost to produce? At what price do you sell? How will customers find you? If you can answer clearly, you are ready to begin.\n\nSet a concrete, measurable goal for the first 90 days. For example: \"get 10 paying customers\" or \"sell 100 units.\" A vague goal like \"succeed\" guides no action. A number tells you every morning what you must do.\n\nKeep this plan alive: it is not carved in stone. Every month, reread it and adjust what is not working. The goal is not to have a perfect plan, but to have a clear direction and move one step at a time.\n\nOnce the big goal is set, break it into small weekly actions. \"10 customers in 90 days\" becomes: this week, contact 15 people, prepare a sample, post an ad. A big dream is scary and paralyzing; a small action gets done right away. Every Sunday evening, write the three concrete actions for the coming week. It's this modest, repeated discipline that turns a plan on paper into a real business.",
            es: "No necesitas un documento de cincuenta páginas para empezar. Un buen plan cabe en una sola página y responde a seis preguntas: ¿Qué vendes? ¿A quién? ¿Qué problema resuelves? ¿Cuánto cuesta producirlo? ¿A qué precio vendes? ¿Cómo te encontrarán los clientes? Si puedes responder con claridad, estás listo para empezar.\n\nFíjate una meta concreta y medible para los primeros 90 días. Por ejemplo: «conseguir 10 clientes que paguen» o «vender 100 unidades». Una meta vaga como «tener éxito» no guía ninguna acción. Una cifra te dice cada mañana lo que debes hacer.\n\nMantén este plan vivo: no está grabado en piedra. Cada mes, reléelo y ajusta lo que no funciona. El objetivo no es tener un plan perfecto, sino tener una dirección clara y avanzar paso a paso.\n\nUna vez fijada la gran meta, divídela en pequeñas acciones de la semana. «10 clientes en 90 días» se convierte en: esta semana, contactar a 15 personas, preparar una muestra, publicar un anuncio. Un gran sueño asusta y paraliza; una pequeña acción se hace enseguida. Cada domingo por la noche, escribe las tres acciones concretas de la semana siguiente. Es esta disciplina modesta y repetida la que convierte un plan en papel en un negocio real.",
          },
          keyPoints: {
            fr: ["Un plan tient sur une page et répond à 6 questions clés", "Fixe un objectif chiffré pour les 90 premiers jours", "Relis et ajuste ton plan chaque mois", "Découpe le grand objectif en 3 actions concrètes par semaine"],
            ht: ["Yon plan kenbe sou yon paj epi reponn 6 kesyon kle", "Fikse yon objektif ak chif pou 90 premye jou yo", "Reli epi ajiste plan w chak mwa", "Koupe gwo objektif la an 3 aksyon konkrè pa semèn"],
            en: ["A plan fits on one page and answers 6 key questions", "Set a numeric goal for the first 90 days", "Reread and adjust your plan every month", "Break the big goal into 3 concrete actions per week"],
            es: ["Un plan cabe en una página y responde 6 preguntas clave", "Fija una meta numérica para los primeros 90 días", "Relee y ajusta tu plan cada mes", "Divide la gran meta en 3 acciones concretas por semana"],
          },
          exercise: {
            fr: "Sur une seule page, réponds aux six questions du plan (quoi, à qui, quel problème, coût, prix, comment te trouver). Fixe un objectif chiffré à 90 jours. Puis écris les trois actions concrètes que tu feras cette semaine pour t'en rapprocher, et coche-les au fur et à mesure.",
            ht: "Sou yon sèl paj, reponn sis kesyon plan an (kisa, pou ki moun, ki pwoblèm, kou, pri, kijan pou jwenn ou). Fikse yon objektif ak chif pou 90 jou. Apre sa, ekri twa aksyon konkrè ou pral fè semèn sa a pou pwoche de li, epi make yo piti piti.",
            en: "On a single page, answer the plan's six questions (what, to whom, what problem, cost, price, how to find you). Set a numeric 90-day goal. Then write the three concrete actions you'll do this week to get closer to it, and tick them off as you go.",
            es: "En una sola página, responde a las seis preguntas del plan (qué, a quién, qué problema, costo, precio, cómo encontrarte). Fija una meta numérica a 90 días. Luego escribe las tres acciones concretas que harás esta semana para acercarte, y márcalas a medida que avances.",
          },
        },
        {
          slug: "commencer-petit-tester",
          title: { fr: "Commencer petit et tester", ht: "Kòmanse piti epi teste", en: "Start small and test", es: "Empezar pequeño y probar" },
          videoId: "",
          content: {
            fr: "Beaucoup rêvent d'un grand lancement et ne démarrent jamais. La sagesse dit de commencer petit avec ce que tu as déjà en main. Vends d'abord un produit simple, à quelques personnes, et apprends de leurs réactions. On appelle ça un « produit minimum » : la plus petite version qui rend déjà service.\n\nCette approche protège ton argent et ton moral. Au lieu d'investir toutes tes économies dans un stock énorme, fais un petit lot, vends-le, écoute les retours, puis améliore. Une entreprise se construit par cycles : essayer, mesurer, corriger, recommencer. Chaque cycle te rend plus fort et plus précis.\n\nNe crains pas les premières imperfections. Un client satisfait d'un produit simple mais honnête vaut mieux que cent clients imaginaires d'un produit parfait qui n'existe pas encore. Livre, apprends, et grandis pas à pas.\n\nDéfinis à l'avance ce que tu veux apprendre de chaque test. Ne te contente pas de « voir si ça marche » : pose une question précise. « Les gens préfèrent-ils le format à 100 gourdes ou à 150 ? » « Achètent-ils plus le matin ou le soir ? » Ainsi, même une petite vente t'apporte une réponse utile. Un entrepreneur malin ne cherche pas seulement à vendre, il cherche à apprendre vite et à moindre coût, pour ensuite investir dans ce qui fonctionne vraiment.",
            ht: "Anpil moun reve yon gwo lansman epi yo pa janm kòmanse. Sajès la di pou kòmanse piti ak sa ou deja genyen nan men w. Vann yon pwodwi senp anvan, ak kèk moun, epi aprann nan reyaksyon yo. Yo rele sa yon « pwodwi minimòm » : pi ti vèsyon an ki deja rann sèvis.\n\nApwòch sa a pwoteje lajan w ak moral ou. Olye pou ou envesti tout ekonomi w nan yon gwo stòk, fè yon ti kantite, vann li, koute repons yo, epi amelyore. Yon antrepriz bati pa sik : eseye, mezire, korije, rekòmanse. Chak sik fè w vin pi fò e pi presi.\n\nPa pè premye enpèfeksyon yo. Yon kliyan ki satisfè ak yon pwodwi senp men onèt vo plis pase san kliyan imajinè pou yon pwodwi pafè ki poko egziste. Livre, aprann, epi grandi pa apa.\n\nDefini davans sa ou vle aprann nan chak tès. Pa kontante w ak « wè si sa mache » : poze yon kesyon presi. « Èske moun pito fòma 100 goud oswa 150 ? » « Èske yo achte plis nan maten oswa nan aswè ? » Konsa, menm yon ti vant pote yon repons itil pou ou. Yon antreprenè entelijan pa chèche sèlman vann, li chèche aprann vit epi a mwen frè, pou apre envesti nan sa ki reyèlman mache.",
            en: "Many dream of a big launch and never start. Wisdom says to begin small with what you already have in hand. First sell a simple product to a few people, and learn from their reactions. This is called a \"minimum product\": the smallest version that already serves someone.\n\nThis approach protects your money and your morale. Instead of investing all your savings in a huge stock, make a small batch, sell it, listen to feedback, then improve. A business is built in cycles: try, measure, correct, start again. Each cycle makes you stronger and more precise.\n\nDo not fear the first imperfections. One satisfied customer of a simple but honest product is worth more than a hundred imaginary customers of a perfect product that does not yet exist. Deliver, learn, and grow step by step.\n\nDefine in advance what you want to learn from each test. Don't just \"see if it works\": ask a precise question. \"Do people prefer the 100-gourde size or the 150 one?\" \"Do they buy more in the morning or the evening?\" That way, even a small sale gives you a useful answer. A smart entrepreneur doesn't only try to sell, they try to learn fast and cheaply, then invest in what really works.",
            es: "Muchos sueñan con un gran lanzamiento y nunca empiezan. La sabiduría dice empezar pequeño con lo que ya tienes en la mano. Vende primero un producto sencillo, a unas pocas personas, y aprende de sus reacciones. A esto se le llama «producto mínimo»: la versión más pequeña que ya presta un servicio.\n\nEste enfoque protege tu dinero y tu ánimo. En lugar de invertir todos tus ahorros en un stock enorme, haz un lote pequeño, véndelo, escucha los comentarios y luego mejora. Un negocio se construye por ciclos: probar, medir, corregir, volver a empezar. Cada ciclo te hace más fuerte y más preciso.\n\nNo temas las primeras imperfecciones. Un cliente satisfecho con un producto sencillo pero honesto vale más que cien clientes imaginarios de un producto perfecto que aún no existe. Entrega, aprende y crece paso a paso.\n\nDefine de antemano qué quieres aprender de cada prueba. No te limites a «ver si funciona»: haz una pregunta precisa. «¿La gente prefiere el tamaño de 100 gourdes o el de 150?» «¿Compran más por la mañana o por la tarde?» Así, incluso una pequeña venta te da una respuesta útil. Un emprendedor astuto no solo busca vender, busca aprender rápido y barato, para luego invertir en lo que de verdad funciona.",
          },
          keyPoints: {
            fr: ["Commence avec un « produit minimum » qui rend déjà service", "Avance par cycles : essayer, mesurer, corriger, recommencer", "Un vrai client vaut mieux que cent clients imaginaires", "Fixe à l'avance la question précise que chaque test doit trancher"],
            ht: ["Kòmanse ak yon « pwodwi minimòm » ki deja rann sèvis", "Avanse pa sik : eseye, mezire, korije, rekòmanse", "Yon vrè kliyan vo plis pase san kliyan imajinè", "Fikse davans kesyon presi chak tès dwe reponn"],
            en: ["Start with a \"minimum product\" that already serves someone", "Move in cycles: try, measure, correct, start again", "One real customer beats a hundred imaginary ones", "Set in advance the precise question each test must answer"],
            es: ["Empieza con un «producto mínimo» que ya presta un servicio", "Avanza por ciclos: probar, medir, corregir, volver a empezar", "Un cliente real vale más que cien imaginarios", "Fija de antemano la pregunta precisa que cada prueba debe resolver"],
          },
          exercise: {
            fr: "Définis la plus petite version vendable de ton produit ou service (ton « produit minimum »). Écris une question précise à laquelle ton premier test doit répondre. Puis vends-le réellement à trois personnes cette semaine, note leurs réactions, et décide d'une amélioration concrète pour le lot suivant.",
            ht: "Defini pi ti vèsyon ou ka vann nan pwodwi oswa sèvis ou (« pwodwi minimòm » ou). Ekri yon kesyon presi premye tès ou dwe reponn. Apre sa, vann li reyèlman bay twa moun semèn sa a, note reyaksyon yo, epi deside yon amelyorasyon konkrè pou pwochen lo a.",
            en: "Define the smallest sellable version of your product or service (your \"minimum product\"). Write a precise question your first test must answer. Then actually sell it to three people this week, note their reactions, and decide on one concrete improvement for the next batch.",
            es: "Define la versión vendible más pequeña de tu producto o servicio (tu «producto mínimo»). Escribe una pregunta precisa que tu primera prueba deba responder. Luego véndelo de verdad a tres personas esta semana, anota sus reacciones y decide una mejora concreta para el siguiente lote.",
          },
        },
        {
          slug: "se-differencier-concurrence",
          title: { fr: "Regarder la concurrence et se différencier", ht: "Gade konkirans lan epi diferansye w", en: "Studying competitors and standing out", es: "Observar la competencia y diferenciarte" },
          videoId: "",
          content: {
            fr: "Beaucoup de débutants ont peur de la concurrence. En réalité, elle est une bonne nouvelle : si d'autres vendent déjà quelque chose de proche, c'est qu'il existe des clients qui paient pour ça. Ton travail n'est pas d'éviter la concurrence, mais de bien la comprendre pour trouver ta place à côté d'elle.\n\nCommence par observer. Va voir cinq personnes ou commerces qui proposent quelque chose de semblable, en vrai ou en ligne. Note leurs prix, leur qualité, ce que disent leurs clients, ce qu'ils font bien et ce qui manque. Les avis négatifs de tes concurrents sont une mine d'or : chaque plainte (« trop lent », « pas aimable », « toujours en rupture ») est une porte d'entrée pour toi.\n\nEnsuite, choisis un point sur lequel tu vas être clairement meilleur ou différent. Tu n'as pas besoin d'être meilleur partout, juste remarquable sur une chose qui compte pour ton client : la rapidité, la fraîcheur, l'accueil, le prix, la proximité, un détail que les autres négligent. Mieux vaut être le premier choix d'un petit groupe que le choix moyen de tout le monde.\n\nEnfin, évite deux erreurs. La première : copier bêtement un concurrent, ce qui te condamne à te battre uniquement sur le prix — une guerre où tout le monde perd. La seconde : dénigrer les autres pour te grandir ; cela abîme ta réputation et n'attire personne. Concentre-toi sur ce que tu fais bien, dis-le simplement, et laisse ta qualité parler. Se différencier, ce n'est pas être contre les autres, c'est être clairement toi-même.",
            ht: "Anpil debitan pè konkirans lan. An reyalite, li se yon bòn nouvèl : si lòt moun deja vann yon bagay ki pre, sa vle di gen kliyan ki peye pou sa. Travay ou se pa evite konkirans lan, men byen konprann li pou jwenn plas ou akote l.\n\nKòmanse ak obsèvasyon. Ale wè senk moun oswa komès ki pwopoze yon bagay ki sanble, an reyèl oswa an liy. Note pri yo, kalite yo, sa kliyan yo di, sa yo fè byen ak sa ki manke. Move avi konkiran ou yo se yon min lò : chak plent (« twò lan », « pa emab », « toujou an ripti ») se yon pòt antre pou ou.\n\nApre sa, chwazi yon pwen kote ou pral klèman pi bon oswa diferan. Ou pa bezwen pi bon toupatou, jis remakab sou yon bagay ki konte pou kliyan ou : rapidite, frechè, akèy, pri, pwoksimite, yon detay lòt yo neglije. Li pi bon pou w premye chwa yon ti gwoup pase chwa mwayen tout moun.\n\nAnfen, evite de erè. Premye a : kopye yon konkiran san reflechi, sa ki kondane w pou batay sèlman sou pri — yon lagè kote tout moun pèdi. Dezyèm nan : rabese lòt yo pou grandi tèt ou ; sa gate repitasyon w epi li pa atire pèsonn. Konsantre w sou sa ou fè byen, di l senpleman, epi kite kalite w pale. Diferansye w, se pa kont lòt yo, se klèman se tèt ou.",
            en: "Many beginners fear competition. In reality, it's good news: if others already sell something similar, it means there are customers who pay for it. Your job isn't to avoid competition, but to understand it well so you can find your place beside it.\n\nStart by observing. Go and look at five people or businesses offering something similar, in person or online. Note their prices, their quality, what their customers say, what they do well and what's missing. Your competitors' negative reviews are a gold mine: every complaint (\"too slow\", \"unfriendly\", \"always out of stock\") is a door in for you.\n\nThen choose one point where you'll be clearly better or different. You don't need to be better everywhere, just remarkable on one thing that matters to your customer: speed, freshness, welcome, price, closeness, a detail others neglect. It's better to be the first choice of a small group than the average choice of everyone.\n\nFinally, avoid two mistakes. The first: blindly copying a competitor, which dooms you to compete only on price — a war where everyone loses. The second: putting others down to lift yourself up; it damages your reputation and attracts no one. Focus on what you do well, say it simply, and let your quality speak. Standing out isn't being against others, it's being clearly yourself.",
            es: "Muchos principiantes temen a la competencia. En realidad, es una buena noticia: si otros ya venden algo parecido, significa que hay clientes que pagan por ello. Tu trabajo no es evitar la competencia, sino entenderla bien para encontrar tu lugar a su lado.\n\nEmpieza por observar. Ve a ver a cinco personas o negocios que ofrezcan algo similar, en persona o en línea. Anota sus precios, su calidad, lo que dicen sus clientes, lo que hacen bien y lo que falta. Las reseñas negativas de tus competidores son una mina de oro: cada queja («muy lento», «poco amable», «siempre agotado») es una puerta de entrada para ti.\n\nLuego elige un punto en el que serás claramente mejor o diferente. No necesitas ser mejor en todo, solo destacable en una cosa que importe a tu cliente: la rapidez, la frescura, la atención, el precio, la cercanía, un detalle que los demás descuidan. Es mejor ser la primera opción de un grupo pequeño que la opción media de todos.\n\nPor último, evita dos errores. El primero: copiar sin más a un competidor, lo que te condena a competir solo por precio — una guerra donde todos pierden. El segundo: menospreciar a los demás para engrandecerte; daña tu reputación y no atrae a nadie. Concéntrate en lo que haces bien, dilo con sencillez y deja que tu calidad hable. Diferenciarte no es estar contra los demás, es ser claramente tú mismo.",
          },
          keyPoints: {
            fr: ["La concurrence prouve qu'un marché existe : étudie-la, ne la crains pas", "Les avis négatifs des concurrents montrent où tu peux briller", "Sois remarquable sur UNE chose qui compte pour ton client", "Ne copie pas et ne dénigre pas : laisse ta qualité parler"],
            ht: ["Konkirans pwouve yon mache egziste : etidye l, pa pè l", "Move avi konkiran yo montre kote ou ka klere", "Vin remakab sou YON bagay ki konte pou kliyan ou", "Pa kopye epi pa rabese : kite kalite w pale"],
            en: ["Competition proves a market exists: study it, don't fear it", "Competitors' negative reviews show where you can shine", "Be remarkable on ONE thing that matters to your customer", "Don't copy or belittle: let your quality speak"],
            es: ["La competencia prueba que existe un mercado: estúdiala, no la temas", "Las reseñas negativas de los competidores muestran dónde puedes brillar", "Sé destacable en UNA cosa que le importe a tu cliente", "No copies ni menosprecies: deja que tu calidad hable"],
          },
          exercise: {
            fr: "Étudie cinq concurrents (en vrai ou en ligne). Pour chacun, note le prix, un point fort et un point faible, en t'aidant des avis de leurs clients. Puis écris en une phrase le point précis sur lequel tu seras clairement meilleur ou différent, et vérifie que ce point compte vraiment pour ton client idéal.",
            ht: "Etidye senk konkiran (an reyèl oswa an liy). Pou chak, note pri a, yon pwen fò ak yon pwen fèb, ak èd avi kliyan yo. Apre sa, ekri nan yon fraz pwen presi kote ou pral klèman pi bon oswa diferan, epi verifye pwen sa a konte vrèman pou kliyan ideyal ou.",
            en: "Study five competitors (in person or online). For each, note the price, one strength and one weakness, using their customers' reviews to help. Then write in one sentence the precise point on which you'll be clearly better or different, and check that this point really matters to your ideal customer.",
            es: "Estudia cinco competidores (en persona o en línea). Para cada uno, anota el precio, un punto fuerte y uno débil, ayudándote de las reseñas de sus clientes. Luego escribe en una frase el punto preciso en el que serás claramente mejor o diferente, y comprueba que ese punto le importe de verdad a tu cliente ideal.",
          },
        },
      ],
    },
    {
      title: { fr: "Gérer l'argent et grandir", ht: "Jere lajan epi grandi", en: "Managing money and growing", es: "Manejar el dinero y crecer" },
      lessons: [
        {
          slug: "fixer-son-prix",
          title: { fr: "Fixer son prix et calculer sa marge", ht: "Fikse pri w epi kalkile maj ou", en: "Setting your price and margin", es: "Fijar tu precio y calcular tu margen" },
          videoId: "",
          content: {
            fr: "Beaucoup de débutants fixent un prix « au feeling » et se retrouvent à travailler à perte. La règle de base est simple : ton prix de vente doit couvrir le coût de production, tes frais (transport, emballage, temps) et te laisser un bénéfice. Marge = prix de vente − coût total. Si la marge est nulle ou négative, tu perds de l'argent à chaque vente.\n\nCalcule d'abord ton coût réel, sans rien oublier : matières, transport, frais de communication, et surtout ton temps. Ton temps a une valeur. Ensuite, ajoute une marge raisonnable. Ne t'excuse pas de vouloir gagner ta vie : un prix juste te permet de continuer à servir tes clients demain.\n\nÉvite le piège du prix trop bas pour « attirer tout le monde ». Un prix trop bas fait douter de la qualité et t'épuise. Il vaut mieux vendre à un juste prix à des clients qui valorisent ton travail que brader ton produit et t'user pour rien.\n\nUne astuce concrète : calcule ton « seuil de rentabilité », c'est-à-dire le nombre de ventes qui couvre tes frais fixes du mois (loyer, abonnements, etc.). Tant que tu n'as pas atteint ce nombre, tu ne gagnes rien ; au-delà, chaque vente devient du bénéfice. Connaître ce chiffre change tout : tu sais exactement combien vendre pour ne plus être dans le rouge, et tu arrêtes de deviner. Pense aussi à prévoir de petites remises réfléchies (par quantité, par fidélité) plutôt que de baisser ton prix de base en panique.",
            ht: "Anpil debitan fikse yon pri « nan santiman » epi yo twouve yo ap travay apèt. Règ de baz la senp : pri vant ou dwe kouvri kou pwodiksyon an, depans ou yo (transpò, anbalaj, tan) epi kite yon benefis pou ou. Maj = pri vant − kou total. Si maj la zewo oswa negatif, ou pèdi lajan nan chak vant.\n\nKalkile kou reyèl ou anvan, san bliye anyen : materyèl, transpò, frè kominikasyon, e sitou tan ou. Tan ou gen yon valè. Apre sa, ajoute yon maj rezonab. Pa eskize w paske ou vle genyen lavi w : yon pri jis pèmèt ou kontinye sèvi kliyan w demen.\n\nEvite pyèj pri twò ba pou « atire tout moun ». Yon pri twò ba fè moun doute kalite a epi li fatige w. Li pi bon pou vann a yon pri jis ak kliyan ki valorize travay ou pase brade pwodwi w epi izé tèt ou pou anyen.\n\nYon astis konkrè : kalkile « sèy rantabilite » ou, sètadi kantite vant ki kouvri frè fiks mwa a (lwaye, abònman, elatriye). Toutotan ou poko rive sou kantite sa a, ou pa genyen anyen ; pi lwen pase l, chak vant vin benefis. Konnen chif sa a chanje tout bagay : ou konnen egzakteman konbyen pou vann pou ou pa nan wouj ankò, epi ou sispann devine. Panse tou pou prevwa ti rabè byen reflechi (pa kantite, pa fidelite) olye pou ou bese pri baz ou nan panik.",
            en: "Many beginners set a price \"by feeling\" and end up working at a loss. The basic rule is simple: your selling price must cover the cost of production, your expenses (transport, packaging, time) and leave you a profit. Margin = selling price − total cost. If the margin is zero or negative, you lose money on every sale.\n\nFirst calculate your real cost, forgetting nothing: materials, transport, communication costs, and above all your time. Your time has value. Then add a reasonable margin. Do not apologize for wanting to earn a living: a fair price lets you keep serving your customers tomorrow.\n\nAvoid the trap of pricing too low to \"attract everyone.\" A price that is too low makes people doubt the quality and wears you out. It is better to sell at a fair price to customers who value your work than to give your product away and exhaust yourself for nothing.\n\nA concrete tip: calculate your \"break-even point\", that is, the number of sales that covers your fixed monthly costs (rent, subscriptions, etc.). Until you reach that number, you earn nothing; beyond it, every sale becomes profit. Knowing this figure changes everything: you know exactly how much to sell to stop being in the red, and you stop guessing. Also plan small, thoughtful discounts (by quantity, by loyalty) rather than dropping your base price in a panic.",
            es: "Muchos principiantes fijan un precio «a ojo» y terminan trabajando a pérdida. La regla básica es sencilla: tu precio de venta debe cubrir el costo de producción, tus gastos (transporte, empaque, tiempo) y dejarte una ganancia. Margen = precio de venta − costo total. Si el margen es cero o negativo, pierdes dinero en cada venta.\n\nCalcula primero tu costo real, sin olvidar nada: materiales, transporte, gastos de comunicación y, sobre todo, tu tiempo. Tu tiempo tiene valor. Luego añade un margen razonable. No te disculpes por querer ganarte la vida: un precio justo te permite seguir sirviendo a tus clientes mañana.\n\nEvita la trampa del precio demasiado bajo para «atraer a todos». Un precio demasiado bajo hace dudar de la calidad y te agota. Es mejor vender a un precio justo a clientes que valoran tu trabajo que malbaratar tu producto y desgastarte para nada.\n\nUn truco concreto: calcula tu «punto de equilibrio», es decir, el número de ventas que cubre tus gastos fijos del mes (alquiler, suscripciones, etc.). Hasta que no alcances ese número, no ganas nada; a partir de ahí, cada venta se vuelve ganancia. Conocer esa cifra lo cambia todo: sabes exactamente cuánto vender para dejar de estar en números rojos, y dejas de adivinar. Prevé también pequeños descuentos pensados (por cantidad, por fidelidad) en lugar de bajar tu precio base por pánico.",
          },
          keyPoints: {
            fr: ["Marge = prix de vente − coût total (matières, frais, ton temps)", "Compte ton temps comme un vrai coût", "Un prix trop bas fait douter de la qualité et t'épuise", "Calcule ton seuil de rentabilité : le nombre de ventes qui couvre tes frais"],
            ht: ["Maj = pri vant − kou total (materyèl, frè, tan ou)", "Konte tan ou kòm yon vrè kou", "Yon pri twò ba fè moun doute kalite epi li fatige w", "Kalkile sèy rantabilite w : kantite vant ki kouvri frè w"],
            en: ["Margin = selling price − total cost (materials, expenses, your time)", "Count your time as a real cost", "Too low a price makes people doubt quality and wears you out", "Calculate your break-even: the number of sales that covers your costs"],
            es: ["Margen = precio de venta − costo total (materiales, gastos, tu tiempo)", "Cuenta tu tiempo como un costo real", "Un precio demasiado bajo hace dudar de la calidad y te agota", "Calcula tu punto de equilibrio: las ventas que cubren tus gastos"],
          },
          exercise: {
            fr: "Prends un de tes produits et liste tous ses coûts, y compris une valeur pour ton temps. Fixe un prix de vente et calcule ta marge (prix − coût total). Puis additionne tes frais fixes du mois et divise-les par ta marge unitaire : tu obtiens le nombre de ventes nécessaire pour couvrir tes charges, ton seuil de rentabilité.",
            ht: "Pran youn nan pwodwi w yo epi liste tout kou li yo, ki gen ladan yon valè pou tan ou. Fikse yon pri vant epi kalkile maj ou (pri − kou total). Apre sa, adisyone frè fiks mwa a epi divize yo pa maj initè ou : ou jwenn kantite vant ki nesesè pou kouvri chaj ou yo, sèy rantabilite w.",
            en: "Take one of your products and list all its costs, including a value for your time. Set a selling price and calculate your margin (price − total cost). Then add up your fixed monthly costs and divide them by your per-unit margin: you get the number of sales needed to cover your costs, your break-even point.",
            es: "Toma uno de tus productos y enumera todos sus costos, incluyendo un valor para tu tiempo. Fija un precio de venta y calcula tu margen (precio − costo total). Luego suma tus gastos fijos del mes y divídelos entre tu margen unitario: obtienes el número de ventas necesario para cubrir tus gastos, tu punto de equilibrio.",
          },
        },
        {
          slug: "separer-argent-suivre",
          title: { fr: "Séparer l'argent et suivre ses comptes", ht: "Separe lajan epi swiv kont ou", en: "Separate the money and track your accounts", es: "Separar el dinero y llevar tus cuentas" },
          videoId: "",
          content: {
            fr: "La première erreur qui tue les petites entreprises, c'est de mélanger l'argent du business et l'argent personnel. Ouvre un compte ou garde une caisse séparée pour l'activité. Quand tout est mélangé, tu crois avoir de l'argent alors que ce sont les fonds de tes fournisseurs ou de tes clients.\n\nSuis tes comptes chaque semaine, même avec un simple cahier ou un tableur : ce qui rentre, ce qui sort, ce qui reste. Note chaque dépense, même petite. À la fin du mois, tu verras clairement si tu gagnes réellement de l'argent, où il fuit, et ce que tu peux ajuster. Ce que tu ne mesures pas, tu ne peux pas l'améliorer.\n\nEnfin, paie-toi un salaire, même modeste, et remets une partie des bénéfices dans l'entreprise pour la faire grandir. La discipline financière est une forme d'intégrité : elle te permet d'honorer tes engagements, de payer tes fournisseurs à temps et de bâtir une réputation solide.\n\nMets aussi de côté deux réserves dès que possible. La première : un petit coussin de sécurité pour les imprévus (une panne, un client qui tarde à payer, un mois creux) afin de ne pas t'écrouler à la première difficulté. La seconde : la part qui revient aux impôts ou taxes si ton activité est déclarée, pour ne pas être pris au dépourvu. Un entrepreneur prudent ne dépense jamais tout ce qui entre ; il pense toujours au mois suivant et à la saison difficile qui peut venir.",
            ht: "Premye erè ki touye ti antrepriz yo, se melanje lajan biznis la ak lajan pèsonèl. Ouvri yon kont oswa kenbe yon kès separe pou aktivite a. Lè tout bagay melanje, ou kwè ou gen lajan pandan se lajan founisè w oswa kliyan w yo.\n\nSwiv kont ou chak semèn, menm ak yon senp kaye oswa yon tablo : sa ki antre, sa ki soti, sa ki rete. Note chak depans, menm ti sa yo. Nan fen mwa a, w ap wè klè si ou reyèlman ap fè lajan, kote li ap fwit, epi sa ou ka ajiste. Sa ou pa mezire, ou pa ka amelyore l.\n\nAnfen, peye tèt ou yon salè, menm yon ti kras, epi remèt yon pati nan benefis yo nan antrepriz la pou fè l grandi. Disiplin finansye se yon fòm entegrite : li pèmèt ou onore angajman w, peye founisè w alè epi bati yon bon repitasyon.\n\nMete de rezèv sou kote depi ou kapab. Premye a : yon ti kousen sekirite pou sa ki pa prevwa (yon pàn, yon kliyan ki pran tan pou peye, yon mwa fèb) pou ou pa tonbe nan premye difikilte. Dezyèm nan : pati ki tounen pou taks si aktivite w deklare, pou ou pa pran o depoubwa. Yon antreprenè pridan pa janm depanse tout sa ki antre ; li toujou panse ak mwa k ap vini an ak sezon difisil ki ka rive.",
            en: "The first mistake that kills small businesses is mixing business money with personal money. Open an account or keep a separate cash box for the business. When everything is mixed, you think you have money when it actually belongs to your suppliers or customers.\n\nTrack your accounts every week, even with a simple notebook or spreadsheet: what comes in, what goes out, what is left. Record every expense, even small ones. At the end of the month you will see clearly whether you really earn money, where it leaks, and what you can adjust. What you do not measure, you cannot improve.\n\nFinally, pay yourself a salary, even a modest one, and put part of the profit back into the business to grow it. Financial discipline is a form of integrity: it lets you honor your commitments, pay your suppliers on time and build a solid reputation.\n\nAlso set aside two reserves as soon as you can. The first: a small safety cushion for the unexpected (a breakdown, a customer slow to pay, a lean month) so you don't collapse at the first difficulty. The second: the share owed for taxes if your business is registered, so you're not caught off guard. A prudent entrepreneur never spends everything that comes in; they always think of the next month and the hard season that may come.",
            es: "El primer error que mata a los pequeños negocios es mezclar el dinero del negocio con el dinero personal. Abre una cuenta o mantén una caja separada para la actividad. Cuando todo está mezclado, crees que tienes dinero cuando en realidad son fondos de tus proveedores o clientes.\n\nLleva tus cuentas cada semana, aunque sea con un simple cuaderno o una hoja de cálculo: lo que entra, lo que sale, lo que queda. Anota cada gasto, hasta los pequeños. Al final del mes verás con claridad si realmente ganas dinero, por dónde se fuga y qué puedes ajustar. Lo que no mides, no lo puedes mejorar.\n\nPor último, págate un salario, aunque sea modesto, y reinvierte parte de las ganancias en el negocio para hacerlo crecer. La disciplina financiera es una forma de integridad: te permite honrar tus compromisos, pagar a tus proveedores a tiempo y construir una reputación sólida.\n\nSepara también dos reservas en cuanto puedas. La primera: un pequeño colchón de seguridad para los imprevistos (una avería, un cliente que tarda en pagar, un mes flojo) para no derrumbarte a la primera dificultad. La segunda: la parte que corresponde a los impuestos si tu actividad está declarada, para que no te tome por sorpresa. Un emprendedor prudente nunca gasta todo lo que entra; siempre piensa en el mes siguiente y en la temporada difícil que puede llegar.",
          },
          keyPoints: {
            fr: ["Ne mélange jamais l'argent du business et l'argent personnel", "Suis chaque semaine ce qui rentre, sort et reste", "Paie-toi un salaire et réinvestis une partie des bénéfices", "Garde deux réserves : un coussin de sécurité et la part des taxes"],
            ht: ["Pa janm melanje lajan biznis la ak lajan pèsonèl", "Swiv chak semèn sa ki antre, soti epi rete", "Peye tèt ou yon salè epi reyenvesti yon pati nan benefis yo", "Kenbe de rezèv : yon kousen sekirite ak pati taks yo"],
            en: ["Never mix business money with personal money", "Track weekly what comes in, goes out and is left", "Pay yourself a salary and reinvest part of the profit", "Keep two reserves: a safety cushion and the tax share"],
            es: ["Nunca mezcles el dinero del negocio con el personal", "Lleva cada semana lo que entra, sale y queda", "Págate un salario y reinvierte parte de las ganancias", "Guarda dos reservas: un colchón de seguridad y la parte de impuestos"],
          },
          exercise: {
            fr: "Ouvre un cahier ou un tableur dédié à ton activité, séparé de ton argent personnel. Pendant deux semaines, note chaque entrée et chaque sortie d'argent, même petite. À la fin, calcule ce qui rentre, ce qui sort et ce qui reste, puis décide d'une somme à mettre de côté chaque semaine comme coussin de sécurité.",
            ht: "Ouvri yon kaye oswa yon tablo ki dedye pou aktivite w, separe ak lajan pèsonèl ou. Pandan de semèn, note chak lajan ki antre ak chak ki soti, menm ti sa yo. Nan fen an, kalkile sa ki antre, sa ki soti ak sa ki rete, apre sa deside yon montan pou mete sou kote chak semèn kòm kousen sekirite.",
            en: "Open a notebook or spreadsheet dedicated to your business, separate from your personal money. For two weeks, record every money in and every money out, even small ones. At the end, calculate what comes in, goes out and is left, then decide on an amount to set aside each week as a safety cushion.",
            es: "Abre un cuaderno u hoja de cálculo dedicada a tu negocio, separada de tu dinero personal. Durante dos semanas, anota cada entrada y cada salida de dinero, hasta las pequeñas. Al final, calcula lo que entra, sale y queda, luego decide una cantidad para apartar cada semana como colchón de seguridad.",
          },
        },
        {
          slug: "gerer-et-grandir",
          title: { fr: "Gérer son activité et la faire grandir", ht: "Jere aktivite w epi fè l grandi", en: "Managing and growing your business", es: "Gestionar y hacer crecer tu negocio" },
          videoId: "",
          content: {
            fr: "Grandir ne veut pas dire « faire tout, tout de suite ». Beaucoup d'entreprises meurent non pas de manque de clients, mais d'avoir grandi trop vite, sans organisation. La croissance saine, c'est consolider ce qui marche, puis ajouter une nouvelle chose à la fois, en gardant la qualité qui a fait ta réputation.\n\nLe premier levier de croissance est souvent le plus négligé : fidéliser tes clients actuels. Il est bien plus facile de vendre à nouveau à quelqu'un de satisfait que de convaincre un inconnu. Prends soin de tes clients, garde le contact, propose-leur un nouveau produit ou une offre spéciale. Un client fidèle qui revient et qui parle de toi vaut plus que dix nouveaux clients de passage.\n\nPour grandir sans t'épuiser, apprends à mieux organiser ton temps et à déléguer. Repère les tâches que tu répètes sans cesse et cherche à les simplifier, les regrouper, ou les confier à quelqu'un. Tu ne peux pas tout faire seul indéfiniment : à un moment, embaucher une aide, même à temps partiel, ou t'associer, te libère pour te concentrer sur ce que toi seul peux faire. Réinvestis une partie de tes bénéfices dans ces outils et ces personnes qui te font gagner du temps.\n\nEnfin, garde un cap clair et des chiffres sous les yeux. Chaque mois, regarde tes ventes, ta marge, tes clients qui reviennent, et demande-toi : « Qu'est-ce qui a le mieux marché ? Qu'est-ce que je peux faire davantage ? » Grandir, c'est répéter et amplifier ce qui fonctionne, et abandonner sans regret ce qui ne rapporte pas. Avance étape par étape, avec patience : les entreprises solides se construisent sur des années, pas sur un coup de chance.",
            ht: "Grandi pa vle di « fè tout bagay, touswit ». Anpil antrepriz mouri, se pa paske yo manke kliyan, men paske yo grandi twò vit, san òganizasyon. Kwasans ki sen, se konsolide sa ki mache, apre sa ajoute yon nouvo bagay alafwa, pandan w ap kenbe kalite ki fè repitasyon w.\n\nPremye leve kwasans lan se souvan sa yo pi neglije a : fidelize kliyan ou genyen deja yo. Li pi fasil pou vann ankò bay yon moun ki satisfè pase konvenk yon enkoni. Pran swen kliyan w, kenbe kontak, pwopoze yo yon nouvo pwodwi oswa yon òf espesyal. Yon kliyan fidèl ki retounen epi ki pale de ou vo plis pase dis nouvo kliyan k ap pase.\n\nPou grandi san izé tèt ou, aprann pi byen òganize tan ou epi delege. Jwenn tach ou repete tout tan yo epi chèche senplifye yo, gwoupe yo, oswa konfye yo bay yon moun. Ou pa ka fè tout bagay poukont ou pou tout tan : nan yon moman, anboche yon èd, menm a tan pasyèl, oswa asosye w, libere w pou konsantre sou sa se ou sèl ki ka fè. Reyenvesti yon pati nan benefis ou nan zouti ak moun sa yo ki fè w genyen tan.\n\nAnfen, kenbe yon kap klè ak chif devan je w. Chak mwa, gade vant ou, maj ou, kliyan ki retounen yo, epi mande tèt ou : « Kisa ki mache pi byen ? Kisa m ka fè plis ? » Grandi, se repete epi anplifye sa ki mache, epi abandone san regrè sa ki pa rapòte. Avanse etap pa etap, ak pasyans : antrepriz solid bati sou ane, pa sou yon kout chans.",
            en: "Growing doesn't mean \"doing everything, all at once.\" Many businesses die not from a lack of customers, but from growing too fast, without organization. Healthy growth means consolidating what works, then adding one new thing at a time, keeping the quality that built your reputation.\n\nThe first lever of growth is often the most neglected: keeping your current customers. It's far easier to sell again to someone satisfied than to convince a stranger. Take care of your customers, stay in touch, offer them a new product or a special deal. A loyal customer who comes back and talks about you is worth more than ten passing new ones.\n\nTo grow without burning out, learn to organize your time better and to delegate. Spot the tasks you repeat endlessly and try to simplify them, group them, or hand them to someone. You can't do everything alone forever: at some point, hiring help, even part-time, or taking a partner, frees you to focus on what only you can do. Reinvest part of your profit into the tools and people that save you time.\n\nFinally, keep a clear direction and the numbers in front of you. Each month, look at your sales, your margin, your returning customers, and ask: \"What worked best? What can I do more of?\" Growing means repeating and amplifying what works, and dropping without regret what doesn't pay. Move step by step, with patience: solid businesses are built over years, not on a stroke of luck.",
            es: "Crecer no significa «hacer todo, de golpe». Muchos negocios mueren no por falta de clientes, sino por crecer demasiado rápido, sin organización. El crecimiento sano es consolidar lo que funciona y luego añadir una cosa nueva a la vez, manteniendo la calidad que construyó tu reputación.\n\nLa primera palanca de crecimiento suele ser la más descuidada: fidelizar a tus clientes actuales. Es mucho más fácil volver a venderle a alguien satisfecho que convencer a un desconocido. Cuida a tus clientes, mantén el contacto, ofréceles un nuevo producto o una oferta especial. Un cliente fiel que vuelve y habla de ti vale más que diez nuevos de paso.\n\nPara crecer sin agotarte, aprende a organizar mejor tu tiempo y a delegar. Detecta las tareas que repites sin cesar y busca simplificarlas, agruparlas o encargárselas a alguien. No puedes hacerlo todo solo indefinidamente: en algún momento, contratar ayuda, aunque sea a tiempo parcial, o asociarte, te libera para concentrarte en lo que solo tú puedes hacer. Reinvierte parte de tus ganancias en esas herramientas y personas que te hacen ganar tiempo.\n\nPor último, mantén un rumbo claro y las cifras a la vista. Cada mes, mira tus ventas, tu margen, tus clientes que vuelven, y pregúntate: «¿Qué funcionó mejor? ¿Qué puedo hacer más?» Crecer es repetir y amplificar lo que funciona, y abandonar sin pena lo que no rinde. Avanza paso a paso, con paciencia: los negocios sólidos se construyen a lo largo de años, no en un golpe de suerte.",
          },
          keyPoints: {
            fr: ["Grandir sainement : consolider ce qui marche, ajouter une chose à la fois", "Fidéliser un client satisfait coûte moins cher que conquérir un inconnu", "Organise ton temps et délègue pour ne pas t'épuiser", "Chaque mois, amplifie ce qui fonctionne, abandonne ce qui ne rapporte pas"],
            ht: ["Grandi ak sante : konsolide sa ki mache, ajoute yon bagay alafwa", "Fidelize yon kliyan satisfè koute mwens pase konkeri yon enkoni", "Òganize tan ou epi delege pou ou pa izé", "Chak mwa, anplifye sa ki mache, abandone sa ki pa rapòte"],
            en: ["Grow healthily: consolidate what works, add one thing at a time", "Keeping a satisfied customer costs less than winning a stranger", "Organize your time and delegate so you don't burn out", "Each month, amplify what works, drop what doesn't pay"],
            es: ["Crecer con salud: consolidar lo que funciona, añadir una cosa a la vez", "Fidelizar a un cliente satisfecho cuesta menos que conquistar a un desconocido", "Organiza tu tiempo y delega para no agotarte", "Cada mes, amplifica lo que funciona, abandona lo que no rinde"],
          },
          exercise: {
            fr: "Fais la liste de tes clients satisfaits et choisis-en trois à recontacter cette semaine avec une attention ou une offre spéciale. Puis note les trois tâches que tu répètes le plus : pour chacune, écris comment tu pourrais la simplifier ou la déléguer. Enfin, à partir de tes chiffres du mois, décide d'une seule chose qui marche que tu vas amplifier.",
            ht: "Fè lis kliyan satisfè ou yo epi chwazi twa pou rekontakte semèn sa a ak yon atansyon oswa yon òf espesyal. Apre sa, note twa tach ou repete plis yo : pou chak, ekri kijan ou ta ka senplifye l oswa delege l. Anfen, apati chif mwa a, deside yon sèl bagay ki mache ou pral anplifye.",
            en: "List your satisfied customers and pick three to reach out to this week with a kind gesture or a special offer. Then note the three tasks you repeat most: for each, write how you could simplify or delegate it. Finally, from your monthly figures, decide on one single thing that works that you'll amplify.",
            es: "Haz la lista de tus clientes satisfechos y elige tres para volver a contactar esta semana con un detalle o una oferta especial. Luego anota las tres tareas que más repites: para cada una, escribe cómo podrías simplificarla o delegarla. Por último, a partir de tus cifras del mes, decide una sola cosa que funcione que vas a amplificar.",
          },
        },
      ],
    },
    {
      title: { fr: "Vendre et travailler avec intégrité", ht: "Vann ak travay ak entegrite", en: "Selling and working with integrity", es: "Vender y trabajar con integridad" },
      lessons: [
        {
          slug: "gagner-premiers-clients",
          title: { fr: "Gagner ses premiers clients", ht: "Genyen premye kliyan w yo", en: "Winning your first customers", es: "Ganar tus primeros clientes" },
          videoId: "",
          content: {
            fr: "Tes premiers clients ne viendront pas d'une grande publicité, mais de ton entourage et du bouche-à-oreille. Commence par les personnes qui te connaissent déjà : famille, amis, voisins, collègues. Parle-leur simplement de ce que tu proposes et demande-leur s'ils connaissent quelqu'un que ça pourrait aider. La confiance se transmet de personne en personne.\n\nSoigne particulièrement tes premiers clients : livre plus que promis, réponds vite, sois reconnaissant. Un premier client bien servi devient ton meilleur vendeur, car il parlera de toi autour de lui. Demande-lui gentiment un témoignage ou une recommandation ; ces preuves sociales valent plus que n'importe quelle affiche.\n\nSois régulier et présent. Beaucoup abandonnent après quelques « non ». Or, chaque « non » te rapproche d'un « oui » et t'apprend à mieux présenter ton offre. Frappe à dix portes, ajuste ton message, et recommence. La constance finit toujours par payer.\n\nRends aussi l'achat le plus facile possible. Beaucoup de ventes se perdent non pas parce que le client dit non, mais parce qu'il ne sait pas comment payer, où te trouver, ni quoi faire ensuite. Indique clairement le prix, les moyens de paiement, et l'étape suivante (« écris-moi sur WhatsApp », « passe samedi entre 9 h et midi »). Un client intéressé mais qui doit deviner comment acheter finit souvent par ne rien faire. Guide-le, pas à pas, jusqu'à la vente.",
            ht: "Premye kliyan w yo p ap soti nan yon gwo reklam, men nan antouraj ou ak bouch a zòrèy. Kòmanse ak moun ki deja konnen w : fanmi, zanmi, vwazen, kòlèg. Pale yo senpleman de sa w ap ofri epi mande yo si yo konnen yon moun sa ta ka ede. Konfyans transmèt de moun an moun.\n\nPran swen premye kliyan w yo espesyalman : livre plis pase sa ou pwomèt, reponn vit, montre rekonesans. Yon premye kliyan ki byen sèvi vin pi bon vandè w, paske l ap pale de ou bay moun otou l. Mande l jantiman yon temwayaj oswa yon rekòmandasyon ; prèv sosyal sa yo vo plis pase nenpòt afich.\n\nSe regilye epi prezan. Anpil moun abandone apre kèk « non ». Men, chak « non » pwoche w de yon « wi » epi li aprann ou prezante òf ou pi byen. Frape dis pòt, ajiste mesaj ou, epi rekòmanse. Konstans toujou fini pa peye.\n\nRann acha a pi fasil posib tou. Anpil vant pèdi, se pa paske kliyan an di non, men paske li pa konnen kijan pou peye, kote pou jwenn ou, ni kisa pou fè apre. Endike klèman pri a, mwayen pou peye yo, ak etap ki apre a (« ekri m sou WhatsApp », « pase samdi ant 9è ak midi »). Yon kliyan ki enterese men ki dwe devine kijan pou achte souvan fini pa pa fè anyen. Gide l, pa apa, jouk nan vant lan.",
            en: "Your first customers will not come from a big ad, but from your circle and word of mouth. Start with the people who already know you: family, friends, neighbors, coworkers. Simply tell them what you offer and ask if they know anyone it could help. Trust passes from person to person.\n\nTake special care of your first customers: deliver more than promised, respond quickly, be grateful. A well-served first customer becomes your best salesperson, because they will talk about you to those around them. Kindly ask for a testimonial or recommendation; this social proof is worth more than any poster.\n\nBe consistent and present. Many give up after a few \"no\"s. Yet every \"no\" brings you closer to a \"yes\" and teaches you to present your offer better. Knock on ten doors, adjust your message, and start again. Consistency always ends up paying off.\n\nAlso make buying as easy as possible. Many sales are lost not because the customer says no, but because they don't know how to pay, where to find you, or what to do next. Clearly state the price, the payment methods, and the next step (\"message me on WhatsApp\", \"come Saturday between 9 and noon\"). An interested customer who has to guess how to buy often ends up doing nothing. Guide them, step by step, to the sale.",
            es: "Tus primeros clientes no vendrán de un gran anuncio, sino de tu entorno y del boca a boca. Empieza por las personas que ya te conocen: familia, amigos, vecinos, compañeros. Cuéntales sencillamente lo que ofreces y pregúntales si conocen a alguien a quien podría ayudar. La confianza se transmite de persona a persona.\n\nCuida especialmente a tus primeros clientes: entrega más de lo prometido, responde rápido, sé agradecido. Un primer cliente bien atendido se convierte en tu mejor vendedor, porque hablará de ti a su alrededor. Pídele amablemente un testimonio o una recomendación; esa prueba social vale más que cualquier cartel.\n\nSé constante y presente. Muchos abandonan tras algunos «no». Sin embargo, cada «no» te acerca a un «sí» y te enseña a presentar mejor tu oferta. Toca diez puertas, ajusta tu mensaje y vuelve a empezar. La constancia siempre termina dando frutos.\n\nHaz también la compra lo más fácil posible. Muchas ventas se pierden no porque el cliente diga no, sino porque no sabe cómo pagar, dónde encontrarte, ni qué hacer después. Indica con claridad el precio, los medios de pago y el paso siguiente («escríbeme por WhatsApp», «pásate el sábado entre las 9 y el mediodía»). Un cliente interesado que debe adivinar cómo comprar a menudo termina no haciendo nada. Guíalo, paso a paso, hasta la venta.",
          },
          keyPoints: {
            fr: ["Commence par ton entourage et le bouche-à-oreille", "Sur-livre pour tes premiers clients : ils deviennent tes vendeurs", "Chaque « non » te rapproche d'un « oui » : reste constant", "Rends l'achat facile : prix, paiement et étape suivante clairs"],
            ht: ["Kòmanse ak antouraj ou ak bouch a zòrèy", "Livre plis pou premye kliyan yo : yo vin vandè w", "Chak « non » pwoche w de yon « wi » : rete konstan", "Rann acha a fasil : pri, peman ak etap ki apre klè"],
            en: ["Start with your circle and word of mouth", "Over-deliver for your first customers: they become your sellers", "Every \"no\" brings you closer to a \"yes\": stay consistent", "Make buying easy: clear price, payment and next step"],
            es: ["Empieza por tu entorno y el boca a boca", "Entrega de más a tus primeros clientes: se vuelven tus vendedores", "Cada «no» te acerca a un «sí»: mantente constante", "Haz la compra fácil: precio, pago y paso siguiente claros"],
          },
          exercise: {
            fr: "Dresse la liste de dix personnes de ton entourage à qui parler de ton activité cette semaine. Prépare une phrase simple pour présenter ton offre et une phrase claire pour dire comment acheter (prix, paiement, étape suivante). Contacte-les, note les réactions, et demande à ton premier client satisfait un court témoignage.",
            ht: "Fè lis dis moun nan antouraj ou pou pale de aktivite w semèn sa a. Prepare yon fraz senp pou prezante òf ou ak yon fraz klè pou di kijan pou achte (pri, peman, etap ki apre). Kontakte yo, note reyaksyon yo, epi mande premye kliyan satisfè w yon ti temwayaj.",
            en: "List ten people in your circle to talk to about your business this week. Prepare a simple sentence to present your offer and a clear sentence to say how to buy (price, payment, next step). Contact them, note the reactions, and ask your first satisfied customer for a short testimonial.",
            es: "Haz la lista de diez personas de tu entorno a quienes hablar de tu negocio esta semana. Prepara una frase simple para presentar tu oferta y una frase clara para decir cómo comprar (precio, pago, paso siguiente). Contáctalos, anota las reacciones y pide a tu primer cliente satisfecho un breve testimonio.",
          },
        },
        {
          slug: "savoir-vendre-sans-forcer",
          title: { fr: "Savoir vendre sans forcer", ht: "Konnen vann san fòse", en: "Selling without pushing", es: "Saber vender sin presionar" },
          videoId: "",
          content: {
            fr: "Beaucoup de gens honnêtes détestent l'idée de « vendre » parce qu'ils l'associent à la manipulation ou à la pression. Change de regard : vendre, ce n'est pas forcer quelqu'un à acheter ce dont il n'a pas besoin, c'est aider une personne qui a un problème à trouver la solution que tu proposes. Bien fait, vendre est un acte de service, pas un combat.\n\nLa base d'une bonne vente, c'est d'écouter avant de parler. Pose des questions pour comprendre le vrai besoin du client, puis présente ton offre comme une réponse précise à ce besoin. Parle des bénéfices (« ce plat vous fait gagner une heure chaque midi ») plutôt que d'une simple liste de caractéristiques. Les gens n'achètent pas ce que fait ton produit, ils achètent ce qu'il change pour eux.\n\nSois honnête, y compris sur les limites de ton offre. Si ton produit ne convient pas à ce client-là, dis-le : tu perds une vente mais tu gagnes une confiance qui te rapportera dix fois plus. Une promesse exagérée attire une vente et détruit une réputation. La sincérité, au contraire, transforme un acheteur méfiant en client fidèle qui revient et te recommande.\n\nEnfin, ose demander la vente clairement. Beaucoup présentent bien leur offre puis restent flous à la fin, par peur du refus, et laissent le client repartir sans rien. Termine par une invitation simple et directe : « Est-ce que vous voulez que je vous en prépare un ? » ou « On commence quand vous voulez, je peux vous livrer demain. » Demander gentiment n'est pas agressif, c'est aider le client à franchir le pas qu'il souhaite déjà faire.",
            ht: "Anpil moun onèt rayi lide « vann » nan paske yo asosye l ak manipilasyon oswa presyon. Chanje fason ou wè l : vann, se pa fòse yon moun achte sa li pa bezwen, se ede yon moun ki gen yon pwoblèm jwenn solisyon ou pwopoze a. Byen fèt, vann se yon zak sèvis, pa yon batay.\n\nBaz yon bon vant, se koute anvan ou pale. Poze kesyon pou konprann vrè bezwen kliyan an, apre sa prezante òf ou kòm yon repons presi pou bezwen sa a. Pale de benefis yo (« plat sa a fè w genyen yon èdtan chak midi ») olye yon senp lis karakteristik. Moun pa achte sa pwodwi w fè, yo achte sa li chanje pou yo.\n\nSe onèt, menm sou limit òf ou. Si pwodwi w pa bon pou kliyan sa a, di l : ou pèdi yon vant men ou genyen yon konfyans ki ap rapòte w dis fwa plis. Yon pwomès egzajere atire yon vant epi detwi yon repitasyon. Sensèrite a, okontrè, transfòme yon achtè mefyan an yon kliyan fidèl ki retounen epi ki rekòmande w.\n\nAnfen, oze mande vant lan klèman. Anpil moun byen prezante òf yo apre sa yo rete vag nan fen an, pa laperèz refi, epi yo kite kliyan an ale san anyen. Fini ak yon envitasyon senp epi dirèk : « Èske ou vle m prepare w youn ? » oswa « N ap kòmanse lè ou vle, m ka livre w demen. » Mande jantiman se pa agresif, se ede kliyan an franchi pa li deja vle fè a.",
            en: "Many honest people hate the idea of \"selling\" because they associate it with manipulation or pressure. Change your view: selling isn't forcing someone to buy what they don't need, it's helping a person with a problem find the solution you offer. Done well, selling is an act of service, not a battle.\n\nThe foundation of good selling is to listen before you speak. Ask questions to understand the customer's real need, then present your offer as a precise answer to that need. Talk about benefits (\"this meal saves you an hour every noon\") rather than a mere list of features. People don't buy what your product does, they buy what it changes for them.\n\nBe honest, including about your offer's limits. If your product isn't right for this customer, say so: you lose a sale but gain a trust that will pay you back tenfold. An exaggerated promise wins a sale and destroys a reputation. Sincerity, on the contrary, turns a wary buyer into a loyal customer who comes back and recommends you.\n\nFinally, dare to ask for the sale clearly. Many present their offer well, then stay vague at the end, out of fear of refusal, and let the customer leave with nothing. End with a simple, direct invitation: \"Would you like me to prepare one for you?\" or \"We can start whenever you want, I can deliver tomorrow.\" Asking kindly isn't aggressive, it's helping the customer take the step they already want to take.",
            es: "Mucha gente honesta detesta la idea de «vender» porque la asocia con la manipulación o la presión. Cambia tu mirada: vender no es forzar a alguien a comprar lo que no necesita, es ayudar a una persona con un problema a encontrar la solución que ofreces. Bien hecho, vender es un acto de servicio, no una pelea.\n\nLa base de una buena venta es escuchar antes de hablar. Haz preguntas para entender la verdadera necesidad del cliente, luego presenta tu oferta como una respuesta precisa a esa necesidad. Habla de los beneficios («este plato le ahorra una hora cada mediodía») en lugar de una simple lista de características. La gente no compra lo que hace tu producto, compra lo que cambia para ellos.\n\nSé honesto, incluso sobre los límites de tu oferta. Si tu producto no le conviene a ese cliente, dilo: pierdes una venta pero ganas una confianza que te devolverá diez veces más. Una promesa exagerada gana una venta y destruye una reputación. La sinceridad, al contrario, convierte a un comprador desconfiado en un cliente fiel que vuelve y te recomienda.\n\nPor último, atrévete a pedir la venta con claridad. Muchos presentan bien su oferta y luego se quedan vagos al final, por miedo al rechazo, y dejan que el cliente se vaya sin nada. Termina con una invitación simple y directa: «¿Quiere que le prepare uno?» o «Empezamos cuando quiera, puedo entregárselo mañana.» Pedir con amabilidad no es agresivo, es ayudar al cliente a dar el paso que ya desea dar.",
          },
          keyPoints: {
            fr: ["Vendre = aider quelqu'un à résoudre son problème, pas forcer", "Écoute d'abord, puis parle des bénéfices, pas des caractéristiques", "Sois honnête sur les limites : la confiance rapporte plus qu'une vente", "Ose demander la vente par une invitation simple et directe"],
            ht: ["Vann = ede yon moun rezoud pwoblèm li, pa fòse", "Koute anvan, apre sa pale de benefis, pa karakteristik", "Se onèt sou limit yo : konfyans rapòte plis pase yon vant", "Oze mande vant lan ak yon envitasyon senp epi dirèk"],
            en: ["Selling = helping someone solve their problem, not forcing", "Listen first, then talk benefits, not features", "Be honest about limits: trust pays more than a sale", "Dare to ask for the sale with a simple, direct invitation"],
            es: ["Vender = ayudar a alguien a resolver su problema, no forzar", "Escucha primero, luego habla de beneficios, no de características", "Sé honesto sobre los límites: la confianza rinde más que una venta", "Atrévete a pedir la venta con una invitación simple y directa"],
          },
          exercise: {
            fr: "Écris trois questions à poser à un client pour comprendre son vrai besoin avant de proposer ton offre. Reformule ensuite ton produit en termes de bénéfices (« ce que ça change pour vous ») et non de caractéristiques. Prépare enfin une phrase simple pour demander la vente, et entraîne-toi à la dire à voix haute avec un proche.",
            ht: "Ekri twa kesyon pou poze yon kliyan pou konprann vrè bezwen li anvan ou pwopoze òf ou. Apre sa, reformile pwodwi w an tèm benefis (« sa li chanje pou ou ») olye karakteristik. Anfen, prepare yon fraz senp pou mande vant lan, epi antrene w pou di l awotvwa ak yon moun pre ou.",
            en: "Write three questions to ask a customer to understand their real need before offering your product. Then reframe your product in terms of benefits (\"what it changes for you\") rather than features. Finally, prepare a simple sentence to ask for the sale, and practise saying it out loud with someone close.",
            es: "Escribe tres preguntas para hacerle a un cliente y entender su verdadera necesidad antes de proponer tu oferta. Luego reformula tu producto en términos de beneficios («lo que cambia para usted») y no de características. Por último, prepara una frase simple para pedir la venta, y practica decirla en voz alta con un allegado.",
          },
        },
        {
          slug: "esprit-chretien-du-travail",
          title: { fr: "L'esprit chrétien du travail et l'intégrité", ht: "Lespri kretyen travay la ak entegrite", en: "The Christian spirit of work and integrity", es: "El espíritu cristiano del trabajo y la integridad" },
          videoId: "",
          content: {
            fr: "Pour le croyant, le travail n'est pas seulement un moyen de gagner de l'argent : c'est une façon de servir Dieu et son prochain. « Quoi que vous fassiez, faites-le de tout votre cœur, comme pour le Seigneur et non pour des hommes. » Cela transforme un simple commerce en vocation. Ton client n'est pas seulement une source de revenu, c'est une personne à servir avec soin.\n\nL'intégrité est ton capital le plus précieux. Tenir parole, livrer ce que tu as promis, dire la vérité sur ton produit, ne pas tromper sur le prix ou la qualité : voilà ce qui bâtit une réputation durable. « Mieux vaut peu avec la justice que de grands revenus avec l'injustice. » Un gain malhonnête finit toujours par coûter cher.\n\nEnfin, souviens-toi que la prospérité n'est pas une fin en soi mais un moyen de faire le bien. Un entrepreneur chrétien crée des emplois, aide sa communauté et donne avec générosité. Travaille dur, sois honnête, sers avec excellence — et fais confiance à Dieu pour les fruits.\n\nL'intégrité se joue surtout dans les petites décisions quotidiennes, quand personne ne regarde : rendre la monnaie exacte, tenir un délai même quand c'est difficile, reconnaître une erreur au lieu de la cacher, refuser un mensonge « qui arrangerait bien ». Ces petits choix, répétés, construisent lentement une confiance qui devient ta meilleure publicité. Dans une communauté, on finit toujours par savoir qui est droit et qui ne l'est pas.\n\nGarde aussi l'équilibre. Le travail est bon, mais il n'est pas un dieu. Prends soin de ta santé, de ta famille et de ta vie spirituelle ; réserve du temps pour te reposer et pour donner. Un entrepreneur qui réussit mais perd sa paix, sa famille ou son âme n'a pas vraiment réussi. Travaille avec ardeur et confiance, sème le bien autour de toi, et laisse Dieu faire croître ce que tu plantes avec droiture.",
            ht: "Pou moun ki kwè a, travay pa sèlman yon mwayen pou fè lajan : se yon fason pou sèvi Bondye ak pwochen w. « Kèlkeswa sa n ap fè, fè l ak tout kè nou, tankou pou Senyè a e non pou moun. » Sa transfòme yon senp komès an yon vokasyon. Kliyan w pa sèlman yon sous revni, se yon moun pou sèvi ak swen.\n\nEntegrite se pi bon kapital ou genyen. Kenbe pawòl ou, livre sa ou pwomèt, di verite sou pwodwi w, pa twonpe sou pri oswa kalite : men sa ki bati yon repitasyon ki dire. « Pito ou gen ti kras ak jistis pase anpil revni ak lenjistis. » Yon pwofi malonèt toujou fini pa koute chè.\n\nAnfen, sonje pwosperite pa yon bi nan tèt li men yon mwayen pou fè byen. Yon antreprenè kretyen kreye djòb, ede kominote l epi bay ak jenerozite. Travay di, se onèt, sèvi ak eksèlans — epi fè Bondye konfyans pou fwi yo.\n\nEntegrite jwe sitou nan ti desizyon chak jou yo, lè pèsonn pa gade : remèt monnen egzak, kenbe yon delè menm lè li difisil, rekonèt yon erè olye kache l, refize yon manti « ki ta byen ranje bagay yo ». Ti chwa sa yo, ki repete, bati dousman yon konfyans ki vin pi bon piblisite w. Nan yon kominote, moun toujou fini pa konnen kilès ki dwat ak kilès ki pa dwat.\n\nKenbe ekilib la tou. Travay bon, men li pa yon bondye. Pran swen sante w, fanmi w ak vi espirityèl ou ; rezève tan pou repoze w epi pou bay. Yon antreprenè ki reyisi men ki pèdi lapè li, fanmi li oswa nanm li pa reyisi tout bon. Travay ak kouraj ak konfyans, simen byen otou w, epi kite Bondye fè grandi sa ou plante ak dwati.",
            en: "For the believer, work is not only a way to earn money: it is a way to serve God and one's neighbor. \"Whatever you do, work at it with all your heart, as working for the Lord and not for men.\" This turns a simple trade into a calling. Your customer is not only a source of income, but a person to serve with care.\n\nIntegrity is your most precious capital. Keeping your word, delivering what you promised, telling the truth about your product, not deceiving on price or quality: this is what builds a lasting reputation. \"Better a little with righteousness than great income with injustice.\" Dishonest gain always ends up costing dearly.\n\nFinally, remember that prosperity is not an end in itself but a means to do good. A Christian entrepreneur creates jobs, helps their community and gives generously. Work hard, be honest, serve with excellence — and trust God for the fruit.\n\nIntegrity is played out above all in the small daily decisions, when no one is watching: giving exact change, keeping a deadline even when it's hard, admitting a mistake instead of hiding it, refusing a lie \"that would be convenient.\" These small choices, repeated, slowly build a trust that becomes your best advertising. In a community, people always end up knowing who is upright and who is not.\n\nKeep your balance too. Work is good, but it is not a god. Take care of your health, your family and your spiritual life; set aside time to rest and to give. An entrepreneur who succeeds but loses their peace, their family or their soul has not truly succeeded. Work with zeal and trust, sow good around you, and let God grow what you plant with uprightness.",
            es: "Para el creyente, el trabajo no es solo un medio para ganar dinero: es una forma de servir a Dios y al prójimo. «Todo lo que hagáis, hacedlo de corazón, como para el Señor y no para los hombres.» Esto convierte un simple comercio en una vocación. Tu cliente no es solo una fuente de ingresos, es una persona a quien servir con cuidado.\n\nLa integridad es tu capital más valioso. Cumplir tu palabra, entregar lo prometido, decir la verdad sobre tu producto, no engañar en el precio o la calidad: eso es lo que construye una reputación duradera. «Mejor es lo poco con justicia que la muchedumbre de frutos sin derecho.» Una ganancia deshonesta siempre termina costando caro.\n\nPor último, recuerda que la prosperidad no es un fin en sí misma, sino un medio para hacer el bien. Un emprendedor cristiano crea empleos, ayuda a su comunidad y da con generosidad. Trabaja duro, sé honesto, sirve con excelencia — y confía en Dios para los frutos.\n\nLa integridad se juega sobre todo en las pequeñas decisiones diarias, cuando nadie mira: dar el cambio exacto, cumplir un plazo aunque sea difícil, reconocer un error en vez de ocultarlo, rechazar una mentira «que vendría bien». Estas pequeñas elecciones, repetidas, construyen despacio una confianza que se vuelve tu mejor publicidad. En una comunidad, la gente siempre termina sabiendo quién es recto y quién no.\n\nMantén también el equilibrio. El trabajo es bueno, pero no es un dios. Cuida tu salud, tu familia y tu vida espiritual; reserva tiempo para descansar y para dar. Un emprendedor que triunfa pero pierde su paz, su familia o su alma no ha triunfado de verdad. Trabaja con ánimo y confianza, siembra el bien a tu alrededor, y deja que Dios haga crecer lo que plantas con rectitud.",
          },
          keyPoints: {
            fr: ["Le travail est un service rendu à Dieu et au prochain", "L'intégrité (tenir parole, dire vrai) est ton capital le plus précieux", "L'intégrité se joue dans les petites décisions, quand personne ne regarde", "Garde l'équilibre : santé, famille et foi comptent plus que le profit"],
            ht: ["Travay se yon sèvis w ap bay Bondye ak pwochen w", "Entegrite (kenbe pawòl, di verite) se pi bon kapital ou", "Entegrite jwe nan ti desizyon yo, lè pèsonn pa gade", "Kenbe ekilib : sante, fanmi ak lafwa konte plis pase pwofi"],
            en: ["Work is a service to God and neighbor", "Integrity (keeping your word, telling the truth) is your most precious capital", "Integrity is played out in small decisions, when no one is watching", "Keep balance: health, family and faith matter more than profit"],
            es: ["El trabajo es un servicio a Dios y al prójimo", "La integridad (cumplir la palabra, decir la verdad) es tu capital más valioso", "La integridad se juega en las pequeñas decisiones, cuando nadie mira", "Mantén el equilibrio: salud, familia y fe importan más que la ganancia"],
          },
          exercise: {
            fr: "Repère dans ton activité une situation où l'honnêteté te coûte un peu (rendre la monnaie exacte, reconnaître une erreur, tenir une promesse difficile) et engage-toi à bien agir cette semaine. Puis choisis une façon concrète de faire le bien avec ton travail : un prix juste, un service rendu gratuitement, ou une part donnée à qui en a besoin.",
            ht: "Jwenn nan aktivite w yon sitiyasyon kote onètete koute w yon ti jan (remèt monnen egzak, rekonèt yon erè, kenbe yon pwomès difisil) epi angaje w pou byen aji semèn sa a. Apre sa, chwazi yon fason konkrè pou fè byen ak travay ou : yon pri jis, yon sèvis bay gratis, oswa yon pati bay moun ki bezwen l.",
            en: "Identify in your business a situation where honesty costs you a little (giving exact change, admitting a mistake, keeping a hard promise) and commit to acting rightly this week. Then choose one concrete way to do good with your work: a fair price, a service given for free, or a share given to someone in need.",
            es: "Identifica en tu negocio una situación donde la honestidad te cuesta un poco (dar el cambio exacto, reconocer un error, cumplir una promesa difícil) y comprométete a actuar bien esta semana. Luego elige una forma concreta de hacer el bien con tu trabajo: un precio justo, un servicio dado gratis, o una parte dada a quien lo necesita.",
          },
        },
      ],
    },
  ],
};

export default entrepreneuriat;
