import { CourseContent } from "./types";

const excel: CourseContent = {
  slug: "excel",
  intro: {
    fr: "Apprendre à utiliser Microsoft Excel pour saisir des données, faire des calculs automatiques, trier, filtrer et créer des graphiques, pas à pas.",
    ht: "Aprann sèvi ak Microsoft Excel pou antre done, fè kalkil otomatik, triye, filtre ak kreye grafik, etap pa etap.",
    en: "Learn to use Microsoft Excel to enter data, do automatic calculations, sort, filter and create charts, step by step.",
    es: "Aprender a usar Microsoft Excel para introducir datos, hacer cálculos automáticos, ordenar, filtrar y crear gráficos, paso a paso.",
  },
  modules: [
    {
      title: { fr: "Comprendre le tableur", ht: "Konprann tablè a", en: "Understanding the spreadsheet", es: "Comprender la hoja de cálculo" },
      lessons: [
        {
          slug: "cellules-lignes-colonnes",
          title: { fr: "Cellules, lignes et colonnes", ht: "Selil, liy ak kolòn", en: "Cells, rows and columns", es: "Celdas, filas y columnas" },
          videoId: "",
          content: {
            fr: "Microsoft Excel est un tableur : un logiciel fait pour organiser des données et faire des calculs. Quand tu l'ouvres, tu vois une grille immense composée de petites cases. Chaque case s'appelle une « cellule », et c'est là que tu tapes tes informations : un mot, un nombre ou une date.\n\nLes colonnes sont verticales et portent des lettres en haut (A, B, C…). Les lignes sont horizontales et portent des numéros à gauche (1, 2, 3…). Chaque cellule a donc une adresse unique formée de la lettre de sa colonne et du numéro de sa ligne : la cellule en haut à gauche est « A1 », juste en dessous « A2 », et à sa droite « B1 ». Cette adresse est très importante pour les calculs.\n\nPour te déplacer, clique simplement sur une cellule ou utilise les flèches du clavier. La cellule sélectionnée est entourée d'un cadre vert, et son adresse s'affiche dans la « zone Nom », le petit cadre en haut à gauche, juste au-dessus de la colonne A.\n\nEn bas de l'écran, des onglets comme « Feuil1 » représentent les différentes feuilles d'un même fichier ; un classeur Excel peut en contenir plusieurs. Cette organisation en grille est parfaite pour tenir un budget, une liste de contacts, un inventaire ou les notes d'une classe.",
            ht: "Microsoft Excel se yon tablè : yon lojisyèl ki fèt pou òganize done epi fè kalkil. Lè ou ouvri l, ou wè yon gwo griy ki gen anpil ti kaz. Chak kaz rele yon « selil », epi se la ou tape enfòmasyon ou : yon mo, yon nimewo oswa yon dat.\n\nKolòn yo vètikal epi yo gen lèt anwo (A, B, C…). Liy yo orizontal epi yo gen nimewo agoch (1, 2, 3…). Konsa chak selil gen yon adrès inik ki fèt ak lèt kolòn li an ak nimewo liy li an : selil anwo agoch la se « A1 », jis anba l se « A2 », epi adwat li se « B1 ». Adrès sa a enpòtan anpil pou kalkil yo.\n\nPou deplase, klike sèlman sou yon selil oswa sèvi ak flèch klavye yo. Selil ou chwazi a gen yon kad vèt otou l, epi adrès li parèt nan « zone Nom » an, ti kad ki anwo agoch la, jis anwo kolòn A.\n\nAnba ekran an, onglè tankou « Feuil1 » reprezante diferan fèy nan yon menm fichye ; yon klasè Excel ka gen plizyè. Òganizasyon an griy sa a pafè pou kenbe yon bidjè, yon lis kontak, yon envantè oswa nòt yon klas.",
            en: "Microsoft Excel is a spreadsheet: a program made to organize data and do calculations. When you open it, you see a huge grid made of small boxes. Each box is called a \"cell\", and that is where you type your information: a word, a number or a date.\n\nColumns are vertical and are labeled with letters at the top (A, B, C…). Rows are horizontal and are labeled with numbers on the left (1, 2, 3…). So each cell has a unique address made of its column letter and its row number: the top-left cell is \"A1\", just below it is \"A2\", and to its right is \"B1\". This address is very important for calculations.\n\nTo move around, simply click a cell or use the arrow keys. The selected cell is surrounded by a green frame, and its address appears in the \"Name Box\", the small box at the top left, just above column A.\n\nAt the bottom of the screen, tabs such as \"Sheet1\" represent the different sheets in the same file; an Excel workbook can contain several. This grid layout is perfect for keeping a budget, a contact list, an inventory or a class's grades.",
            es: "Microsoft Excel es una hoja de cálculo: un programa hecho para organizar datos y hacer cálculos. Cuando lo abres, ves una cuadrícula enorme formada por pequeñas casillas. Cada casilla se llama «celda», y ahí es donde escribes tu información: una palabra, un número o una fecha.\n\nLas columnas son verticales y llevan letras arriba (A, B, C…). Las filas son horizontales y llevan números a la izquierda (1, 2, 3…). Así, cada celda tiene una dirección única formada por la letra de su columna y el número de su fila: la celda de arriba a la izquierda es «A1», justo debajo «A2», y a su derecha «B1». Esta dirección es muy importante para los cálculos.\n\nPara desplazarte, simplemente haz clic en una celda o usa las flechas del teclado. La celda seleccionada está rodeada por un marco verde, y su dirección aparece en el «cuadro de nombres», la pequeña casilla de arriba a la izquierda, justo encima de la columna A.\n\nEn la parte inferior de la pantalla, pestañas como «Hoja1» representan las distintas hojas de un mismo archivo; un libro de Excel puede contener varias. Esta organización en cuadrícula es perfecta para llevar un presupuesto, una lista de contactos, un inventario o las notas de una clase.",
          },
          keyPoints: {
            fr: ["Une cellule = une case où l'on tape une donnée", "Colonnes = lettres (A, B…), lignes = numéros (1, 2…)", "Chaque cellule a une adresse unique (A1, B2…)", "La zone Nom affiche l'adresse de la cellule active"],
            ht: ["Yon selil = yon kaz kote ou tape yon done", "Kolòn = lèt (A, B…), liy = nimewo (1, 2…)", "Chak selil gen yon adrès inik (A1, B2…)", "Zone Nom nan montre adrès selil aktif la"],
            en: ["A cell = a box where you type a piece of data", "Columns = letters (A, B…), rows = numbers (1, 2…)", "Each cell has a unique address (A1, B2…)", "The Name Box shows the active cell's address"],
            es: ["Una celda = una casilla donde se escribe un dato", "Columnas = letras (A, B…), filas = números (1, 2…)", "Cada celda tiene una dirección única (A1, B2…)", "El cuadro de nombres muestra la dirección de la celda activa"],
          },
          exercise: {
            fr: "Ouvre un nouveau classeur. Clique sur la cellule B2 et vérifie que « B2 » s'affiche dans la zone Nom. Tape ton prénom en A1, ton âge en B1, ta ville en C1, puis déplace-toi avec les flèches du clavier pour repérer les adresses A2, B2 et C2.",
            ht: "Ouvri yon nouvo klasè. Klike sou selil B2 epi verifye « B2 » parèt nan zone Nom nan. Tape prenon ou nan A1, laj ou nan B1, vil ou nan C1, epi deplase ak flèch klavye yo pou jwenn adrès A2, B2 ak C2.",
            en: "Open a new workbook. Click cell B2 and check that \"B2\" appears in the Name Box. Type your first name in A1, your age in B1, your city in C1, then move with the arrow keys to spot addresses A2, B2 and C2.",
            es: "Abre un libro nuevo. Haz clic en la celda B2 y comprueba que aparece «B2» en el cuadro de nombres. Escribe tu nombre en A1, tu edad en B1, tu ciudad en C1, luego desplázate con las flechas del teclado para localizar las direcciones A2, B2 y C2.",
          },
        },
        {
          slug: "saisir-donnees",
          title: { fr: "Saisir et modifier des données", ht: "Antre ak chanje done", en: "Entering and editing data", es: "Introducir y modificar datos" },
          videoId: "",
          content: {
            fr: "Pour remplir un tableau, clique sur une cellule, tape ton texte ou ton nombre, puis appuie sur Entrée pour valider et descendre à la cellule du dessous. Tu peux aussi appuyer sur la touche Tab pour valider et passer à la cellule de droite. C'est ainsi que tu construis, par exemple, une colonne de noms et une colonne de montants.\n\nSi tu veux corriger une cellule, tu as deux façons de faire. Clique une fois dessus et retape entièrement pour tout remplacer, ou double-clique pour entrer dans la cellule et modifier seulement une partie du contenu. La touche Suppr efface le contenu d'une cellule sélectionnée sans supprimer la cellule elle-même.\n\nExcel distingue les nombres du texte : un nombre se cale à droite de la cellule, un texte à gauche. Si un nombre s'affiche à gauche, c'est souvent qu'il contient une erreur (un espace, une virgule mal placée) et Excel le prend pour du texte : il ne pourra pas servir dans un calcul.\n\nExcel offre une aide très pratique : la recopie automatique. Tape « Janvier » dans une cellule, sélectionne-la, puis attrape le petit carré en bas à droite de la cellule (la « poignée de recopie ») et tire vers le bas : Excel écrit tout seul Février, Mars, Avril… Cela marche aussi avec les nombres et les dates, et fait gagner beaucoup de temps.",
            ht: "Pou ranpli yon tablo, klike sou yon selil, tape tèks ou oswa nimewo ou, epi peze Entrée pou valide epi desann nan selil anba a. Ou ka peze bouton Tab tou pou valide epi pase nan selil adwat la. Se konsa ou konstwi, pa egzanp, yon kolòn non ak yon kolòn montan.\n\nSi ou vle korije yon selil, ou gen de fason pou fè l. Klike yon fwa sou li epi retape tout pou ranplase tout, oswa double-klike pou antre nan selil la epi chanje sèlman yon pati nan kontni an. Bouton Suppr efase kontni yon selil ou chwazi san efase selil la menm.\n\nExcel fè diferans ant nimewo ak tèks : yon nimewo kole adwat selil la, yon tèks kole agoch. Si yon nimewo parèt agoch, souvan se paske li gen yon erè (yon espas, yon vigil ki mal plase) epi Excel pran l pou tèks : li p ap ka sèvi nan yon kalkil.\n\nExcel bay yon èd ki pratik anpil : rekopi otomatik. Tape « Janvier » nan yon selil, chwazi l, epi kenbe ti kare ki anba adwat selil la (« ponyèt rekopi » a) epi rale desann : Excel ekri pou kont li Février, Mars, Avril… Sa mache tou ak nimewo ak dat, epi li fè ou pran anpil mwens tan.",
            en: "To fill in a table, click a cell, type your text or number, then press Enter to confirm and move down to the cell below. You can also press the Tab key to confirm and move to the cell on the right. This is how you build, for example, a column of names and a column of amounts.\n\nIf you want to correct a cell, you have two ways. Click it once and retype everything to replace it all, or double-click to enter the cell and change only part of the content. The Delete key clears the content of a selected cell without removing the cell itself.\n\nExcel tells numbers and text apart: a number lines up on the right of the cell, text on the left. If a number appears on the left, it often means it contains an error (a space, a misplaced comma) and Excel treats it as text: it will not work in a calculation.\n\nExcel offers a very handy help: automatic fill. Type \"January\" in a cell, select it, then grab the small square at the bottom-right of the cell (the \"fill handle\") and drag down: Excel writes February, March, April… by itself. This also works with numbers and dates, and saves a lot of time.",
            es: "Para rellenar una tabla, haz clic en una celda, escribe tu texto o número, y luego pulsa Enter para confirmar y bajar a la celda de abajo. También puedes pulsar la tecla Tab para confirmar y pasar a la celda de la derecha. Así es como construyes, por ejemplo, una columna de nombres y una columna de importes.\n\nSi quieres corregir una celda, tienes dos formas. Haz clic una vez y vuelve a escribir todo para reemplazarlo, o haz doble clic para entrar en la celda y cambiar solo una parte del contenido. La tecla Supr borra el contenido de una celda seleccionada sin eliminar la celda en sí.\n\nExcel distingue los números del texto: un número se alinea a la derecha de la celda, un texto a la izquierda. Si un número aparece a la izquierda, suele significar que contiene un error (un espacio, una coma mal puesta) y Excel lo toma por texto: no podrá usarse en un cálculo.\n\nExcel ofrece una ayuda muy práctica: el relleno automático. Escribe «Enero» en una celda, selecciónala, luego agarra el pequeño cuadrado de la esquina inferior derecha de la celda (el «controlador de relleno») y arrastra hacia abajo: Excel escribe solo Febrero, Marzo, Abril… Esto también funciona con números y fechas, y ahorra mucho tiempo.",
          },
          keyPoints: {
            fr: ["Entrée valide et descend, Tab valide et va à droite", "Double-clic pour modifier une partie, Suppr pour effacer", "Nombre calé à droite, texte à gauche : repère les erreurs", "La poignée de recopie prolonge mois, dates, nombres"],
            ht: ["Entrée valide epi desann, Tab valide epi ale adwat", "Double-klike pou chanje yon pati, Suppr pou efase", "Nimewo kole adwat, tèks agoch : jwenn erè yo", "Ponyèt rekopi a kontinye mwa, dat, nimewo"],
            en: ["Enter confirms and moves down, Tab confirms and moves right", "Double-click to edit part of it, Delete to clear", "Number aligns right, text left: spot the errors", "The fill handle extends months, dates, numbers"],
            es: ["Enter confirma y baja, Tab confirma y va a la derecha", "Doble clic para modificar una parte, Supr para borrar", "Número a la derecha, texto a la izquierda: detecta errores", "El controlador de relleno extiende meses, fechas, números"],
          },
          exercise: {
            fr: "En A1 tape « Janvier », puis avec la poignée de recopie tire jusqu'en A6 pour obtenir les six premiers mois. En B1, tape 100, en B2 tape 200, sélectionne les deux et tire vers le bas : observe si Excel continue la suite. Corrige ensuite une valeur avec un double-clic.",
            ht: "Nan A1 tape « Janvier », epi ak ponyèt rekopi a rale jouk A6 pou jwenn sis premye mwa yo. Nan B1, tape 100, nan B2 tape 200, chwazi tou de epi rale desann : gade si Excel kontinye seri a. Apre sa korije yon valè ak yon double-klik.",
            en: "In A1 type \"January\", then with the fill handle drag down to A6 to get the first six months. In B1, type 100, in B2 type 200, select both and drag down: watch whether Excel continues the sequence. Then correct one value with a double-click.",
            es: "En A1 escribe «Enero», luego con el controlador de relleno arrastra hasta A6 para obtener los seis primeros meses. En B1, escribe 100, en B2 escribe 200, selecciona ambos y arrastra hacia abajo: observa si Excel continúa la serie. Luego corrige un valor con doble clic.",
          },
        },
        {
          slug: "lignes-colonnes-feuilles",
          title: { fr: "Insérer, supprimer et gérer les feuilles", ht: "Mete, efase ak jere fèy yo", en: "Inserting, deleting and managing sheets", es: "Insertar, eliminar y gestionar las hojas" },
          videoId: "",
          content: {
            fr: "Une fois un tableau commencé, tu auras souvent besoin d'ajouter une ligne oubliée ou de retirer une colonne inutile. Pour insérer une ligne, fais un clic droit sur le numéro de la ligne (à gauche) au-dessus de laquelle tu veux insérer, puis choisis « Insertion » : une ligne vide apparaît et tout le reste descend d'un cran. Pour une colonne, fais un clic droit sur la lettre de la colonne et choisis « Insertion » de la même manière.\n\nPour supprimer, même principe : clic droit sur le numéro de ligne ou la lettre de colonne, puis « Supprimer ». Attention à ne pas confondre avec la touche Suppr, qui efface seulement le contenu et laisse la ligne vide en place. « Supprimer » retire vraiment la ligne, et tout remonte.\n\nTu peux aussi élargir une colonne trop étroite : double-clique sur la ligne qui sépare deux lettres de colonnes, et la colonne s'ajuste automatiquement au contenu le plus long. Pour cacher temporairement des données, le clic droit propose aussi « Masquer ».\n\nEnfin, un même fichier Excel (un « classeur ») peut contenir plusieurs feuilles, visibles par les onglets en bas. Clique sur le petit « + » pour ajouter une feuille, double-clique sur un onglet pour le renommer (par exemple « Budget » et « Contacts »), et fais un clic droit pour changer sa couleur ou la supprimer. Séparer les données sur plusieurs feuilles garde ton classeur bien rangé.",
            ht: "Yon fwa ou kòmanse yon tablo, ou ap souvan bezwen ajoute yon liy ou bliye oswa retire yon kolòn ki initil. Pou mete yon liy, fè yon klik dwat sou nimewo liy la (agoch) anwo kote ou vle mete a, epi chwazi « Insertion » : yon liy vid parèt epi tout rès la desann yon kran. Pou yon kolòn, fè yon klik dwat sou lèt kolòn nan epi chwazi « Insertion » menm jan an.\n\nPou efase, menm prensip : klik dwat sou nimewo liy la oswa lèt kolòn nan, epi « Supprimer ». Atansyon pou pa konfonn ak bouton Suppr, ki efase sèlman kontni an epi kite liy vid la an plas. « Supprimer » retire liy la vre, epi tout remonte.\n\nOu ka elaji yon kolòn ki twò sere tou : double-klike sou liy ki separe de lèt kolòn yo, epi kolòn nan ajiste otomatikman ak kontni ki pi long lan. Pou kache done tanporèman, klik dwat la pwopoze « Masquer » tou.\n\nAnfen, yon menm fichye Excel (yon « klasè ») ka gen plizyè fèy, ki parèt ak onglè anba yo. Klike sou ti « + » a pou ajoute yon fèy, double-klike sou yon onglè pou renonmen l (pa egzanp « Budget » ak « Contacts »), epi fè yon klik dwat pou chanje koulè l oswa efase l. Separe done sou plizyè fèy kenbe klasè ou byen ranje.",
            en: "Once a table is started, you will often need to add a forgotten row or remove a useless column. To insert a row, right-click the row number (on the left) above which you want to insert, then choose \"Insert\": an empty row appears and everything else moves down one notch. For a column, right-click the column letter and choose \"Insert\" the same way.\n\nTo delete, same principle: right-click the row number or column letter, then \"Delete\". Be careful not to confuse this with the Delete key, which only clears the content and leaves the empty row in place. \"Delete\" truly removes the row, and everything moves up.\n\nYou can also widen a column that is too narrow: double-click the line that separates two column letters, and the column adjusts automatically to the longest content. To hide data temporarily, the right-click menu also offers \"Hide\".\n\nFinally, one Excel file (a \"workbook\") can contain several sheets, shown by the tabs at the bottom. Click the small \"+\" to add a sheet, double-click a tab to rename it (for example \"Budget\" and \"Contacts\"), and right-click to change its color or delete it. Splitting data across several sheets keeps your workbook well organized.",
            es: "Una vez empezada una tabla, a menudo necesitarás añadir una fila olvidada o quitar una columna inútil. Para insertar una fila, haz clic derecho en el número de la fila (a la izquierda) por encima de la cual quieres insertar, luego elige «Insertar»: aparece una fila vacía y todo lo demás baja un puesto. Para una columna, haz clic derecho en la letra de la columna y elige «Insertar» de la misma manera.\n\nPara eliminar, mismo principio: clic derecho en el número de fila o la letra de columna, luego «Eliminar». Cuidado con no confundirlo con la tecla Supr, que solo borra el contenido y deja la fila vacía en su sitio. «Eliminar» quita realmente la fila, y todo sube.\n\nTambién puedes ensanchar una columna demasiado estrecha: haz doble clic en la línea que separa dos letras de columnas, y la columna se ajusta automáticamente al contenido más largo. Para ocultar datos temporalmente, el clic derecho también ofrece «Ocultar».\n\nPor último, un mismo archivo de Excel (un «libro») puede contener varias hojas, visibles por las pestañas de abajo. Haz clic en el pequeño «+» para añadir una hoja, doble clic en una pestaña para cambiarle el nombre (por ejemplo «Presupuesto» y «Contactos»), y clic derecho para cambiar su color o eliminarla. Separar los datos en varias hojas mantiene tu libro bien organizado.",
          },
          keyPoints: {
            fr: ["Clic droit sur un numéro/lettre > Insertion pour ajouter", "Supprimer retire la ligne ; Suppr efface juste le contenu", "Double-clic entre deux lettres élargit la colonne", "Le + en bas ajoute une feuille ; double-clic pour la renommer"],
            ht: ["Klik dwat sou yon nimewo/lèt > Insertion pou ajoute", "Supprimer retire liy la ; Suppr efase sèlman kontni an", "Double-klik ant de lèt elaji kolòn nan", "+ anba a ajoute yon fèy ; double-klik pou renonmen l"],
            en: ["Right-click a number/letter > Insert to add", "Delete removes the row; the Delete key only clears content", "Double-click between two letters widens the column", "The + at the bottom adds a sheet; double-click to rename it"],
            es: ["Clic derecho en un número/letra > Insertar para añadir", "Eliminar quita la fila; Supr solo borra el contenido", "Doble clic entre dos letras ensancha la columna", "El + de abajo añade una hoja; doble clic para renombrarla"],
          },
          exercise: {
            fr: "Crée une petite liste de trois noms dans la colonne A. Insère une ligne au-dessus du deuxième nom, puis supprime-la. Ajoute ensuite une nouvelle feuille avec le bouton +, renomme-la « Contacts » et donne-lui une couleur d'onglet.",
            ht: "Kreye yon ti lis twa non nan kolòn A. Mete yon liy anwo dezyèm non an, epi efase l. Apre sa ajoute yon nouvo fèy ak bouton + a, renonmen l « Contacts » epi ba li yon koulè onglè.",
            en: "Create a small list of three names in column A. Insert a row above the second name, then delete it. Then add a new sheet with the + button, rename it \"Contacts\" and give it a tab color.",
            es: "Crea una pequeña lista de tres nombres en la columna A. Inserta una fila encima del segundo nombre, luego elimínala. Después añade una nueva hoja con el botón +, renómbrala «Contactos» y dale un color de pestaña.",
          },
        },
      ],
    },
    {
      title: { fr: "Calculer avec les formules", ht: "Kalkile ak fòmil yo", en: "Calculating with formulas", es: "Calcular con fórmulas" },
      lessons: [
        {
          slug: "premiere-formule",
          title: { fr: "Ta première formule de calcul", ht: "Premye fòmil kalkil ou", en: "Your first calculation formula", es: "Tu primera fórmula de cálculo" },
          videoId: "",
          content: {
            fr: "Le vrai pouvoir d'Excel, c'est qu'il calcule à ta place. Toute formule commence par le signe égal « = ». Dès qu'Excel voit ce signe au début d'une cellule, il comprend qu'il doit calculer au lieu d'afficher du texte. Par exemple, tape « =5+3 » dans une cellule et appuie sur Entrée : la cellule affiche 8.\n\nMais l'intérêt est d'utiliser les adresses des cellules plutôt que des nombres fixes. Si le prix est en A1 et la quantité en B1, tape « =A1*B1 » pour obtenir le total. Les opérateurs sont simples : « + » pour additionner, « - » pour soustraire, « * » pour multiplier et « / » pour diviser.\n\nUne astuce évite les fautes de frappe dans les adresses : après avoir tapé « = », clique directement sur la cellule voulue au lieu de taper son nom. Excel insère l'adresse tout seul. Tape l'opérateur, clique sur la cellule suivante, puis Entrée.\n\nL'énorme avantage, c'est que le calcul se met à jour tout seul. Si tu changes le nombre dans A1, le résultat se recalcule instantanément. C'est ce qui rend Excel si utile pour un budget : tu modifies une dépense, et le total se corrige automatiquement, sans que tu aies à recompter quoi que ce soit.",
            ht: "Vrè pouvwa Excel, se ke li kalkile nan plas ou. Tout fòmil kòmanse ak siy egal « = ». Depi Excel wè siy sa a nan kòmansman yon selil, li konprann li dwe kalkile olye pou l montre tèks. Pa egzanp, tape « =5+3 » nan yon selil epi peze Entrée : selil la montre 8.\n\nMen sa ki enteresan se sèvi ak adrès selil yo olye pou nimewo fiks. Si pri a nan A1 epi kantite a nan B1, tape « =A1*B1 » pou jwenn total la. Operatè yo senp : « + » pou adisyone, « - » pou soustrè, « * » pou miltipliye epi « / » pou divize.\n\nGen yon astis ki anpeche fot nan adrès yo : apre ou tape « = », klike dirèk sou selil ou vle a olye pou w tape non l. Excel mete adrès la pou kont li. Tape operatè a, klike sou selil ki vin apre a, epi Entrée.\n\nGwo avantaj la, se ke kalkil la mete ajou pou kont li. Si ou chanje nimewo a nan A1, rezilta a rekalkile touswit. Se sa ki fè Excel itil konsa pou yon bidjè : ou chanje yon depans, epi total la korije otomatikman, san ou pa bezwen rekonte anyen.",
            en: "The real power of Excel is that it calculates for you. Every formula begins with the equals sign \"=\". As soon as Excel sees this sign at the start of a cell, it understands it must calculate instead of showing text. For example, type \"=5+3\" in a cell and press Enter: the cell shows 8.\n\nBut the point is to use cell addresses rather than fixed numbers. If the price is in A1 and the quantity in B1, type \"=A1*B1\" to get the total. The operators are simple: \"+\" to add, \"-\" to subtract, \"*\" to multiply and \"/\" to divide.\n\nA trick avoids typing mistakes in the addresses: after typing \"=\", click directly on the cell you want instead of typing its name. Excel inserts the address by itself. Type the operator, click the next cell, then Enter.\n\nThe huge advantage is that the calculation updates by itself. If you change the number in A1, the result recalculates instantly. That is what makes Excel so useful for a budget: you change one expense, and the total corrects itself automatically, without you having to recount anything.",
            es: "El verdadero poder de Excel es que calcula por ti. Toda fórmula empieza con el signo igual «=». En cuanto Excel ve este signo al principio de una celda, entiende que debe calcular en vez de mostrar texto. Por ejemplo, escribe «=5+3» en una celda y pulsa Enter: la celda muestra 8.\n\nPero lo interesante es usar las direcciones de las celdas en lugar de números fijos. Si el precio está en A1 y la cantidad en B1, escribe «=A1*B1» para obtener el total. Los operadores son simples: «+» para sumar, «-» para restar, «*» para multiplicar y «/» para dividir.\n\nUn truco evita los errores de tecleo en las direcciones: después de escribir «=», haz clic directamente en la celda que quieras en lugar de escribir su nombre. Excel inserta la dirección solo. Escribe el operador, haz clic en la siguiente celda, luego Enter.\n\nLa enorme ventaja es que el cálculo se actualiza solo. Si cambias el número en A1, el resultado se recalcula al instante. Eso es lo que hace a Excel tan útil para un presupuesto: cambias un gasto y el total se corrige automáticamente, sin que tengas que volver a contar nada.",
          },
          keyPoints: {
            fr: ["Toute formule commence par le signe égal =", "Utiliser les adresses (=A1*B1) plutôt que des nombres fixes", "Opérateurs : + - * / ; le résultat se met à jour tout seul", "Cliquer les cellules au lieu de taper leur adresse"],
            ht: ["Tout fòmil kòmanse ak siy egal =", "Sèvi ak adrès yo (=A1*B1) olye nimewo fiks", "Operatè : + - * / ; rezilta a mete ajou pou kont li", "Klike selil yo olye tape adrès yo"],
            en: ["Every formula starts with the equals sign =", "Use addresses (=A1*B1) rather than fixed numbers", "Operators: + - * / ; the result updates by itself", "Click the cells instead of typing their address"],
            es: ["Toda fórmula empieza con el signo igual =", "Usa direcciones (=A1*B1) en vez de números fijos", "Operadores: + - * / ; el resultado se actualiza solo", "Haz clic en las celdas en vez de escribir su dirección"],
          },
          exercise: {
            fr: "En A1 tape 12 (le prix), en B1 tape 3 (la quantité). En C1, tape « = », clique sur A1, tape « * », clique sur B1, puis Entrée pour obtenir le total 36. Change ensuite le prix en A1 par 20 et observe le total se recalculer tout seul.",
            ht: "Nan A1 tape 12 (pri a), nan B1 tape 3 (kantite a). Nan C1, tape « = », klike sou A1, tape « * », klike sou B1, epi Entrée pou jwenn total 36 la. Apre sa chanje pri a nan A1 pou 20 epi gade total la rekalkile pou kont li.",
            en: "In A1 type 12 (the price), in B1 type 3 (the quantity). In C1, type \"=\", click A1, type \"*\", click B1, then Enter to get the total 36. Then change the price in A1 to 20 and watch the total recalculate by itself.",
            es: "En A1 escribe 12 (el precio), en B1 escribe 3 (la cantidad). En C1, escribe «=», haz clic en A1, escribe «*», haz clic en B1, luego Enter para obtener el total 36. Luego cambia el precio en A1 por 20 y observa el total recalcularse solo.",
          },
        },
        {
          slug: "somme-moyenne",
          title: { fr: "Les fonctions SUM et AVERAGE", ht: "Fonksyon SUM ak AVERAGE", en: "The SUM and AVERAGE functions", es: "Las funciones SUM y AVERAGE" },
          videoId: "",
          content: {
            fr: "Additionner beaucoup de cellules une par une serait fastidieux. Excel propose des « fonctions » : des formules toutes prêtes qui font le travail pour toi. La plus utilisée est SUM (SOMME dans la version française), qui additionne une série de cellules. Au lieu de « =A1+A2+A3+A4 », tu écris « =SUM(A1:A4) ». Le « deux-points » signifie « de A1 jusqu'à A4 ».\n\nLe plus simple est d'utiliser le bouton « Somme automatique » (le symbole Σ) dans l'onglet Accueil. Clique sur la cellule vide sous ta colonne de nombres, appuie sur ce bouton : Excel devine la plage à additionner et affiche le total. Vérifie la sélection proposée, puis appuie sur Entrée.\n\nLa fonction AVERAGE (MOYENNE) calcule la moyenne d'une série, très utile pour des notes ou des ventes mensuelles. Tape « =AVERAGE(B1:B10) » pour obtenir la moyenne des dix cellules. Il existe aussi MIN et MAX pour trouver la plus petite et la plus grande valeur, et COUNT pour compter le nombre de cellules qui contiennent un nombre.\n\nToutes ces fonctions suivent le même modèle : le nom, puis les cellules entre parenthèses. Tu peux aussi les recopier : sélectionne la cellule qui contient la fonction et tire la poignée de recopie vers la droite pour appliquer le même calcul à d'autres colonnes.",
            ht: "Adisyone anpil selil youn pa youn ta long anpil. Excel bay « fonksyon » yo : fòmil ki deja pare ki fè travay la pou ou. Sa yo pi sèvi a se SUM, ki adisyone yon seri selil. Olye « =A1+A2+A3+A4 », ou ekri « =SUM(A1:A4) ». « De pwen » an vle di « depi A1 jouk A4 ».\n\nPi senp la se sèvi ak bouton « Somme automatique » a (senbòl Σ) nan onglè Accueil. Klike sou selil vid ki anba kolòn nimewo ou yo, peze bouton sa a : Excel devine ki seri pou adisyone epi montre total la. Tcheke seleksyon li pwopoze a, epi peze Entrée.\n\nFonksyon AVERAGE la kalkile mwayèn yon seri, itil anpil pou nòt oswa vant chak mwa. Tape « =AVERAGE(B1:B10) » pou jwenn mwayèn dis selil yo. Gen MIN ak MAX tou pou jwenn pi piti ak pi gwo valè a, epi COUNT pou konte konbyen selil ki gen yon nimewo.\n\nTout fonksyon sa yo swiv menm modèl la : non an, epi selil yo nan parantèz. Ou ka rekopye yo tou : chwazi selil ki gen fonksyon an epi rale ponyèt rekopi a nan dwat pou aplike menm kalkil la sou lòt kolòn.",
            en: "Adding many cells one by one would be tedious. Excel offers \"functions\": ready-made formulas that do the work for you. The most used is SUM, which adds a series of cells. Instead of \"=A1+A2+A3+A4\", you write \"=SUM(A1:A4)\". The \"colon\" means \"from A1 to A4\".\n\nThe easiest way is to use the \"AutoSum\" button (the Σ symbol) in the Home tab. Click the empty cell below your column of numbers, press that button: Excel guesses the range to add and shows the total. Check the suggested selection, then press Enter.\n\nThe AVERAGE function calculates the average of a series, very useful for grades or monthly sales. Type \"=AVERAGE(B1:B10)\" to get the average of the ten cells. There are also MIN and MAX to find the smallest and largest value, and COUNT to count how many cells contain a number.\n\nAll these functions follow the same pattern: the name, then the cells in parentheses. You can also copy them: select the cell containing the function and drag the fill handle to the right to apply the same calculation to other columns.",
            es: "Sumar muchas celdas una por una sería tedioso. Excel ofrece «funciones»: fórmulas ya listas que hacen el trabajo por ti. La más usada es SUM (SUMA en la versión en español), que suma una serie de celdas. En lugar de «=A1+A2+A3+A4», escribes «=SUM(A1:A4)». Los «dos puntos» significan «desde A1 hasta A4».\n\nLo más fácil es usar el botón «Autosuma» (el símbolo Σ) en la pestaña Inicio. Haz clic en la celda vacía debajo de tu columna de números, pulsa ese botón: Excel adivina el rango que sumar y muestra el total. Comprueba la selección propuesta y luego pulsa Enter.\n\nLa función AVERAGE (PROMEDIO) calcula el promedio de una serie, muy útil para notas o ventas mensuales. Escribe «=AVERAGE(B1:B10)» para obtener el promedio de las diez celdas. También existen MIN y MAX para encontrar el valor más pequeño y el más grande, y COUNT para contar cuántas celdas contienen un número.\n\nTodas estas funciones siguen el mismo patrón: el nombre, y luego las celdas entre paréntesis. También puedes copiarlas: selecciona la celda con la función y arrastra el controlador de relleno hacia la derecha para aplicar el mismo cálculo a otras columnas.",
          },
          keyPoints: {
            fr: ["=SUM(A1:A4) additionne toute une plage de cellules", "Le bouton Σ (Somme automatique) fait le total en un clic", "=AVERAGE calcule la moyenne ; MIN, MAX et COUNT existent aussi", "Recopier une fonction avec la poignée applique le même calcul"],
            ht: ["=SUM(A1:A4) adisyone yon seri selil antye", "Bouton Σ (Somme automatique) fè total la ak yon sèl klik", "=AVERAGE kalkile mwayèn ; MIN, MAX ak COUNT egziste tou", "Rekopye yon fonksyon ak ponyèt la aplike menm kalkil la"],
            en: ["=SUM(A1:A4) adds up a whole range of cells", "The Σ (AutoSum) button totals in one click", "=AVERAGE gives the mean; MIN, MAX and COUNT also exist", "Copying a function with the handle applies the same calculation"],
            es: ["=SUM(A1:A4) suma todo un rango de celdas", "El botón Σ (Autosuma) hace el total con un clic", "=AVERAGE calcula la media; MIN, MAX y COUNT también existen", "Copiar una función con el controlador aplica el mismo cálculo"],
          },
          exercise: {
            fr: "Dans la colonne B, tape cinq notes de 0 à 20. En B6, utilise le bouton Somme automatique (Σ) pour obtenir le total. En B7, tape « =AVERAGE(B1:B5) » pour la moyenne. En B8 et B9, ajoute « =MIN(B1:B5) » et « =MAX(B1:B5) » pour la plus petite et la plus grande note.",
            ht: "Nan kolòn B, tape senk nòt ki soti 0 rive 20. Nan B6, sèvi ak bouton Somme automatique (Σ) pou jwenn total la. Nan B7, tape « =AVERAGE(B1:B5) » pou mwayèn nan. Nan B8 ak B9, ajoute « =MIN(B1:B5) » ak « =MAX(B1:B5) » pou pi piti ak pi gwo nòt la.",
            en: "In column B, type five grades from 0 to 20. In B6, use the AutoSum button (Σ) to get the total. In B7, type \"=AVERAGE(B1:B5)\" for the average. In B8 and B9, add \"=MIN(B1:B5)\" and \"=MAX(B1:B5)\" for the smallest and largest grade.",
            es: "En la columna B, escribe cinco notas de 0 a 20. En B6, usa el botón Autosuma (Σ) para obtener el total. En B7, escribe «=AVERAGE(B1:B5)» para el promedio. En B8 y B9, añade «=MIN(B1:B5)» y «=MAX(B1:B5)» para la nota más pequeña y la más grande.",
          },
        },
        {
          slug: "references-recopie-formules",
          title: { fr: "Recopier une formule et références absolues", ht: "Rekopye yon fòmil ak referans absoli", en: "Copying a formula and absolute references", es: "Copiar una fórmula y referencias absolutas" },
          videoId: "",
          content: {
            fr: "Quand tu as une formule qui fonctionne, tu n'as pas besoin de la retaper pour chaque ligne. Sélectionne la cellule qui contient la formule, attrape la poignée de recopie (le petit carré en bas à droite) et tire vers le bas : Excel copie la formule et l'adapte automatiquement à chaque ligne. Si C1 contient « =A1*B1 », alors C2 deviendra « =A2*B2 », C3 « =A3*B3 », et ainsi de suite. C'est une « référence relative » : elle se décale avec la copie.\n\nCe comportement est très pratique, mais il pose problème quand une cellule ne doit jamais changer. Imagine un taux de TVA écrit une seule fois en E1, que tu veux appliquer à toutes tes lignes. Si tu tapes « =A1*E1 » et que tu recopies, la deuxième ligne deviendra « =A2*E2 », qui pointe vers une cellule vide : le calcul est faux.\n\nLa solution est la « référence absolue » : on met un signe dollar « $ » devant la lettre et le numéro pour bloquer l'adresse. Écris « =A1*$E$1 » : en recopiant, la partie A1 se décale normalement mais $E$1 reste toujours fixée sur E1. Astuce : après avoir cliqué sur une cellule dans une formule, appuie sur la touche F4 pour ajouter les dollars automatiquement.\n\nMaîtriser la différence entre référence relative (qui bouge) et absolue (qui reste bloquée) est l'une des compétences les plus utiles d'Excel. Elle t'évite d'innombrables erreurs dès que tu recopies des formules sur beaucoup de lignes.",
            ht: "Lè ou gen yon fòmil ki mache, ou pa bezwen retape l pou chak liy. Chwazi selil ki gen fòmil la, kenbe ponyèt rekopi a (ti kare anba adwat la) epi rale desann : Excel kopye fòmil la epi adapte l otomatikman pou chak liy. Si C1 gen « =A1*B1 », lè sa a C2 ap vin « =A2*B2 », C3 « =A3*B3 », epi konsa. Se yon « referans relatif » : li dekale ak kopi a.\n\nKonpòtman sa a pratik anpil, men li fè pwoblèm lè yon selil pa dwe janm chanje. Imajine yon to TVA ki ekri yon sèl fwa nan E1, ke ou vle aplike sou tout liy ou yo. Si ou tape « =A1*E1 » epi ou rekopye, dezyèm liy la ap vin « =A2*E2 », ki pwente sou yon selil vid : kalkil la fo.\n\nSolisyon an se « referans absoli » : ou mete yon siy dola « $ » devan lèt la ak nimewo a pou bloke adrès la. Ekri « =A1*$E$1 » : lè w rekopye, pati A1 la dekale nòmalman men $E$1 rete toujou fikse sou E1. Astis : apre ou klike sou yon selil nan yon fòmil, peze bouton F4 pou ajoute dola yo otomatikman.\n\nMetrize diferans ant referans relatif (ki bouje) ak absoli (ki rete bloke) se youn nan konpetans ki pi itil nan Excel. Li anpeche ou fè yon pakèt erè depi ou rekopye fòmil sou anpil liy.",
            en: "When you have a formula that works, you don't need to retype it for every row. Select the cell containing the formula, grab the fill handle (the small square at the bottom right) and drag down: Excel copies the formula and adapts it automatically to each row. If C1 contains \"=A1*B1\", then C2 will become \"=A2*B2\", C3 \"=A3*B3\", and so on. This is a \"relative reference\": it shifts with the copy.\n\nThis behavior is very handy, but it causes a problem when a cell must never change. Imagine a VAT rate written just once in E1, which you want to apply to all your rows. If you type \"=A1*E1\" and copy it down, the second row becomes \"=A2*E2\", which points to an empty cell: the calculation is wrong.\n\nThe solution is the \"absolute reference\": you put a dollar sign \"$\" in front of the letter and the number to lock the address. Write \"=A1*$E$1\": when copied, the A1 part shifts normally but $E$1 always stays fixed on E1. Tip: after clicking a cell in a formula, press the F4 key to add the dollars automatically.\n\nMastering the difference between a relative reference (which moves) and an absolute one (which stays locked) is one of Excel's most useful skills. It saves you countless errors whenever you copy formulas across many rows.",
            es: "Cuando tienes una fórmula que funciona, no necesitas volver a escribirla para cada fila. Selecciona la celda con la fórmula, agarra el controlador de relleno (el pequeño cuadrado de la esquina inferior derecha) y arrastra hacia abajo: Excel copia la fórmula y la adapta automáticamente a cada fila. Si C1 contiene «=A1*B1», entonces C2 se convertirá en «=A2*B2», C3 en «=A3*B3», y así sucesivamente. Es una «referencia relativa»: se desplaza con la copia.\n\nEste comportamiento es muy práctico, pero causa un problema cuando una celda nunca debe cambiar. Imagina una tasa de IVA escrita una sola vez en E1, que quieres aplicar a todas tus filas. Si escribes «=A1*E1» y lo copias hacia abajo, la segunda fila se convierte en «=A2*E2», que apunta a una celda vacía: el cálculo es incorrecto.\n\nLa solución es la «referencia absoluta»: se pone un signo de dólar «$» delante de la letra y del número para bloquear la dirección. Escribe «=A1*$E$1»: al copiar, la parte A1 se desplaza normalmente pero $E$1 siempre queda fija en E1. Truco: después de hacer clic en una celda dentro de una fórmula, pulsa la tecla F4 para añadir los dólares automáticamente.\n\nDominar la diferencia entre referencia relativa (que se mueve) y absoluta (que queda bloqueada) es una de las habilidades más útiles de Excel. Te evita innumerables errores cada vez que copias fórmulas en muchas filas.",
          },
          keyPoints: {
            fr: ["La poignée de recopie adapte la formule à chaque ligne", "Référence relative (A1) : elle se décale à la copie", "Référence absolue ($E$1) : elle reste bloquée", "La touche F4 ajoute les dollars automatiquement"],
            ht: ["Ponyèt rekopi a adapte fòmil la pou chak liy", "Referans relatif (A1) : li dekale lè w kopye", "Referans absoli ($E$1) : li rete bloke", "Bouton F4 ajoute dola yo otomatikman"],
            en: ["The fill handle adapts the formula to each row", "Relative reference (A1): it shifts when copied", "Absolute reference ($E$1): it stays locked", "The F4 key adds the dollars automatically"],
            es: ["El controlador de relleno adapta la fórmula a cada fila", "Referencia relativa (A1): se desplaza al copiar", "Referencia absoluta ($E$1): queda bloqueada", "La tecla F4 añade los dólares automáticamente"],
          },
          exercise: {
            fr: "En A1 à A4, tape quatre prix. En E1, tape un taux de TVA de 0,2. En B1, tape « =A1*$E$1 » puis recopie la formule jusqu'en B4 avec la poignée. Clique sur B4 et vérifie dans la barre de formule que $E$1 est resté fixe alors que A1 est devenu A4.",
            ht: "Nan A1 rive A4, tape kat pri. Nan E1, tape yon to TVA 0,2. Nan B1, tape « =A1*$E$1 » epi rekopye fòmil la jouk B4 ak ponyèt la. Klike sou B4 epi verifye nan bar fòmil la ke $E$1 rete fiks pandan A1 vin A4.",
            en: "In A1 to A4, type four prices. In E1, type a VAT rate of 0.2. In B1, type \"=A1*$E$1\" then copy the formula down to B4 with the handle. Click B4 and check in the formula bar that $E$1 stayed fixed while A1 became A4.",
            es: "En A1 a A4, escribe cuatro precios. En E1, escribe una tasa de IVA de 0,2. En B1, escribe «=A1*$E$1» luego copia la fórmula hasta B4 con el controlador. Haz clic en B4 y comprueba en la barra de fórmulas que $E$1 quedó fijo mientras A1 se convirtió en A4.",
          },
        },
      ],
    },
    {
      title: { fr: "Organiser et présenter les données", ht: "Òganize ak prezante done yo", en: "Organizing and presenting data", es: "Organizar y presentar los datos" },
      lessons: [
        {
          slug: "mise-en-forme-tableau",
          title: { fr: "Mettre en forme un tableau", ht: "Byen ranje yon tablo", en: "Formatting a table", es: "Dar formato a una tabla" },
          videoId: "",
          content: {
            fr: "Un tableau bien présenté se lit d'un coup d'œil. Comme dans Word, l'onglet Accueil regroupe la mise en forme : sélectionne d'abord les cellules concernées, puis applique le gras, une couleur ou une taille. Mets par exemple la ligne d'en-tête (les titres de colonnes) en gras et avec une couleur de fond pour bien la distinguer du reste.\n\nLes bordures aident à séparer visuellement les cases. Sélectionne ton tableau, clique sur le bouton « Bordures » et choisis « Toutes les bordures » : chaque cellule est alors encadrée d'un trait. Pour les colonnes de sommes d'argent, le bouton format « Nombre comptabilité » ou « Monétaire » ajoute automatiquement le symbole de monnaie et deux décimales.\n\nLes formats de nombre changent l'affichage sans changer la valeur : le bouton « % » transforme 0,2 en 20 %, et les boutons « Ajouter/réduire une décimale » règlent le nombre de chiffres après la virgule. Le format « Date » affiche une date correctement quel que soit ce que tu tapes.\n\nPense aussi à ajuster la largeur des colonnes si le texte est coupé. Place la souris sur la ligne entre deux lettres de colonnes en haut : le curseur devient une double flèche. Double-clique alors pour que la colonne s'élargisse automatiquement à la taille du contenu le plus long. Ces petits réglages rendent ta feuille claire et professionnelle.",
            ht: "Yon tablo ki byen prezante li fasil. Menm jan ak nan Word, onglè Accueil gwoupe mizanfòm : chwazi selil yo anvan, epi aplike gra, yon koulè oswa yon gwosè. Mete pa egzanp liy tèt la (tit kolòn yo) an gra epi ak yon koulè fon pou l byen diferan de rès la.\n\nBòdi yo ede separe kaz yo pou je. Chwazi tablo ou, klike sou bouton « Bordures » epi chwazi « Toutes les bordures » : chak selil vin gen yon trè otou l. Pou kolòn kòb yo, bouton fòma « Nombre comptabilité » oswa « Monétaire » ajoute otomatikman senbòl lajan an ak de desimal.\n\nFòma nimewo yo chanje afichaj la san chanje valè a : bouton « % » a transfòme 0,2 an 20 %, epi bouton « Ajoute/redui yon desimal » regle konbyen chif apre vigil la. Fòma « Date » a montre yon dat kòrèkteman kèlkeswa sa ou tape.\n\nSonje ajiste lajè kolòn yo tou si tèks la koupe. Mete sourit la sou liy ki ant de lèt kolòn anwo a : kurseur a vin yon doub flèch. Double-klike lè sa a pou kolòn nan vin laj otomatikman jouk gwosè kontni ki pi long lan. Ti reglaj sa yo fè fèy ou klè epi pwofesyonèl.",
            en: "A well-presented table can be read at a glance. As in Word, the Home tab groups the formatting: first select the cells you want, then apply bold, a color or a size. For example, make the header row (the column titles) bold and give it a background color to set it apart from the rest.\n\nBorders help visually separate the boxes. Select your table, click the \"Borders\" button and choose \"All Borders\": each cell is then outlined with a line. For columns of money amounts, the \"Accounting\" or \"Currency\" number format automatically adds the currency symbol and two decimals.\n\nNumber formats change the display without changing the value: the \"%\" button turns 0.2 into 20%, and the \"Increase/Decrease Decimal\" buttons set the number of digits after the decimal point. The \"Date\" format shows a date correctly regardless of what you type.\n\nAlso remember to adjust the column width if text is cut off. Place the mouse on the line between two column letters at the top: the cursor becomes a double arrow. Double-click then so the column automatically widens to fit the longest content. These small adjustments make your sheet clear and professional.",
            es: "Una tabla bien presentada se lee de un vistazo. Como en Word, la pestaña Inicio agrupa el formato: selecciona primero las celdas que quieras y luego aplica la negrita, un color o un tamaño. Pon por ejemplo la fila de encabezado (los títulos de las columnas) en negrita y con un color de fondo para distinguirla bien del resto.\n\nLos bordes ayudan a separar visualmente las casillas. Selecciona tu tabla, haz clic en el botón «Bordes» y elige «Todos los bordes»: cada celda queda enmarcada con una línea. Para las columnas de importes de dinero, el formato de número «Contabilidad» o «Moneda» añade automáticamente el símbolo de la moneda y dos decimales.\n\nLos formatos de número cambian la visualización sin cambiar el valor: el botón «%» convierte 0,2 en 20 %, y los botones «Aumentar/disminuir decimales» ajustan la cantidad de cifras tras la coma. El formato «Fecha» muestra una fecha correctamente sin importar lo que escribas.\n\nAcuérdate también de ajustar el ancho de las columnas si el texto se corta. Coloca el ratón sobre la línea entre dos letras de columnas arriba: el cursor se convierte en una doble flecha. Haz doble clic entonces para que la columna se ensanche automáticamente al tamaño del contenido más largo. Estos pequeños ajustes hacen tu hoja clara y profesional.",
          },
          keyPoints: {
            fr: ["En-tête en gras + couleur de fond pour le distinguer", "Bordures : « Toutes les bordures » encadre chaque cellule", "Formats Monétaire, % et décimales changent l'affichage", "Double-clic entre deux colonnes pour ajuster la largeur"],
            ht: ["Tèt la an gra + koulè fon pou diferansye l", "Bòdi : « Toutes les bordures » ankadre chak selil", "Fòma Monétaire, % ak desimal chanje afichaj la", "Double-klike ant de kolòn pou ajiste lajè a"],
            en: ["Header in bold + background color to set it apart", "Borders: \"All Borders\" outlines every cell", "Currency, % and decimal formats change the display", "Double-click between two columns to adjust the width"],
            es: ["Encabezado en negrita + color de fondo para distinguirlo", "Bordes: «Todos los bordes» enmarca cada celda", "Formatos Moneda, % y decimales cambian la visualización", "Doble clic entre dos columnas para ajustar el ancho"],
          },
          exercise: {
            fr: "Crée un petit tableau de dépenses avec les colonnes « Article » et « Montant » et quatre lignes. Mets l'en-tête en gras avec un fond gris, ajoute « Toutes les bordures », et applique le format Monétaire à la colonne des montants. Élargis enfin la colonne Article par un double-clic.",
            ht: "Kreye yon ti tablo depans ak kolòn « Atik » ak « Montan » epi kat liy. Mete tèt la an gra ak yon fon gri, ajoute « Toutes les bordures », epi aplike fòma Monétaire sou kolòn montan yo. Anfen elaji kolòn Atik la ak yon double-klik.",
            en: "Create a small expense table with the columns \"Item\" and \"Amount\" and four rows. Make the header bold with a gray background, add \"All Borders\", and apply the Currency format to the amount column. Finally widen the Item column with a double-click.",
            es: "Crea una pequeña tabla de gastos con las columnas «Artículo» e «Importe» y cuatro filas. Pon el encabezado en negrita con un fondo gris, añade «Todos los bordes», y aplica el formato Moneda a la columna de importes. Por último, ensancha la columna Artículo con un doble clic.",
          },
        },
        {
          slug: "trier-filtrer",
          title: { fr: "Trier et filtrer les données", ht: "Triye ak filtre done yo", en: "Sorting and filtering data", es: "Ordenar y filtrar los datos" },
          videoId: "",
          content: {
            fr: "Quand une liste devient longue, trier et filtrer aide à s'y retrouver. Trier, c'est ranger les lignes dans un ordre : par ordre alphabétique pour des noms, ou du plus petit au plus grand pour des nombres. Clique sur une cellule de la colonne à trier, va dans l'onglet « Données » et clique sur « Trier de A à Z » (croissant) ou « Trier de Z à A » (décroissant). Excel réorganise toutes les lignes en gardant chaque ligne cohérente.\n\nAttention : ne sélectionne pas seulement une colonne avant de trier, sinon tu risques de mélanger les données. Clique simplement sur une seule cellule de la colonne, et Excel comprend qu'il doit trier tout le tableau ensemble.\n\nFiltrer, c'est n'afficher que les lignes qui t'intéressent, en cachant temporairement les autres. Clique sur une cellule du tableau, puis sur « Filtrer » dans l'onglet Données : de petites flèches apparaissent en haut de chaque colonne. Clique sur la flèche d'une colonne pour choisir ce que tu veux voir, par exemple seulement la ville « Port-au-Prince » ou seulement les montants supérieurs à 100.\n\nLes lignes qui ne correspondent pas sont masquées, mais rien n'est supprimé : décoche le filtre ou clique sur « Effacer » pour tout réafficher. Trier et filtrer sont parfaits pour analyser une liste de ventes, de contacts ou de stock sans jamais perdre de données.",
            ht: "Lè yon lis vin long, triye ak filtre ede ou jwenn wout ou. Triye vle di ranje liy yo nan yon lòd : nan lòd alfabetik pou non, oswa depi pi piti rive pi gwo pou nimewo. Klike sou yon selil nan kolòn pou triye a, ale nan onglè « Données » epi klike sou « Trier de A à Z » (kwasan) oswa « Trier de Z à A » (dekwasan). Excel reòganize tout liy yo epi kenbe chak liy koyeran.\n\nAtansyon : pa chwazi sèlman yon kolòn anvan ou triye, sinon ou riske melanje done yo. Klike senpleman sou yon sèl selil nan kolòn nan, epi Excel konprann li dwe triye tout tablo a ansanm.\n\nFiltre vle di montre sèlman liy ki enterese ou yo, epi kache lòt yo tanporèman. Klike sou yon selil nan tablo a, epi sou « Filtrer » nan onglè Données : ti flèch parèt anwo chak kolòn. Klike sou flèch yon kolòn pou chwazi sa ou vle wè a, pa egzanp sèlman vil « Port-au-Prince » oswa sèlman montan ki pi gwo pase 100.\n\nLiy ki pa koresponn yo kache, men anyen pa efase : dekoche filtè a oswa klike sou « Effacer » pou remontre tout. Triye ak filtre pafè pou analize yon lis vant, kontak oswa stòk san ou pa janm pèdi done.",
            en: "When a list gets long, sorting and filtering help you find your way. Sorting means arranging the rows in an order: alphabetically for names, or from smallest to largest for numbers. Click a cell in the column to sort, go to the \"Data\" tab and click \"Sort A to Z\" (ascending) or \"Sort Z to A\" (descending). Excel reorganizes all the rows while keeping each row consistent.\n\nBe careful: do not select only one column before sorting, or you risk scrambling the data. Simply click a single cell in the column, and Excel understands it must sort the whole table together.\n\nFiltering means showing only the rows you care about, temporarily hiding the others. Click a cell in the table, then \"Filter\" in the Data tab: small arrows appear at the top of each column. Click a column's arrow to choose what you want to see, for example only the city \"Port-au-Prince\" or only amounts above 100.\n\nThe rows that don't match are hidden, but nothing is deleted: uncheck the filter or click \"Clear\" to show everything again. Sorting and filtering are perfect for analyzing a list of sales, contacts or stock without ever losing data.",
            es: "Cuando una lista se hace larga, ordenar y filtrar ayuda a orientarse. Ordenar es colocar las filas en un orden: alfabéticamente para nombres, o de menor a mayor para números. Haz clic en una celda de la columna que ordenar, ve a la pestaña «Datos» y haz clic en «Ordenar de A a Z» (ascendente) u «Ordenar de Z a A» (descendente). Excel reorganiza todas las filas manteniendo cada fila coherente.\n\nCuidado: no selecciones solo una columna antes de ordenar, o corres el riesgo de mezclar los datos. Simplemente haz clic en una sola celda de la columna, y Excel entiende que debe ordenar toda la tabla junta.\n\nFiltrar es mostrar solo las filas que te interesan, ocultando temporalmente las demás. Haz clic en una celda de la tabla, luego en «Filtrar» en la pestaña Datos: aparecen pequeñas flechas en la parte superior de cada columna. Haz clic en la flecha de una columna para elegir lo que quieres ver, por ejemplo solo la ciudad «Puerto Príncipe» o solo los importes superiores a 100.\n\nLas filas que no coinciden quedan ocultas, pero nada se elimina: desmarca el filtro o haz clic en «Borrar» para volver a mostrar todo. Ordenar y filtrar son perfectos para analizar una lista de ventas, contactos o inventario sin perder nunca datos.",
          },
          keyPoints: {
            fr: ["Cliquer une seule cellule avant de trier, pas toute la colonne", "Données > Trier A-Z (croissant) ou Z-A (décroissant)", "Filtrer affiche les flèches ; choisir ce qu'on veut voir", "Le filtre masque sans supprimer ; « Effacer » réaffiche tout"],
            ht: ["Klike yon sèl selil anvan ou triye, pa tout kolòn nan", "Données > Trier A-Z (kwasan) oswa Z-A (dekwasan)", "Filtre montre flèch yo ; chwazi sa ou vle wè", "Filtè a kache san efase ; « Effacer » remontre tout"],
            en: ["Click a single cell before sorting, not the whole column", "Data > Sort A-Z (ascending) or Z-A (descending)", "Filter shows the arrows; choose what you want to see", "The filter hides without deleting; \"Clear\" shows all again"],
            es: ["Haz clic en una sola celda antes de ordenar, no toda la columna", "Datos > Ordenar A-Z (ascendente) o Z-A (descendente)", "Filtrar muestra las flechas; elige lo que quieres ver", "El filtro oculta sin eliminar; «Borrar» muestra todo de nuevo"],
          },
          exercise: {
            fr: "Crée un tableau de six lignes avec les colonnes « Nom », « Ville » et « Montant ». Trie-le par Montant du plus grand au plus petit. Active ensuite le filtre et affiche uniquement une ville de ton choix, puis efface le filtre pour tout revoir.",
            ht: "Kreye yon tablo sis liy ak kolòn « Nom », « Ville » ak « Montant ». Triye l pa Montant depi pi gwo rive pi piti. Apre sa aktive filtè a epi montre sèlman yon vil ou chwazi, epi efase filtè a pou revwa tout.",
            en: "Create a six-row table with the columns \"Name\", \"City\" and \"Amount\". Sort it by Amount from largest to smallest. Then turn on the filter and show only one city of your choice, then clear the filter to see everything again.",
            es: "Crea una tabla de seis filas con las columnas «Nombre», «Ciudad» e «Importe». Ordénala por Importe de mayor a menor. Luego activa el filtro y muestra solo una ciudad de tu elección, después borra el filtro para volver a ver todo.",
          },
        },
        {
          slug: "mise-en-forme-conditionnelle",
          title: { fr: "La mise en forme conditionnelle", ht: "Mizanfòm kondisyonèl la", en: "Conditional formatting", es: "El formato condicional" },
          videoId: "",
          content: {
            fr: "La mise en forme conditionnelle colore automatiquement les cellules selon leur valeur. C'est un moyen puissant de faire ressortir les informations importantes sans les chercher une par une : les mauvaises notes en rouge, les gros montants en vert, les stocks bas en orange. Excel applique la couleur tout seul et la met à jour si la valeur change.\n\nSélectionne d'abord la plage de cellules concernée, par exemple une colonne de notes. Va dans l'onglet « Accueil » et clique sur « Mise en forme conditionnelle ». Le sous-menu « Règles de mise en surbrillance des cellules » propose des conditions simples : « Inférieur à… », « Supérieur à… », « Égal à… ». Choisis par exemple « Inférieur à », tape 10, et sélectionne un remplissage rouge : toutes les notes en dessous de 10 deviennent rouges instantanément.\n\nD'autres options visuelles existent. Les « Barres de données » dessinent une petite barre colorée dans chaque cellule, proportionnelle à sa valeur, comme un mini-graphique. Les « Nuances de couleurs » vont du rouge au vert selon que la valeur est basse ou haute, et les « Jeux d'icônes » ajoutent des flèches ou des feux tricolores.\n\nSi tu veux enlever ces couleurs, retourne dans « Mise en forme conditionnelle », choisis « Effacer les règles », et sélectionne « Effacer les règles des cellules sélectionnées ». La mise en forme conditionnelle transforme un tableau de chiffres en un tableau de bord facile à lire d'un seul regard.",
            ht: "Mizanfòm kondisyonèl la kolore selil yo otomatikman selon valè yo. Se yon mwayen pwisan pou fè enfòmasyon enpòtan yo parèt san chèche yo youn pa youn : move nòt an wouj, gwo montan an vèt, stòk ki ba an zoranj. Excel aplike koulè a pou kont li epi mete l ajou si valè a chanje.\n\nChwazi plaj selil ki konsène a anvan, pa egzanp yon kolòn nòt. Ale nan onglè « Accueil » epi klike sou « Mise en forme conditionnelle ». Sou-meni « Règles de mise en surbrillance des cellules » a pwopoze kondisyon senp : « Inférieur à… », « Supérieur à… », « Égal à… ». Chwazi pa egzanp « Inférieur à », tape 10, epi chwazi yon ranplisaj wouj : tout nòt ki anba 10 vin wouj touswit.\n\nGen lòt opsyon vizyèl. « Barres de données » yo desine yon ti bar ki gen koulè nan chak selil, pwopòsyonèl ak valè li, tankou yon mini-grafik. « Nuances de couleurs » yo soti wouj rive vèt selon si valè a ba oswa wo, epi « Jeux d'icônes » ajoute flèch oswa fe tricolò.\n\nSi ou vle retire koulè sa yo, retounen nan « Mise en forme conditionnelle », chwazi « Effacer les règles », epi chwazi « Effacer les règles des cellules sélectionnées ». Mizanfòm kondisyonèl la transfòme yon tablo chif an yon tablodbò fasil pou li ak yon sèl kout je.",
            en: "Conditional formatting automatically colors cells according to their value. It is a powerful way to make important information stand out without searching one by one: bad grades in red, large amounts in green, low stock in orange. Excel applies the color by itself and updates it if the value changes.\n\nFirst select the range of cells concerned, for example a column of grades. Go to the \"Home\" tab and click \"Conditional Formatting\". The \"Highlight Cells Rules\" submenu offers simple conditions: \"Less Than…\", \"Greater Than…\", \"Equal To…\". Choose for example \"Less Than\", type 10, and select a red fill: all grades below 10 turn red instantly.\n\nOther visual options exist. \"Data Bars\" draw a small colored bar in each cell, proportional to its value, like a mini chart. \"Color Scales\" go from red to green depending on whether the value is low or high, and \"Icon Sets\" add arrows or traffic lights.\n\nIf you want to remove these colors, go back to \"Conditional Formatting\", choose \"Clear Rules\", and select \"Clear Rules from Selected Cells\". Conditional formatting turns a table of numbers into a dashboard that is easy to read at a single glance.",
            es: "El formato condicional colorea automáticamente las celdas según su valor. Es una forma potente de hacer resaltar la información importante sin buscarla una por una: las malas notas en rojo, los importes grandes en verde, el stock bajo en naranja. Excel aplica el color solo y lo actualiza si el valor cambia.\n\nSelecciona primero el rango de celdas correspondiente, por ejemplo una columna de notas. Ve a la pestaña «Inicio» y haz clic en «Formato condicional». El submenú «Reglas para resaltar celdas» ofrece condiciones simples: «Es menor que…», «Es mayor que…», «Es igual a…». Elige por ejemplo «Es menor que», escribe 10, y selecciona un relleno rojo: todas las notas por debajo de 10 se vuelven rojas al instante.\n\nExisten otras opciones visuales. Las «Barras de datos» dibujan una pequeña barra de color en cada celda, proporcional a su valor, como un minigráfico. Las «Escalas de color» van del rojo al verde según si el valor es bajo o alto, y los «Conjuntos de iconos» añaden flechas o semáforos.\n\nSi quieres quitar estos colores, vuelve a «Formato condicional», elige «Borrar reglas», y selecciona «Borrar reglas de las celdas seleccionadas». El formato condicional convierte una tabla de números en un panel fácil de leer de un solo vistazo.",
          },
          keyPoints: {
            fr: ["Colore automatiquement les cellules selon leur valeur", "Accueil > Mise en forme conditionnelle > règles (Inférieur à…)", "Barres de données, nuances de couleurs et jeux d'icônes", "Effacer les règles pour retirer les couleurs"],
            ht: ["Kolore selil yo otomatikman selon valè yo", "Accueil > Mise en forme conditionnelle > règ (Inférieur à…)", "Barres de données, nuances de couleurs ak jeux d'icônes", "Effacer les règles pou retire koulè yo"],
            en: ["Automatically colors cells according to their value", "Home > Conditional Formatting > rules (Less Than…)", "Data bars, color scales and icon sets", "Clear Rules to remove the colors"],
            es: ["Colorea automáticamente las celdas según su valor", "Inicio > Formato condicional > reglas (Es menor que…)", "Barras de datos, escalas de color y conjuntos de iconos", "Borrar reglas para quitar los colores"],
          },
          exercise: {
            fr: "Tape une colonne de huit notes de 0 à 20. Sélectionne-la et applique une mise en forme conditionnelle « Inférieur à » 10 avec un remplissage rouge. Ajoute ensuite des « Barres de données » sur la même colonne, puis change une note pour voir la couleur se mettre à jour.",
            ht: "Tape yon kolòn uit nòt ki soti 0 rive 20. Chwazi l epi aplike yon mizanfòm kondisyonèl « Inférieur à » 10 ak yon ranplisaj wouj. Apre sa ajoute « Barres de données » sou menm kolòn nan, epi chanje yon nòt pou wè koulè a mete ajou.",
            en: "Type a column of eight grades from 0 to 20. Select it and apply conditional formatting \"Less Than\" 10 with a red fill. Then add \"Data Bars\" to the same column, then change a grade to see the color update.",
            es: "Escribe una columna de ocho notas de 0 a 20. Selecciónala y aplica un formato condicional «Es menor que» 10 con un relleno rojo. Luego añade «Barras de datos» a la misma columna, después cambia una nota para ver el color actualizarse.",
          },
        },
      ],
    },
    {
      title: { fr: "Visualiser, tableaux et impression", ht: "Vizyalize, tablo ak enprime", en: "Visualizing, tables and printing", es: "Visualizar, tablas e impresión" },
      lessons: [
        {
          slug: "creer-graphique",
          title: { fr: "Créer un graphique", ht: "Kreye yon grafik", en: "Creating a chart", es: "Crear un gráfico" },
          videoId: "",
          content: {
            fr: "Un graphique transforme des chiffres en image : on comprend d'un coup d'œil une tendance qu'un tableau ne montre pas aussi vite. Excel crée un graphique automatiquement à partir de tes données ; tu n'as rien à dessiner toi-même.\n\nCommence par sélectionner les données à représenter, en incluant les étiquettes. Par exemple, sélectionne la colonne des mois et la colonne des ventes correspondantes. Va ensuite dans l'onglet « Insertion », dans la zone « Graphiques », et choisis un type : l'histogramme (barres verticales) est idéal pour comparer des valeurs, la courbe pour montrer une évolution dans le temps, et le camembert (secteurs) pour montrer des parts d'un tout, comme la répartition d'un budget.\n\nUne fois inséré, le graphique s'affiche sur ta feuille. Clique dessus pour le déplacer, ou tire un coin pour l'agrandir. Deux onglets « Création de graphique » et « Format » apparaissent : ils permettent d'ajouter un titre clair, d'afficher les valeurs sur les barres, ou de changer les couleurs d'un clic.\n\nUn atout très pratique : si tu modifies un chiffre dans le tableau, le graphique se met à jour tout seul. C'est l'outil parfait pour présenter des résultats de façon convaincante dans un rapport ou une réunion.",
            ht: "Yon grafik transfòme chif an imaj : ou konprann ak yon sèl kout je yon tandans yon tablo pa montre osi vit. Excel kreye yon grafik otomatikman apati done ou yo ; ou pa gen anyen pou desine tèt ou.\n\nKòmanse pa chwazi done pou reprezante yo, ansanm ak etikèt yo. Pa egzanp, chwazi kolòn mwa yo ak kolòn vant ki koresponn yo. Apre sa ale nan onglè « Insertion », nan zòn « Graphiques » lan, epi chwazi yon tip : istogram (bar vètikal) ideyal pou konpare valè, koub la pou montre yon evolisyon nan tan, epi kamanbè (sektè) pou montre pòsyon nan yon antye, tankou repartisyon yon bidjè.\n\nYon fwa li antre, grafik la parèt sou fèy ou. Klike sou li pou deplase l, oswa rale yon kwen pou agrandi l. De onglè « Création de graphique » ak « Format » parèt : yo pèmèt ajoute yon tit klè, montre valè yo sou bar yo, oswa chanje koulè ak yon klik.\n\nYon avantaj trè pratik : si ou chanje yon chif nan tablo a, grafik la mete ajou pou kont li. Se zouti pafè pou prezante rezilta yon fason konvenkan nan yon rapò oswa yon reyinyon.",
            en: "A chart turns numbers into a picture: you grasp at a glance a trend that a table does not show as quickly. Excel creates a chart automatically from your data; you don't have to draw anything yourself.\n\nStart by selecting the data to display, including the labels. For example, select the column of months and the column of matching sales. Then go to the \"Insert\" tab, into the \"Charts\" area, and choose a type: the column chart (vertical bars) is ideal for comparing values, the line chart for showing change over time, and the pie chart for showing parts of a whole, like the breakdown of a budget.\n\nOnce inserted, the chart appears on your sheet. Click it to move it, or drag a corner to enlarge it. Two tabs \"Chart Design\" and \"Format\" appear: they let you add a clear title, show the values on the bars, or change the colors with a click.\n\nA very handy benefit: if you change a number in the table, the chart updates by itself. It is the perfect tool to present results in a convincing way in a report or a meeting.",
            es: "Un gráfico convierte los números en una imagen: se entiende de un vistazo una tendencia que una tabla no muestra tan rápido. Excel crea un gráfico automáticamente a partir de tus datos; no tienes que dibujar nada tú mismo.\n\nEmpieza seleccionando los datos que representar, incluyendo las etiquetas. Por ejemplo, selecciona la columna de los meses y la columna de las ventas correspondientes. Luego ve a la pestaña «Insertar», a la zona «Gráficos», y elige un tipo: el gráfico de columnas (barras verticales) es ideal para comparar valores, el de líneas para mostrar una evolución en el tiempo, y el circular (sectores) para mostrar partes de un todo, como el reparto de un presupuesto.\n\nUna vez insertado, el gráfico aparece en tu hoja. Haz clic en él para moverlo, o arrastra una esquina para agrandarlo. Aparecen dos pestañas «Diseño de gráfico» y «Formato»: permiten añadir un título claro, mostrar los valores sobre las barras, o cambiar los colores con un clic.\n\nUna ventaja muy práctica: si cambias un número en la tabla, el gráfico se actualiza solo. Es la herramienta perfecta para presentar resultados de forma convincente en un informe o una reunión.",
          },
          keyPoints: {
            fr: ["Sélectionner les données (avec étiquettes) avant d'insérer", "Insertion > Graphiques : barres, courbe ou camembert selon le besoin", "Les onglets Création/Format ajoutent titre, valeurs et couleurs", "Le graphique se met à jour quand les données changent"],
            ht: ["Chwazi done yo (ak etikèt) anvan ou insere", "Insertion > Graphiques : bar, koub oswa kamanbè selon bezwen", "Onglè Création/Format ajoute tit, valè ak koulè", "Grafik la mete ajou lè done yo chanje"],
            en: ["Select the data (with labels) before inserting", "Insert > Charts: bars, line or pie depending on the need", "The Design/Format tabs add title, values and colors", "The chart updates when the data changes"],
            es: ["Selecciona los datos (con etiquetas) antes de insertar", "Insertar > Gráficos: barras, líneas o circular según la necesidad", "Las pestañas Diseño/Formato añaden título, valores y colores", "El gráfico se actualiza cuando cambian los datos"],
          },
          exercise: {
            fr: "Crée un tableau avec les six premiers mois en colonne A et des ventes en colonne B. Sélectionne les deux colonnes, insère un histogramme, puis ajoute-lui le titre « Ventes du semestre ». Change enfin une valeur de ventes et observe la barre correspondante se redimensionner.",
            ht: "Kreye yon tablo ak sis premye mwa yo nan kolòn A ak vant nan kolòn B. Chwazi de kolòn yo, mete yon istogram, epi ajoute l tit « Vant semès la ». Anfen chanje yon valè vant epi gade bar ki koresponn lan chanje gwosè.",
            en: "Create a table with the first six months in column A and sales in column B. Select both columns, insert a column chart, then add the title \"Half-year sales\". Finally change one sales value and watch the matching bar resize.",
            es: "Crea una tabla con los seis primeros meses en la columna A y ventas en la columna B. Selecciona ambas columnas, inserta un gráfico de columnas, luego añádele el título «Ventas del semestre». Por último, cambia un valor de ventas y observa la barra correspondiente cambiar de tamaño.",
          },
        },
        {
          slug: "tableau-excel-structure",
          title: { fr: "Mettre les données en tableau structuré", ht: "Mete done yo an tablo estriktire", en: "Turning data into a structured table", es: "Convertir los datos en tabla estructurada" },
          videoId: "",
          content: {
            fr: "Au-delà d'une simple mise en forme, Excel propose une vraie fonction « Tableau » qui transforme une plage de données en un objet intelligent. Sélectionne n'importe quelle cellule de tes données, va dans l'onglet « Insertion » et clique sur « Tableau » (ou utilise le raccourci Ctrl+L). Excel détecte automatiquement l'étendue de tes données ; vérifie que la case « Mon tableau comporte des en-têtes » est cochée, puis valide.\n\nTa plage devient aussitôt un tableau coloré, avec des lignes alternées pour la lisibilité et des flèches de filtre déjà présentes sur chaque en-tête. Un nouvel onglet « Création de tableau » apparaît, où tu peux changer le style de couleurs d'un clic.\n\nL'avantage principal, c'est que le tableau grandit tout seul. Si tu tapes une nouvelle ligne juste en dessous, elle est automatiquement intégrée au tableau avec la même mise en forme. Coche aussi « Ligne des totaux » dans l'onglet Création : une ligne apparaît en bas et te propose, via un menu déroulant, de calculer la somme ou la moyenne de chaque colonne sans écrire de formule.\n\nLes tableaux structurés rendent tes données plus faciles à trier, filtrer et calculer, et évitent beaucoup d'erreurs quand ta liste s'allonge. C'est la façon professionnelle d'organiser une liste de ventes, de membres ou de produits dans Excel.",
            ht: "Pi lwen pase yon senp mizanfòm, Excel pwopoze yon vrè fonksyon « Tableau » ki transfòme yon plaj done an yon objè entèlijan. Chwazi nenpòt selil nan done ou yo, ale nan onglè « Insertion » epi klike sou « Tableau » (oswa sèvi ak rakoursi Ctrl+L). Excel detekte otomatikman etandue done ou yo ; verifye ke kaz « Mon tableau comporte des en-têtes » a koche, epi valide.\n\nPlaj ou a vin touswit yon tablo ki gen koulè, ak liy ki altène pou lizibilite epi flèch filtè ki deja sou chak tèt. Yon nouvo onglè « Création de tableau » parèt, kote ou ka chanje style koulè a ak yon klik.\n\nPrensipal avantaj la, se ke tablo a grandi pou kont li. Si ou tape yon nouvo liy jis anba a, li otomatikman entegre nan tablo a ak menm mizanfòm nan. Koche « Ligne des totaux » tou nan onglè Création : yon liy parèt anba epi pwopoze ou, ak yon meni dewoulan, kalkile som oswa mwayèn chak kolòn san ekri fòmil.\n\nTablo estriktire yo fè done ou pi fasil pou triye, filtre ak kalkile, epi evite anpil erè lè lis ou a vin pi long. Se fason pwofesyonèl pou òganize yon lis vant, manm oswa pwodwi nan Excel.",
            en: "Beyond simple formatting, Excel offers a real \"Table\" feature that turns a range of data into a smart object. Select any cell in your data, go to the \"Insert\" tab and click \"Table\" (or use the shortcut Ctrl+L). Excel automatically detects the extent of your data; make sure the \"My table has headers\" box is checked, then confirm.\n\nYour range immediately becomes a colored table, with alternating rows for readability and filter arrows already present on each header. A new \"Table Design\" tab appears, where you can change the color style with one click.\n\nThe main advantage is that the table grows on its own. If you type a new row just below, it is automatically included in the table with the same formatting. Also check \"Total Row\" in the Design tab: a row appears at the bottom and offers, through a drop-down menu, to calculate the sum or average of each column without writing a formula.\n\nStructured tables make your data easier to sort, filter and calculate, and prevent many errors as your list grows. It is the professional way to organize a list of sales, members or products in Excel.",
            es: "Más allá del simple formato, Excel ofrece una verdadera función «Tabla» que convierte un rango de datos en un objeto inteligente. Selecciona cualquier celda de tus datos, ve a la pestaña «Insertar» y haz clic en «Tabla» (o usa el atajo Ctrl+L). Excel detecta automáticamente la extensión de tus datos; asegúrate de que la casilla «La tabla tiene encabezados» esté marcada, luego confirma.\n\nTu rango se convierte de inmediato en una tabla con color, con filas alternas para la legibilidad y flechas de filtro ya presentes en cada encabezado. Aparece una nueva pestaña «Diseño de tabla», donde puedes cambiar el estilo de colores con un clic.\n\nLa ventaja principal es que la tabla crece sola. Si escribes una nueva fila justo debajo, se integra automáticamente en la tabla con el mismo formato. Marca también «Fila de totales» en la pestaña Diseño: aparece una fila abajo y te ofrece, mediante un menú desplegable, calcular la suma o el promedio de cada columna sin escribir una fórmula.\n\nLas tablas estructuradas hacen que tus datos sean más fáciles de ordenar, filtrar y calcular, y evitan muchos errores cuando tu lista se alarga. Es la forma profesional de organizar una lista de ventas, miembros o productos en Excel.",
          },
          keyPoints: {
            fr: ["Insertion > Tableau (ou Ctrl+L) crée un tableau intelligent", "Cocher « Mon tableau comporte des en-têtes »", "Le tableau grandit tout seul avec les nouvelles lignes", "La ligne des totaux calcule somme/moyenne sans formule"],
            ht: ["Insertion > Tableau (oswa Ctrl+L) kreye yon tablo entèlijan", "Koche « Mon tableau comporte des en-têtes »", "Tablo a grandi pou kont li ak nouvo liy yo", "Liy total la kalkile som/mwayèn san fòmil"],
            en: ["Insert > Table (or Ctrl+L) creates a smart table", "Check \"My table has headers\"", "The table grows on its own with new rows", "The total row calculates sum/average without a formula"],
            es: ["Insertar > Tabla (o Ctrl+L) crea una tabla inteligente", "Marca «La tabla tiene encabezados»", "La tabla crece sola con las nuevas filas", "La fila de totales calcula suma/promedio sin fórmula"],
          },
          exercise: {
            fr: "Saisis une liste de cinq produits avec les colonnes « Produit », « Quantité » et « Prix ». Clique dans les données et appuie sur Ctrl+L pour créer un tableau. Choisis un style de couleur, ajoute une ligne de totaux et affiche la somme de la colonne Prix. Tape enfin un sixième produit sous le tableau et vérifie qu'il s'y intègre.",
            ht: "Antre yon lis senk pwodwi ak kolòn « Produit », « Quantité » ak « Prix ». Klike nan done yo epi peze Ctrl+L pou kreye yon tablo. Chwazi yon style koulè, ajoute yon liy total epi montre som kolòn Prix la. Anfen tape yon sizyèm pwodwi anba tablo a epi verifye li entegre ladan.",
            en: "Enter a list of five products with the columns \"Product\", \"Quantity\" and \"Price\". Click in the data and press Ctrl+L to create a table. Choose a color style, add a total row and show the sum of the Price column. Finally type a sixth product below the table and check that it gets included.",
            es: "Introduce una lista de cinco productos con las columnas «Producto», «Cantidad» y «Precio». Haz clic en los datos y pulsa Ctrl+L para crear una tabla. Elige un estilo de color, añade una fila de totales y muestra la suma de la columna Precio. Por último, escribe un sexto producto debajo de la tabla y comprueba que se integra en ella.",
          },
        },
        {
          slug: "figer-volets-imprimer",
          title: { fr: "Figer les volets et imprimer", ht: "Fige volè yo ak enprime", en: "Freezing panes and printing", es: "Inmovilizar paneles e imprimir" },
          videoId: "",
          content: {
            fr: "Quand un tableau devient long, on perd de vue les titres des colonnes dès qu'on descend. La solution est de « figer les volets » : garder la première ligne visible en permanence, même en faisant défiler. Va dans l'onglet « Affichage », clique sur « Figer les volets » et choisis « Figer la ligne supérieure ». La ligne d'en-tête reste alors collée en haut pendant que le reste défile.\n\nTu peux aussi « Figer la première colonne » pour garder les noms visibles à gauche, ou sélectionner une cellule et choisir « Figer les volets » pour bloquer à la fois les lignes au-dessus et les colonnes à gauche. Pour annuler, reviens au même bouton et choisis « Libérer les volets ».\n\nImprimer une feuille Excel demande un peu d'attention, car une grande grille tient rarement sur une seule page. Va dans « Fichier » puis « Imprimer » : l'aperçu à droite te montre comment les pages seront découpées. Si le tableau déborde, utilise l'option « Ajuster la feuille à une page » en bas des réglages pour tout faire tenir.\n\nDeux réglages sont très utiles : dans l'onglet « Mise en page », « Zone d'impression » permet de n'imprimer qu'une partie sélectionnée, et « Imprimer les titres » répète la ligne d'en-tête en haut de chaque page imprimée. Enfin, choisis l'orientation Paysage si ton tableau est large. Avec ces réglages, ton tableau sort proprement sur le papier.",
            ht: "Lè yon tablo vin long, ou pèdi tit kolòn yo depi ou desann. Solisyon an se « fige volè yo » : kenbe premye liy la vizib tout tan, menm lè w ap desann. Ale nan onglè « Affichage », klike sou « Figer les volets » epi chwazi « Figer la ligne supérieure ». Liy tèt la rete kole anwo pandan rès la ap defile.\n\nOu ka « Figer la première colonne » tou pou kenbe non yo vizib agoch, oswa chwazi yon selil epi chwazi « Figer les volets » pou bloke ni liy anwo yo ni kolòn agoch yo an menm tan. Pou anile, retounen nan menm bouton an epi chwazi « Libérer les volets ».\n\nEnprime yon fèy Excel mande yon ti atansyon, paske yon gwo griy raman kenbe sou yon sèl paj. Ale nan « Fichier » epi « Imprimer » : apèsi adwat la montre ou kijan paj yo ap koupe. Si tablo a debòde, sèvi ak opsyon « Ajuster la feuille à une page » anba reglaj yo pou fè tout kenbe.\n\nDe reglaj itil anpil : nan onglè « Mise en page », « Zone d'impression » pèmèt enprime sèlman yon pati ou chwazi, epi « Imprimer les titres » repete liy tèt la anwo chak paj ki enprime. Anfen, chwazi oryantasyon Paysage si tablo ou laj. Ak reglaj sa yo, tablo ou soti pwòp sou papye a.",
            en: "When a table gets long, you lose sight of the column titles as soon as you scroll down. The solution is to \"freeze panes\": keep the first row visible at all times, even while scrolling. Go to the \"View\" tab, click \"Freeze Panes\" and choose \"Freeze Top Row\". The header row then stays stuck at the top while the rest scrolls.\n\nYou can also \"Freeze First Column\" to keep the names visible on the left, or select a cell and choose \"Freeze Panes\" to lock both the rows above and the columns to the left at once. To undo, go back to the same button and choose \"Unfreeze Panes\".\n\nPrinting an Excel sheet takes a bit of care, because a large grid rarely fits on a single page. Go to \"File\" then \"Print\": the preview on the right shows how the pages will be split. If the table overflows, use the \"Fit Sheet on One Page\" option at the bottom of the settings to make everything fit.\n\nTwo settings are very useful: in the \"Layout\" tab, \"Print Area\" lets you print only a selected part, and \"Print Titles\" repeats the header row at the top of every printed page. Finally, choose Landscape orientation if your table is wide. With these settings, your table comes out cleanly on paper.",
            es: "Cuando una tabla se hace larga, pierdes de vista los títulos de las columnas en cuanto bajas. La solución es «inmovilizar paneles»: mantener la primera fila visible en todo momento, incluso al desplazarte. Ve a la pestaña «Vista», haz clic en «Inmovilizar» y elige «Inmovilizar fila superior». La fila de encabezado queda entonces pegada arriba mientras el resto se desplaza.\n\nTambién puedes «Inmovilizar primera columna» para mantener los nombres visibles a la izquierda, o seleccionar una celda y elegir «Inmovilizar paneles» para bloquear a la vez las filas de arriba y las columnas de la izquierda. Para deshacer, vuelve al mismo botón y elige «Movilizar paneles».\n\nImprimir una hoja de Excel requiere un poco de atención, porque una gran cuadrícula rara vez cabe en una sola página. Ve a «Archivo» y luego «Imprimir»: la vista previa a la derecha te muestra cómo se dividirán las páginas. Si la tabla se desborda, usa la opción «Ajustar hoja en una página» en la parte inferior de los ajustes para que todo quepa.\n\nDos ajustes son muy útiles: en la pestaña «Diseño de página», «Área de impresión» permite imprimir solo una parte seleccionada, e «Imprimir títulos» repite la fila de encabezado en la parte superior de cada página impresa. Por último, elige la orientación Horizontal si tu tabla es ancha. Con estos ajustes, tu tabla sale limpia en el papel.",
          },
          keyPoints: {
            fr: ["Affichage > Figer les volets garde l'en-tête visible en défilant", "Figer la ligne supérieure ou la première colonne", "Fichier > Imprimer : « Ajuster à une page » si ça déborde", "Imprimer les titres répète l'en-tête sur chaque page"],
            ht: ["Affichage > Figer les volets kenbe tèt la vizib lè w defile", "Fige liy anwo a oswa premye kolòn nan", "Fichier > Imprimer : « Ajuster à une page » si li debòde", "Imprimer les titres repete tèt la sou chak paj"],
            en: ["View > Freeze Panes keeps the header visible while scrolling", "Freeze the top row or the first column", "File > Print: \"Fit on One Page\" if it overflows", "Print Titles repeats the header on every page"],
            es: ["Vista > Inmovilizar mantiene el encabezado visible al desplazar", "Inmoviliza la fila superior o la primera columna", "Archivo > Imprimir: «Ajustar en una página» si se desborda", "Imprimir títulos repite el encabezado en cada página"],
          },
          exercise: {
            fr: "Crée un tableau de quinze lignes avec un en-tête. Utilise Affichage > Figer les volets > Figer la ligne supérieure, puis fais défiler pour vérifier que l'en-tête reste visible. Ouvre ensuite Fichier > Imprimer, active « Ajuster la feuille à une page » et passe l'orientation en Paysage.",
            ht: "Kreye yon tablo kenz liy ak yon tèt. Sèvi ak Affichage > Figer les volets > Figer la ligne supérieure, epi defile pou verifye tèt la rete vizib. Apre sa ouvri Fichier > Imprimer, aktive « Ajuster la feuille à une page » epi mete oryantasyon an an Paysage.",
            en: "Create a fifteen-row table with a header. Use View > Freeze Panes > Freeze Top Row, then scroll to check that the header stays visible. Then open File > Print, turn on \"Fit Sheet on One Page\" and set the orientation to Landscape.",
            es: "Crea una tabla de quince filas con un encabezado. Usa Vista > Inmovilizar > Inmovilizar fila superior, luego desplázate para comprobar que el encabezado sigue visible. Después abre Archivo > Imprimir, activa «Ajustar hoja en una página» y pon la orientación en Horizontal.",
          },
        },
      ],
    },
  ],
};

export default excel;
