import { CourseContent } from "./types";

const famille: CourseContent = {
  slug: "famille",
  intro: {
    fr: "Bâtir une famille et un mariage selon le plan de Dieu : l'amour, l'engagement et la grâce comme fondations d'un foyer solide.",
    ht: "Bati yon fanmi ak yon maryaj selon plan Bondye : lanmou, angajman ak gras kòm fondasyon yon fwaye solid.",
    en: "Building a family and marriage according to God's plan: love, commitment and grace as the foundations of a strong home.",
    es: "Construir una familia y un matrimonio según el plan de Dios: el amor, el compromiso y la gracia como fundamentos de un hogar sólido.",
  },
  modules: [
    {
      title: { fr: "Le mariage selon le dessein de Dieu", ht: "Maryaj la selon plan Bondye", en: "Marriage according to God's design", es: "El matrimonio según el diseño de Dios" },
      lessons: [
        {
          slug: "fondement-du-mariage",
          title: { fr: "Le fondement du mariage", ht: "Fondasyon maryaj la", en: "The foundation of marriage", es: "El fundamento del matrimonio" },
          videoId: "",
          content: {
            fr: "Le mariage n'est pas une invention humaine, mais une idée de Dieu. Dès le commencement, « l'Éternel Dieu dit : Il n'est pas bon que l'homme soit seul ; je lui ferai une aide semblable à lui. » (Genèse 2.18) Le mariage est un don de Dieu, conçu pour le bien de l'homme et de la femme.\n\nJésus rappelle le plan originel : « C'est pourquoi l'homme quittera son père et sa mère, et s'attachera à sa femme, et les deux deviendront une seule chair. » (Matthieu 19.5) Le mariage repose sur trois piliers : quitter (l'indépendance des parents), s'attacher (l'engagement pour la vie) et devenir un (l'unité profonde du corps, de l'âme et de l'esprit).\n\nUn mariage solide se construit sur le roc de la Parole de Dieu et non sur le sable des émotions changeantes. « Si l'Éternel ne bâtit la maison, ceux qui la bâtissent travaillent en vain. » (Psaume 127.1) Christ doit être au centre, invité comme aux noces de Cana.\n\nEnfin, le mariage est une alliance devant Dieu, et non un simple contrat entre deux personnes. « L'Éternel a été témoin entre toi et la femme de ta jeunesse. » (Malachie 2.14) Comprendre cela change tout : quand les difficultés arrivent, on ne cherche pas la sortie, on cherche Celui qui a scellé l'union et qui donne la force de tenir jusqu'au bout.",
            ht: "Maryaj se pa yon envansyon lèzòm, men yon lide Bondye. Depi nan kòmansman, « Senyè Bondye a di : Li pa bon pou nonm nan pou kont li ; m ap fè yon èd ki tankou li. » (Jenèz 2.18) Maryaj se yon kado Bondye, ki fèt pou byen nonm ak fanm.\n\nJezi raple plan orijinal la : « Se poutèt sa nonm nan ap kite papa l ak manman l, epi l ap atache l ak madanm li, e toude ap vin yon sèl chè. » (Matye 19.5) Maryaj chita sou twa pilye : kite (endepandans paran yo), atache (angajman pou tout lavi) ak vin yon sèl (inite pwofon kò, nanm ak lespri).\n\nYon maryaj solid bati sou wòch Pawòl Bondye e non sou sab emosyon k ap chanje. « Si Senyè a pa bati kay la, moun k ap bati l yo travay pou granmesi. » (Sòm 127.1) Kris dwe nan sant lan, envite tankou nan nòs Kana.\n\nAnfen, maryaj se yon alyans devan Bondye, e non yon senp kontra ant de moun. « Senyè a te temwen ant ou menm ak madanm jenès ou a. » (Malachi 2.14) Konprann sa a chanje tout bagay : lè difikilte yo rive, ou pa chèche sòti a, ou chèche Sila ki te sele inyon an e ki bay fòs pou kenbe jouk nan bout.",
            en: "Marriage is not a human invention, but God's idea. From the beginning, \"The Lord God said, 'It is not good for the man to be alone. I will make a helper suitable for him.'\" (Genesis 2:18) Marriage is a gift from God, designed for the good of man and woman.\n\nJesus recalls the original plan: \"For this reason a man will leave his father and mother and be united to his wife, and the two will become one flesh.\" (Matthew 19:5) Marriage rests on three pillars: leaving (independence from parents), being united (a lifelong commitment) and becoming one (deep unity of body, soul and spirit).\n\nA strong marriage is built on the rock of God's Word and not on the sand of shifting emotions. \"Unless the Lord builds the house, the builders labor in vain.\" (Psalm 127:1) Christ must be at the center, invited as at the wedding in Cana.\n\nFinally, marriage is a covenant before God, not a mere contract between two people. \"The Lord is the witness between you and the wife of your youth.\" (Malachi 2:14) Understanding this changes everything: when difficulties come, we do not look for the exit, we look to the One who sealed the union and who gives the strength to hold on to the end.",
            es: "El matrimonio no es un invento humano, sino una idea de Dios. Desde el principio, «Y dijo Jehová Dios: No es bueno que el hombre esté solo; le haré ayuda idónea para él.» (Génesis 2:18) El matrimonio es un regalo de Dios, diseñado para el bien del hombre y la mujer.\n\nJesús recuerda el plan original: «Por esto el hombre dejará padre y madre, y se unirá a su mujer, y los dos serán una sola carne.» (Mateo 19:5) El matrimonio se apoya en tres pilares: dejar (independencia de los padres), unirse (compromiso de por vida) y ser uno (unidad profunda de cuerpo, alma y espíritu).\n\nUn matrimonio sólido se construye sobre la roca de la Palabra de Dios y no sobre la arena de las emociones cambiantes. «Si Jehová no edificare la casa, en vano trabajan los que la edifican.» (Salmo 127:1) Cristo debe estar en el centro, invitado como en las bodas de Caná.\n\nPor último, el matrimonio es un pacto delante de Dios, no un simple contrato entre dos personas. «Jehová ha atestiguado entre ti y la mujer de tu juventud.» (Malaquías 2:14) Entender esto lo cambia todo: cuando llegan las dificultades, no buscamos la salida, buscamos a Aquel que selló la unión y que da la fuerza para sostenerla hasta el final.",
          },
          keyPoints: {
            fr: ["Le mariage est un don de Dieu, pas une invention humaine", "Trois piliers : quitter, s'attacher, devenir un (Mt 19.5)", "Christ au centre : sans lui on bâtit en vain (Ps 127.1)", "Une alliance devant Dieu témoin, pas un simple contrat (Mal 2.14)"],
            ht: ["Maryaj se yon kado Bondye, pa yon envansyon lèzòm", "Twa pilye : kite, atache, vin yon sèl (Matye 19.5)", "Kris nan sant : san li ou bati pou granmesi (Sòm 127.1)", "Yon alyans devan Bondye temwen, pa yon senp kontra (Mal 2.14)"],
            en: ["Marriage is God's gift, not a human invention", "Three pillars: leave, be united, become one (Mt 19:5)", "Christ at the center: without him we build in vain (Ps 127:1)", "A covenant before God as witness, not a mere contract (Mal 2:14)"],
            es: ["El matrimonio es un regalo de Dios, no un invento humano", "Tres pilares: dejar, unirse, ser uno (Mt 19:5)", "Cristo en el centro: sin él se edifica en vano (Sal 127:1)", "Un pacto delante de Dios testigo, no un simple contrato (Mal 2:14)"],
          },
          exercise: {
            fr: "Avec votre conjoint (ou, si vous êtes célibataire, dans la prière), identifiez lequel des trois piliers — quitter, s'attacher, devenir un — est aujourd'hui le plus fragile dans votre relation. Écrivez une action concrète à poser cette semaine pour le renforcer, puis remettez votre foyer à Dieu dans une courte prière commune.",
            ht: "Ak konjwen ou (oswa, si w selibatè, nan lapriyè), idantifye kilès nan twa pilye yo — kite, atache, vin yon sèl — ki pi frajil jodi a nan relasyon ou. Ekri yon aksyon konkrè pou w poze semèn sa a pou ranfòse l, epi remèt fwaye ou bay Bondye nan yon ti lapriyè ansanm.",
            en: "With your spouse (or, if you are single, in prayer), identify which of the three pillars — leaving, being united, becoming one — is the most fragile in your relationship today. Write one concrete action to take this week to strengthen it, then entrust your home to God in a short shared prayer.",
            es: "Con tu cónyuge (o, si eres soltero, en oración), identifica cuál de los tres pilares — dejar, unirse, ser uno — es hoy el más frágil en tu relación. Escribe una acción concreta para realizar esta semana y así fortalecerlo, luego entrega tu hogar a Dios en una breve oración compartida.",
          },
          verse: "Genèse 2.24",
        },
        {
          slug: "roles-mari-femme",
          title: { fr: "S'aimer et se respecter", ht: "Renmen ak respekte youn lòt", en: "Loving and respecting one another", es: "Amarse y respetarse" },
          videoId: "",
          content: {
            fr: "Dieu a donné au mari et à la femme des rôles complémentaires, non pour créer une hiérarchie de valeur, mais une harmonie d'amour. « Maris, aimez vos femmes, comme Christ a aimé l'Église, et s'est livré lui-même pour elle. » (Éphésiens 5.25) L'autorité du mari n'est pas une domination, mais un amour sacrificiel qui se donne.\n\nÀ la femme, il est demandé le respect et le soutien : « Que la femme respecte son mari. » (Éphésiens 5.33) Ces instructions ne s'opposent pas, elles se répondent : l'homme aime en se donnant, la femme honore en soutenant. Chacun donne à l'autre ce dont il a le plus besoin.\n\nLe secret, c'est la soumission mutuelle : « Soumettez-vous les uns aux autres dans la crainte de Christ. » (Éphésiens 5.21) Dans un mariage chrétien, on ne cherche pas à gagner l'un contre l'autre, mais à servir l'un pour l'autre. L'amour n'est pas seulement un sentiment, c'est une décision quotidienne.\n\nCet amour a une définition précise dans la Parole : « L'amour est patient, il est plein de bonté ; il ne cherche point son intérêt, il ne s'irrite point. » (1 Corinthiens 13.4-5) Aimer son conjoint, ce n'est pas attendre qu'il change, c'est choisir de le servir chaque jour, même quand les sentiments faiblissent. C'est ainsi que l'amour grandit et devient inébranlable.",
            ht: "Bondye bay mari ak madanm wòl konplemantè, se pa pou kreye yon yerachi valè, men yon amoni lanmou. « Mari, renmen madanm nou, menm jan Kris te renmen Legliz la e li te bay tèt li pou li. » (Efezyen 5.25) Otorite mari a se pa yon dominasyon, men yon lanmou sakrifisyèl ki bay tèt li.\n\nPou madanm nan, yo mande respè ak sipò : « Se pou madanm nan respekte mari l. » (Efezyen 5.33) Enstriksyon sa yo pa opoze, yo reponn youn lòt : nonm nan renmen lè li bay tèt li, fanm nan onore lè li sipòte. Chak moun bay lòt la sa li pi bezwen.\n\nSekrè a, se soumisyon mityèl : « Soumèt nou youn anba lòt nan lakrentif Kris. » (Efezyen 5.21) Nan yon maryaj kretyen, ou pa chèche genyen youn kont lòt, men sèvi youn pou lòt. Lanmou se pa sèlman yon santiman, se yon desizyon chak jou.\n\nLanmou sa a gen yon definisyon presi nan Pawòl la : « Lanmou pasyan, li plen bonte ; li pa chèche enterè l, li pa fache. » (1 Korentyen 13.4-5) Renmen konjwen w, se pa tann li chanje, se chwazi sèvi l chak jou, menm lè santiman yo febli. Se konsa lanmou grandi e vin solid.",
            en: "God gave the husband and wife complementary roles, not to create a hierarchy of value, but a harmony of love. \"Husbands, love your wives, just as Christ loved the church and gave himself up for her.\" (Ephesians 5:25) The husband's authority is not domination, but a sacrificial love that gives itself.\n\nThe wife is asked for respect and support: \"The wife must respect her husband.\" (Ephesians 5:33) These instructions do not oppose each other, they answer each other: the man loves by giving himself, the woman honors by supporting. Each gives the other what they need most.\n\nThe secret is mutual submission: \"Submit to one another out of reverence for Christ.\" (Ephesians 5:21) In a Christian marriage, you do not seek to win one against the other, but to serve one for the other. Love is not only a feeling, it is a daily decision.\n\nThis love has a precise definition in the Word: \"Love is patient, love is kind... it is not self-seeking, it is not easily angered.\" (1 Corinthians 13:4-5) To love your spouse is not to wait for them to change, it is to choose to serve them every day, even when feelings weaken. This is how love grows and becomes unshakable.",
            es: "Dios dio al esposo y a la esposa roles complementarios, no para crear una jerarquía de valor, sino una armonía de amor. «Maridos, amad a vuestras mujeres, así como Cristo amó a la iglesia, y se entregó a sí mismo por ella.» (Efesios 5:25) La autoridad del esposo no es dominación, sino un amor sacrificial que se entrega.\n\nA la esposa se le pide respeto y apoyo: «La mujer respete a su marido.» (Efesios 5:33) Estas instrucciones no se oponen, se responden: el hombre ama entregándose, la mujer honra apoyando. Cada uno da al otro lo que más necesita.\n\nEl secreto es la sumisión mutua: «Someteos unos a otros en el temor de Dios.» (Efesios 5:21) En un matrimonio cristiano no se busca ganar uno contra el otro, sino servir uno para el otro. El amor no es solo un sentimiento, es una decisión diaria.\n\nEste amor tiene una definición precisa en la Palabra: «El amor es sufrido, es benigno... no busca lo suyo, no se irrita.» (1 Corintios 13:4-5) Amar a tu cónyuge no es esperar a que cambie, es escoger servirle cada día, aun cuando los sentimientos se debilitan. Así es como el amor crece y se vuelve inquebrantable.",
          },
          keyPoints: {
            fr: ["Le mari aime en se sacrifiant comme Christ (Éph 5.25)", "La femme honore et soutient (Éph 5.33)", "Soumission mutuelle : servir l'un pour l'autre (Éph 5.21)", "L'amour est une décision quotidienne (1 Cor 13.4-5)"],
            ht: ["Mari a renmen an sakrifis tankou Kris (Efez 5.25)", "Fanm nan onore e sipòte (Efez 5.33)", "Soumisyon mityèl : sèvi youn pou lòt (Efez 5.21)", "Lanmou se yon desizyon chak jou (1 Kor 13.4-5)"],
            en: ["The husband loves sacrificially like Christ (Eph 5:25)", "The wife honors and supports (Eph 5:33)", "Mutual submission: serve one for the other (Eph 5:21)", "Love is a daily decision (1 Cor 13:4-5)"],
            es: ["El esposo ama sacrificándose como Cristo (Ef 5:25)", "La esposa honra y apoya (Ef 5:33)", "Sumisión mutua: servir uno para el otro (Ef 5:21)", "El amor es una decisión diaria (1 Cor 13:4-5)"],
          },
          exercise: {
            fr: "Cette semaine, demandez à votre conjoint : « De quelle manière te sens-tu le plus aimé(e) et respecté(e) ? » Écoutez sans vous justifier, puis engagez-vous à poser chaque jour un geste concret dans le sens de sa réponse. Relisez 1 Corinthiens 13.4-7 et cochez les traits d'amour que vous voulez cultiver.",
            ht: "Semèn sa a, mande konjwen w : « Nan ki fason ou santi w pi renmen e pi respekte ? » Koute san ou pa jistifye tèt ou, epi angaje w pou poze chak jou yon jès konkrè nan sans repons li a. Reli 1 Korentyen 13.4-7 e make trè lanmou ou vle kiltive yo.",
            en: "This week, ask your spouse: \"In what way do you feel most loved and respected?\" Listen without defending yourself, then commit to one concrete gesture each day in the direction of their answer. Reread 1 Corinthians 13:4-7 and mark the traits of love you want to cultivate.",
            es: "Esta semana, pregunta a tu cónyuge: «¿De qué manera te sientes más amado(a) y respetado(a)?» Escucha sin justificarte, luego comprométete a un gesto concreto cada día en la dirección de su respuesta. Relee 1 Corintios 13:4-7 y marca los rasgos del amor que quieres cultivar.",
          },
          verse: "Éphésiens 5.25",
        },
        {
          slug: "alliance-et-engagement",
          title: { fr: "Une alliance pour la vie", ht: "Yon alyans pou tout lavi", en: "A covenant for life", es: "Un pacto para toda la vida" },
          videoId: "",
          content: {
            fr: "Dans une culture où l'on jette ce qui ne fonctionne plus, la Bible présente le mariage comme une alliance sacrée, indissoluble par nature. « Que l'homme ne sépare pas ce que Dieu a uni. » (Matthieu 19.6) L'engagement n'est pas une prison, c'est le sol ferme sur lequel l'amour peut grandir en sécurité.\n\nL'engagement se prouve dans la durée, pas dans les beaux jours. « L'amour couvre toutes les fautes. » (Proverbes 10.12) Beaucoup abandonnent au premier hiver, alors que le printemps était juste après. La fidélité de Dieu envers son peuple, malgré ses infidélités, est le modèle de la fidélité conjugale : un amour qui reste quand tout invite à partir.\n\nL'union à deux, scellée par Dieu, devient une corde à trois brins : « la corde à trois fils ne se rompt pas facilement. » (Ecclésiaste 4.12) Quand un couple invite Dieu comme troisième partenaire, il puise une force qu'aucune volonté humaine seule ne peut fournir. Les tempêtes qui briseraient un couple seul ne rompent pas celui qui est tenu par le Seigneur.\n\nEnfin, l'engagement se renouvelle. Les vœux prononcés une fois se réaffirment par mille petits choix quotidiens : rester, pardonner, recommencer. « Je te fiancerai à moi pour toujours ; je te fiancerai à moi par la fidélité. » (Osée 2.19-20) Dieu lui-même se fiance à son peuple pour toujours : voilà le cœur de l'engagement conjugal.",
            ht: "Nan yon kilti kote moun jete sa ki pa mache ankò, Bib la prezante maryaj kòm yon alyans sakre, ki pa ka kase pa nati l. « Se pou lòm pa separe sa Bondye mete ansanm. » (Matye 19.6) Angajman se pa yon prizon, se tè fèm kote lanmou ka grandi an sekirite.\n\nAngajman pwouve tèt li nan dire, pa nan bèl jou yo. « Lanmou kouvri tout fot. » (Pwovèb 10.12) Anpil moun abandone nan premye ivè a, pandan prentan an te jis apre. Fidelite Bondye anvè pèp li, malgre enfidelite yo, se modèl fidelite maryaj la : yon lanmou ki rete lè tout bagay envite w pati.\n\nInyon de moun, sele pa Bondye, vin yon kòd twa bwen : « kòd twa fil la pa kase fasil. » (Eklezyas 4.12) Lè yon koup envite Bondye kòm twazyèm patnè, li pran yon fòs okenn volonte imen pou kont li pa ka bay. Tanpèt ki ta kraze yon koup pou kont li pa kase sila Senyè a kenbe a.\n\nAnfen, angajman renouvle. Ve yo pwononse yon fwa reafime tèt yo pa mil ti chwa chak jou : rete, padonnen, rekòmanse. « M ap fiyanse ou avè m pou tout tan ; m ap fiyanse ou avè m nan fidelite. » (Oze 2.19-20) Bondye menm fiyanse ak pèp li pou tout tan : men kè angajman maryaj la.",
            en: "In a culture that throws away what no longer works, the Bible presents marriage as a sacred covenant, indissoluble by nature. \"Therefore what God has joined together, let no one separate.\" (Matthew 19:6) Commitment is not a prison; it is the firm ground on which love can grow in safety.\n\nCommitment proves itself over time, not in the good days. \"Love covers over all wrongs.\" (Proverbs 10:12) Many give up at the first winter, when spring was just around the corner. God's faithfulness to his people, despite their unfaithfulness, is the model of marital faithfulness: a love that stays when everything invites you to leave.\n\nThe union of two, sealed by God, becomes a cord of three strands: \"a cord of three strands is not quickly broken.\" (Ecclesiastes 4:12) When a couple invites God as the third partner, they draw on a strength that no human will alone can supply. The storms that would break a couple on its own do not break the one held by the Lord.\n\nFinally, commitment is renewed. The vows spoken once are reaffirmed through a thousand small daily choices: to stay, to forgive, to begin again. \"I will betroth you to me forever... in faithfulness.\" (Hosea 2:19-20) God himself betroths his people forever: this is the heart of marital commitment.",
            es: "En una cultura que desecha lo que ya no funciona, la Biblia presenta el matrimonio como un pacto sagrado, indisoluble por naturaleza. «Por tanto, lo que Dios juntó, no lo separe el hombre.» (Mateo 19:6) El compromiso no es una prisión; es el suelo firme sobre el cual el amor puede crecer con seguridad.\n\nEl compromiso se prueba con el tiempo, no en los buenos días. «El amor cubrirá todas las faltas.» (Proverbios 10:12) Muchos se rinden en el primer invierno, cuando la primavera estaba a la vuelta de la esquina. La fidelidad de Dios hacia su pueblo, a pesar de sus infidelidades, es el modelo de la fidelidad conyugal: un amor que permanece cuando todo invita a marcharse.\n\nLa unión de dos, sellada por Dios, se convierte en una cuerda de tres hilos: «cordón de tres dobleces no se rompe pronto.» (Eclesiastés 4:12) Cuando una pareja invita a Dios como tercer compañero, recibe una fuerza que ninguna voluntad humana sola puede dar. Las tormentas que romperían a una pareja sola no rompen a la que sostiene el Señor.\n\nPor último, el compromiso se renueva. Los votos pronunciados una vez se reafirman mediante mil pequeñas decisiones diarias: quedarse, perdonar, volver a empezar. «Te desposaré conmigo para siempre... en fidelidad.» (Oseas 2:19-20) Dios mismo se desposa con su pueblo para siempre: este es el corazón del compromiso conyugal.",
          },
          keyPoints: {
            fr: ["Le mariage est une alliance que l'homme ne doit pas rompre (Mt 19.6)", "L'engagement se prouve dans la durée, pas dans les beaux jours", "La corde à trois brins avec Dieu ne rompt pas (Ecc 4.12)", "Renouveler ses vœux par mille choix quotidiens (Osée 2.19-20)"],
            ht: ["Maryaj se yon alyans lòm pa dwe kase (Matye 19.6)", "Angajman pwouve nan dire, pa nan bèl jou", "Kòd twa bwen ak Bondye pa kase (Ekl 4.12)", "Renouvle ve yo pa mil chwa chak jou (Oze 2.19-20)"],
            en: ["Marriage is a covenant no one should break (Mt 19:6)", "Commitment proves itself over time, not in good days", "The three-strand cord with God is not broken (Ecc 4:12)", "Renew your vows through a thousand daily choices (Hos 2:19-20)"],
            es: ["El matrimonio es un pacto que nadie debe romper (Mt 19:6)", "El compromiso se prueba con el tiempo, no en los buenos días", "El cordón de tres hilos con Dios no se rompe (Ecl 4:12)", "Renovar los votos con mil decisiones diarias (Os 2:19-20)"],
          },
          exercise: {
            fr: "Écrivez ensemble (ou seul, en prière pour votre futur foyer) une phrase d'engagement renouvelé : « Quoi qu'il arrive, je choisis de... » Affichez-la dans un lieu visible de la maison. Puis nommez une « tempête » que vous traversez actuellement et remettez-la explicitement à Dieu, le troisième brin de votre corde.",
            ht: "Ekri ansanm (oswa pou kont ou, nan lapriyè pou fwaye w a lavni) yon fraz angajman renouvle : « Kèlkeswa sa k rive, mwen chwazi... » Kole l nan yon kote vizib nan kay la. Apre sa, site yon « tanpèt » w ap travèse kounye a e remèt li klèman bay Bondye, twazyèm bwen kòd ou a.",
            en: "Write together (or alone, in prayer for your future home) a sentence of renewed commitment: \"Whatever happens, I choose to...\" Post it somewhere visible in the house. Then name a \"storm\" you are currently facing and explicitly hand it over to God, the third strand of your cord.",
            es: "Escriban juntos (o solo, en oración por tu futuro hogar) una frase de compromiso renovado: «Pase lo que pase, elijo...» Colócala en un lugar visible de la casa. Luego nombra una «tormenta» que estás atravesando y entrégala explícitamente a Dios, el tercer hilo de tu cuerda.",
          },
          verse: "Ecclésiaste 4.12",
        },
      ],
    },
    {
      title: { fr: "La communication et le pardon dans le couple", ht: "Kominikasyon ak padon nan koup la", en: "Communication and forgiveness in the couple", es: "La comunicación y el perdón en la pareja" },
      lessons: [
        {
          slug: "communiquer-avec-amour",
          title: { fr: "Communiquer avec amour", ht: "Kominike ak lanmou", en: "Communicating with love", es: "Comunicar con amor" },
          videoId: "",
          content: {
            fr: "La plupart des blessures dans un couple ne viennent pas d'un manque d'amour, mais d'un manque de communication. La Bible conseille : « Que chacun soit prompt à écouter, lent à parler, lent à se mettre en colère. » (Jacques 1.19) Écouter vraiment son conjoint, c'est déjà l'aimer.\n\nLes mots ont un pouvoir immense : « La mort et la vie sont au pouvoir de la langue. » (Proverbes 18.21) Une parole dure peut blesser pour des années, une parole douce peut restaurer. « Une réponse douce calme la fureur, mais une parole dure excite la colère. » (Proverbes 15.1) Choisir ses mots, c'est protéger son couple.\n\nLa bonne communication ne consiste pas à avoir raison, mais à se comprendre. Parle de ce que tu ressens sans accuser, écoute pour comprendre et non pour répondre. « Que votre parole soit toujours accompagnée de grâce, assaisonnée de sel. » (Colossiens 4.6)\n\nLa communication n'est pas seulement des mots : c'est aussi le ton, le regard et le silence. Beaucoup de disputes ne portent pas sur le sujet apparent, mais sur un besoin caché de se sentir entendu et valorisé. Prenez l'habitude de reformuler ce que l'autre dit avant de répondre : « Si je comprends bien, tu ressens... » Cette simple discipline désamorce la moitié des conflits avant qu'ils n'éclatent.",
            ht: "Pifò blesi nan yon koup pa soti nan yon mank lanmou, men nan yon mank kominikasyon. Bib la konseye : « Se pou chak moun prese pou koute, dousman pou pale, dousman pou fache. » (Jak 1.19) Koute konjwen w vrèman, se deja renmen l.\n\nMo yo gen yon pouvwa imans : « Lanmò ak lavi nan pouvwa lang lan. » (Pwovèb 18.21) Yon pawòl di ka blese pou ane, yon pawòl dous ka restore. « Yon repons dous kalme kòlè, men yon pawòl di limen kòlè. » (Pwovèb 15.1) Chwazi mo w yo, se pwoteje koup ou.\n\nBon kominikasyon pa nan gen rezon, men nan konprann youn lòt. Pale de sa w santi san akize, koute pou konprann e non pou reponn. « Se pou pawòl nou toujou akonpaye ak gras, sale ak sèl. » (Kolosyen 4.6)\n\nKominikasyon se pa sèlman mo : se ton an tou, gade a ak silans lan. Anpil diskisyon pa sou sijè aparan an, men sou yon bezwen kache pou santi w tande e valorize. Pran abitid repete sa lòt la di anvan w reponn : « Si mwen konprann byen, ou santi... » Senp disiplin sa a dezamòse mwatye konfli yo anvan yo eklate.",
            en: "Most wounds in a couple do not come from a lack of love, but from a lack of communication. The Bible advises: \"Everyone should be quick to listen, slow to speak and slow to become angry.\" (James 1:19) To truly listen to your spouse is already to love them.\n\nWords have immense power: \"The tongue has the power of life and death.\" (Proverbs 18:21) A harsh word can wound for years, a gentle word can restore. \"A gentle answer turns away wrath, but a harsh word stirs up anger.\" (Proverbs 15:1) Choosing your words is protecting your marriage.\n\nGood communication is not about being right, but about understanding each other. Speak about what you feel without accusing, listen to understand and not to reply. \"Let your conversation be always full of grace, seasoned with salt.\" (Colossians 4:6)\n\nCommunication is not only words: it is also tone, look and silence. Many arguments are not about the apparent subject, but about a hidden need to feel heard and valued. Make a habit of restating what the other says before answering: \"If I understand correctly, you feel...\" This simple discipline defuses half of conflicts before they erupt.",
            es: "La mayoría de las heridas en una pareja no vienen de una falta de amor, sino de una falta de comunicación. La Biblia aconseja: «Todo hombre sea pronto para oír, tardo para hablar, tardo para airarse.» (Santiago 1:19) Escuchar de verdad a tu cónyuge ya es amarlo.\n\nLas palabras tienen un poder inmenso: «La muerte y la vida están en poder de la lengua.» (Proverbios 18:21) Una palabra dura puede herir por años, una palabra suave puede restaurar. «La blanda respuesta quita la ira, mas la palabra áspera hace subir el furor.» (Proverbios 15:1) Escoger tus palabras es proteger tu matrimonio.\n\nLa buena comunicación no consiste en tener razón, sino en entenderse. Habla de lo que sientes sin acusar, escucha para comprender y no para responder. «Sea vuestra palabra siempre con gracia, sazonada con sal.» (Colosenses 4:6)\n\nLa comunicación no es solo palabras: es también el tono, la mirada y el silencio. Muchas discusiones no son sobre el tema aparente, sino sobre una necesidad oculta de sentirse escuchado y valorado. Toma el hábito de repetir lo que el otro dice antes de responder: «Si entiendo bien, tú sientes...» Esta sencilla disciplina desactiva la mitad de los conflictos antes de que estallen.",
          },
          keyPoints: {
            fr: ["Prompt à écouter, lent à parler et à se fâcher (Jacques 1.19)", "Les mots donnent la vie ou la mort (Proverbes 18.21)", "Chercher à comprendre, pas à avoir raison", "Reformuler avant de répondre désamorce les conflits"],
            ht: ["Prese pou koute, dousman pou pale e fache (Jak 1.19)", "Mo yo bay lavi oswa lanmò (Pwovèb 18.21)", "Chèche konprann, pa gen rezon", "Repete anvan w reponn dezamòse konfli"],
            en: ["Quick to listen, slow to speak and to anger (James 1:19)", "Words give life or death (Proverbs 18:21)", "Seek to understand, not to be right", "Restate before answering to defuse conflict"],
            es: ["Pronto para oír, tardo para hablar y airarse (Santiago 1:19)", "Las palabras dan vida o muerte (Proverbios 18:21)", "Buscar entender, no tener razón", "Repetir antes de responder desactiva el conflicto"],
          },
          exercise: {
            fr: "Choisissez un moment calme, sans distraction, pour un « rendez-vous d'écoute » de quinze minutes : l'un parle de son cœur, l'autre écoute et reformule sans se défendre, puis vous inversez les rôles. Notez une parole que vous voulez cesser de dire et une parole d'encouragement que vous voulez répéter chaque jour.",
            ht: "Chwazi yon moman kalm, san distraksyon, pou yon « randevou koute » kenz minit : youn pale de kè l, lòt la koute e repete san li pa defann tèt li, apre sa nou chanje wòl. Note yon pawòl ou vle sispann di ak yon pawòl ankourajman ou vle repete chak jou.",
            en: "Choose a calm, distraction-free moment for a fifteen-minute \"listening appointment\": one speaks from the heart, the other listens and restates without defending, then you switch roles. Note one phrase you want to stop saying and one word of encouragement you want to repeat every day.",
            es: "Escojan un momento tranquilo, sin distracciones, para una «cita de escucha» de quince minutos: uno habla desde el corazón, el otro escucha y repite sin defenderse, luego cambian de roles. Anota una frase que quieres dejar de decir y una palabra de aliento que quieres repetir cada día.",
          },
          verse: "Jacques 1.19",
        },
        {
          slug: "pardon-et-reconciliation",
          title: { fr: "Le pardon et la réconciliation", ht: "Padon ak rekonsilyasyon", en: "Forgiveness and reconciliation", es: "El perdón y la reconciliación" },
          videoId: "",
          content: {
            fr: "Aucun couple n'échappe aux blessures et aux offenses. Ce qui détruit un mariage, ce ne sont pas les fautes elles-mêmes, mais l'accumulation des rancunes non pardonnées. La Bible commande : « Supportez-vous les uns les autres, et pardonnez-vous, comme Christ vous a pardonné. » (Colossiens 3.13)\n\nLe pardon n'est pas nier la douleur ni prétendre que rien n'est arrivé. C'est choisir de libérer l'autre de sa dette, comme Dieu nous a libérés. Pierre demanda combien de fois pardonner, jusqu'à sept fois ? Jésus répondit : « soixante-dix fois sept fois » (Matthieu 18.22), c'est-à-dire sans compter. Le pardon est un mode de vie, pas un événement isolé.\n\nUn couple qui sait dire « pardonne-moi » et « je te pardonne » possède un trésor. « Que le soleil ne se couche pas sur votre colère. » (Éphésiens 4.26) Régler les conflits vite, avant qu'ils ne s'enracinent, garde l'amour vivant et le foyer en paix.\n\nLa réconciliation va plus loin que le pardon : elle reconstruit la confiance. Le pardon est une décision immédiate, la restauration est un chemin patient. « Autant qu'il dépend de vous, soyez en paix avec tous les hommes. » (Romains 12.18) Cela demande de l'humilité pour reconnaître ses torts et de la douceur pour accueillir le repentir de l'autre. Là où le pardon coule librement, l'amour ne cesse de se renouveler.",
            ht: "Pa gen koup ki chape anba blesi ak ofans. Sa ki detwi yon maryaj, se pa fot yo menm, men akimilasyon rankin ki pa padonnen. Bib la kòmande : « Sipòte youn lòt, e padonnen youn lòt, menm jan Kris padonnen nou. » (Kolosyen 3.13)\n\nPadon se pa nye doulè a ni pretann anyen pa t rive. Se chwazi libere lòt la anba dèt li, menm jan Bondye libere nou. Pyè te mande konbyen fwa pou padonnen, jouk sèt fwa ? Jezi reponn : « swasanndis fwa sèt fwa » (Matye 18.22), sa vle di san konte. Padon se yon fason viv, pa yon evènman izole.\n\nYon koup ki konnen di « padonnen m » ak « mwen padonnen w » gen yon trezò. « Pa kite solèy la kouche sou kòlè nou. » (Efezyen 4.26) Regle konfli yo vit, anvan yo pran rasin, kenbe lanmou vivan e fwaye a nan lapè.\n\nRekonsilyasyon ale pi lwen pase padon : li rebati konfyans. Padon se yon desizyon imedya, restorasyon se yon chemen pasyan. « Otank sa depann de nou, viv an lapè ak tout moun. » (Women 12.18) Sa mande imilite pou rekonèt tò w ak dousè pou akeyi repantans lòt la. Kote padon koule lib, lanmou pa sispann renouvle.",
            en: "No couple escapes wounds and offenses. What destroys a marriage is not the faults themselves, but the buildup of unforgiven resentment. The Bible commands: \"Bear with each other and forgive one another... Forgive as the Lord forgave you.\" (Colossians 3:13)\n\nForgiveness is not denying the pain or pretending nothing happened. It is choosing to release the other from their debt, as God released us. Peter asked how many times to forgive, up to seven times? Jesus answered: \"seventy-seven times\" (Matthew 18:22), meaning without counting. Forgiveness is a way of life, not an isolated event.\n\nA couple that knows how to say \"forgive me\" and \"I forgive you\" holds a treasure. \"Do not let the sun go down while you are still angry.\" (Ephesians 4:26) Settling conflicts quickly, before they take root, keeps love alive and the home at peace.\n\nReconciliation goes further than forgiveness: it rebuilds trust. Forgiveness is an immediate decision, restoration is a patient path. \"If it is possible, as far as it depends on you, live at peace with everyone.\" (Romans 12:18) It takes humility to admit your wrongs and gentleness to welcome the other's repentance. Where forgiveness flows freely, love never stops renewing itself.",
            es: "Ninguna pareja escapa de las heridas y las ofensas. Lo que destruye un matrimonio no son las faltas mismas, sino la acumulación de rencores no perdonados. La Biblia manda: «Soportándoos unos a otros, y perdonándoos... de la manera que Cristo os perdonó, así también hacedlo vosotros.» (Colosenses 3:13)\n\nEl perdón no es negar el dolor ni fingir que nada pasó. Es escoger liberar al otro de su deuda, como Dios nos liberó. Pedro preguntó cuántas veces perdonar, ¿hasta siete? Jesús respondió: «setenta veces siete» (Mateo 18:22), es decir, sin contar. El perdón es un modo de vida, no un evento aislado.\n\nUna pareja que sabe decir «perdóname» y «te perdono» posee un tesoro. «No se ponga el sol sobre vuestro enojo.» (Efesios 4:26) Resolver los conflictos rápido, antes de que echen raíces, mantiene el amor vivo y el hogar en paz.\n\nLa reconciliación va más allá del perdón: reconstruye la confianza. El perdón es una decisión inmediata, la restauración es un camino paciente. «Si es posible, en cuanto dependa de vosotros, estad en paz con todos los hombres.» (Romanos 12:18) Requiere humildad para reconocer los propios errores y ternura para acoger el arrepentimiento del otro. Donde el perdón fluye libremente, el amor nunca deja de renovarse.",
          },
          keyPoints: {
            fr: ["Pardonner comme Christ nous a pardonné (Col 3.13)", "Pardonner sans compter : 70 fois 7 (Matthieu 18.22)", "Ne pas laisser le soleil se coucher sur la colère (Éph 4.26)", "La réconciliation reconstruit la confiance avec patience (Rom 12.18)"],
            ht: ["Padonnen tankou Kris padonnen nou (Kol 3.13)", "Padonnen san konte : 70 fwa 7 (Matye 18.22)", "Pa kite solèy kouche sou kòlè (Efez 4.26)", "Rekonsilyasyon rebati konfyans ak pasyans (Rom 12.18)"],
            en: ["Forgive as Christ forgave us (Col 3:13)", "Forgive without counting: 70 times 7 (Matthew 18:22)", "Don't let the sun set on your anger (Eph 4:26)", "Reconciliation rebuilds trust with patience (Rom 12:18)"],
            es: ["Perdonar como Cristo nos perdonó (Col 3:13)", "Perdonar sin contar: 70 veces 7 (Mateo 18:22)", "No dejar que el sol se ponga sobre el enojo (Ef 4:26)", "La reconciliación reconstruye la confianza con paciencia (Rom 12:18)"],
          },
          exercise: {
            fr: "S'il existe une blessure non réglée entre vous, prenez le risque de la nommer avec douceur, en commençant par vos propres torts et non ceux de l'autre. Dites clairement les mots « pardonne-moi » ou « je te pardonne ». Puis priez ensemble en confiant à Dieu ce que vous ne pouvez pas encore ressentir, en lui demandant la grâce de restaurer la confiance.",
            ht: "Si gen yon blesi ki poko regle ant nou, pran risk pou nonmen l ak dousè, kòmanse ak pwòp tò w e non tò lòt la. Di klèman mo « padonnen m » oswa « mwen padonnen w ». Apre sa priye ansanm, konfye Bondye sa w poko ka santi, mande l gras pou restore konfyans lan.",
            en: "If there is an unresolved wound between you, take the risk of naming it gently, starting with your own faults and not the other's. Clearly say the words \"forgive me\" or \"I forgive you.\" Then pray together, entrusting to God what you cannot yet feel, asking him for the grace to restore trust.",
            es: "Si hay una herida sin resolver entre ustedes, arriésgate a nombrarla con ternura, empezando por tus propias faltas y no las del otro. Di claramente las palabras «perdóname» o «te perdono». Luego oren juntos, entregando a Dios lo que aún no pueden sentir, pidiéndole la gracia de restaurar la confianza.",
          },
          verse: "Colossiens 3.13",
        },
        {
          slug: "intimite-et-fidelite",
          title: { fr: "L'intimité et la fidélité", ht: "Entimite ak fidelite", en: "Intimacy and faithfulness", es: "La intimidad y la fidelidad" },
          videoId: "",
          content: {
            fr: "Dieu a créé l'intimité conjugale et l'a déclarée bonne et sainte. « Que le mariage soit honoré de tous, et le lit conjugal exempt de souillure. » (Hébreux 13.4) Loin d'être un sujet honteux, l'union physique et affective des époux est un don de Dieu, à protéger et à cultiver dans le respect.\n\nL'intimité véritable ne se réduit pas au corps : elle englobe le cœur, l'âme et l'esprit. Devenir « une seule chair » (Genèse 2.24), c'est se connaître profondément, sans masque et sans peur. Cette transparence se construit dans la sécurité de l'engagement : on ne s'ouvre pleinement que là où l'on se sait aimé sans condition.\n\nLa fidélité protège ce jardin. « Bois les eaux de ta citerne... sois en tout temps épris de son amour. » (Proverbes 5.15-19) Le monde banalise l'adultère, mais Dieu appelle à garder son cœur, ses yeux et ses pas. La fidélité commence dans les pensées, bien avant les actes ; c'est là qu'il faut veiller.\n\nProtéger son couple demande des barrières sages : éviter les proximités ambiguës, fuir la pornographie, cultiver la transparence et nourrir l'attirance pour son conjoint. « Que chacun sache posséder son corps dans la sainteté et l'honneur. » (1 Thessaloniciens 4.4) La fidélité n'est pas seulement l'absence de trahison, c'est la présence active d'un amour qui choisit chaque jour la même personne.",
            ht: "Bondye kreye entimite maryaj la e li deklare l bon e sen. « Se pou maryaj la onore pa tout moun, e kabann maryaj la san salte. » (Ebre 13.4) Lwen de yon sijè wont, inyon fizik ak afektif mari ak madanm se yon kado Bondye, pou pwoteje e kiltive ak respè.\n\nVrè entimite pa rezime nan kò a : li anglobe kè, nanm ak lespri. Vin « yon sèl chè » (Jenèz 2.24), se konnen youn lòt pwofondman, san mask e san laperèz. Transparans sa a bati nan sekirite angajman an : ou ouvri tèt ou nèt sèlman kote ou konnen ou renmen san kondisyon.\n\nFidelite pwoteje jaden sa a. « Bwè dlo sitèn ou... se pou lanmou l anvayi w tout tan. » (Pwovèb 5.15-19) Monn nan banalize adiltè, men Bondye rele w pou kenbe kè w, je w ak pa w yo. Fidelite kòmanse nan panse, byen anvan aksyon ; se la pou w veye.\n\nPwoteje koup ou mande baryè saj : evite pwoksimite anbigwe, kouri kite pònografi, kiltive transparans e nouri atirans pou konjwen w. « Se pou chak moun konnen posede kò l nan sentete e onè. » (1 Tesalonisyen 4.4) Fidelite se pa sèlman absans trayizon, se prezans aktif yon lanmou ki chwazi menm moun nan chak jou.",
            en: "God created marital intimacy and declared it good and holy. \"Marriage should be honored by all, and the marriage bed kept pure.\" (Hebrews 13:4) Far from being a shameful subject, the physical and emotional union of spouses is a gift from God, to be protected and cultivated with respect.\n\nTrue intimacy is not reduced to the body: it embraces heart, soul and spirit. To become \"one flesh\" (Genesis 2:24) is to know each other deeply, without a mask and without fear. This transparency is built in the safety of commitment: we open up fully only where we know we are loved unconditionally.\n\nFaithfulness protects this garden. \"Drink water from your own cistern... may you ever be intoxicated with her love.\" (Proverbs 5:15-19) The world trivializes adultery, but God calls us to guard our heart, our eyes and our steps. Faithfulness begins in the thoughts, long before the acts; that is where we must watch.\n\nProtecting your marriage requires wise boundaries: avoiding ambiguous closeness, fleeing pornography, cultivating transparency and nurturing attraction to your spouse. \"Each of you should learn to control your own body in a way that is holy and honorable.\" (1 Thessalonians 4:4) Faithfulness is not only the absence of betrayal, it is the active presence of a love that chooses the same person every day.",
            es: "Dios creó la intimidad conyugal y la declaró buena y santa. «Honroso sea en todos el matrimonio, y el lecho sin mancilla.» (Hebreos 13:4) Lejos de ser un tema vergonzoso, la unión física y afectiva de los esposos es un regalo de Dios, que se debe proteger y cultivar con respeto.\n\nLa verdadera intimidad no se reduce al cuerpo: abarca el corazón, el alma y el espíritu. Llegar a ser «una sola carne» (Génesis 2:24) es conocerse profundamente, sin máscara y sin miedo. Esta transparencia se construye en la seguridad del compromiso: uno se abre plenamente solo donde se sabe amado sin condiciones.\n\nLa fidelidad protege este jardín. «Bebe el agua de tu misma cisterna... en su amor recréate siempre.» (Proverbios 5:15-19) El mundo banaliza el adulterio, pero Dios llama a guardar el corazón, los ojos y los pasos. La fidelidad comienza en los pensamientos, mucho antes que en los actos; allí hay que velar.\n\nProteger tu matrimonio requiere límites sabios: evitar cercanías ambiguas, huir de la pornografía, cultivar la transparencia y alimentar la atracción hacia tu cónyuge. «Que cada uno sepa tener su propio cuerpo en santidad y honor.» (1 Tesalonicenses 4:4) La fidelidad no es solo la ausencia de traición, es la presencia activa de un amor que escoge a la misma persona cada día.",
          },
          keyPoints: {
            fr: ["L'intimité conjugale est un don saint de Dieu (Hébreux 13.4)", "Devenir une seule chair : cœur, âme et corps (Genèse 2.24)", "La fidélité commence dans les pensées (Proverbes 5.15-19)", "Poser des barrières sages pour protéger son couple (1 Th 4.4)"],
            ht: ["Entimite maryaj se yon kado sen Bondye (Ebre 13.4)", "Vin yon sèl chè : kè, nanm ak kò (Jenèz 2.24)", "Fidelite kòmanse nan panse (Pwovèb 5.15-19)", "Mete baryè saj pou pwoteje koup ou (1 Tes 4.4)"],
            en: ["Marital intimacy is a holy gift from God (Hebrews 13:4)", "Become one flesh: heart, soul and body (Genesis 2:24)", "Faithfulness begins in the thoughts (Proverbs 5:15-19)", "Set wise boundaries to protect your marriage (1 Th 4:4)"],
            es: ["La intimidad conyugal es un don santo de Dios (Hebreos 13:4)", "Ser una sola carne: corazón, alma y cuerpo (Génesis 2:24)", "La fidelidad comienza en los pensamientos (Proverbios 5:15-19)", "Poner límites sabios para proteger tu matrimonio (1 Ts 4:4)"],
          },
          exercise: {
            fr: "Identifiez ensemble une « barrière de protection » concrète à mettre en place pour garder votre couple (par exemple sur le téléphone, les amitiés, les horaires) et un geste régulier pour nourrir votre intimité (une soirée dédiée, une attention hebdomadaire). Priez pour que Dieu garde vos cœurs et vos yeux fidèles.",
            ht: "Idantifye ansanm yon « baryè pwoteksyon » konkrè pou mete an plas pou kenbe koup ou (pa egzanp sou telefòn, zanmitay, orè) ak yon jès regilye pou nouri entimite w (yon aswè dedye, yon atansyon chak semèn). Priye pou Bondye kenbe kè nou ak je nou fidèl.",
            en: "Together, identify one concrete \"protective boundary\" to put in place to guard your marriage (for example around the phone, friendships, schedules) and one regular gesture to nurture your intimacy (a dedicated evening, a weekly attention). Pray that God keeps your hearts and eyes faithful.",
            es: "Identifiquen juntos un «límite de protección» concreto para poner en práctica y guardar su matrimonio (por ejemplo sobre el teléfono, las amistades, los horarios) y un gesto regular para alimentar su intimidad (una noche dedicada, una atención semanal). Oren para que Dios guarde sus corazones y sus ojos fieles.",
          },
          verse: "Hébreux 13.4",
        },
      ],
    },
    {
      title: { fr: "Élever les enfants dans la foi", ht: "Elve timoun nan lafwa", en: "Raising children in the faith", es: "Criar a los hijos en la fe" },
      lessons: [
        {
          slug: "eduquer-selon-dieu",
          title: { fr: "Éduquer selon le cœur de Dieu", ht: "Edike selon kè Bondye", en: "Raising children after God's heart", es: "Educar según el corazón de Dios" },
          videoId: "",
          content: {
            fr: "Les enfants sont un don précieux : « Voici, des enfants sont un héritage de l'Éternel, le fruit des entrailles est une récompense. » (Psaume 127.3) Les parents ne sont pas propriétaires de leurs enfants, mais intendants : Dieu les leur confie pour un temps afin de les élever pour lui.\n\nLa mission des parents est claire : « Tu les inculqueras à tes enfants, et tu en parleras quand tu seras dans ta maison, quand tu iras en voyage, quand tu te coucheras et quand tu te lèveras. » (Deutéronome 6.7) La foi ne se transmet pas seulement à l'église, mais dans la vie quotidienne, par l'exemple et la conversation.\n\n« Instruis l'enfant selon la voie qu'il doit suivre ; et quand il sera vieux, il ne s'en détournera pas. » (Proverbes 22.6) Éduquer, ce n'est pas imposer, c'est former le caractère avec amour et fermeté. Les enfants oublient beaucoup de nos paroles, mais ils n'oublient jamais qui nous étions.\n\nAvant d'instruire par la parole, les parents instruisent par l'exemple. « Timothée, dès l'enfance, tu connais les saintes lettres » écrit Paul, rappelant « la foi qui a d'abord habité dans ta grand-mère Loïs et dans ta mère Eunice. » (2 Timothée 1.5 ; 3.15) Une foi vécue avec cohérence dans le foyer marque plus profondément qu'un long discours. Nos enfants deviennent souvent ce qu'ils nous voient être.",
            ht: "Timoun se yon kado presye : « Gade, timoun se yon eritaj Senyè a, fwi vant se yon rekonpans. » (Sòm 127.3) Paran yo pa pwopriyetè timoun yo, men jeran : Bondye konfye yo ba yo pou yon tan pou elve yo pou li.\n\nMisyon paran yo klè : « W ap anseye yo bay pitit ou yo, e w ap pale de yo lè w lakay ou, lè w ap vwayaje, lè w kouche e lè w leve. » (Detewonòm 6.7) Lafwa pa transmèt sèlman nan legliz, men nan lavi chak jou, pa egzanp ak konvèsasyon.\n\n« Enstwi timoun nan selon chemen li dwe swiv ; e lè li granmoun, li p ap detounen. » (Pwovèb 22.6) Edike se pa enpoze, se fòme karaktè ak lanmou e fèmte. Timoun bliye anpil nan pawòl nou yo, men yo pa janm bliye ki moun nou te ye.\n\nAnvan yo enstwi ak pawòl, paran yo enstwi ak egzanp. « Timote, depi timoun ou konnen sent ekriti yo » Pòl ekri, li raple « lafwa ki te dabò abite nan grann ou Loyis ak nan manman ou Enis. » (2 Timote 1.5 ; 3.15) Yon lafwa ki viv ak koyerans nan fwaye a make pi pwofon pase yon long diskou. Timoun nou yo souvan vin sa yo wè nou ye.",
            en: "Children are a precious gift: \"Children are a heritage from the Lord, offspring a reward from him.\" (Psalm 127:3) Parents are not owners of their children, but stewards: God entrusts them for a time so they may be raised for him.\n\nThe parents' mission is clear: \"Impress them on your children. Talk about them when you sit at home and when you walk along the road, when you lie down and when you get up.\" (Deuteronomy 6:7) Faith is not transmitted only at church, but in daily life, through example and conversation.\n\n\"Start children off on the way they should go, and even when they are old they will not turn from it.\" (Proverbs 22:6) To raise a child is not to impose, but to form character with love and firmness. Children forget many of our words, but they never forget who we were.\n\nBefore instructing by words, parents instruct by example. \"From infancy you have known the Holy Scriptures,\" Paul writes to Timothy, recalling \"the faith that first lived in your grandmother Lois and in your mother Eunice.\" (2 Timothy 1:5; 3:15) A faith lived with consistency in the home marks more deeply than a long speech. Our children often become what they see us to be.",
            es: "Los hijos son un regalo precioso: «He aquí, herencia de Jehová son los hijos; cosa de estima el fruto del vientre.» (Salmo 127:3) Los padres no son dueños de sus hijos, sino administradores: Dios se los confía por un tiempo para criarlos para él.\n\nLa misión de los padres es clara: «Las repetirás a tus hijos, y hablarás de ellas estando en tu casa, y andando por el camino, al acostarte, y cuando te levantes.» (Deuteronomio 6:7) La fe no se transmite solo en la iglesia, sino en la vida diaria, por el ejemplo y la conversación.\n\n«Instruye al niño en su camino, y aun cuando fuere viejo no se apartará de él.» (Proverbios 22:6) Educar no es imponer, es formar el carácter con amor y firmeza. Los hijos olvidan muchas de nuestras palabras, pero nunca olvidan quiénes fuimos.\n\nAntes de instruir con la palabra, los padres instruyen con el ejemplo. «Desde la niñez has sabido las Sagradas Escrituras» escribe Pablo a Timoteo, recordando «la fe que habitó primero en tu abuela Loida, y en tu madre Eunice.» (2 Timoteo 1:5; 3:15) Una fe vivida con coherencia en el hogar marca más profundamente que un largo discurso. Nuestros hijos a menudo llegan a ser lo que nos ven ser.",
          },
          keyPoints: {
            fr: ["Les enfants sont un héritage confié par Dieu (Ps 127.3)", "Transmettre la foi au quotidien (Deutéronome 6.7)", "Former le caractère avec amour et fermeté (Pr 22.6)", "L'exemple des parents marque plus que les paroles (2 Tim 1.5)"],
            ht: ["Timoun se yon eritaj Bondye konfye (Sòm 127.3)", "Transmèt lafwa chak jou (Detewonòm 6.7)", "Fòme karaktè ak lanmou e fèmte (Pwovèb 22.6)", "Egzanp paran make plis pase pawòl (2 Tim 1.5)"],
            en: ["Children are a heritage entrusted by God (Ps 127:3)", "Pass on faith in daily life (Deuteronomy 6:7)", "Form character with love and firmness (Pr 22:6)", "Parents' example marks more than words (2 Tim 1:5)"],
            es: ["Los hijos son herencia confiada por Dios (Sal 127:3)", "Transmitir la fe a diario (Deuteronomio 6:7)", "Formar el carácter con amor y firmeza (Pr 22:6)", "El ejemplo de los padres marca más que las palabras (2 Tim 1:5)"],
          },
          exercise: {
            fr: "Instaurez cette semaine un moment quotidien simple de foi en famille : un court verset au repas, une prière avant le coucher ou une question sur la journée éclairée par la Parole. Demandez-vous honnêtement : « Qu'est-ce que mes enfants apprennent en me regardant vivre ? » et notez un point à ajuster.",
            ht: "Enstore semèn sa a yon moman senp chak jou pou lafwa an fanmi : yon ti vèsè nan repa a, yon lapriyè anvan dòmi oswa yon kesyon sou jounen an eklere pa Pawòl la. Mande tèt ou onètman : « Kisa pitit mwen yo aprann lè yo gade m viv ? » e note yon pwen pou ajiste.",
            en: "This week, set up a simple daily moment of faith as a family: a short verse at a meal, a prayer before bed, or a question about the day shaped by the Word. Ask yourself honestly: \"What are my children learning by watching me live?\" and note one thing to adjust.",
            es: "Esta semana, establece un momento diario sencillo de fe en familia: un versículo corto en la comida, una oración antes de dormir o una pregunta sobre el día iluminada por la Palabra. Pregúntate con honestidad: «¿Qué aprenden mis hijos al verme vivir?» y anota un punto para ajustar.",
          },
          verse: "Deutéronome 6.6-7",
        },
        {
          slug: "foyer-centre-sur-christ",
          title: { fr: "Un foyer centré sur Christ", ht: "Yon fwaye ki santre sou Kris", en: "A Christ-centered home", es: "Un hogar centrado en Cristo" },
          videoId: "",
          content: {
            fr: "Le climat spirituel d'une maison ne se décrète pas, il se cultive. Josué a fait cette déclaration devant tout Israël : « Moi et ma maison, nous servirons l'Éternel. » (Josué 24.15) Un foyer centré sur Christ commence par un choix clair et assumé des parents.\n\nCe choix se traduit par des habitudes simples : prier ensemble, lire la Parole, se pardonner, ouvrir sa maison à la communauté et honorer Dieu dans les décisions. La foi ne se limite pas au dimanche ; elle imprègne la table, les conflits, les projets et les loisirs. Les enfants apprennent à connaître Dieu d'abord en voyant leurs parents marcher avec lui.\n\nUn foyer chrétien n'est pas un foyer parfait, mais un foyer où Christ est invité au centre de tout, où la grâce couvre les échecs et où l'amour l'emporte. « Si l'Éternel ne garde la ville, celui qui la garde veille en vain. » (Psaume 127.1) Confiez chaque jour votre maison à celui qui la bâtit.\n\nUn tel foyer devient aussi un lieu de refuge et d'hospitalité. « Que l'amour fraternel demeure. N'oubliez pas l'hospitalité. » (Hébreux 13.1-2) Une maison où l'on prie, où l'on accueille, où l'on encourage, rayonne au-delà de ses murs. Ce que Dieu bâtit dans une famille, il s'en sert pour bénir tout un voisinage, une église, une génération.",
            ht: "Klima espirityèl yon kay pa dekrete, li kiltive. Jozye te fè deklarasyon sa a devan tout Izrayèl : « Mwen menm ak fanmi mwen, n ap sèvi Senyè a. » (Jozye 24.15) Yon fwaye ki santre sou Kris kòmanse pa yon chwa klè paran yo pran.\n\nChwa sa a tradui nan abitid senp : priye ansanm, li Pawòl la, padonnen youn lòt, louvri kay ou pou kominote a e onore Bondye nan desizyon yo. Lafwa pa limite nan dimanch ; li antre nan tab la, nan konfli yo, nan pwojè yo ak nan lwazi. Timoun aprann konnen Bondye dabò lè yo wè paran yo mache avè l.\n\nYon fwaye kretyen se pa yon fwaye pafè, men yon fwaye kote Kris envite nan sant tout bagay, kote gras kouvri echèk yo e kote lanmou pran devan. « Si Senyè a pa veye vil la, moun k ap veye l la veye pou granmesi. » (Sòm 127.1) Konfye kay nou chak jou bay sila k ap bati l la.\n\nYon fwaye konsa vin tou yon kote refij ak lospitalite. « Se pou lanmou fratènèl rete. Pa bliye lospitalite. » (Ebre 13.1-2) Yon kay kote moun priye, kote moun akeyi, kote moun ankouraje, klere pi lwen pase mi li. Sa Bondye bati nan yon fanmi, li sèvi avè l pou beni yon katye antye, yon legliz, yon jenerasyon.",
            en: "The spiritual climate of a home is not decreed, it is cultivated. Joshua made this declaration before all Israel: \"As for me and my household, we will serve the Lord.\" (Joshua 24:15) A Christ-centered home begins with a clear and owned choice by the parents.\n\nThis choice is expressed through simple habits: praying together, reading the Word, forgiving one another, opening your home to the community and honoring God in decisions. Faith is not limited to Sunday; it permeates the table, the conflicts, the projects and the leisure. Children first learn to know God by seeing their parents walk with him.\n\nA Christian home is not a perfect home, but a home where Christ is invited to the center of everything, where grace covers failures and where love prevails. \"Unless the Lord watches over the city, the guards stand watch in vain.\" (Psalm 127:1) Entrust your home each day to the one who builds it.\n\nSuch a home also becomes a place of refuge and hospitality. \"Keep on loving one another as brothers and sisters. Do not forget to show hospitality.\" (Hebrews 13:1-2) A house where people pray, welcome and encourage shines beyond its walls. What God builds in a family, he uses to bless a whole neighborhood, a church, a generation.",
            es: "El clima espiritual de un hogar no se decreta, se cultiva. Josué hizo esta declaración ante todo Israel: «Yo y mi casa serviremos a Jehová.» (Josué 24:15) Un hogar centrado en Cristo comienza con una decisión clara y asumida de los padres.\n\nEsta decisión se traduce en hábitos sencillos: orar juntos, leer la Palabra, perdonarse, abrir la casa a la comunidad y honrar a Dios en las decisiones. La fe no se limita al domingo; impregna la mesa, los conflictos, los proyectos y el descanso. Los hijos aprenden a conocer a Dios primero al ver a sus padres caminar con él.\n\nUn hogar cristiano no es un hogar perfecto, sino un hogar donde Cristo es invitado al centro de todo, donde la gracia cubre los fracasos y donde el amor prevalece. «Si Jehová no guardare la ciudad, en vano vela la guardia.» (Salmo 127:1) Confía tu casa cada día a aquel que la edifica.\n\nUn hogar así también se convierte en un lugar de refugio y hospitalidad. «Permanezca el amor fraternal. No os olvidéis de la hospitalidad.» (Hebreos 13:1-2) Una casa donde se ora, se acoge y se anima, brilla más allá de sus muros. Lo que Dios edifica en una familia, lo usa para bendecir a todo un vecindario, una iglesia, una generación.",
          },
          keyPoints: {
            fr: ["Choisir de servir Dieu en famille (Josué 24.15)", "La foi imprègne le quotidien, pas seulement le dimanche", "Un foyer imparfait mais couvert par la grâce (Ps 127.1)", "Un foyer de prière rayonne par l'hospitalité (Hébreux 13.1-2)"],
            ht: ["Chwazi sèvi Bondye an fanmi (Jozye 24.15)", "Lafwa antre nan chak jou, pa sèlman dimanch", "Yon fwaye enpafè men kouvri ak gras (Sòm 127.1)", "Yon fwaye lapriyè klere ak lospitalite (Ebre 13.1-2)"],
            en: ["Choose to serve God as a family (Joshua 24:15)", "Faith permeates daily life, not just Sunday", "An imperfect home but covered by grace (Ps 127:1)", "A praying home shines through hospitality (Hebrews 13:1-2)"],
            es: ["Escoger servir a Dios en familia (Josué 24:15)", "La fe impregna lo cotidiano, no solo el domingo", "Un hogar imperfecto pero cubierto por la gracia (Sal 127:1)", "Un hogar de oración brilla por la hospitalidad (Hebreos 13:1-2)"],
          },
          exercise: {
            fr: "En famille, définissez ensemble une « devise de maison » inspirée de Josué 24.15, et choisissez une habitude spirituelle simple à instaurer ce mois-ci (un temps de prière fixe, un repas d'accueil pour quelqu'un de seul). Écrivez-la et priez pour que votre foyer soit une lumière au-delà de ses murs.",
            ht: "An fanmi, defini ansanm yon « deviz kay » ki enspire de Jozye 24.15, e chwazi yon abitid espirityèl senp pou enstore mwa sa a (yon tan lapriyè fiks, yon repa akèy pou yon moun ki poukont li). Ekri l e priye pou fwaye w a se yon limyè pi lwen pase mi li.",
            en: "As a family, define together a \"house motto\" inspired by Joshua 24:15, and choose one simple spiritual habit to establish this month (a set prayer time, a welcome meal for someone who is alone). Write it down and pray that your home may be a light beyond its walls.",
            es: "En familia, definan juntos un «lema de la casa» inspirado en Josué 24:15, y escojan un hábito espiritual sencillo para establecer este mes (un tiempo fijo de oración, una comida de acogida para alguien que está solo). Escríbanlo y oren para que su hogar sea una luz más allá de sus muros.",
          },
          verse: "Josué 24.15",
        },
        {
          slug: "discipline-et-encouragement",
          title: { fr: "La discipline et l'encouragement", ht: "Disiplin ak ankourajman", en: "Discipline and encouragement", es: "La disciplina y el aliento" },
          videoId: "",
          content: {
            fr: "Éduquer un enfant demande deux mains : celle de la fermeté et celle de la tendresse. « Vous, pères, n'irritez pas vos enfants, mais élevez-les en les corrigeant et en les instruisant selon le Seigneur. » (Éphésiens 6.4) La discipline biblique n'est ni la sévérité écrasante ni le laxisme, mais une correction aimante orientée vers la croissance.\n\nLa discipline est une preuve d'amour, non de rejet. « Celui qui aime son fils s'empresse de le corriger. » (Proverbes 13.24) Un enfant à qui l'on ne dit jamais non grandit sans repères et sans sécurité. Poser des limites claires et constantes, avec calme et cohérence, aide l'enfant à comprendre le bien et le mal et à se sentir protégé.\n\nMais la discipline sans encouragement écrase, et l'encouragement sans discipline gâte. Les deux vont ensemble. « Que nulle parole malsaine ne sorte de votre bouche, mais s'il y a lieu, quelque bonne parole qui serve à l'édification. » (Éphésiens 4.29) Les enfants ont soif d'être vus, félicités et bénis par leurs parents ; un mot d'encouragement peut porter du fruit toute une vie.\n\nLe modèle ultime est notre Père céleste, qui « corrige celui qu'il aime » (Hébreux 12.6) tout en nous couvrant de sa bonté. Discipliner comme Dieu, c'est corriger sans humilier, exiger sans écraser, et toujours rappeler à l'enfant qu'il est aimé sans condition. Le but n'est pas d'obtenir l'obéissance par la peur, mais de gagner le cœur.",
            ht: "Edike yon timoun mande de men : sa ki fèm nan ak sa ki tandr la. « Nou menm papa, pa fè pitit nou yo fache, men elve yo ak korije yo e enstwi yo selon Senyè a. » (Efezyen 6.4) Disiplin biblik la se ni severite k ap kraze ni laksis, men yon koreksyon lanmou ki oryante vè kwasans.\n\nDisiplin se yon prèv lanmou, pa yon rejè. « Moun ki renmen pitit li prese korije l. » (Pwovèb 13.24) Yon timoun ou pa janm di non grandi san repè e san sekirite. Mete limit klè e konstan, ak kalm e koyerans, ede timoun nan konprann byen ak mal e santi l pwoteje.\n\nMen disiplin san ankourajman kraze, e ankourajman san disiplin gate. Toude ale ansanm. « Pa kite okenn move pawòl sòti nan bouch nou, men si gen okazyon, kèk bon pawòl ki sèvi pou edifikasyon. » (Efezyen 4.29) Timoun swaf pou paran yo wè yo, felisite yo e beni yo ; yon mo ankourajman ka pote fwi pou tout yon lavi.\n\nModèl final la se Papa selès nou an, ki « korije sila li renmen » (Ebre 12.6) pandan l kouvri nou ak bonte l. Disipline tankou Bondye, se korije san imilye, egzije san kraze, e toujou raple timoun nan li renmen san kondisyon. Bi a se pa jwenn obeyisans pa laperèz, men genyen kè a.",
            en: "Raising a child requires two hands: firmness and tenderness. \"Fathers, do not exasperate your children; instead, bring them up in the training and instruction of the Lord.\" (Ephesians 6:4) Biblical discipline is neither crushing severity nor permissiveness, but loving correction aimed at growth.\n\nDiscipline is a proof of love, not of rejection. \"Whoever loves their children is careful to discipline them.\" (Proverbs 13:24) A child who is never told no grows up without landmarks and without security. Setting clear and consistent limits, with calm and coherence, helps the child understand good and evil and feel protected.\n\nBut discipline without encouragement crushes, and encouragement without discipline spoils. The two go together. \"Do not let any unwholesome talk come out of your mouths, but only what is helpful for building others up.\" (Ephesians 4:29) Children long to be seen, praised and blessed by their parents; a word of encouragement can bear fruit for a lifetime.\n\nThe ultimate model is our heavenly Father, who \"disciplines the one he loves\" (Hebrews 12:6) while covering us with his goodness. To discipline like God is to correct without humiliating, to require without crushing, and always to remind the child that they are loved unconditionally. The goal is not to obtain obedience through fear, but to win the heart.",
            es: "Criar a un hijo requiere dos manos: la firmeza y la ternura. «Y vosotros, padres, no provoquéis a ira a vuestros hijos, sino criadlos en disciplina y amonestación del Señor.» (Efesios 6:4) La disciplina bíblica no es ni severidad aplastante ni permisividad, sino una corrección amorosa orientada al crecimiento.\n\nLa disciplina es una prueba de amor, no de rechazo. «El que ama a su hijo, desde temprano lo corrige.» (Proverbios 13:24) Un niño a quien nunca se le dice no crece sin referencias y sin seguridad. Poner límites claros y constantes, con calma y coherencia, ayuda al niño a comprender el bien y el mal y a sentirse protegido.\n\nPero la disciplina sin aliento aplasta, y el aliento sin disciplina malcría. Ambos van juntos. «Ninguna palabra corrompida salga de vuestra boca, sino la que sea buena para la necesaria edificación.» (Efesios 4:29) Los niños anhelan ser vistos, felicitados y bendecidos por sus padres; una palabra de aliento puede dar fruto toda una vida.\n\nEl modelo supremo es nuestro Padre celestial, que «al que ama, disciplina» (Hebreos 12:6) mientras nos cubre con su bondad. Disciplinar como Dios es corregir sin humillar, exigir sin aplastar, y recordar siempre al niño que es amado sin condiciones. La meta no es obtener obediencia por el miedo, sino ganar el corazón.",
          },
          keyPoints: {
            fr: ["Élever sans irriter, corriger selon le Seigneur (Éph 6.4)", "La discipline est une preuve d'amour (Proverbes 13.24)", "Encourager par des paroles qui édifient (Éph 4.29)", "Corriger comme Dieu : sans humilier, pour gagner le cœur (Héb 12.6)"],
            ht: ["Elve san fache, korije selon Senyè a (Efez 6.4)", "Disiplin se yon prèv lanmou (Pwovèb 13.24)", "Ankouraje ak pawòl ki edifye (Efez 4.29)", "Korije tankou Bondye : san imilye, pou genyen kè (Ebre 12.6)"],
            en: ["Bring them up without exasperating, correct in the Lord (Eph 6:4)", "Discipline is a proof of love (Proverbs 13:24)", "Encourage with words that build up (Eph 4:29)", "Correct like God: without humiliating, to win the heart (Heb 12:6)"],
            es: ["Criar sin provocar, corregir según el Señor (Ef 6:4)", "La disciplina es una prueba de amor (Proverbios 13:24)", "Alentar con palabras que edifican (Ef 4:29)", "Corregir como Dios: sin humillar, para ganar el corazón (Heb 12:6)"],
          },
          exercise: {
            fr: "Cette semaine, pour chaque correction que vous donnez à un enfant, ajoutez délibérément trois encouragements sincères. Prenez aussi un moment seul avec chaque enfant pour lui dire précisément une qualité que vous admirez en lui et prier pour lui. Observez comment son cœur s'ouvre.",
            ht: "Semèn sa a, pou chak koreksyon ou bay yon timoun, ajoute espre twa ankourajman sensè. Pran tou yon moman poukont ou ak chak timoun pou di l presi yon kalite ou admire nan li e priye pou li. Obsève kijan kè l ouvri.",
            en: "This week, for every correction you give a child, deliberately add three sincere encouragements. Also take a moment alone with each child to tell them precisely one quality you admire in them and to pray for them. Watch how their heart opens.",
            es: "Esta semana, por cada corrección que des a un hijo, añade deliberadamente tres alientos sinceros. Toma también un momento a solas con cada hijo para decirle con precisión una cualidad que admiras en él y orar por él. Observa cómo se abre su corazón.",
          },
          verse: "Éphésiens 6.4",
        },
      ],
    },
    {
      title: { fr: "Fondations pratiques et héritage familial", ht: "Fondasyon pratik ak eritaj fanmi an", en: "Practical foundations and family legacy", es: "Fundamentos prácticos y legado familiar" },
      lessons: [
        {
          slug: "honorer-parents-et-aines",
          title: { fr: "Honorer ses parents et ses aînés", ht: "Onore paran ak granmoun yo", en: "Honoring parents and elders", es: "Honrar a los padres y a los mayores" },
          videoId: "",
          content: {
            fr: "Le respect des parents est si important qu'il figure dans les dix commandements, comme un pilier de toute société stable. « Honore ton père et ta mère, afin que tes jours se prolongent dans le pays que l'Éternel, ton Dieu, te donne. » (Exode 20.12) C'est le premier commandement accompagné d'une promesse.\n\nPaul le rappelle aux familles chrétiennes : « Enfants, obéissez à vos parents, selon le Seigneur, car cela est juste. » (Éphésiens 6.1) Honorer, c'est plus qu'obéir dans l'enfance : c'est respecter, écouter et valoriser ses parents tout au long de la vie, même adulte. La manière dont nous traitons nos parents enseigne à nos enfants comment ils nous traiteront un jour.\n\nCet honneur s'étend aux personnes âgées et aux aînés dans la foi. « Lève-toi devant les cheveux blancs, et honore la personne du vieillard. » (Lévitique 19.32) Une société qui méprise ses anciens perd sa mémoire et sa sagesse. Dieu place dans les générations précédentes un trésor d'expérience et de foi à recueillir.\n\nHonorer ses parents inclut aussi de prendre soin d'eux dans leur vieillesse. Jésus a repris ceux qui négligeaient leurs parents sous prétexte de religion (Marc 7.10-13), et Paul affirme : « Si quelqu'un n'a pas soin des siens... il a renié la foi. » (1 Timothée 5.8) L'honneur véritable se prouve en actes de service concrets, pas seulement en paroles.",
            ht: "Respè pou paran yo si enpòtan ke li nan dis kòmandman yo, kòm yon pilye tout sosyete ki estab. « Onore papa w ak manman w, pou jou w yo ka pwolonje nan peyi Senyè a, Bondye w la, ba ou. » (Egzòd 20.12) Se premye kòmandman ki gen yon pwomès avè l.\n\nPòl raple fanmi kretyen yo : « Timoun, obeyi paran nou selon Senyè a, paske sa jis. » (Efezyen 6.1) Onore, se plis pase obeyi nan anfans : se respekte, koute e valorize paran ou pandan tout lavi, menm granmoun. Fason nou trete paran nou anseye pitit nou kijan yo ap trete nou yon jou.\n\nOnè sa a rive jwenn granmoun aje yo ak ansyen nan lafwa yo. « Kanpe devan cheve blanch, e onore granmoun aje a. » (Levitik 19.32) Yon sosyete ki meprize ansyen l yo pèdi memwa l ak sajès li. Bondye mete nan jenerasyon anvan yo yon trezò eksperyans ak lafwa pou rekeyi.\n\nOnore paran w gen ladan tou pran swen yo nan vyeyès yo. Jezi te reprimande sila yo ki neglije paran yo anba pretèks relijyon (Mak 7.10-13), e Pòl afime : « Si yon moun pa pran swen moun pa l yo... li nye lafwa. » (1 Timote 5.8) Vrè onè pwouve tèt li nan aksyon sèvis konkrè, pa sèlman nan pawòl.",
            en: "Respect for parents is so important that it appears in the Ten Commandments, as a pillar of every stable society. \"Honor your father and your mother, so that you may live long in the land the Lord your God is giving you.\" (Exodus 20:12) It is the first commandment with a promise attached.\n\nPaul reminds Christian families: \"Children, obey your parents in the Lord, for this is right.\" (Ephesians 6:1) To honor is more than to obey in childhood: it is to respect, listen to and value your parents throughout life, even as an adult. The way we treat our parents teaches our children how they will one day treat us.\n\nThis honor extends to the elderly and to elders in the faith. \"Stand up in the presence of the aged, show respect for the elderly.\" (Leviticus 19:32) A society that despises its elders loses its memory and its wisdom. God places in the previous generations a treasure of experience and faith to be gathered.\n\nHonoring your parents also includes caring for them in their old age. Jesus rebuked those who neglected their parents under the pretext of religion (Mark 7:10-13), and Paul states: \"Anyone who does not provide for their relatives... has denied the faith.\" (1 Timothy 5:8) True honor proves itself in concrete acts of service, not only in words.",
            es: "El respeto a los padres es tan importante que figura en los diez mandamientos, como un pilar de toda sociedad estable. «Honra a tu padre y a tu madre, para que tus días se alarguen en la tierra que Jehová tu Dios te da.» (Éxodo 20:12) Es el primer mandamiento acompañado de una promesa.\n\nPablo lo recuerda a las familias cristianas: «Hijos, obedeced en el Señor a vuestros padres, porque esto es justo.» (Efesios 6:1) Honrar es más que obedecer en la infancia: es respetar, escuchar y valorar a los padres a lo largo de la vida, aun siendo adulto. La manera en que tratamos a nuestros padres enseña a nuestros hijos cómo nos tratarán un día.\n\nEste honor se extiende a los ancianos y a los mayores en la fe. «Delante de las canas te levantarás, y honrarás el rostro del anciano.» (Levítico 19:32) Una sociedad que desprecia a sus ancianos pierde su memoria y su sabiduría. Dios coloca en las generaciones anteriores un tesoro de experiencia y de fe para recoger.\n\nHonrar a los padres incluye también cuidarlos en su vejez. Jesús reprendió a los que descuidaban a sus padres con el pretexto de la religión (Marcos 7:10-13), y Pablo afirma: «Si alguno no provee para los suyos... ha negado la fe.» (1 Timoteo 5:8) El verdadero honor se prueba en actos de servicio concretos, no solo en palabras.",
          },
          keyPoints: {
            fr: ["Honorer ses parents : commandement avec promesse (Exode 20.12)", "Honorer, c'est respecter à vie, pas seulement obéir enfant (Éph 6.1)", "Respecter les aînés et les cheveux blancs (Lévitique 19.32)", "Prendre soin de ses parents âgés, en actes (1 Tim 5.8)"],
            ht: ["Onore paran : kòmandman ak pwomès (Egzòd 20.12)", "Onore, se respekte pou tout lavi, pa sèlman obeyi timoun (Efez 6.1)", "Respekte ansyen yo ak cheve blanch (Levitik 19.32)", "Pran swen paran aje yo, an aksyon (1 Tim 5.8)"],
            en: ["Honor your parents: commandment with a promise (Exodus 20:12)", "To honor is lifelong respect, not just childhood obedience (Eph 6:1)", "Respect elders and the gray-haired (Leviticus 19:32)", "Care for your aging parents, in deeds (1 Tim 5:8)"],
            es: ["Honrar a los padres: mandamiento con promesa (Éxodo 20:12)", "Honrar es respetar de por vida, no solo obedecer de niño (Ef 6:1)", "Respetar a los mayores y las canas (Levítico 19:32)", "Cuidar a los padres ancianos, en hechos (1 Tim 5:8)"],
          },
          exercise: {
            fr: "Cette semaine, posez un geste concret d'honneur envers vos parents ou un aîné : un appel, une visite, un service, un mot de reconnaissance pour ce qu'ils vous ont transmis. Si la relation est blessée, demandez à Dieu la grâce d'un premier pas de respect. Notez ce que vous voulez transmettre à la génération suivante.",
            ht: "Semèn sa a, poze yon jès konkrè onè anvè paran ou oswa yon granmoun : yon apèl, yon vizit, yon sèvis, yon mo rekonesans pou sa yo transmèt ou. Si relasyon an blese, mande Bondye gras pou yon premye pa respè. Note sa w vle transmèt bay jenerasyon k ap vini an.",
            en: "This week, make one concrete gesture of honor toward your parents or an elder: a call, a visit, an act of service, a word of gratitude for what they passed on to you. If the relationship is wounded, ask God for the grace of a first step of respect. Note what you want to pass on to the next generation.",
            es: "Esta semana, haz un gesto concreto de honra hacia tus padres o un mayor: una llamada, una visita, un servicio, una palabra de gratitud por lo que te transmitieron. Si la relación está herida, pide a Dios la gracia de un primer paso de respeto. Anota lo que quieres transmitir a la próxima generación.",
          },
          verse: "Exode 20.12",
        },
        {
          slug: "gerer-les-finances-du-foyer",
          title: { fr: "Gérer les finances du foyer", ht: "Jere finans fwaye a", en: "Managing the household finances", es: "Administrar las finanzas del hogar" },
          videoId: "",
          content: {
            fr: "L'argent est l'une des premières causes de tension dans les couples, mais la Bible offre une sagesse claire pour gérer les finances du foyer dans la paix. Tout commence par une vérité fondamentale : « À l'Éternel la terre et ce qu'elle renferme. » (Psaume 24.1) Nous ne sommes pas propriétaires mais gérants de ce que Dieu nous confie.\n\nLa première discipline est de ne pas vivre au-dessus de ses moyens. « L'emprunteur est l'esclave de celui qui prête. » (Proverbes 22.7) La dette non maîtrisée devient une prison qui pèse sur tout le foyer. À l'inverse, la Bible loue la prévoyance : « Il y a de précieux trésors et de l'huile dans la demeure du sage. » (Proverbes 21.20) Épargner, budgétiser et planifier honorent Dieu.\n\nDonner fait partie de la gestion chrétienne des finances. « Honore l'Éternel avec tes biens, avec les prémices de tout ton revenu. » (Proverbes 3.9) Le croyant apprend à donner avec joie, à sa communauté et aux plus démunis, car « il y a plus de bonheur à donner qu'à recevoir. » (Actes 20.35) La générosité brise l'emprise de l'argent sur le cœur.\n\nEnfin, le couple doit gérer les finances ensemble, avec transparence et accord. Les décisions financières cachées détruisent la confiance. « Deux valent mieux qu'un... si l'un tombe, l'autre le relève. » (Ecclésiaste 4.9-10) Priez ensemble sur vos décisions d'argent, fixez un budget commun, et souvenez-vous : « Vous ne pouvez servir Dieu et Mammon. » (Matthieu 6.24) L'argent est un bon serviteur mais un mauvais maître.",
            ht: "Lajan se youn nan premye kòz tansyon nan koup yo, men Bib la ofri yon sajès klè pou jere finans fwaye a nan lapè. Tout kòmanse ak yon verite fondamantal : « Se pou Senyè a tè a ak tou sa ki ladan l. » (Sòm 24.1) Nou pa pwopriyetè men jeran sa Bondye konfye nou.\n\nPremye disiplin nan se pou pa viv pi wo pase mwayen ou. « Moun ki prete se esklav moun ki prete l la. » (Pwovèb 22.7) Dèt ki pa kontwole vin yon prizon ki peze sou tout fwaye a. Okontrè, Bib la fè lwanj pou previzyon : « Gen trezò presye ak lwil nan kay saj la. » (Pwovèb 21.20) Ekonomize, fè bidjè e planifye onore Bondye.\n\nBay fè pati jesyon kretyen finans yo. « Onore Senyè a ak byen ou, ak premye fwi tout revni ou. » (Pwovèb 3.9) Kwayan an aprann bay ak lajwa, bay kominote l ak moun ki pi pòv yo, paske « gen plis bonè nan bay pase nan resevwa. » (Travay 20.35) Jenewozite kase pouvwa lajan sou kè a.\n\nAnfen, koup la dwe jere finans yo ansanm, ak transparans e antant. Desizyon finansye kache detwi konfyans. « De vo pi bon pase yon... si youn tonbe, lòt la leve l. » (Eklezyas 4.9-10) Priye ansanm sou desizyon lajan nou yo, fikse yon bidjè komen, e sonje : « Nou pa ka sèvi Bondye ak Manmon. » (Matye 6.24) Lajan se yon bon sèvitè men yon move mèt.",
            en: "Money is one of the leading causes of tension in couples, but the Bible offers clear wisdom for managing household finances in peace. It all begins with a fundamental truth: \"The earth is the Lord's, and everything in it.\" (Psalm 24:1) We are not owners but managers of what God entrusts to us.\n\nThe first discipline is not to live beyond your means. \"The borrower is slave to the lender.\" (Proverbs 22:7) Uncontrolled debt becomes a prison that weighs on the whole home. Conversely, the Bible praises foresight: \"The wise store up choice food and olive oil.\" (Proverbs 21:20) Saving, budgeting and planning honor God.\n\nGiving is part of the Christian management of finances. \"Honor the Lord with your wealth, with the firstfruits of all your crops.\" (Proverbs 3:9) The believer learns to give with joy, to their community and to those in need, for \"it is more blessed to give than to receive.\" (Acts 20:35) Generosity breaks money's grip on the heart.\n\nFinally, the couple should manage finances together, with transparency and agreement. Hidden financial decisions destroy trust. \"Two are better than one... if either of them falls, one can help the other up.\" (Ecclesiastes 4:9-10) Pray together over your money decisions, set a shared budget, and remember: \"You cannot serve both God and money.\" (Matthew 6:24) Money is a good servant but a bad master.",
            es: "El dinero es una de las principales causas de tensión en las parejas, pero la Biblia ofrece una sabiduría clara para administrar las finanzas del hogar en paz. Todo comienza con una verdad fundamental: «De Jehová es la tierra y su plenitud.» (Salmo 24:1) No somos dueños sino administradores de lo que Dios nos confía.\n\nLa primera disciplina es no vivir por encima de tus posibilidades. «El que toma prestado es siervo del que presta.» (Proverbios 22:7) La deuda no controlada se convierte en una prisión que pesa sobre todo el hogar. Por el contrario, la Biblia elogia la previsión: «Tesoro precioso y aceite hay en la casa del sabio.» (Proverbios 21:20) Ahorrar, presupuestar y planificar honran a Dios.\n\nDar es parte de la administración cristiana de las finanzas. «Honra a Jehová con tus bienes, y con las primicias de todos tus frutos.» (Proverbios 3:9) El creyente aprende a dar con gozo, a su comunidad y a los necesitados, porque «más bienaventurado es dar que recibir.» (Hechos 20:35) La generosidad rompe el dominio del dinero sobre el corazón.\n\nPor último, la pareja debe administrar las finanzas juntos, con transparencia y acuerdo. Las decisiones financieras ocultas destruyen la confianza. «Mejores son dos que uno... si cayeren, el uno levantará a su compañero.» (Eclesiastés 4:9-10) Oren juntos sobre sus decisiones de dinero, fijen un presupuesto común, y recuerden: «No podéis servir a Dios y a las riquezas.» (Mateo 6:24) El dinero es un buen siervo pero un mal amo.",
          },
          keyPoints: {
            fr: ["Nous sommes gérants, pas propriétaires (Psaume 24.1)", "Fuir la dette non maîtrisée, pratiquer la prévoyance (Pr 22.7)", "Donner avec joie brise l'emprise de l'argent (Actes 20.35)", "Gérer ensemble, avec transparence et prière (Ecc 4.9-10)"],
            ht: ["Nou se jeran, pa pwopriyetè (Sòm 24.1)", "Kouri kite dèt ki pa kontwole, pratike previzyon (Pwov 22.7)", "Bay ak lajwa kase pouvwa lajan (Travay 20.35)", "Jere ansanm, ak transparans e lapriyè (Ekl 4.9-10)"],
            en: ["We are managers, not owners (Psalm 24:1)", "Flee uncontrolled debt, practice foresight (Pr 22:7)", "Giving with joy breaks money's grip (Acts 20:35)", "Manage together, with transparency and prayer (Ecc 4:9-10)"],
            es: ["Somos administradores, no dueños (Salmo 24:1)", "Huir de la deuda no controlada, practicar la previsión (Pr 22:7)", "Dar con gozo rompe el dominio del dinero (Hechos 20:35)", "Administrar juntos, con transparencia y oración (Ecl 4:9-10)"],
          },
          exercise: {
            fr: "Asseyez-vous en couple (ou seul) pour poser à plat vos revenus, vos dépenses et vos dettes, sans reproche mais avec honnêteté. Fixez ensemble un budget simple, décidez d'un montant à donner et d'un montant à épargner, et priez pour confier vos finances au Seigneur, votre vrai pourvoyeur.",
            ht: "Chita an koup (oswa poukont ou) pou mete aplat revni w, depans ou ak dèt ou, san repwòch men ak onètte. Fikse ansanm yon bidjè senp, deside yon montan pou bay e yon montan pou ekonomize, e priye pou konfye finans ou bay Senyè a, vrè founisè w.",
            en: "Sit down as a couple (or alone) to lay out your income, expenses and debts, without blame but with honesty. Together set a simple budget, decide on an amount to give and an amount to save, and pray to entrust your finances to the Lord, your true provider.",
            es: "Siéntense en pareja (o solo) para poner sobre la mesa tus ingresos, gastos y deudas, sin reproches pero con honestidad. Fijen juntos un presupuesto sencillo, decidan una cantidad para dar y una para ahorrar, y oren para entregar sus finanzas al Señor, tu verdadero proveedor.",
          },
          verse: "Proverbes 3.9-10",
        },
        {
          slug: "famille-temoignage-et-heritage",
          title: { fr: "La famille, lumière et héritage", ht: "Fanmi an, limyè ak eritaj", en: "The family, light and legacy", es: "La familia, luz y legado" },
          videoId: "",
          content: {
            fr: "Une famille selon Dieu n'existe pas seulement pour elle-même : elle est appelée à briller dans le monde. « Que votre lumière luise ainsi devant les hommes, afin qu'ils voient vos bonnes œuvres, et qu'ils glorifient votre Père. » (Matthieu 5.16) Un foyer où règnent l'amour, le pardon et la paix devient un témoignage vivant de l'Évangile.\n\nLe témoignage d'une famille touche d'abord ceux qui la composent, puis rayonne au-delà. Quand le geôlier de Philippes demanda comment être sauvé, Paul répondit : « Crois au Seigneur Jésus, et tu seras sauvé, toi et ta famille. » (Actes 16.31) Dieu a un plan de salut non seulement pour des individus, mais pour des maisonnées entières.\n\nLa famille est aussi le lieu où se transmet un héritage spirituel, de génération en génération. « Ce que nous avons entendu... nous ne le cacherons pas à leurs enfants ; nous dirons à la génération future les louanges de l'Éternel. » (Psaume 78.3-4) Ce que les parents sèment dans la foi peut porter du fruit chez leurs petits-enfants et au-delà. L'héritage le plus précieux n'est pas matériel, il est spirituel.\n\nEnfin, aucune famille n'est parfaite, et Dieu se plaît à écrire de belles histoires avec des familles brisées et restaurées. Regardez Joseph, vendu par ses frères puis réconcilié : « Vous aviez médité de me faire du mal, Dieu l'a changé en bien. » (Genèse 50.20) Quel que soit le passé de votre famille, il n'est jamais trop tard pour commencer à bâtir un héritage de foi. Confiez chaque membre au Seigneur : votre foyer peut devenir une bénédiction pour des générations.",
            ht: "Yon fanmi selon Bondye pa egziste sèlman pou tèt li : li rele pou klere nan monn nan. « Se pou limyè nou klere devan lèzòm, pou yo ka wè bon zèv nou yo, e pou yo bay Papa nou glwa. » (Matye 5.16) Yon fwaye kote lanmou, padon ak lapè renye vin yon temwayaj vivan Levanjil la.\n\nTemwayaj yon fanmi touche dabò sila ki ladan l yo, apre sa li klere pi lwen. Lè gadyen prizon Filip la te mande kijan pou l sove, Pòl reponn : « Kwè nan Senyè Jezi, e w ap sove, ou menm ak fanmi w. » (Travay 16.31) Bondye gen yon plan sali non sèlman pou moun endividyèl, men pou fanmi antye.\n\nFanmi an se tou kote yon eritaj espirityèl transmèt, de jenerasyon an jenerasyon. « Sa nou tande... nou p ap kache l pou pitit yo ; n ap di jenerasyon k ap vini an louwanj Senyè a. » (Sòm 78.3-4) Sa paran yo simen nan lafwa ka pote fwi nan pitit-pitit yo e pi lwen. Eritaj ki pi presye a se pa materyèl, li espirityèl.\n\nAnfen, pa gen fanmi ki pafè, e Bondye pran plezi ekri bèl istwa ak fanmi ki brize e ki restore. Gade Jozèf, vann pa frè l yo epi rekonsilye : « Nou te fè plan pou fè m mal, Bondye chanje l an byen. » (Jenèz 50.20) Kèlkeswa pase fanmi w, li pa janm twò ta pou kòmanse bati yon eritaj lafwa. Konfye chak manm bay Senyè a : fwaye w ka vin yon benediksyon pou jenerasyon.",
            en: "A family according to God does not exist only for itself: it is called to shine in the world. \"Let your light shine before others, that they may see your good deeds and glorify your Father.\" (Matthew 5:16) A home ruled by love, forgiveness and peace becomes a living testimony of the Gospel.\n\nA family's testimony first touches those within it, then radiates beyond. When the Philippian jailer asked how to be saved, Paul replied: \"Believe in the Lord Jesus, and you will be saved, you and your household.\" (Acts 16:31) God has a plan of salvation not only for individuals, but for entire households.\n\nThe family is also the place where a spiritual heritage is passed on, from generation to generation. \"What we have heard... we will not hide from their descendants; we will tell the next generation the praiseworthy deeds of the Lord.\" (Psalm 78:3-4) What parents sow in faith can bear fruit in their grandchildren and beyond. The most precious inheritance is not material, it is spiritual.\n\nFinally, no family is perfect, and God delights in writing beautiful stories with broken and restored families. Look at Joseph, sold by his brothers then reconciled: \"You intended to harm me, but God intended it for good.\" (Genesis 50:20) Whatever your family's past, it is never too late to begin building a legacy of faith. Entrust each member to the Lord: your home can become a blessing for generations.",
            es: "Una familia según Dios no existe solo para sí misma: está llamada a brillar en el mundo. «Así alumbre vuestra luz delante de los hombres, para que vean vuestras buenas obras, y glorifiquen a vuestro Padre.» (Mateo 5:16) Un hogar donde reinan el amor, el perdón y la paz se convierte en un testimonio vivo del Evangelio.\n\nEl testimonio de una familia toca primero a quienes la componen, luego irradia más allá. Cuando el carcelero de Filipos preguntó cómo ser salvo, Pablo respondió: «Cree en el Señor Jesucristo, y serás salvo, tú y tu casa.» (Hechos 16:31) Dios tiene un plan de salvación no solo para individuos, sino para casas enteras.\n\nLa familia es también el lugar donde se transmite una herencia espiritual, de generación en generación. «Lo que oímos... no lo encubriremos a sus hijos; contaremos a la generación venidera las alabanzas de Jehová.» (Salmo 78:3-4) Lo que los padres siembran en la fe puede dar fruto en sus nietos y más allá. La herencia más preciosa no es material, es espiritual.\n\nPor último, ninguna familia es perfecta, y Dios se complace en escribir hermosas historias con familias rotas y restauradas. Mira a José, vendido por sus hermanos y luego reconciliado: «Vosotros pensasteis mal contra mí, mas Dios lo encaminó a bien.» (Génesis 50:20) Sea cual sea el pasado de tu familia, nunca es tarde para empezar a construir un legado de fe. Entrega cada miembro al Señor: tu hogar puede convertirse en una bendición para generaciones.",
          },
          keyPoints: {
            fr: ["Le foyer est une lumière et un témoignage (Matthieu 5.16)", "Dieu sauve des maisonnées entières (Actes 16.31)", "Transmettre un héritage spirituel aux générations (Ps 78.3-4)", "Dieu restaure les familles brisées (Genèse 50.20)"],
            ht: ["Fwaye a se yon limyè ak yon temwayaj (Matye 5.16)", "Bondye sove fanmi antye (Travay 16.31)", "Transmèt yon eritaj espirityèl bay jenerasyon (Sòm 78.3-4)", "Bondye restore fanmi ki brize (Jenèz 50.20)"],
            en: ["The home is a light and a testimony (Matthew 5:16)", "God saves entire households (Acts 16:31)", "Pass on a spiritual legacy to generations (Ps 78:3-4)", "God restores broken families (Genesis 50:20)"],
            es: ["El hogar es una luz y un testimonio (Mateo 5:16)", "Dios salva casas enteras (Hechos 16:31)", "Transmitir un legado espiritual a las generaciones (Sal 78:3-4)", "Dios restaura las familias rotas (Génesis 50:20)"],
          },
          exercise: {
            fr: "Écrivez le nom de chaque membre de votre famille (y compris ceux qui sont loin de Dieu ou avec qui la relation est difficile) et priez nommément pour chacun, en réclamant la promesse d'Actes 16.31. Choisissez une valeur de foi que vous voulez laisser en héritage, et un geste de témoignage à poser cette semaine envers votre entourage.",
            ht: "Ekri non chak manm fanmi w (menm sila ki lwen Bondye oswa ak kiyès relasyon an difisil) e priye nominalman pou chak, reklame pwomès Travay 16.31 lan. Chwazi yon valè lafwa ou vle kite an eritaj, ak yon jès temwayaj pou poze semèn sa a anvè antouraj ou.",
            en: "Write the name of each member of your family (including those far from God or with whom the relationship is difficult) and pray by name for each one, claiming the promise of Acts 16:31. Choose one value of faith you want to leave as a legacy, and one gesture of witness to make this week toward those around you.",
            es: "Escribe el nombre de cada miembro de tu familia (incluidos los que están lejos de Dios o con quienes la relación es difícil) y ora por cada uno por su nombre, reclamando la promesa de Hechos 16:31. Escoge un valor de fe que quieras dejar como legado, y un gesto de testimonio para realizar esta semana hacia quienes te rodean.",
          },
          verse: "Actes 16.31",
        },
      ],
    },
  ],
};

export default famille;
