import { CourseContent } from "./types";

const google: CourseContent = {
  slug: "google",
  intro: {
    fr: "Maîtriser les outils Google gratuits : créer et sécuriser un compte, envoyer et organiser ses courriels avec Gmail, stocker et partager ses fichiers sur Drive, écrire avec Docs, calculer avec Sheets, se réunir avec Meet et organiser son temps avec Agenda.",
    ht: "Metrize zouti Google gratis yo : kreye epi sekirize yon kont, voye epi òganize imèl ak Gmail, estoke epi pataje fichye sou Drive, ekri ak Docs, kalkile ak Sheets, fè reyinyon ak Meet epi òganize tan ou ak Agenda.",
    en: "Master the free Google tools: create and secure an account, send and organize your emails with Gmail, store and share your files on Drive, write with Docs, calculate with Sheets, meet with Meet and organize your time with Calendar.",
    es: "Dominar las herramientas gratuitas de Google: crear y proteger una cuenta, enviar y organizar tus correos con Gmail, guardar y compartir tus archivos en Drive, escribir con Docs, calcular con Sheets, reunirte con Meet y organizar tu tiempo con Calendar.",
  },
  modules: [
    {
      title: { fr: "Le compte Google et Gmail", ht: "Kont Google la ak Gmail", en: "The Google account and Gmail", es: "La cuenta de Google y Gmail" },
      lessons: [
        {
          slug: "creer-un-compte-google",
          title: { fr: "Créer un compte Google", ht: "Kreye yon kont Google", en: "Creating a Google account", es: "Crear una cuenta de Google" },
          videoId: "",
          content: {
            fr: "Un compte Google est une clé unique qui ouvre gratuitement tous les services de Google : Gmail, Drive, Docs, Agenda, YouTube et bien d'autres. Créer ce compte une seule fois te donne accès à tout, avec la même adresse et le même mot de passe.\n\nPour le créer, va sur le site accounts.google.com et clique sur « Créer un compte ». On te demande ton prénom et ton nom, puis de choisir un nom d'utilisateur : c'est le début de ton adresse Gmail (par exemple jean.pierre@gmail.com). Si le nom est déjà pris, Google t'en propose d'autres. Choisis ensuite un mot de passe solide, que tu confirmes en le tapant deux fois.\n\nGoogle te demande souvent un numéro de téléphone. Il sert à protéger ton compte et à le récupérer si tu oublies ton mot de passe. Note bien ton adresse et ton mot de passe dans un endroit sûr. Une fois le compte créé, tu es prêt à utiliser tous les outils, chacun accessible d'un simple clic.\n\nUn bon mot de passe est ta première protection : mélange des lettres, des chiffres et des symboles, et évite les évidences comme ta date de naissance ou « 123456 ». En haut à droite de n'importe quelle page Google, un petit rond avec ton initiale ou ta photo indique que tu es bien connecté ; c'est aussi par là que tu passeras d'un service à l'autre.",
            ht: "Yon kont Google se yon kle inik ki louvri gratis tout sèvis Google yo : Gmail, Drive, Docs, Agenda, YouTube ak anpil lòt. Kreye kont sa a yon sèl fwa ba ou aksè a tout bagay, ak menm adrès la ak menm modpas la.\n\nPou kreye l, ale sou sit accounts.google.com epi klike sou « Kreye yon kont ». Yo mande w prenon ou ak non ou, apre chwazi yon non itilizatè : se kòmansman adrès Gmail ou (pa egzanp jan.pyè@gmail.com). Si non an deja pran, Google pwopoze w lòt. Chwazi apre yon modpas solid, ou konfime l lè w tape l de fwa.\n\nGoogle souvan mande w yon nimewo telefòn. Li sèvi pou pwoteje kont ou epi rekipere l si w bliye modpas ou. Note byen adrès ou ak modpas ou nan yon kote ki an sekirite. Yon fwa kont lan kreye, ou pare pou itilize tout zouti yo, chak aksesib ak yon senp klik.\n\nYon bon modpas se premye pwoteksyon ou : melanje lèt, chif ak senbòl, epi evite bagay ki evidan tankou dat nesans ou oswa « 123456 ». Anwo adwat nenpòt paj Google, yon ti won ak inisyal ou oswa foto ou montre ou byen konekte ; se la tou ou pral pase soti nan yon sèvis al nan yon lòt.",
            en: "A Google account is a single key that opens all of Google's services for free: Gmail, Drive, Docs, Calendar, YouTube and many more. Creating this account just once gives you access to everything, with the same address and the same password.\n\nTo create it, go to accounts.google.com and click \"Create account.\" You are asked for your first and last name, then to choose a username: this is the start of your Gmail address (for example jean.pierre@gmail.com). If the name is already taken, Google suggests others. Then choose a strong password, which you confirm by typing it twice.\n\nGoogle often asks for a phone number. It serves to protect your account and recover it if you forget your password. Write down your address and password in a safe place. Once the account is created, you are ready to use all the tools, each accessible with a single click.\n\nA good password is your first protection: mix letters, numbers and symbols, and avoid the obvious such as your birth date or \"123456\". At the top right of any Google page, a small circle with your initial or photo shows you are signed in; that is also where you will switch from one service to another.",
            es: "Una cuenta de Google es una llave única que abre gratis todos los servicios de Google: Gmail, Drive, Docs, Calendar, YouTube y muchos más. Crear esta cuenta una sola vez te da acceso a todo, con la misma dirección y la misma contraseña.\n\nPara crearla, ve al sitio accounts.google.com y haz clic en «Crear cuenta». Te piden tu nombre y apellido, luego elegir un nombre de usuario: es el comienzo de tu dirección de Gmail (por ejemplo juan.pedro@gmail.com). Si el nombre ya está tomado, Google te propone otros. Elige después una contraseña segura, que confirmas escribiéndola dos veces.\n\nGoogle suele pedir un número de teléfono. Sirve para proteger tu cuenta y recuperarla si olvidas tu contraseña. Anota bien tu dirección y contraseña en un lugar seguro. Una vez creada la cuenta, estás listo para usar todas las herramientas, cada una accesible con un simple clic.\n\nUna buena contraseña es tu primera protección: mezcla letras, números y símbolos, y evita lo obvio como tu fecha de nacimiento o «123456». Arriba a la derecha de cualquier página de Google, un pequeño círculo con tu inicial o foto muestra que has iniciado sesión; ahí también cambiarás de un servicio a otro.",
          },
          keyPoints: {
            fr: ["Un seul compte ouvre tous les services Google gratuits", "Le nom d'utilisateur devient ton adresse Gmail", "Note ton adresse et ton mot de passe dans un endroit sûr", "Un mot de passe solide mêle lettres, chiffres et symboles"],
            ht: ["Yon sèl kont louvri tout sèvis Google gratis yo", "Non itilizatè a vin adrès Gmail ou", "Note adrès ou ak modpas ou nan yon kote ki an sekirite", "Yon modpas solid melanje lèt, chif ak senbòl"],
            en: ["One account opens all free Google services", "The username becomes your Gmail address", "Write your address and password in a safe place", "A strong password mixes letters, numbers and symbols"],
            es: ["Una sola cuenta abre todos los servicios gratuitos de Google", "El nombre de usuario se convierte en tu dirección de Gmail", "Anota tu dirección y contraseña en un lugar seguro", "Una contraseña segura mezcla letras, números y símbolos"],
          },
          exercise: {
            fr: "Rends-toi sur accounts.google.com et crée un compte : renseigne ton nom, choisis un nom d'utilisateur disponible et un mot de passe solide. Note ton adresse Gmail complète et ton mot de passe sur un papier gardé en lieu sûr.",
            ht: "Ale sou accounts.google.com epi kreye yon kont : mete non ou, chwazi yon non itilizatè ki disponib ak yon modpas solid. Note adrès Gmail konplè ou ak modpas ou sou yon papye ou kenbe nan yon kote ki an sekirite.",
            en: "Go to accounts.google.com and create an account: enter your name, choose an available username and a strong password. Write your full Gmail address and password on paper kept in a safe place.",
            es: "Ve a accounts.google.com y crea una cuenta: introduce tu nombre, elige un nombre de usuario disponible y una contraseña segura. Anota tu dirección de Gmail completa y tu contraseña en un papel guardado en lugar seguro.",
          },
        },
        {
          slug: "envoyer-recevoir-gmail",
          title: { fr: "Envoyer et recevoir avec Gmail", ht: "Voye epi resevwa ak Gmail", en: "Sending and receiving with Gmail", es: "Enviar y recibir con Gmail" },
          videoId: "",
          content: {
            fr: "Gmail est ta boîte de courriel : elle sert à envoyer et recevoir des messages écrits, gratuitement et partout dans le monde. Pour l'ouvrir, va sur gmail.com ou clique sur l'icône Gmail. La page principale, appelée « boîte de réception », affiche la liste des messages reçus, les plus récents en haut.\n\nPour écrire un message, clique sur le bouton « Nouveau message » (souvent marqué d'un crayon ou d'un « + »). Une petite fenêtre s'ouvre. Dans le champ « À », tape l'adresse du destinataire. Dans « Objet », écris le sujet en quelques mots. Puis rédige ton texte dans la grande zone. Quand tout est prêt, clique sur « Envoyer ».\n\nPour lire un message reçu, clique simplement dessus : il s'ouvre en entier. Tu peux alors répondre en cliquant sur « Répondre », ou transférer le message à quelqu'un d'autre. Tu peux aussi joindre un fichier (photo, document) à un message que tu envoies grâce à l'icône en forme de trombone. Attention aux courriels d'inconnus : ne clique pas sur les liens douteux.\n\nQuelques bons réflexes rendent tes courriels plus efficaces. Écris un objet clair pour que le destinataire sache tout de suite de quoi il s'agit, commence par une formule de politesse et signe ton message. Le champ « Cc » permet d'envoyer une copie à d'autres personnes, tandis que « Cci » les met en copie sans que les autres voient leur adresse.",
            ht: "Gmail se bwat imèl ou : li sèvi pou voye ak resevwa mesaj ekri, gratis e toupatou nan lemonn. Pou louvri l, ale sou gmail.com oswa klike sou ikòn Gmail lan. Paj prensipal la, yo rele « bwat resepsyon », montre lis mesaj ou resevwa yo, pi resan yo anwo.\n\nPou ekri yon mesaj, klike sou bouton « Nouvo mesaj » (souvan make ak yon kreyon oswa yon « + »). Yon ti fenèt louvri. Nan chan « À » a, tape adrès moun w ap voye ba li a. Nan « Objè », ekri sijè a an kèk mo. Apre redije tèks ou nan gwo zòn nan. Lè tout bagay pare, klike sou « Voye ».\n\nPou li yon mesaj ou resevwa, senpleman klike sou li : li louvri antye. Ou ka apre reponn lè w klike sou « Reponn », oswa transfere mesaj la bay yon lòt moun. Ou ka tou tache yon fichye (foto, dokiman) nan yon mesaj ou voye gremesi ikòn ki gen fòm yon tronbòn. Atansyon ak imèl moun ou pa konnen : pa klike sou lyen ki dwòl yo.\n\nKèk bon abitid fè imèl ou pi efikas. Ekri yon objè klè pou moun nan konnen touswit de kisa li ye, kòmanse ak yon fòmil politès epi siyen mesaj ou. Chan « Cc » a pèmèt voye yon kopi bay lòt moun, pandan « Cci » mete yo an kopi san lòt yo pa wè adrès yo.",
            en: "Gmail is your email box: it is used to send and receive written messages, for free and anywhere in the world. To open it, go to gmail.com or click the Gmail icon. The main page, called the \"inbox,\" shows the list of received messages, the most recent at the top.\n\nTo write a message, click the \"Compose\" button (often marked with a pencil or a \"+\"). A small window opens. In the \"To\" field, type the recipient's address. In \"Subject,\" write the topic in a few words. Then write your text in the large area. When everything is ready, click \"Send.\"\n\nTo read a received message, simply click on it: it opens in full. You can then reply by clicking \"Reply,\" or forward the message to someone else. You can also attach a file (photo, document) to a message you send using the paperclip icon. Beware of emails from strangers: do not click on suspicious links.\n\nA few good habits make your emails more effective. Write a clear subject so the recipient knows right away what it is about, start with a greeting and sign your message. The \"Cc\" field lets you send a copy to other people, while \"Bcc\" copies them without the others seeing their address.",
            es: "Gmail es tu buzón de correo: sirve para enviar y recibir mensajes escritos, gratis y en cualquier parte del mundo. Para abrirlo, ve a gmail.com o haz clic en el icono de Gmail. La página principal, llamada «bandeja de entrada», muestra la lista de mensajes recibidos, los más recientes arriba.\n\nPara escribir un mensaje, haz clic en el botón «Redactar» (a menudo marcado con un lápiz o un «+»). Se abre una pequeña ventana. En el campo «Para», escribe la dirección del destinatario. En «Asunto», escribe el tema en pocas palabras. Luego redacta tu texto en la gran zona. Cuando todo está listo, haz clic en «Enviar».\n\nPara leer un mensaje recibido, simplemente haz clic en él: se abre entero. Puedes entonces responder haciendo clic en «Responder», o reenviar el mensaje a otra persona. También puedes adjuntar un archivo (foto, documento) a un mensaje que envías gracias al icono en forma de clip. Cuidado con los correos de desconocidos: no hagas clic en los enlaces dudosos.\n\nAlgunos buenos hábitos hacen tus correos más eficaces. Escribe un asunto claro para que el destinatario sepa enseguida de qué se trata, empieza con un saludo y firma tu mensaje. El campo «Cc» permite enviar una copia a otras personas, mientras que «Cco» las pone en copia sin que las demás vean su dirección.",
          },
          keyPoints: {
            fr: ["La boîte de réception liste tes messages reçus", "Nouveau message : remplir « À », « Objet », le texte, puis Envoyer", "Répondre, transférer, joindre un fichier (trombone) ; méfiance des inconnus", "Cc envoie une copie ; Cci la cache aux autres destinataires"],
            ht: ["Bwat resepsyon an montre mesaj ou resevwa yo", "Nouvo mesaj : ranpli « À », « Objè », tèks la, apre Voye", "Reponn, transfere, tache yon fichye (tronbòn) ; mefyans ak enkoni", "Cc voye yon kopi ; Cci kache l pou lòt moun yo"],
            en: ["The inbox lists your received messages", "Compose: fill \"To\", \"Subject\", the text, then Send", "Reply, forward, attach a file (paperclip); beware of strangers", "Cc sends a copy; Bcc hides it from the other recipients"],
            es: ["La bandeja de entrada lista tus mensajes recibidos", "Redactar: rellenar «Para», «Asunto», el texto, luego Enviar", "Responder, reenviar, adjuntar un archivo (clip); cuidado con desconocidos", "Cc envía una copia; Cco la oculta a los demás destinatarios"],
          },
          exercise: {
            fr: "Envoie-toi un courriel à ta propre adresse : mets un objet clair, écris quelques lignes et joins une photo grâce au trombone. Ouvre ensuite le message reçu et exerce-toi à cliquer sur « Répondre ».",
            ht: "Voye tèt ou yon imèl sou pwòp adrès ou : mete yon objè klè, ekri kèk liy epi tache yon foto gremesi tronbòn nan. Apre ouvri mesaj ou resevwa a epi egzèse ou klike sou « Reponn ».",
            en: "Send yourself an email to your own address: put a clear subject, write a few lines and attach a photo using the paperclip. Then open the received message and practice clicking \"Reply.\"",
            es: "Envíate un correo a tu propia dirección: pon un asunto claro, escribe unas líneas y adjunta una foto con el clip. Luego abre el mensaje recibido y practica hacer clic en «Responder».",
          },
        },
        {
          slug: "organiser-sa-boite-gmail",
          title: { fr: "Organiser sa boîte Gmail", ht: "Òganize bwat Gmail ou", en: "Organizing your Gmail inbox", es: "Organizar tu bandeja de Gmail" },
          videoId: "",
          content: {
            fr: "Avec le temps, la boîte de réception se remplit et il devient difficile de retrouver un message. Gmail offre des outils simples pour garder tout en ordre. Le plus utile est la « recherche » : en haut, une longue barre te permet de taper un mot, un nom d'expéditeur ou un sujet ; Gmail affiche aussitôt tous les messages qui correspondent, même très anciens.\n\nPour ranger tes messages, tu disposes de « libellés » (aussi appelés catégories ou étiquettes). Un libellé est comme un dossier de couleur : tu peux en créer « Travail », « Famille » ou « Factures », puis attribuer un message à un libellé. Un même message peut porter plusieurs libellés, ce qui te permet de le retrouver de différentes façons.\n\nQuand un message est traité mais que tu veux le garder, « archive-le » : il quitte la boîte de réception sans être supprimé, et reste retrouvable par la recherche. Pour un message vraiment inutile, la corbeille (l'icône poubelle) le supprime ; il y reste trente jours avant d'être effacé pour de bon, au cas où tu changerais d'avis.\n\nDeux fonctions protègent ta tranquillité. Le « spam » (courrier indésirable) est un dossier où Gmail range automatiquement les messages suspects ou publicitaires ; jette-y un œil de temps en temps. Et le bouton « Se désabonner », qui apparaît en haut de certains courriels, arrête de recevoir les lettres d'information que tu ne lis plus.",
            ht: "Ak tan, bwat resepsyon an ranpli epi li vin difisil pou jwenn yon mesaj. Gmail bay zouti senp pou kenbe tout bagay an lòd. Sa ki pi itil la se « recherche » a : anwo, yon long bar pèmèt ou tape yon mo, yon non moun ki voye oswa yon sijè ; Gmail montre touswit tout mesaj ki koresponn, menm sa ki trè ansyen.\n\nPou ranje mesaj ou yo, ou gen « libellés » (yo rele yo tou kategori oswa etikèt). Yon libellé se tankou yon dosye kolore : ou ka kreye « Travail », « Famille » oswa « Factures », apre bay yon mesaj yon libellé. Yon menm mesaj ka gen plizyè libellé, sa ki pèmèt ou jwenn li nan diferan fason.\n\nLè yon mesaj trete men ou vle kenbe l, « archive l » : li kite bwat resepsyon an san yo pa efase l, epi li rete jwenab pa recherche a. Pou yon mesaj ki vrèman initil, poubèl la (ikòn poubèl la) efase l ; li rete la trant jou anvan yo efase l nèt, si ou ta chanje lide.\n\nDe fonksyon pwoteje trankilite ou. « Spam » a (kourye endezirab) se yon dosye kote Gmail ranje otomatikman mesaj sispèk oswa piblisite yo ; jete yon je ladan detanzantan. Epi bouton « Se désabonner », ki parèt anwo kèk imèl, sispann resevwa lèt enfòmasyon ou pa li ankò.",
            en: "Over time, the inbox fills up and it becomes hard to find a message. Gmail offers simple tools to keep everything in order. The most useful is \"search\": at the top, a long bar lets you type a word, a sender's name or a subject; Gmail immediately shows all matching messages, even very old ones.\n\nTo tidy your messages, you have \"labels\" (also called categories or tags). A label is like a colored folder: you can create \"Work\", \"Family\" or \"Bills\", then assign a message to a label. One message can carry several labels, which lets you find it in different ways.\n\nWhen a message is handled but you want to keep it, \"archive\" it: it leaves the inbox without being deleted, and stays findable by search. For a truly useless message, the trash (the bin icon) deletes it; it stays there thirty days before being erased for good, in case you change your mind.\n\nTwo functions protect your peace of mind. \"Spam\" (junk mail) is a folder where Gmail automatically files suspicious or advertising messages; glance at it from time to time. And the \"Unsubscribe\" button, which appears at the top of certain emails, stops receiving newsletters you no longer read.",
            es: "Con el tiempo, la bandeja de entrada se llena y se vuelve difícil encontrar un mensaje. Gmail ofrece herramientas sencillas para mantener todo en orden. La más útil es la «búsqueda»: arriba, una larga barra te permite escribir una palabra, un nombre de remitente o un asunto; Gmail muestra enseguida todos los mensajes que coinciden, incluso muy antiguos.\n\nPara ordenar tus mensajes, dispones de «etiquetas» (también llamadas categorías). Una etiqueta es como una carpeta de color: puedes crear «Trabajo», «Familia» o «Facturas», luego asignar un mensaje a una etiqueta. Un mismo mensaje puede llevar varias etiquetas, lo que te permite encontrarlo de distintas maneras.\n\nCuando un mensaje está resuelto pero quieres conservarlo, «archívalo»: sale de la bandeja de entrada sin ser eliminado, y sigue localizable por la búsqueda. Para un mensaje realmente inútil, la papelera (el icono de basura) lo elimina; permanece ahí treinta días antes de borrarse definitivamente, por si cambias de opinión.\n\nDos funciones protegen tu tranquilidad. El «spam» (correo no deseado) es una carpeta donde Gmail archiva automáticamente los mensajes sospechosos o publicitarios; échale un vistazo de vez en cuando. Y el botón «Cancelar suscripción», que aparece arriba de ciertos correos, detiene la recepción de boletines que ya no lees.",
          },
          keyPoints: {
            fr: ["La barre de recherche retrouve n'importe quel message par mot-clé", "Les libellés rangent les messages par catégorie de couleur", "Archiver garde un message hors de la boîte ; la corbeille le supprime", "Le dossier spam filtre les indésirables ; « Se désabonner » stoppe les newsletters"],
            ht: ["Bar recherche a jwenn nenpòt mesaj pa mo kle", "Libellés yo ranje mesaj yo pa kategori koulè", "Archive kenbe yon mesaj andeyò bwat la ; poubèl la efase l", "Dosye spam nan filtre endezirab yo ; « Se désabonner » sispann newsletter yo"],
            en: ["The search bar finds any message by keyword", "Labels sort messages by colored category", "Archiving keeps a message out of the inbox; the trash deletes it", "The spam folder filters junk; \"Unsubscribe\" stops newsletters"],
            es: ["La barra de búsqueda encuentra cualquier mensaje por palabra clave", "Las etiquetas ordenan los mensajes por categoría de color", "Archivar mantiene un mensaje fuera de la bandeja; la papelera lo elimina", "La carpeta de spam filtra el correo no deseado; «Cancelar suscripción» detiene los boletines"],
          },
          exercise: {
            fr: "Crée un libellé « Important » et applique-le à deux messages. Recherche ensuite un message par mot-clé dans la barre du haut, archive un message traité, et repère le dossier « Spam » dans le menu de gauche.",
            ht: "Kreye yon libellé « Important » epi aplike l sou de mesaj. Apre chèche yon mesaj pa mo kle nan bar anwo a, archive yon mesaj ki trete, epi jwenn dosye « Spam » nan meni agoch la.",
            en: "Create an \"Important\" label and apply it to two messages. Then search for a message by keyword in the top bar, archive a handled message, and locate the \"Spam\" folder in the left menu.",
            es: "Crea una etiqueta «Importante» y aplícala a dos mensajes. Luego busca un mensaje por palabra clave en la barra superior, archiva un mensaje resuelto, y localiza la carpeta «Spam» en el menú de la izquierda.",
          },
        },
      ],
    },
    {
      title: { fr: "Stocker et créer : Drive, Docs, Sheets", ht: "Estoke ak kreye : Drive, Docs, Sheets", en: "Store and create: Drive, Docs, Sheets", es: "Guardar y crear: Drive, Docs, Sheets" },
      lessons: [
        {
          slug: "stocker-avec-drive",
          title: { fr: "Stocker ses fichiers avec Drive", ht: "Estoke fichye ou ak Drive", en: "Storing your files with Drive", es: "Guardar tus archivos con Drive" },
          videoId: "",
          content: {
            fr: "Google Drive est un espace de rangement gratuit sur Internet, offert avec ton compte Google. Au lieu de garder tes fichiers seulement sur l'ordinateur, tu les enregistres « dans le nuage » (le cloud). Ainsi, tu les retrouves depuis n'importe quel appareil connecté : ordinateur, téléphone ou tablette, où que tu sois.\n\nCet espace est très utile pour ne rien perdre. Si ton ordinateur tombe en panne ou est volé, tes photos et documents restent en sécurité sur Drive. Pour y déposer un fichier, ouvre drive.google.com, puis fais glisser le fichier depuis ton ordinateur vers la fenêtre, ou clique sur « Nouveau » puis « Importer un fichier ».\n\nDans Drive, tu peux créer des dossiers pour organiser tes fichiers, exactement comme sur l'ordinateur. Clique sur « Nouveau » puis « Dossier », donne-lui un nom, puis fais glisser tes fichiers à l'intérieur. Un rangement en dossiers clairs (Photos, Papiers, Travail) t'évite de chercher longtemps plus tard.\n\nDrive t'offre gratuitement quinze gigaoctets d'espace, partagés avec Gmail. C'est largement suffisant pour des documents et des photos, mais les vidéos, plus lourdes, le remplissent vite. La barre de recherche en haut de Drive retrouve un fichier par son nom en une seconde, ce qui est bien plus rapide que de fouiller dossier par dossier.",
            ht: "Google Drive se yon espas depo gratis sou Entènèt, yo ofri ak kont Google ou. Olye ou kenbe fichye ou yo sèlman sou òdinatè a, ou anrejistre yo « nan nyaj la » (cloud). Konsa, ou jwenn yo depi nenpòt aparèy ki konekte : òdinatè, telefòn oswa tablèt, kèlkeswa kote ou ye.\n\nEspas sa a trè itil pou pa pèdi anyen. Si òdinatè ou an pann oswa yo vòlè l, foto ak dokiman ou yo rete an sekirite sou Drive. Pou depoze yon fichye, louvri drive.google.com, apre fè fichye a glise soti nan òdinatè ou vè fenèt la, oswa klike sou « Nouvo » apre « Enpòte yon fichye ».\n\nNan Drive, ou ka kreye dosye pou òganize fichye ou yo, egzakteman tankou sou òdinatè a. Klike sou « Nouvo » apre « Dossier », ba li yon non, apre fè fichye ou yo glise anndan. Yon ranjman ak dosye klè (Foto, Papye, Travay) evite ou chèche lontan pita.\n\nDrive ba ou gratis kenz gigaoktè espas, ki pataje ak Gmail. Sa ase anpil pou dokiman ak foto, men videyo yo, ki pi lou, ranpli l vit. Bar recherche anwo Drive a jwenn yon fichye pa non l nan yon segonn, sa ki pi rapid pase fouye dosye pa dosye.",
            en: "Google Drive is a free storage space on the Internet, provided with your Google account. Instead of keeping your files only on the computer, you save them \"in the cloud.\" That way, you can find them from any connected device: computer, phone or tablet, wherever you are.\n\nThis space is very useful for losing nothing. If your computer breaks down or is stolen, your photos and documents stay safe on Drive. To put a file there, open drive.google.com, then drag the file from your computer into the window, or click \"New\" then \"File upload.\"\n\nIn Drive, you can create folders to organize your files, exactly like on the computer. Click \"New\" then \"Folder\", give it a name, then drag your files inside. Tidy storage in clear folders (Photos, Papers, Work) saves you from long searches later.\n\nDrive gives you fifteen gigabytes of space for free, shared with Gmail. That is plenty for documents and photos, but videos, being heavier, fill it up fast. The search bar at the top of Drive finds a file by its name in a second, much faster than digging folder by folder.",
            es: "Google Drive es un espacio de almacenamiento gratuito en Internet, ofrecido con tu cuenta de Google. En lugar de guardar tus archivos solo en la computadora, los guardas «en la nube» (el cloud). Así, los encuentras desde cualquier dispositivo conectado: computadora, teléfono o tableta, estés donde estés.\n\nEste espacio es muy útil para no perder nada. Si tu computadora se avería o te la roban, tus fotos y documentos quedan seguros en Drive. Para subir un archivo, abre drive.google.com, luego arrastra el archivo desde tu computadora a la ventana, o haz clic en «Nuevo» y luego «Subir archivo».\n\nEn Drive, puedes crear carpetas para organizar tus archivos, exactamente como en la computadora. Haz clic en «Nuevo» y luego «Carpeta», dale un nombre, y arrastra tus archivos dentro. Un orden en carpetas claras (Fotos, Papeles, Trabajo) te evita buscar mucho más tarde.\n\nDrive te da gratis quince gigabytes de espacio, compartidos con Gmail. Es de sobra para documentos y fotos, pero los videos, más pesados, lo llenan rápido. La barra de búsqueda arriba de Drive encuentra un archivo por su nombre en un segundo, mucho más rápido que hurgar carpeta por carpeta.",
          },
          keyPoints: {
            fr: ["Drive stocke tes fichiers « dans le nuage », accessibles partout", "Tes fichiers restent en sécurité même si l'ordinateur tombe en panne", "On importe par glisser-déposer et on range dans des dossiers", "15 Go gratuits partagés avec Gmail ; la recherche trouve vite un fichier"],
            ht: ["Drive estoke fichye ou « nan nyaj la », aksesib toupatou", "Fichye ou yo rete an sekirite menm si òdinatè a an pann", "Ou enpòte pa glise-depoze epi ou ranje nan dosye", "15 Go gratis pataje ak Gmail ; recherche a jwenn yon fichye vit"],
            en: ["Drive stores your files \"in the cloud,\" accessible anywhere", "Your files stay safe even if the computer breaks down", "You upload by drag-and-drop and tidy into folders", "15 GB free shared with Gmail; search finds a file fast"],
            es: ["Drive guarda tus archivos «en la nube», accesibles en todas partes", "Tus archivos quedan seguros incluso si la computadora se avería", "Se sube arrastrando y soltando y se ordena en carpetas", "15 GB gratis compartidos con Gmail; la búsqueda encuentra un archivo rápido"],
          },
          exercise: {
            fr: "Ouvre drive.google.com, crée un dossier nommé « Documents », puis importe deux fichiers depuis ton ordinateur par glisser-déposer et range-les dans ce dossier. Retrouve enfin l'un d'eux avec la barre de recherche.",
            ht: "Ouvri drive.google.com, kreye yon dosye ki rele « Documents », apre enpòte de fichye soti nan òdinatè ou ak glise-depoze epi ranje yo nan dosye sa a. Anfen jwenn youn nan yo ak bar recherche a.",
            en: "Open drive.google.com, create a folder named \"Documents\", then upload two files from your computer by drag-and-drop and place them in that folder. Finally find one of them with the search bar.",
            es: "Abre drive.google.com, crea una carpeta llamada «Documentos», luego sube dos archivos desde tu computadora arrastrando y soltando y colócalos en esa carpeta. Por último, encuentra uno de ellos con la barra de búsqueda.",
          },
        },
        {
          slug: "ecrire-avec-docs",
          title: { fr: "Écrire un document avec Docs", ht: "Ekri yon dokiman ak Docs", en: "Writing a document with Docs", es: "Escribir un documento con Docs" },
          videoId: "",
          content: {
            fr: "Google Docs est un traitement de texte gratuit qui fonctionne directement dans le navigateur : pas besoin d'installer de programme. Il sert à écrire des lettres, des rapports, une liste ou tout autre document texte. Pour commencer, va sur docs.google.com et clique sur « Document vierge ».\n\nUne page blanche apparaît, comme une feuille de papier. Tu peux taper ton texte, puis le mettre en forme grâce à la barre d'outils en haut : choisir la taille des lettres, mettre un mot en gras, souligner, changer la couleur ou centrer un titre. Sélectionne d'abord le texte avec la souris, puis clique sur le bouton voulu.\n\nLe grand avantage de Docs : il enregistre ton travail automatiquement, à chaque seconde, dans ton Drive. Tu ne risques donc pas de perdre ton document. Tu peux aussi le partager pour écrire à plusieurs sur le même texte, et le télécharger sur ton ordinateur au format Word ou PDF quand tu en as besoin.\n\nDocs offre bien plus que du texte : le menu « Insertion » ajoute une image, un tableau ou un lien, et le menu « Format » applique des « styles de titre » qui structurent un long document. Pour renommer ton fichier, clique simplement sur son titre en haut à gauche et tape le nouveau nom ; il se retrouve ensuite dans Drive, prêt à être rouvert n'importe quand.",
            ht: "Google Docs se yon pwogram pou ekri tèks gratis ki fonksyone dirèkteman nan navigatè a : pa bezwen enstale okenn pwogram. Li sèvi pou ekri lèt, rapò, yon lis oswa nenpòt lòt dokiman tèks. Pou kòmanse, ale sou docs.google.com epi klike sou « Dokiman vid ».\n\nYon paj blanch parèt, tankou yon fèy papye. Ou ka tape tèks ou, apre mete l an fòm gremesi ba zouti anwo a : chwazi gwosè lèt yo, mete yon mo an gra, souliye, chanje koulè oswa santre yon tit. Seleksyone dabò tèks la ak sourit la, apre klike sou bouton ou vle a.\n\nGwo avantaj Docs : li anrejistre travay ou otomatikman, chak segonn, nan Drive ou. Konsa ou pa riske pèdi dokiman ou. Ou ka tou pataje l pou ekri plizyè moun sou menm tèks la, epi telechaje l sou òdinatè ou nan fòma Word oswa PDF lè ou bezwen l.\n\nDocs ofri plis pase tèks : meni « Insertion » ajoute yon imaj, yon tablo oswa yon lyen, epi meni « Format » aplike « estil tit » ki estriktire yon long dokiman. Pou chanje non fichye ou, senpleman klike sou tit li anwo agoch epi tape nouvo non an ; apre li jwenn nan Drive, pare pou rouvri nenpòt kilè.",
            en: "Google Docs is a free word processor that works directly in the browser: no need to install a program. It is used to write letters, reports, a list or any other text document. To start, go to docs.google.com and click \"Blank document.\"\n\nA white page appears, like a sheet of paper. You can type your text, then format it using the toolbar at the top: choose the letter size, make a word bold, underline, change the color or center a title. First select the text with the mouse, then click the button you want.\n\nThe great advantage of Docs: it saves your work automatically, every second, in your Drive. So you do not risk losing your document. You can also share it to write with several people on the same text, and download it to your computer in Word or PDF format when you need it.\n\nDocs offers much more than text: the \"Insert\" menu adds an image, a table or a link, and the \"Format\" menu applies \"heading styles\" that structure a long document. To rename your file, simply click its title at the top left and type the new name; it then appears in Drive, ready to be reopened anytime.",
            es: "Google Docs es un procesador de textos gratuito que funciona directamente en el navegador: no hay que instalar ningún programa. Sirve para escribir cartas, informes, una lista o cualquier otro documento de texto. Para empezar, ve a docs.google.com y haz clic en «Documento en blanco».\n\nAparece una página blanca, como una hoja de papel. Puedes escribir tu texto, luego darle formato gracias a la barra de herramientas de arriba: elegir el tamaño de las letras, poner una palabra en negrita, subrayar, cambiar el color o centrar un título. Selecciona primero el texto con el ratón, luego haz clic en el botón que quieras.\n\nLa gran ventaja de Docs: guarda tu trabajo automáticamente, cada segundo, en tu Drive. Así no corres el riesgo de perder tu documento. También puedes compartirlo para escribir entre varios sobre el mismo texto, y descargarlo a tu computadora en formato Word o PDF cuando lo necesites.\n\nDocs ofrece mucho más que texto: el menú «Insertar» añade una imagen, una tabla o un enlace, y el menú «Formato» aplica «estilos de título» que estructuran un documento largo. Para renombrar tu archivo, simplemente haz clic en su título arriba a la izquierda y escribe el nuevo nombre; luego aparece en Drive, listo para reabrirse en cualquier momento.",
          },
          keyPoints: {
            fr: ["Docs écrit des documents dans le navigateur, sans installation", "La barre d'outils met en forme (gras, taille, couleur, titre)", "Enregistrement automatique dans Drive ; partage et export Word/PDF", "Insertion ajoute image, tableau, lien ; les styles structurent un long texte"],
            ht: ["Docs ekri dokiman nan navigatè a, san enstalasyon", "Ba zouti a mete an fòm (gra, gwosè, koulè, tit)", "Anrejistreman otomatik nan Drive ; pataj ak ekspò Word/PDF", "Insertion ajoute imaj, tablo, lyen ; estil yo estriktire yon long tèks"],
            en: ["Docs writes documents in the browser, no installation", "The toolbar formats (bold, size, color, title)", "Automatic saving in Drive; sharing and Word/PDF export", "Insert adds image, table, link; styles structure a long text"],
            es: ["Docs escribe documentos en el navegador, sin instalación", "La barra de herramientas da formato (negrita, tamaño, color, título)", "Guardado automático en Drive; compartir y exportar Word/PDF", "Insertar añade imagen, tabla, enlace; los estilos estructuran un texto largo"],
          },
          exercise: {
            fr: "Crée un document vierge sur docs.google.com et rédige une courte lettre. Donne-lui un nom en cliquant sur le titre, mets ta signature en gras, puis télécharge le document au format PDF depuis le menu « Fichier ».",
            ht: "Kreye yon dokiman vid sou docs.google.com epi redije yon kout lèt. Ba li yon non lè w klike sou tit la, mete siyati ou an gra, apre telechaje dokiman an nan fòma PDF soti nan meni « Fichier ».",
            en: "Create a blank document on docs.google.com and write a short letter. Give it a name by clicking the title, make your signature bold, then download the document as a PDF from the \"File\" menu.",
            es: "Crea un documento en blanco en docs.google.com y redacta una carta corta. Dale un nombre haciendo clic en el título, pon tu firma en negrita, luego descarga el documento en formato PDF desde el menú «Archivo».",
          },
        },
        {
          slug: "calculer-avec-sheets",
          title: { fr: "Calculer avec Sheets", ht: "Kalkile ak Sheets", en: "Calculating with Sheets", es: "Calcular con Sheets" },
          videoId: "",
          content: {
            fr: "Google Sheets est un tableur gratuit, c'est-à-dire un outil pour organiser des chiffres et faire des calculs automatiquement. Il est parfait pour tenir un budget, une liste de dépenses, un inventaire ou les notes d'une classe. Pour commencer, va sur sheets.google.com et clique sur « Feuille de calcul vierge ».\n\nUne grille apparaît, faite de « cases » appelées cellules. Les colonnes portent des lettres (A, B, C…) et les lignes des numéros (1, 2, 3…). Chaque cellule a donc une adresse, comme A1 ou B3. Tu cliques sur une cellule et tu tapes dedans : un mot, un nombre ou une date. C'est ainsi que tu construis un tableau propre, colonne par colonne.\n\nLa force d'un tableur, c'est le calcul automatique. Pour additionner des nombres, clique sur une cellule vide, tape le signe « = », puis « SOMME » suivi des cellules entre parenthèses, par exemple =SOMME(A1:A5), et appuie sur Entrée. Le total apparaît aussitôt, et si tu changes un nombre plus haut, le total se recalcule tout seul.\n\nSheets propose bien d'autres fonctions simples : MOYENNE pour une moyenne, MIN et MAX pour le plus petit et le plus grand nombre. Comme Docs, il s'enregistre automatiquement dans ton Drive et se partage à plusieurs. Tu peux même transformer tes chiffres en graphique via le menu « Insertion » puis « Graphique », pour visualiser d'un coup d'œil.",
            ht: "Google Sheets se yon tableur gratis, sa vle di yon zouti pou òganize chif epi fè kalkil otomatikman. Li pafè pou kenbe yon bidjè, yon lis depans, yon envantè oswa nòt yon klas. Pou kòmanse, ale sou sheets.google.com epi klike sou « Feuille de calcul vierge ».\n\nYon griy parèt, ki fèt ak « kaz » yo rele selil. Kolòn yo pote lèt (A, B, C…) epi liy yo nimewo (1, 2, 3…). Chak selil gen yon adrès, tankou A1 oswa B3. Ou klike sou yon selil epi ou tape ladan : yon mo, yon nonb oswa yon dat. Se konsa ou konstwi yon tablo pwòp, kolòn pa kolòn.\n\nFòs yon tableur, se kalkil otomatik la. Pou adisyone nonb, klike sou yon selil vid, tape siy « = » a, apre « SOMME » swiv selil yo ant parantèz, pa egzanp =SOMME(A1:A5), epi peze Entrée. Total la parèt touswit, epi si ou chanje yon nonb pi wo, total la rekalkile pou kont li.\n\nSheets pwopoze anpil lòt fonksyon senp : MOYENNE pou yon mwayèn, MIN ak MAX pou pi piti ak pi gwo nonb la. Menm jan ak Docs, li anrejistre otomatikman nan Drive ou epi li pataje ak plizyè moun. Ou ka menm transfòme chif ou yo an graf atravè meni « Insertion » apre « Graphique », pou vizyalize nan yon kout je.",
            en: "Google Sheets is a free spreadsheet, that is, a tool to organize numbers and do calculations automatically. It is perfect for keeping a budget, an expense list, an inventory or a class's grades. To start, go to sheets.google.com and click \"Blank spreadsheet.\"\n\nA grid appears, made of \"boxes\" called cells. The columns carry letters (A, B, C…) and the rows numbers (1, 2, 3…). Each cell therefore has an address, like A1 or B3. You click a cell and type into it: a word, a number or a date. That is how you build a clean table, column by column.\n\nThe strength of a spreadsheet is automatic calculation. To add numbers, click an empty cell, type the \"=\" sign, then \"SUM\" followed by the cells in parentheses, for example =SUM(A1:A5), and press Enter. The total appears at once, and if you change a number above, the total recalculates on its own.\n\nSheets offers many other simple functions: AVERAGE for an average, MIN and MAX for the smallest and largest number. Like Docs, it saves automatically in your Drive and is shared with several people. You can even turn your figures into a chart via the \"Insert\" menu then \"Chart\", to visualize at a glance.",
            es: "Google Sheets es una hoja de cálculo gratuita, es decir, una herramienta para organizar números y hacer cálculos automáticamente. Es perfecta para llevar un presupuesto, una lista de gastos, un inventario o las notas de una clase. Para empezar, ve a sheets.google.com y haz clic en «Hoja de cálculo en blanco».\n\nAparece una cuadrícula, formada por «casillas» llamadas celdas. Las columnas llevan letras (A, B, C…) y las filas números (1, 2, 3…). Cada celda tiene por tanto una dirección, como A1 o B3. Haces clic en una celda y escribes dentro: una palabra, un número o una fecha. Así construyes una tabla ordenada, columna por columna.\n\nLa fuerza de una hoja de cálculo es el cálculo automático. Para sumar números, haz clic en una celda vacía, escribe el signo «=», luego «SUMA» seguido de las celdas entre paréntesis, por ejemplo =SUMA(A1:A5), y pulsa Enter. El total aparece enseguida, y si cambias un número más arriba, el total se recalcula solo.\n\nSheets ofrece muchas otras funciones simples: PROMEDIO para una media, MIN y MAX para el número más pequeño y el más grande. Como Docs, se guarda automáticamente en tu Drive y se comparte entre varios. Incluso puedes convertir tus cifras en gráfico mediante el menú «Insertar» y luego «Gráfico», para visualizar de un vistazo.",
          },
          keyPoints: {
            fr: ["Sheets organise des chiffres dans une grille de cellules", "Colonnes en lettres, lignes en numéros : chaque cellule a une adresse", "=SOMME(A1:A5) additionne ; le total se recalcule automatiquement", "MOYENNE, MIN, MAX et graphiques pour analyser les données"],
            ht: ["Sheets òganize chif nan yon griy selil", "Kolòn an lèt, liy an nimewo : chak selil gen yon adrès", "=SOMME(A1:A5) adisyone ; total la rekalkile otomatikman", "MOYENNE, MIN, MAX ak graf pou analize done yo"],
            en: ["Sheets organizes numbers in a grid of cells", "Columns in letters, rows in numbers: each cell has an address", "=SUM(A1:A5) adds up; the total recalculates automatically", "AVERAGE, MIN, MAX and charts to analyze the data"],
            es: ["Sheets organiza números en una cuadrícula de celdas", "Columnas en letras, filas en números: cada celda tiene una dirección", "=SUMA(A1:A5) suma; el total se recalcula automáticamente", "PROMEDIO, MIN, MAX y gráficos para analizar los datos"],
          },
          exercise: {
            fr: "Crée une feuille de calcul et tape cinq montants de dépenses dans la colonne A. Dans la cellule A6, écris =SOMME(A1:A5) pour obtenir le total, puis change un montant et vérifie que le total se met à jour tout seul.",
            ht: "Kreye yon feuille de calcul epi tape senk montan depans nan kolòn A. Nan selil A6, ekri =SOMME(A1:A5) pou jwenn total la, apre chanje yon montan epi verifye total la mete ajou pou kont li.",
            en: "Create a spreadsheet and type five expense amounts in column A. In cell A6, write =SUM(A1:A5) to get the total, then change an amount and check that the total updates on its own.",
            es: "Crea una hoja de cálculo y escribe cinco importes de gastos en la columna A. En la celda A6, escribe =SUMA(A1:A5) para obtener el total, luego cambia un importe y comprueba que el total se actualiza solo.",
          },
        },
      ],
    },
    {
      title: { fr: "Partager et collaborer", ht: "Pataje epi kolabore", en: "Sharing and collaborating", es: "Compartir y colaborar" },
      lessons: [
        {
          slug: "partager-ses-fichiers",
          title: { fr: "Partager ses fichiers", ht: "Pataje fichye ou yo", en: "Sharing your files", es: "Compartir tus archivos" },
          videoId: "",
          content: {
            fr: "L'un des grands atouts de Drive, Docs et Sheets est de pouvoir partager un fichier sans l'envoyer par courriel. La personne accède au fichier original, toujours à jour, et vous ne vous retrouvez pas avec dix copies différentes. Le bouton « Partager » (souvent bleu, en haut à droite d'un document ouvert) ouvre cette fonction.\n\nPour partager, clique sur « Partager », tape l'adresse Gmail de la personne, puis envoie. Elle reçoit un message avec un lien vers le fichier. Tu peux partager avec une seule personne ou avec plusieurs à la fois en ajoutant plusieurs adresses. Un fichier partagé apparaît aussi dans son Drive, à la rubrique « Partagés avec moi ».\n\nLe point le plus important est de choisir les « droits » que tu accordes. « Lecteur » permet seulement de voir le fichier, sans le modifier : idéal pour diffuser une information. « Commentateur » autorise à laisser des remarques sans toucher au texte. « Éditeur » donne le droit de modifier le contenu : à réserver aux personnes de confiance avec qui tu travailles vraiment.\n\nTu peux aussi générer un « lien de partage » à copier et coller dans un message ou un groupe. Fais attention à son réglage : « Tous les utilisateurs disposant du lien » rend le fichier accessible à quiconque possède l'adresse, ce qui est pratique mais moins privé. Pour des documents personnels, préfère toujours le partage par adresse, nominatif et contrôlé.",
            ht: "Youn nan gwo avantaj Drive, Docs ak Sheets se kapasite pou pataje yon fichye san voye l pa imèl. Moun nan gen aksè a fichye orijinal la, ki toujou ajou, epi nou pa retrouve nou ak dis kopi diferan. Bouton « Partager » a (souvan ble, anwo adwat yon dokiman ki louvri) ouvri fonksyon sa a.\n\nPou pataje, klike sou « Partager », tape adrès Gmail moun nan, apre voye. Li resevwa yon mesaj ak yon lyen vè fichye a. Ou ka pataje ak yon sèl moun oswa ak plizyè an menm tan lè w ajoute plizyè adrès. Yon fichye pataje parèt tou nan Drive li, nan rubrik « Partagés avec moi ».\n\nPwen ki pi enpòtan an se chwazi « droits » ou akòde yo. « Lecteur » pèmèt sèlman wè fichye a, san modifye l : ideyal pou difize yon enfòmasyon. « Commentateur » otorize kite remak san touche tèks la. « Éditeur » bay dwa modifye kontni an : rezève l pou moun konfyans w ap travay vrèman ak yo.\n\nOu ka tou jenere yon « lien de partage » pou kopye epi kole nan yon mesaj oswa yon gwoup. Fè atansyon ak reglaj li : « Tous les utilisateurs disposant du lien » rann fichye a aksesib pou nenpòt moun ki gen adrès la, sa ki pratik men mwens prive. Pou dokiman pèsonèl, toujou prefere pataj pa adrès, nominatif epi kontwole.",
            en: "One of the great strengths of Drive, Docs and Sheets is being able to share a file without emailing it. The person accesses the original file, always up to date, and you do not end up with ten different copies. The \"Share\" button (often blue, at the top right of an open document) opens this function.\n\nTo share, click \"Share\", type the person's Gmail address, then send. They receive a message with a link to the file. You can share with one person or with several at once by adding several addresses. A shared file also appears in their Drive, under \"Shared with me\".\n\nThe most important point is choosing the \"rights\" you grant. \"Viewer\" only allows seeing the file, without editing it: ideal for spreading information. \"Commenter\" allows leaving remarks without touching the text. \"Editor\" gives the right to change the content: reserve it for trusted people you really work with.\n\nYou can also generate a \"share link\" to copy and paste into a message or a group. Be careful with its setting: \"Anyone with the link\" makes the file accessible to whoever has the address, which is handy but less private. For personal documents, always prefer sharing by address, named and controlled.",
            es: "Una de las grandes ventajas de Drive, Docs y Sheets es poder compartir un archivo sin enviarlo por correo. La persona accede al archivo original, siempre actualizado, y no terminas con diez copias diferentes. El botón «Compartir» (a menudo azul, arriba a la derecha de un documento abierto) abre esta función.\n\nPara compartir, haz clic en «Compartir», escribe la dirección de Gmail de la persona, luego envía. Recibe un mensaje con un enlace al archivo. Puedes compartir con una sola persona o con varias a la vez añadiendo varias direcciones. Un archivo compartido también aparece en su Drive, en la sección «Compartido conmigo».\n\nEl punto más importante es elegir los «permisos» que concedes. «Lector» solo permite ver el archivo, sin modificarlo: ideal para difundir una información. «Comentador» permite dejar observaciones sin tocar el texto. «Editor» da el derecho de modificar el contenido: resérvalo para personas de confianza con las que realmente trabajas.\n\nTambién puedes generar un «enlace para compartir» para copiar y pegar en un mensaje o un grupo. Ten cuidado con su ajuste: «Cualquier persona con el enlace» hace el archivo accesible a quien tenga la dirección, lo que es práctico pero menos privado. Para documentos personales, prefiere siempre compartir por dirección, nominativo y controlado.",
          },
          keyPoints: {
            fr: ["Le bouton « Partager » donne accès au fichier sans l'envoyer", "On partage par adresse Gmail, à une ou plusieurs personnes", "Droits : Lecteur (voir), Commentateur (remarques), Éditeur (modifier)", "Le lien « Tous ceux qui ont le lien » est pratique mais moins privé"],
            ht: ["Bouton « Partager » a bay aksè a fichye a san voye l", "Ou pataje pa adrès Gmail, ak youn oswa plizyè moun", "Droits : Lecteur (wè), Commentateur (remak), Éditeur (modifye)", "Lyen « Tout moun ki gen lyen an » pratik men mwens prive"],
            en: ["The \"Share\" button gives access to the file without sending it", "You share by Gmail address, with one or several people", "Rights: Viewer (see), Commenter (remarks), Editor (edit)", "The \"Anyone with the link\" link is handy but less private"],
            es: ["El botón «Compartir» da acceso al archivo sin enviarlo", "Se comparte por dirección de Gmail, con una o varias personas", "Permisos: Lector (ver), Comentador (observaciones), Editor (modificar)", "El enlace «Cualquiera con el enlace» es práctico pero menos privado"],
          },
          exercise: {
            fr: "Ouvre un document Docs, clique sur « Partager » et partage-le avec une adresse (par exemple la tienne, secondaire, ou celle d'un proche) en droit « Lecteur ». Change ensuite le droit en « Éditeur » et observe la différence.",
            ht: "Ouvri yon dokiman Docs, klike sou « Partager » epi pataje l ak yon adrès (pa egzanp pa ou, segondè, oswa pa yon pwòch) ak dwa « Lecteur ». Apre chanje dwa a an « Éditeur » epi gade diferans lan.",
            en: "Open a Docs document, click \"Share\" and share it with an address (for example your own, secondary, or a relative's) with \"Viewer\" rights. Then change the right to \"Editor\" and observe the difference.",
            es: "Abre un documento de Docs, haz clic en «Compartir» y compártelo con una dirección (por ejemplo la tuya secundaria, o la de un allegado) con permiso «Lector». Luego cambia el permiso a «Editor» y observa la diferencia.",
          },
        },
        {
          slug: "travailler-a-plusieurs",
          title: { fr: "Travailler à plusieurs en temps réel", ht: "Travay ak plizyè moun an tan reyèl", en: "Working together in real time", es: "Trabajar juntos en tiempo real" },
          videoId: "",
          content: {
            fr: "Une fois un document partagé en mode « Éditeur », la vraie magie de Google commence : plusieurs personnes peuvent écrire dans le même document en même temps, chacune depuis son propre ordinateur. C'est ce qu'on appelle la collaboration en temps réel, et elle fonctionne aussi bien dans Docs que dans Sheets ou Slides.\n\nQuand quelqu'un d'autre travaille sur le document, tu vois son curseur bouger, souvent d'une couleur différente, avec son nom à côté. Tout ce qu'il tape apparaît sous tes yeux en direct, et tout s'enregistre automatiquement. Fini les allers-retours de fichiers par courriel : chacun voit toujours la dernière version.\n\nPour échanger sans modifier le texte, utilise les « commentaires ». Sélectionne un mot ou une phrase, clique sur l'icône de bulle qui apparaît, et écris ta remarque. L'auteur reçoit une notification, peut te répondre, et clique sur « Résoudre » une fois la question réglée. C'est parfait pour relire le travail de quelqu'un sans effacer son texte.\n\nDeux outils complètent la collaboration. Le « mode Suggestion » (dans Docs) propose tes modifications sans les imposer : l'auteur les accepte ou les refuse d'un clic. Et l'« historique des versions » (menu Fichier) garde la trace de tous les changements, avec qui a fait quoi et quand ; tu peux même revenir à une version antérieure si nécessaire. Rien n'est jamais vraiment perdu.",
            ht: "Yon fwa yon dokiman pataje an mòd « Éditeur », vrè maji Google la kòmanse : plizyè moun ka ekri nan menm dokiman an an menm tan, chak soti nan pwòp òdinatè yo. Se sa yo rele kolaborasyon an tan reyèl, epi li fonksyone byen nan Docs menm jan ak nan Sheets oswa Slides.\n\nLè yon lòt moun ap travay sou dokiman an, ou wè kurzè li bouje, souvan ak yon koulè diferan, ak non li akote. Tout sa li tape parèt devan je ou an dirèk, epi tout anrejistre otomatikman. Fini ale-vini fichye pa imèl : chak moun toujou wè dènye vèsyon an.\n\nPou echanje san modifye tèks la, sèvi ak « commentaires » yo. Chwazi yon mo oswa yon fraz, klike sou ikòn bul ki parèt la, epi ekri remak ou. Otè a resevwa yon notifikasyon, ka reponn ou, epi klike sou « Résoudre » yon fwa kesyon an regle. Li pafè pou reli travay yon moun san efase tèks li.\n\nDe zouti konplete kolaborasyon an. « Mode Suggestion » (nan Docs) pwopoze modifikasyon ou yo san enpoze yo : otè a aksepte oswa refize yo ak yon klik. Epi « historique des versions » (meni Fichier) kenbe tras tout chanjman yo, ak kiyès ki fè kisa epi kilè ; ou ka menm retounen nan yon vèsyon anvan si sa nesesè. Anyen pa janm vrèman pèdi.",
            en: "Once a document is shared in \"Editor\" mode, Google's real magic begins: several people can write in the same document at the same time, each from their own computer. This is called real-time collaboration, and it works in Docs as well as in Sheets or Slides.\n\nWhen someone else works on the document, you see their cursor move, often in a different color, with their name next to it. Everything they type appears before your eyes live, and everything saves automatically. No more emailing files back and forth: everyone always sees the latest version.\n\nTo exchange without changing the text, use \"comments\". Select a word or a sentence, click the speech-bubble icon that appears, and write your remark. The author gets a notification, can reply to you, and clicks \"Resolve\" once the question is settled. It is perfect for reviewing someone's work without erasing their text.\n\nTwo tools round out collaboration. \"Suggesting mode\" (in Docs) proposes your changes without imposing them: the author accepts or rejects them with a click. And the \"version history\" (File menu) keeps track of all changes, with who did what and when; you can even go back to an earlier version if needed. Nothing is ever truly lost.",
            es: "Una vez que un documento se comparte en modo «Editor», empieza la verdadera magia de Google: varias personas pueden escribir en el mismo documento al mismo tiempo, cada una desde su propia computadora. Es lo que se llama colaboración en tiempo real, y funciona tanto en Docs como en Sheets o Slides.\n\nCuando otra persona trabaja en el documento, ves su cursor moverse, a menudo de un color distinto, con su nombre al lado. Todo lo que escribe aparece ante tus ojos en directo, y todo se guarda automáticamente. Se acabaron los envíos de archivos de ida y vuelta por correo: cada uno ve siempre la última versión.\n\nPara intercambiar sin modificar el texto, usa los «comentarios». Selecciona una palabra o una frase, haz clic en el icono de globo que aparece, y escribe tu observación. El autor recibe una notificación, puede responderte, y hace clic en «Resolver» una vez zanjada la cuestión. Es perfecto para revisar el trabajo de alguien sin borrar su texto.\n\nDos herramientas completan la colaboración. El «modo Sugerencias» (en Docs) propone tus modificaciones sin imponerlas: el autor las acepta o las rechaza con un clic. Y el «historial de versiones» (menú Archivo) guarda el rastro de todos los cambios, con quién hizo qué y cuándo; incluso puedes volver a una versión anterior si es necesario. Nada se pierde nunca de verdad.",
          },
          keyPoints: {
            fr: ["Plusieurs personnes écrivent dans le même document en même temps", "On voit le curseur et le nom des autres ; tout s'enregistre seul", "Les commentaires laissent des remarques sans modifier le texte", "Mode Suggestion et historique des versions gardent tout sous contrôle"],
            ht: ["Plizyè moun ekri nan menm dokiman an an menm tan", "Ou wè kurzè ak non lòt yo ; tout anrejistre pou kont li", "Commentaires yo kite remak san modifye tèks la", "Mode Suggestion ak historique des versions kenbe tout sou kontwòl"],
            en: ["Several people write in the same document at the same time", "You see others' cursor and name; everything saves by itself", "Comments leave remarks without changing the text", "Suggesting mode and version history keep everything under control"],
            es: ["Varias personas escriben en el mismo documento al mismo tiempo", "Se ve el cursor y el nombre de los demás; todo se guarda solo", "Los comentarios dejan observaciones sin modificar el texto", "El modo Sugerencias y el historial de versiones mantienen todo bajo control"],
          },
          exercise: {
            fr: "Dans un document Docs partagé, sélectionne une phrase et ajoute un commentaire avec l'icône de bulle. Ouvre ensuite « Fichier > Historique des versions » pour voir la liste des modifications enregistrées.",
            ht: "Nan yon dokiman Docs pataje, chwazi yon fraz epi ajoute yon kòmantè ak ikòn bul la. Apre ouvri « Fichier > Historique des versions » pou wè lis modifikasyon ki anrejistre yo.",
            en: "In a shared Docs document, select a sentence and add a comment with the speech-bubble icon. Then open \"File > Version history\" to see the list of saved changes.",
            es: "En un documento de Docs compartido, selecciona una frase y añade un comentario con el icono de globo. Luego abre «Archivo > Historial de versiones» para ver la lista de modificaciones guardadas.",
          },
        },
        {
          slug: "reunion-avec-meet",
          title: { fr: "Se réunir en vidéo avec Meet", ht: "Fè reyinyon videyo ak Meet", en: "Meeting by video with Meet", es: "Reunirse por video con Meet" },
          videoId: "",
          content: {
            fr: "Google Meet est l'outil de visioconférence gratuit de Google : il permet de se voir et de se parler à distance, par vidéo et par son, comme un appel où l'on se voit à l'écran. C'est idéal pour une réunion de travail, un cours ou simplement pour parler à la famille éloignée, sans rien installer sur ordinateur.\n\nPour démarrer une réunion, va sur meet.google.com et clique sur « Nouvelle réunion ». Meet crée un lien unique, une adresse qui mène à ta salle virtuelle. Tu copies ce lien et tu l'envoies aux personnes que tu veux inviter, par courriel ou par message. Au moment voulu, chacun clique sur le lien pour entrer dans la réunion.\n\nAvant d'entrer, ton appareil te demande l'autorisation d'utiliser la caméra et le microphone : accepte pour être vu et entendu. À l'écran, deux boutons essentiels : le microphone, que tu peux couper quand tu ne parles pas pour éviter les bruits, et la caméra, que tu peux éteindre si tu ne veux pas être filmé. Le bouton rouge quitte la réunion.\n\nMeet offre des fonctions pratiques pendant l'appel. Le « chat » (une bulle de discussion) permet d'écrire un message à tous, par exemple un lien. Le « partage d'écran » montre aux autres ce que tu as sur ton écran, très utile pour présenter un document. Pense à tester ta caméra et ton micro quelques minutes avant, et installe-toi dans un endroit calme et bien éclairé.",
            ht: "Google Meet se zouti videyokonferans gratis Google la : li pèmèt wè epi pale ak moun a distans, pa videyo epi pa son, tankou yon apèl kote nou wè youn lòt sou ekran. Li ideyal pou yon reyinyon travay, yon kou oswa senpleman pou pale ak fanmi ki lwen, san enstale anyen sou òdinatè.\n\nPou kòmanse yon reyinyon, ale sou meet.google.com epi klike sou « Nouvelle réunion ». Meet kreye yon lyen inik, yon adrès ki mennen nan sal vityèl ou. Ou kopye lyen sa a epi ou voye l bay moun ou vle envite yo, pa imèl oswa pa mesaj. Nan moman ou vle a, chak moun klike sou lyen an pou antre nan reyinyon an.\n\nAnvan ou antre, aparèy ou mande otorizasyon pou itilize kamera ak mikwo : aksepte pou yo ka wè epi tande ou. Sou ekran, de bouton esansyèl : mikwo a, ke ou ka koupe lè ou pa pale pou evite bri, ak kamera a, ke ou ka etenn si ou pa vle yo filme ou. Bouton wouj la kite reyinyon an.\n\nMeet ofri fonksyon pratik pandan apèl la. « Chat » a (yon bul diskisyon) pèmèt ekri yon mesaj bay tout moun, pa egzanp yon lyen. « Partage d'écran » montre lòt yo sa ou genyen sou ekran ou, trè itil pou prezante yon dokiman. Panse pou teste kamera ak mikwo ou kèk minit anvan, epi enstale ou nan yon kote ki kalm epi byen eklere.",
            en: "Google Meet is Google's free video-conferencing tool: it lets you see and talk with people at a distance, by video and sound, like a call where you see each other on screen. It is ideal for a work meeting, a class or simply to talk with distant family, without installing anything on a computer.\n\nTo start a meeting, go to meet.google.com and click \"New meeting\". Meet creates a unique link, an address that leads to your virtual room. You copy this link and send it to the people you want to invite, by email or by message. At the chosen time, everyone clicks the link to enter the meeting.\n\nBefore entering, your device asks permission to use the camera and microphone: accept to be seen and heard. On screen, two essential buttons: the microphone, which you can mute when you are not speaking to avoid noise, and the camera, which you can turn off if you do not want to be filmed. The red button leaves the meeting.\n\nMeet offers handy functions during the call. The \"chat\" (a discussion bubble) lets you write a message to everyone, for example a link. \"Screen sharing\" shows others what is on your screen, very useful to present a document. Remember to test your camera and mic a few minutes before, and settle in a quiet, well-lit place.",
            es: "Google Meet es la herramienta de videoconferencia gratuita de Google: permite verse y hablar con personas a distancia, por video y sonido, como una llamada en la que os veis en la pantalla. Es ideal para una reunión de trabajo, una clase o simplemente para hablar con la familia lejana, sin instalar nada en la computadora.\n\nPara iniciar una reunión, ve a meet.google.com y haz clic en «Nueva reunión». Meet crea un enlace único, una dirección que lleva a tu sala virtual. Copias ese enlace y lo envías a las personas que quieres invitar, por correo o por mensaje. A la hora prevista, cada uno hace clic en el enlace para entrar en la reunión.\n\nAntes de entrar, tu dispositivo pide permiso para usar la cámara y el micrófono: acepta para ser visto y oído. En la pantalla, dos botones esenciales: el micrófono, que puedes silenciar cuando no hablas para evitar ruidos, y la cámara, que puedes apagar si no quieres ser filmado. El botón rojo abandona la reunión.\n\nMeet ofrece funciones prácticas durante la llamada. El «chat» (una burbuja de conversación) permite escribir un mensaje a todos, por ejemplo un enlace. La «compartir pantalla» muestra a los demás lo que tienes en tu pantalla, muy útil para presentar un documento. Acuérdate de probar tu cámara y micrófono unos minutos antes, e instálate en un lugar tranquilo y bien iluminado.",
          },
          keyPoints: {
            fr: ["Meet permet de se voir et se parler à distance, gratuitement", "« Nouvelle réunion » crée un lien à envoyer aux invités", "Boutons clés : couper le micro, éteindre la caméra, quitter (rouge)", "Chat et partage d'écran aident ; tester micro et caméra avant"],
            ht: ["Meet pèmèt wè epi pale a distans, gratis", "« Nouvelle réunion » kreye yon lyen pou voye bay envite yo", "Bouton kle : koupe mikwo, etenn kamera, kite (wouj)", "Chat ak partage d'écran ede ; teste mikwo ak kamera anvan"],
            en: ["Meet lets you see and talk at a distance, for free", "\"New meeting\" creates a link to send to the guests", "Key buttons: mute the mic, turn off the camera, leave (red)", "Chat and screen sharing help; test mic and camera before"],
            es: ["Meet permite verse y hablar a distancia, gratis", "«Nueva reunión» crea un enlace para enviar a los invitados", "Botones clave: silenciar el micro, apagar la cámara, salir (rojo)", "El chat y compartir pantalla ayudan; probar micro y cámara antes"],
          },
          exercise: {
            fr: "Va sur meet.google.com et clique sur « Nouvelle réunion » pour créer un lien. Entre dans la salle, autorise ta caméra et ton micro, puis exerce-toi à couper puis rallumer le micro et à repérer les boutons de chat et de partage d'écran.",
            ht: "Ale sou meet.google.com epi klike sou « Nouvelle réunion » pou kreye yon lyen. Antre nan sal la, otorize kamera ak mikwo ou, apre egzèse ou koupe apre rilimen mikwo a epi jwenn bouton chat ak partage d'écran yo.",
            en: "Go to meet.google.com and click \"New meeting\" to create a link. Enter the room, allow your camera and mic, then practice muting then unmuting the mic and locating the chat and screen-sharing buttons.",
            es: "Ve a meet.google.com y haz clic en «Nueva reunión» para crear un enlace. Entra en la sala, autoriza tu cámara y micrófono, luego practica silenciar y reactivar el micro y localizar los botones de chat y compartir pantalla.",
          },
        },
      ],
    },
    {
      title: { fr: "Organiser et sécuriser", ht: "Òganize epi sekirize", en: "Organize and secure", es: "Organizar y proteger" },
      lessons: [
        {
          slug: "creer-un-evenement",
          title: { fr: "Créer un événement dans l'Agenda", ht: "Kreye yon evènman nan Agenda a", en: "Creating an event in Calendar", es: "Crear un evento en Calendar" },
          videoId: "",
          content: {
            fr: "Google Agenda est un calendrier électronique qui t'aide à ne rien oublier : rendez-vous, réunions, anniversaires ou tâches importantes. Il est lié à ton compte Google et se retrouve sur tous tes appareils. Pour l'ouvrir, va sur calendar.google.com. Tu vois alors les jours du mois, avec la date d'aujourd'hui mise en évidence.\n\nPour ajouter un rendez-vous, clique sur le jour concerné, ou sur le bouton « Créer ». Une fenêtre s'ouvre : donne un titre à l'événement (par exemple « Visite médecin »), choisis la date et l'heure de début et de fin. Tu peux aussi ajouter un lieu et une petite note. Clique enfin sur « Enregistrer » et l'événement apparaît dans ton calendrier.\n\nTu peux afficher ton agenda par jour, par semaine ou par mois, selon ce qui t'aide le mieux à voir clair. Chaque événement s'affiche comme un petit bloc coloré. En un coup d'œil, tu sais ce que tu as à faire et quand, ce qui aide à mieux organiser tes journées.\n\nL'Agenda se marie très bien avec les autres outils. En créant un événement, tu peux inviter des personnes en tapant leur adresse Gmail : elles reçoivent l'invitation et peuvent répondre « Oui » ou « Non ». Tu peux même ajouter une visioconférence Meet en un clic : un lien apparaît dans l'événement, prêt à cliquer au moment de la réunion.",
            ht: "Google Agenda se yon kalandriye elektwonik ki ede w pa bliye anyen : randevou, reyinyon, anivèsè oswa tach enpòtan. Li lye ak kont Google ou epi li jwenn sou tout aparèy ou yo. Pou louvri l, ale sou calendar.google.com. Ou wè apre jou nan mwa a, ak dat jodi a ki make.\n\nPou ajoute yon randevou, klike sou jou konsène a, oswa sou bouton « Kreye ». Yon fenèt louvri : bay evènman an yon tit (pa egzanp « Vizit doktè »), chwazi dat la ak lè kòmansman ak fen an. Ou ka tou ajoute yon kote ak yon ti nòt. Klike anfen sou « Anrejistre » epi evènman an parèt nan kalandriye ou.\n\nOu ka afiche agenda ou pa jou, pa semèn oswa pa mwa, selon sa ki ede w pi byen wè klè. Chak evènman afiche tankou yon ti blòk kolore. Nan yon sèl kout je, ou konnen sa ou gen pou fè ak kilè, sa ki ede òganize jounen ou pi byen.\n\nAgenda a marye trè byen ak lòt zouti yo. Lè w kreye yon evènman, ou ka envite moun lè w tape adrès Gmail yo : yo resevwa envitasyon an epi yo ka reponn « Wi » oswa « Non ». Ou ka menm ajoute yon videyokonferans Meet ak yon klik : yon lyen parèt nan evènman an, pare pou klike nan moman reyinyon an.",
            en: "Google Calendar is an electronic calendar that helps you forget nothing: appointments, meetings, birthdays or important tasks. It is linked to your Google account and is found on all your devices. To open it, go to calendar.google.com. You then see the days of the month, with today's date highlighted.\n\nTo add an appointment, click on the day concerned, or on the \"Create\" button. A window opens: give the event a title (for example \"Doctor visit\"), choose the date and the start and end time. You can also add a location and a small note. Finally click \"Save\" and the event appears in your calendar.\n\nYou can display your calendar by day, by week or by month, according to what helps you see clearly. Each event shows as a small colored block. At a glance, you know what you have to do and when, which helps you organize your days better.\n\nCalendar pairs very well with the other tools. When creating an event, you can invite people by typing their Gmail address: they receive the invitation and can answer \"Yes\" or \"No\". You can even add a Meet video conference in one click: a link appears in the event, ready to click at meeting time.",
            es: "Google Calendar es un calendario electrónico que te ayuda a no olvidar nada: citas, reuniones, cumpleaños o tareas importantes. Está vinculado a tu cuenta de Google y se encuentra en todos tus dispositivos. Para abrirlo, ve a calendar.google.com. Entonces ves los días del mes, con la fecha de hoy resaltada.\n\nPara añadir una cita, haz clic en el día correspondiente, o en el botón «Crear». Se abre una ventana: dale un título al evento (por ejemplo «Visita médico»), elige la fecha y la hora de inicio y de fin. También puedes añadir un lugar y una pequeña nota. Haz clic finalmente en «Guardar» y el evento aparece en tu calendario.\n\nPuedes mostrar tu calendario por día, por semana o por mes, según lo que te ayude a ver mejor. Cada evento se muestra como un pequeño bloque de color. De un vistazo, sabes qué tienes que hacer y cuándo, lo que ayuda a organizar mejor tus días.\n\nCalendar combina muy bien con las demás herramientas. Al crear un evento, puedes invitar a personas escribiendo su dirección de Gmail: reciben la invitación y pueden responder «Sí» o «No». Incluso puedes añadir una videoconferencia de Meet con un clic: un enlace aparece en el evento, listo para hacer clic a la hora de la reunión.",
          },
          keyPoints: {
            fr: ["Agenda regroupe rendez-vous et tâches sur tous tes appareils", "Créer : titre, date, heure de début et de fin, puis Enregistrer", "Vue par jour, semaine ou mois pour voir clair d'un coup d'œil", "On peut inviter des personnes et ajouter un lien Meet à l'événement"],
            ht: ["Agenda rasanble randevou ak tach sou tout aparèy ou", "Kreye : tit, dat, lè kòmansman ak fen, apre Anrejistre", "Vi pa jou, semèn oswa mwa pou wè klè nan yon kout je", "Ou ka envite moun epi ajoute yon lyen Meet nan evènman an"],
            en: ["Calendar gathers appointments and tasks on all your devices", "Create: title, date, start and end time, then Save", "View by day, week or month to see clearly at a glance", "You can invite people and add a Meet link to the event"],
            es: ["Calendar reúne citas y tareas en todos tus dispositivos", "Crear: título, fecha, hora de inicio y fin, luego Guardar", "Vista por día, semana o mes para ver claro de un vistazo", "Se puede invitar a personas y añadir un enlace de Meet al evento"],
          },
          exercise: {
            fr: "Sur calendar.google.com, crée un événement « Rendez-vous » demain à une heure précise, ajoute un lieu et une note, puis enregistre-le. Change ensuite l'affichage de « Mois » à « Semaine » pour bien le repérer.",
            ht: "Sou calendar.google.com, kreye yon evènman « Randevou » demen nan yon lè presi, ajoute yon kote ak yon nòt, apre anrejistre l. Apre chanje afichaj la soti nan « Mois » al nan « Semaine » pou byen jwenn li.",
            en: "On calendar.google.com, create a \"Meeting\" event tomorrow at a specific time, add a location and a note, then save it. Then change the view from \"Month\" to \"Week\" to spot it clearly.",
            es: "En calendar.google.com, crea un evento «Cita» mañana a una hora concreta, añade un lugar y una nota, luego guárdalo. Después cambia la vista de «Mes» a «Semana» para localizarlo bien.",
          },
        },
        {
          slug: "rappels-et-notifications",
          title: { fr: "Rappels et notifications", ht: "Rapèl ak notifikasyon", en: "Reminders and notifications", es: "Recordatorios y notificaciones" },
          videoId: "",
          content: {
            fr: "L'intérêt le plus précieux de l'Agenda, c'est qu'il peut te prévenir avant un événement. C'est ce qu'on appelle un « rappel » ou une « notification ». Ainsi, tu ne risques plus d'oublier un rendez-vous, même si tu es occupé à autre chose.\n\nQuand tu crées ou modifies un événement, cherche l'option « Notification » ou « Rappel ». Tu choisis combien de temps avant tu veux être prévenu : par exemple dix minutes, une heure ou un jour à l'avance. À l'heure prévue, ton téléphone ou ton ordinateur affiche un message et fait parfois un son, pour te rappeler ce qui arrive.\n\nTu peux mettre plusieurs rappels pour un même événement important : un la veille pour te préparer, et un autre juste avant. Pour les rendez-vous qui reviennent (comme une réunion chaque lundi), Agenda propose de « répéter » l'événement automatiquement. Tu n'as plus besoin de le réécrire chaque semaine : l'outil s'en souvient à ta place.\n\nPour que les rappels fonctionnent bien, deux conditions. D'abord, sur le téléphone, l'application Google Agenda doit avoir l'autorisation d'afficher des notifications ; vérifie-le dans les réglages de l'appareil. Ensuite, choisis un délai adapté à chaque situation : dix minutes suffisent pour un appel, mais un rendez-vous lointain mérite un rappel la veille pour avoir le temps de t'organiser.",
            ht: "Enterè ki pi presye nan Agenda a, se ke li ka avèti w anvan yon evènman. Se sa yo rele yon « rapèl » oswa yon « notifikasyon ». Konsa, ou pa riske bliye yon randevou ankò, menm si ou okipe ak yon lòt bagay.\n\nLè w kreye oswa modifye yon evènman, chèche opsyon « Notifikasyon » oswa « Rapèl ». Ou chwazi konbyen tan anvan ou vle yo avèti w : pa egzanp dis minit, yon èdtan oswa yon jou davans. Nan lè ki prevwa a, telefòn ou oswa òdinatè ou afiche yon mesaj epi pafwa li fè yon son, pou raple w sa k ap vini an.\n\nOu ka mete plizyè rapèl pou yon menm evènman enpòtan : youn lavèy pou prepare w, ak yon lòt jis anvan. Pou randevou ki tounen (tankou yon reyinyon chak lendi), Agenda pwopoze pou « repete » evènman an otomatikman. Ou pa bezwen reekri l chak semèn ankò : zouti a sonje l pou ou.\n\nPou rapèl yo mache byen, de kondisyon. Dabò, sou telefòn, aplikasyon Google Agenda a dwe gen otorizasyon pou afiche notifikasyon ; verifye sa nan reglaj aparèy la. Apre sa, chwazi yon delè ki adapte ak chak sitiyasyon : dis minit ase pou yon apèl, men yon randevou ki lwen merite yon rapèl lavèy pou w gen tan òganize w.",
            en: "The most valuable benefit of Calendar is that it can warn you before an event. This is what we call a \"reminder\" or a \"notification.\" That way, you no longer risk forgetting an appointment, even if you are busy with something else.\n\nWhen you create or edit an event, look for the \"Notification\" or \"Reminder\" option. You choose how long before you want to be warned: for example ten minutes, one hour or one day ahead. At the set time, your phone or computer shows a message and sometimes makes a sound, to remind you of what is coming.\n\nYou can set several reminders for the same important event: one the day before to prepare, and another just before. For recurring appointments (like a meeting every Monday), Calendar offers to \"repeat\" the event automatically. You no longer need to rewrite it each week: the tool remembers it for you.\n\nFor reminders to work well, two conditions. First, on the phone, the Google Calendar app must have permission to show notifications; check it in the device settings. Second, choose a delay suited to each situation: ten minutes is enough for a call, but a distant appointment deserves a reminder the day before so you have time to get organized.",
            es: "El beneficio más valioso de Calendar es que puede avisarte antes de un evento. Es lo que llamamos un «recordatorio» o una «notificación». Así, ya no corres el riesgo de olvidar una cita, aunque estés ocupado con otra cosa.\n\nCuando creas o modificas un evento, busca la opción «Notificación» o «Recordatorio». Eliges con cuánto tiempo de antelación quieres ser avisado: por ejemplo diez minutos, una hora o un día antes. A la hora prevista, tu teléfono o computadora muestra un mensaje y a veces hace un sonido, para recordarte lo que viene.\n\nPuedes poner varios recordatorios para un mismo evento importante: uno la víspera para prepararte, y otro justo antes. Para las citas que se repiten (como una reunión cada lunes), Calendar propone «repetir» el evento automáticamente. Ya no necesitas reescribirlo cada semana: la herramienta lo recuerda por ti.\n\nPara que los recordatorios funcionen bien, dos condiciones. Primero, en el teléfono, la aplicación Google Calendar debe tener permiso para mostrar notificaciones; compruébalo en los ajustes del dispositivo. Segundo, elige un plazo adecuado a cada situación: diez minutos bastan para una llamada, pero una cita lejana merece un recordatorio la víspera para tener tiempo de organizarte.",
          },
          keyPoints: {
            fr: ["Un rappel te prévient avant l'événement (10 min, 1 h, 1 jour…)", "Le téléphone ou l'ordinateur affiche un message à l'heure prévue", "Les événements récurrents se répètent automatiquement", "Autoriser les notifications de l'appli et choisir un délai adapté"],
            ht: ["Yon rapèl avèti w anvan evènman an (10 min, 1 è, 1 jou…)", "Telefòn oswa òdinatè afiche yon mesaj nan lè ki prevwa a", "Evènman ki tounen yo repete otomatikman", "Otorize notifikasyon apli a epi chwazi yon delè ki adapte"],
            en: ["A reminder warns you before the event (10 min, 1 h, 1 day…)", "The phone or computer shows a message at the set time", "Recurring events repeat automatically", "Allow the app's notifications and choose a suitable delay"],
            es: ["Un recordatorio te avisa antes del evento (10 min, 1 h, 1 día…)", "El teléfono o la computadora muestra un mensaje a la hora prevista", "Los eventos recurrentes se repiten automáticamente", "Permitir las notificaciones de la app y elegir un plazo adecuado"],
          },
          exercise: {
            fr: "Ouvre un événement de ton agenda et ajoute deux rappels : un la veille et un dix minutes avant. Si l'événement se répète chaque semaine, active l'option « Répéter » et vérifie qu'il apparaît bien les semaines suivantes.",
            ht: "Ouvri yon evènman nan agenda ou epi ajoute de rapèl : youn lavèy la ak youn dis minit anvan. Si evènman an repete chak semèn, aktive opsyon « Répéter » a epi verifye li parèt byen nan semèn ki vin apre yo.",
            en: "Open an event in your calendar and add two reminders: one the day before and one ten minutes before. If the event repeats every week, enable the \"Repeat\" option and check that it appears in the following weeks.",
            es: "Abre un evento de tu calendario y añade dos recordatorios: uno la víspera y uno diez minutos antes. Si el evento se repite cada semana, activa la opción «Repetir» y comprueba que aparece en las semanas siguientes.",
          },
        },
        {
          slug: "securite-du-compte",
          title: { fr: "Protéger la sécurité de son compte", ht: "Pwoteje sekirite kont ou", en: "Protecting your account's security", es: "Proteger la seguridad de tu cuenta" },
          videoId: "",
          content: {
            fr: "Ton compte Google contient tes courriels, tes photos, tes documents : le protéger est essentiel. Toute la sécurité se règle au même endroit : va sur myaccount.google.com, puis dans la rubrique « Sécurité ». Cette page rassemble tout ce qui protège ton compte et signale les points à améliorer.\n\nLa première protection est un bon mot de passe, connu de toi seul. Choisis-en un long, mêlant lettres, chiffres et symboles, et différent de ceux de tes autres comptes. Ne le communique jamais par courriel ni par téléphone : Google ne te le demandera jamais. Si tu penses qu'il a été vu par quelqu'un, change-le aussitôt depuis cette page « Sécurité ».\n\nLa protection la plus efficace s'appelle la « validation en deux étapes ». Une fois activée, en plus de ton mot de passe, Google envoie un code à ton téléphone (par message ou dans une application) à chaque nouvelle connexion. Ainsi, même si quelqu'un devinait ton mot de passe, il ne pourrait pas entrer sans ton téléphone. C'est la meilleure barrière contre le vol de compte.\n\nPrévois aussi les moyens de récupération, au cas où tu perdrais l'accès : un numéro de téléphone et une adresse courriel de secours, à renseigner dans la page Sécurité. Enfin, méfie-toi de l'« hameçonnage » (phishing) : ce sont de faux messages qui imitent Google pour te voler ton mot de passe. Ne clique jamais sur un lien pressant qui te réclame tes identifiants ; en cas de doute, tape toi-même l'adresse du site.",
            ht: "Kont Google ou gen imèl ou, foto ou, dokiman ou : pwoteje l esansyèl. Tout sekirite a regle nan menm kote : ale sou myaccount.google.com, apre nan rubrik « Sécurité » a. Paj sa a rasanble tout sa ki pwoteje kont ou epi li siyale pwen pou amelyore yo.\n\nPremye pwoteksyon an se yon bon modpas, ou menm sèl ki konnen l. Chwazi youn ki long, ki melanje lèt, chif ak senbòl, epi ki diferan de sa lòt kont ou yo. Pa janm bay li pa imèl ni pa telefòn : Google p ap janm mande w li. Si ou panse yon moun wè l, chanje l touswit soti nan paj « Sécurité » a.\n\nPwoteksyon ki pi efikas la rele « validation en deux étapes ». Yon fwa ou aktive l, anplis modpas ou, Google voye yon kòd sou telefòn ou (pa mesaj oswa nan yon aplikasyon) chak nouvo koneksyon. Konsa, menm si yon moun ta devine modpas ou, li p ap ka antre san telefòn ou. Se pi bon baryè kont vòl kont.\n\nPrevwa tou mwayen rekiperasyon yo, si ou ta pèdi aksè : yon nimewo telefòn ak yon adrès imèl sekou, pou mete nan paj Sécurité a. Anfen, mefye w de « hameçonnage » (phishing) : se fo mesaj ki imite Google pou vòlè modpas ou. Pa janm klike sou yon lyen prese ki reklame idantifyan ou ; si ou gen dout, tape adrès sit la ou menm.",
            en: "Your Google account holds your emails, your photos, your documents: protecting it is essential. All security is set in the same place: go to myaccount.google.com, then to the \"Security\" section. This page gathers everything that protects your account and flags the points to improve.\n\nThe first protection is a good password, known only to you. Choose a long one, mixing letters, numbers and symbols, and different from those of your other accounts. Never share it by email or phone: Google will never ask you for it. If you think someone has seen it, change it right away from this \"Security\" page.\n\nThe most effective protection is called \"2-Step Verification\". Once enabled, in addition to your password, Google sends a code to your phone (by message or in an app) at each new login. That way, even if someone guessed your password, they could not get in without your phone. It is the best barrier against account theft.\n\nAlso set up recovery means, in case you lose access: a phone number and a backup email address, to enter on the Security page. Finally, beware of \"phishing\": these are fake messages that imitate Google to steal your password. Never click an urgent link that demands your credentials; when in doubt, type the site's address yourself.",
            es: "Tu cuenta de Google contiene tus correos, tus fotos, tus documentos: protegerla es esencial. Toda la seguridad se ajusta en el mismo sitio: ve a myaccount.google.com, luego a la sección «Seguridad». Esta página reúne todo lo que protege tu cuenta y señala los puntos a mejorar.\n\nLa primera protección es una buena contraseña, conocida solo por ti. Elige una larga, que mezcle letras, números y símbolos, y distinta de las de tus otras cuentas. Nunca la comuniques por correo ni por teléfono: Google nunca te la pedirá. Si crees que alguien la ha visto, cámbiala enseguida desde esta página «Seguridad».\n\nLa protección más eficaz se llama «verificación en dos pasos». Una vez activada, además de tu contraseña, Google envía un código a tu teléfono (por mensaje o en una aplicación) en cada nuevo inicio de sesión. Así, aunque alguien adivinara tu contraseña, no podría entrar sin tu teléfono. Es la mejor barrera contra el robo de cuenta.\n\nPrevé también los medios de recuperación, por si pierdes el acceso: un número de teléfono y una dirección de correo de respaldo, a rellenar en la página Seguridad. Por último, desconfía del «phishing»: son mensajes falsos que imitan a Google para robar tu contraseña. Nunca hagas clic en un enlace urgente que te reclame tus credenciales; en caso de duda, escribe tú mismo la dirección del sitio.",
          },
          keyPoints: {
            fr: ["Tout se règle sur myaccount.google.com, rubrique « Sécurité »", "Un mot de passe long et unique ; ne jamais le communiquer", "La validation en deux étapes ajoute un code envoyé au téléphone", "Prévoir téléphone et courriel de secours ; se méfier de l'hameçonnage"],
            ht: ["Tout regle sou myaccount.google.com, rubrik « Sécurité »", "Yon modpas long epi inik ; pa janm bay li", "Validation en deux étapes ajoute yon kòd yo voye sou telefòn", "Prevwa telefòn ak imèl sekou ; mefye w de hameçonnage"],
            en: ["Everything is set on myaccount.google.com, \"Security\" section", "A long, unique password; never share it", "2-Step Verification adds a code sent to the phone", "Set up backup phone and email; beware of phishing"],
            es: ["Todo se ajusta en myaccount.google.com, sección «Seguridad»", "Una contraseña larga y única; nunca comunicarla", "La verificación en dos pasos añade un código enviado al teléfono", "Prever teléfono y correo de respaldo; desconfiar del phishing"],
          },
          exercise: {
            fr: "Va sur myaccount.google.com, ouvre la rubrique « Sécurité » et repère l'état de ton mot de passe et de la validation en deux étapes. Vérifie qu'un numéro de téléphone et une adresse de secours sont bien renseignés, et active la validation en deux étapes si ce n'est pas déjà fait.",
            ht: "Ale sou myaccount.google.com, ouvri rubrik « Sécurité » a epi jwenn eta modpas ou ak validation en deux étapes la. Verifye yon nimewo telefòn ak yon adrès sekou byen mete, epi aktive validation en deux étapes la si li poko fèt.",
            en: "Go to myaccount.google.com, open the \"Security\" section and check the status of your password and of 2-Step Verification. Verify that a phone number and a backup address are set, and enable 2-Step Verification if it is not already done.",
            es: "Ve a myaccount.google.com, abre la sección «Seguridad» y revisa el estado de tu contraseña y de la verificación en dos pasos. Comprueba que un número de teléfono y una dirección de respaldo están puestos, y activa la verificación en dos pasos si no lo está ya.",
          },
        },
      ],
    },
  ],
};

export default google;
