import { CourseContent } from "./types";

const informatique: CourseContent = {
  slug: "informatique",
  intro: {
    fr: "Découvrir l'ordinateur pas à pas : comprendre ce qu'est une machine, savoir utiliser la souris et le clavier, organiser ses fichiers et entretenir sa machine avec confiance, même en partant de zéro.",
    ht: "Dekouvri òdinatè a etap pa etap : konprann kisa yon machin ye, konnen kijan pou sèvi ak sourit ak klavye, òganize fichye ou yo epi antretni machin ou ak konfyans, menm si w ap kòmanse depi zewo.",
    en: "Discover the computer step by step: understand what a machine is, learn to use the mouse and keyboard, organize your files and maintain your machine with confidence, even starting from scratch.",
    es: "Descubrir la computadora paso a paso: comprender qué es una máquina, saber usar el ratón y el teclado, organizar tus archivos y mantener tu máquina con confianza, incluso empezando desde cero.",
  },
  modules: [
    {
      title: { fr: "Comprendre l'ordinateur", ht: "Konprann òdinatè a", en: "Understanding the computer", es: "Comprender la computadora" },
      lessons: [
        {
          slug: "quest-ce-quun-ordinateur",
          title: { fr: "Qu'est-ce qu'un ordinateur ?", ht: "Kisa yon òdinatè ye ?", en: "What is a computer?", es: "¿Qué es una computadora?" },
          videoId: "",
          content: {
            fr: "Un ordinateur est une machine qui reçoit des informations, les traite et te donne un résultat. Tu lui donnes des ordres (taper un texte, ouvrir une photo) et il les exécute très vite. Il ne faut pas en avoir peur : c'est un outil, comme un stylo ou une calculatrice, mais beaucoup plus puissant.\n\nUn ordinateur se compose de deux grandes parties. Le matériel (le « hardware ») est tout ce que tu peux toucher : l'écran qui affiche les images, le clavier pour écrire, la souris pour pointer, et l'unité centrale qui contient le « cerveau » de la machine. Les logiciels (le « software ») sont les programmes invisibles qui font fonctionner tout cela, comme le système Windows ou un traitement de texte.\n\nIl existe plusieurs formes d'ordinateurs : l'ordinateur de bureau qui reste sur une table, l'ordinateur portable que l'on transporte, et même le téléphone intelligent qui est un petit ordinateur dans ta poche. Tous suivent le même principe : allumer, utiliser, puis éteindre correctement pour ne rien abîmer.\n\nComprendre ce vocabulaire de base te met en confiance. Chaque fois que tu entends un mot nouveau, retiens qu'il désigne soit une pièce que l'on touche, soit un programme qui s'exécute. Avec cette simple distinction, tout le reste devient plus clair.",
            ht: "Yon òdinatè se yon machin ki resevwa enfòmasyon, trete yo epi ba ou yon rezilta. Ou ba li lòd (tape yon tèks, louvri yon foto) epi li egzekite yo byen vit. Ou pa dwe pè li : se yon zouti, tankou yon plim oswa yon kalkilatris, men li pi pisan anpil.\n\nYon òdinatè gen de gwo pati. Materyèl la (« hardware ») se tout sa ou ka manyen : ekran ki montre imaj yo, klavye pou ekri, sourit pou pwente, ak inite santral la ki genyen « sèvo » machin nan. Lojisyèl yo (« software ») se pwogram envizib ki fè tout sa fonksyone, tankou sistèm Windows lan oswa yon pwogram pou ekri tèks.\n\nGen plizyè fòm òdinatè : òdinatè biwo a ki rete sou yon tab, òdinatè pòtab la ou ka pote ale, e menm telefòn entèlijan an ki se yon ti òdinatè nan pòch ou. Yo tout swiv menm prensip la : limen, itilize, epi etenn kòrèkteman pou ou pa gate anyen.\n\nKonprann vokabilè debaz sa a ba ou konfyans. Chak fwa ou tande yon mo nouvo, sonje li vle di swa yon pyès ou ka manyen, swa yon pwogram k ap egzekite. Ak senp distenksyon sa a, tout rès la vin pi klè.",
            en: "A computer is a machine that receives information, processes it and gives you a result. You give it commands (type a text, open a photo) and it carries them out very quickly. There is no need to fear it: it is a tool, like a pen or a calculator, but far more powerful.\n\nA computer has two main parts. The hardware is everything you can touch: the screen that displays images, the keyboard for writing, the mouse for pointing, and the main unit that holds the machine's \"brain.\" The software is the invisible programs that make it all work, like the Windows system or a word processor.\n\nThere are several kinds of computers: the desktop that stays on a table, the laptop you can carry around, and even the smartphone which is a small computer in your pocket. They all follow the same principle: turn it on, use it, then shut it down properly so nothing gets damaged.\n\nUnderstanding this basic vocabulary builds your confidence. Each time you hear a new word, remember it names either a part you can touch or a program that runs. With this simple distinction, everything else becomes clearer.",
            es: "Una computadora es una máquina que recibe información, la procesa y te da un resultado. Le das órdenes (escribir un texto, abrir una foto) y las ejecuta muy rápido. No hay que tenerle miedo: es una herramienta, como un bolígrafo o una calculadora, pero mucho más poderosa.\n\nUna computadora tiene dos grandes partes. El hardware es todo lo que puedes tocar: la pantalla que muestra las imágenes, el teclado para escribir, el ratón para señalar, y la unidad central que contiene el «cerebro» de la máquina. El software son los programas invisibles que hacen funcionar todo eso, como el sistema Windows o un procesador de textos.\n\nExisten varias formas de computadoras: la de escritorio que se queda sobre una mesa, la portátil que se transporta, e incluso el teléfono inteligente, que es una pequeña computadora en tu bolsillo. Todas siguen el mismo principio: encender, usar, y luego apagar correctamente para no dañar nada.\n\nComprender este vocabulario básico te da confianza. Cada vez que oigas una palabra nueva, recuerda que designa o una pieza que se toca o un programa que se ejecuta. Con esta simple distinción, todo lo demás se vuelve más claro.",
          },
          keyPoints: {
            fr: ["L'ordinateur est un outil : il reçoit, traite et donne un résultat", "Le matériel se touche, le logiciel fait fonctionner", "Bureau, portable ou téléphone suivent le même principe", "Chaque mot nouveau désigne soit une pièce, soit un programme"],
            ht: ["Òdinatè a se yon zouti : li resevwa, trete epi bay rezilta", "Materyèl la ka manyen, lojisyèl la fè l fonksyone", "Biwo, pòtab oswa telefòn swiv menm prensip la", "Chak mo nouvo vle di swa yon pyès, swa yon pwogram"],
            en: ["A computer is a tool: it receives, processes and gives a result", "Hardware you touch, software makes it run", "Desktop, laptop or phone follow the same principle", "Each new word names either a part or a program"],
            es: ["La computadora es una herramienta: recibe, procesa y da un resultado", "El hardware se toca, el software lo hace funcionar", "Escritorio, portátil o teléfono siguen el mismo principio", "Cada palabra nueva designa o una pieza o un programa"],
          },
          exercise: {
            fr: "Devant ton ordinateur, montre du doigt et nomme à voix haute chaque partie que tu vois : l'écran, le clavier, la souris et l'unité centrale (ou le corps du portable). Puis dis si ton ordinateur est un modèle de bureau ou un modèle portable, et explique pourquoi. Enfin, cite un logiciel que tu connais déjà.",
            ht: "Devan òdinatè ou, montre ak dwèt ou epi rele awotvwa chak pati ou wè : ekran an, klavye a, sourit la ak inite santral la (oswa kò pòtab la). Apre di si òdinatè ou se yon modèl biwo oswa yon modèl pòtab, epi eksplike poukisa. Anfen, site yon lojisyèl ou deja konnen.",
            en: "In front of your computer, point to and say out loud each part you see: the screen, the keyboard, the mouse and the main unit (or the body of the laptop). Then say whether your computer is a desktop model or a laptop, and explain why. Finally, name one piece of software you already know.",
            es: "Frente a tu computadora, señala con el dedo y di en voz alta cada parte que ves: la pantalla, el teclado, el ratón y la unidad central (o el cuerpo de la portátil). Luego di si tu computadora es un modelo de escritorio o portátil, y explica por qué. Por último, nombra un software que ya conozcas.",
          },
        },
        {
          slug: "allumer-eteindre-bureau",
          title: { fr: "Allumer, éteindre et découvrir le bureau", ht: "Limen, etenn epi dekouvri biwo a", en: "Turning on, off and discovering the desktop", es: "Encender, apagar y descubrir el escritorio" },
          videoId: "",
          content: {
            fr: "Pour allumer un ordinateur, appuie une seule fois sur le bouton marqué du symbole rond avec un trait (⏻). Patiente quelques instants : la machine se prépare, c'est normal que cela prenne un peu de temps. Quand tout est prêt, un écran d'accueil apparaît, parfois avec un mot de passe à saisir.\n\nCet écran d'accueil s'appelle le « bureau ». C'est ta table de travail virtuelle. Tu y trouves des petites images appelées « icônes » : chacune ouvre un programme ou un dossier quand tu cliques dessus. En bas, une barre (la barre des tâches) affiche l'heure, le menu Démarrer et les fenêtres ouvertes.\n\nLe menu Démarrer, à gauche de la barre des tâches, est la porte d'entrée vers tous tes programmes. Clique dessus et une liste s'ouvre : tu y trouves les applications installées, un champ pour rechercher, et le bouton pour éteindre. C'est le point de départ de presque toutes tes actions.\n\nPour éteindre, ne coupe jamais le courant brutalement. Clique sur le menu Démarrer, puis sur « Arrêter ». La machine ferme proprement tous les programmes et s'éteint seule. Cette bonne habitude protège tes fichiers et prolonge la vie de l'ordinateur.",
            ht: "Pou limen yon òdinatè, peze yon sèl fwa sou bouton ki make ak senbòl won ak yon ti bwa a (⏻). Tann kèk moman : machin nan ap prepare, se nòmal pou sa pran yon ti tan. Lè tout bagay pare, yon ekran akèy parèt, pafwa ak yon modpas pou ou antre.\n\nEkran akèy sa a rele « biwo » a. Se tab travay vityèl ou. La ou jwenn ti imaj yo rele « ikòn » : chak louvri yon pwogram oswa yon dosye lè ou klike sou li. Anba, yon ba (ba tach yo) montre lè a, meni Demaraj la ak fenèt ki louvri yo.\n\nMeni Demaraj la, agoch ba tach yo, se pòt antre a vè tout pwogram ou yo. Klike sou li epi yon lis louvri : la ou jwenn aplikasyon ki enstale yo, yon espas pou fè rechèch, ak bouton pou etenn nan. Se pwen depa prèske tout aksyon ou yo.\n\nPou etenn, pa janm koupe kouran an brital. Klike sou meni Demaraj la, apre sou « Etenn ». Machin nan fèmen tout pwogram yo pwòpman epi li etenn pou kont li. Bon abitid sa a pwoteje fichye ou yo epi li fè òdinatè a dire pi lontan.",
            en: "To turn on a computer, press the button marked with the round symbol and a line (⏻) just once. Wait a few moments: the machine is getting ready, and it is normal for this to take a little time. When everything is ready, a welcome screen appears, sometimes asking for a password.\n\nThis welcome screen is called the \"desktop.\" It is your virtual worktable. On it you find small pictures called \"icons\": each one opens a program or a folder when you click on it. At the bottom, a bar (the taskbar) shows the time, the Start menu and the open windows.\n\nThe Start menu, on the left of the taskbar, is the doorway to all your programs. Click it and a list opens: you find the installed applications, a field to search, and the button to shut down. It is the starting point for almost all your actions.\n\nTo turn off, never cut the power abruptly. Click the Start menu, then \"Shut down.\" The machine closes all programs cleanly and turns itself off. This good habit protects your files and extends the life of the computer.",
            es: "Para encender una computadora, pulsa una sola vez el botón marcado con el símbolo redondo y una línea (⏻). Espera unos instantes: la máquina se está preparando, y es normal que tarde un poco. Cuando todo está listo, aparece una pantalla de bienvenida, a veces con una contraseña que escribir.\n\nEsta pantalla de bienvenida se llama el «escritorio». Es tu mesa de trabajo virtual. En ella encuentras pequeñas imágenes llamadas «iconos»: cada una abre un programa o una carpeta cuando haces clic. Abajo, una barra (la barra de tareas) muestra la hora, el menú Inicio y las ventanas abiertas.\n\nEl menú Inicio, a la izquierda de la barra de tareas, es la puerta de entrada a todos tus programas. Haz clic en él y se abre una lista: encuentras las aplicaciones instaladas, un campo para buscar, y el botón para apagar. Es el punto de partida de casi todas tus acciones.\n\nPara apagar, nunca cortes la corriente de golpe. Haz clic en el menú Inicio y luego en «Apagar». La máquina cierra todos los programas de forma limpia y se apaga sola. Este buen hábito protege tus archivos y alarga la vida de la computadora.",
          },
          keyPoints: {
            fr: ["Allumer : une seule pression sur le bouton ⏻, puis patienter", "Le bureau affiche les icônes et la barre des tâches", "Le menu Démarrer ouvre tous les programmes", "Toujours éteindre par le menu Démarrer → Arrêter"],
            ht: ["Limen : yon sèl presyon sou bouton ⏻ a, apre tann", "Biwo a montre ikòn yo ak ba tach yo", "Meni Demaraj la louvri tout pwogram yo", "Toujou etenn pa meni Demaraj → Etenn"],
            en: ["Turn on: one press of the ⏻ button, then wait", "The desktop shows icons and the taskbar", "The Start menu opens all programs", "Always shut down via Start menu → Shut down"],
            es: ["Encender: una sola pulsación del botón ⏻, luego esperar", "El escritorio muestra los iconos y la barra de tareas", "El menú Inicio abre todos los programas", "Apagar siempre por el menú Inicio → Apagar"],
          },
          exercise: {
            fr: "Allume ton ordinateur et attends que le bureau s'affiche. Compte les icônes présentes sur le bureau et lis à voix haute le nom de trois d'entre elles. Trouve l'heure affichée dans la barre des tâches en bas. Ouvre le menu Démarrer, regarde ce qu'il contient, puis referme-le. Enfin, éteins correctement l'ordinateur par Démarrer → Arrêter.",
            ht: "Limen òdinatè ou epi tann biwo a parèt. Konte ikòn ki sou biwo a epi li awotvwa non twa nan yo. Jwenn lè ki afiche nan ba tach yo anba a. Louvri meni Demaraj la, gade sa l genyen, apre refèmen l. Anfen, etenn òdinatè a kòrèkteman pa Demaraj → Etenn.",
            en: "Turn on your computer and wait for the desktop to appear. Count the icons on the desktop and read out loud the names of three of them. Find the time shown in the taskbar at the bottom. Open the Start menu, look at what it contains, then close it again. Finally, shut the computer down properly via Start → Shut down.",
            es: "Enciende tu computadora y espera a que aparezca el escritorio. Cuenta los iconos que hay en el escritorio y lee en voz alta el nombre de tres de ellos. Encuentra la hora que se muestra en la barra de tareas abajo. Abre el menú Inicio, mira lo que contiene, y luego ciérralo. Por último, apaga la computadora correctamente por Inicio → Apagar.",
          },
        },
        {
          slug: "les-fenetres-et-programmes",
          title: { fr: "Ouvrir, déplacer et fermer une fenêtre", ht: "Louvri, deplase epi fèmen yon fenèt", en: "Opening, moving and closing a window", es: "Abrir, mover y cerrar una ventana" },
          videoId: "",
          content: {
            fr: "Quand tu ouvres un programme, il s'affiche dans un rectangle appelé « fenêtre ». Tu peux avoir plusieurs fenêtres ouvertes en même temps, une par programme. Tout en haut de chaque fenêtre se trouve la « barre de titre », qui indique le nom du programme ouvert.\n\nEn haut à droite de chaque fenêtre se trouvent trois petits boutons. Le trait « – » réduit la fenêtre : elle disparaît dans la barre des tâches sans se fermer, et tu la retrouves d'un simple clic. Le carré agrandit la fenêtre pour qu'elle occupe tout l'écran, ou la remet à sa taille normale. La croix « × » ferme complètement le programme.\n\nPour déplacer une fenêtre, place le pointeur sur la barre de titre, maintiens le clic gauche enfoncé et fais glisser : la fenêtre suit la souris. Relâche à l'endroit voulu. Tu peux ainsi ranger deux fenêtres côte à côte pour comparer deux documents, ou dégager la vue.\n\nQuand plusieurs fenêtres sont ouvertes, une seule est « active », c'est-à-dire au premier plan. Pour passer de l'une à l'autre, clique sur son bouton dans la barre des tâches en bas, ou clique directement sur la partie visible de la fenêtre. Fermer les fenêtres inutiles garde l'écran clair et l'ordinateur plus rapide.",
            ht: "Lè ou louvri yon pwogram, li parèt nan yon rektang yo rele « fenèt ». Ou ka gen plizyè fenèt louvri an menm tan, youn pou chak pwogram. Anwo nèt chak fenèt gen « ba tit la », ki endike non pwogram ki louvri a.\n\nAnwo adwat chak fenèt gen twa ti bouton. Ti bwa « – » a redui fenèt la : li disparèt nan ba tach yo san li pa fèmen, epi ou jwenn li ak yon sèl klik. Kare a agrandi fenèt la pou l pran tout ekran an, oswa remete l nan gwosè nòmal li. Kwa « × » a fèmen pwogram nan nèt.\n\nPou deplase yon fenèt, mete pwentè a sou ba tit la, kenbe klik goch la peze epi fè l glise : fenèt la swiv sourit la. Lage l kote ou vle a. Konsa ou ka ranje de fenèt kòtakòt pou konpare de dokiman, oswa pou degaje vi a.\n\nLè plizyè fenèt louvri, se yon sèl ki « aktif », sa vle di ki nan premye plan an. Pou pase soti nan youn ale nan lòt, klike sou bouton li nan ba tach yo anba a, oswa klike dirèkteman sou pati vizib fenèt la. Fèmen fenèt ki initil yo kenbe ekran an klè epi òdinatè a pi rapid.",
            en: "When you open a program, it appears in a rectangle called a \"window.\" You can have several windows open at the same time, one per program. At the very top of each window is the \"title bar,\" which shows the name of the open program.\n\nAt the top right of each window are three small buttons. The line \"–\" minimizes the window: it disappears into the taskbar without closing, and you get it back with a single click. The square maximizes the window to fill the whole screen, or restores it to its normal size. The cross \"×\" closes the program completely.\n\nTo move a window, place the pointer on the title bar, hold the left click down and drag: the window follows the mouse. Release at the desired spot. This way you can place two windows side by side to compare two documents, or clear the view.\n\nWhen several windows are open, only one is \"active,\" meaning in the foreground. To switch from one to another, click its button in the taskbar at the bottom, or click directly on the visible part of the window. Closing unneeded windows keeps the screen clear and the computer faster.",
            es: "Cuando abres un programa, aparece en un rectángulo llamado «ventana». Puedes tener varias ventanas abiertas al mismo tiempo, una por programa. En la parte superior de cada ventana está la «barra de título», que indica el nombre del programa abierto.\n\nArriba a la derecha de cada ventana hay tres pequeños botones. La línea «–» minimiza la ventana: desaparece en la barra de tareas sin cerrarse, y la recuperas con un solo clic. El cuadrado maximiza la ventana para que ocupe toda la pantalla, o la devuelve a su tamaño normal. La cruz «×» cierra el programa por completo.\n\nPara mover una ventana, coloca el puntero sobre la barra de título, mantén pulsado el clic izquierdo y arrastra: la ventana sigue al ratón. Suelta en el lugar deseado. Así puedes colocar dos ventanas una al lado de otra para comparar dos documentos, o despejar la vista.\n\nCuando hay varias ventanas abiertas, solo una está «activa», es decir, en primer plano. Para pasar de una a otra, haz clic en su botón en la barra de tareas abajo, o haz clic directamente en la parte visible de la ventana. Cerrar las ventanas innecesarias mantiene la pantalla despejada y la computadora más rápida.",
          },
          keyPoints: {
            fr: ["Chaque programme s'ouvre dans une fenêtre avec une barre de titre", "Les trois boutons : réduire (–), agrandir (carré), fermer (×)", "On déplace une fenêtre en glissant sa barre de titre", "Une seule fenêtre est active ; on change par la barre des tâches"],
            ht: ["Chak pwogram louvri nan yon fenèt ak yon ba tit", "Twa bouton yo : redui (–), agrandi (kare), fèmen (×)", "Ou deplase yon fenèt lè w glise ba tit li", "Yon sèl fenèt aktif ; ou chanje pa ba tach yo"],
            en: ["Each program opens in a window with a title bar", "The three buttons: minimize (–), maximize (square), close (×)", "You move a window by dragging its title bar", "Only one window is active; switch via the taskbar"],
            es: ["Cada programa se abre en una ventana con barra de título", "Los tres botones: minimizar (–), maximizar (cuadrado), cerrar (×)", "Se mueve una ventana arrastrando su barra de título", "Solo una ventana está activa; se cambia por la barra de tareas"],
          },
          exercise: {
            fr: "Ouvre un programme depuis le menu Démarrer (par exemple la calculatrice ou le bloc-notes). Clique sur le bouton réduire (–) et retrouve la fenêtre dans la barre des tâches. Agrandis-la, puis remets-la à sa taille normale. Attrape sa barre de titre et déplace la fenêtre dans un coin de l'écran. Enfin, ferme le programme avec la croix (×).",
            ht: "Louvri yon pwogram depi meni Demaraj la (pa egzanp kalkilatris la oswa blòk-nòt la). Klike sou bouton redui (–) a epi jwenn fenèt la nan ba tach yo. Agrandi l, apre remete l nan gwosè nòmal li. Kenbe ba tit li epi deplase fenèt la nan yon kwen ekran an. Anfen, fèmen pwogram nan ak kwa (×) a.",
            en: "Open a program from the Start menu (for example the calculator or notepad). Click the minimize button (–) and find the window again in the taskbar. Maximize it, then restore it to its normal size. Grab its title bar and move the window to a corner of the screen. Finally, close the program with the cross (×).",
            es: "Abre un programa desde el menú Inicio (por ejemplo la calculadora o el bloc de notas). Haz clic en el botón minimizar (–) y encuentra la ventana de nuevo en la barra de tareas. Maximízala, luego devuélvela a su tamaño normal. Agarra su barra de título y mueve la ventana a una esquina de la pantalla. Por último, cierra el programa con la cruz (×).",
          },
        },
      ],
    },
    {
      title: { fr: "La souris et le clavier", ht: "Sourit la ak klavye a", en: "The mouse and the keyboard", es: "El ratón y el teclado" },
      lessons: [
        {
          slug: "utiliser-la-souris",
          title: { fr: "Bien utiliser la souris", ht: "Byen sèvi ak sourit la", en: "Using the mouse well", es: "Usar bien el ratón" },
          videoId: "",
          content: {
            fr: "La souris déplace une petite flèche à l'écran appelée « pointeur » ou « curseur ». Pose la main dessus sans serrer, glisse-la sur la table, et le pointeur suit tes mouvements. Si tu manques de place, soulève la souris et repose-la plus loin : le pointeur ne bouge pas pendant ce temps.\n\nLa souris a deux boutons principaux. Le clic gauche est le plus utilisé : il sert à sélectionner et à ouvrir. Un seul clic sélectionne un élément, un double-clic rapide (deux clics de suite) ouvre un dossier ou un programme. Le clic droit ouvre un petit menu d'options, utile pour copier, coller ou supprimer.\n\nEntre les deux boutons se trouve souvent une petite roue : elle sert à faire défiler la page vers le haut ou le bas, par exemple pour lire un long texte. Fais tourner la roue vers l'avant pour monter, vers toi pour descendre.\n\nSur un ordinateur portable, la souris est souvent remplacée par un « pavé tactile » (touchpad) : une surface lisse sur laquelle on glisse le doigt pour déplacer le pointeur. Un appui bref remplace le clic gauche. Entraîne-toi à viser une icône et à cliquer : avec quelques minutes de pratique, le geste devient naturel.",
            ht: "Sourit la deplase yon ti flèch sou ekran an yo rele « pwentè » oswa « kisè ». Mete men w sou li san w pa sere, glise l sou tab la, epi pwentè a swiv mouvman ou. Si w manke plas, leve sourit la epi remete l pi lwen : pwentè a p ap bouje pandan tan sa a.\n\nSourit la gen de bouton prensipal. Klik goch la se sa yo plis itilize : li sèvi pou seleksyone ak louvri. Yon sèl klik seleksyone yon eleman, yon doub-klik rapid (de klik youn dèyè lòt) louvri yon dosye oswa yon pwogram. Klik dwat la louvri yon ti meni opsyon, itil pou kopye, kole oswa efase.\n\nAnt de bouton yo souvan gen yon ti wou : li sèvi pou fè paj la desann oswa monte, pa egzanp pou li yon long tèks. Fè wou a vire pa devan pou monte, vè ou pou desann.\n\nSou yon òdinatè pòtab, sourit la souvan ranplase pa yon « paviyon taktil » (touchpad) : yon sifas lis kote ou glise dwèt ou pou deplase pwentè a. Yon ti tape ranplase klik goch la. Antrene w vize yon ikòn epi klike : ak kèk minit pratik, jès la vin natirèl.",
            en: "The mouse moves a small arrow on the screen called the \"pointer\" or \"cursor.\" Rest your hand on it without gripping, slide it across the table, and the pointer follows your movements. If you run out of room, lift the mouse and set it down farther away: the pointer does not move during that time.\n\nThe mouse has two main buttons. The left click is used most: it serves to select and to open. A single click selects an item, a quick double-click (two clicks in a row) opens a folder or a program. The right click opens a small menu of options, handy for copying, pasting or deleting.\n\nBetween the two buttons there is often a small wheel: it is used to scroll the page up or down, for example to read a long text. Roll the wheel forward to go up, toward you to go down.\n\nOn a laptop, the mouse is often replaced by a \"touchpad\": a smooth surface on which you slide your finger to move the pointer. A brief tap replaces the left click. Practice aiming at an icon and clicking: with a few minutes of practice, the gesture becomes natural.",
            es: "El ratón mueve una pequeña flecha en la pantalla llamada «puntero» o «cursor». Apoya la mano encima sin apretar, deslízalo sobre la mesa, y el puntero sigue tus movimientos. Si te quedas sin espacio, levanta el ratón y colócalo más lejos: el puntero no se mueve durante ese tiempo.\n\nEl ratón tiene dos botones principales. El clic izquierdo es el más usado: sirve para seleccionar y abrir. Un solo clic selecciona un elemento, un doble clic rápido (dos clics seguidos) abre una carpeta o un programa. El clic derecho abre un pequeño menú de opciones, útil para copiar, pegar o eliminar.\n\nEntre los dos botones suele haber una pequeña rueda: sirve para desplazar la página hacia arriba o hacia abajo, por ejemplo para leer un texto largo. Gira la rueda hacia adelante para subir, hacia ti para bajar.\n\nEn una computadora portátil, el ratón suele estar reemplazado por un «panel táctil» (touchpad): una superficie lisa sobre la que deslizas el dedo para mover el puntero. Un toque breve reemplaza al clic izquierdo. Practica apuntar a un icono y hacer clic: con unos minutos de práctica, el gesto se vuelve natural.",
          },
          keyPoints: {
            fr: ["Clic gauche : sélectionner (1 clic) ou ouvrir (double-clic)", "Clic droit : ouvrir le menu d'options", "La roue centrale fait défiler la page", "Sur portable, le pavé tactile remplace la souris"],
            ht: ["Klik goch : seleksyone (1 klik) oswa louvri (doub-klik)", "Klik dwat : louvri meni opsyon yo", "Wou santral la fè paj la defile", "Sou pòtab, paviyon taktil la ranplase sourit la"],
            en: ["Left click: select (1 click) or open (double-click)", "Right click: open the options menu", "The center wheel scrolls the page", "On a laptop, the touchpad replaces the mouse"],
            es: ["Clic izquierdo: seleccionar (1 clic) o abrir (doble clic)", "Clic derecho: abrir el menú de opciones", "La rueda central desplaza la página", "En portátil, el panel táctil reemplaza al ratón"],
          },
          exercise: {
            fr: "Sur le bureau, fais un seul clic gauche sur une icône : elle se colore, elle est sélectionnée. Fais ensuite un double-clic rapide pour l'ouvrir, puis referme la fenêtre. Fais un clic droit dans une zone vide du bureau et observe le menu qui apparaît, puis referme-le en cliquant ailleurs. Enfin, ouvre une longue page et utilise la roue pour la faire défiler de haut en bas.",
            ht: "Sou biwo a, fè yon sèl klik goch sou yon ikòn : li vin kolore, li seleksyone. Apre fè yon doub-klik rapid pou louvri l, epi refèmen fenèt la. Fè yon klik dwat nan yon zòn vid sou biwo a epi obsève meni ki parèt la, apre refèmen l lè w klike yon lòt kote. Anfen, louvri yon long paj epi itilize wou a pou fè l defile soti anwo desann anba.",
            en: "On the desktop, make a single left click on an icon: it changes color, it is selected. Then make a quick double-click to open it, and close the window again. Make a right click in an empty area of the desktop and watch the menu that appears, then close it by clicking elsewhere. Finally, open a long page and use the wheel to scroll it up and down.",
            es: "En el escritorio, haz un solo clic izquierdo sobre un icono: cambia de color, está seleccionado. Luego haz un doble clic rápido para abrirlo, y cierra la ventana. Haz un clic derecho en una zona vacía del escritorio y observa el menú que aparece, luego ciérralo haciendo clic en otro lugar. Por último, abre una página larga y usa la rueda para desplazarla de arriba abajo.",
          },
        },
        {
          slug: "ecrire-avec-le-clavier",
          title: { fr: "Écrire avec le clavier", ht: "Ekri ak klavye a", en: "Writing with the keyboard", es: "Escribir con el teclado" },
          videoId: "",
          content: {
            fr: "Le clavier sert à écrire. Chaque touche porte une lettre, un chiffre ou un symbole. Pour taper une lettre, appuie doucement puis relâche : inutile d'appuyer fort. La grande touche du bas, la barre d'espace, ajoute un espace entre les mots.\n\nQuelques touches sont très utiles à connaître. La touche « Maj » (ou « Shift », marquée d'une flèche vers le haut), maintenue en même temps qu'une lettre, écrit une majuscule. La touche « Entrée » va à la ligne suivante. La touche « Retour arrière » (« Backspace ») efface la lettre située juste avant le curseur, pratique pour corriger une faute.\n\nD'autres touches rendent service. La touche « Verr. Maj » (Caps Lock) bloque les majuscules jusqu'à ce que tu la désactives. La touche « Suppr » (Delete) efface la lettre située après le curseur. Les chiffres se trouvent en haut du clavier et parfois aussi sur un pavé à droite.\n\nLe curseur clignotant indique où le texte va s'écrire. Tu peux le déplacer en cliquant à l'endroit voulu avec la souris, ou avec les touches fléchées. Prends ton temps : au début on cherche les lettres une par une, puis la vitesse vient naturellement avec la pratique.",
            ht: "Klavye a sèvi pou ekri. Chak touch pote yon lèt, yon chif oswa yon senbòl. Pou tape yon lèt, peze dousman epi lage : ou pa bezwen peze fò. Gwo touch anba a, ba espas la, ajoute yon espas ant mo yo.\n\nGen kèk touch ki trè itil pou konnen. Touch « Maj » (oswa « Shift », ki make ak yon flèch anlè), lè w kenbe l ansanm ak yon lèt, ekri yon majiskil. Touch « Antre » (« Enter ») ale nan liy ki vin apre a. Touch « Retou aryè » (« Backspace ») efase lèt ki jis anvan kisè a, itil pou korije yon fot.\n\nGen lòt touch ki rann sèvis. Touch « Verr. Maj » (Caps Lock) bloke majiskil yo jouk ou dezaktive l. Touch « Suppr » (Delete) efase lèt ki apre kisè a. Chif yo jwenn anwo klavye a epi pafwa tou sou yon paviyon adwat.\n\nKisè k ap klete a montre kote tèks la pral ekri. Ou ka deplase l lè w klike kote ou vle a ak sourit la, oswa ak touch flèch yo. Pran tan ou : nan kòmansman ou chèche lèt yo youn pa youn, apre vitès la vini natirèlman ak pratik.",
            en: "The keyboard is for writing. Each key carries a letter, a number or a symbol. To type a letter, press gently and release: there is no need to press hard. The large key at the bottom, the space bar, adds a space between words.\n\nA few keys are very useful to know. The \"Shift\" key (marked with an upward arrow), held at the same time as a letter, types a capital letter. The \"Enter\" key moves to the next line. The \"Backspace\" key erases the letter just before the cursor, handy for fixing a mistake.\n\nOther keys are helpful. The \"Caps Lock\" key locks capital letters until you turn it off. The \"Delete\" key erases the letter located after the cursor. The numbers are at the top of the keyboard and sometimes also on a pad on the right.\n\nThe blinking cursor shows where the text will be written. You can move it by clicking at the desired spot with the mouse, or with the arrow keys. Take your time: at first you look for the letters one by one, then speed comes naturally with practice.",
            es: "El teclado sirve para escribir. Cada tecla lleva una letra, un número o un símbolo. Para escribir una letra, pulsa suavemente y suelta: no hace falta apretar fuerte. La tecla grande de abajo, la barra espaciadora, añade un espacio entre las palabras.\n\nAlgunas teclas son muy útiles de conocer. La tecla «Mayús» (o «Shift», marcada con una flecha hacia arriba), mantenida junto con una letra, escribe una mayúscula. La tecla «Enter» pasa a la línea siguiente. La tecla «Retroceso» («Backspace») borra la letra situada justo antes del cursor, práctica para corregir un error.\n\nOtras teclas son de ayuda. La tecla «Bloq Mayús» (Caps Lock) bloquea las mayúsculas hasta que la desactivas. La tecla «Supr» (Delete) borra la letra situada después del cursor. Los números están en la parte superior del teclado y a veces también en un teclado numérico a la derecha.\n\nEl cursor parpadeante indica dónde se escribirá el texto. Puedes moverlo haciendo clic en el lugar deseado con el ratón, o con las teclas de flecha. Tómate tu tiempo: al principio buscas las letras una por una, y luego la velocidad llega naturalmente con la práctica.",
          },
          keyPoints: {
            fr: ["Maj (Shift) + lettre = majuscule ; barre d'espace = espace", "Entrée va à la ligne, Retour arrière efface avant le curseur", "Suppr efface après le curseur ; Verr. Maj bloque les majuscules", "Le curseur clignotant montre où le texte s'écrit"],
            ht: ["Maj (Shift) + lèt = majiskil ; ba espas = espas", "Antre ale nan liy, Retou aryè efase anvan kisè a", "Suppr efase apre kisè a ; Verr. Maj bloke majiskil yo", "Kisè k ap klete a montre kote tèks la ekri"],
            en: ["Shift + letter = capital; space bar = space", "Enter goes to a new line, Backspace erases before the cursor", "Delete erases after the cursor; Caps Lock locks capitals", "The blinking cursor shows where text is written"],
            es: ["Mayús (Shift) + letra = mayúscula; barra espaciadora = espacio", "Enter va a la línea, Retroceso borra antes del cursor", "Supr borra después del cursor; Bloq Mayús bloquea mayúsculas", "El cursor parpadeante muestra dónde se escribe el texto"],
          },
          exercise: {
            fr: "Ouvre le bloc-notes (Notepad) depuis le menu Démarrer. Tape ton prénom en commençant par une majuscule (Maj + première lettre). Ajoute un espace, puis écris ton nom de famille. Appuie sur Entrée pour aller à la ligne et écris une courte phrase. Enfin, sers-toi de la touche Retour arrière pour effacer un mot et le réécrire correctement.",
            ht: "Louvri blòk-nòt (Notepad) depi meni Demaraj la. Tape prenon ou an kòmanse ak yon majiskil (Maj + premye lèt). Ajoute yon espas, apre ekri siyati ou. Peze Antre pou ale nan liy epi ekri yon ti fraz. Anfen, sèvi ak touch Retou aryè pou efase yon mo epi reekri l kòrèkteman.",
            en: "Open Notepad from the Start menu. Type your first name starting with a capital letter (Shift + first letter). Add a space, then write your last name. Press Enter to go to a new line and write a short sentence. Finally, use the Backspace key to erase a word and rewrite it correctly.",
            es: "Abre el Bloc de notas (Notepad) desde el menú Inicio. Escribe tu nombre empezando por una mayúscula (Mayús + primera letra). Añade un espacio, luego escribe tu apellido. Pulsa Enter para ir a la línea siguiente y escribe una frase corta. Por último, usa la tecla Retroceso para borrar una palabra y volver a escribirla correctamente.",
          },
        },
        {
          slug: "selectionner-copier-coller-texte",
          title: { fr: "Sélectionner, copier et coller un texte", ht: "Seleksyone, kopye epi kole yon tèks", en: "Selecting, copying and pasting text", es: "Seleccionar, copiar y pegar texto" },
          videoId: "",
          content: {
            fr: "Copier, couper et coller sont trois gestes qui font gagner un temps précieux. « Copier » prend une copie d'un élément (un mot, une phrase, une image) sans toucher à l'original. « Coller » dépose cette copie ailleurs. « Couper » déplace l'élément : il disparaît de son point de départ pour réapparaître là où tu colles.\n\nPour copier un texte, il faut d'abord le sélectionner. Place le curseur juste avant le premier mot, maintiens le clic gauche enfoncé et glisse jusqu'à la fin du passage : le texte se surligne en bleu. Relâche. Le texte surligné est maintenant sélectionné.\n\nEnsuite, fais un clic droit sur la zone bleue et choisis « Copier » (ou « Couper »). Place le curseur à l'endroit où tu veux déposer le texte, fais de nouveau un clic droit et choisis « Coller ». Le texte apparaît. Tu peux le coller autant de fois que tu veux.\n\nIl existe des raccourcis clavier plus rapides, communs à presque tous les programmes : Ctrl + C pour copier, Ctrl + X pour couper, et Ctrl + V pour coller. On maintient la touche Ctrl enfoncée puis on appuie brièvement sur l'autre lettre. Ces mêmes gestes fonctionnent aussi pour copier des fichiers d'un dossier à un autre.",
            ht: "Kopye, koupe ak kole se twa jès ki fè w genyen anpil tan. « Kopye » pran yon kopi yon eleman (yon mo, yon fraz, yon imaj) san li pa touche orijinal la. « Kole » depoze kopi sa a yon lòt kote. « Koupe » deplase eleman an : li disparèt kote l te ye a pou l reparèt kote ou kole a.\n\nPou kopye yon tèks, fòk ou seleksyone l anvan. Mete kisè a jis anvan premye mo a, kenbe klik goch la peze epi glise jouk nan fen pasaj la : tèks la vin sou-liyen ble. Lage. Tèks sou-liyen an seleksyone kounye a.\n\nApre sa, fè yon klik dwat sou zòn ble a epi chwazi « Kopye » (oswa « Koupe »). Mete kisè a kote ou vle depoze tèks la, fè yon lòt klik dwat epi chwazi « Kole ». Tèks la parèt. Ou ka kole l otan fwa ou vle.\n\nGen rakoursi klavye ki pi rapid, ki menm nan prèske tout pwogram yo : Ctrl + C pou kopye, Ctrl + X pou koupe, ak Ctrl + V pou kole. Ou kenbe touch Ctrl la peze apre ou peze lòt lèt la yon ti moman. Menm jès sa yo fonksyone tou pou kopye fichye soti nan yon dosye ale nan yon lòt.",
            en: "Copy, cut and paste are three actions that save precious time. \"Copy\" takes a copy of an item (a word, a sentence, an image) without touching the original. \"Paste\" places that copy elsewhere. \"Cut\" moves the item: it disappears from its starting point to reappear where you paste.\n\nTo copy text, you must first select it. Place the cursor just before the first word, hold the left click down and drag to the end of the passage: the text highlights in blue. Release. The highlighted text is now selected.\n\nThen right-click on the blue area and choose \"Copy\" (or \"Cut\"). Place the cursor where you want to drop the text, right-click again and choose \"Paste.\" The text appears. You can paste it as many times as you like.\n\nThere are faster keyboard shortcuts, common to almost all programs: Ctrl + C to copy, Ctrl + X to cut, and Ctrl + V to paste. You hold the Ctrl key down then briefly press the other letter. These same actions also work to copy files from one folder to another.",
            es: "Copiar, cortar y pegar son tres gestos que ahorran un tiempo valioso. «Copiar» toma una copia de un elemento (una palabra, una frase, una imagen) sin tocar el original. «Pegar» coloca esa copia en otro lugar. «Cortar» mueve el elemento: desaparece de su punto de partida para reaparecer donde pegas.\n\nPara copiar un texto, primero hay que seleccionarlo. Coloca el cursor justo antes de la primera palabra, mantén pulsado el clic izquierdo y arrastra hasta el final del pasaje: el texto se resalta en azul. Suelta. El texto resaltado está ahora seleccionado.\n\nLuego haz clic derecho sobre la zona azul y elige «Copiar» (o «Cortar»). Coloca el cursor donde quieras dejar el texto, haz clic derecho de nuevo y elige «Pegar». El texto aparece. Puedes pegarlo tantas veces como quieras.\n\nExisten atajos de teclado más rápidos, comunes a casi todos los programas: Ctrl + C para copiar, Ctrl + X para cortar, y Ctrl + V para pegar. Mantienes pulsada la tecla Ctrl y luego pulsas brevemente la otra letra. Estos mismos gestos también funcionan para copiar archivos de una carpeta a otra.",
          },
          keyPoints: {
            fr: ["Sélectionner : glisser le clic gauche pour surligner en bleu", "Copier garde l'original, couper le déplace, coller le dépose", "Clic droit → Copier / Couper / Coller", "Raccourcis : Ctrl+C copier, Ctrl+X couper, Ctrl+V coller"],
            ht: ["Seleksyone : glise klik goch la pou sou-liyen an ble", "Kopye kenbe orijinal la, koupe deplase l, kole depoze l", "Klik dwat → Kopye / Koupe / Kole", "Rakoursi : Ctrl+C kopye, Ctrl+X koupe, Ctrl+V kole"],
            en: ["Select: drag the left click to highlight in blue", "Copy keeps the original, cut moves it, paste drops it", "Right-click → Copy / Cut / Paste", "Shortcuts: Ctrl+C copy, Ctrl+X cut, Ctrl+V paste"],
            es: ["Seleccionar: arrastrar el clic izquierdo para resaltar en azul", "Copiar conserva el original, cortar lo mueve, pegar lo coloca", "Clic derecho → Copiar / Cortar / Pegar", "Atajos: Ctrl+C copiar, Ctrl+X cortar, Ctrl+V pegar"],
          },
          exercise: {
            fr: "Dans le bloc-notes, écris la phrase « J'apprends l'informatique ». Sélectionne-la en glissant le clic gauche du début à la fin, jusqu'à ce qu'elle soit surlignée en bleu. Copie-la avec Ctrl + C. Va à la ligne avec Entrée, puis colle-la trois fois de suite avec Ctrl + V. Tu dois maintenant voir la phrase répétée trois fois.",
            ht: "Nan blòk-nòt la, ekri fraz « M ap aprann enfòmatik ». Seleksyone l lè w glise klik goch la depi kòmansman jouk nan fen, jouk li sou-liyen an ble. Kopye l ak Ctrl + C. Ale nan liy ak Antre, apre kole l twa fwa youn dèyè lòt ak Ctrl + V. Kounye a ou dwe wè fraz la repete twa fwa.",
            en: "In Notepad, write the sentence \"I am learning computing.\" Select it by dragging the left click from start to end, until it is highlighted in blue. Copy it with Ctrl + C. Go to a new line with Enter, then paste it three times in a row with Ctrl + V. You should now see the sentence repeated three times.",
            es: "En el Bloc de notas, escribe la frase «Estoy aprendiendo informática». Selecciónala arrastrando el clic izquierdo del principio al final, hasta que quede resaltada en azul. Cópiala con Ctrl + C. Ve a una nueva línea con Enter, luego pégala tres veces seguidas con Ctrl + V. Ahora debes ver la frase repetida tres veces.",
          },
        },
      ],
    },
    {
      title: { fr: "Fichiers et dossiers", ht: "Fichye ak dosye", en: "Files and folders", es: "Archivos y carpetas" },
      lessons: [
        {
          slug: "comprendre-fichiers-dossiers",
          title: { fr: "Comprendre fichiers et dossiers", ht: "Konprann fichye ak dosye", en: "Understanding files and folders", es: "Comprender archivos y carpetas" },
          videoId: "",
          content: {
            fr: "Un fichier est un document enregistré dans l'ordinateur : une lettre écrite, une photo, une chanson ou une vidéo est chacun un fichier. Chaque fichier porte un nom (par exemple « facture ») et une extension qui indique son type (« .pdf », « .jpg », « .docx »). Le nom t'aide à le retrouver, l'extension dit à l'ordinateur avec quel programme l'ouvrir.\n\nUn dossier est comme une chemise en carton : il sert à ranger plusieurs fichiers ensemble. Tu peux mettre un dossier à l'intérieur d'un autre dossier, comme des boîtes rangées les unes dans les autres. Cela crée une organisation en arbre, du dossier général vers les sous-dossiers.\n\nPour voir tes fichiers et dossiers, on ouvre l'« explorateur de fichiers », représenté par une icône de dossier jaune dans la barre des tâches. À gauche, une liste montre les grands emplacements : Bureau, Documents, Images, Téléchargements. Clique sur l'un d'eux pour voir ce qu'il contient.\n\nBien ranger ses fichiers dans des dossiers clairs (par exemple « Photos famille », « Papiers importants ») fait gagner beaucoup de temps. Un ordinateur bien organisé est un ordinateur où l'on retrouve tout en quelques secondes.",
            ht: "Yon fichye se yon dokiman ki anrejistre nan òdinatè a : yon lèt ou ekri, yon foto, yon chante oswa yon videyo se chak yon fichye. Chak fichye pote yon non (pa egzanp « fakti ») ak yon ekstansyon ki endike tip li (« .pdf », « .jpg », « .docx »). Non an ede w jwenn li, ekstansyon an di òdinatè a ak ki pwogram pou louvri l.\n\nYon dosye se tankou yon chemiz katon : li sèvi pou ranje plizyè fichye ansanm. Ou ka mete yon dosye anndan yon lòt dosye, tankou bwat yo ranje youn nan lòt. Sa kreye yon òganizasyon an pyebwa, soti nan dosye jeneral la desann nan sou-dosye yo.\n\nPou wè fichye ak dosye ou yo, ou louvri « esplorate fichye a », ki reprezante pa yon ikòn dosye jòn nan ba tach yo. Agoch, yon lis montre gwo kote yo : Biwo, Dokiman, Imaj, Telechajman. Klike sou youn ladan yo pou wè sa l genyen.\n\nByen ranje fichye yo nan dosye klè (pa egzanp « Foto fanmi », « Papye enpòtan ») fè w genyen anpil tan. Yon òdinatè byen òganize se yon òdinatè kote ou jwenn tout bagay nan kèk segonn.",
            en: "A file is a document saved on the computer: a written letter, a photo, a song or a video is each a file. Every file has a name (for example \"invoice\") and an extension that shows its type (\".pdf\", \".jpg\", \".docx\"). The name helps you find it, the extension tells the computer which program to open it with.\n\nA folder is like a cardboard file: it is used to store several files together. You can put a folder inside another folder, like boxes arranged one inside the other. This creates a tree-like organization, from the general folder down to the subfolders.\n\nTo see your files and folders, you open the \"file explorer,\" shown by a yellow folder icon in the taskbar. On the left, a list shows the main locations: Desktop, Documents, Pictures, Downloads. Click one of them to see what it contains.\n\nStoring your files well in clear folders (for example \"Family photos\", \"Important papers\") saves a lot of time. A well-organized computer is one where everything is found in a few seconds.",
            es: "Un archivo es un documento guardado en la computadora: una carta escrita, una foto, una canción o un video es cada uno un archivo. Cada archivo tiene un nombre (por ejemplo «factura») y una extensión que indica su tipo («.pdf», «.jpg», «.docx»). El nombre te ayuda a encontrarlo, la extensión le dice a la computadora con qué programa abrirlo.\n\nUna carpeta es como una carpeta de cartón: sirve para guardar varios archivos juntos. Puedes poner una carpeta dentro de otra carpeta, como cajas ordenadas unas dentro de otras. Esto crea una organización en forma de árbol, desde la carpeta general hasta las subcarpetas.\n\nPara ver tus archivos y carpetas, se abre el «explorador de archivos», representado por un icono de carpeta amarilla en la barra de tareas. A la izquierda, una lista muestra las ubicaciones principales: Escritorio, Documentos, Imágenes, Descargas. Haz clic en una de ellas para ver lo que contiene.\n\nOrdenar bien los archivos en carpetas claras (por ejemplo «Fotos familia», «Papeles importantes») ahorra mucho tiempo. Una computadora bien organizada es aquella donde se encuentra todo en pocos segundos.",
          },
          keyPoints: {
            fr: ["Un fichier = un document (photo, texte, vidéo…) avec nom + extension", "Un dossier range plusieurs fichiers ensemble", "L'explorateur de fichiers montre tous tes dossiers", "Des dossiers clairs = tout se retrouve vite"],
            ht: ["Yon fichye = yon dokiman (foto, tèks, videyo…) ak non + ekstansyon", "Yon dosye ranje plizyè fichye ansanm", "Esplorate fichye a montre tout dosye ou yo", "Dosye klè = tout bagay jwenn vit"],
            en: ["A file = a document (photo, text, video…) with name + extension", "A folder stores several files together", "The file explorer shows all your folders", "Clear folders = everything is found quickly"],
            es: ["Un archivo = un documento (foto, texto, video…) con nombre + extensión", "Una carpeta guarda varios archivos juntos", "El explorador de archivos muestra todas tus carpetas", "Carpetas claras = todo se encuentra rápido"],
          },
          exercise: {
            fr: "Ouvre l'explorateur de fichiers (icône de dossier jaune dans la barre des tâches). Clique sur « Documents » à gauche, puis sur « Images ». Choisis un fichier et lis à voix haute son nom complet, puis son extension (les lettres après le point). Dis à quel type il correspond : photo, texte, vidéo ou musique.",
            ht: "Louvri esplorate fichye a (ikòn dosye jòn nan ba tach yo). Klike sou « Dokiman » agoch, apre sou « Imaj ». Chwazi yon fichye epi li awotvwa non konplè li, apre ekstansyon li (lèt yo apre pwen an). Di ki tip li ye : foto, tèks, videyo oswa mizik.",
            en: "Open the file explorer (yellow folder icon in the taskbar). Click \"Documents\" on the left, then \"Pictures.\" Choose a file and read out loud its full name, then its extension (the letters after the dot). Say which type it is: photo, text, video or music.",
            es: "Abre el explorador de archivos (icono de carpeta amarilla en la barra de tareas). Haz clic en «Documentos» a la izquierda, luego en «Imágenes». Elige un archivo y lee en voz alta su nombre completo, luego su extensión (las letras después del punto). Di a qué tipo corresponde: foto, texto, video o música.",
          },
        },
        {
          slug: "creer-ranger-enregistrer",
          title: { fr: "Créer, ranger et enregistrer", ht: "Kreye, ranje epi anrejistre", en: "Create, organize and save", es: "Crear, ordenar y guardar" },
          videoId: "",
          content: {
            fr: "Pour créer un nouveau dossier, ouvre l'explorateur de fichiers, choisis l'endroit voulu, fais un clic droit dans une zone vide, puis clique sur « Nouveau » et « Dossier ». Un dossier apparaît : tape tout de suite un nom clair, puis appuie sur Entrée. Tu peux désormais y glisser des fichiers.\n\nPour déplacer un fichier dans un dossier, tu peux le « glisser-déposer » : clique dessus sans relâcher, fais-le glisser jusqu'au dossier, puis relâche le bouton. Autre méthode plus sûre : clic droit sur le fichier, « Couper », puis clic droit dans le dossier de destination et « Coller ». « Copier » garde l'original et en fait un double.\n\nQuand tu travailles dans un programme (traitement de texte, par exemple), pense à enregistrer souvent avec « Fichier » puis « Enregistrer ». Choisis un nom et un dossier faciles à retrouver. Sans enregistrement, ton travail est perdu si l'ordinateur s'éteint.\n\nLa première fois, le programme demande « Enregistrer sous » : tu choisis le dossier et le nom. Ensuite, un simple « Enregistrer » (ou le raccourci Ctrl + S) garde la version à jour au même endroit. Enregistrer régulièrement est le meilleur réflexe du débutant.",
            ht: "Pou kreye yon nouvo dosye, louvri esplorate fichye a, chwazi kote ou vle a, fè yon klik dwat nan yon zòn vid, apre klike sou « Nouvo » ak « Dosye ». Yon dosye parèt : tape tousuit yon non klè, apre peze Antre. Kounye a ou ka glise fichye ladan l.\n\nPou deplase yon fichye nan yon dosye, ou ka fè « glise-depoze » : klike sou li san w pa lage, fè l glise jouk nan dosye a, apre lage bouton an. Yon lòt metòd ki pi si : klik dwat sou fichye a, « Koupe », apre klik dwat nan dosye destinasyon an epi « Kole ». « Kopye » kenbe orijinal la epi fè yon doub.\n\nLè w ap travay nan yon pwogram (pwogram pou ekri tèks, pa egzanp), sonje anrejistre souvan ak « Fichye » apre « Anrejistre ». Chwazi yon non ak yon dosye ki fasil pou jwenn. San anrejistreman, travay ou pèdi si òdinatè a etenn.\n\nPremye fwa a, pwogram nan mande « Anrejistre sou » : ou chwazi dosye a ak non an. Apre sa, yon senp « Anrejistre » (oswa rakoursi Ctrl + S) kenbe vèsyon ki ajou a nan menm kote a. Anrejistre regilyèman se pi bon refleks debitan an.",
            en: "To create a new folder, open the file explorer, choose the desired place, right-click in an empty area, then click \"New\" and \"Folder.\" A folder appears: type a clear name right away, then press Enter. You can now drag files into it.\n\nTo move a file into a folder, you can \"drag and drop\" it: click on it without releasing, drag it to the folder, then release the button. Another safer method: right-click the file, \"Cut,\" then right-click in the destination folder and \"Paste.\" \"Copy\" keeps the original and makes a duplicate.\n\nWhen you work in a program (a word processor, for example), remember to save often with \"File\" then \"Save.\" Choose a name and a folder that are easy to find. Without saving, your work is lost if the computer shuts off.\n\nThe first time, the program asks \"Save as\": you choose the folder and the name. After that, a simple \"Save\" (or the shortcut Ctrl + S) keeps the up-to-date version in the same place. Saving regularly is the beginner's best habit.",
            es: "Para crear una nueva carpeta, abre el explorador de archivos, elige el lugar deseado, haz clic derecho en una zona vacía, luego haz clic en «Nuevo» y «Carpeta». Aparece una carpeta: escribe enseguida un nombre claro y luego pulsa Enter. Ahora puedes arrastrar archivos a ella.\n\nPara mover un archivo a una carpeta, puedes «arrastrar y soltar»: haz clic sin soltar, arrástralo hasta la carpeta y luego suelta el botón. Otro método más seguro: clic derecho en el archivo, «Cortar», luego clic derecho en la carpeta de destino y «Pegar». «Copiar» conserva el original y hace un duplicado.\n\nCuando trabajas en un programa (un procesador de textos, por ejemplo), recuerda guardar a menudo con «Archivo» y luego «Guardar». Elige un nombre y una carpeta fáciles de encontrar. Sin guardar, tu trabajo se pierde si la computadora se apaga.\n\nLa primera vez, el programa pide «Guardar como»: eliges la carpeta y el nombre. Después, un simple «Guardar» (o el atajo Ctrl + S) mantiene la versión actualizada en el mismo lugar. Guardar con regularidad es el mejor reflejo del principiante.",
          },
          keyPoints: {
            fr: ["Clic droit → Nouveau → Dossier pour créer un dossier nommé", "Glisser-déposer ou Couper/Coller pour déplacer un fichier", "La première fois : « Enregistrer sous » (choisir nom + dossier)", "Enregistrer souvent (Ctrl + S) évite de tout perdre"],
            ht: ["Klik dwat → Nouvo → Dosye pou kreye yon dosye ki gen non", "Glise-depoze oswa Koupe/Kole pou deplase yon fichye", "Premye fwa a : « Anrejistre sou » (chwazi non + dosye)", "Anrejistre souvan (Ctrl + S) anpeche ou pèdi tout"],
            en: ["Right-click → New → Folder to create a named folder", "Drag-and-drop or Cut/Paste to move a file", "The first time: \"Save as\" (choose name + folder)", "Save often (Ctrl + S) to avoid losing everything"],
            es: ["Clic derecho → Nuevo → Carpeta para crear una carpeta con nombre", "Arrastrar y soltar o Cortar/Pegar para mover un archivo", "La primera vez: «Guardar como» (elegir nombre + carpeta)", "Guardar a menudo (Ctrl + S) evita perderlo todo"],
          },
          exercise: {
            fr: "Ouvre l'explorateur de fichiers et va dans « Documents ». Fais un clic droit dans une zone vide, choisis « Nouveau » puis « Dossier », et nomme-le « Mes exercices ». Ouvre ensuite le bloc-notes, écris quelques mots, puis fais « Fichier » → « Enregistrer sous » et enregistre le document dans ton dossier « Mes exercices » sous le nom « premier essai ».",
            ht: "Louvri esplorate fichye a epi ale nan « Dokiman ». Fè yon klik dwat nan yon zòn vid, chwazi « Nouvo » apre « Dosye », epi rele l « Egzèsis mwen yo ». Apre louvri blòk-nòt la, ekri kèk mo, apre fè « Fichye » → « Anrejistre sou » epi anrejistre dokiman an nan dosye « Egzèsis mwen yo » sou non « premye esè ».",
            en: "Open the file explorer and go to \"Documents.\" Right-click in an empty area, choose \"New\" then \"Folder,\" and name it \"My exercises.\" Then open Notepad, write a few words, and do \"File\" → \"Save as\" and save the document in your \"My exercises\" folder under the name \"first try.\"",
            es: "Abre el explorador de archivos y ve a «Documentos». Haz clic derecho en una zona vacía, elige «Nuevo» y luego «Carpeta», y nómbrala «Mis ejercicios». Luego abre el Bloc de notas, escribe unas palabras, y haz «Archivo» → «Guardar como» y guarda el documento en tu carpeta «Mis ejercicios» con el nombre «primer intento».",
          },
        },
        {
          slug: "renommer-supprimer-corbeille",
          title: { fr: "Renommer, supprimer et la corbeille", ht: "Chanje non, efase epi panyen fatra a", en: "Renaming, deleting and the recycle bin", es: "Renombrar, eliminar y la papelera" },
          videoId: "",
          content: {
            fr: "Un nom de fichier peut être changé à tout moment. Pour renommer un fichier ou un dossier, fais un clic droit dessus et choisis « Renommer ». Le nom devient modifiable : efface l'ancien avec la touche Retour arrière, tape le nouveau nom, puis appuie sur Entrée. Choisis des noms clairs qui décrivent le contenu, comme « Facture électricité janvier ».\n\nPour supprimer un fichier dont tu n'as plus besoin, fais un clic droit dessus et choisis « Supprimer », ou sélectionne-le et appuie sur la touche « Suppr » du clavier. Le fichier n'est pas détruit tout de suite : il part dans la « corbeille ».\n\nLa corbeille est un dossier spécial, représenté par une icône de poubelle sur le bureau. Elle garde les fichiers supprimés au cas où tu changerais d'avis. Si tu as effacé un fichier par erreur, ouvre la corbeille, fais un clic droit sur le fichier et choisis « Restaurer » : il revient à sa place d'origine.\n\nQuand tu es sûr de ne plus rien vouloir récupérer, tu peux « Vider la corbeille » pour libérer de l'espace sur l'ordinateur. Attention : après cette étape, les fichiers sont définitivement perdus. Vide la corbeille seulement quand tu es certain de ton choix.",
            ht: "Ou ka chanje non yon fichye nenpòt lè. Pou chanje non yon fichye oswa yon dosye, fè yon klik dwat sou li epi chwazi « Chanje non ». Non an vin modifyab : efase ansyen an ak touch Retou aryè, tape nouvo non an, apre peze Antre. Chwazi non klè ki dekri sa ki ladan l, tankou « Fakti elektrisite janvye ».\n\nPou efase yon fichye ou pa bezwen ankò, fè yon klik dwat sou li epi chwazi « Efase », oswa seleksyone l epi peze touch « Suppr » nan klavye a. Fichye a pa detwi tousuit : li ale nan « panyen fatra a ».\n\nPanyen fatra a se yon dosye espesyal, ki reprezante pa yon ikòn poubèl sou biwo a. Li kenbe fichye ou efase yo pou ka si ou ta chanje lide. Si ou efase yon fichye pa erè, louvri panyen fatra a, fè yon klik dwat sou fichye a epi chwazi « Restore » : li retounen nan plas orijinal li.\n\nLè ou si ou pa vle rekipere anyen ankò, ou ka « Vide panyen fatra a » pou libere espas sou òdinatè a. Atansyon : apre etap sa a, fichye yo pèdi nèt. Vide panyen fatra a sèlman lè ou sèten de chwa ou.",
            en: "A file name can be changed at any time. To rename a file or folder, right-click it and choose \"Rename.\" The name becomes editable: erase the old one with Backspace, type the new name, then press Enter. Choose clear names that describe the content, like \"Electricity bill January.\"\n\nTo delete a file you no longer need, right-click it and choose \"Delete,\" or select it and press the \"Delete\" key on the keyboard. The file is not destroyed right away: it goes to the \"recycle bin.\"\n\nThe recycle bin is a special folder, shown by a trash-can icon on the desktop. It keeps deleted files in case you change your mind. If you erased a file by mistake, open the recycle bin, right-click the file and choose \"Restore\": it returns to its original place.\n\nWhen you are sure you no longer want to recover anything, you can \"Empty the recycle bin\" to free up space on the computer. Be careful: after this step, the files are permanently lost. Empty the recycle bin only when you are certain of your choice.",
            es: "El nombre de un archivo puede cambiarse en cualquier momento. Para renombrar un archivo o carpeta, haz clic derecho sobre él y elige «Cambiar nombre». El nombre se vuelve editable: borra el antiguo con la tecla Retroceso, escribe el nuevo nombre y pulsa Enter. Elige nombres claros que describan el contenido, como «Factura electricidad enero».\n\nPara eliminar un archivo que ya no necesitas, haz clic derecho sobre él y elige «Eliminar», o selecciónalo y pulsa la tecla «Supr» del teclado. El archivo no se destruye enseguida: va a la «papelera».\n\nLa papelera es una carpeta especial, representada por un icono de cubo de basura en el escritorio. Guarda los archivos eliminados por si cambias de opinión. Si borraste un archivo por error, abre la papelera, haz clic derecho sobre el archivo y elige «Restaurar»: vuelve a su lugar de origen.\n\nCuando estés seguro de que ya no quieres recuperar nada, puedes «Vaciar la papelera» para liberar espacio en la computadora. Cuidado: después de este paso, los archivos se pierden definitivamente. Vacía la papelera solo cuando estés seguro de tu elección.",
          },
          keyPoints: {
            fr: ["Clic droit → Renommer pour changer le nom d'un fichier", "Supprimer (ou touche Suppr) envoie le fichier à la corbeille", "La corbeille permet de restaurer un fichier effacé par erreur", "Vider la corbeille efface définitivement : à faire avec prudence"],
            ht: ["Klik dwat → Chanje non pou chanje non yon fichye", "Efase (oswa touch Suppr) voye fichye a nan panyen fatra a", "Panyen fatra a pèmèt restore yon fichye efase pa erè", "Vide panyen fatra a efase nèt : fè l ak prekosyon"],
            en: ["Right-click → Rename to change a file's name", "Delete (or the Delete key) sends the file to the recycle bin", "The recycle bin lets you restore a file erased by mistake", "Emptying the bin erases permanently: do it carefully"],
            es: ["Clic derecho → Cambiar nombre para cambiar el nombre de un archivo", "Eliminar (o tecla Supr) envía el archivo a la papelera", "La papelera permite restaurar un archivo borrado por error", "Vaciar la papelera borra definitivamente: hazlo con prudencia"],
          },
          exercise: {
            fr: "Dans ton dossier « Mes exercices », clique droit sur le fichier « premier essai » et choisis « Renommer » ; donne-lui le nom « exercice fichiers ». Ensuite, supprime-le avec la touche Suppr. Ouvre la corbeille sur le bureau, retrouve ton fichier, fais un clic droit dessus et choisis « Restaurer ». Vérifie qu'il est bien revenu dans « Mes exercices ».",
            ht: "Nan dosye « Egzèsis mwen yo », klik dwat sou fichye « premye esè » a epi chwazi « Chanje non » ; ba li non « egzèsis fichye ». Apre, efase l ak touch Suppr. Louvri panyen fatra a sou biwo a, jwenn fichye ou a, fè yon klik dwat sou li epi chwazi « Restore ». Verifye li byen retounen nan « Egzèsis mwen yo ».",
            en: "In your \"My exercises\" folder, right-click the \"first try\" file and choose \"Rename\"; give it the name \"files exercise.\" Then delete it with the Delete key. Open the recycle bin on the desktop, find your file, right-click it and choose \"Restore.\" Check that it has returned to \"My exercises.\"",
            es: "En tu carpeta «Mis ejercicios», haz clic derecho en el archivo «primer intento» y elige «Cambiar nombre»; dale el nombre «ejercicio archivos». Luego elimínalo con la tecla Supr. Abre la papelera en el escritorio, encuentra tu archivo, haz clic derecho sobre él y elige «Restaurar». Comprueba que ha vuelto a «Mis ejercicios».",
          },
        },
      ],
    },
    {
      title: { fr: "Entretenir et sécuriser sa machine", ht: "Antretni epi sekirize machin ou", en: "Maintaining and securing your machine", es: "Mantener y proteger tu máquina" },
      lessons: [
        {
          slug: "sauvegarder-sur-cle-usb",
          title: { fr: "Sauvegarder sur une clé USB", ht: "Fè yon sovgad sou yon kle USB", en: "Backing up to a USB stick", es: "Hacer copia en una memoria USB" },
          videoId: "",
          content: {
            fr: "Une clé USB est un petit objet que l'on branche sur l'ordinateur pour y ranger des fichiers et les transporter. Sauvegarder veut dire garder une deuxième copie de tes documents importants ailleurs que dans l'ordinateur. Ainsi, si la machine tombe en panne, tes photos et tes papiers ne sont pas perdus.\n\nPour utiliser une clé USB, cherche une prise rectangulaire sur le côté ou l'avant de l'ordinateur, et enfonce la clé doucement dans le bon sens (ne force jamais). Après quelques secondes, la clé apparaît dans l'explorateur de fichiers, souvent sous un nom comme « Disque amovible (E:) ».\n\nPour copier tes fichiers dessus, ouvre le dossier qui contient tes documents, sélectionne-les, fais « Copier », puis ouvre la clé USB et fais « Coller ». Tu peux aussi glisser-déposer un dossier entier vers l'icône de la clé. Patiente pendant la copie : une barre montre l'avancement.\n\nAvant de retirer la clé, il faut la « retirer en toute sécurité » pour ne pas abîmer les fichiers. Clique sur la petite icône de clé USB près de l'horloge, choisis « Éjecter », attends le message de confirmation, puis débranche la clé. Prends l'habitude de sauvegarder chaque semaine tes fichiers les plus précieux.",
            ht: "Yon kle USB se yon ti objè ou branche sou òdinatè a pou ranje fichye ladan l epi transpòte yo. Fè yon sovgad vle di kenbe yon dezyèm kopi dokiman enpòtan ou yo yon lòt kote pase nan òdinatè a. Konsa, si machin nan an pàn, foto ou ak papye ou yo pa pèdi.\n\nPou itilize yon kle USB, chèche yon priz rektangilè sou kote oswa devan òdinatè a, epi antre kle a dousman nan bon sans lan (pa janm fòse). Apre kèk segonn, kle a parèt nan esplorate fichye a, souvan sou yon non tankou « Disk amovib (E:) ».\n\nPou kopye fichye ou yo sou li, louvri dosye ki gen dokiman ou yo, seleksyone yo, fè « Kopye », apre louvri kle USB la epi fè « Kole ». Ou ka tou glise-depoze yon dosye antye sou ikòn kle a. Tann pandan kopi a : yon ba montre avansman an.\n\nAnvan ou retire kle a, fòk ou « retire l an tout sekirite » pou ou pa gate fichye yo. Klike sou ti ikòn kle USB a bò kote lè a, chwazi « Ejekte », tann mesaj konfimasyon an, apre debranche kle a. Pran abitid fè yon sovgad chak semèn pou fichye ki pi presye yo.",
            en: "A USB stick is a small object you plug into the computer to store files and carry them around. To back up means keeping a second copy of your important documents somewhere other than the computer. That way, if the machine breaks down, your photos and papers are not lost.\n\nTo use a USB stick, look for a rectangular slot on the side or front of the computer, and push the stick in gently the right way round (never force it). After a few seconds, the stick appears in the file explorer, often under a name like \"Removable Disk (E:).\"\n\nTo copy your files onto it, open the folder that holds your documents, select them, do \"Copy,\" then open the USB stick and do \"Paste.\" You can also drag and drop a whole folder onto the stick's icon. Wait during the copy: a bar shows the progress.\n\nBefore removing the stick, you must \"safely remove\" it so as not to damage the files. Click the small USB icon near the clock, choose \"Eject,\" wait for the confirmation message, then unplug the stick. Get into the habit of backing up your most precious files every week.",
            es: "Una memoria USB es un pequeño objeto que se conecta a la computadora para guardar archivos y transportarlos. Hacer una copia de seguridad significa guardar una segunda copia de tus documentos importantes en otro lugar que no sea la computadora. Así, si la máquina se avería, tus fotos y papeles no se pierden.\n\nPara usar una memoria USB, busca una ranura rectangular en el lado o la parte delantera de la computadora, e introduce la memoria suavemente en el sentido correcto (nunca la fuerces). Tras unos segundos, la memoria aparece en el explorador de archivos, a menudo con un nombre como «Disco extraíble (E:)».\n\nPara copiar tus archivos en ella, abre la carpeta que contiene tus documentos, selecciónalos, haz «Copiar», luego abre la memoria USB y haz «Pegar». También puedes arrastrar y soltar una carpeta entera sobre el icono de la memoria. Espera durante la copia: una barra muestra el avance.\n\nAntes de retirar la memoria, hay que «quitarla de forma segura» para no dañar los archivos. Haz clic en el pequeño icono de USB junto al reloj, elige «Expulsar», espera el mensaje de confirmación y luego desconecta la memoria. Adquiere el hábito de hacer una copia cada semana de tus archivos más valiosos.",
          },
          keyPoints: {
            fr: ["Sauvegarder = garder une deuxième copie ailleurs que dans l'ordinateur", "Brancher la clé doucement, dans le bon sens, sans forcer", "Copier/Coller ou glisser-déposer les fichiers sur la clé", "Toujours « Éjecter » avant de débrancher la clé"],
            ht: ["Sovgad = kenbe yon dezyèm kopi yon lòt kote pase nan òdinatè a", "Branche kle a dousman, nan bon sans, san fòse", "Kopye/Kole oswa glise-depoze fichye yo sou kle a", "Toujou « Ejekte » anvan ou debranche kle a"],
            en: ["Backup = keep a second copy somewhere other than the computer", "Plug the stick in gently, the right way round, without forcing", "Copy/Paste or drag-and-drop the files onto the stick", "Always \"Eject\" before unplugging the stick"],
            es: ["Copia de seguridad = guardar una segunda copia fuera de la computadora", "Conecta la memoria suavemente, en el sentido correcto, sin forzar", "Copiar/Pegar o arrastrar y soltar los archivos en la memoria", "Siempre «Expulsar» antes de desconectar la memoria"],
          },
          exercise: {
            fr: "Branche une clé USB sur ton ordinateur et attends qu'elle apparaisse dans l'explorateur de fichiers. Ouvre ton dossier « Mes exercices », sélectionne-le, fais « Copier », puis ouvre la clé USB et fais « Coller ». Vérifie que le dossier est bien copié sur la clé. Enfin, retire la clé proprement en utilisant « Éjecter » avant de la débrancher.",
            ht: "Branche yon kle USB sou òdinatè ou epi tann li parèt nan esplorate fichye a. Louvri dosye « Egzèsis mwen yo », seleksyone l, fè « Kopye », apre louvri kle USB la epi fè « Kole ». Verifye dosye a byen kopye sou kle a. Anfen, retire kle a pwòpman ak « Ejekte » anvan ou debranche l.",
            en: "Plug a USB stick into your computer and wait for it to appear in the file explorer. Open your \"My exercises\" folder, select it, do \"Copy,\" then open the USB stick and do \"Paste.\" Check that the folder is properly copied onto the stick. Finally, remove the stick cleanly using \"Eject\" before unplugging it.",
            es: "Conecta una memoria USB a tu computadora y espera a que aparezca en el explorador de archivos. Abre tu carpeta «Mis ejercicios», selecciónala, haz «Copiar», luego abre la memoria USB y haz «Pegar». Comprueba que la carpeta se ha copiado bien en la memoria. Por último, retira la memoria correctamente usando «Expulsar» antes de desconectarla.",
          },
        },
        {
          slug: "mises-a-jour-et-antivirus",
          title: { fr: "Mises à jour et antivirus", ht: "Mizajou ak antiviris", en: "Updates and antivirus", es: "Actualizaciones y antivirus" },
          videoId: "",
          content: {
            fr: "Un ordinateur a besoin d'entretien, comme une voiture. Les « mises à jour » sont des améliorations que le fabricant envoie régulièrement pour corriger des erreurs et boucher les failles de sécurité. Les installer protège ta machine contre les virus qui profitent de ces failles.\n\nLa plupart du temps, l'ordinateur te prévient quand une mise à jour est prête. Il vaut mieux l'accepter, en général le soir ou quand tu ne travailles pas, car cela peut demander de redémarrer la machine. Ne débranche jamais l'ordinateur pendant une mise à jour : laisse-la se terminer complètement.\n\nUn « antivirus » est un programme qui surveille l'ordinateur et bloque les logiciels dangereux. Windows en contient déjà un, appelé « Sécurité Windows ». Tu peux l'ouvrir pour vérifier que la protection est bien active (une coche verte) et lancer une « analyse » qui inspecte tes fichiers à la recherche de menaces.\n\nPour rester en sécurité, combine trois bonnes habitudes : garde l'ordinateur à jour, laisse l'antivirus allumé, et ne télécharge que des programmes venant de sites de confiance. Ces gestes simples évitent la grande majorité des problèmes.",
            ht: "Yon òdinatè bezwen antretyen, tankou yon machin. « Mizajou » yo se amelyorasyon fabrikan an voye regilyèman pou korije erè epi bouche twou sekirite yo. Enstale yo pwoteje machin ou kont viris ki pwofite twou sa yo.\n\nPifò tan, òdinatè a avèti ou lè yon mizajou pare. Li pi bon pou aksepte l, an jeneral aswè oswa lè ou pa travay, paske sa ka mande pou redemare machin nan. Pa janm debranche òdinatè a pandan yon mizajou : kite l fini nèt.\n\nYon « antiviris » se yon pwogram ki siveye òdinatè a epi bloke lojisyèl danjere yo. Windows deja gen youn ladan l, yo rele « Sekirite Windows ». Ou ka louvri l pou verifye pwoteksyon an byen aktif (yon tchèk vèt) epi lanse yon « analiz » ki enspekte fichye ou yo pou chèche menas.\n\nPou ou rete an sekirite, konbine twa bon abitid : kenbe òdinatè a ajou, kite antiviris la limen, epi telechaje sèlman pwogram ki soti nan sit ou fè konfyans. Jès senp sa yo evite pi gwo pati nan pwoblèm yo.",
            en: "A computer needs maintenance, like a car. \"Updates\" are improvements that the manufacturer sends regularly to fix errors and close security holes. Installing them protects your machine against viruses that take advantage of those holes.\n\nMost of the time, the computer warns you when an update is ready. It is better to accept it, usually in the evening or when you are not working, because it may require restarting the machine. Never unplug the computer during an update: let it finish completely.\n\nAn \"antivirus\" is a program that watches over the computer and blocks dangerous software. Windows already includes one, called \"Windows Security.\" You can open it to check that protection is active (a green checkmark) and run a \"scan\" that inspects your files looking for threats.\n\nTo stay safe, combine three good habits: keep the computer up to date, leave the antivirus turned on, and download only programs from trusted sites. These simple actions prevent the vast majority of problems.",
            es: "Una computadora necesita mantenimiento, como un coche. Las «actualizaciones» son mejoras que el fabricante envía con regularidad para corregir errores y cerrar fallos de seguridad. Instalarlas protege tu máquina contra los virus que aprovechan esos fallos.\n\nLa mayoría de las veces, la computadora te avisa cuando una actualización está lista. Es mejor aceptarla, generalmente por la noche o cuando no trabajas, porque puede requerir reiniciar la máquina. Nunca desconectes la computadora durante una actualización: déjala terminar por completo.\n\nUn «antivirus» es un programa que vigila la computadora y bloquea el software peligroso. Windows ya incluye uno, llamado «Seguridad de Windows». Puedes abrirlo para comprobar que la protección está activa (una marca verde) y lanzar un «análisis» que inspecciona tus archivos en busca de amenazas.\n\nPara mantenerte seguro, combina tres buenos hábitos: mantén la computadora actualizada, deja el antivirus encendido, y descarga solo programas de sitios de confianza. Estos gestos simples evitan la gran mayoría de los problemas.",
          },
          keyPoints: {
            fr: ["Les mises à jour corrigent les erreurs et les failles de sécurité", "Ne jamais débrancher l'ordinateur pendant une mise à jour", "L'antivirus (Sécurité Windows) bloque les logiciels dangereux", "À jour + antivirus allumé + téléchargements de confiance"],
            ht: ["Mizajou yo korije erè ak twou sekirite yo", "Pa janm debranche òdinatè a pandan yon mizajou", "Antiviris la (Sekirite Windows) bloke lojisyèl danjere yo", "Ajou + antiviris limen + telechajman ou fè konfyans"],
            en: ["Updates fix errors and security holes", "Never unplug the computer during an update", "The antivirus (Windows Security) blocks dangerous software", "Up to date + antivirus on + trusted downloads"],
            es: ["Las actualizaciones corrigen errores y fallos de seguridad", "Nunca desconectes la computadora durante una actualización", "El antivirus (Seguridad de Windows) bloquea software peligroso", "Actualizado + antivirus encendido + descargas de confianza"],
          },
          exercise: {
            fr: "Ouvre les « Paramètres » depuis le menu Démarrer (icône d'engrenage). Cherche la rubrique « Windows Update » et clique sur « Rechercher des mises à jour » : observe si ton ordinateur est à jour ou s'il propose une installation. Ensuite, ouvre « Sécurité Windows » et vérifie que la protection contre les virus est bien active (coche verte).",
            ht: "Louvri « Paramèt » yo depi meni Demaraj la (ikòn angrenaj). Chèche ribrik « Windows Update » a epi klike sou « Chèche mizajou » : obsève si òdinatè ou ajou oswa si l pwopoze yon enstalasyon. Apre, louvri « Sekirite Windows » epi verifye pwoteksyon kont viris la byen aktif (tchèk vèt).",
            en: "Open \"Settings\" from the Start menu (gear icon). Look for the \"Windows Update\" section and click \"Check for updates\": see whether your computer is up to date or offers an installation. Then open \"Windows Security\" and check that virus protection is active (green checkmark).",
            es: "Abre «Configuración» desde el menú Inicio (icono de engranaje). Busca la sección «Windows Update» y haz clic en «Buscar actualizaciones»: observa si tu computadora está actualizada o si propone una instalación. Luego abre «Seguridad de Windows» y comprueba que la protección contra virus está activa (marca verde).",
          },
        },
        {
          slug: "installer-desinstaller-programme",
          title: { fr: "Installer et désinstaller un programme", ht: "Enstale epi dezenstale yon pwogram", en: "Installing and uninstalling a program", es: "Instalar y desinstalar un programa" },
          videoId: "",
          content: {
            fr: "Un « programme » (ou application, logiciel) ajoute une fonction à ton ordinateur : lire des vidéos, discuter, retoucher des photos. Pour en installer un, on télécharge d'abord son fichier d'installation depuis le site officiel du logiciel, puis on double-clique dessus pour lancer l'installation.\n\nUn assistant s'ouvre alors et te guide étape par étape. Lis chaque écran avant de cliquer sur « Suivant ». Fais attention aux cases déjà cochées qui proposent d'installer des programmes supplémentaires inutiles : décoche-les. À la fin, clique sur « Terminer », et le nouveau programme apparaît dans le menu Démarrer.\n\nAvec le temps, certains programmes ne servent plus et encombrent l'ordinateur. Pour en supprimer un proprement, ne te contente pas d'effacer son icône. Ouvre les « Paramètres », puis « Applications », trouve le programme dans la liste, clique dessus et choisis « Désinstaller ».\n\nNe désinstalle que les programmes que tu as toi-même ajoutés et que tu reconnais. Laisse tranquilles ceux dont le nom t'est inconnu ou qui appartiennent au système : ils peuvent être nécessaires au bon fonctionnement de la machine. En cas de doute, renseigne-toi avant de supprimer.",
            ht: "Yon « pwogram » (oswa aplikasyon, lojisyèl) ajoute yon fonksyon nan òdinatè ou : gade videyo, pale, retouche foto. Pou enstale youn, ou telechaje anvan fichye enstalasyon li a depi sou sit ofisyèl lojisyèl la, apre ou double-klike sou li pou lanse enstalasyon an.\n\nYon asistan louvri epi li gide ou etap pa etap. Li chak ekran anvan ou klike sou « Swivan ». Fè atansyon ak kaz ki deja tcheke ki pwopoze pou enstale lòt pwogram initil : detcheke yo. Nan fen an, klike sou « Fini », epi nouvo pwogram nan parèt nan meni Demaraj la.\n\nAk tan an, gen pwogram ki pa sèvi ankò epi ki chaje òdinatè a. Pou retire youn pwòpman, pa jis efase ikòn li. Louvri « Paramèt » yo, apre « Aplikasyon », jwenn pwogram nan nan lis la, klike sou li epi chwazi « Dezenstale ».\n\nDezenstale sèlman pwogram ou menm te ajoute epi ou rekonèt yo. Kite trankil sa yo ou pa konnen non yo oswa ki fè pati sistèm nan : yo ka nesesè pou bon fonksyònman machin nan. Si ou gen dout, enfòme ou anvan ou retire.",
            en: "A \"program\" (or application, software) adds a function to your computer: playing videos, chatting, editing photos. To install one, you first download its installation file from the software's official site, then double-click it to start the installation.\n\nA wizard then opens and guides you step by step. Read each screen before clicking \"Next.\" Watch out for pre-checked boxes that offer to install extra, useless programs: uncheck them. At the end, click \"Finish,\" and the new program appears in the Start menu.\n\nOver time, some programs are no longer useful and clutter the computer. To remove one cleanly, do not just erase its icon. Open \"Settings,\" then \"Apps,\" find the program in the list, click it and choose \"Uninstall.\"\n\nUninstall only the programs you added yourself and recognize. Leave alone those whose name is unfamiliar or that belong to the system: they may be needed for the machine to work properly. When in doubt, find out before removing.",
            es: "Un «programa» (o aplicación, software) añade una función a tu computadora: reproducir videos, chatear, retocar fotos. Para instalar uno, primero se descarga su archivo de instalación desde el sitio oficial del software, luego se hace doble clic sobre él para iniciar la instalación.\n\nEntonces se abre un asistente que te guía paso a paso. Lee cada pantalla antes de hacer clic en «Siguiente». Presta atención a las casillas ya marcadas que proponen instalar programas adicionales inútiles: desmárcalas. Al final, haz clic en «Finalizar», y el nuevo programa aparece en el menú Inicio.\n\nCon el tiempo, algunos programas ya no sirven y saturan la computadora. Para quitar uno correctamente, no te limites a borrar su icono. Abre «Configuración», luego «Aplicaciones», encuentra el programa en la lista, haz clic sobre él y elige «Desinstalar».\n\nDesinstala solo los programas que tú mismo añadiste y que reconoces. Deja en paz aquellos cuyo nombre no conoces o que pertenecen al sistema: pueden ser necesarios para el buen funcionamiento de la máquina. En caso de duda, infórmate antes de eliminar.",
          },
          keyPoints: {
            fr: ["Installer : télécharger depuis le site officiel, puis suivre l'assistant", "Décocher les programmes supplémentaires inutiles proposés", "Désinstaller proprement par Paramètres → Applications → Désinstaller", "Ne toucher qu'aux programmes que l'on reconnaît"],
            ht: ["Enstale : telechaje depi sit ofisyèl la, apre swiv asistan an", "Detcheke lòt pwogram initil yo pwopoze yo", "Dezenstale pwòpman pa Paramèt → Aplikasyon → Dezenstale", "Manyen sèlman pwogram ou rekonèt yo"],
            en: ["Install: download from the official site, then follow the wizard", "Uncheck the useless extra programs offered", "Uninstall cleanly via Settings → Apps → Uninstall", "Only touch programs you recognize"],
            es: ["Instalar: descargar del sitio oficial, luego seguir el asistente", "Desmarcar los programas adicionales inútiles propuestos", "Desinstalar correctamente por Configuración → Aplicaciones → Desinstalar", "Tocar solo los programas que se reconocen"],
          },
          exercise: {
            fr: "Ouvre les « Paramètres » puis « Applications » et « Applications installées ». Fais défiler la liste des programmes présents sur ton ordinateur et repère-en trois que tu reconnais et utilises. Clique sur l'un d'eux pour voir apparaître le bouton « Désinstaller », mais NE clique PAS dessus : le but est seulement de savoir où se trouve cette option, sans rien supprimer.",
            ht: "Louvri « Paramèt » yo apre « Aplikasyon » ak « Aplikasyon enstale yo ». Fè lis pwogram ki sou òdinatè ou defile epi repere twa ladan yo ou rekonèt epi ou itilize. Klike sou youn ladan yo pou wè bouton « Dezenstale » a parèt, men PA klike sou li : objektif la se sèlman konnen kote opsyon sa a ye, san w pa efase anyen.",
            en: "Open \"Settings\" then \"Apps\" and \"Installed apps.\" Scroll through the list of programs on your computer and spot three that you recognize and use. Click one of them to make the \"Uninstall\" button appear, but do NOT click it: the goal is only to learn where this option is, without removing anything.",
            es: "Abre «Configuración» luego «Aplicaciones» y «Aplicaciones instaladas». Desplázate por la lista de programas de tu computadora y localiza tres que reconozcas y uses. Haz clic en uno de ellos para que aparezca el botón «Desinstalar», pero NO hagas clic en él: el objetivo es solo saber dónde está esta opción, sin eliminar nada.",
          },
        },
      ],
    },
  ],
};

export default informatique;
