import { CourseContent } from "./types";

const internet: CourseContent = {
  slug: "internet",
  intro: {
    fr: "Naviguer sur Internet en confiance : comprendre le navigateur, faire des recherches efficaces, protéger ses mots de passe, reconnaître les arnaques et communiquer en ligne pour rester en sécurité et utile.",
    ht: "Navige sou Entènèt ak konfyans : konprann navigatè a, fè rechèch ki efikas, pwoteje modpas ou, rekonèt magouy epi kominike sou entènèt pou ou rete an sekirite epi itil.",
    en: "Browse the Internet with confidence: understand the browser, search effectively, protect your passwords, recognize scams and communicate online to stay safe and capable.",
    es: "Navegar por Internet con confianza: comprender el navegador, hacer búsquedas eficaces, proteger tus contraseñas, reconocer las estafas y comunicarte en línea para mantenerte seguro y capaz.",
  },
  modules: [
    {
      title: { fr: "Découvrir Internet", ht: "Dekouvri Entènèt", en: "Discovering the Internet", es: "Descubrir Internet" },
      lessons: [
        {
          slug: "quest-ce-quinternet-navigateur",
          title: { fr: "Internet et le navigateur", ht: "Entènèt ak navigatè a", en: "The Internet and the browser", es: "Internet y el navegador" },
          videoId: "",
          content: {
            fr: "Internet est un immense réseau qui relie des millions d'ordinateurs dans le monde entier. Grâce à lui, tu peux lire des informations, regarder des vidéos, envoyer des messages ou faire des achats, sans bouger de chez toi. Pour t'y connecter, il te faut un accès Internet (par câble, par Wi-Fi ou par le réseau du téléphone).\n\nPour visiter des pages Internet, on utilise un programme spécial appelé « navigateur ». Les plus connus sont Chrome, Firefox, Edge et Safari. Reconnaissable à son icône ronde ou colorée, le navigateur est la fenêtre par laquelle tu regardes le web. Tu l'ouvres d'un double-clic, comme n'importe quel programme.\n\nEn haut du navigateur se trouve la « barre d'adresse ». C'est là que l'on tape l'adresse d'un site (par exemple www.exemple.com) pour s'y rendre directement. Chaque site a une adresse unique, un peu comme une maison a une adresse postale. Une fois l'adresse tapée, appuie sur Entrée et la page s'affiche.\n\nÀ côté de la barre d'adresse, deux flèches sont très utiles. La flèche vers la gauche te ramène à la page précédente, celle vers la droite te fait avancer de nouveau. Un bouton en forme de cercle (recharger) réaffiche la page si elle s'est mal chargée. Ces boutons te permettent de circuler sans jamais te perdre.",
            ht: "Entènèt se yon gwo rezo ki konekte plizyè milyon òdinatè nan lemonn antye. Gremesi li, ou ka li enfòmasyon, gade videyo, voye mesaj oswa fè acha, san w pa deplase lakay ou. Pou konekte, ou bezwen yon aksè Entènèt (pa kab, pa Wi-Fi oswa pa rezo telefòn nan).\n\nPou vizite paj Entènèt, nou itilize yon pwogram espesyal yo rele « navigatè ». Sa yo pi popilè yo se Chrome, Firefox, Edge ak Safari. Ou rekonèt li ak ikòn won oswa kolore l, navigatè a se fenèt kote ou gade web la. Ou louvri l ak yon doub-klik, tankou nenpòt pwogram.\n\nAnwo navigatè a gen « ba adrès la ». Se la ou tape adrès yon sit (pa egzanp www.egzanp.com) pou w ale la dirèkteman. Chak sit gen yon adrès inik, tankou yon kay gen yon adrès postal. Yon fwa ou tape adrès la, peze Antre epi paj la parèt.\n\nBò kote ba adrès la, de flèch trè itil. Flèch ki vè agoch la mennen ou tounen nan paj anvan an, sa ki vè adwat la fè w avanse ankò. Yon bouton ki gen fòm yon sèk (rechaje) reafiche paj la si li pa byen chaje. Bouton sa yo pèmèt ou sikile san ou pa janm pèdi.",
            en: "The Internet is a huge network that connects millions of computers around the world. Thanks to it, you can read information, watch videos, send messages or shop, without leaving home. To connect, you need Internet access (by cable, by Wi-Fi or through the phone network).\n\nTo visit Internet pages, we use a special program called a \"browser.\" The best known are Chrome, Firefox, Edge and Safari. Recognizable by its round or colorful icon, the browser is the window through which you look at the web. You open it with a double-click, like any program.\n\nAt the top of the browser is the \"address bar.\" That is where you type the address of a site (for example www.example.com) to go there directly. Each site has a unique address, a bit like a house has a postal address. Once the address is typed, press Enter and the page appears.\n\nNext to the address bar, two arrows are very useful. The left arrow takes you back to the previous page, the right one moves you forward again. A circle-shaped button (reload) redisplays the page if it loaded badly. These buttons let you move around without ever getting lost.",
            es: "Internet es una inmensa red que conecta millones de computadoras en todo el mundo. Gracias a ella, puedes leer información, ver videos, enviar mensajes o hacer compras, sin moverte de casa. Para conectarte, necesitas un acceso a Internet (por cable, por Wi-Fi o por la red del teléfono).\n\nPara visitar páginas de Internet, usamos un programa especial llamado «navegador». Los más conocidos son Chrome, Firefox, Edge y Safari. Reconocible por su icono redondo o colorido, el navegador es la ventana por la que miras la web. Lo abres con un doble clic, como cualquier programa.\n\nEn la parte superior del navegador está la «barra de direcciones». Ahí es donde se escribe la dirección de un sitio (por ejemplo www.ejemplo.com) para ir directamente. Cada sitio tiene una dirección única, un poco como una casa tiene una dirección postal. Una vez escrita la dirección, pulsa Enter y la página aparece.\n\nJunto a la barra de direcciones, dos flechas son muy útiles. La flecha hacia la izquierda te lleva de vuelta a la página anterior, la de la derecha te hace avanzar de nuevo. Un botón en forma de círculo (recargar) vuelve a mostrar la página si se cargó mal. Estos botones te permiten circular sin perderte nunca.",
          },
          keyPoints: {
            fr: ["Internet relie des millions d'ordinateurs dans le monde", "Le navigateur (Chrome, Firefox…) est la fenêtre vers le web", "La barre d'adresse sert à taper l'adresse d'un site", "Les flèches précédent/suivant et le bouton recharger aident à circuler"],
            ht: ["Entènèt konekte plizyè milyon òdinatè nan lemonn", "Navigatè a (Chrome, Firefox…) se fenèt vè web la", "Ba adrès la sèvi pou tape adrès yon sit", "Flèch anvan/swivan ak bouton rechaje a ede sikile"],
            en: ["The Internet links millions of computers worldwide", "The browser (Chrome, Firefox…) is the window to the web", "The address bar is for typing a site's address", "The back/forward arrows and reload button help you move around"],
            es: ["Internet conecta millones de computadoras en el mundo", "El navegador (Chrome, Firefox…) es la ventana a la web", "La barra de direcciones sirve para escribir la dirección de un sitio", "Las flechas atrás/adelante y el botón recargar ayudan a circular"],
          },
          exercise: {
            fr: "Ouvre ton navigateur d'un double-clic. Dans la barre d'adresse en haut, tape « www.wikipedia.org » et appuie sur Entrée pour ouvrir le site. Clique sur un lien de la page, puis utilise la flèche « précédent » (à gauche) pour revenir en arrière. Enfin, clique sur le bouton « recharger » (le cercle) pour réafficher la page.",
            ht: "Louvri navigatè ou ak yon doub-klik. Nan ba adrès la anwo, tape « www.wikipedia.org » epi peze Antre pou louvri sit la. Klike sou yon lyen nan paj la, apre itilize flèch « anvan » an (agoch) pou tounen dèyè. Anfen, klike sou bouton « rechaje » a (sèk la) pou reafiche paj la.",
            en: "Open your browser with a double-click. In the address bar at the top, type \"www.wikipedia.org\" and press Enter to open the site. Click a link on the page, then use the \"back\" arrow (on the left) to go back. Finally, click the \"reload\" button (the circle) to redisplay the page.",
            es: "Abre tu navegador con un doble clic. En la barra de direcciones arriba, escribe «www.wikipedia.org» y pulsa Enter para abrir el sitio. Haz clic en un enlace de la página, luego usa la flecha «atrás» (a la izquierda) para volver. Por último, haz clic en el botón «recargar» (el círculo) para volver a mostrar la página.",
          },
        },
        {
          slug: "rechercher-efficacement",
          title: { fr: "Rechercher efficacement", ht: "Fè rechèch ki efikas", en: "Searching effectively", es: "Buscar eficazmente" },
          videoId: "",
          content: {
            fr: "Quand on ne connaît pas l'adresse exacte d'un site, on utilise un « moteur de recherche » comme Google. Il suffit d'écrire ce que l'on cherche dans la barre de recherche, puis d'appuyer sur Entrée. Le moteur affiche alors une liste de résultats : des liens bleus sur lesquels tu peux cliquer pour ouvrir chaque page.\n\nPour de bons résultats, tape des mots simples et précis plutôt qu'une longue phrase. Par exemple, écris « horaire pharmacie Port-au-Prince » plutôt que « je voudrais savoir à quelle heure ouvre la pharmacie ». Plus les mots sont ciblés, plus les résultats sont utiles.\n\nTous les résultats ne se valent pas. Regarde l'adresse du site et le titre avant de cliquer. Méfie-toi des pages qui promettent des choses trop belles. Les premiers résultats marqués « Annonce » ou « Sponsorisé » sont des publicités payées, pas forcément les meilleures réponses. Compare plusieurs sources pour te faire une idée juste.\n\nAprès avoir ouvert un résultat, si la page ne te convient pas, reviens en arrière avec la flèche « précédent » et essaie un autre lien. Tu peux aussi reformuler ta recherche en ajoutant un mot, par exemple « recette riz collé Haïti facile ». Chercher, c'est aussi affiner petit à petit jusqu'à trouver.",
            ht: "Lè ou pa konnen adrès egzak yon sit, ou itilize yon « motè rechèch » tankou Google. Ou senpleman ekri sa w ap chèche a nan ba rechèch la, apre peze Antre. Motè a montre yon lis rezilta : lyen ble ou ka klike sou yo pou louvri chak paj.\n\nPou bon rezilta, tape mo senp e presi olye yon long fraz. Pa egzanp, ekri « lè famasi Pòtoprens » olye « mwen ta renmen konnen a ki lè famasi a louvri ». Plis mo yo sible, plis rezilta yo itil.\n\nTout rezilta pa gen menm valè. Gade adrès sit la ak tit la anvan ou klike. Pran prekosyon ak paj ki pwomèt bagay ki twò bèl. Premye rezilta ki make « Anons » oswa « Sponsorize » yo se piblisite yo peye, se pa nesesèman pi bon repons yo. Konpare plizyè sous pou fè yon lide ki jis.\n\nApre ou louvri yon rezilta, si paj la pa konvni ou, tounen dèyè ak flèch « anvan » an epi eseye yon lòt lyen. Ou ka tou refòmile rechèch ou lè w ajoute yon mo, pa egzanp « resèt diri kole Ayiti fasil ». Chèche, se afine tou piti piti jouk ou jwenn.",
            en: "When you don't know the exact address of a site, you use a \"search engine\" like Google. Just write what you are looking for in the search bar, then press Enter. The engine then shows a list of results: blue links you can click to open each page.\n\nFor good results, type simple, precise words rather than a long sentence. For example, write \"pharmacy hours Port-au-Prince\" rather than \"I would like to know what time the pharmacy opens.\" The more targeted the words, the more useful the results.\n\nNot all results are equal. Look at the site's address and the title before clicking. Be wary of pages that promise things too good to be true. The first results marked \"Ad\" or \"Sponsored\" are paid advertisements, not necessarily the best answers. Compare several sources to form a fair idea.\n\nAfter opening a result, if the page does not suit you, go back with the \"back\" arrow and try another link. You can also reword your search by adding a word, for example \"easy rice and beans recipe Haiti.\" Searching also means refining little by little until you find it.",
            es: "Cuando no conoces la dirección exacta de un sitio, usas un «motor de búsqueda» como Google. Basta con escribir lo que buscas en la barra de búsqueda y luego pulsar Enter. El motor muestra entonces una lista de resultados: enlaces azules en los que puedes hacer clic para abrir cada página.\n\nPara buenos resultados, escribe palabras simples y precisas en lugar de una frase larga. Por ejemplo, escribe «horario farmacia Puerto Príncipe» en lugar de «quisiera saber a qué hora abre la farmacia». Cuanto más específicas sean las palabras, más útiles serán los resultados.\n\nNo todos los resultados valen lo mismo. Mira la dirección del sitio y el título antes de hacer clic. Desconfía de las páginas que prometen cosas demasiado buenas. Los primeros resultados marcados «Anuncio» o «Patrocinado» son publicidad pagada, no necesariamente las mejores respuestas. Compara varias fuentes para formarte una idea justa.\n\nDespués de abrir un resultado, si la página no te conviene, vuelve atrás con la flecha «atrás» y prueba otro enlace. También puedes reformular tu búsqueda añadiendo una palabra, por ejemplo «receta arroz con frijoles Haití fácil». Buscar también es afinar poco a poco hasta encontrar.",
          },
          keyPoints: {
            fr: ["Un moteur de recherche (Google) trouve des sites par mots-clés", "Tape des mots simples et précis, pas de longue phrase", "Méfie-toi des « Annonces » et compare plusieurs sources", "Reviens en arrière et reformule si le résultat ne convient pas"],
            ht: ["Yon motè rechèch (Google) jwenn sit ak mo-kle", "Tape mo senp e presi, pa long fraz", "Pran prekosyon ak « Anons » epi konpare plizyè sous", "Tounen dèyè epi refòmile si rezilta a pa konvni"],
            en: ["A search engine (Google) finds sites by keywords", "Type simple, precise words, not a long sentence", "Beware of \"Ads\" and compare several sources", "Go back and reword if the result does not fit"],
            es: ["Un motor de búsqueda (Google) encuentra sitios por palabras clave", "Escribe palabras simples y precisas, no una frase larga", "Desconfía de los «Anuncios» y compara varias fuentes", "Vuelve atrás y reformula si el resultado no conviene"],
          },
          exercise: {
            fr: "Ouvre Google (www.google.com). Cherche l'information « météo » suivie du nom de ta ville, par exemple « météo Port-au-Prince », et appuie sur Entrée. Repère dans la liste les résultats marqués « Annonce » et ne clique pas dessus. Ouvre un vrai résultat, lis l'information, puis reviens en arrière et affine ta recherche en ajoutant le mot « demain ».",
            ht: "Louvri Google (www.google.com). Chèche enfòmasyon « meteyo » swiv non vil ou, pa egzanp « meteyo Pòtoprens », epi peze Antre. Repere nan lis la rezilta ki make « Anons » yo epi pa klike sou yo. Louvri yon vrè rezilta, li enfòmasyon an, apre tounen dèyè epi afine rechèch ou lè w ajoute mo « demen » an.",
            en: "Open Google (www.google.com). Search for the information \"weather\" followed by your city's name, for example \"weather Port-au-Prince,\" and press Enter. Spot in the list the results marked \"Ad\" and do not click them. Open a real result, read the information, then go back and refine your search by adding the word \"tomorrow.\"",
            es: "Abre Google (www.google.com). Busca la información «clima» seguida del nombre de tu ciudad, por ejemplo «clima Puerto Príncipe», y pulsa Enter. Localiza en la lista los resultados marcados «Anuncio» y no hagas clic en ellos. Abre un resultado real, lee la información, luego vuelve atrás y afina tu búsqueda añadiendo la palabra «mañana».",
          },
        },
        {
          slug: "naviguer-liens-precedent",
          title: { fr: "Naviguer d'une page à l'autre", ht: "Navige soti nan yon paj ale nan yon lòt", en: "Moving from one page to another", es: "Navegar de una página a otra" },
          videoId: "",
          content: {
            fr: "Une page web contient souvent des « liens » : des mots ou des images sur lesquels on peut cliquer pour aller ailleurs. On les reconnaît car le pointeur de la souris se transforme en petite main quand il passe dessus. Les liens en texte sont souvent soulignés ou de couleur différente, généralement bleue.\n\nCliquer sur un lien t'emmène vers une nouvelle page, sur le même site ou sur un autre. C'est ainsi que l'on « navigue » : de lien en lien, comme on tourne les pages d'un journal. Chaque site est organisé avec un menu en haut, qui regroupe les grandes rubriques (Accueil, Contact, Actualités).\n\nSi tu te retrouves sur une page qui ne t'intéresse pas, pas de panique : la flèche « précédent » en haut à gauche te ramène à la page d'avant. Tu peux appuyer plusieurs fois pour remonter tout ton parcours. La flèche « suivant » refait le chemin en avant.\n\nPour revenir directement au début d'un site, clique sur son logo ou sur le mot « Accueil » dans le menu : cela te ramène à la page principale. Avec ces quelques gestes, tu peux explorer n'importe quel site sans crainte de te perdre, puisque tu sais toujours comment revenir en arrière.",
            ht: "Yon paj web souvan gen « lyen » : mo oswa imaj ou ka klike sou yo pou ale yon lòt kote. Ou rekonèt yo paske pwentè sourit la vin yon ti men lè li pase sou yo. Lyen tèks yo souvan sou-liyen oswa yon lòt koulè, jeneralman ble.\n\nKlike sou yon lyen mennen ou nan yon nouvo paj, sou menm sit la oswa sou yon lòt. Se konsa ou « navige » : soti nan yon lyen ale nan yon lòt, tankou ou vire paj yon jounal. Chak sit òganize ak yon meni anwo, ki rasanble gwo ribrik yo (Akèy, Kontak, Aktualite).\n\nSi ou rive sou yon paj ki pa enterese ou, pa panike : flèch « anvan » an anwo agoch mennen ou tounen nan paj anvan an. Ou ka peze plizyè fwa pou remonte tout parkou ou. Flèch « swivan » an refè chemen an devan.\n\nPou tounen dirèkteman nan kòmansman yon sit, klike sou logo li oswa sou mo « Akèy » la nan meni an : sa mennen ou tounen nan paj prensipal la. Ak kèk jès sa yo, ou ka eksplore nenpòt sit san laperèz pou pèdi, paske ou toujou konnen kijan pou tounen dèyè.",
            en: "A web page often contains \"links\": words or images you can click to go elsewhere. You recognize them because the mouse pointer turns into a small hand when it passes over them. Text links are often underlined or a different color, usually blue.\n\nClicking a link takes you to a new page, on the same site or another. That is how you \"navigate\": from link to link, like turning the pages of a newspaper. Each site is organized with a menu at the top, gathering the main sections (Home, Contact, News).\n\nIf you end up on a page that does not interest you, do not panic: the \"back\" arrow at the top left brings you to the page before. You can press it several times to retrace your whole path. The \"forward\" arrow redoes the way forward.\n\nTo return directly to the start of a site, click its logo or the word \"Home\" in the menu: that brings you to the main page. With these few gestures, you can explore any site without fear of getting lost, since you always know how to go back.",
            es: "Una página web suele contener «enlaces»: palabras o imágenes en las que se puede hacer clic para ir a otro lugar. Se reconocen porque el puntero del ratón se convierte en una pequeña mano cuando pasa por encima. Los enlaces de texto suelen estar subrayados o de un color diferente, generalmente azul.\n\nHacer clic en un enlace te lleva a una nueva página, en el mismo sitio o en otro. Así es como se «navega»: de enlace en enlace, como se pasan las páginas de un periódico. Cada sitio está organizado con un menú arriba, que agrupa las grandes secciones (Inicio, Contacto, Noticias).\n\nSi acabas en una página que no te interesa, no te asustes: la flecha «atrás» arriba a la izquierda te lleva a la página anterior. Puedes pulsarla varias veces para rehacer todo tu recorrido. La flecha «adelante» rehace el camino hacia adelante.\n\nPara volver directamente al inicio de un sitio, haz clic en su logo o en la palabra «Inicio» del menú: eso te lleva a la página principal. Con estos pocos gestos, puedes explorar cualquier sitio sin miedo a perderte, ya que siempre sabes cómo volver atrás.",
          },
          keyPoints: {
            fr: ["Un lien (texte souligné/bleu ou image) mène à une autre page", "Le pointeur devient une petite main sur un lien", "La flèche « précédent » ramène toujours à la page d'avant", "Le logo ou « Accueil » ramène à la page principale du site"],
            ht: ["Yon lyen (tèks sou-liyen/ble oswa imaj) mennen nan yon lòt paj", "Pwentè a vin yon ti men sou yon lyen", "Flèch « anvan » an toujou mennen tounen nan paj anvan an", "Logo a oswa « Akèy » mennen tounen nan paj prensipal sit la"],
            en: ["A link (underlined/blue text or image) leads to another page", "The pointer becomes a small hand over a link", "The \"back\" arrow always returns to the previous page", "The logo or \"Home\" returns to the site's main page"],
            es: ["Un enlace (texto subrayado/azul o imagen) lleva a otra página", "El puntero se vuelve una pequeña mano sobre un enlace", "La flecha «atrás» siempre lleva a la página anterior", "El logo o «Inicio» lleva a la página principal del sitio"],
          },
          exercise: {
            fr: "Ouvre un site d'information que tu connais. Passe le pointeur sur différents endroits de la page pour repérer les liens : il devient une petite main. Clique sur un titre d'article pour l'ouvrir, lis le début, puis reviens avec la flèche « précédent ». Clique ensuite sur le logo du site en haut pour revenir à la page d'accueil.",
            ht: "Louvri yon sit enfòmasyon ou konnen. Pase pwentè a sou diferan kote nan paj la pou repere lyen yo : li vin yon ti men. Klike sou yon tit atik pou louvri l, li kòmansman an, apre tounen ak flèch « anvan » an. Apre klike sou logo sit la anwo pou tounen nan paj akèy la.",
            en: "Open a news site you know. Move the pointer over different spots on the page to spot the links: it becomes a small hand. Click an article title to open it, read the beginning, then go back with the \"back\" arrow. Then click the site's logo at the top to return to the home page.",
            es: "Abre un sitio de noticias que conozcas. Pasa el puntero por distintos lugares de la página para localizar los enlaces: se convierte en una pequeña mano. Haz clic en un título de artículo para abrirlo, lee el principio, luego vuelve con la flecha «atrás». Después haz clic en el logo del sitio arriba para volver a la página de inicio.",
          },
        },
      ],
    },
    {
      title: { fr: "Se protéger en ligne", ht: "Pwoteje tèt ou sou entènèt", en: "Protecting yourself online", es: "Protegerse en línea" },
      lessons: [
        {
          slug: "mots-de-passe-solides",
          title: { fr: "Des mots de passe solides", ht: "Modpas ki solid", en: "Strong passwords", es: "Contraseñas seguras" },
          videoId: "",
          content: {
            fr: "Un mot de passe est la clé qui protège tes comptes (courriel, banque, réseaux sociaux). S'il est trop simple, quelqu'un peut le deviner et prendre ta place. Évite « 123456 », « motdepasse » ou ta date de naissance : ce sont les premiers essais des personnes mal intentionnées.\n\nUn bon mot de passe est long (au moins douze caractères) et mélange majuscules, minuscules, chiffres et symboles. Une astuce : pense à une phrase que tu retiens facilement et transforme-la, par exemple « J'aime le café à 6h ! » devient « JaimeLeCafeA6h! ». C'est long, unique et facile à mémoriser pour toi seul.\n\nUtilise un mot de passe différent pour chaque compte important. Ainsi, si l'un est découvert, les autres restent protégés. Ne le partage jamais et ne l'écris pas sur un papier laissé à la vue de tous. Pour aider ta mémoire, un « gestionnaire de mots de passe » peut les garder en sécurité à ta place.\n\nQuand c'est possible, active la « double authentification » (ou vérification en deux étapes). En plus du mot de passe, le site t'envoie un code par message sur ton téléphone. Même si quelqu'un connaît ton mot de passe, il ne peut pas entrer sans ce code. C'est une protection très efficace, surtout pour ton courriel et ta banque.",
            ht: "Yon modpas se kle ki pwoteje kont ou yo (imèl, bank, rezo sosyal). Si li twò senp, yon moun ka devine l epi pran plas ou. Evite « 123456 », « modpas » oswa dat nesans ou : se premye esè move moun yo fè.\n\nYon bon modpas long (omwen douz karaktè) epi li melanje majiskil, miniskil, chif ak senbòl. Yon ti astis : panse a yon fraz ou sonje fasil epi transfòme l, pa egzanp « Mwen renmen kafe a 6è ! » vin « MwenRenmenKafeA6e! ». Li long, inik e fasil pou ou sèl sonje.\n\nItilize yon modpas diferan pou chak kont ki enpòtan. Konsa, si youn dekouvri, lòt yo rete pwoteje. Pa janm pataje l epi pa ekri l sou yon papye ou kite devan je tout moun. Pou ede memwa ou, yon « jesyonè modpas » ka kenbe yo an sekirite nan plas ou.\n\nLè sa posib, aktive « doub otantifikasyon » an (oswa verifikasyon an de etap). Anplis modpas la, sit la voye yon kòd pou ou nan yon mesaj sou telefòn ou. Menm si yon moun konnen modpas ou, li pa ka antre san kòd sa a. Se yon pwoteksyon trè efikas, sitou pou imèl ou ak bank ou.",
            en: "A password is the key that protects your accounts (email, bank, social media). If it is too simple, someone can guess it and take your place. Avoid \"123456\", \"password\" or your date of birth: these are the first tries of ill-intentioned people.\n\nA good password is long (at least twelve characters) and mixes uppercase, lowercase, numbers and symbols. A tip: think of a phrase you remember easily and transform it, for example \"I love coffee at 6am!\" becomes \"ILoveCoffeeAt6am!\". It is long, unique and easy for you alone to remember.\n\nUse a different password for each important account. That way, if one is discovered, the others stay protected. Never share it and do not write it on a paper left in plain sight. To help your memory, a \"password manager\" can keep them safe for you.\n\nWhen possible, turn on \"two-factor authentication\" (or two-step verification). In addition to the password, the site sends you a code by message on your phone. Even if someone knows your password, they cannot get in without that code. It is a very effective protection, especially for your email and your bank.",
            es: "Una contraseña es la llave que protege tus cuentas (correo, banco, redes sociales). Si es demasiado simple, alguien puede adivinarla y tomar tu lugar. Evita «123456», «contraseña» o tu fecha de nacimiento: son los primeros intentos de las personas malintencionadas.\n\nUna buena contraseña es larga (al menos doce caracteres) y mezcla mayúsculas, minúsculas, números y símbolos. Un truco: piensa en una frase que recuerdes fácilmente y transfórmala, por ejemplo «¡Me gusta el café a las 6h!» se convierte en «MeGustaElCafeA6h!». Es larga, única y fácil de memorizar solo para ti.\n\nUsa una contraseña diferente para cada cuenta importante. Así, si una es descubierta, las demás quedan protegidas. Nunca la compartas ni la escribas en un papel a la vista de todos. Para ayudar a tu memoria, un «gestor de contraseñas» puede guardarlas de forma segura por ti.\n\nCuando sea posible, activa la «doble autenticación» (o verificación en dos pasos). Además de la contraseña, el sitio te envía un código por mensaje a tu teléfono. Aunque alguien conozca tu contraseña, no puede entrar sin ese código. Es una protección muy eficaz, sobre todo para tu correo y tu banco.",
          },
          keyPoints: {
            fr: ["Évite les mots de passe simples (123456, date de naissance)", "Long (12+ caractères) : majuscules, chiffres, symboles", "Un mot de passe différent par compte, jamais partagé", "Active la double authentification quand c'est possible"],
            ht: ["Evite modpas senp (123456, dat nesans)", "Long (12+ karaktè) : majiskil, chif, senbòl", "Yon modpas diferan pou chak kont, pa janm pataje", "Aktive doub otantifikasyon lè sa posib"],
            en: ["Avoid simple passwords (123456, birth date)", "Long (12+ characters): capitals, numbers, symbols", "A different password per account, never shared", "Turn on two-factor authentication when possible"],
            es: ["Evita contraseñas simples (123456, fecha de nacimiento)", "Larga (12+ caracteres): mayúsculas, números, símbolos", "Una contraseña diferente por cuenta, nunca compartida", "Activa la doble autenticación cuando sea posible"],
          },
          exercise: {
            fr: "Sur une feuille de papier, invente un bon mot de passe à partir d'une phrase que tu retiens facilement (par exemple « Mon chien s'appelle Rex depuis 2019 »). Transforme-la en un mot de passe d'au moins douze caractères mélangeant majuscules, minuscules, chiffres et un symbole. Vérifie qu'il ne contient ni ta date de naissance ni ton prénom. Puis déchire la feuille : le but est seulement de t'entraîner à en créer un solide.",
            ht: "Sou yon fèy papye, envante yon bon modpas apati yon fraz ou sonje fasil (pa egzanp « Chen mwen rele Rex depi 2019 »). Transfòme l an yon modpas omwen douz karaktè ki melanje majiskil, miniskil, chif ak yon senbòl. Verifye li pa gen ni dat nesans ou ni prenon ou. Apre chire fèy la : objektif la se sèlman antrene w kreye youn ki solid.",
            en: "On a sheet of paper, invent a good password from a phrase you remember easily (for example \"My dog is named Rex since 2019\"). Turn it into a password of at least twelve characters mixing capitals, lowercase, numbers and one symbol. Check that it contains neither your birth date nor your first name. Then tear up the sheet: the goal is only to practice creating a strong one.",
            es: "En una hoja de papel, inventa una buena contraseña a partir de una frase que recuerdes fácilmente (por ejemplo «Mi perro se llama Rex desde 2019»). Transfórmala en una contraseña de al menos doce caracteres que mezcle mayúsculas, minúsculas, números y un símbolo. Comprueba que no contenga ni tu fecha de nacimiento ni tu nombre. Luego rompe la hoja: el objetivo es solo practicar crear una segura.",
          },
        },
        {
          slug: "arnaques-phishing",
          title: { fr: "Reconnaître les arnaques et le phishing", ht: "Rekonèt magouy ak phishing", en: "Recognizing scams and phishing", es: "Reconocer estafas y phishing" },
          videoId: "",
          content: {
            fr: "Le « phishing » (ou hameçonnage) est une arnaque très courante. Un escroc t'envoie un message qui imite une entreprise connue (ta banque, un service de livraison) pour te voler tes informations. Le message crée souvent la peur ou l'urgence : « Votre compte va être bloqué, cliquez vite ! » Le but est de te faire agir sans réfléchir.\n\nApprends à repérer les signes d'alerte. Vérifie l'adresse de l'expéditeur : elle est souvent bizarre ou mal orthographiée. Méfie-toi des fautes de langue, des liens étranges et des demandes d'argent, de mot de passe ou de numéro de carte. Une vraie banque ne te demandera jamais ton mot de passe complet par courriel ou par téléphone.\n\nEn cas de doute, ne clique sur aucun lien et n'ouvre aucune pièce jointe. Ne réponds pas au message. Contacte l'entreprise toi-même, en tapant son adresse officielle dans le navigateur ou en appelant le numéro que tu connais déjà. Si une offre semble trop belle pour être vraie, c'est presque toujours un piège.\n\nLes arnaques ne viennent pas que par courriel : elles arrivent aussi par SMS, par appel ou sur les réseaux sociaux. Méfie-toi d'un inconnu qui te promet un gain, un héritage ou l'amour, puis finit par demander de l'argent. La règle d'or reste la même : ne jamais donner d'argent ni d'informations personnelles à quelqu'un que tu ne connais pas vraiment.",
            ht: "« Phishing » (oswa peche moun) se yon magouy ki trè kouran. Yon eskwo voye yon mesaj ki imite yon konpayi ou konnen (bank ou, yon sèvis livrezon) pou vòlè enfòmasyon ou. Mesaj la souvan kreye laperèz oswa ijans : « Kont ou pral bloke, klike vit ! » Objektif la se fè w aji san reflechi.\n\nAprann repere siy danje yo. Verifye adrès moun ki voye a : souvan li dwòl oswa mal ekri. Pran prekosyon ak fot lang, lyen etranj ak demann lajan, modpas oswa nimewo kat. Yon vrè bank p ap janm mande w modpas konplè ou pa imèl oswa pa telefòn.\n\nSi ou gen dout, pa klike sou okenn lyen epi pa louvri okenn atachman. Pa reponn mesaj la. Kontakte konpayi an ou menm, lè w tape adrès ofisyèl li nan navigatè a oswa lè w rele nimewo ou deja konnen an. Si yon òf sanble twò bèl pou l vre, prèske toujou se yon pyèj.\n\nMagouy pa vini sèlman pa imèl : yo rive tou pa SMS, pa apèl oswa sou rezo sosyal yo. Pran prekosyon ak yon enkoni ki pwomèt ou yon gany, yon eritaj oswa lanmou, apre l fini pa mande lajan. Règ an lò a rete menm bagay la : pa janm bay lajan ni enfòmasyon pèsonèl bay yon moun ou pa vrèman konnen.",
            en: "\"Phishing\" is a very common scam. A crook sends you a message that imitates a well-known company (your bank, a delivery service) to steal your information. The message often creates fear or urgency: \"Your account will be blocked, click quickly!\" The aim is to make you act without thinking.\n\nLearn to spot the warning signs. Check the sender's address: it is often strange or misspelled. Be wary of language mistakes, odd links, and requests for money, a password or a card number. A real bank will never ask for your full password by email or by phone.\n\nWhen in doubt, do not click any link and do not open any attachment. Do not reply to the message. Contact the company yourself, by typing its official address into the browser or by calling a number you already know. If an offer seems too good to be true, it is almost always a trap.\n\nScams do not come only by email: they also arrive by text message, by call or on social media. Be wary of a stranger who promises you a prize, an inheritance or love, then ends up asking for money. The golden rule stays the same: never give money or personal information to someone you do not really know.",
            es: "El «phishing» (o suplantación) es una estafa muy común. Un estafador te envía un mensaje que imita a una empresa conocida (tu banco, un servicio de entrega) para robar tu información. El mensaje suele crear miedo o urgencia: «¡Tu cuenta será bloqueada, haz clic rápido!» El objetivo es hacerte actuar sin pensar.\n\nAprende a detectar las señales de alerta. Verifica la dirección del remitente: suele ser rara o mal escrita. Desconfía de los errores de idioma, los enlaces extraños y las peticiones de dinero, contraseña o número de tarjeta. Un banco real nunca te pedirá tu contraseña completa por correo o por teléfono.\n\nEn caso de duda, no hagas clic en ningún enlace ni abras ningún adjunto. No respondas al mensaje. Contacta a la empresa tú mismo, escribiendo su dirección oficial en el navegador o llamando a un número que ya conoces. Si una oferta parece demasiado buena para ser verdad, casi siempre es una trampa.\n\nLas estafas no llegan solo por correo: también llegan por SMS, por llamada o en las redes sociales. Desconfía de un desconocido que te promete un premio, una herencia o amor, y acaba pidiendo dinero. La regla de oro sigue siendo la misma: nunca des dinero ni información personal a alguien que no conoces de verdad.",
          },
          keyPoints: {
            fr: ["Le phishing imite une entreprise et crée l'urgence", "Signes : adresse bizarre, fautes, demande de mot de passe/argent", "En cas de doute : ne clique pas, contacte l'entreprise toi-même", "Les arnaques arrivent aussi par SMS, appel et réseaux sociaux"],
            ht: ["Phishing imite yon konpayi epi kreye ijans", "Siy : adrès dwòl, fot, demann modpas/lajan", "Si dout : pa klike, kontakte konpayi an ou menm", "Magouy rive tou pa SMS, apèl ak rezo sosyal"],
            en: ["Phishing imitates a company and creates urgency", "Signs: strange address, mistakes, request for password/money", "When in doubt: don't click, contact the company yourself", "Scams also come by text, call and social media"],
            es: ["El phishing imita a una empresa y crea urgencia", "Señales: dirección rara, errores, petición de contraseña/dinero", "Ante la duda: no hagas clic, contacta a la empresa tú mismo", "Las estafas también llegan por SMS, llamada y redes sociales"],
          },
          exercise: {
            fr: "Repense à un message suspect que toi ou un proche avez déjà reçu (courriel, SMS ou message sur les réseaux). Note sur une feuille au moins trois signes d'alerte qu'il contenait : urgence, faute d'orthographe, adresse bizarre, demande d'argent ou de mot de passe. Écris ensuite la bonne réaction : ne pas cliquer, ne pas répondre, et contacter l'entreprise par son vrai numéro.",
            ht: "Sonje yon mesaj sispèk ou menm oswa yon moun pre ou te deja resevwa (imèl, SMS oswa mesaj sou rezo yo). Note sou yon fèy omwen twa siy danje li te genyen : ijans, fot òtograf, adrès dwòl, demann lajan oswa modpas. Apre ekri bon reyaksyon an : pa klike, pa reponn, epi kontakte konpayi an ak vrè nimewo li.",
            en: "Think back to a suspicious message you or someone close to you already received (email, text or message on social media). Write on a sheet at least three warning signs it contained: urgency, spelling mistake, strange address, request for money or password. Then write the right reaction: do not click, do not reply, and contact the company through its real number.",
            es: "Recuerda un mensaje sospechoso que tú o alguien cercano ya haya recibido (correo, SMS o mensaje en redes). Anota en una hoja al menos tres señales de alerta que contenía: urgencia, falta de ortografía, dirección rara, petición de dinero o contraseña. Luego escribe la reacción correcta: no hacer clic, no responder, y contactar a la empresa por su número real.",
          },
        },
        {
          slug: "proteger-vie-privee",
          title: { fr: "Protéger sa vie privée", ht: "Pwoteje vi prive ou", en: "Protecting your privacy", es: "Proteger tu privacidad" },
          videoId: "",
          content: {
            fr: "Tout ce que tu publies sur Internet peut être vu, copié et gardé longtemps. Avant de partager une photo, une adresse ou un numéro de téléphone, demande-toi : « Est-ce que cela me dérangerait que n'importe qui le voie ? » Une fois en ligne, une information est très difficile à effacer complètement.\n\nSur les réseaux sociaux, règle les « paramètres de confidentialité » pour choisir qui peut voir tes publications : tout le monde, ou seulement tes amis. Par défaut, beaucoup de comptes sont visibles par tous. Prends le temps d'ouvrir les réglages et de limiter la visibilité de ce que tu partages.\n\nMéfie-toi des informations que tu donnes aux sites. Beaucoup demandent ta date de naissance, ton adresse ou ton numéro sans réelle nécessité. Ne remplis que les champs obligatoires, souvent marqués d'une étoile (*), et laisse le reste vide quand c'est possible.\n\nEnfin, fais attention aux « cookies » et aux autorisations. Quand un site demande d'accéder à ta position, à ta caméra ou à ton micro, réfléchis si c'est vraiment utile avant d'accepter. Sur un ordinateur partagé, déconnecte-toi de tes comptes et évite d'enregistrer tes mots de passe dans le navigateur. Protéger sa vie privée, c'est décider soi-même ce que l'on montre et ce que l'on garde pour soi.",
            ht: "Tout sa ou pibliye sou Entènèt ka wè, kopye epi kenbe pandan lontan. Anvan ou pataje yon foto, yon adrès oswa yon nimewo telefòn, mande tèt ou : « Èske sa ta deranje m si nenpòt moun wè l ? » Yon fwa sou entènèt, yon enfòmasyon trè difisil pou efase nèt.\n\nSou rezo sosyal yo, regle « paramèt konfidansyalite » yo pou chwazi kiyès ki ka wè piblikasyon ou : tout moun, oswa sèlman zanmi ou. Pa defo, anpil kont vizib pou tout moun. Pran tan pou louvri reglaj yo epi limite vizibilite sa ou pataje.\n\nPran prekosyon ak enfòmasyon ou bay sit yo. Anpil mande dat nesans ou, adrès ou oswa nimewo ou san reyèl nesesite. Ranpli sèlman chan obligatwa yo, souvan make ak yon zetwal (*), epi kite rès la vid lè sa posib.\n\nAnfen, fè atansyon ak « cookies » yo ak otorizasyon yo. Lè yon sit mande pou aksede pozisyon ou, kamera ou oswa mikwo ou, reflechi si li vrèman itil anvan ou aksepte. Sou yon òdinatè pataje, dekonekte de kont ou yo epi evite anrejistre modpas ou nan navigatè a. Pwoteje vi prive ou, se deside tèt ou sa ou montre ak sa ou kenbe pou ou.",
            en: "Everything you post on the Internet can be seen, copied and kept for a long time. Before sharing a photo, an address or a phone number, ask yourself: \"Would it bother me if anyone at all saw it?\" Once online, information is very hard to erase completely.\n\nOn social media, set the \"privacy settings\" to choose who can see your posts: everyone, or only your friends. By default, many accounts are visible to all. Take the time to open the settings and limit the visibility of what you share.\n\nBe careful about the information you give to sites. Many ask for your birth date, address or number without real need. Fill in only the required fields, often marked with a star (*), and leave the rest empty when possible.\n\nFinally, watch out for \"cookies\" and permissions. When a site asks to access your location, camera or microphone, think about whether it is really useful before accepting. On a shared computer, log out of your accounts and avoid saving your passwords in the browser. Protecting your privacy means deciding for yourself what you show and what you keep to yourself.",
            es: "Todo lo que publicas en Internet puede verse, copiarse y guardarse durante mucho tiempo. Antes de compartir una foto, una dirección o un número de teléfono, pregúntate: «¿Me molestaría que cualquiera lo viera?» Una vez en línea, una información es muy difícil de borrar por completo.\n\nEn las redes sociales, ajusta la «configuración de privacidad» para elegir quién puede ver tus publicaciones: todo el mundo, o solo tus amigos. Por defecto, muchas cuentas son visibles para todos. Tómate el tiempo de abrir los ajustes y limitar la visibilidad de lo que compartes.\n\nDesconfía de la información que das a los sitios. Muchos piden tu fecha de nacimiento, tu dirección o tu número sin verdadera necesidad. Rellena solo los campos obligatorios, a menudo marcados con una estrella (*), y deja el resto vacío cuando sea posible.\n\nPor último, ten cuidado con las «cookies» y los permisos. Cuando un sitio pide acceder a tu ubicación, tu cámara o tu micrófono, piensa si es realmente útil antes de aceptar. En una computadora compartida, cierra sesión de tus cuentas y evita guardar tus contraseñas en el navegador. Proteger tu privacidad es decidir tú mismo qué muestras y qué guardas para ti.",
          },
          keyPoints: {
            fr: ["Ce qui est publié en ligne peut être vu et gardé longtemps", "Règle les paramètres de confidentialité (qui voit tes publications)", "Ne remplis que les champs obligatoires (étoile *)", "Réfléchis avant d'autoriser position, caméra ou micro"],
            ht: ["Sa ki pibliye sou entènèt ka wè epi kenbe lontan", "Regle paramèt konfidansyalite yo (kiyès ki wè piblikasyon ou)", "Ranpli sèlman chan obligatwa yo (zetwal *)", "Reflechi anvan ou otorize pozisyon, kamera oswa mikwo"],
            en: ["What is posted online can be seen and kept for a long time", "Set the privacy settings (who sees your posts)", "Fill only the required fields (star *)", "Think before allowing location, camera or microphone"],
            es: ["Lo publicado en línea puede verse y guardarse mucho tiempo", "Ajusta la configuración de privacidad (quién ve tus publicaciones)", "Rellena solo los campos obligatorios (estrella *)", "Piensa antes de permitir ubicación, cámara o micrófono"],
          },
          exercise: {
            fr: "Si tu as un compte sur un réseau social, ouvre ses « Paramètres » puis la section « Confidentialité ». Regarde qui peut voir tes publications et, si c'est réglé sur « Public », change-le en « Amis ». Si tu n'as pas de compte, réfléchis à trois informations que tu ne devrais jamais publier en ligne (adresse exacte, numéro de carte, mot de passe) et note-les.",
            ht: "Si ou gen yon kont sou yon rezo sosyal, louvri « Paramèt » li yo apre seksyon « Konfidansyalite » a. Gade kiyès ki ka wè piblikasyon ou yo epi, si li regle sou « Piblik », chanje l an « Zanmi ». Si ou pa gen kont, reflechi sou twa enfòmasyon ou pa ta dwe janm pibliye sou entènèt (adrès egzak, nimewo kat, modpas) epi note yo.",
            en: "If you have an account on a social network, open its \"Settings\" then the \"Privacy\" section. Look at who can see your posts and, if it is set to \"Public,\" change it to \"Friends.\" If you do not have an account, think of three pieces of information you should never post online (exact address, card number, password) and write them down.",
            es: "Si tienes una cuenta en una red social, abre su «Configuración» y luego la sección «Privacidad». Mira quién puede ver tus publicaciones y, si está en «Público», cámbialo a «Amigos». Si no tienes cuenta, piensa en tres informaciones que nunca deberías publicar en línea (dirección exacta, número de tarjeta, contraseña) y anótalas.",
          },
        },
      ],
    },
    {
      title: { fr: "Naviguer avec de bonnes habitudes", ht: "Navige ak bon abitid", en: "Browsing with good habits", es: "Navegar con buenos hábitos" },
      lessons: [
        {
          slug: "sites-surs-https",
          title: { fr: "Reconnaître un site sûr", ht: "Rekonèt yon sit ki an sekirite", en: "Recognizing a safe site", es: "Reconocer un sitio seguro" },
          videoId: "",
          content: {
            fr: "Avant de saisir une information personnelle (mot de passe, numéro de carte), assure-toi que le site est sûr. Regarde le début de l'adresse dans la barre du navigateur : elle doit commencer par « https » et non « http ». Le « s » signifie « sécurisé » : les données échangées sont protégées.\n\nUn petit cadenas fermé apparaît souvent à côté de l'adresse. Il indique que la connexion est chiffrée. Attention toutefois : le cadenas dit que la liaison est protégée, pas que le site est honnête. Vérifie aussi que l'adresse est bien celle attendue, sans faute ni lettre en trop (par exemple « paypa1.com » au lieu de « paypal.com »).\n\nSur un ordinateur public ou un Wi-Fi gratuit (café, aéroport), sois prudent : évite d'y consulter ta banque ou d'y entrer des mots de passe importants. Quand tu as fini, pense à te déconnecter de tes comptes en cliquant sur « Se déconnecter », surtout si l'ordinateur n'est pas le tien.\n\nMéfie-toi aussi des fenêtres qui surgissent brusquement (« pop-ups ») pour annoncer que tu as gagné un prix ou que ton ordinateur est infecté. Ce sont presque toujours des pièges : ne clique pas dessus, ferme-les avec la petite croix ou en fermant l'onglet. Un vrai site sérieux ne t'agresse pas de messages clignotants.",
            ht: "Anvan ou antre yon enfòmasyon pèsonèl (modpas, nimewo kat), asire w sit la an sekirite. Gade kòmansman adrès la nan ba navigatè a : li dwe kòmanse ak « https » epi non pa « http ». « s » la vle di « sekirize » : done ki chanje yo pwoteje.\n\nYon ti kadna fèmen souvan parèt bò kote adrès la. Li endike koneksyon an chifre. Men atansyon : kadna a di lyezon an pwoteje, se pa sit la ki onèt. Verifye tou adrès la se byen sa w ap tann nan, san fot ni lèt anplis (pa egzanp « paypa1.com » olye « paypal.com »).\n\nSou yon òdinatè piblik oswa yon Wi-Fi gratis (kafe, ayewopò), fè atansyon : evite konsilte bank ou oswa antre modpas enpòtan la. Lè w fini, sonje dekonekte de kont ou yo lè w klike sou « Dekonekte », sitou si òdinatè a se pa pou ou.\n\nPran prekosyon tou ak fenèt ki sote sanzatann yo (« pop-ups ») pou anonse ou genyen yon pri oswa òdinatè ou enfekte. Prèske toujou se pyèj : pa klike sou yo, fèmen yo ak ti kwa a oswa lè w fèmen onglè a. Yon vrè sit serye pa atake ou ak mesaj k ap klete.",
            en: "Before entering personal information (password, card number), make sure the site is safe. Look at the start of the address in the browser bar: it should begin with \"https\" and not \"http.\" The \"s\" means \"secure\": the data exchanged is protected.\n\nA small closed padlock often appears next to the address. It indicates the connection is encrypted. Be careful though: the padlock says the link is protected, not that the site is honest. Also check that the address is really the expected one, with no mistake or extra letter (for example \"paypa1.com\" instead of \"paypal.com\").\n\nOn a public computer or free Wi-Fi (café, airport), be cautious: avoid checking your bank or entering important passwords there. When you are done, remember to log out of your accounts by clicking \"Log out,\" especially if the computer is not yours.\n\nAlso be wary of windows that pop up suddenly (\"pop-ups\") announcing you have won a prize or that your computer is infected. These are almost always traps: do not click them, close them with the small cross or by closing the tab. A real, serious site does not attack you with flashing messages.",
            es: "Antes de introducir una información personal (contraseña, número de tarjeta), asegúrate de que el sitio es seguro. Mira el inicio de la dirección en la barra del navegador: debe empezar por «https» y no «http». La «s» significa «seguro»: los datos intercambiados están protegidos.\n\nUn pequeño candado cerrado suele aparecer junto a la dirección. Indica que la conexión está cifrada. Ten cuidado, sin embargo: el candado dice que el enlace está protegido, no que el sitio sea honesto. Verifica también que la dirección sea la esperada, sin error ni letra de más (por ejemplo «paypa1.com» en lugar de «paypal.com»).\n\nEn una computadora pública o un Wi-Fi gratuito (café, aeropuerto), sé prudente: evita consultar tu banco o introducir contraseñas importantes. Cuando termines, recuerda cerrar sesión de tus cuentas haciendo clic en «Cerrar sesión», sobre todo si la computadora no es tuya.\n\nDesconfía también de las ventanas que surgen de golpe («pop-ups») para anunciar que has ganado un premio o que tu computadora está infectada. Casi siempre son trampas: no hagas clic en ellas, ciérralas con la pequeña cruz o cerrando la pestaña. Un sitio serio de verdad no te agrede con mensajes parpadeantes.",
          },
          keyPoints: {
            fr: ["Un site sûr commence par « https » avec un cadenas fermé", "Vérifie l'adresse exacte (attention aux fautes qui imitent)", "Sur un ordinateur public : prudence et déconnexion", "Ferme les pop-ups « vous avez gagné » sans jamais cliquer dedans"],
            ht: ["Yon sit an sekirite kòmanse ak « https » ak yon kadna fèmen", "Verifye adrès egzak la (atansyon fot ki imite)", "Sou yon òdinatè piblik : prekosyon ak dekoneksyon", "Fèmen pop-ups « ou genyen » san w pa janm klike ladan yo"],
            en: ["A safe site starts with \"https\" and a closed padlock", "Check the exact address (watch for imitation misspellings)", "On a public computer: caution and log out", "Close \"you have won\" pop-ups without ever clicking inside them"],
            es: ["Un sitio seguro empieza por «https» con un candado cerrado", "Verifica la dirección exacta (cuidado con errores que imitan)", "En una computadora pública: prudencia y cerrar sesión", "Cierra los pop-ups «has ganado» sin hacer clic nunca dentro"],
          },
          exercise: {
            fr: "Ouvre le site d'une grande organisation que tu connais (par exemple une banque ou un journal). Regarde attentivement le début de l'adresse et vérifie qu'elle commence par « https ». Repère le petit cadenas fermé à gauche de l'adresse et clique dessus pour voir les informations de sécurité. Enfin, lis l'adresse en entier et vérifie qu'aucune lettre n'est remplacée par un chiffre.",
            ht: "Louvri sit yon gwo òganizasyon ou konnen (pa egzanp yon bank oswa yon jounal). Gade byen kòmansman adrès la epi verifye li kòmanse ak « https ». Repere ti kadna fèmen an agoch adrès la epi klike sou li pou wè enfòmasyon sekirite yo. Anfen, li adrès la nèt epi verifye pa gen okenn lèt ki ranplase pa yon chif.",
            en: "Open the site of a large organization you know (for example a bank or a newspaper). Look carefully at the start of the address and check that it begins with \"https.\" Spot the small closed padlock to the left of the address and click it to see the security information. Finally, read the whole address and check that no letter is replaced by a number.",
            es: "Abre el sitio de una gran organización que conozcas (por ejemplo un banco o un periódico). Mira con atención el inicio de la dirección y verifica que empieza por «https». Localiza el pequeño candado cerrado a la izquierda de la dirección y haz clic en él para ver la información de seguridad. Por último, lee la dirección entera y verifica que ninguna letra esté reemplazada por un número.",
          },
        },
        {
          slug: "onglets-favoris-historique",
          title: { fr: "Onglets, favoris et historique", ht: "Onglè, favori ak istorik", en: "Tabs, favorites and history", es: "Pestañas, favoritos e historial" },
          videoId: "",
          content: {
            fr: "Le navigateur permet d'ouvrir plusieurs pages en même temps grâce aux « onglets ». Chaque onglet est comme une page dans un même cahier : tu passes de l'une à l'autre en cliquant sur le petit rectangle en haut. Pour ouvrir un nouvel onglet, clique sur le « + » à côté des onglets existants ; pour en fermer un, clique sur la petite croix.\n\nLes « favoris » (ou marque-pages) servent à garder l'adresse d'un site que tu visites souvent, sans avoir à la retaper. Il suffit de cliquer sur la petite étoile dans la barre d'adresse. La prochaine fois, tu retrouveras le site en un clic dans ta liste de favoris. C'est très pratique pour ton courriel ou un site d'information favori.\n\nL'« historique » garde la trace des pages que tu as visitées. Il t'aide à retrouver un site que tu as vu hier mais dont tu as oublié l'adresse. Sur un ordinateur partagé, tu peux effacer cet historique pour préserver ta vie privée, ou utiliser une « fenêtre de navigation privée » qui n'enregistre rien.\n\nUn conseil pour rester organisé : n'ouvre pas trop d'onglets à la fois, car cela ralentit l'ordinateur et rend l'écran confus. Ferme ceux dont tu n'as plus besoin. Range tes favoris dans des dossiers (par exemple « Administratif », « Loisirs ») pour les retrouver encore plus vite.",
            ht: "Navigatè a pèmèt ou louvri plizyè paj an menm tan gremesi « onglè » yo. Chak onglè tankou yon paj nan menm kaye a : ou pase soti nan youn ale nan lòt lè w klike sou ti rektang anwo a. Pou louvri yon nouvo onglè, klike sou « + » bò kote onglè ki egziste yo ; pou fèmen youn, klike sou ti kwa a.\n\n« Favori » yo (oswa mak-paj) sèvi pou kenbe adrès yon sit ou vizite souvan, san w pa bezwen retape l. Ou senpleman klike sou ti zetwal la nan ba adrès la. Pwochèn fwa, ou pral jwenn sit la ak yon sèl klik nan lis favori ou. Sa trè pratik pou imèl ou oswa yon sit enfòmasyon ou pi renmen.\n\n« Istorik » la kenbe tras paj ou vizite yo. Li ede w jwenn yon sit ou te wè yè men ou bliye adrès la. Sou yon òdinatè pataje, ou ka efase istorik sa a pou pwoteje vi prive ou, oswa itilize yon « fenèt navigasyon prive » ki pa anrejistre anyen.\n\nYon konsèy pou rete òganize : pa louvri twòp onglè an menm tan, paske sa ralanti òdinatè a epi fè ekran an konfize. Fèmen sa ou pa bezwen ankò yo. Ranje favori ou yo nan dosye (pa egzanp « Administratif », « Lwazi ») pou jwenn yo pi vit toujou.",
            en: "The browser lets you open several pages at the same time thanks to \"tabs.\" Each tab is like a page in the same notebook: you switch from one to another by clicking the small rectangle at the top. To open a new tab, click the \"+\" next to the existing tabs; to close one, click the small cross.\n\n\"Favorites\" (or bookmarks) are used to keep the address of a site you visit often, without having to retype it. Just click the small star in the address bar. Next time, you will find the site with one click in your favorites list. This is very handy for your email or a favorite news site.\n\nThe \"history\" keeps a record of the pages you have visited. It helps you find a site you saw yesterday but whose address you forgot. On a shared computer, you can clear this history to protect your privacy, or use a \"private browsing window\" that saves nothing.\n\nA tip to stay organized: do not open too many tabs at once, because that slows down the computer and makes the screen confusing. Close the ones you no longer need. Arrange your favorites into folders (for example \"Admin\", \"Leisure\") to find them even faster.",
            es: "El navegador permite abrir varias páginas al mismo tiempo gracias a las «pestañas». Cada pestaña es como una página en el mismo cuaderno: pasas de una a otra haciendo clic en el pequeño rectángulo de arriba. Para abrir una nueva pestaña, haz clic en el «+» junto a las pestañas existentes; para cerrar una, haz clic en la pequeña cruz.\n\nLos «favoritos» (o marcadores) sirven para guardar la dirección de un sitio que visitas a menudo, sin tener que volver a escribirla. Basta con hacer clic en la pequeña estrella de la barra de direcciones. La próxima vez, encontrarás el sitio con un clic en tu lista de favoritos. Es muy práctico para tu correo o un sitio de noticias favorito.\n\nEl «historial» guarda el rastro de las páginas que has visitado. Te ayuda a encontrar un sitio que viste ayer pero cuya dirección olvidaste. En una computadora compartida, puedes borrar este historial para proteger tu privacidad, o usar una «ventana de navegación privada» que no guarda nada.\n\nUn consejo para mantenerte organizado: no abras demasiadas pestañas a la vez, porque eso ralentiza la computadora y vuelve confusa la pantalla. Cierra las que ya no necesitas. Ordena tus favoritos en carpetas (por ejemplo «Administrativo», «Ocio») para encontrarlos aún más rápido.",
          },
          keyPoints: {
            fr: ["Les onglets ouvrent plusieurs pages en même temps", "Les favoris (étoile) gardent les sites visités souvent", "L'historique retrouve les pages ; la navigation privée n'enregistre rien", "N'ouvre pas trop d'onglets et ferme ceux devenus inutiles"],
            ht: ["Onglè yo louvri plizyè paj an menm tan", "Favori yo (zetwal) kenbe sit ou vizite souvan", "Istorik la jwenn paj yo ; navigasyon prive pa anrejistre anyen", "Pa louvri twòp onglè epi fèmen sa ki vin initil yo"],
            en: ["Tabs open several pages at once", "Favorites (star) keep frequently visited sites", "History finds pages; private browsing saves nothing", "Do not open too many tabs and close the useless ones"],
            es: ["Las pestañas abren varias páginas a la vez", "Los favoritos (estrella) guardan los sitios visitados a menudo", "El historial encuentra las páginas; la navegación privada no guarda nada", "No abras demasiadas pestañas y cierra las que ya no sirven"],
          },
          exercise: {
            fr: "Dans ton navigateur, ouvre un nouvel onglet avec le « + » et affiche-y le site www.wikipedia.org. Reviens au premier onglet en cliquant dessus, puis retourne au second. Sur la page Wikipedia, clique sur la petite étoile de la barre d'adresse pour l'ajouter aux favoris. Enfin, ferme l'onglet avec la croix et vérifie que le favori est bien enregistré.",
            ht: "Nan navigatè ou, louvri yon nouvo onglè ak « + » a epi afiche sit www.wikipedia.org ladan l. Tounen nan premye onglè a lè w klike sou li, apre retounen nan dezyèm nan. Sou paj Wikipedia a, klike sou ti zetwal ba adrès la pou ajoute l nan favori. Anfen, fèmen onglè a ak kwa a epi verifye favori a byen anrejistre.",
            en: "In your browser, open a new tab with the \"+\" and display the site www.wikipedia.org in it. Go back to the first tab by clicking it, then return to the second. On the Wikipedia page, click the small star in the address bar to add it to favorites. Finally, close the tab with the cross and check that the favorite is properly saved.",
            es: "En tu navegador, abre una nueva pestaña con el «+» y muestra en ella el sitio www.wikipedia.org. Vuelve a la primera pestaña haciendo clic en ella, luego regresa a la segunda. En la página de Wikipedia, haz clic en la pequeña estrella de la barra de direcciones para añadirla a favoritos. Por último, cierra la pestaña con la cruz y comprueba que el favorito se ha guardado bien.",
          },
        },
        {
          slug: "telecharger-un-fichier",
          title: { fr: "Télécharger un fichier en sécurité", ht: "Telechaje yon fichye an sekirite", en: "Downloading a file safely", es: "Descargar un archivo con seguridad" },
          videoId: "",
          content: {
            fr: "« Télécharger » veut dire copier un fichier depuis Internet vers ton ordinateur : une facture en PDF, une photo, un formulaire à remplir. Quand tu cliques sur un bouton « Télécharger » ou sur un lien de fichier, le navigateur récupère le fichier et le range automatiquement dans le dossier « Téléchargements ».\n\nPendant le téléchargement, une petite barre montre l'avancement, souvent en bas ou en haut à droite du navigateur. Une fois terminé, tu peux cliquer sur le fichier pour l'ouvrir directement, ou aller le retrouver plus tard dans le dossier « Téléchargements » de l'explorateur de fichiers.\n\nSois prudent avec ce que tu télécharges. Ne récupère des fichiers que depuis des sites de confiance. Méfie-toi des boutons « Télécharger » très voyants et clignotants sur certaines pages : ce sont parfois de fausses publicités qui installent des programmes indésirables. Regarde bien le nom du fichier et son extension avant de l'ouvrir.\n\nCertaines extensions demandent une attention particulière. Un fichier « .pdf » (document), « .jpg » (image) ou « .docx » (texte) est généralement sans danger. En revanche, un fichier « .exe » installe un programme : ne l'ouvre que si tu es certain de sa provenance. En cas de doute, ne l'ouvre pas et supprime-le.",
            ht: "« Telechaje » vle di kopye yon fichye depi sou Entènèt vè òdinatè ou : yon fakti an PDF, yon foto, yon fòmilè pou ranpli. Lè ou klike sou yon bouton « Telechaje » oswa sou yon lyen fichye, navigatè a rekipere fichye a epi range l otomatikman nan dosye « Telechajman » an.\n\nPandan telechajman an, yon ti ba montre avansman an, souvan anba oswa anwo adwat navigatè a. Yon fwa fini, ou ka klike sou fichye a pou louvri l dirèkteman, oswa ale jwenn li pita nan dosye « Telechajman » nan esplorate fichye a.\n\nFè atansyon ak sa ou telechaje. Rekipere fichye sèlman depi sou sit ou fè konfyans. Pran prekosyon ak bouton « Telechaje » ki twò vizib epi k ap klete sou kèk paj : pafwa se fo piblisite ki enstale pwogram endezirab. Gade byen non fichye a ak ekstansyon li anvan ou louvri l.\n\nGen kèk ekstansyon ki mande yon atansyon patikilye. Yon fichye « .pdf » (dokiman), « .jpg » (imaj) oswa « .docx » (tèks) jeneralman san danje. Men, yon fichye « .exe » enstale yon pwogram : louvri l sèlman si ou sèten kote l soti. Si ou gen dout, pa louvri l epi efase l.",
            en: "\"Download\" means copying a file from the Internet onto your computer: a PDF invoice, a photo, a form to fill in. When you click a \"Download\" button or a file link, the browser fetches the file and automatically puts it in the \"Downloads\" folder.\n\nDuring the download, a small bar shows the progress, often at the bottom or top right of the browser. Once finished, you can click the file to open it directly, or go find it later in the \"Downloads\" folder of the file explorer.\n\nBe careful with what you download. Only get files from trusted sites. Be wary of very flashy, blinking \"Download\" buttons on some pages: they are sometimes fake ads that install unwanted programs. Look carefully at the file's name and extension before opening it.\n\nSome extensions call for special attention. A \".pdf\" file (document), \".jpg\" (image) or \".docx\" (text) is generally safe. On the other hand, an \".exe\" file installs a program: open it only if you are certain of its source. When in doubt, do not open it and delete it.",
            es: "«Descargar» significa copiar un archivo desde Internet a tu computadora: una factura en PDF, una foto, un formulario para rellenar. Cuando haces clic en un botón «Descargar» o en un enlace de archivo, el navegador recupera el archivo y lo guarda automáticamente en la carpeta «Descargas».\n\nDurante la descarga, una pequeña barra muestra el avance, a menudo abajo o arriba a la derecha del navegador. Una vez terminada, puedes hacer clic en el archivo para abrirlo directamente, o ir a buscarlo más tarde en la carpeta «Descargas» del explorador de archivos.\n\nTen cuidado con lo que descargas. Recupera archivos solo desde sitios de confianza. Desconfía de los botones «Descargar» muy llamativos y parpadeantes en algunas páginas: a veces son publicidad falsa que instala programas no deseados. Mira bien el nombre del archivo y su extensión antes de abrirlo.\n\nAlgunas extensiones requieren una atención especial. Un archivo «.pdf» (documento), «.jpg» (imagen) o «.docx» (texto) generalmente es seguro. En cambio, un archivo «.exe» instala un programa: ábrelo solo si estás seguro de su procedencia. En caso de duda, no lo abras y elimínalo.",
          },
          keyPoints: {
            fr: ["Télécharger = copier un fichier d'Internet vers l'ordinateur", "Les fichiers vont dans le dossier « Téléchargements »", "Ne télécharge que depuis des sites de confiance", "Prudence avec les fichiers .exe ; .pdf/.jpg/.docx sont plus sûrs"],
            ht: ["Telechaje = kopye yon fichye depi entènèt vè òdinatè a", "Fichye yo ale nan dosye « Telechajman » an", "Telechaje sèlman depi sou sit ou fè konfyans", "Prekosyon ak fichye .exe ; .pdf/.jpg/.docx pi an sekirite"],
            en: ["Download = copy a file from the Internet to the computer", "Files go into the \"Downloads\" folder", "Download only from trusted sites", "Caution with .exe files; .pdf/.jpg/.docx are safer"],
            es: ["Descargar = copiar un archivo de Internet a la computadora", "Los archivos van a la carpeta «Descargas»", "Descarga solo desde sitios de confianza", "Cuidado con los archivos .exe; .pdf/.jpg/.docx son más seguros"],
          },
          exercise: {
            fr: "Sur un site officiel de confiance, trouve un document à télécharger (par exemple un formulaire administratif en PDF) et clique sur son bouton « Télécharger ». Observe la barre de progression. Une fois terminé, ouvre l'explorateur de fichiers, va dans le dossier « Téléchargements » et retrouve ton fichier. Lis son nom et son extension, puis ouvre-le pour vérifier que c'est bien un PDF.",
            ht: "Sou yon sit ofisyèl ou fè konfyans, jwenn yon dokiman pou telechaje (pa egzanp yon fòmilè administratif an PDF) epi klike sou bouton « Telechaje » li. Obsève ba pwogresyon an. Yon fwa fini, louvri esplorate fichye a, ale nan dosye « Telechajman » an epi jwenn fichye ou. Li non li ak ekstansyon li, apre louvri l pou verifye se byen yon PDF.",
            en: "On a trusted official site, find a document to download (for example an administrative form in PDF) and click its \"Download\" button. Watch the progress bar. Once finished, open the file explorer, go to the \"Downloads\" folder and find your file. Read its name and extension, then open it to check that it is indeed a PDF.",
            es: "En un sitio oficial de confianza, encuentra un documento para descargar (por ejemplo un formulario administrativo en PDF) y haz clic en su botón «Descargar». Observa la barra de progreso. Una vez terminada, abre el explorador de archivos, ve a la carpeta «Descargas» y encuentra tu archivo. Lee su nombre y su extensión, luego ábrelo para comprobar que es efectivamente un PDF.",
          },
        },
      ],
    },
    {
      title: { fr: "Communiquer et agir en ligne", ht: "Kominike epi aji sou entènèt", en: "Communicating and acting online", es: "Comunicarse y actuar en línea" },
      lessons: [
        {
          slug: "envoyer-un-courriel",
          title: { fr: "Créer et envoyer un courriel", ht: "Kreye epi voye yon imèl", en: "Creating and sending an email", es: "Crear y enviar un correo electrónico" },
          videoId: "",
          content: {
            fr: "Le courriel (ou e-mail) est comme une lettre envoyée par Internet, qui arrive en quelques secondes. Pour en envoyer, il faut d'abord une « adresse de courriel », par exemple prenom.nom@gmail.com. Elle se compose de ton nom, du signe « @ » (arobase) et du nom du service (gmail.com, yahoo.com…).\n\nUne fois connecté à ta boîte de courriel, clique sur le bouton « Nouveau message » (ou « Écrire »). Une fenêtre s'ouvre avec plusieurs cases. Dans « À », tape l'adresse complète du destinataire, sans faute : une seule lettre erronée et le message n'arrivera pas. Dans « Objet », résume en quelques mots le sujet, par exemple « Demande de rendez-vous ».\n\nDans la grande zone en dessous, écris ton message comme dans un traitement de texte. Commence par une salutation (« Bonjour »), explique clairement ta demande, puis termine poliment (« Merci, cordialement ») en signant de ton nom. Relis-toi pour corriger les fautes avant d'envoyer.\n\nQuand tout est prêt, clique sur « Envoyer ». Le message part aussitôt. Tu peux aussi joindre un fichier (une photo, un document) en cliquant sur l'icône du trombone, puis en choisissant le fichier sur ton ordinateur. Les messages reçus, eux, apparaissent dans la « boîte de réception » : clique sur l'un d'eux pour le lire, et sur « Répondre » pour renvoyer une réponse.",
            ht: "Imèl (oswa e-mail) se tankou yon lèt ou voye pa Entènèt, ki rive nan kèk segonn. Pou voye youn, fòk ou gen anvan yon « adrès imèl », pa egzanp prenon.non@gmail.com. Li konpoze ak non ou, siy « @ » (awobas) ak non sèvis la (gmail.com, yahoo.com…).\n\nYon fwa ou konekte nan bwat imèl ou, klike sou bouton « Nouvo mesaj » (oswa « Ekri »). Yon fenèt louvri ak plizyè kaz. Nan « À », tape adrès konplè moun w ap voye a, san fot : yon sèl lèt ki mal epi mesaj la p ap rive. Nan « Sijè », rezime an kèk mo sa l ap pale de li, pa egzanp « Demann yon randevou ».\n\nNan gwo zòn ki anba a, ekri mesaj ou tankou nan yon pwogram pou ekri tèks. Kòmanse ak yon salitasyon (« Bonjou »), eksplike demann ou klèman, apre fini avèk politès (« Mèsi, kòdyalman ») epi siyen non ou. Reli tèt ou pou korije fot yo anvan ou voye.\n\nLè tout bagay pare, klike sou « Voye ». Mesaj la pati lapoula. Ou ka tou tache yon fichye (yon foto, yon dokiman) lè w klike sou ikòn tronbòn nan, apre chwazi fichye a sou òdinatè ou. Mesaj ou resevwa yo parèt nan « bwat resepsyon » an : klike sou youn ladan yo pou li l, epi sou « Reponn » pou voye yon repons.",
            en: "Email is like a letter sent over the Internet, arriving in a few seconds. To send one, you first need an \"email address,\" for example firstname.lastname@gmail.com. It is made of your name, the \"@\" sign, and the service name (gmail.com, yahoo.com…).\n\nOnce logged into your mailbox, click the \"New message\" button (or \"Compose\"). A window opens with several boxes. In \"To,\" type the recipient's full address, without error: a single wrong letter and the message will not arrive. In \"Subject,\" sum up the topic in a few words, for example \"Appointment request.\"\n\nIn the large area below, write your message as in a word processor. Start with a greeting (\"Hello\"), explain your request clearly, then end politely (\"Thank you, best regards\") and sign with your name. Reread yourself to fix mistakes before sending.\n\nWhen everything is ready, click \"Send.\" The message leaves right away. You can also attach a file (a photo, a document) by clicking the paperclip icon, then choosing the file on your computer. Received messages appear in the \"inbox\": click one to read it, and \"Reply\" to send an answer back.",
            es: "El correo electrónico (o e-mail) es como una carta enviada por Internet, que llega en pocos segundos. Para enviar uno, primero hace falta una «dirección de correo», por ejemplo nombre.apellido@gmail.com. Se compone de tu nombre, el signo «@» (arroba) y el nombre del servicio (gmail.com, yahoo.com…).\n\nUna vez conectado a tu buzón, haz clic en el botón «Nuevo mensaje» (o «Redactar»). Se abre una ventana con varias casillas. En «Para», escribe la dirección completa del destinatario, sin error: una sola letra equivocada y el mensaje no llegará. En «Asunto», resume en pocas palabras el tema, por ejemplo «Solicitud de cita».\n\nEn la gran zona de abajo, escribe tu mensaje como en un procesador de textos. Empieza con un saludo («Hola»), explica claramente tu petición, luego termina con cortesía («Gracias, un saludo») y firma con tu nombre. Reléete para corregir los errores antes de enviar.\n\nCuando todo esté listo, haz clic en «Enviar». El mensaje sale enseguida. También puedes adjuntar un archivo (una foto, un documento) haciendo clic en el icono del clip, luego eligiendo el archivo en tu computadora. Los mensajes recibidos aparecen en la «bandeja de entrada»: haz clic en uno para leerlo, y en «Responder» para enviar una respuesta.",
          },
          keyPoints: {
            fr: ["Une adresse de courriel : nom + @ + service (ex. gmail.com)", "« Nouveau message » : remplir « À », « Objet » et le texte", "Saluer, expliquer, remercier, signer, puis « Envoyer »", "Le trombone joint un fichier ; « Répondre » renvoie une réponse"],
            ht: ["Yon adrès imèl : non + @ + sèvis (egz. gmail.com)", "« Nouvo mesaj » : ranpli « À », « Sijè » ak tèks la", "Salye, eksplike, di mèsi, siyen, apre « Voye »", "Tronbòn nan tache yon fichye ; « Reponn » voye yon repons"],
            en: ["An email address: name + @ + service (e.g. gmail.com)", "\"New message\": fill \"To,\" \"Subject\" and the text", "Greet, explain, thank, sign, then \"Send\"", "The paperclip attaches a file; \"Reply\" sends an answer"],
            es: ["Una dirección de correo: nombre + @ + servicio (ej. gmail.com)", "«Nuevo mensaje»: rellenar «Para», «Asunto» y el texto", "Saludar, explicar, agradecer, firmar, luego «Enviar»", "El clip adjunta un archivo; «Responder» envía una respuesta"],
          },
          exercise: {
            fr: "Connecte-toi à ta boîte de courriel (ou crée-en une gratuitement). Clique sur « Nouveau message ». Dans « À », tape ta propre adresse pour t'envoyer un message à toi-même. Mets pour objet « Mon premier courriel », écris un court texte avec une salutation et une signature, puis clique sur « Envoyer ». Va enfin dans la boîte de réception pour vérifier qu'il est bien arrivé.",
            ht: "Konekte nan bwat imèl ou (oswa kreye youn gratis). Klike sou « Nouvo mesaj ». Nan « À », tape pwòp adrès ou pou voye yon mesaj ba tèt ou. Mete kòm sijè « Premye imèl mwen », ekri yon ti tèks ak yon salitasyon epi yon siyati, apre klike sou « Voye ». Anfen, ale nan bwat resepsyon an pou verifye li byen rive.",
            en: "Log into your mailbox (or create one for free). Click \"New message.\" In \"To,\" type your own address to send yourself a message. Put \"My first email\" as the subject, write a short text with a greeting and a signature, then click \"Send.\" Finally, go to the inbox to check that it has arrived.",
            es: "Conéctate a tu buzón de correo (o crea uno gratis). Haz clic en «Nuevo mensaje». En «Para», escribe tu propia dirección para enviarte un mensaje a ti mismo. Pon como asunto «Mi primer correo», escribe un texto corto con un saludo y una firma, luego haz clic en «Enviar». Por último, ve a la bandeja de entrada para comprobar que ha llegado.",
          },
        },
        {
          slug: "remplir-un-formulaire",
          title: { fr: "Remplir un formulaire en ligne", ht: "Ranpli yon fòmilè sou entènèt", en: "Filling in an online form", es: "Rellenar un formulario en línea" },
          videoId: "",
          content: {
            fr: "Beaucoup de démarches se font aujourd'hui par des « formulaires » sur Internet : s'inscrire à un service, prendre un rendez-vous, faire une demande. Un formulaire est une page où l'on tape des informations dans des cases appelées « champs ». Tu cliques dans un champ pour y placer le curseur, puis tu écris au clavier.\n\nPour passer d'un champ au suivant, clique dedans avec la souris, ou appuie sur la touche « Tabulation » (Tab) qui saute automatiquement au champ suivant. Certains champs sont obligatoires, souvent marqués d'une étoile (*) : le formulaire refusera d'être envoyé s'ils sont vides.\n\nIl existe plusieurs types de champs. La case de texte reçoit un nom ou une adresse. La « liste déroulante » propose des choix quand tu cliques dessus (par exemple ton pays). La « case à cocher » se coche d'un clic pour dire oui. Les « boutons ronds » (options) te font choisir une seule réponse parmi plusieurs.\n\nAvant d'envoyer, relis chaque champ avec attention, surtout ton nom, ton adresse et ton numéro. Une erreur peut retarder ta démarche. Puis clique sur le bouton « Envoyer » ou « Valider » en bas du formulaire. Un message de confirmation apparaît alors : c'est la preuve que tes informations ont bien été reçues.",
            ht: "Anpil demach fèt jodi a pa « fòmilè » sou Entènèt : enskri nan yon sèvis, pran yon randevou, fè yon demann. Yon fòmilè se yon paj kote ou tape enfòmasyon nan kaz yo rele « chan ». Ou klike nan yon chan pou mete kisè a ladan, apre ou ekri ak klavye a.\n\nPou pase soti nan yon chan ale nan pwochen an, klike ladan l ak sourit la, oswa peze touch « Tabilasyon » (Tab) ki sote otomatikman nan chan ki vin apre a. Gen kèk chan ki obligatwa, souvan make ak yon zetwal (*) : fòmilè a ap refize voye si yo vid.\n\nGen plizyè kalite chan. Kaz tèks la resevwa yon non oswa yon adrès. « Lis dewoulan » an pwopoze chwa lè w klike sou li (pa egzanp peyi ou). « Kaz pou tcheke » a tcheke ak yon klik pou di wi. « Bouton won » yo (opsyon) fè w chwazi yon sèl repons pami plizyè.\n\nAnvan ou voye, reli chak chan ak atansyon, sitou non ou, adrès ou ak nimewo ou. Yon erè ka retade demach ou. Apre klike sou bouton « Voye » oswa « Valide » anba fòmilè a. Yon mesaj konfimasyon parèt lè sa : se prèv enfòmasyon ou yo byen resevwa.",
            en: "Many procedures are done today through \"forms\" on the Internet: signing up for a service, booking an appointment, making a request. A form is a page where you type information into boxes called \"fields.\" You click in a field to place the cursor there, then you type on the keyboard.\n\nTo move from one field to the next, click in it with the mouse, or press the \"Tab\" key which jumps automatically to the next field. Some fields are required, often marked with a star (*): the form will refuse to be sent if they are empty.\n\nThere are several types of fields. The text box takes a name or an address. The \"drop-down list\" offers choices when you click it (for example your country). The \"checkbox\" is ticked with a click to say yes. The \"radio buttons\" (options) let you choose only one answer among several.\n\nBefore sending, reread each field carefully, especially your name, address and number. An error can delay your procedure. Then click the \"Send\" or \"Submit\" button at the bottom of the form. A confirmation message then appears: that is proof your information has been received.",
            es: "Hoy en día muchos trámites se hacen mediante «formularios» en Internet: inscribirse en un servicio, pedir una cita, hacer una solicitud. Un formulario es una página donde se escribe información en casillas llamadas «campos». Haces clic en un campo para colocar el cursor ahí, luego escribes con el teclado.\n\nPara pasar de un campo al siguiente, haz clic en él con el ratón, o pulsa la tecla «Tabulación» (Tab) que salta automáticamente al siguiente campo. Algunos campos son obligatorios, a menudo marcados con una estrella (*): el formulario se negará a enviarse si están vacíos.\n\nExisten varios tipos de campos. La casilla de texto recibe un nombre o una dirección. La «lista desplegable» ofrece opciones cuando haces clic en ella (por ejemplo tu país). La «casilla de verificación» se marca con un clic para decir sí. Los «botones redondos» (opciones) te hacen elegir una sola respuesta entre varias.\n\nAntes de enviar, relee cada campo con atención, sobre todo tu nombre, tu dirección y tu número. Un error puede retrasar tu trámite. Luego haz clic en el botón «Enviar» o «Validar» al final del formulario. Aparece entonces un mensaje de confirmación: es la prueba de que tu información se ha recibido bien.",
          },
          keyPoints: {
            fr: ["Un formulaire = des cases (« champs ») à remplir au clavier", "La touche Tab passe au champ suivant", "Les champs obligatoires sont marqués d'une étoile (*)", "Relire, puis « Envoyer » ; un message confirme la réception"],
            ht: ["Yon fòmilè = kaz (« chan ») pou ranpli ak klavye a", "Touch Tab la pase nan chan ki vin apre a", "Chan obligatwa yo make ak yon zetwal (*)", "Reli, apre « Voye » ; yon mesaj konfime resepsyon an"],
            en: ["A form = boxes (\"fields\") to fill in with the keyboard", "The Tab key moves to the next field", "Required fields are marked with a star (*)", "Reread, then \"Send\"; a message confirms receipt"],
            es: ["Un formulario = casillas («campos») para rellenar con el teclado", "La tecla Tab pasa al campo siguiente", "Los campos obligatorios están marcados con una estrella (*)", "Releer, luego «Enviar»; un mensaje confirma la recepción"],
          },
          exercise: {
            fr: "Cherche un formulaire simple en ligne (par exemple un formulaire de contact d'un site de confiance, ou un formulaire d'inscription à une lettre d'information). Clique dans le premier champ et remplis-le, puis utilise la touche Tab pour passer au champ suivant. Repère les champs marqués d'une étoile (*) et remplis-les. Relis tout avant de décider d'envoyer ou non.",
            ht: "Chèche yon fòmilè senp sou entènèt (pa egzanp yon fòmilè kontak yon sit ou fè konfyans, oswa yon fòmilè enskripsyon nan yon bilten enfòmasyon). Klike nan premye chan an epi ranpli l, apre itilize touch Tab la pou pase nan chan ki vin apre a. Repere chan ki make ak yon zetwal (*) yo epi ranpli yo. Reli tout anvan ou deside voye oswa non.",
            en: "Look for a simple form online (for example a contact form on a trusted site, or a newsletter sign-up form). Click in the first field and fill it in, then use the Tab key to move to the next field. Spot the fields marked with a star (*) and fill them. Reread everything before deciding whether or not to send.",
            es: "Busca un formulario sencillo en línea (por ejemplo un formulario de contacto de un sitio de confianza, o un formulario de suscripción a un boletín). Haz clic en el primer campo y rellénalo, luego usa la tecla Tab para pasar al siguiente campo. Localiza los campos marcados con una estrella (*) y rellénalos. Relee todo antes de decidir si enviar o no.",
          },
        },
        {
          slug: "reseaux-sociaux-appels-video",
          title: { fr: "Réseaux sociaux et appels vidéo", ht: "Rezo sosyal ak apèl videyo", en: "Social media and video calls", es: "Redes sociales y videollamadas" },
          videoId: "",
          content: {
            fr: "Les « réseaux sociaux » (Facebook, WhatsApp, Instagram) et les applications d'appel (WhatsApp, Zoom) servent à rester en contact avec la famille et les amis, même loin. Tu peux y envoyer des messages écrits, des photos, des nouvelles, et voir celles des autres. Pour commencer, il faut créer un compte avec ton nom, ton numéro ou ton adresse de courriel, et un mot de passe.\n\nSur ces applications, on écrit un message dans une case en bas, puis on appuie sur la flèche ou le bouton « Envoyer » pour l'expédier. Ton correspondant le reçoit aussitôt et peut te répondre. On peut aussi partager une photo en cliquant sur l'icône d'appareil photo ou de trombone, puis en la choisissant dans ton téléphone ou ton ordinateur.\n\nL'« appel vidéo » permet de se voir et de se parler en direct, comme une conversation en face à face. Choisis un contact, clique sur l'icône de caméra, et attends que la personne réponde. Vérifie avant que ta caméra et ton micro sont autorisés, et que ta connexion Internet est bonne pour une image nette.\n\nGarde toujours à l'esprit les règles de prudence. N'accepte pas d'inconnus qui te demandent en ami sans raison. Ne partage pas d'informations privées ni d'argent, même si le message vient d'un « ami » (son compte a pu être piraté). Réfléchis avant de publier une photo, car beaucoup de monde peut la voir. Utilisées avec bon sens, ces applications rapprochent les gens et rendent de grands services.",
            ht: "« Rezo sosyal » yo (Facebook, WhatsApp, Instagram) ak aplikasyon apèl yo (WhatsApp, Zoom) sèvi pou rete an kontak ak fanmi ak zanmi, menm lwen. Ou ka voye mesaj ekri, foto, nouvèl, epi wè sa lòt moun yo. Pou kòmanse, fòk ou kreye yon kont ak non ou, nimewo ou oswa adrès imèl ou, epi yon modpas.\n\nSou aplikasyon sa yo, ou ekri yon mesaj nan yon kaz anba, apre ou peze flèch la oswa bouton « Voye » a pou voye l. Moun w ap ekri a resevwa l lapoula epi li ka reponn ou. Ou ka tou pataje yon foto lè w klike sou ikòn aparèy foto oswa tronbòn nan, apre chwazi l nan telefòn ou oswa òdinatè ou.\n\n« Apèl videyo » a pèmèt moun wè youn lòt epi pale an dirèk, tankou yon konvèsasyon fasafas. Chwazi yon kontak, klike sou ikòn kamera a, epi tann moun nan reponn. Verifye anvan kamera ou ak mikwo ou otorize, epi koneksyon Entènèt ou bon pou yon imaj klè.\n\nToujou kenbe nan tèt ou règ prekosyon yo. Pa aksepte enkoni ki mande w kòm zanmi san rezon. Pa pataje enfòmasyon prive ni lajan, menm si mesaj la sot nan yon « zanmi » (kont li ka te pirate). Reflechi anvan ou pibliye yon foto, paske anpil moun ka wè l. Lè ou itilize yo ak bon sans, aplikasyon sa yo rapwoche moun epi yo rann gwo sèvis.",
            en: "\"Social media\" (Facebook, WhatsApp, Instagram) and calling apps (WhatsApp, Zoom) help you stay in touch with family and friends, even far away. You can send written messages, photos, news, and see other people's. To start, you must create an account with your name, your number or email address, and a password.\n\nOn these apps, you write a message in a box at the bottom, then press the arrow or the \"Send\" button to send it. Your contact receives it right away and can reply. You can also share a photo by clicking the camera or paperclip icon, then choosing it on your phone or computer.\n\nThe \"video call\" lets you see and talk to each other live, like a face-to-face conversation. Choose a contact, click the camera icon, and wait for the person to answer. Check beforehand that your camera and microphone are allowed, and that your Internet connection is good for a clear picture.\n\nAlways keep the safety rules in mind. Do not accept strangers who send you a friend request for no reason. Do not share private information or money, even if the message comes from a \"friend\" (their account may have been hacked). Think before posting a photo, because many people can see it. Used with common sense, these apps bring people closer and are of great help.",
            es: "Las «redes sociales» (Facebook, WhatsApp, Instagram) y las aplicaciones de llamada (WhatsApp, Zoom) sirven para mantenerse en contacto con la familia y los amigos, aunque estén lejos. Puedes enviar mensajes escritos, fotos, noticias, y ver las de los demás. Para empezar, hay que crear una cuenta con tu nombre, tu número o tu dirección de correo, y una contraseña.\n\nEn estas aplicaciones, escribes un mensaje en una casilla abajo, luego pulsas la flecha o el botón «Enviar» para enviarlo. Tu contacto lo recibe enseguida y puede responderte. También puedes compartir una foto haciendo clic en el icono de cámara o de clip, luego eligiéndola en tu teléfono o computadora.\n\nLa «videollamada» permite verse y hablar en directo, como una conversación cara a cara. Elige un contacto, haz clic en el icono de cámara, y espera a que la persona responda. Comprueba antes que tu cámara y tu micrófono están permitidos, y que tu conexión a Internet es buena para una imagen nítida.\n\nTen siempre presentes las reglas de prudencia. No aceptes a desconocidos que te agregan como amigo sin razón. No compartas información privada ni dinero, aunque el mensaje venga de un «amigo» (su cuenta pudo ser pirateada). Piensa antes de publicar una foto, porque mucha gente puede verla. Usadas con sentido común, estas aplicaciones acercan a las personas y prestan grandes servicios.",
          },
          keyPoints: {
            fr: ["Réseaux et applications d'appel gardent le contact avec les proches", "Écrire dans la case, puis « Envoyer » ; le trombone partage une photo", "L'appel vidéo demande caméra, micro autorisés et bonne connexion", "Prudence : ne pas accepter d'inconnus ni partager argent/données"],
            ht: ["Rezo ak aplikasyon apèl kenbe kontak ak moun pre ou yo", "Ekri nan kaz la, apre « Voye » ; tronbòn nan pataje yon foto", "Apèl videyo mande kamera, mikwo otorize ak bon koneksyon", "Prekosyon : pa aksepte enkoni ni pataje lajan/done"],
            en: ["Social and calling apps keep contact with loved ones", "Write in the box, then \"Send\"; the paperclip shares a photo", "Video call needs camera, mic allowed and a good connection", "Caution: don't accept strangers or share money/data"],
            es: ["Redes y apps de llamada mantienen el contacto con los seres queridos", "Escribir en la casilla, luego «Enviar»; el clip comparte una foto", "La videollamada necesita cámara, micrófono permitidos y buena conexión", "Prudencia: no aceptar desconocidos ni compartir dinero/datos"],
          },
          exercise: {
            fr: "Si tu utilises WhatsApp ou une application similaire, choisis un contact de confiance (un membre de ta famille). Écris-lui un court message dans la case du bas et envoie-le avec la flèche. Ensuite, partage-lui une photo en cliquant sur l'icône de trombone ou d'appareil photo. Enfin, si la personne est d'accord, lance un appel vidéo avec l'icône de caméra et vérifie que tu la vois et l'entends bien.",
            ht: "Si ou itilize WhatsApp oswa yon aplikasyon menm jan, chwazi yon kontak ou fè konfyans (yon manm fanmi ou). Ekri l yon ti mesaj nan kaz anba a epi voye l ak flèch la. Apre, pataje yon foto avè l lè w klike sou ikòn tronbòn oswa aparèy foto a. Anfen, si moun nan dakò, lanse yon apèl videyo ak ikòn kamera a epi verifye ou wè l epi ou tande l byen.",
            en: "If you use WhatsApp or a similar app, choose a trusted contact (a family member). Write them a short message in the box at the bottom and send it with the arrow. Then share a photo with them by clicking the paperclip or camera icon. Finally, if the person agrees, start a video call with the camera icon and check that you see and hear them well.",
            es: "Si usas WhatsApp o una aplicación similar, elige un contacto de confianza (un familiar). Escríbele un mensaje corto en la casilla de abajo y envíalo con la flecha. Luego comparte con él una foto haciendo clic en el icono de clip o de cámara. Por último, si la persona está de acuerdo, inicia una videollamada con el icono de cámara y comprueba que la ves y la oyes bien.",
          },
        },
      ],
    },
  ],
};

export default internet;
