import { CourseContent } from "./types";

const musique: CourseContent = {
  slug: "musique",
  intro: {
    fr: "Servir Dieu par la musique et la louange : conduire le peuple dans l'adoration avec un cœur pur, l'excellence et l'onction du Saint-Esprit.",
    ht: "Sèvi Bondye ak mizik ak louwanj : mennen pèp la nan adorasyon ak yon kè pwòp, eksèlans ak onksyon Sentespri a.",
    en: "Serving God through music and worship: leading the people in adoration with a pure heart, excellence and the anointing of the Holy Spirit.",
    es: "Servir a Dios por medio de la música y la alabanza: guiar al pueblo en la adoración con un corazón puro, excelencia y la unción del Espíritu Santo.",
  },
  modules: [
    {
      title: { fr: "Le cœur de l'adorateur", ht: "Kè adoratè a", en: "The heart of the worshiper", es: "El corazón del adorador" },
      lessons: [
        {
          slug: "adoration-en-esprit-verite",
          title: { fr: "Adorer en esprit et en vérité", ht: "Adore an lespri ak an verite", en: "Worshiping in spirit and truth", es: "Adorar en espíritu y en verdad" },
          videoId: "",
          content: {
            fr: "L'adoration ne commence pas sur une scène, mais dans le cœur. Jésus a dit à la Samaritaine : « Les vrais adorateurs adoreront le Père en esprit et en vérité ; car ce sont là les adorateurs que le Père demande. » (Jean 4.23) Dieu ne recherche pas d'abord de bons chanteurs, mais de vrais adorateurs.\n\nAdorer en esprit, c'est adorer avec tout son être, pas seulement avec les lèvres. Jésus a repris ceux qui « m'honorent des lèvres, mais leur cœur est éloigné de moi. » (Matthieu 15.8) L'adoration authentique jaillit d'une vie donnée à Dieu, pas d'une simple performance musicale.\n\nAdorer en vérité, c'est adorer selon ce que Dieu révèle de lui-même dans sa Parole, avec sincérité et sans faux-semblant. La musique est un moyen puissant, mais l'adoration véritable est un mode de vie : « Offrez vos corps comme un sacrifice vivant... c'est là votre culte raisonnable. » (Romains 12.1)\n\nCe qui touche le cœur de Dieu, ce n'est pas la beauté du son mais la sincérité de celui qui chante. « Dieu est esprit, et il faut que ceux qui l'adorent l'adorent en esprit et en vérité. » (Jean 4.24) Le plus humble croyant qui adore avec un cœur brisé et sincère offre à Dieu un culte plus agréable que le musicien le plus talentueux au cœur distrait. L'adoration commence dans le secret, avant de se manifester en public.",
            ht: "Adorasyon pa kòmanse sou yon sèn, men nan kè a. Jezi te di fanm Samari a : « Vrè adoratè yo ap adore Papa a an lespri ak an verite ; paske se adoratè konsa Papa a mande. » (Jan 4.23) Bondye pa chèche dabò bon chantè, men vrè adoratè.\n\nAdore an lespri, se adore ak tout tèt ou, se pa sèlman ak lèv ou. Jezi te reprimande sila yo ki « onore m ak lèv yo, men kè yo lwen mwen. » (Matye 15.8) Vrè adorasyon soti nan yon lavi ki bay Bondye, pa nan yon senp pèfòmans mizikal.\n\nAdore an verite, se adore selon sa Bondye revele de tèt li nan Pawòl li, ak sensèrite e san fè sanblan. Mizik se yon mwayen pisan, men vrè adorasyon se yon fason viv : « Ofri kò nou kòm yon sakrifis vivan... se sa ki kilt ki gen sans nou dwe bay. » (Women 12.1)\n\nSa ki touche kè Bondye, se pa bèlte son an men sensèrite moun k ap chante a. « Bondye se lespri, e fòk sila ki adore l yo adore l an lespri ak an verite. » (Jan 4.24) Kwayan ki pi enb ki adore ak yon kè brize e sensè ofri Bondye yon kilt ki pi agreyab pase mizisyen ki pi talantye ak yon kè distrè. Adorasyon kòmanse nan sekrè, anvan li manifeste an piblik.",
            en: "Worship does not begin on a stage, but in the heart. Jesus said to the Samaritan woman: \"True worshipers will worship the Father in spirit and truth, for they are the kind of worshipers the Father seeks.\" (John 4:23) God is not first looking for good singers, but for true worshipers.\n\nTo worship in spirit is to worship with your whole being, not just with your lips. Jesus rebuked those who \"honor me with their lips, but their hearts are far from me.\" (Matthew 15:8) Authentic worship springs from a life given to God, not from a mere musical performance.\n\nTo worship in truth is to worship according to what God reveals about himself in his Word, with sincerity and without pretense. Music is a powerful means, but true worship is a way of life: \"Offer your bodies as a living sacrifice... this is your true and proper worship.\" (Romans 12:1)\n\nWhat touches God's heart is not the beauty of the sound but the sincerity of the one who sings. \"God is spirit, and his worshipers must worship in the Spirit and in truth.\" (John 4:24) The humblest believer who worships with a broken and sincere heart offers God a more pleasing worship than the most talented musician with a distracted heart. Worship begins in secret, before it shows in public.",
            es: "La adoración no comienza en un escenario, sino en el corazón. Jesús dijo a la samaritana: «Los verdaderos adoradores adorarán al Padre en espíritu y en verdad; porque también el Padre tales adoradores busca.» (Juan 4:23) Dios no busca primero buenos cantantes, sino verdaderos adoradores.\n\nAdorar en espíritu es adorar con todo el ser, no solo con los labios. Jesús reprendió a los que «de labios me honra, mas su corazón está lejos de mí.» (Mateo 15:8) La adoración auténtica brota de una vida entregada a Dios, no de una simple actuación musical.\n\nAdorar en verdad es adorar según lo que Dios revela de sí mismo en su Palabra, con sinceridad y sin fingimiento. La música es un medio poderoso, pero la verdadera adoración es un modo de vida: «Presentad vuestros cuerpos en sacrificio vivo... que es vuestro culto racional.» (Romanos 12:1)\n\nLo que toca el corazón de Dios no es la belleza del sonido sino la sinceridad del que canta. «Dios es Espíritu; y los que le adoran, en espíritu y en verdad es necesario que adoren.» (Juan 4:24) El creyente más humilde que adora con un corazón quebrantado y sincero ofrece a Dios un culto más agradable que el músico más talentoso con un corazón distraído. La adoración comienza en lo secreto, antes de manifestarse en público.",
          },
          keyPoints: {
            fr: ["Dieu cherche de vrais adorateurs, pas de bons chanteurs (Jean 4.23)", "Adorer avec le cœur, pas seulement les lèvres (Mt 15.8)", "L'adoration est un mode de vie (Romains 12.1)", "La sincérité touche Dieu plus que la beauté du son (Jean 4.24)"],
            ht: ["Bondye chèche vrè adoratè, pa bon chantè (Jan 4.23)", "Adore ak kè, pa sèlman lèv (Matye 15.8)", "Adorasyon se yon fason viv (Women 12.1)", "Sensèrite touche Bondye plis pase bèlte son (Jan 4.24)"],
            en: ["God seeks true worshipers, not good singers (John 4:23)", "Worship with the heart, not just the lips (Mt 15:8)", "Worship is a way of life (Romans 12:1)", "Sincerity touches God more than beautiful sound (John 4:24)"],
            es: ["Dios busca verdaderos adoradores, no buenos cantantes (Juan 4:23)", "Adorar con el corazón, no solo los labios (Mt 15:8)", "La adoración es un modo de vida (Romanos 12:1)", "La sinceridad toca a Dios más que el bello sonido (Juan 4:24)"],
          },
          exercise: {
            fr: "Avant votre prochaine participation à la louange, prenez dix minutes seul avec Dieu, sans instrument, pour l'adorer simplement du cœur. Demandez-vous : « Est-ce que je chante pour être vu, ou pour glorifier Dieu ? » Notez une chose dans votre vie quotidienne que vous voulez offrir à Dieu comme un « sacrifice vivant ».",
            ht: "Anvan pwochen patisipasyon w nan louwanj, pran dis minit poukont ou ak Bondye, san enstriman, pou adore l senpleman ak kè w. Mande tèt ou : « Èske m ap chante pou moun wè m, oswa pou bay Bondye glwa ? » Note yon bagay nan lavi chak jou w ou vle ofri Bondye kòm yon « sakrifis vivan ».",
            en: "Before your next time leading or joining worship, take ten minutes alone with God, without an instrument, to worship him simply from the heart. Ask yourself: \"Am I singing to be seen, or to glorify God?\" Note one thing in your daily life that you want to offer to God as a \"living sacrifice.\"",
            es: "Antes de tu próxima participación en la alabanza, toma diez minutos a solas con Dios, sin instrumento, para adorarle simplemente desde el corazón. Pregúntate: «¿Canto para ser visto, o para glorificar a Dios?» Anota una cosa de tu vida diaria que quieres ofrecer a Dios como un «sacrificio vivo».",
          },
          verse: "Jean 4.23-24",
        },
        {
          slug: "coeur-pur-devant-dieu",
          title: { fr: "Un cœur pur devant Dieu", ht: "Yon kè pwòp devan Bondye", en: "A pure heart before God", es: "Un corazón puro delante de Dios" },
          videoId: "",
          content: {
            fr: "Le talent peut ouvrir des portes, mais seul le caractère y fait demeurer. David, le plus grand musicien de la Bible, était « un homme selon le cœur de Dieu » (1 Samuel 13.14) avant d'être un grand harpiste. Dieu regarde d'abord le cœur : « L'Éternel regarde au cœur. » (1 Samuel 16.7)\n\nCelui qui conduit la louange se tient devant Dieu au nom du peuple ; sa vie ne peut contredire son chant. Le psalmiste demande : « Qui pourra monter à la montagne de l'Éternel ? Celui qui a les mains innocentes et le cœur pur. » (Psaume 24.3-4) Servir sur l'estrade exige de veiller dans le secret.\n\nLa musique chrétienne n'est pas un spectacle pour se faire admirer, mais une offrande pour glorifier Dieu. L'orgueil est le grand piège du musicien : Lucifer lui-même était lié à la musique avant sa chute (Ézéchiel 28). Reste humble, car l'onction repose sur ceux qui cherchent la gloire de Dieu et non la leur.\n\nQuand le péché ou la souillure entrent dans le cœur, la prière du psalmiste doit devenir la nôtre : « Ô Dieu, crée en moi un cœur pur, renouvelle en moi un esprit bien disposé. » (Psaume 51.12) Dieu ne demande pas la perfection, mais un cœur honnête, prompt à se repentir. Le musicien qui vit dans la lumière, transparent devant Dieu et devant ses frères, portera un fruit durable que le talent seul ne peut produire.",
            ht: "Talan ka louvri pòt, men se karaktè sèlman ki fè w rete. David, pi gwo mizisyen nan Bib la, te « yon nonm selon kè Bondye » (1 Samyèl 13.14) anvan li te yon gwo jwè ap. Bondye gade kè a dabò : « Senyè a gade nan kè. » (1 Samyèl 16.7)\n\nMoun ki mennen louwanj kanpe devan Bondye nan non pèp la ; lavi l pa ka kontredi chan l. Sòm nan mande : « Ki moun ki ka moute sou mòn Senyè a ? Se moun ki gen men inosan ak kè pwòp. » (Sòm 24.3-4) Sèvi sou estrad la egzije veye nan sekrè.\n\nMizik kretyen se pa yon espektak pou fè moun admire w, men yon ofrann pou bay Bondye glwa. Ògèy se gwo pyèj mizisyen an : Lisifè menm te lye ak mizik anvan chit li (Ezekyèl 28). Rete enb, paske onksyon an repoze sou moun k ap chèche glwa Bondye e non pa glwa pa yo.\n\nLè peche oswa salte antre nan kè a, lapriyè sòm nan dwe vin pa nou : « O Bondye, kreye nan mwen yon kè pwòp, renouvle nan mwen yon lespri byen dispoze. » (Sòm 51.12) Bondye pa mande pèfeksyon, men yon kè onèt, prese pou repanti. Mizisyen ki viv nan limyè a, transparan devan Bondye e devan frè l yo, ap pote yon fwi ki dire talan sèlman pa ka pwodui.",
            en: "Talent can open doors, but only character keeps you there. David, the greatest musician in the Bible, was \"a man after God's own heart\" (1 Samuel 13:14) before he was a great harpist. God looks at the heart first: \"The Lord looks at the heart.\" (1 Samuel 16:7)\n\nThe one who leads worship stands before God on behalf of the people; his life cannot contradict his song. The psalmist asks: \"Who may ascend the mountain of the Lord? The one who has clean hands and a pure heart.\" (Psalm 24:3-4) Serving on the platform requires watching in secret.\n\nChristian music is not a show to be admired, but an offering to glorify God. Pride is the musician's great trap: Lucifer himself was associated with music before his fall (Ezekiel 28). Stay humble, for the anointing rests on those who seek God's glory and not their own.\n\nWhen sin or defilement enters the heart, the psalmist's prayer must become ours: \"Create in me a pure heart, O God, and renew a steadfast spirit within me.\" (Psalm 51:10) God does not ask for perfection, but for an honest heart, quick to repent. The musician who lives in the light, transparent before God and before his brothers, will bear lasting fruit that talent alone cannot produce.",
            es: "El talento puede abrir puertas, pero solo el carácter te mantiene allí. David, el mayor músico de la Biblia, era «un varón conforme a su corazón» (1 Samuel 13:14) antes de ser un gran arpista. Dios mira primero el corazón: «Jehová mira el corazón.» (1 Samuel 16:7)\n\nEl que dirige la alabanza se para delante de Dios en nombre del pueblo; su vida no puede contradecir su canto. El salmista pregunta: «¿Quién subirá al monte de Jehová? El limpio de manos y puro de corazón.» (Salmo 24:3-4) Servir en la plataforma exige velar en lo secreto.\n\nLa música cristiana no es un espectáculo para ser admirado, sino una ofrenda para glorificar a Dios. El orgullo es la gran trampa del músico: el mismo Lucifer estaba ligado a la música antes de su caída (Ezequiel 28). Mantente humilde, porque la unción reposa sobre los que buscan la gloria de Dios y no la suya.\n\nCuando el pecado o la impureza entran en el corazón, la oración del salmista debe volverse la nuestra: «Crea en mí, oh Dios, un corazón limpio, y renueva un espíritu recto dentro de mí.» (Salmo 51:10) Dios no pide perfección, sino un corazón honesto, pronto a arrepentirse. El músico que vive en la luz, transparente delante de Dios y de sus hermanos, dará un fruto duradero que el talento solo no puede producir.",
          },
          keyPoints: {
            fr: ["Dieu regarde le cœur avant le talent (1 Samuel 16.7)", "Mains innocentes et cœur pur pour servir (Psaume 24.4)", "L'orgueil est le grand piège du musicien : rester humble", "Un cœur pur se renouvelle par le repentir (Psaume 51.12)"],
            ht: ["Bondye gade kè anvan talan (1 Samyèl 16.7)", "Men inosan ak kè pwòp pou sèvi (Sòm 24.4)", "Ògèy se gwo pyèj mizisyen an : rete enb", "Yon kè pwòp renouvle ak repantans (Sòm 51.12)"],
            en: ["God looks at the heart before talent (1 Samuel 16:7)", "Clean hands and a pure heart to serve (Psalm 24:4)", "Pride is the musician's great trap: stay humble", "A pure heart is renewed through repentance (Psalm 51:10)"],
            es: ["Dios mira el corazón antes que el talento (1 Samuel 16:7)", "Manos limpias y corazón puro para servir (Salmo 24:4)", "El orgullo es la gran trampa del músico: ser humilde", "Un corazón puro se renueva con el arrepentimiento (Salmo 51:10)"],
          },
          exercise: {
            fr: "Faites un examen de conscience honnête devant Dieu : y a-t-il dans votre vie une zone d'ombre qui contredit ce que vous chantez sur scène ? Priez le Psaume 51 en votre nom, demandant à Dieu un cœur pur. Si nécessaire, ouvrez-vous à un frère de confiance pour marcher dans la lumière.",
            ht: "Fè yon egzamen konsyans onèt devan Bondye : èske gen nan lavi w yon zòn nwa ki kontredi sa w ap chante sou sèn ? Priye Sòm 51 nan non w, mande Bondye yon kè pwòp. Si nesesè, ouvri tèt ou bay yon frè konfyans pou mache nan limyè a.",
            en: "Do an honest self-examination before God: is there in your life an area of shadow that contradicts what you sing on stage? Pray Psalm 51 in your own name, asking God for a pure heart. If needed, open up to a trusted brother to walk in the light.",
            es: "Haz un examen de conciencia honesto delante de Dios: ¿hay en tu vida una zona de sombra que contradice lo que cantas en el escenario? Ora el Salmo 51 en tu nombre, pidiendo a Dios un corazón limpio. Si es necesario, ábrete a un hermano de confianza para caminar en la luz.",
          },
          verse: "1 Samuel 16.7",
        },
        {
          slug: "sacrifice-de-louange",
          title: { fr: "Le sacrifice de louange", ht: "Sakrifis louwanj lan", en: "The sacrifice of praise", es: "El sacrificio de alabanza" },
          videoId: "",
          content: {
            fr: "Il y a une louange qui coûte, et c'est celle qui touche le plus profondément le cœur de Dieu. « Offrons sans cesse à Dieu un sacrifice de louange, c'est-à-dire le fruit de lèvres qui confessent son nom. » (Hébreux 13.15) Une louange est un sacrifice quand on la présente même dans la fatigue, la douleur ou l'épreuve.\n\nDavid comprenait ce principe : « Je ne présenterai pas à l'Éternel, mon Dieu, des holocaustes qui ne me coûtent rien. » (2 Samuel 24.24) Louer Dieu quand tout va bien est facile ; le louer quand le cœur est brisé est un véritable acte de foi. C'est dans ces moments que la louange devient une arme et un parfum agréable.\n\nJob, ayant tout perdu, se prosterna et adora : « L'Éternel a donné, et l'Éternel a ôté ; que le nom de l'Éternel soit béni ! » (Job 1.21) Une telle louange déclare que Dieu est digne, non pour ce qu'il donne, mais pour qui il est. Elle proclame notre confiance en lui au milieu des ténèbres.\n\nLe psalmiste décide de bénir Dieu quoi qu'il arrive : « Je bénirai l'Éternel en tout temps ; sa louange sera toujours dans ma bouche. » (Psaume 34.2) La louange n'est pas soumise aux circonstances ; c'est un choix de la volonté. Choisissez d'adorer Dieu dans toutes les saisons, et vous découvrirez que le sacrifice de louange ouvre le ciel au-dessus de votre vie.",
            ht: "Gen yon louwanj ki koute, e se li ki touche kè Bondye pi pwofon. « Ann ofri Bondye san sès yon sakrifis louwanj, sa vle di fwi lèv ki konfese non li. » (Ebre 13.15) Yon louwanj se yon sakrifis lè w prezante l menm nan fatig, doulè oswa eprèv.\n\nDavid te konprann prensip sa a : « Mwen p ap prezante Senyè a, Bondye m, olokòs ki pa koute m anyen. » (2 Samyèl 24.24) Louwe Bondye lè tout bagay ap mache byen fasil ; louwe l lè kè a brize se yon vrè zak lafwa. Se nan moman sa yo louwanj vin yon zam ak yon pafen agreyab.\n\nJòb, ki te pèdi tout bagay, te bese e adore : « Senyè a bay, e Senyè a wete ; se pou non Senyè a beni ! » (Jòb 1.21) Yon louwanj konsa deklare Bondye diy, se pa pou sa li bay, men pou kiyès li ye. Li pwoklame konfyans nou nan li nan mitan tenèb.\n\nSòm nan deside beni Bondye kèlkeswa sa k rive : « M ap beni Senyè a tout tan ; louwanj li ap toujou nan bouch mwen. » (Sòm 34.2) Louwanj pa soumèt a sikonstans ; se yon chwa volonte. Chwazi adore Bondye nan tout sezon, e w ap dekouvri ke sakrifis louwanj lan louvri syèl la sou lavi w.",
            en: "There is a praise that costs, and it is the one that touches God's heart most deeply. \"Through Jesus, therefore, let us continually offer to God a sacrifice of praise—the fruit of lips that openly profess his name.\" (Hebrews 13:15) Praise becomes a sacrifice when we offer it even in weariness, pain or trial.\n\nDavid understood this principle: \"I will not sacrifice to the Lord my God burnt offerings that cost me nothing.\" (2 Samuel 24:24) Praising God when all is well is easy; praising him when the heart is broken is a true act of faith. It is in these moments that praise becomes a weapon and a pleasing fragrance.\n\nJob, having lost everything, fell to the ground and worshiped: \"The Lord gave and the Lord has taken away; may the name of the Lord be praised.\" (Job 1:21) Such praise declares that God is worthy, not for what he gives, but for who he is. It proclaims our trust in him in the midst of darkness.\n\nThe psalmist decides to bless God no matter what: \"I will extol the Lord at all times; his praise will always be on my lips.\" (Psalm 34:1) Praise is not subject to circumstances; it is a choice of the will. Choose to worship God in every season, and you will discover that the sacrifice of praise opens heaven over your life.",
            es: "Hay una alabanza que cuesta, y es la que toca más profundamente el corazón de Dios. «Ofrezcamos siempre a Dios, por medio de él, sacrificio de alabanza, es decir, fruto de labios que confiesan su nombre.» (Hebreos 13:15) Una alabanza es un sacrificio cuando se ofrece incluso en el cansancio, el dolor o la prueba.\n\nDavid comprendía este principio: «No ofreceré a Jehová mi Dios holocaustos que no me cuesten nada.» (2 Samuel 24:24) Alabar a Dios cuando todo va bien es fácil; alabarle cuando el corazón está quebrantado es un verdadero acto de fe. Es en esos momentos que la alabanza se vuelve un arma y un perfume agradable.\n\nJob, habiéndolo perdido todo, se postró y adoró: «Jehová dio, y Jehová quitó; sea el nombre de Jehová bendito.» (Job 1:21) Tal alabanza declara que Dios es digno, no por lo que da, sino por quién es. Proclama nuestra confianza en él en medio de las tinieblas.\n\nEl salmista decide bendecir a Dios pase lo que pase: «Bendeciré a Jehová en todo tiempo; su alabanza estará de continuo en mi boca.» (Salmo 34:1) La alabanza no está sujeta a las circunstancias; es una decisión de la voluntad. Escoge adorar a Dios en toda estación, y descubrirás que el sacrificio de alabanza abre el cielo sobre tu vida.",
          },
          keyPoints: {
            fr: ["Offrir sans cesse un sacrifice de louange (Hébreux 13.15)", "Ne pas offrir à Dieu ce qui ne coûte rien (2 Samuel 24.24)", "Adorer même dans la perte, comme Job (Job 1.21)", "Bénir l'Éternel en tout temps, par choix (Psaume 34.2)"],
            ht: ["Ofri san sès yon sakrifis louwanj (Ebre 13.15)", "Pa ofri Bondye sa ki pa koute anyen (2 Samyèl 24.24)", "Adore menm nan pèt la, tankou Jòb (Jòb 1.21)", "Beni Senyè a tout tan, pa chwa (Sòm 34.2)"],
            en: ["Continually offer a sacrifice of praise (Hebrews 13:15)", "Do not offer God what costs nothing (2 Samuel 24:24)", "Worship even in loss, like Job (Job 1:21)", "Bless the Lord at all times, by choice (Psalm 34:1)"],
            es: ["Ofrecer siempre un sacrificio de alabanza (Hebreos 13:15)", "No ofrecer a Dios lo que no cuesta nada (2 Samuel 24:24)", "Adorar aun en la pérdida, como Job (Job 1:21)", "Bendecir al Señor en todo tiempo, por decisión (Salmo 34:1)"],
          },
          exercise: {
            fr: "Cette semaine, choisissez délibérément d'adorer Dieu dans un domaine où vous êtes fatigué, déçu ou éprouvé. Chantez ou proclamez à voix haute la bonté de Dieu malgré la circonstance, en reprenant les mots de Job. Notez ce qui change dans votre cœur après ce sacrifice de louange.",
            ht: "Semèn sa a, chwazi espre pou adore Bondye nan yon domèn kote w fatige, desi oswa eprouve. Chante oswa pwoklame awotvwa bonte Bondye malgre sikonstans lan, repran mo Jòb yo. Note sa ki chanje nan kè w apre sakrifis louwanj sa a.",
            en: "This week, deliberately choose to worship God in an area where you are tired, disappointed or tested. Sing or proclaim aloud God's goodness despite the circumstance, echoing Job's words. Note what changes in your heart after this sacrifice of praise.",
            es: "Esta semana, escoge deliberadamente adorar a Dios en un área donde estás cansado, decepcionado o probado. Canta o proclama en voz alta la bondad de Dios a pesar de la circunstancia, repitiendo las palabras de Job. Anota lo que cambia en tu corazón después de este sacrificio de alabanza.",
          },
          verse: "Hébreux 13.15",
        },
      ],
    },
    {
      title: { fr: "La puissance de la louange", ht: "Pouvwa louwanj lan", en: "The power of praise", es: "El poder de la alabanza" },
      lessons: [
        {
          slug: "louange-qui-libere",
          title: { fr: "La louange qui libère", ht: "Louwanj ki libere", en: "Praise that sets free", es: "La alabanza que libera" },
          videoId: "",
          content: {
            fr: "La louange n'est pas seulement une émotion, c'est une arme spirituelle. Paul et Silas, emprisonnés et blessés, « chantaient les louanges de Dieu » à minuit, et soudain « un grand tremblement de terre » ouvrit les portes de la prison (Actes 16.25-26). La louange dans l'épreuve fait descendre la délivrance.\n\nQuand le roi Josaphat affronta une armée immense, Dieu lui dit de placer les chantres devant les soldats. « Au moment où l'on commençait les chants et les louanges, l'Éternel plaça une embuscade » contre l'ennemi (2 Chroniques 20.22). La bataille fut gagnée par l'adoration avant même le combat.\n\nDieu « habite au milieu des louanges d'Israël » (Psaume 22.4). Là où le peuple loue, la présence de Dieu se manifeste, et là où sa présence se manifeste, les chaînes tombent. « L'Esprit du Seigneur est là, là est la liberté. » (2 Corinthiens 3.17) Louer, c'est ouvrir la porte à l'intervention de Dieu.\n\nCe combat est spirituel, pas humain. La louange déloge l'ennemi car elle proclame la vérité : Dieu règne. Quand David jouait de la harpe, « l'esprit mauvais se retirait » de Saül (1 Samuel 16.23). La musique consacrée à Dieu apaise, libère et repousse les ténèbres. N'oubliez jamais : votre louange dépasse les murs de la salle et agit dans le monde invisible.",
            ht: "Louwanj se pa sèlman yon emosyon, se yon zam espirityèl. Pòl ak Silas, nan prizon e blese, « t ap chante louwanj Bondye » a minwi, e sibitman « yon gwo tranblemanntè » louvri pòt prizon an (Travay 16.25-26). Louwanj nan eprèv fè delivrans desann.\n\nLè wa Jozafat te afwonte yon lame imans, Bondye di l pou mete chantè yo devan sòlda yo. « Nan moman yo kòmanse chante ak louwanj, Senyè a mete yon anbiskad » kont ènmi an (2 Kwonik 20.22). Batay la te genyen ak adorasyon anvan menm konba a.\n\nBondye « rete nan mitan louwanj Izrayèl yo » (Sòm 22.4). Kote pèp la louwe, prezans Bondye manifeste, e kote prezans li manifeste, chèn yo tonbe. « Kote Lespri Senyè a ye, la gen libète. » (2 Korentyen 3.17) Louwe, se louvri pòt pou entèvansyon Bondye.\n\nKonba sa a espirityèl, se pa imen. Louwanj deloje ènmi an paske li pwoklame verite a : Bondye renye. Lè David t ap jwe ap la, « move lespri a te retire » sou Sayil (1 Samyèl 16.23). Mizik konsakre pou Bondye kalme, libere e repouse tenèb. Pa janm bliye : louwanj ou depase mi sal la e aji nan monn envizib la.",
            en: "Praise is not only an emotion, it is a spiritual weapon. Paul and Silas, imprisoned and wounded, \"were singing hymns to God\" at midnight, and suddenly \"a violent earthquake\" opened the prison doors (Acts 16:25-26). Praise in the trial brings down deliverance.\n\nWhen King Jehoshaphat faced an immense army, God told him to place the singers in front of the soldiers. \"As they began to sing and praise, the Lord set ambushes\" against the enemy (2 Chronicles 20:22). The battle was won by worship before the fighting even began.\n\nGod is \"enthroned on the praises of Israel\" (Psalm 22:3). Where the people praise, God's presence is manifested, and where his presence is manifested, chains fall. \"Where the Spirit of the Lord is, there is freedom.\" (2 Corinthians 3:17) To praise is to open the door to God's intervention.\n\nThis battle is spiritual, not human. Praise dislodges the enemy because it proclaims the truth: God reigns. When David played the harp, \"the evil spirit would leave\" Saul (1 Samuel 16:23). Music consecrated to God soothes, sets free and pushes back the darkness. Never forget: your praise goes beyond the walls of the room and acts in the unseen world.",
            es: "La alabanza no es solo una emoción, es un arma espiritual. Pablo y Silas, encarcelados y heridos, «cantaban himnos a Dios» a medianoche, y de repente «un gran terremoto» abrió las puertas de la cárcel (Hechos 16:25-26). La alabanza en la prueba hace descender la liberación.\n\nCuando el rey Josafat enfrentó un ejército inmenso, Dios le dijo que pusiera a los cantores delante de los soldados. «Cuando comenzaron a entonar cantos y alabanzas, Jehová puso emboscadas» contra el enemigo (2 Crónicas 20:22). La batalla se ganó con adoración antes del combate.\n\nDios «habita entre las alabanzas de Israel» (Salmo 22:3). Donde el pueblo alaba, la presencia de Dios se manifiesta, y donde su presencia se manifiesta, las cadenas caen. «Donde está el Espíritu del Señor, allí hay libertad.» (2 Corintios 3:17) Alabar es abrir la puerta a la intervención de Dios.\n\nEsta batalla es espiritual, no humana. La alabanza desaloja al enemigo porque proclama la verdad: Dios reina. Cuando David tocaba el arpa, «el espíritu malo se apartaba» de Saúl (1 Samuel 16:23). La música consagrada a Dios calma, libera y hace retroceder las tinieblas. Nunca olvides: tu alabanza traspasa las paredes de la sala y actúa en el mundo invisible.",
          },
          keyPoints: {
            fr: ["La louange est une arme : Paul et Silas libérés (Actes 16)", "Josaphat gagne la bataille par la louange (2 Chr 20.22)", "Dieu habite les louanges de son peuple (Psaume 22.4)", "La louange repousse les ténèbres, comme chez Saül (1 Sam 16.23)"],
            ht: ["Louwanj se yon zam : Pòl ak Silas libere (Travay 16)", "Jozafat genyen batay la ak louwanj (2 Kwonik 20.22)", "Bondye rete nan louwanj pèp li a (Sòm 22.4)", "Louwanj repouse tenèb, tankou sou Sayil (1 Sam 16.23)"],
            en: ["Praise is a weapon: Paul and Silas set free (Acts 16)", "Jehoshaphat wins the battle through praise (2 Chr 20:22)", "God dwells in the praises of his people (Psalm 22:3)", "Praise pushes back the darkness, as with Saul (1 Sam 16:23)"],
            es: ["La alabanza es un arma: Pablo y Silas liberados (Hechos 16)", "Josafat gana la batalla por la alabanza (2 Cr 20:22)", "Dios habita en las alabanzas de su pueblo (Salmo 22:3)", "La alabanza hace retroceder las tinieblas, como con Saúl (1 Sam 16:23)"],
          },
          exercise: {
            fr: "Face à une difficulté que vous traversez actuellement, décidez d'engager le « combat de la louange » : mettez de côté vos inquiétudes et adorez Dieu à voix haute pendant plusieurs minutes, en proclamant qui il est. Choisissez un chant de victoire et faites-en votre hymne cette semaine, comme Josaphat plaçant les chantres devant l'armée.",
            ht: "Fas ak yon difikilte w ap travèse kounye a, deside angaje « konba louwanj lan » : mete enkyetid ou yo sou kote e adore Bondye awotvwa pandan plizyè minit, pwoklame kiyès li ye. Chwazi yon chan viktwa e fè l vin im ou semèn sa a, tankou Jozafat ki mete chantè yo devan lame a.",
            en: "In the face of a difficulty you are currently going through, decide to enter the \"battle of praise\": set aside your worries and worship God aloud for several minutes, proclaiming who he is. Choose a song of victory and make it your anthem this week, like Jehoshaphat placing the singers before the army.",
            es: "Ante una dificultad que estás atravesando, decide entrar en la «batalla de la alabanza»: deja a un lado tus preocupaciones y adora a Dios en voz alta durante varios minutos, proclamando quién es él. Escoge un canto de victoria y hazlo tu himno esta semana, como Josafat poniendo a los cantores delante del ejército.",
          },
          verse: "2 Chroniques 20.22",
        },
        {
          slug: "conduire-l-assemblee",
          title: { fr: "Conduire l'assemblée dans l'adoration", ht: "Mennen asanble a nan adorasyon", en: "Leading the congregation in worship", es: "Guiar a la congregación en la adoración" },
          videoId: "",
          content: {
            fr: "Conduire la louange, c'est bien plus que chanter juste : c'est guider le peuple dans la présence de Dieu. Le conducteur de louange est un berger musical, sensible à l'Esprit et attentif à l'assemblée. Son rôle n'est pas d'attirer les regards sur lui, mais de les élever vers Dieu, comme Jean-Baptiste : « Il faut qu'il croisse, et que je diminue. » (Jean 3.30)\n\nDavid organisa les Lévites pour le chant « selon leur art » avec des instruments et des voix (1 Chroniques 25). L'excellence honore Dieu, mais elle reste au service de l'adoration, jamais au-dessus. Un cœur brisé qui chante faux touche Dieu plus qu'une performance parfaite au cœur froid.\n\nLe conducteur prépare son cœur avant de préparer ses accords. Il choisit des chants qui exaltent Christ, laisse de la place au silence et à la spontanéité de l'Esprit, et encourage l'assemblée à participer. « Que tout ce qui respire loue l'Éternel ! » (Psaume 150.6) Le but ultime est que le peuple, et non l'équipe, devienne l'orchestre de Dieu.\n\nConduire, c'est aussi discerner les temps : il y a un temps pour la fête et l'allégresse, et un temps pour l'adoration douce et le recueillement. « Il y a un temps pour tout. » (Ecclésiaste 3.1) Le bon conducteur lit l'atmosphère spirituelle et suit la conduite de l'Esprit plutôt qu'une simple liste de chants. Sa priorité n'est jamais le spectacle, mais la rencontre du peuple avec son Dieu.",
            ht: "Mennen louwanj, se plis pase chante jis : se gide pèp la nan prezans Bondye. Moun k ap mennen louwanj se yon bèje mizikal, sansib a Lespri a e atantif a asanble a. Wòl li se pa atire je moun sou li, men leve yo vè Bondye, tankou Jan Batis : « Fòk li grandi, e mwen menm diminye. » (Jan 3.30)\n\nDavid te òganize Levit yo pou chan an « selon atizay yo » ak enstriman ak vwa (1 Kwonik 25). Eksèlans onore Bondye, men li rete nan sèvis adorasyon, pa janm anwo l. Yon kè brize ki chante fo touche Bondye plis pase yon pèfòmans pafè ak yon kè frèt.\n\nMoun k ap mennen an prepare kè l anvan li prepare akò l yo. Li chwazi chan ki egzalte Kris, kite plas pou silans ak espontanèite Lespri a, e ankouraje asanble a patisipe. « Se pou tout sa ki gen souf louwe Senyè a ! » (Sòm 150.6) Bi final la se pou pèp la, e non ekip la, vin òkès Bondye.\n\nMennen, se tou disène tan yo : gen yon tan pou fèt ak kè kontan, e yon tan pou adorasyon dous ak rekèyman. « Gen yon tan pou tout bagay. » (Eklezyas 3.1) Bon konduktè a li atmosfè espirityèl la e swiv direksyon Lespri a olye yon senp lis chan. Priyorite l pa janm espektak la, men rankont pèp la ak Bondye l.",
            en: "Leading worship is much more than singing in tune: it is guiding the people into God's presence. The worship leader is a musical shepherd, sensitive to the Spirit and attentive to the congregation. His role is not to draw attention to himself, but to lift eyes toward God, like John the Baptist: \"He must become greater; I must become less.\" (John 3:30)\n\nDavid organized the Levites for singing \"according to their skill\" with instruments and voices (1 Chronicles 25). Excellence honors God, but it remains in the service of worship, never above it. A broken heart singing off-key touches God more than a flawless performance with a cold heart.\n\nThe leader prepares his heart before preparing his chords. He chooses songs that exalt Christ, leaves room for silence and the spontaneity of the Spirit, and encourages the congregation to participate. \"Let everything that has breath praise the Lord.\" (Psalm 150:6) The ultimate goal is for the people, not the team, to become God's orchestra.\n\nLeading also means discerning the times: there is a time for celebration and joy, and a time for gentle worship and reflection. \"There is a time for everything.\" (Ecclesiastes 3:1) The good leader reads the spiritual atmosphere and follows the leading of the Spirit rather than a mere song list. His priority is never the show, but the people's encounter with their God.",
            es: "Guiar la alabanza es mucho más que cantar afinado: es guiar al pueblo a la presencia de Dios. El director de alabanza es un pastor musical, sensible al Espíritu y atento a la congregación. Su papel no es atraer las miradas hacia sí mismo, sino elevarlas hacia Dios, como Juan el Bautista: «Es necesario que él crezca, pero que yo mengüe.» (Juan 3:30)\n\nDavid organizó a los levitas para el canto «conforme a su arte» con instrumentos y voces (1 Crónicas 25). La excelencia honra a Dios, pero permanece al servicio de la adoración, nunca por encima. Un corazón quebrantado que canta desafinado toca a Dios más que una actuación perfecta con un corazón frío.\n\nEl director prepara su corazón antes de preparar sus acordes. Escoge cantos que exalten a Cristo, deja espacio para el silencio y la espontaneidad del Espíritu, y anima a la congregación a participar. «Todo lo que respira alabe a Jehová.» (Salmo 150:6) La meta final es que el pueblo, y no el equipo, se convierta en la orquesta de Dios.\n\nGuiar también es discernir los tiempos: hay un tiempo para la fiesta y el júbilo, y un tiempo para la adoración suave y el recogimiento. «Todo tiene su tiempo.» (Eclesiastés 3:1) El buen director lee la atmósfera espiritual y sigue la guía del Espíritu más que una simple lista de cantos. Su prioridad nunca es el espectáculo, sino el encuentro del pueblo con su Dios.",
          },
          keyPoints: {
            fr: ["Élever les regards vers Dieu, pas vers soi (Jean 3.30)", "L'excellence sert l'adoration, elle ne la remplace pas", "Faire participer toute l'assemblée (Psaume 150.6)", "Discerner les temps et suivre l'Esprit (Ecclésiaste 3.1)"],
            ht: ["Leve je moun vè Bondye, pa vè tèt ou (Jan 3.30)", "Eksèlans sèvi adorasyon, li pa ranplase l", "Fè tout asanble a patisipe (Sòm 150.6)", "Disène tan yo e swiv Lespri a (Eklezyas 3.1)"],
            en: ["Lift eyes toward God, not toward self (John 3:30)", "Excellence serves worship, it does not replace it", "Involve the whole congregation (Psalm 150:6)", "Discern the times and follow the Spirit (Ecclesiastes 3:1)"],
            es: ["Elevar las miradas hacia Dios, no hacia sí mismo (Juan 3:30)", "La excelencia sirve a la adoración, no la reemplaza", "Hacer participar a toda la congregación (Salmo 150:6)", "Discernir los tiempos y seguir al Espíritu (Eclesiastés 3:1)"],
          },
          exercise: {
            fr: "Préparez une courte séquence de louange (trois chants) en priant d'abord pour l'assemblée que vous servez. Réfléchissez au « fil conducteur » spirituel : par où commencer, comment monter vers l'adoration, où laisser un temps de silence. Avant de servir, remettez à Dieu votre besoin d'être vu et demandez qu'il soit, lui, exalté.",
            ht: "Prepare yon ti sekans louwanj (twa chan) an priye dabò pou asanble w ap sèvi a. Reflechi sou « fil kondiktè » espirityèl la : ki kote pou kòmanse, kijan pou monte vè adorasyon, ki kote pou kite yon tan silans. Anvan w sèvi, remèt Bondye bezwen w pou moun wè w e mande pou se li menm ki egzalte.",
            en: "Prepare a short worship set (three songs), praying first for the congregation you serve. Think through the spiritual \"thread\": where to begin, how to build toward adoration, where to leave a time of silence. Before you serve, hand over to God your need to be seen and ask that he be the one exalted.",
            es: "Prepara una breve secuencia de alabanza (tres cantos), orando primero por la congregación que sirves. Reflexiona sobre el «hilo conductor» espiritual: por dónde empezar, cómo subir hacia la adoración, dónde dejar un tiempo de silencio. Antes de servir, entrega a Dios tu necesidad de ser visto y pide que sea él el exaltado.",
          },
          verse: "Jean 3.30",
        },
        {
          slug: "chanter-un-cantique-nouveau",
          title: { fr: "Chanter un cantique nouveau", ht: "Chante yon chante nèf", en: "Singing a new song", es: "Cantar un cántico nuevo" },
          videoId: "",
          content: {
            fr: "La Bible nous invite sans cesse à la fraîcheur dans la louange : « Chantez à l'Éternel un cantique nouveau, car il a fait des prodiges. » (Psaume 98.1) Un cantique nouveau naît d'une rencontre nouvelle avec Dieu. La louange ne doit jamais devenir une routine mécanique, mais rester l'expression vivante d'un cœur qui découvre chaque jour la bonté de Dieu.\n\nLe « cantique nouveau » est souvent le fruit d'une délivrance. David témoigne : « Il a mis dans ma bouche un cantique nouveau, une louange à notre Dieu. » (Psaume 40.4) Après avoir été retiré de la fosse, son cœur déborde d'un chant qui n'existait pas avant. Vos propres expériences avec Dieu peuvent devenir des chants qui touchent les autres.\n\nChanter un cantique nouveau, c'est aussi laisser l'Esprit inspirer une louange spontanée, au-delà des chants appris. « Je chanterai par l'esprit, mais je chanterai aussi avec l'intelligence. » (1 Corinthiens 14.15) Il y a une place pour les cantiques connus qui unissent l'assemblée, et une place pour l'adoration libre et personnelle qui jaillit du cœur.\n\nDieu se réjouit de la nouveauté parce qu'elle témoigne d'une relation vivante. Un couple qui s'aime ne cesse de trouver de nouvelles manières d'exprimer son amour ; ainsi en est-il de l'adorateur. Recherchez la présence de Dieu dans le secret, et de cette intimité jailliront des chants nouveaux. « Toute la terre, poussez vers l'Éternel des cris de joie ! » (Psaume 98.4)",
            ht: "Bib la envite nou san sès nan freche nan louwanj : « Chante Senyè a yon chante nèf, paske li fè mèvèy. » (Sòm 98.1) Yon chante nèf fèt nan yon rankont nèf ak Bondye. Louwanj pa dwe janm vin yon woutin mekanik, men rete ekspresyon vivan yon kè k ap dekouvri chak jou bonte Bondye.\n\n« Chante nèf » la souvan fwi yon delivrans. David temwaye : « Li mete nan bouch mwen yon chante nèf, yon louwanj pou Bondye nou. » (Sòm 40.4) Apre li te retire nan twou a, kè l debòde ak yon chan ki pa t egziste anvan. Pwòp eksperyans ou ak Bondye ka vin chan ki touche lòt moun.\n\nChante yon chante nèf, se tou kite Lespri a enspire yon louwanj espontane, pi lwen pase chan yo aprann. « M ap chante ak lespri, men m ap chante tou ak entèlijans. » (1 Korentyen 14.15) Gen yon plas pou chante li konnen ki ini asanble a, e yon plas pou adorasyon lib e pèsonèl ki soti nan kè.\n\nBondye rejwi ak nouvote paske li temwaye yon relasyon vivan. Yon koup ki renmen pa sispann jwenn nouvo fason pou eksprime lanmou l ; se konsa pou adoratè a. Chèche prezans Bondye nan sekrè, e nan entimite sa a chan nèf ap jayi. « Tout latè, pouse kri lajwa bay Senyè a ! » (Sòm 98.4)",
            en: "The Bible constantly invites us to freshness in worship: \"Sing to the Lord a new song, for he has done marvelous things.\" (Psalm 98:1) A new song is born of a fresh encounter with God. Worship must never become a mechanical routine, but remain the living expression of a heart that discovers God's goodness anew each day.\n\nThe \"new song\" is often the fruit of a deliverance. David testifies: \"He put a new song in my mouth, a hymn of praise to our God.\" (Psalm 40:3) After being lifted out of the pit, his heart overflows with a song that did not exist before. Your own experiences with God can become songs that touch others.\n\nTo sing a new song is also to let the Spirit inspire spontaneous praise, beyond learned songs. \"I will sing with my spirit, but I will also sing with my understanding.\" (1 Corinthians 14:15) There is a place for known songs that unite the congregation, and a place for free, personal worship that springs from the heart.\n\nGod rejoices in newness because it testifies to a living relationship. A couple in love never stops finding new ways to express their love; so it is with the worshiper. Seek God's presence in secret, and out of that intimacy new songs will flow. \"Shout for joy to the Lord, all the earth!\" (Psalm 98:4)",
            es: "La Biblia nos invita continuamente a la frescura en la alabanza: «Cantad a Jehová cántico nuevo, porque ha hecho maravillas.» (Salmo 98:1) Un cántico nuevo nace de un encuentro nuevo con Dios. La alabanza nunca debe volverse una rutina mecánica, sino permanecer como la expresión viva de un corazón que descubre cada día la bondad de Dios.\n\nEl «cántico nuevo» es a menudo el fruto de una liberación. David testifica: «Puso luego en mi boca cántico nuevo, alabanza a nuestro Dios.» (Salmo 40:3) Después de ser sacado del pozo, su corazón desborda con un canto que no existía antes. Tus propias experiencias con Dios pueden convertirse en cantos que tocan a otros.\n\nCantar un cántico nuevo es también dejar que el Espíritu inspire una alabanza espontánea, más allá de los cantos aprendidos. «Cantaré con el espíritu, pero cantaré también con el entendimiento.» (1 Corintios 14:15) Hay un lugar para los cantos conocidos que unen a la congregación, y un lugar para la adoración libre y personal que brota del corazón.\n\nDios se regocija en la novedad porque testifica de una relación viva. Una pareja que se ama no deja de encontrar nuevas maneras de expresar su amor; así es con el adorador. Busca la presencia de Dios en lo secreto, y de esa intimidad brotarán cantos nuevos. «Cantad alegres a Jehová, toda la tierra!» (Salmo 98:4)",
          },
          keyPoints: {
            fr: ["Chanter un cantique nouveau, fruit d'une rencontre (Psaume 98.1)", "La délivrance met un chant nouveau dans la bouche (Ps 40.4)", "Chanter par l'esprit et avec l'intelligence (1 Cor 14.15)", "La nouveauté témoigne d'une relation vivante avec Dieu"],
            ht: ["Chante yon chante nèf, fwi yon rankont (Sòm 98.1)", "Delivrans mete yon chan nèf nan bouch (Sòm 40.4)", "Chante ak lespri e ak entèlijans (1 Kor 14.15)", "Nouvote temwaye yon relasyon vivan ak Bondye"],
            en: ["Sing a new song, the fruit of an encounter (Psalm 98:1)", "Deliverance puts a new song in the mouth (Ps 40:3)", "Sing with the spirit and with the understanding (1 Cor 14:15)", "Newness testifies to a living relationship with God"],
            es: ["Cantar un cántico nuevo, fruto de un encuentro (Salmo 98:1)", "La liberación pone un canto nuevo en la boca (Sal 40:3)", "Cantar con el espíritu y con el entendimiento (1 Cor 14:15)", "La novedad testifica de una relación viva con Dios"],
          },
          exercise: {
            fr: "Prenez un moment seul avec Dieu et laissez monter de votre cœur une louange spontanée : quelques mots, une mélodie simple, un merci chanté pour ce qu'il a fait récemment dans votre vie. N'écoutez aucune musique enregistrée ; laissez naître votre propre cantique nouveau, même imparfait, et offrez-le à Dieu.",
            ht: "Pran yon moman poukont ou ak Bondye e kite yon louwanj espontane monte nan kè w : kèk mo, yon senp melodi, yon mèsi chante pou sa li fè dènyèman nan lavi w. Pa koute okenn mizik anrejistre ; kite pwòp chante nèf ou a fèt, menm si li pa pafè, e ofri l bay Bondye.",
            en: "Take a moment alone with God and let a spontaneous praise rise from your heart: a few words, a simple melody, a sung thank-you for what he has recently done in your life. Do not listen to any recorded music; let your own new song be born, even imperfect, and offer it to God.",
            es: "Toma un momento a solas con Dios y deja que suba de tu corazón una alabanza espontánea: unas pocas palabras, una melodía sencilla, un gracias cantado por lo que él ha hecho recientemente en tu vida. No escuches ninguna música grabada; deja nacer tu propio cántico nuevo, aunque imperfecto, y ofrécelo a Dios.",
          },
          verse: "Psaume 40.4",
        },
      ],
    },
    {
      title: { fr: "Servir dans l'équipe de louange", ht: "Sèvi nan ekip louwanj lan", en: "Serving in the worship team", es: "Servir en el equipo de alabanza" },
      lessons: [
        {
          slug: "excellence-et-preparation",
          title: { fr: "L'excellence et la préparation", ht: "Eksèlans ak preparasyon", en: "Excellence and preparation", es: "La excelencia y la preparación" },
          videoId: "",
          content: {
            fr: "Servir Dieu mérite le meilleur de nous-mêmes. La Bible dit : « Jouez de vos instruments avec art. » (Psaume 33.3) L'excellence n'est pas le perfectionnisme orgueilleux, mais le désir d'offrir à Dieu ce qu'il y a de meilleur, par respect pour sa grandeur. On ne présente pas à Dieu ce qui ne coûte rien (2 Samuel 24.24).\n\nLa préparation est une forme d'adoration. Répéter ses parties, connaître les chants, accorder son instrument, arriver à l'heure : tout cela honore Dieu et sert l'assemblée. « Maudit soit celui qui fait avec négligence l'œuvre de l'Éternel. » (Jérémie 48.10) La négligence dans les choses de Dieu n'est jamais un signe de spiritualité.\n\nMais l'excellence technique sans l'onction reste vide, et l'onction sans préparation crée le désordre. Les deux vont ensemble : travaille comme si tout dépendait de toi, prie comme si tout dépendait de Dieu. « Que tout se fasse avec bienséance et avec ordre. » (1 Corinthiens 14.40)\n\nL'excellence est aussi une question de fidélité dans les petites choses invisibles : la constance aux répétitions, le soin du matériel, le respect des autres musiciens. « Tu as été fidèle en peu de choses, je t'établirai sur beaucoup. » (Matthieu 25.21) Dieu confie davantage à ceux qui prennent au sérieux ce qu'il leur a déjà donné. Cherchez l'excellence non pour impressionner les hommes, mais pour honorer un Dieu qui mérite ce qu'il y a de meilleur.",
            ht: "Sèvi Bondye merite pi bon nan nou menm. Bib la di : « Jwe enstriman nou yo ak atizay. » (Sòm 33.3) Eksèlans se pa pèfeksyonis ògeye, men dezi pou ofri Bondye sa ki pi bon, pa respè pou grandè li. Ou pa prezante Bondye sa ki pa koute anyen (2 Samyèl 24.24).\n\nPreparasyon se yon fòm adorasyon. Repete pati ou yo, konnen chan yo, akòde enstriman ou, rive alè : tout sa onore Bondye e sèvi asanble a. « Madichon pou moun ki fè travay Senyè a ak neglijans. » (Jeremi 48.10) Neglijans nan bagay Bondye pa janm yon siy espiritalite.\n\nMen eksèlans teknik san onksyon rete vid, e onksyon san preparasyon kreye dezòd. Toude ale ansanm : travay tankou tout bagay depann de ou, priye tankou tout bagay depann de Bondye. « Se pou tout bagay fèt avèk lòd e byen òganize. » (1 Korentyen 14.40)\n\nEksèlans se tou yon kesyon fidelite nan ti bagay envizib yo : konstans nan repetisyon, swen materyèl, respè pou lòt mizisyen yo. « Ou te fidèl nan ti bagay, m ap etabli w sou anpil. » (Matye 25.21) Bondye konfye plis bay moun ki pran o serye sa li deja ba yo. Chèche eksèlans se pa pou enprèsyone lèzòm, men pou onore yon Bondye ki merite sa ki pi bon.",
            en: "Serving God deserves our very best. The Bible says: \"Play skillfully on the strings.\" (Psalm 33:3) Excellence is not prideful perfectionism, but the desire to offer God the very best, out of respect for his greatness. We do not present to God what costs us nothing (2 Samuel 24:24).\n\nPreparation is a form of worship. Rehearsing your parts, knowing the songs, tuning your instrument, arriving on time: all of this honors God and serves the congregation. \"Cursed is the one who does the Lord's work negligently.\" (Jeremiah 48:10) Carelessness in the things of God is never a sign of spirituality.\n\nBut technical excellence without the anointing remains empty, and anointing without preparation creates disorder. The two go together: work as if everything depended on you, pray as if everything depended on God. \"Everything should be done in a fitting and orderly way.\" (1 Corinthians 14:40)\n\nExcellence is also a matter of faithfulness in the small, invisible things: consistency at rehearsals, care for the equipment, respect for the other musicians. \"You have been faithful with a few things; I will put you in charge of many things.\" (Matthew 25:21) God entrusts more to those who take seriously what he has already given them. Seek excellence not to impress people, but to honor a God who deserves the very best.",
            es: "Servir a Dios merece lo mejor de nosotros. La Biblia dice: «Hacedlo bien, tañendo con júbilo.» (Salmo 33:3) La excelencia no es perfeccionismo orgulloso, sino el deseo de ofrecer a Dios lo mejor, por respeto a su grandeza. No presentamos a Dios lo que no nos cuesta nada (2 Samuel 24:24).\n\nLa preparación es una forma de adoración. Ensayar tus partes, conocer los cantos, afinar tu instrumento, llegar a tiempo: todo esto honra a Dios y sirve a la congregación. «Maldito el que hiciere indolentemente la obra de Jehová.» (Jeremías 48:10) La negligencia en las cosas de Dios nunca es señal de espiritualidad.\n\nPero la excelencia técnica sin la unción queda vacía, y la unción sin preparación crea desorden. Ambas van juntas: trabaja como si todo dependiera de ti, ora como si todo dependiera de Dios. «Hágase todo decentemente y con orden.» (1 Corintios 14:40)\n\nLa excelencia es también una cuestión de fidelidad en las pequeñas cosas invisibles: la constancia en los ensayos, el cuidado del equipo, el respeto por los demás músicos. «Sobre poco has sido fiel, sobre mucho te pondré.» (Mateo 25:21) Dios confía más a los que toman en serio lo que ya les ha dado. Busca la excelencia no para impresionar a los hombres, sino para honrar a un Dios que merece lo mejor.",
          },
          keyPoints: {
            fr: ["Offrir le meilleur à Dieu, avec art (Psaume 33.3)", "La préparation est une forme d'adoration (Jérémie 48.10)", "Excellence + onction ensemble, travail et prière (1 Cor 14.40)", "Fidèle dans les petites choses invisibles (Matthieu 25.21)"],
            ht: ["Ofri pi bon bay Bondye, ak atizay (Sòm 33.3)", "Preparasyon se yon fòm adorasyon (Jeremi 48.10)", "Eksèlans + onksyon ansanm, travay ak lapriyè (1 Kor 14.40)", "Fidèl nan ti bagay envizib yo (Matye 25.21)"],
            en: ["Offer God your best, with skill (Psalm 33:3)", "Preparation is a form of worship (Jeremiah 48:10)", "Excellence + anointing together, work and prayer (1 Cor 14:40)", "Faithful in the small, invisible things (Matthew 25:21)"],
            es: ["Ofrecer lo mejor a Dios, con arte (Salmo 33:3)", "La preparación es una forma de adoración (Jeremías 48:10)", "Excelencia + unción juntas, trabajo y oración (1 Cor 14:40)", "Fiel en las pequeñas cosas invisibles (Mateo 25:21)"],
          },
          exercise: {
            fr: "Avant votre prochain service, engagez-vous à une préparation intentionnelle : maîtrisez vos parties, apprenez les paroles par cœur pour lever les yeux vers Dieu et non vers la feuille, et arrivez en avance pour prier avec l'équipe. Identifiez un point de négligence habituel et corrigez-le comme un acte d'adoration.",
            ht: "Anvan pwochen sèvis ou, angaje w nan yon preparasyon entansyonèl : metrize pati ou yo, aprann pawòl yo pakè pou w leve je w vè Bondye e non vè fèy la, e rive davans pou priye ak ekip la. Idantifye yon pwen neglijans abityèl e korije l kòm yon zak adorasyon.",
            en: "Before your next service, commit to intentional preparation: master your parts, learn the lyrics by heart so you can lift your eyes to God and not to the sheet, and arrive early to pray with the team. Identify one habitual point of carelessness and correct it as an act of worship.",
            es: "Antes de tu próximo servicio, comprométete a una preparación intencional: domina tus partes, aprende la letra de memoria para levantar los ojos a Dios y no a la hoja, y llega temprano para orar con el equipo. Identifica un punto de descuido habitual y corrígelo como un acto de adoración.",
          },
          verse: "Psaume 33.3",
        },
        {
          slug: "unite-et-humilite-equipe",
          title: { fr: "L'unité et l'humilité dans l'équipe", ht: "Inite ak imilite nan ekip la", en: "Unity and humility in the team", es: "La unidad y la humildad en el equipo" },
          videoId: "",
          content: {
            fr: "Une équipe de louange est comme un corps : chaque membre est nécessaire, mais aucun n'est le centre. « Il y a diversité de dons, mais le même Esprit. » (1 Corinthiens 12.4) Le chanteur, le musicien, le technicien du son : tous servent le même Seigneur, et personne n'est plus important qu'un autre.\n\nL'ennemi de l'unité, c'est l'orgueil et la comparaison. Quand chacun cherche sa place au premier plan, l'harmonie se brise. Paul exhorte : « Ne faites rien par esprit de rivalité ou par vaine gloire, mais que l'humilité vous fasse regarder les autres comme étant au-dessus de vous-mêmes. » (Philippiens 2.3) Servir en équipe, c'est mourir à soi pour élever l'ensemble.\n\nL'unité ouvre la porte à la bénédiction. « Voici, oh ! qu'il est agréable... pour des frères de demeurer ensemble ! ... Car c'est là que l'Éternel envoie la bénédiction. » (Psaume 133) Une équipe soumise, qui prie ensemble et se pardonne, portera un fruit que le talent seul ne peut produire. Honore ton conducteur, encourage tes frères, et laisse Dieu recevoir toute la gloire.\n\nL'harmonie musicale est l'image de l'harmonie des cœurs : des voix différentes qui s'accordent produisent une beauté qu'aucune voix seule ne peut créer. « Ayez les mêmes sentiments les uns envers les autres. » (Romains 12.16) Avant de rechercher l'accord parfait des instruments, recherchez l'accord des cœurs. C'est cette unité, plus que la performance, qui ouvre le ciel et bénit l'assemblée.",
            ht: "Yon ekip louwanj se tankou yon kò : chak manm nesesè, men pa gen youn ki sant lan. « Gen divèsite don, men se menm Lespri a. » (1 Korentyen 12.4) Chantè a, mizisyen an, teknisyen son an : tout sèvi menm Senyè a, e pa gen youn ki pi enpòtan pase yon lòt.\n\nEnmi inite a, se ògèy ak konparezon. Lè chak moun ap chèche plas li nan premye plan, amoni an kase. Pòl egzòte : « Pa fè anyen pa lespri rivalite oswa pa vanite, men se pou imilite fè nou konsidere lòt moun pi wo pase tèt nou. » (Filipyen 2.3) Sèvi an ekip, se mouri a tèt ou pou leve tout ansanm lan.\n\nInite louvri pòt pou benediksyon. « Gade, o ! jan sa bon... pou frè rete ansanm ! ... Paske se la Senyè a voye benediksyon. » (Sòm 133) Yon ekip ki soumèt, ki priye ansanm e ki padonnen youn lòt, ap pote yon fwi talan sèlman pa ka pwodui. Onore konduktè w, ankouraje frè w yo, e kite Bondye resevwa tout glwa a.\n\nAmoni mizikal la se imaj amoni kè yo : vwa diferan ki akòde pwodui yon bèlte okenn vwa pou kont li pa ka kreye. « Se pou nou gen menm santiman youn pou lòt. » (Women 12.16) Anvan w chèche akò pafè enstriman yo, chèche akò kè yo. Se inite sa a, plis pase pèfòmans, ki louvri syèl la e beni asanble a.",
            en: "A worship team is like a body: every member is needed, but no one is the center. \"There are different kinds of gifts, but the same Spirit.\" (1 Corinthians 12:4) The singer, the musician, the sound technician: all serve the same Lord, and no one is more important than another.\n\nThe enemy of unity is pride and comparison. When everyone seeks the front position, harmony breaks. Paul exhorts: \"Do nothing out of selfish ambition or vain conceit. Rather, in humility value others above yourselves.\" (Philippians 2:3) To serve in a team is to die to self so the whole may be lifted up.\n\nUnity opens the door to blessing. \"How good and pleasant it is when God's people live together in unity! ... For there the Lord bestows his blessing.\" (Psalm 133) A team that is submitted, that prays together and forgives one another, will bear fruit that talent alone cannot produce. Honor your leader, encourage your brothers, and let God receive all the glory.\n\nMusical harmony is a picture of the harmony of hearts: different voices that blend produce a beauty no single voice can create. \"Live in harmony with one another.\" (Romans 12:16) Before seeking the perfect blend of instruments, seek the blending of hearts. It is this unity, more than the performance, that opens heaven and blesses the congregation.",
            es: "Un equipo de alabanza es como un cuerpo: cada miembro es necesario, pero ninguno es el centro. «Hay diversidad de dones, pero el Espíritu es el mismo.» (1 Corintios 12:4) El cantante, el músico, el técnico de sonido: todos sirven al mismo Señor, y ninguno es más importante que otro.\n\nEl enemigo de la unidad es el orgullo y la comparación. Cuando cada uno busca su lugar en primer plano, la armonía se rompe. Pablo exhorta: «Nada hagáis por contienda o por vanagloria; antes bien con humildad, estimando cada uno a los demás como superiores a él mismo.» (Filipenses 2:3) Servir en equipo es morir a uno mismo para elevar al conjunto.\n\nLa unidad abre la puerta a la bendición. «¡Mirad cuán bueno y cuán delicioso es habitar los hermanos juntos en armonía! ... Porque allí envía Jehová bendición.» (Salmo 133) Un equipo sometido, que ora unido y se perdona, dará un fruto que el talento solo no puede producir. Honra a tu director, anima a tus hermanos, y deja que Dios reciba toda la gloria.\n\nLa armonía musical es la imagen de la armonía de los corazones: voces diferentes que se combinan producen una belleza que ninguna voz sola puede crear. «Unánimes entre vosotros.» (Romanos 12:16) Antes de buscar la mezcla perfecta de los instrumentos, busca la unión de los corazones. Es esta unidad, más que la actuación, la que abre el cielo y bendice a la congregación.",
          },
          keyPoints: {
            fr: ["Chaque membre est nécessaire, aucun n'est le centre (1 Cor 12.4)", "Estimer les autres au-dessus de soi (Philippiens 2.3)", "L'unité attire la bénédiction de Dieu (Psaume 133)", "L'accord des cœurs avant l'accord des instruments (Rom 12.16)"],
            ht: ["Chak manm nesesè, pa gen youn ki sant (1 Kor 12.4)", "Konsidere lòt moun pi wo pase tèt ou (Filipyen 2.3)", "Inite atire benediksyon Bondye (Sòm 133)", "Akò kè yo anvan akò enstriman yo (Rom 12.16)"],
            en: ["Every member is needed, none is the center (1 Cor 12:4)", "Value others above yourself (Philippians 2:3)", "Unity draws God's blessing (Psalm 133)", "The blending of hearts before that of instruments (Rom 12:16)"],
            es: ["Cada miembro es necesario, ninguno es el centro (1 Cor 12:4)", "Estimar a los demás por encima de uno mismo (Filipenses 2:3)", "La unidad atrae la bendición de Dios (Salmo 133)", "La unión de los corazones antes que la de los instrumentos (Rom 12:16)"],
          },
          exercise: {
            fr: "Lors de votre prochaine répétition, prenez l'initiative d'encourager sincèrement chaque membre de l'équipe pour son apport, en particulier ceux qui sont dans l'ombre (technicien, choristes). Si une tension existe avec quelqu'un, faites le premier pas de réconciliation avant de servir ensemble, et priez pour l'unité de l'équipe.",
            ht: "Nan pwochen repetisyon w, pran inisyativ pou ankouraje sensèman chak manm ekip la pou kontribisyon l, sitou sila ki nan lonbraj yo (teknisyen, koris). Si gen yon tansyon ak yon moun, fè premye pa rekonsilyasyon an anvan w sèvi ansanm, e priye pou inite ekip la.",
            en: "At your next rehearsal, take the initiative to sincerely encourage each team member for their contribution, especially those in the background (technician, backup singers). If there is tension with someone, take the first step of reconciliation before serving together, and pray for the team's unity.",
            es: "En tu próximo ensayo, toma la iniciativa de animar sinceramente a cada miembro del equipo por su aporte, especialmente a los que están en la sombra (técnico, coristas). Si hay una tensión con alguien, da el primer paso de reconciliación antes de servir juntos, y ora por la unidad del equipo.",
          },
          verse: "Psaume 133.1",
        },
        {
          slug: "fidelite-et-constance-service",
          title: { fr: "La fidélité et la constance dans le service", ht: "Fidelite ak konstans nan sèvis la", en: "Faithfulness and constancy in service", es: "La fidelidad y la constancia en el servicio" },
          videoId: "",
          content: {
            fr: "Le service dans la louange n'est pas une course de vitesse, mais une marche d'endurance. Ce que Dieu recherche par-dessus tout chez ses serviteurs, c'est la fidélité : « Ce qu'on demande des dispensateurs, c'est que chacun soit trouvé fidèle. » (1 Corinthiens 4.2) Le talent impressionne un instant, mais la fidélité construit sur le long terme.\n\nLa fidélité se prouve dans la durée et dans les moments où personne ne regarde. « Celui qui est fidèle dans les petites choses est aussi fidèle dans les grandes. » (Luc 16.10) Servir avec constance quand on est fatigué, découragé ou peu remarqué, voilà ce qui plaît à Dieu et forme un vrai caractère de serviteur.\n\nLe service véritable est motivé par l'amour de Dieu, non par la reconnaissance des hommes. « Que vous mangiez, que vous buviez, ou quoi que vous fassiez, faites tout pour la gloire de Dieu. » (1 Corinthiens 10.31) Quand notre but est de plaire à Dieu, nous ne nous décourageons pas si les applaudissements manquent, car notre récompense vient de lui.\n\nEnfin, il faut servir sans se lasser, en gardant les yeux sur la moisson à venir. « Ne nous lassons pas de faire le bien ; car nous moissonnerons au temps convenable, si nous ne nous relâchons pas. » (Galates 6.9) Ceux qui persévèrent dans le service, année après année, laissent une empreinte durable dans l'Église et entendront un jour : « C'est bien, bon et fidèle serviteur. » (Matthieu 25.21)",
            ht: "Sèvis nan louwanj se pa yon kous vitès, men yon mach andirans. Sa Bondye chèche anlè tout bagay nan sèvitè l yo, se fidelite : « Sa yo mande nan men dispansatè yo, se pou chak moun jwenn fidèl. » (1 Korentyen 4.2) Talan enprèsyone yon moman, men fidelite bati sou long tèm.\n\nFidelite pwouve tèt li nan dire e nan moman kote pèsòn pa gade. « Moun ki fidèl nan ti bagay fidèl tou nan gwo bagay. » (Lik 16.10) Sèvi ak konstans lè w fatige, dekouraje oswa pa remake, men sa ki fè Bondye plezi e ki fòme yon vrè karaktè sèvitè.\n\nVrè sèvis motive pa lanmou Bondye, se pa rekonesans lèzòm. « Kit nou manje, kit nou bwè, oswa nenpòt sa nou fè, fè tout pou glwa Bondye. » (1 Korentyen 10.31) Lè bi nou se fè Bondye plezi, nou pa dekouraje si aplodisman yo manke, paske rekonpans nou soti nan men l.\n\nAnfen, fòk nou sèvi san nou pa fatige, kenbe je nou sou rekòt k ap vini an. « Pa kite nou fatige nan fè byen ; paske nou pral rekòlte nan tan ki apwopriye a, si nou pa lage. » (Galat 6.9) Sila ki pèsevere nan sèvis la, ane apre ane, kite yon anprent ki dire nan Legliz e yon jou y ap tande : « Se byen, bon e fidèl sèvitè. » (Matye 25.21)",
            en: "Service in worship is not a sprint, but a marathon of endurance. What God seeks above all in his servants is faithfulness: \"Those who have been given a trust must prove faithful.\" (1 Corinthians 4:2) Talent impresses for a moment, but faithfulness builds over the long term.\n\nFaithfulness proves itself over time and in the moments when no one is watching. \"Whoever is faithful in very little is also faithful in much.\" (Luke 16:10) To serve with constancy when you are tired, discouraged or unnoticed—this is what pleases God and forms a true servant's character.\n\nTrue service is motivated by the love of God, not by the recognition of people. \"Whether you eat or drink or whatever you do, do it all for the glory of God.\" (1 Corinthians 10:31) When our aim is to please God, we do not get discouraged if the applause is missing, for our reward comes from him.\n\nFinally, we must serve without growing weary, keeping our eyes on the harvest to come. \"Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.\" (Galatians 6:9) Those who persevere in service, year after year, leave a lasting mark on the Church and will one day hear: \"Well done, good and faithful servant.\" (Matthew 25:21)",
            es: "El servicio en la alabanza no es una carrera de velocidad, sino una marcha de resistencia. Lo que Dios busca por encima de todo en sus siervos es la fidelidad: «Se requiere de los administradores, que cada uno sea hallado fiel.» (1 Corintios 4:2) El talento impresiona por un instante, pero la fidelidad edifica a largo plazo.\n\nLa fidelidad se prueba con el tiempo y en los momentos en que nadie mira. «El que es fiel en lo muy poco, también en lo más es fiel.» (Lucas 16:10) Servir con constancia cuando estás cansado, desanimado o poco notado, eso es lo que agrada a Dios y forma un verdadero carácter de siervo.\n\nEl verdadero servicio está motivado por el amor de Dios, no por el reconocimiento de los hombres. «Si, pues, coméis o bebéis, o hacéis otra cosa, hacedlo todo para la gloria de Dios.» (1 Corintios 10:31) Cuando nuestro objetivo es agradar a Dios, no nos desanimamos si faltan los aplausos, porque nuestra recompensa viene de él.\n\nPor último, debemos servir sin cansarnos, con los ojos puestos en la cosecha venidera. «No nos cansemos, pues, de hacer bien; porque a su tiempo segaremos, si no desmayamos.» (Gálatas 6:9) Los que perseveran en el servicio, año tras año, dejan una huella duradera en la Iglesia y un día escucharán: «Bien, buen siervo y fiel.» (Mateo 25:21)",
          },
          keyPoints: {
            fr: ["Dieu cherche des serviteurs fidèles (1 Corinthiens 4.2)", "Fidèle dans les petites choses comme dans les grandes (Luc 16.10)", "Servir pour la gloire de Dieu, pas pour les applaudissements (1 Cor 10.31)", "Ne pas se lasser : la moisson vient à son temps (Galates 6.9)"],
            ht: ["Bondye chèche sèvitè fidèl (1 Korentyen 4.2)", "Fidèl nan ti bagay tankou nan gwo bagay (Lik 16.10)", "Sèvi pou glwa Bondye, pa pou aplodisman (1 Kor 10.31)", "Pa fatige : rekòt la vini nan tan l (Galat 6.9)"],
            en: ["God seeks faithful servants (1 Corinthians 4:2)", "Faithful in little things as in great ones (Luke 16:10)", "Serve for God's glory, not for applause (1 Cor 10:31)", "Do not grow weary: the harvest comes in time (Galatians 6:9)"],
            es: ["Dios busca siervos fieles (1 Corintios 4:2)", "Fiel en lo poco como en lo mucho (Lucas 16:10)", "Servir para la gloria de Dios, no por los aplausos (1 Cor 10:31)", "No cansarse: la cosecha llega a su tiempo (Gálatas 6:9)"],
          },
          exercise: {
            fr: "Examinez votre motivation à servir : cherchez-vous d'abord à plaire à Dieu ou à être remarqué des hommes ? Prenez un engagement concret de constance (par exemple assiduité aux répétitions, ponctualité, disponibilité) pour les prochains mois, et confiez à Dieu les moments où vous êtes tenté par le découragement.",
            ht: "Egzamine motivasyon w pou sèvi : èske w chèche dabò fè Bondye plezi oswa pou moun remake w ? Pran yon angajman konkrè konstans (pa egzanp asiduite nan repetisyon, pontyalite, disponiblite) pou pwochen mwa yo, e konfye Bondye moman kote w tante pa dekourajman.",
            en: "Examine your motivation for serving: do you first seek to please God or to be noticed by people? Make a concrete commitment to constancy (for example attendance at rehearsals, punctuality, availability) for the coming months, and entrust to God the moments when you are tempted by discouragement.",
            es: "Examina tu motivación para servir: ¿buscas primero agradar a Dios o ser notado por los hombres? Toma un compromiso concreto de constancia (por ejemplo asistencia a los ensayos, puntualidad, disponibilidad) para los próximos meses, y entrega a Dios los momentos en que te sientes tentado por el desánimo.",
          },
          verse: "1 Corinthiens 4.2",
        },
      ],
    },
    {
      title: { fr: "La musique, don de Dieu à travers les âges", ht: "Mizik, kado Bondye atravè laj yo", en: "Music, God's gift through the ages", es: "La música, don de Dios a través de los tiempos" },
      lessons: [
        {
          slug: "origine-et-vocation-de-la-musique",
          title: { fr: "L'origine et la vocation de la musique", ht: "Orijin ak vokasyon mizik la", en: "The origin and calling of music", es: "El origen y la vocación de la música" },
          videoId: "",
          content: {
            fr: "La musique n'est pas née sur terre, mais au ciel. Avant même la création de l'homme, « les étoiles du matin éclataient en chants d'allégresse, et tous les fils de Dieu poussaient des cris de joie. » (Job 38.7) La musique fait partie de l'atmosphère du ciel ; elle a été créée pour glorifier Dieu bien avant d'exister sur terre.\n\nDans l'histoire humaine, la musique apparaît très tôt : Jubal fut « le père de tous ceux qui jouent de la harpe et du chalumeau. » (Genèse 4.21) Don donné à toute l'humanité, la musique peut servir Dieu ou l'idole, édifier ou détruire ; sa vocation première, cependant, est de rendre gloire au Créateur.\n\nLa musique porte une puissance particulière parce qu'elle touche l'âme là où les mots seuls n'atteignent pas. Elle peut apaiser, comme la harpe de David calmant Saül, ou galvaniser, comme les trompettes de Jéricho. C'est pourquoi l'ennemi cherche tant à détourner la musique : ce qui est puissant pour le bien peut être détourné pour le mal.\n\nLa vocation du musicien chrétien est donc de reconquérir la musique pour la gloire de Dieu. « Chantez à l'Éternel, bénissez son nom, annoncez de jour en jour son salut ! » (Psaume 96.2) Chaque note, chaque mélodie peut redevenir ce qu'elle était à l'origine : un écho du ciel, un instrument entre les mains de Dieu pour toucher les cœurs et l'exalter.",
            ht: "Mizik pa fèt sou latè, men nan syèl la. Anvan menm kreyasyon lòm, « etwal maten yo t ap eklate an chan lajwa, e tout pitit Bondye yo t ap pouse kri lajwa. » (Jòb 38.7) Mizik fè pati atmosfè syèl la ; li te kreye pou bay Bondye glwa byen anvan li egziste sou latè.\n\nNan istwa imen an, mizik parèt byen bonè : Jibal te « papa tout moun ki jwe ap ak flit. » (Jenèz 4.21) Kado bay tout limanite, mizik ka sèvi Bondye oswa zidòl, edifye oswa detwi ; men premye vokasyon l se bay Kreyatè a glwa.\n\nMizik pote yon pouvwa patikilye paske li touche nanm nan kote mo sèlman pa rive. Li ka kalme, tankou ap David la ki kalme Sayil, oswa galvanize, tankou twonpèt Jeriko yo. Se poutèt sa ènmi an chèche tèlman detounen mizik : sa ki pisan pou byen ka detounen pou mal.\n\nVokasyon mizisyen kretyen an se donk rekonkeri mizik pou glwa Bondye. « Chante Senyè a, beni non li, anonse chak jou sali li ! » (Sòm 96.2) Chak nòt, chak melodi ka rvin sa li te ye nan orijin : yon eko syèl la, yon enstriman nan men Bondye pou touche kè yo e egzalte l.",
            en: "Music was not born on earth, but in heaven. Even before the creation of man, \"the morning stars sang together and all the angels shouted for joy.\" (Job 38:7) Music is part of the atmosphere of heaven; it was created to glorify God long before it existed on earth.\n\nIn human history, music appears very early: Jubal was \"the father of all who play stringed instruments and pipes.\" (Genesis 4:21) A gift given to all humanity, music can serve God or the idol, build up or destroy; its first calling, however, is to give glory to the Creator.\n\nMusic carries a particular power because it touches the soul where words alone cannot reach. It can soothe, like David's harp calming Saul, or stir up, like the trumpets of Jericho. This is why the enemy seeks so hard to divert music: what is powerful for good can be diverted for evil.\n\nThe calling of the Christian musician is therefore to reclaim music for the glory of God. \"Sing to the Lord, praise his name; proclaim his salvation day after day.\" (Psalm 96:2) Every note, every melody can become again what it was at the beginning: an echo of heaven, an instrument in God's hands to touch hearts and exalt him.",
            es: "La música no nació en la tierra, sino en el cielo. Incluso antes de la creación del hombre, «alababan todas las estrellas del alba, y se regocijaban todos los hijos de Dios.» (Job 38:7) La música forma parte de la atmósfera del cielo; fue creada para glorificar a Dios mucho antes de existir en la tierra.\n\nEn la historia humana, la música aparece muy temprano: Jubal fue «padre de todos los que tocan arpa y flauta.» (Génesis 4:21) Don dado a toda la humanidad, la música puede servir a Dios o al ídolo, edificar o destruir; sin embargo, su primera vocación es dar gloria al Creador.\n\nLa música lleva un poder particular porque toca el alma donde las palabras solas no alcanzan. Puede calmar, como el arpa de David calmando a Saúl, o enardecer, como las trompetas de Jericó. Por eso el enemigo busca tanto desviar la música: lo que es poderoso para el bien puede desviarse para el mal.\n\nLa vocación del músico cristiano es, por tanto, reconquistar la música para la gloria de Dios. «Cantad a Jehová, bendecid su nombre; anunciad de día en día su salvación.» (Salmo 96:2) Cada nota, cada melodía puede volver a ser lo que era en el origen: un eco del cielo, un instrumento en las manos de Dios para tocar los corazones y exaltarle.",
          },
          keyPoints: {
            fr: ["La musique est née au ciel, avant la terre (Job 38.7)", "Jubal, père des musiciens : un don pour l'humanité (Genèse 4.21)", "La musique touche l'âme là où les mots n'atteignent pas", "Vocation : reconquérir la musique pour la gloire de Dieu (Ps 96.2)"],
            ht: ["Mizik fèt nan syèl, anvan latè (Jòb 38.7)", "Jibal, papa mizisyen yo : yon kado pou limanite (Jenèz 4.21)", "Mizik touche nanm kote mo pa rive", "Vokasyon : rekonkeri mizik pou glwa Bondye (Sòm 96.2)"],
            en: ["Music was born in heaven, before earth (Job 38:7)", "Jubal, father of musicians: a gift for humanity (Genesis 4:21)", "Music touches the soul where words cannot reach", "Calling: reclaim music for the glory of God (Ps 96:2)"],
            es: ["La música nació en el cielo, antes que la tierra (Job 38:7)", "Jubal, padre de los músicos: un don para la humanidad (Génesis 4:21)", "La música toca el alma donde las palabras no alcanzan", "Vocación: reconquistar la música para la gloria de Dios (Sal 96:2)"],
          },
          exercise: {
            fr: "Réfléchissez à votre parcours musical : quand et comment Dieu a-t-il mis la musique dans votre vie ? Écrivez une phrase qui exprime votre vocation musicale au service de Dieu. Puis, cette semaine, prenez un chant que vous aimez et redécouvrez-le comme une offrande, en méditant chacune de ses paroles devant Dieu.",
            ht: "Reflechi sou pakou mizikal ou : kilè e kijan Bondye te mete mizik nan lavi w ? Ekri yon fraz ki eksprime vokasyon mizikal ou nan sèvis Bondye. Apre sa, semèn sa a, pran yon chan ou renmen e redekouvri l kòm yon ofrann, an medite chak nan pawòl li yo devan Bondye.",
            en: "Reflect on your musical journey: when and how did God put music in your life? Write a sentence that expresses your musical calling in the service of God. Then, this week, take a song you love and rediscover it as an offering, meditating on each of its words before God.",
            es: "Reflexiona sobre tu recorrido musical: ¿cuándo y cómo puso Dios la música en tu vida? Escribe una frase que exprese tu vocación musical al servicio de Dios. Luego, esta semana, toma un canto que ames y redescúbrelo como una ofrenda, meditando cada una de sus palabras delante de Dios.",
          },
          verse: "Job 38.7",
        },
        {
          slug: "instruments-et-diversite",
          title: { fr: "Les instruments et la diversité dans la louange", ht: "Enstriman ak divèsite nan louwanj lan", en: "Instruments and diversity in worship", es: "Los instrumentos y la diversidad en la alabanza" },
          videoId: "",
          content: {
            fr: "La Bible célèbre une louange riche et variée, mobilisant tous les instruments et toutes les expressions. Le Psaume 150 en est le sommet : « Louez-le au son de la trompette... du luth et de la harpe... du tambourin... des instruments à cordes et du chalumeau... des cymbales sonores ! » (Psaume 150.3-5) Aucun instrument n'est exclu du service de Dieu.\n\nLa diversité des instruments reflète la diversité des dons dans l'Église. David établit des milliers de Lévites pour la musique, répartis en chanteurs et instrumentistes de toutes sortes (1 Chroniques 15 et 25). Chacun avait sa place et sa fonction, et l'ensemble produisait une louange qui remplissait le temple de la gloire de Dieu (2 Chroniques 5.13-14).\n\nLa louange biblique engage aussi tout le corps : on chante, on joue, on lève les mains, on danse. « Qu'ils louent son nom avec des danses, qu'ils le célèbrent avec le tambourin et la harpe ! » (Psaume 149.3) L'adoration n'est pas figée ni uniquement intérieure ; elle peut s'exprimer avec joie et exubérance, comme David dansant devant l'arche (2 Samuel 6.14).\n\nCette diversité doit cependant rester au service de l'unité et de l'édification. « Que tout se fasse pour l'édification. » (1 Corinthiens 14.26) Les styles, les cultures et les générations peuvent se rencontrer dans la louange, car Dieu aime la variété qu'il a lui-même créée. Le but n'est pas l'uniformité, mais l'harmonie : de nombreuses voix et de nombreux instruments unis pour glorifier un seul Dieu.",
            ht: "Bib la selebre yon louwanj rich e varye, ki mobilize tout enstriman ak tout ekspresyon. Sòm 150 se somè a : « Louwe l ak son twonpèt... lut ak ap... tanbouren... enstriman a kòd ak flit... senbal ki sonnen ! » (Sòm 150.3-5) Pa gen enstriman ki eskli nan sèvis Bondye.\n\nDivèsite enstriman yo reflete divèsite don nan Legliz la. David etabli plizyè milye Levit pou mizik la, separe an chantè ak enstrimantis tout kalite (1 Kwonik 15 ak 25). Chak te gen plas li ak fonksyon l, e ansanm lan te pwodui yon louwanj ki te ranpli tanp lan ak glwa Bondye (2 Kwonik 5.13-14).\n\nLouwanj biblik la angaje tou tout kò a : moun chante, moun jwe, moun leve men, moun danse. « Se pou yo louwe non li ak dans, se pou yo selebre l ak tanbouren ak ap ! » (Sòm 149.3) Adorasyon pa fikse ni sèlman enteryè ; li ka eksprime ak lajwa e egzuberans, tankou David k ap danse devan lach la (2 Samyèl 6.14).\n\nMen divèsite sa a dwe rete nan sèvis inite ak edifikasyon. « Se pou tout bagay fèt pou edifikasyon. » (1 Korentyen 14.26) Estil, kilti ak jenerasyon ka rankontre nan louwanj, paske Bondye renmen varyete li menm te kreye. Bi a se pa inifòmite, men amoni : anpil vwa ak anpil enstriman ini pou bay yon sèl Bondye glwa.",
            en: "The Bible celebrates a rich and varied worship, mobilizing all instruments and all expressions. Psalm 150 is its summit: \"Praise him with the sounding of the trumpet... with the harp and lyre... with timbrel... with strings and pipe... with the clash of cymbals!\" (Psalm 150:3-5) No instrument is excluded from the service of God.\n\nThe diversity of instruments reflects the diversity of gifts in the Church. David appointed thousands of Levites for music, divided into singers and instrumentalists of all kinds (1 Chronicles 15 and 25). Each one had his place and function, and together they produced a worship that filled the temple with the glory of God (2 Chronicles 5:13-14).\n\nBiblical worship also engages the whole body: we sing, we play, we lift our hands, we dance. \"Let them praise his name with dancing and make music to him with timbrel and harp.\" (Psalm 149:3) Worship is not rigid nor only inward; it can be expressed with joy and exuberance, like David dancing before the ark (2 Samuel 6:14).\n\nThis diversity, however, must remain in the service of unity and edification. \"Everything must be done so that the church may be built up.\" (1 Corinthians 14:26) Styles, cultures and generations can meet in worship, for God loves the variety he himself created. The goal is not uniformity, but harmony: many voices and many instruments united to glorify one God.",
            es: "La Biblia celebra una alabanza rica y variada, que moviliza todos los instrumentos y todas las expresiones. El Salmo 150 es su cumbre: «Alabadle a son de bocina... con arpa y salterio... con pandero... con cuerdas y flautas... con címbalos resonantes!» (Salmo 150:3-5) Ningún instrumento está excluido del servicio de Dios.\n\nLa diversidad de instrumentos refleja la diversidad de dones en la Iglesia. David estableció miles de levitas para la música, repartidos en cantores e instrumentistas de todo tipo (1 Crónicas 15 y 25). Cada uno tenía su lugar y su función, y juntos producían una alabanza que llenaba el templo de la gloria de Dios (2 Crónicas 5:13-14).\n\nLa alabanza bíblica también involucra todo el cuerpo: se canta, se toca, se levantan las manos, se danza. «Alaben su nombre con danza; con pandero y arpa a él canten.» (Salmo 149:3) La adoración no es rígida ni solo interior; puede expresarse con gozo y exuberancia, como David danzando ante el arca (2 Samuel 6:14).\n\nSin embargo, esta diversidad debe permanecer al servicio de la unidad y la edificación. «Hágase todo para edificación.» (1 Corintios 14:26) Los estilos, las culturas y las generaciones pueden encontrarse en la alabanza, porque Dios ama la variedad que él mismo creó. La meta no es la uniformidad, sino la armonía: muchas voces y muchos instrumentos unidos para glorificar a un solo Dios.",
          },
          keyPoints: {
            fr: ["Tous les instruments servent à louer Dieu (Psaume 150.3-5)", "La diversité des instruments reflète la diversité des dons", "La louange engage tout le corps : chant, danse, mains (Ps 149.3)", "La diversité au service de l'unité et de l'édification (1 Cor 14.26)"],
            ht: ["Tout enstriman sèvi pou louwe Bondye (Sòm 150.3-5)", "Divèsite enstriman reflete divèsite don yo", "Louwanj angaje tout kò : chan, dans, men (Sòm 149.3)", "Divèsite nan sèvis inite ak edifikasyon (1 Kor 14.26)"],
            en: ["All instruments serve to praise God (Psalm 150:3-5)", "The diversity of instruments reflects the diversity of gifts", "Worship engages the whole body: song, dance, hands (Ps 149:3)", "Diversity in the service of unity and edification (1 Cor 14:26)"],
            es: ["Todos los instrumentos sirven para alabar a Dios (Salmo 150:3-5)", "La diversidad de instrumentos refleja la diversidad de dones", "La alabanza involucra todo el cuerpo: canto, danza, manos (Sal 149:3)", "La diversidad al servicio de la unidad y la edificación (1 Cor 14:26)"],
          },
          exercise: {
            fr: "Lisez le Psaume 150 à voix haute et laissez-le élargir votre vision de la louange. Cette semaine, sortez de votre zone de confort dans l'adoration : si vous êtes réservé, exprimez votre louange plus librement (mains levées, chant à pleine voix) ; réfléchissez aussi à la manière dont votre équipe peut accueillir davantage de diversité au service de l'unité.",
            ht: "Li Sòm 150 awotvwa e kite l elaji vizyon w sou louwanj. Semèn sa a, sòti nan zòn konfò w nan adorasyon : si w rezève, eksprime louwanj ou pi lib (men leve, chante ak tout vwa w) ; reflechi tou sou fason ekip ou ka akeyi plis divèsite nan sèvis inite a.",
            en: "Read Psalm 150 aloud and let it enlarge your vision of worship. This week, step out of your comfort zone in worship: if you are reserved, express your praise more freely (hands raised, singing at full voice); also reflect on how your team can welcome more diversity in the service of unity.",
            es: "Lee el Salmo 150 en voz alta y deja que amplíe tu visión de la alabanza. Esta semana, sal de tu zona de confort en la adoración: si eres reservado, expresa tu alabanza con más libertad (manos levantadas, cantando a plena voz); reflexiona también sobre cómo tu equipo puede acoger más diversidad al servicio de la unidad.",
          },
          verse: "Psaume 150.6",
        },
        {
          slug: "musique-dans-la-vie-quotidienne",
          title: { fr: "La musique dans la vie quotidienne", ht: "Mizik nan lavi chak jou", en: "Music in daily life", es: "La música en la vida cotidiana" },
          videoId: "",
          content: {
            fr: "La louange ne se limite pas au culte du dimanche ; elle est appelée à imprégner toute la vie du croyant. Paul exhorte : « Entretenez-vous par des psaumes, par des hymnes, et par des cantiques spirituels, chantant et célébrant de tout votre cœur les louanges du Seigneur. » (Éphésiens 5.19) Le chant devient une manière de vivre rempli de l'Esprit chaque jour.\n\nLa musique est un puissant moyen d'ancrer la Parole de Dieu dans nos cœurs. « Que la parole de Christ habite parmi vous abondamment ; instruisez-vous... par des psaumes, par des hymnes, par des cantiques spirituels. » (Colossiens 3.16) Beaucoup de vérités bibliques restent gravées en nous parce que nous les avons chantées. Le chant enseigne autant qu'il adore.\n\nLe chant fortifie aussi dans les moments difficiles. Le croyant peut chanter dans la nuit : « De jour l'Éternel m'accordait sa grâce ; la nuit, je chantais ses louanges. » (Psaume 42.9) Un cœur qui chante résiste au découragement, car la louange redirige le regard des problèmes vers la grandeur de Dieu.\n\nEnfin, la musique dans la maison bénit la famille et le témoignage. Un foyer où l'on chante les louanges de Dieu devient un lieu de paix et de présence. Prenez l'habitude d'adorer chez vous, dans la voiture, au travail : « Je chanterai à l'Éternel tant que je vivrai, je célébrerai mon Dieu tant que j'existerai. » (Psaume 104.33) Faites de votre vie entière un chant continu à la gloire de Dieu.",
            ht: "Louwanj pa limite nan kilt dimanch la ; li rele pou antre nan tout lavi kwayan an. Pòl egzòte : « Antretni tèt nou ak sòm, im, ak chante espirityèl, chante e selebre ak tout kè nou louwanj Senyè a. » (Efezyen 5.19) Chan an vin yon fason viv ranpli ak Lespri a chak jou.\n\nMizik se yon mwayen pisan pou ankre Pawòl Bondye nan kè nou. « Se pou pawòl Kris rete nan mitan nou an abondans ; enstwi tèt nou... ak sòm, ak im, ak chante espirityèl. » (Kolosyen 3.16) Anpil verite biblik rete grave nan nou paske nou te chante yo. Chan an anseye menm jan li adore.\n\nChan an fòtifye tou nan moman difisil. Kwayan an ka chante nan lannwit : « Lajounen Senyè a te ban m gras li ; lannwit, mwen te chante louwanj li. » (Sòm 42.9) Yon kè k ap chante reziste dekourajman, paske louwanj redirije gade a soti nan pwoblèm nan vè grandè Bondye.\n\nAnfen, mizik nan kay la beni fanmi an ak temwayaj la. Yon fwaye kote moun chante louwanj Bondye vin yon kote lapè ak prezans. Pran abitid adore lakay ou, nan machin nan, nan travay : « M ap chante Senyè a toutotan m ap viv, m ap selebre Bondye m toutotan mwen egziste. » (Sòm 104.33) Fè tout lavi w yon chan kontinyèl pou glwa Bondye.",
            en: "Praise is not limited to Sunday worship; it is called to permeate the whole life of the believer. Paul exhorts: \"Speak to one another with psalms, hymns, and songs from the Spirit. Sing and make music from your heart to the Lord.\" (Ephesians 5:19) Singing becomes a way of living filled with the Spirit each day.\n\nMusic is a powerful means of anchoring God's Word in our hearts. \"Let the message of Christ dwell among you richly as you teach... through psalms, hymns, and songs from the Spirit.\" (Colossians 3:16) Many biblical truths remain engraved in us because we have sung them. Singing teaches as much as it worships.\n\nSinging also strengthens us in difficult moments. The believer can sing in the night: \"By day the Lord directs his love, at night his song is with me.\" (Psalm 42:8) A heart that sings resists discouragement, for praise redirects the gaze from problems to the greatness of God.\n\nFinally, music in the home blesses the family and the testimony. A home where God's praises are sung becomes a place of peace and presence. Make a habit of worshiping at home, in the car, at work: \"I will sing to the Lord all my life; I will sing praise to my God as long as I live.\" (Psalm 104:33) Make your whole life a continuous song to the glory of God.",
            es: "La alabanza no se limita al culto del domingo; está llamada a impregnar toda la vida del creyente. Pablo exhorta: «Hablando entre vosotros con salmos, con himnos y cánticos espirituales, cantando y alabando al Señor en vuestros corazones.» (Efesios 5:19) El canto se convierte en una manera de vivir llenos del Espíritu cada día.\n\nLa música es un medio poderoso para arraigar la Palabra de Dios en nuestros corazones. «La palabra de Cristo more en abundancia en vosotros, enseñándoos... con salmos e himnos y cánticos espirituales.» (Colosenses 3:16) Muchas verdades bíblicas quedan grabadas en nosotros porque las hemos cantado. El canto enseña tanto como adora.\n\nEl canto también nos fortalece en los momentos difíciles. El creyente puede cantar en la noche: «De día mandará Jehová su misericordia, y de noche su cántico estará conmigo.» (Salmo 42:8) Un corazón que canta resiste el desánimo, porque la alabanza redirige la mirada de los problemas a la grandeza de Dios.\n\nPor último, la música en el hogar bendice a la familia y el testimonio. Un hogar donde se cantan las alabanzas de Dios se convierte en un lugar de paz y presencia. Toma el hábito de adorar en casa, en el auto, en el trabajo: «A Jehová cantaré en mi vida; a mi Dios cantaré salmos mientras viva.» (Salmo 104:33) Haz de toda tu vida un canto continuo para la gloria de Dios.",
          },
          keyPoints: {
            fr: ["La louange imprègne toute la vie, pas seulement le culte (Éph 5.19)", "Le chant ancre la Parole de Dieu dans le cœur (Col 3.16)", "Chanter dans la nuit résiste au découragement (Psaume 42.9)", "Adorer chez soi, partout, toute la vie (Psaume 104.33)"],
            ht: ["Louwanj antre nan tout lavi, pa sèlman kilt (Efez 5.19)", "Chan ankre Pawòl Bondye nan kè (Kol 3.16)", "Chante nan lannwit reziste dekourajman (Sòm 42.9)", "Adore lakay ou, tout kote, tout lavi (Sòm 104.33)"],
            en: ["Praise permeates all of life, not just worship (Eph 5:19)", "Singing anchors God's Word in the heart (Col 3:16)", "Singing in the night resists discouragement (Psalm 42:8)", "Worship at home, everywhere, all your life (Psalm 104:33)"],
            es: ["La alabanza impregna toda la vida, no solo el culto (Ef 5:19)", "El canto arraiga la Palabra de Dios en el corazón (Col 3:16)", "Cantar en la noche resiste el desánimo (Salmo 42:8)", "Adorar en casa, en todas partes, toda la vida (Salmo 104:33)"],
          },
          exercise: {
            fr: "Cette semaine, transformez des moments ordinaires en moments de louange : chantez un cantique en cuisinant, en conduisant ou avant de dormir. Choisissez un verset biblique et trouvez (ou inventez) une mélodie pour le mémoriser en chantant. Observez comment votre cœur et l'atmosphère de votre maison changent quand la louange devient quotidienne.",
            ht: "Semèn sa a, transfòme moman òdinè an moman louwanj : chante yon chan pandan w ap kwit manje, pandan w ap kondwi oswa anvan w dòmi. Chwazi yon vèsè biblik e jwenn (oswa envante) yon melodi pou memorize l an chante. Obsève kijan kè w ak atmosfè kay ou chanje lè louwanj vin chak jou.",
            en: "This week, turn ordinary moments into moments of praise: sing a song while cooking, driving, or before sleeping. Choose a Bible verse and find (or make up) a melody to memorize it by singing. Notice how your heart and the atmosphere of your home change when praise becomes daily.",
            es: "Esta semana, transforma momentos ordinarios en momentos de alabanza: canta un canto mientras cocinas, conduces o antes de dormir. Escoge un versículo bíblico y encuentra (o inventa) una melodía para memorizarlo cantando. Observa cómo cambian tu corazón y la atmósfera de tu casa cuando la alabanza se vuelve cotidiana.",
          },
          verse: "Éphésiens 5.19",
        },
      ],
    },
  ],
};

export default musique;
