import { CourseContent } from "./types";

const powerpoint: CourseContent = {
  slug: "powerpoint",
  intro: {
    fr: "Apprendre à utiliser PowerPoint pour créer des diapositives claires, les mettre en forme, les animer, ajouter du son et de la vidéo, puis présenter et partager avec assurance, pas à pas.",
    ht: "Aprann sèvi ak PowerPoint pou kreye diapozitiv klè, mete yo an fòm, anime yo, ajoute son ak videyo, epi prezante ak pataje ak konfyans, etap pa etap.",
    en: "Learn to use PowerPoint to create clear slides, format them, animate them, add sound and video, then present and share with confidence, step by step.",
    es: "Aprender a usar PowerPoint para crear diapositivas claras, darles formato, animarlas, añadir sonido y video, y luego presentar y compartir con seguridad, paso a paso.",
  },
  modules: [
    {
      title: { fr: "Créer une présentation", ht: "Kreye yon prezantasyon", en: "Creating a presentation", es: "Crear una presentación" },
      lessons: [
        {
          slug: "diapositives-et-dispositions",
          title: { fr: "Les diapositives et leurs dispositions", ht: "Diapozitiv yo ak dispozisyon yo", en: "Slides and their layouts", es: "Las diapositivas y sus diseños" },
          videoId: "",
          content: {
            fr: "PowerPoint sert à créer des présentations : une suite d'écrans, appelés « diapositives » (ou « slides »), que l'on projette devant un public pour appuyer un exposé. Chaque diapositive est comme une page qui apparaît l'une après l'autre pendant que tu parles.\n\nQuand tu ouvres PowerPoint et choisis une présentation vierge, la première diapositive apparaît au centre. À gauche, une colonne de miniatures montre toutes tes diapositives dans l'ordre : c'est le panneau de navigation. Pour ajouter une nouvelle diapositive, va dans l'onglet « Accueil » et clique sur « Nouvelle diapositive ».\n\nEn cliquant sur la flèche sous ce bouton, tu choisis une « disposition » : c'est un modèle de placement des éléments. La disposition « Diapositive de titre » sert pour la page d'ouverture, « Titre et contenu » offre un titre en haut et une zone pour du texte ou une image en dessous, et « Vide » te laisse tout placer librement.\n\nChoisir la bonne disposition dès le départ fait gagner beaucoup de temps. Prends l'habitude d'ouvrir chaque présentation par une diapositive de titre qui annonce le sujet, puis d'enchaîner avec des diapositives « Titre et contenu » pour développer une idée par diapositive.",
            ht: "PowerPoint sèvi pou kreye prezantasyon : yon seri ekran, ki rele « diapozitiv » (oswa « slides »), ke ou pwojte devan yon piblik pou soutni yon ekspoze. Chak diapozitiv se tankou yon paj ki parèt youn apre lòt pandan w ap pale.\n\nLè ou ouvri PowerPoint epi chwazi yon prezantasyon vid, premye diapozitiv la parèt nan mitan. Agoch, yon kolòn ti imaj montre tout diapozitiv ou yo nan lòd : se pano navigasyon an. Pou ajoute yon nouvo diapozitiv, ale nan onglè « Accueil » epi klike sou « Nouvelle diapositive ».\n\nLè ou klike sou flèch ki anba bouton sa a, ou chwazi yon « disposition » : se yon modèl kote eleman yo plase. Disposition « Diapositive de titre » sèvi pou paj ouvèti a, « Titre et contenu » bay yon tit anwo ak yon zòn pou tèks oswa imaj anba, epi « Vide » kite ou plase tout bagay lib.\n\nChwazi bon disposition depi nan kòmansman fè ou pran anpil mwens tan. Pran abitid ouvri chak prezantasyon ak yon diapozitiv tit ki anonse sijè a, epi kontinye ak diapozitiv « Titre et contenu » pou devlope yon sèl lide pou chak diapozitiv.",
            en: "PowerPoint is used to create presentations: a series of screens, called \"slides\", that you project in front of an audience to support a talk. Each slide is like a page that appears one after another while you speak.\n\nWhen you open PowerPoint and choose a blank presentation, the first slide appears in the center. On the left, a column of thumbnails shows all your slides in order: this is the navigation panel. To add a new slide, go to the \"Home\" tab and click \"New Slide\".\n\nBy clicking the arrow under this button, you choose a \"layout\": a template for where elements are placed. The \"Title Slide\" layout is for the opening page, \"Title and Content\" offers a title at the top and an area for text or an image below, and \"Blank\" lets you place everything freely.\n\nChoosing the right layout from the start saves a lot of time. Get into the habit of opening each presentation with a title slide that announces the topic, then continuing with \"Title and Content\" slides to develop one idea per slide.",
            es: "PowerPoint sirve para crear presentaciones: una serie de pantallas, llamadas «diapositivas» (o «slides»), que se proyectan ante un público para apoyar una exposición. Cada diapositiva es como una página que aparece una tras otra mientras hablas.\n\nCuando abres PowerPoint y eliges una presentación en blanco, la primera diapositiva aparece en el centro. A la izquierda, una columna de miniaturas muestra todas tus diapositivas en orden: es el panel de navegación. Para añadir una nueva diapositiva, ve a la pestaña «Inicio» y haz clic en «Nueva diapositiva».\n\nAl hacer clic en la flecha debajo de este botón, eliges un «diseño»: es una plantilla de colocación de los elementos. El diseño «Diapositiva de título» sirve para la página de apertura, «Título y contenido» ofrece un título arriba y una zona para texto o una imagen debajo, y «En blanco» te deja colocar todo libremente.\n\nElegir el diseño adecuado desde el principio ahorra mucho tiempo. Adquiere el hábito de abrir cada presentación con una diapositiva de título que anuncie el tema, y luego seguir con diapositivas «Título y contenido» para desarrollar una idea por diapositiva.",
          },
          keyPoints: {
            fr: ["Une présentation = une suite de diapositives projetées", "Accueil > Nouvelle diapositive pour en ajouter", "La disposition (titre, titre + contenu, vide) place les éléments", "Le panneau de gauche montre toutes les diapositives dans l'ordre"],
            ht: ["Yon prezantasyon = yon seri diapozitiv ki pwojte", "Accueil > Nouvelle diapositive pou ajoute youn", "Disposition (tit, tit + kontni, vid) plase eleman yo", "Pano agoch la montre tout diapozitiv yo nan lòd"],
            en: ["A presentation = a series of projected slides", "Home > New Slide to add one", "The layout (title, title + content, blank) places the elements", "The left panel shows all slides in order"],
            es: ["Una presentación = una serie de diapositivas proyectadas", "Inicio > Nueva diapositiva para añadir una", "El diseño (título, título + contenido, en blanco) coloca los elementos", "El panel de la izquierda muestra todas las diapositivas en orden"],
          },
          exercise: {
            fr: "Ouvre PowerPoint et crée une présentation vierge. Ajoute trois diapositives : une avec la disposition « Diapositive de titre », une avec « Titre et contenu » et une « Vide ». Observe où se placent les cadres dans chaque cas.",
            ht: "Ouvri PowerPoint epi kreye yon prezantasyon vid. Ajoute twa diapozitiv : youn ak disposition « Diapositive de titre », youn ak « Titre et contenu » epi youn « Vide ». Gade kote kad yo plase nan chak ka.",
            en: "Open PowerPoint and create a blank presentation. Add three slides: one with the \"Title Slide\" layout, one with \"Title and Content\" and one \"Blank\". Notice where the frames are placed in each case.",
            es: "Abre PowerPoint y crea una presentación en blanco. Añade tres diapositivas: una con el diseño «Diapositiva de título», una con «Título y contenido» y una «En blanco». Observa dónde se colocan los marcos en cada caso.",
          },
        },
        {
          slug: "ajouter-texte-images",
          title: { fr: "Ajouter du texte et des images", ht: "Ajoute tèks ak imaj", en: "Adding text and images", es: "Añadir texto e imágenes" },
          videoId: "",
          content: {
            fr: "Sur une diapositive, le texte se met dans des « zones de texte » : des rectangles prévus pour cela. Sur une disposition « Titre et contenu », tu vois des cadres avec la mention « Cliquez pour ajouter un titre » ou « du texte ». Clique simplement dedans et tape ; le texte remplace l'invite. Pour créer une zone de texte n'importe où, va dans « Insertion » puis « Zone de texte » et dessine un rectangle à l'endroit voulu.\n\nLa règle d'or d'une bonne diapositive est la sobriété : peu de mots, de gros caractères. Écris des phrases courtes ou des puces, pas des paragraphes entiers. Le public doit lire en une seconde ; c'est toi qui développes à l'oral. Une taille de police d'au moins 24 assure que tout le monde voit bien, même au fond de la salle.\n\nPour ajouter une image, va dans « Insertion » puis « Images » et choisis un fichier. L'image apparaît sur la diapositive ; tire un coin pour la redimensionner sans la déformer, et glisse-la pour la placer. Une image bien choisie vaut mieux qu'un long texte : une photo, un logo ou un schéma marque davantage les esprits.\n\nÉvite de tirer un côté d'une image (le haut ou un bord), car cela l'écrase ou l'étire : utilise toujours un coin pour garder ses proportions. Laisse aussi un peu d'espace vide autour du texte et des images : une diapositive qui « respire » se lit bien mieux qu'une diapositive surchargée.",
            ht: "Sou yon diapozitiv, tèks la ale nan « zòn tèks » : rektang ki fèt pou sa. Sou yon disposition « Titre et contenu », ou wè kad ki di « Cliquez pour ajouter un titre » oswa « du texte ». Klike senpleman ladan epi tape ; tèks la ranplase envit la. Pou kreye yon zòn tèks nenpòt kote, ale nan « Insertion » epi « Zone de texte » epi desine yon rektang kote ou vle a.\n\nRèg an lò yon bon diapozitiv se senplisite : kèk mo, gwo lèt. Ekri fraz kout oswa puces, pa paragraf antye. Piblik la dwe li nan yon segonn ; se ou menm ki devlope alowal. Yon gwosè police omwen 24 asire tout moun wè byen, menm nan fon sal la.\n\nPou ajoute yon imaj, ale nan « Insertion » epi « Images » epi chwazi yon fichye. Imaj la parèt sou diapozitiv la ; rale yon kwen pou chanje gwosè l san defòme l, epi glise l pou plase l. Yon imaj byen chwazi pi bon pase yon tèks long : yon foto, yon logo oswa yon dyagram make plis lespri moun.\n\nEvite rale yon kote nan yon imaj (anwo oswa yon bò), paske sa kraze l oswa etire l : sèvi toujou ak yon kwen pou kenbe pwopòsyon l. Kite tou yon ti espas vid alantou tèks la ak imaj yo : yon diapozitiv ki « respire » li pi byen pase yon diapozitiv ki twò chaje.",
            en: "On a slide, text goes into \"text boxes\": rectangles made for it. On a \"Title and Content\" layout, you see frames marked \"Click to add title\" or \"text\". Simply click inside and type; the text replaces the prompt. To create a text box anywhere, go to \"Insert\" then \"Text Box\" and draw a rectangle where you want it.\n\nThe golden rule of a good slide is simplicity: few words, large characters. Write short sentences or bullets, not whole paragraphs. The audience must read in a second; you are the one who expands out loud. A font size of at least 24 ensures everyone can see well, even at the back of the room.\n\nTo add an image, go to \"Insert\" then \"Pictures\" and choose a file. The image appears on the slide; drag a corner to resize it without distorting it, and drag it to position it. A well-chosen image is worth more than a long text: a photo, a logo or a diagram sticks in people's minds more.\n\nAvoid dragging a side of an image (the top or an edge), because that squashes or stretches it: always use a corner to keep its proportions. Also leave some empty space around the text and images: a slide that \"breathes\" reads much better than an overloaded one.",
            es: "En una diapositiva, el texto se coloca en «cuadros de texto»: rectángulos previstos para ello. En un diseño «Título y contenido», ves marcos con la indicación «Haga clic para agregar un título» o «texto». Simplemente haz clic dentro y escribe; el texto reemplaza la indicación. Para crear un cuadro de texto en cualquier lugar, ve a «Insertar» y luego «Cuadro de texto» y dibuja un rectángulo donde quieras.\n\nLa regla de oro de una buena diapositiva es la sobriedad: pocas palabras, letras grandes. Escribe frases cortas o viñetas, no párrafos enteros. El público debe leer en un segundo; eres tú quien desarrolla de viva voz. Un tamaño de fuente de al menos 24 asegura que todos vean bien, incluso al fondo de la sala.\n\nPara añadir una imagen, ve a «Insertar» y luego «Imágenes» y elige un archivo. La imagen aparece en la diapositiva; arrastra una esquina para redimensionarla sin deformarla, y arrástrala para colocarla. Una imagen bien elegida vale más que un texto largo: una foto, un logo o un esquema queda más grabado en la mente.\n\nEvita arrastrar un lado de una imagen (la parte superior o un borde), porque eso la aplasta o la estira: usa siempre una esquina para mantener sus proporciones. Deja también algo de espacio vacío alrededor del texto y las imágenes: una diapositiva que «respira» se lee mucho mejor que una sobrecargada.",
          },
          keyPoints: {
            fr: ["Le texte se tape dans des zones de texte (cadres)", "Peu de mots, gros caractères (police 24 minimum)", "Insertion > Images ; tirer un coin pour redimensionner", "Insertion > Zone de texte pour écrire n'importe où"],
            ht: ["Tèks la tape nan zòn tèks (kad)", "Kèk mo, gwo lèt (police 24 minimòm)", "Insertion > Images ; rale yon kwen pou chanje gwosè", "Insertion > Zone de texte pou ekri nenpòt kote"],
            en: ["Text is typed into text boxes (frames)", "Few words, large characters (font 24 minimum)", "Insert > Pictures; drag a corner to resize", "Insert > Text Box to write anywhere"],
            es: ["El texto se escribe en cuadros de texto (marcos)", "Pocas palabras, letras grandes (fuente 24 mínimo)", "Insertar > Imágenes; arrastra una esquina para redimensionar", "Insertar > Cuadro de texto para escribir en cualquier lugar"],
          },
          exercise: {
            fr: "Sur une diapositive « Titre et contenu », tape un titre et trois puces courtes (moins de six mots chacune). Insère ensuite une image depuis ton ordinateur et redimensionne-la en tirant un coin, sans la déformer.",
            ht: "Sou yon diapozitiv « Titre et contenu », tape yon tit ak twa puces kout (mwens pase sis mo chak). Apre sa, mete yon imaj soti nan òdinatè ou epi chanje gwosè l lè w rale yon kwen, san defòme l.",
            en: "On a \"Title and Content\" slide, type a title and three short bullets (fewer than six words each). Then insert an image from your computer and resize it by dragging a corner, without distorting it.",
            es: "En una diapositiva «Título y contenido», escribe un título y tres viñetas cortas (menos de seis palabras cada una). Luego inserta una imagen desde tu computadora y redimensiónala arrastrando una esquina, sin deformarla.",
          },
        },
        {
          slug: "organiser-les-diapositives",
          title: { fr: "Organiser et réordonner les diapositives", ht: "Òganize ak reòdone diapozitiv yo", en: "Organizing and reordering slides", es: "Organizar y reordenar las diapositivas" },
          videoId: "",
          content: {
            fr: "Une présentation réussie suit un ordre logique : ce n'est pas seulement une pile de diapositives, mais un chemin qui conduit le public d'une idée à la suivante. Le panneau de miniatures, à gauche, est ton outil principal pour ranger ce chemin. Chaque miniature y porte un numéro qui indique sa position.\n\nPour changer l'ordre, clique sur une miniature et fais-la glisser vers le haut ou le bas ; une ligne montre où elle va se poser, puis relâche. Pour dupliquer une diapositive réussie et la réutiliser comme modèle, fais un clic droit dessus et choisis « Dupliquer la diapositive ». Pour en retirer une, clic droit puis « Supprimer la diapositive » — ou sélectionne-la et appuie sur la touche Suppr.\n\nQuand la présentation devient longue, l'onglet « Affichage » offre la « Trieuse de diapositives » : toutes les diapositives s'affichent en petit, côte à côte, comme des cartes étalées sur une table. C'est la meilleure vue pour repérer un déséquilibre, déplacer plusieurs diapositives et vérifier l'enchaînement d'ensemble.\n\nPour les longues présentations, tu peux aussi créer des « sections » : un clic droit entre deux diapositives, puis « Ajouter une section », regroupe les diapositives par thème (introduction, partie 1, conclusion…). Tu peux replier une section pour t'y retrouver plus vite. Avant de te lancer, il est souvent utile de noter ton plan sur papier, puis de créer une diapositive par point.",
            ht: "Yon prezantasyon ki reyisi swiv yon lòd lojik : se pa sèlman yon pil diapozitiv, men yon chemen ki mennen piblik la soti nan yon lide al nan lòt la. Pano ti imaj yo, agoch, se zouti prensipal ou pou ranje chemen sa a. Chak ti imaj gen yon nimewo ki endike pozisyon l.\n\nPou chanje lòd la, klike sou yon ti imaj epi fè l glise anwo oswa anba ; yon liy montre kote li pral poze, apre lage l. Pou fè yon kopi yon diapozitiv ki reyisi epi resèvi l kòm modèl, fè yon klik dwat sou li epi chwazi « Dupliquer la diapositive ». Pou retire youn, klik dwat apre « Supprimer la diapositive » — oswa chwazi l epi peze bouton Suppr.\n\nLè prezantasyon an vin long, onglè « Affichage » a bay « Trieuse de diapositives » : tout diapozitiv yo afiche an piti, kòt a kòt, tankou kat yo etale sou yon tab. Se pi bon vi pou wè yon dezekilib, deplase plizyè diapozitiv epi verifye ansanm nan.\n\nPou long prezantasyon, ou ka tou kreye « seksyon » : yon klik dwat ant de diapozitiv, apre « Ajouter une section », rasanble diapozitiv yo pa tèm (entwodiksyon, pati 1, konklizyon…). Ou ka pliye yon seksyon pou w jwenn wout ou pi vit. Anvan ou kòmanse, li souvan itil pou note plan ou sou papye, apre kreye yon diapozitiv pou chak pwen.",
            en: "A successful presentation follows a logical order: it is not just a stack of slides, but a path that leads the audience from one idea to the next. The thumbnail panel on the left is your main tool for arranging that path. Each thumbnail carries a number showing its position.\n\nTo change the order, click a thumbnail and drag it up or down; a line shows where it will land, then release. To duplicate a successful slide and reuse it as a template, right-click it and choose \"Duplicate Slide\". To remove one, right-click then \"Delete Slide\" — or select it and press the Delete key.\n\nWhen the presentation gets long, the \"View\" tab offers the \"Slide Sorter\": all slides appear small, side by side, like cards laid out on a table. This is the best view to spot an imbalance, move several slides and check the overall flow.\n\nFor long presentations, you can also create \"sections\": a right-click between two slides, then \"Add Section\", groups slides by theme (introduction, part 1, conclusion…). You can collapse a section to find your way faster. Before you start, it is often useful to jot your outline on paper, then create one slide per point.",
            es: "Una presentación lograda sigue un orden lógico: no es solo un montón de diapositivas, sino un camino que lleva al público de una idea a la siguiente. El panel de miniaturas, a la izquierda, es tu herramienta principal para ordenar ese camino. Cada miniatura lleva un número que indica su posición.\n\nPara cambiar el orden, haz clic en una miniatura y arrástrala hacia arriba o abajo; una línea muestra dónde va a quedar, luego suéltala. Para duplicar una diapositiva lograda y reutilizarla como plantilla, haz clic derecho sobre ella y elige «Duplicar diapositiva». Para quitar una, clic derecho y luego «Eliminar diapositiva» — o selecciónala y pulsa la tecla Supr.\n\nCuando la presentación se hace larga, la pestaña «Vista» ofrece el «Clasificador de diapositivas»: todas las diapositivas aparecen pequeñas, una al lado de otra, como cartas extendidas sobre una mesa. Es la mejor vista para detectar un desequilibrio, mover varias diapositivas y comprobar el hilo general.\n\nPara presentaciones largas, también puedes crear «secciones»: un clic derecho entre dos diapositivas, luego «Agregar sección», agrupa las diapositivas por tema (introducción, parte 1, conclusión…). Puedes contraer una sección para orientarte más rápido. Antes de empezar, suele ser útil anotar tu esquema en papel y luego crear una diapositiva por punto.",
          },
          keyPoints: {
            fr: ["Glisser une miniature dans le panneau change son ordre", "Clic droit : Dupliquer ou Supprimer une diapositive", "La Trieuse de diapositives (Affichage) montre tout d'un coup", "Les sections regroupent les diapositives par thème"],
            ht: ["Glise yon ti imaj nan pano an chanje lòd li", "Klik dwat : Dupliquer oswa Supprimer yon diapozitiv", "Trieuse de diapositives (Affichage) montre tout ansanm", "Seksyon yo rasanble diapozitiv yo pa tèm"],
            en: ["Dragging a thumbnail in the panel changes its order", "Right-click: Duplicate or Delete a slide", "The Slide Sorter (View) shows everything at once", "Sections group slides by theme"],
            es: ["Arrastrar una miniatura en el panel cambia su orden", "Clic derecho: Duplicar o Eliminar una diapositiva", "El Clasificador de diapositivas (Vista) lo muestra todo a la vez", "Las secciones agrupan las diapositivas por tema"],
          },
          exercise: {
            fr: "Sur une présentation de cinq diapositives, déplace la dernière en deuxième position par glisser-déposer, duplique-en une, puis supprime le doublon. Ouvre enfin la Trieuse de diapositives et vérifie que l'ordre te paraît logique.",
            ht: "Sou yon prezantasyon senk diapozitiv, deplase dènye a nan dezyèm pozisyon ak glise-depoze, fè yon kopi youn, apre efase kopi a. Anfen ouvri Trieuse de diapositives epi verifye lòd la parèt lojik pou ou.",
            en: "On a five-slide presentation, move the last slide to second position by drag-and-drop, duplicate one, then delete the duplicate. Finally open the Slide Sorter and check that the order looks logical to you.",
            es: "En una presentación de cinco diapositivas, mueve la última a la segunda posición arrastrando y soltando, duplica una y luego elimina el duplicado. Por último, abre el Clasificador de diapositivas y comprueba que el orden te parece lógico.",
          },
        },
      ],
    },
    {
      title: { fr: "Mettre en forme et habiller", ht: "Mete an fòm epi abiye", en: "Formatting and styling", es: "Dar formato y estilo" },
      lessons: [
        {
          slug: "themes-et-couleurs",
          title: { fr: "Choisir un thème et des couleurs", ht: "Chwazi yon tèm ak koulè", en: "Choosing a theme and colors", es: "Elegir un tema y colores" },
          videoId: "",
          content: {
            fr: "Un « thème » est un habillage complet appliqué à toute la présentation d'un seul coup : couleurs de fond, polices, styles de titres. Au lieu de décorer chaque diapositive à la main, tu choisis un thème et tout devient cohérent instantanément. Va dans l'onglet « Création » (ou « Conception ») : une galerie de thèmes s'affiche ; clique sur celui qui te plaît et il s'applique partout.\n\nLa lisibilité passe avant la décoration. Choisis un fort contraste entre le fond et le texte : un texte foncé sur fond clair, ou un texte clair sur fond foncé. Évite d'écrire en jaune sur blanc ou en bleu foncé sur noir, illisibles à la projection. Garde deux ou trois couleurs maximum pour toute la présentation, sinon l'ensemble paraît brouillon.\n\nReste cohérent d'une diapositive à l'autre : même police, mêmes couleurs, mêmes emplacements de titres. Cette régularité donne une impression sérieuse et professionnelle. Le thème t'y aide automatiquement, mais fais attention si tu ajoutes tes propres couleurs à ne pas rompre l'harmonie.\n\nÀ droite de la galerie, le bouton « Variantes » propose la même mise en page en plusieurs jeux de couleurs : tu gardes le style choisi mais changes l'ambiance. Pense au lieu de projection : une salle très éclairée rend un fond clair plus lisible, tandis qu'une salle sombre supporte bien un fond foncé.",
            ht: "Yon « tèm » se yon abiman konplè ki aplike sou tout prezantasyon an yon sèl kou : koulè fon, police, estil tit. Olye pou dekore chak diapozitiv ak men, ou chwazi yon tèm epi tout vin koyeran touswit. Ale nan onglè « Création » (oswa « Conception ») : yon galri tèm parèt ; klike sou sa ki fè ou plezi a epi li aplike toupatou.\n\nLizibilite pase anvan dekorasyon. Chwazi yon gwo kontras ant fon an ak tèks la : yon tèks fonse sou fon klè, oswa yon tèks klè sou fon fonse. Evite ekri an jòn sou blan oswa an ble fonse sou nwa, ki pa ka li nan pwojeksyon. Kenbe de oswa twa koulè maksimòm pou tout prezantasyon an, sinon tout la parèt an dezòd.\n\nRete koyeran de yon diapozitiv a lòt : menm police, menm koulè, menm kote pou tit. Regilarite sa a bay yon enpresyon serye epi pwofesyonèl. Tèm nan ede ou otomatikman, men fè atansyon si ou ajoute pwòp koulè ou pou ou pa kraze amoni an.\n\nSou bò dwat galri a, bouton « Variantes » a pwopoze menm mizanpaj la nan plizyè jeu koulè : ou kenbe estil ou chwazi a men ou chanje anbyans lan. Panse ak kote pwojeksyon an : yon sal ki byen eklere fè yon fon klè pi lizib, pandan yon sal fènwa sipòte byen yon fon fonse.",
            en: "A \"theme\" is a complete look applied to the whole presentation at once: background colors, fonts, title styles. Instead of decorating each slide by hand, you choose a theme and everything becomes consistent instantly. Go to the \"Design\" tab: a gallery of themes appears; click the one you like and it applies everywhere.\n\nReadability comes before decoration. Choose a strong contrast between the background and the text: dark text on a light background, or light text on a dark background. Avoid writing in yellow on white or dark blue on black, unreadable when projected. Keep two or three colors at most for the whole presentation, otherwise the whole thing looks messy.\n\nStay consistent from one slide to the next: same font, same colors, same title placement. This regularity gives a serious, professional impression. The theme helps you with this automatically, but be careful if you add your own colors not to break the harmony.\n\nTo the right of the gallery, the \"Variants\" button offers the same layout in several color sets: you keep the chosen style but change the mood. Think about the projection room: a very bright room makes a light background more readable, while a dark room handles a dark background well.",
            es: "Un «tema» es un revestimiento completo que se aplica a toda la presentación de una sola vez: colores de fondo, fuentes, estilos de títulos. En lugar de decorar cada diapositiva a mano, eliges un tema y todo se vuelve coherente al instante. Ve a la pestaña «Diseño»: aparece una galería de temas; haz clic en el que te guste y se aplica en todas partes.\n\nLa legibilidad va antes que la decoración. Elige un fuerte contraste entre el fondo y el texto: un texto oscuro sobre fondo claro, o un texto claro sobre fondo oscuro. Evita escribir en amarillo sobre blanco o en azul oscuro sobre negro, ilegibles al proyectar. Mantén dos o tres colores como máximo para toda la presentación, de lo contrario el conjunto parece desordenado.\n\nMantente coherente de una diapositiva a otra: la misma fuente, los mismos colores, la misma ubicación de los títulos. Esta regularidad da una impresión seria y profesional. El tema te ayuda con esto automáticamente, pero ten cuidado si añades tus propios colores de no romper la armonía.\n\nA la derecha de la galería, el botón «Variantes» ofrece el mismo diseño en varios juegos de colores: conservas el estilo elegido pero cambias el ambiente. Piensa en el lugar de proyección: una sala muy iluminada hace un fondo claro más legible, mientras que una sala oscura admite bien un fondo oscuro.",
          },
          keyPoints: {
            fr: ["Un thème habille toute la présentation en un clic (onglet Création)", "Fort contraste fond/texte pour rester lisible à la projection", "Deux ou trois couleurs max, et rester cohérent partout", "Garder la même police et le même style sur toutes les diapositives"],
            ht: ["Yon tèm abiye tout prezantasyon an ak yon klik (onglè Création)", "Gwo kontras fon/tèks pou rete lizib nan pwojeksyon", "De oswa twa koulè maks, epi rete koyeran toupatou", "Kenbe menm police ak menm estil sou tout diapozitiv yo"],
            en: ["A theme dresses the whole presentation in one click (Design tab)", "Strong background/text contrast to stay readable when projected", "Two or three colors max, and stay consistent everywhere", "Keep the same font and style on every slide"],
            es: ["Un tema reviste toda la presentación con un clic (pestaña Diseño)", "Fuerte contraste fondo/texto para seguir legible al proyectar", "Dos o tres colores máximo, y mantener la coherencia en todo", "Mantener la misma fuente y el mismo estilo en todas las diapositivas"],
          },
          exercise: {
            fr: "Applique un thème depuis l'onglet Création, puis essaie deux « Variantes » de couleur. Vérifie la lisibilité : le texte se lit-il bien sur le fond ? Compte les couleurs utilisées et ramène-les à trois maximum.",
            ht: "Aplike yon tèm soti nan onglè Création, apre eseye de « Variantes » koulè. Verifye lizibilite : tèks la li byen sou fon an ? Konte koulè ou itilize yo epi rale yo nan twa maksimòm.",
            en: "Apply a theme from the Design tab, then try two color \"Variants\". Check readability: does the text read well on the background? Count the colors used and bring them down to three at most.",
            es: "Aplica un tema desde la pestaña Diseño, luego prueba dos «Variantes» de color. Comprueba la legibilidad: ¿se lee bien el texto sobre el fondo? Cuenta los colores usados y redúcelos a tres como máximo.",
          },
        },
        {
          slug: "mise-en-forme-du-texte",
          title: { fr: "Mettre en forme le texte", ht: "Mete tèks la an fòm", en: "Formatting text", es: "Dar formato al texto" },
          videoId: "",
          content: {
            fr: "Mettre en forme le texte, c'est le rendre plus clair et plus facile à lire. Toutes les commandes se trouvent dans l'onglet « Accueil », dans la zone « Police » et la zone « Paragraphe ». La règle est simple : sélectionne d'abord le texte avec la souris, puis clique sur le bouton voulu ; la mise en forme s'applique à ce que tu as sélectionné.\n\nDans la zone « Police », tu choisis le type de lettres (par exemple Calibri ou Arial) et leur taille en points. Les boutons G, I et S mettent le texte en gras, en italique ou souligné, utiles pour faire ressortir un mot important. Le petit « A » coloré change la couleur des lettres. Garde une même police sur toute la présentation et n'utilise le gras que pour l'essentiel, sinon plus rien ne ressort.\n\nDans la zone « Paragraphe », tu alignes le texte à gauche, au centre ou à droite. C'est là aussi que se trouvent les listes : les « puces » (petits points devant chaque ligne) et les listes « numérotées » (1, 2, 3). Les puces conviennent à une énumération d'idées, les numéros à des étapes qui se suivent dans l'ordre.\n\nLes boutons « Augmenter le retrait » et « Diminuer le retrait » créent des niveaux dans une liste : une idée principale, puis des sous-idées décalées vers la droite. Enfin, l'« interligne » règle l'espace entre les lignes ; un peu d'air rend le texte plus reposant à lire. Reste sobre : la mise en forme doit aider la lecture, pas la surcharger.",
            ht: "Mete tèks la an fòm, se rann li pi klè epi pi fasil pou li. Tout kòmand yo nan onglè « Accueil », nan zòn « Police » ak zòn « Paragraphe ». Règ la senp : chwazi tèks la anvan ak sourit la, apre klike sou bouton ou vle a ; fòma a aplike sou sa ou chwazi a.\n\nNan zòn « Police », ou chwazi kalite lèt yo (pa egzanp Calibri oswa Arial) ak gwosè yo an pwen. Bouton G, I ak S mete tèks la an gra, an italik oswa souliye, itil pou fè yon mo enpòtan sòti. Ti « A » kolore a chanje koulè lèt yo. Kenbe menm police sou tout prezantasyon an epi sèvi ak gra sèlman pou sa ki esansyèl, sinon anyen p ap sòti ankò.\n\nNan zòn « Paragraphe », ou aliyen tèks la agoch, nan mitan oswa adwat. Se la tou lis yo ye : « puces » (ti pwen devan chak liy) ak lis « numérotées » (1, 2, 3). Puces yo bon pou yon enimerasyon lide, nimewo yo pou etap ki swiv youn apre lòt nan lòd.\n\nBouton « Augmenter le retrait » ak « Diminuer le retrait » kreye nivo nan yon lis : yon lide prensipal, apre soulide ki dekale vè dwat. Anfen, « interligne » a regle espas ant liy yo ; yon ti lè rann tèks la pi repozan pou li. Rete senp : fòma a dwe ede lekti a, pa chaje l twòp.",
            en: "Formatting text means making it clearer and easier to read. All the commands are in the \"Home\" tab, in the \"Font\" area and the \"Paragraph\" area. The rule is simple: first select the text with the mouse, then click the button you want; the formatting applies to what you selected.\n\nIn the \"Font\" area, you choose the type of letters (for example Calibri or Arial) and their size in points. The B, I and U buttons make the text bold, italic or underlined, useful to highlight an important word. The small colored \"A\" changes the letter color. Keep one font throughout the presentation and use bold only for the essentials, otherwise nothing stands out anymore.\n\nIn the \"Paragraph\" area, you align text to the left, center or right. This is also where the lists are: \"bullets\" (small dots before each line) and \"numbered\" lists (1, 2, 3). Bullets suit a list of ideas, numbers suit steps that follow one another in order.\n\nThe \"Increase Indent\" and \"Decrease Indent\" buttons create levels in a list: a main idea, then sub-ideas shifted to the right. Finally, \"line spacing\" adjusts the space between lines; a bit of air makes the text more restful to read. Stay simple: formatting should help reading, not overload it.",
            es: "Dar formato al texto significa hacerlo más claro y más fácil de leer. Todos los comandos están en la pestaña «Inicio», en la zona «Fuente» y la zona «Párrafo». La regla es simple: selecciona primero el texto con el ratón, luego haz clic en el botón que quieras; el formato se aplica a lo que has seleccionado.\n\nEn la zona «Fuente», eliges el tipo de letras (por ejemplo Calibri o Arial) y su tamaño en puntos. Los botones N, K y S ponen el texto en negrita, cursiva o subrayado, útiles para resaltar una palabra importante. La pequeña «A» de color cambia el color de las letras. Mantén una misma fuente en toda la presentación y usa la negrita solo para lo esencial, de lo contrario ya nada resalta.\n\nEn la zona «Párrafo», alineas el texto a la izquierda, al centro o a la derecha. Ahí también están las listas: las «viñetas» (pequeños puntos delante de cada línea) y las listas «numeradas» (1, 2, 3). Las viñetas sirven para una enumeración de ideas, los números para pasos que se siguen en orden.\n\nLos botones «Aumentar sangría» y «Disminuir sangría» crean niveles en una lista: una idea principal, luego subideas desplazadas a la derecha. Por último, el «interlineado» ajusta el espacio entre líneas; un poco de aire hace el texto más descansado de leer. Mantente sobrio: el formato debe ayudar a la lectura, no sobrecargarla.",
          },
          keyPoints: {
            fr: ["Sélectionner le texte d'abord, puis cliquer sur le bouton", "Zone Police : type, taille, gras/italique/souligné, couleur", "Puces pour des idées, listes numérotées pour des étapes", "Le retrait crée des niveaux ; l'interligne aère le texte"],
            ht: ["Chwazi tèks la anvan, apre klike sou bouton an", "Zòn Police : kalite, gwosè, gra/italik/souliye, koulè", "Puces pou lide, lis numérotées pou etap", "Retrait kreye nivo ; interligne bay tèks la lè"],
            en: ["Select the text first, then click the button", "Font area: type, size, bold/italic/underline, color", "Bullets for ideas, numbered lists for steps", "Indent creates levels; line spacing airs out the text"],
            es: ["Seleccionar el texto primero, luego hacer clic en el botón", "Zona Fuente: tipo, tamaño, negrita/cursiva/subrayado, color", "Viñetas para ideas, listas numeradas para pasos", "La sangría crea niveles; el interlineado airea el texto"],
          },
          exercise: {
            fr: "Écris une liste de cinq idées et transforme-la en liste à puces. Mets un mot important en gras, choisis une taille d'au moins 24, puis crée un sous-niveau avec le bouton « Augmenter le retrait » pour une des lignes.",
            ht: "Ekri yon lis senk lide epi transfòme l an lis ak puces. Mete yon mo enpòtan an gra, chwazi yon gwosè omwen 24, apre kreye yon sou-nivo ak bouton « Augmenter le retrait » pou youn nan liy yo.",
            en: "Write a list of five ideas and turn it into a bulleted list. Make one important word bold, choose a size of at least 24, then create a sub-level with the \"Increase Indent\" button for one of the lines.",
            es: "Escribe una lista de cinco ideas y conviértela en una lista con viñetas. Pon una palabra importante en negrita, elige un tamaño de al menos 24, luego crea un subnivel con el botón «Aumentar sangría» para una de las líneas.",
          },
        },
        {
          slug: "formes-et-tableaux",
          title: { fr: "Formes, tableaux et graphiques", ht: "Fòm, tablo ak graf", en: "Shapes, tables and charts", es: "Formas, tablas y gráficos" },
          videoId: "",
          content: {
            fr: "Au-delà du texte et des images, PowerPoint sait dessiner directement sur la diapositive. Dans l'onglet « Insertion », le bouton « Formes » propose des flèches, des rectangles, des cercles et bien d'autres. Tu choisis une forme, puis tu la dessines en tirant la souris. Une flèche entre deux idées, un cadre autour d'un mot clé : ces formes simples guident l'œil du public.\n\nPour montrer un enchaînement d'idées de façon plus élégante, utilise « SmartArt » (toujours dans « Insertion »). Ce sont des schémas tout prêts : listes, processus en étapes, cycles, organigrammes. Tu choisis un modèle, tu tapes ton texte dans les cases, et le schéma se dessine et s'aligne automatiquement. C'est parfait pour illustrer « étape 1, étape 2, étape 3 » sans rien dessiner à la main.\n\nQuand tu as des données à comparer, un « Tableau » range l'information en lignes et en colonnes. Clique sur « Insertion » puis « Tableau », choisis le nombre de lignes et de colonnes, et remplis les cases. Un tableau clair vaut mieux qu'un long paragraphe de chiffres, car l'œil compare tout de suite les valeurs alignées.\n\nEnfin, pour rendre des chiffres parlants, insère un « Graphique » : un histogramme en barres, des parts de camembert, une courbe. PowerPoint ouvre une petite feuille de données où tu tapes tes valeurs, et le graphique se dessine aussitôt. Une image de données frappe bien plus qu'une liste de nombres. Comme toujours, garde ces éléments simples et lisibles, sans les surcharger.",
            ht: "Anplis tèks ak imaj, PowerPoint konn desine dirèkteman sou diapozitiv la. Nan onglè « Insertion » a, bouton « Formes » a pwopoze flèch, rektang, sèk ak anpil lòt. Ou chwazi yon fòm, apre ou desine l lè w rale sourit la. Yon flèch ant de lide, yon kad alantou yon mo kle : fòm senp sa yo gide je piblik la.\n\nPou montre yon seri lide nan yon fason ki pi bèl, sèvi ak « SmartArt » (toujou nan « Insertion »). Se dyagram ki fin pare : lis, pwosesis an etap, sik, òganigram. Ou chwazi yon modèl, ou tape tèks ou nan kaz yo, epi dyagram nan desine epi aliyen otomatikman. Li pafè pou ilistre « etap 1, etap 2, etap 3 » san desine anyen ak men.\n\nLè ou gen done pou konpare, yon « Tableau » ranje enfòmasyon an nan liy ak kolòn. Klike sou « Insertion » apre « Tableau », chwazi kantite liy ak kolòn, epi ranpli kaz yo. Yon tablo klè pi bon pase yon long paragraf chif, paske je a konpare touswit valè ki aliyen yo.\n\nAnfen, pou fè chif yo pale, mete yon « Graphique » : yon istogram an ba, moso kamanbè, yon koub. PowerPoint ouvri yon ti fèy done kote ou tape valè ou yo, epi graf la desine touswit. Yon imaj done frape plis pase yon lis nonb. Kòm toujou, kenbe eleman sa yo senp epi lizib, san chaje yo.",
            en: "Beyond text and images, PowerPoint can draw directly on the slide. In the \"Insert\" tab, the \"Shapes\" button offers arrows, rectangles, circles and many more. You choose a shape, then draw it by dragging the mouse. An arrow between two ideas, a frame around a keyword: these simple shapes guide the audience's eye.\n\nTo show a sequence of ideas more elegantly, use \"SmartArt\" (also in \"Insert\"). These are ready-made diagrams: lists, step processes, cycles, org charts. You choose a model, type your text in the boxes, and the diagram draws and aligns itself automatically. It is perfect for illustrating \"step 1, step 2, step 3\" without drawing anything by hand.\n\nWhen you have data to compare, a \"Table\" arranges the information in rows and columns. Click \"Insert\" then \"Table\", choose the number of rows and columns, and fill in the cells. A clear table beats a long paragraph of figures, because the eye compares the aligned values right away.\n\nFinally, to make numbers speak, insert a \"Chart\": a bar chart, pie slices, a line curve. PowerPoint opens a small data sheet where you type your values, and the chart draws immediately. A picture of data hits much harder than a list of numbers. As always, keep these elements simple and readable, without overloading them.",
            es: "Más allá del texto y las imágenes, PowerPoint puede dibujar directamente en la diapositiva. En la pestaña «Insertar», el botón «Formas» ofrece flechas, rectángulos, círculos y muchos más. Eliges una forma, luego la dibujas arrastrando el ratón. Una flecha entre dos ideas, un recuadro alrededor de una palabra clave: estas formas simples guían la vista del público.\n\nPara mostrar una secuencia de ideas de forma más elegante, usa «SmartArt» (también en «Insertar»). Son esquemas ya preparados: listas, procesos por pasos, ciclos, organigramas. Eliges un modelo, escribes tu texto en las casillas, y el esquema se dibuja y se alinea automáticamente. Es perfecto para ilustrar «paso 1, paso 2, paso 3» sin dibujar nada a mano.\n\nCuando tienes datos que comparar, una «Tabla» ordena la información en filas y columnas. Haz clic en «Insertar» y luego «Tabla», elige el número de filas y columnas, y rellena las celdas. Una tabla clara vale más que un largo párrafo de cifras, porque la vista compara enseguida los valores alineados.\n\nPor último, para hacer hablar a los números, inserta un «Gráfico»: un gráfico de barras, porciones de pastel, una curva. PowerPoint abre una pequeña hoja de datos donde escribes tus valores, y el gráfico se dibuja al instante. Una imagen de datos impacta mucho más que una lista de números. Como siempre, mantén estos elementos simples y legibles, sin sobrecargarlos.",
          },
          keyPoints: {
            fr: ["Insertion > Formes pour flèches, cadres et repères visuels", "SmartArt dessine des schémas d'étapes tout prêts", "Un tableau range les données en lignes et colonnes", "Un graphique rend des chiffres immédiatement parlants"],
            ht: ["Insertion > Formes pou flèch, kad ak repè vizyèl", "SmartArt desine dyagram etap ki fin pare", "Yon tablo ranje done yo an liy ak kolòn", "Yon graf fè chif yo pale touswit"],
            en: ["Insert > Shapes for arrows, frames and visual cues", "SmartArt draws ready-made step diagrams", "A table arranges data in rows and columns", "A chart makes numbers instantly speak"],
            es: ["Insertar > Formas para flechas, recuadros y guías visuales", "SmartArt dibuja esquemas de pasos ya preparados", "Una tabla ordena los datos en filas y columnas", "Un gráfico hace hablar los números al instante"],
          },
          exercise: {
            fr: "Sur une nouvelle diapositive, insère un SmartArt de type « Processus » avec trois étapes que tu remplis. Sur une autre, crée un petit tableau de trois colonnes et deux lignes, puis un graphique en barres à partir de trois valeurs.",
            ht: "Sou yon nouvo diapozitiv, mete yon SmartArt tip « Processus » ak twa etap ou ranpli. Sou yon lòt, kreye yon ti tablo twa kolòn ak de liy, apre yon graf an ba ak twa valè.",
            en: "On a new slide, insert a \"Process\" SmartArt with three steps that you fill in. On another, create a small table of three columns and two rows, then a bar chart from three values.",
            es: "En una nueva diapositiva, inserta un SmartArt de tipo «Proceso» con tres pasos que rellenes. En otra, crea una pequeña tabla de tres columnas y dos filas, y luego un gráfico de barras a partir de tres valores.",
          },
        },
      ],
    },
    {
      title: { fr: "Animer et enrichir", ht: "Anime epi anrichi", en: "Animate and enrich", es: "Animar y enriquecer" },
      lessons: [
        {
          slug: "transitions-et-animations",
          title: { fr: "Transitions et animations", ht: "Tranzisyon ak animasyon", en: "Transitions and animations", es: "Transiciones y animaciones" },
          videoId: "",
          content: {
            fr: "Les transitions et les animations rendent une présentation plus vivante, mais elles se distinguent. Une « transition » est l'effet qui se produit au passage d'une diapositive à la suivante, comme un fondu ou un glissement. Une « animation » fait apparaître ou bouger un élément à l'intérieur d'une même diapositive, par exemple faire surgir les puces une par une.\n\nPour ajouter une transition, ouvre l'onglet « Transitions », sélectionne une diapositive dans la colonne de gauche, et choisis un effet comme « Fondu ». Le bouton « Appliquer partout » met la même transition sur toutes les diapositives, pour un rendu régulier. Pour une animation, sélectionne d'abord l'élément (un titre, une image), va dans l'onglet « Animations » et choisis un effet comme « Apparaître ».\n\nLe conseil le plus important est la modération. Un effet discret et unique, répété partout, fait pro ; des effets clignotants et différents à chaque diapositive fatiguent et distraient le public de ton message. Les animations doivent servir le propos — révéler une idée au bon moment — jamais impressionner pour elles-mêmes.\n\nUn usage particulièrement utile est de faire apparaître les puces d'une liste une par une : le public se concentre sur le point dont tu parles, sans lire d'avance toute la diapositive. Choisis un effet simple comme « Apparaître » ou « Estomper », et garde le même d'un bout à l'autre pour rester cohérent.",
            ht: "Tranzisyon ak animasyon fè yon prezantasyon vin pi vivan, men yo diferan. Yon « transition » se efè ki fèt lè w ap pase yon diapozitiv al nan lòt la, tankou yon fondi oswa yon glisman. Yon « animation » fè yon eleman parèt oswa bouje anndan menm diapozitiv la, pa egzanp fè puces yo parèt youn pa youn.\n\nPou ajoute yon tranzisyon, ouvri onglè « Transitions » lan, chwazi yon diapozitiv nan kolòn agoch la, epi chwazi yon efè tankou « Fondu ». Bouton « Appliquer partout » a mete menm tranzisyon an sou tout diapozitiv yo, pou yon rezilta regilye. Pou yon animasyon, chwazi eleman an anvan (yon tit, yon imaj), ale nan onglè « Animations » epi chwazi yon efè tankou « Apparaître ».\n\nKonsèy ki pi enpòtan an se modon. Yon efè diskrè epi inik, repete toupatou, fè pwo ; efè k ap klete epi diferan chak diapozitiv fatige epi distrè piblik la de mesaj ou. Animasyon yo dwe sèvi pwopo a — revele yon lide nan bon moman — pa janm enpresyone pou tèt yo.\n\nYon itilizasyon ki itil anpil se fè puces yon lis parèt youn pa youn : piblik la konsantre sou pwen w ap pale a, san li tout diapozitiv la davans. Chwazi yon efè senp tankou « Apparaître » oswa « Estomper », epi kenbe menm lan depi nan kòmansman rive nan fen pou rete koyeran.",
            en: "Transitions and animations make a presentation more lively, but they are different. A \"transition\" is the effect that happens when moving from one slide to the next, like a fade or a slide. An \"animation\" makes an element appear or move within the same slide, for example revealing bullets one by one.\n\nTo add a transition, open the \"Transitions\" tab, select a slide in the left column, and choose an effect like \"Fade\". The \"Apply to All\" button puts the same transition on every slide, for a consistent result. For an animation, first select the element (a title, an image), go to the \"Animations\" tab and choose an effect like \"Appear\".\n\nThe most important advice is moderation. A discreet, single effect, repeated everywhere, looks professional; flashing effects that differ on each slide tire and distract the audience from your message. Animations must serve the point — revealing an idea at the right moment — never impress for their own sake.\n\nA particularly useful use is to reveal a list's bullets one by one: the audience focuses on the point you are discussing, without reading the whole slide ahead. Choose a simple effect like \"Appear\" or \"Fade\", and keep the same one from start to finish to stay consistent.",
            es: "Las transiciones y las animaciones hacen una presentación más amena, pero son distintas. Una «transición» es el efecto que se produce al pasar de una diapositiva a la siguiente, como un fundido o un deslizamiento. Una «animación» hace aparecer o mover un elemento dentro de una misma diapositiva, por ejemplo revelar las viñetas una a una.\n\nPara añadir una transición, abre la pestaña «Transiciones», selecciona una diapositiva en la columna izquierda y elige un efecto como «Desvanecer». El botón «Aplicar a todo» pone la misma transición en todas las diapositivas, para un resultado uniforme. Para una animación, selecciona primero el elemento (un título, una imagen), ve a la pestaña «Animaciones» y elige un efecto como «Aparecer».\n\nEl consejo más importante es la moderación. Un efecto discreto y único, repetido en todas partes, se ve profesional; efectos parpadeantes y distintos en cada diapositiva cansan y distraen al público de tu mensaje. Las animaciones deben servir al propósito — revelar una idea en el momento adecuado — nunca impresionar por sí mismas.\n\nUn uso especialmente útil es revelar las viñetas de una lista una a una: el público se concentra en el punto del que hablas, sin leer de antemano toda la diapositiva. Elige un efecto simple como «Aparecer» o «Desvanecer», y mantén el mismo de principio a fin para seguir siendo coherente.",
          },
          keyPoints: {
            fr: ["Transition = entre deux diapositives ; animation = dans une diapositive", "« Appliquer partout » pour une transition uniforme", "Modération : un effet discret fait plus pro que des effets partout", "Les animations révèlent une idée au bon moment, sans distraire"],
            ht: ["Tranzisyon = ant de diapozitiv ; animasyon = anndan yon diapozitiv", "« Appliquer partout » pou yon tranzisyon inifòm", "Modon : yon efè diskrè fè pi pwo pase efè toupatou", "Animasyon yo revele yon lide nan bon moman, san distrè"],
            en: ["Transition = between two slides; animation = within a slide", "\"Apply to All\" for a uniform transition", "Moderation: one discreet effect looks more pro than effects everywhere", "Animations reveal an idea at the right moment, without distracting"],
            es: ["Transición = entre dos diapositivas; animación = dentro de una diapositiva", "«Aplicar a todo» para una transición uniforme", "Moderación: un efecto discreto se ve más profesional que efectos por todas partes", "Las animaciones revelan una idea en el momento adecuado, sin distraer"],
          },
          exercise: {
            fr: "Ajoute la transition « Fondu » à une diapositive puis clique sur « Appliquer partout ». Sur une autre diapositive, fais apparaître les puces une par une avec l'animation « Apparaître », puis lance le diaporama pour observer le résultat.",
            ht: "Ajoute tranzisyon « Fondu » sou yon diapozitiv apre klike sou « Appliquer partout ». Sou yon lòt diapozitiv, fè puces yo parèt youn pa youn ak animasyon « Apparaître », apre lanse diaporama a pou gade rezilta a.",
            en: "Add the \"Fade\" transition to a slide then click \"Apply to All\". On another slide, reveal the bullets one by one with the \"Appear\" animation, then start the slideshow to observe the result.",
            es: "Añade la transición «Desvanecer» a una diapositiva y luego haz clic en «Aplicar a todo». En otra diapositiva, haz aparecer las viñetas una a una con la animación «Aparecer», luego inicia la presentación para observar el resultado.",
          },
        },
        {
          slug: "animer-les-elements",
          title: { fr: "Régler l'ordre et le minutage des animations", ht: "Regle lòd ak minitaj animasyon yo", en: "Controlling animation order and timing", es: "Controlar el orden y el tiempo de las animaciones" },
          videoId: "",
          content: {
            fr: "Une fois que tu maîtrises les animations simples, tu peux contrôler précisément quand et dans quel ordre chaque élément apparaît. L'outil clé s'appelle le « Volet Animation » : dans l'onglet « Animations », clique sur ce bouton et une liste s'ouvre à droite, montrant toutes les animations de la diapositive, dans l'ordre où elles se déclencheront.\n\nChaque animation peut se déclencher de trois façons, réglées dans la case « Démarrer ». « Au clic » attend que tu cliques pour la lancer : c'est le réglage le plus courant, car il te laisse maître du rythme. « Avec la précédente » lance l'animation en même temps que celle d'avant. « Après la précédente » l'enchaîne automatiquement, sans clic, juste après la fin de la précédente.\n\nDans le Volet Animation, tu peux réorganiser l'ordre en faisant glisser une ligne vers le haut ou le bas, exactement comme pour les diapositives. Tu peux aussi régler une « Durée » (la lenteur de l'effet) et un « Délai » (le temps d'attente avant qu'il démarre). Ces réglages fins évitent qu'un texte surgisse trop vite ou trop tard.\n\nUn même objet peut recevoir plusieurs animations : une « entrée » pour apparaître, une « sortie » pour disparaître ensuite. Le bouton « Aperçu » rejoue toute la séquence sans lancer le diaporama, ce qui te fait gagner du temps pour ajuster. Reste toujours mesuré : l'animation doit accompagner ton discours, pas voler la vedette.",
            ht: "Yon fwa ou metrize animasyon senp yo, ou ka kontwole ak presizyon kilè ak nan ki lòd chak eleman parèt. Zouti kle a rele « Volet Animation » : nan onglè « Animations », klike sou bouton sa a epi yon lis ouvri adwat, ki montre tout animasyon diapozitiv la, nan lòd yo pral deklanche.\n\nChak animasyon ka deklanche nan twa fason, ki regle nan kaz « Démarrer » a. « Au clic » tann pou ou klike anvan li lanse : se reglaj ki pi kouran an, paske li kite ou mèt ritm nan. « Avec la précédente » lanse animasyon an ansanm ak sa ki anvan an. « Après la précédente » chennen l otomatikman, san klik, jis apre sa ki anvan an fini.\n\nNan Volet Animation, ou ka reòganize lòd la lè w fè yon liy glise anwo oswa anba, egzakteman tankou pou diapozitiv yo. Ou ka tou regle yon « Durée » (vitès efè a) ak yon « Délai » (tan pou tann anvan li kòmanse). Reglaj fen sa yo anpeche yon tèks sòti twò vit oswa twò ta.\n\nYon menm objè ka resevwa plizyè animasyon : yon « entrée » pou parèt, yon « sortie » pou disparèt apre. Bouton « Aperçu » a rejwe tout sekans lan san lanse diaporama a, sa ki fè ou pran mwens tan pou ajiste. Rete toujou mezire : animasyon an dwe akonpaye diskou ou, pa vòlè vedèt la.",
            en: "Once you master simple animations, you can precisely control when and in what order each element appears. The key tool is called the \"Animation Pane\": in the \"Animations\" tab, click this button and a list opens on the right, showing all the slide's animations in the order they will fire.\n\nEach animation can start in three ways, set in the \"Start\" box. \"On Click\" waits for you to click before running: this is the most common setting, because it leaves you in control of the pace. \"With Previous\" starts the animation at the same time as the one before. \"After Previous\" chains it automatically, without a click, right after the previous one ends.\n\nIn the Animation Pane, you can reorder by dragging a line up or down, exactly like slides. You can also set a \"Duration\" (how slow the effect is) and a \"Delay\" (the wait before it starts). These fine settings prevent text from popping up too fast or too late.\n\nOne object can receive several animations: an \"entrance\" to appear, an \"exit\" to disappear afterward. The \"Preview\" button replays the whole sequence without launching the slideshow, saving you time to adjust. Always stay measured: the animation should accompany your speech, not steal the show.",
            es: "Una vez que dominas las animaciones simples, puedes controlar con precisión cuándo y en qué orden aparece cada elemento. La herramienta clave se llama «Panel de animación»: en la pestaña «Animaciones», haz clic en este botón y una lista se abre a la derecha, mostrando todas las animaciones de la diapositiva, en el orden en que se dispararán.\n\nCada animación puede iniciarse de tres maneras, ajustadas en la casilla «Iniciar». «Al hacer clic» espera a que hagas clic para lanzarla: es el ajuste más común, porque te deja al mando del ritmo. «Con la anterior» lanza la animación al mismo tiempo que la de antes. «Después de la anterior» la encadena automáticamente, sin clic, justo después de que termina la anterior.\n\nEn el Panel de animación, puedes reordenar arrastrando una línea hacia arriba o abajo, exactamente como las diapositivas. También puedes ajustar una «Duración» (la lentitud del efecto) y un «Retraso» (el tiempo de espera antes de que empiece). Estos ajustes finos evitan que un texto surja demasiado rápido o demasiado tarde.\n\nUn mismo objeto puede recibir varias animaciones: una «entrada» para aparecer, una «salida» para desaparecer después. El botón «Vista previa» reproduce toda la secuencia sin lanzar la presentación, lo que te ahorra tiempo para ajustar. Mantente siempre mesurado: la animación debe acompañar tu discurso, no robar el protagonismo.",
          },
          keyPoints: {
            fr: ["Le Volet Animation liste et ordonne toutes les animations", "Démarrer : au clic, avec la précédente ou après la précédente", "Durée et délai règlent la vitesse et l'attente d'un effet", "Aperçu rejoue la séquence sans lancer le diaporama"],
            ht: ["Volet Animation liste epi bay lòd tout animasyon yo", "Démarrer : au clic, avec la précédente oswa après la précédente", "Durée ak délai regle vitès ak tan tann yon efè", "Aperçu rejwe sekans lan san lanse diaporama a"],
            en: ["The Animation Pane lists and orders all animations", "Start: on click, with previous or after previous", "Duration and delay set an effect's speed and wait", "Preview replays the sequence without launching the slideshow"],
            es: ["El Panel de animación lista y ordena todas las animaciones", "Iniciar: al hacer clic, con la anterior o después de la anterior", "Duración y retraso ajustan la velocidad y la espera de un efecto", "Vista previa reproduce la secuencia sin lanzar la presentación"],
          },
          exercise: {
            fr: "Ouvre le Volet Animation sur une diapositive contenant un titre et deux puces. Règle le titre sur « Après la précédente » et les puces sur « Au clic », change l'ordre pour que le titre vienne en premier, puis clique sur Aperçu.",
            ht: "Ouvri Volet Animation sou yon diapozitiv ki gen yon tit ak de puces. Regle tit la sou « Après la précédente » epi puces yo sou « Au clic », chanje lòd la pou tit la vin an premye, apre klike sou Aperçu.",
            en: "Open the Animation Pane on a slide with a title and two bullets. Set the title to \"After Previous\" and the bullets to \"On Click\", change the order so the title comes first, then click Preview.",
            es: "Abre el Panel de animación en una diapositiva con un título y dos viñetas. Ajusta el título a «Después de la anterior» y las viñetas a «Al hacer clic», cambia el orden para que el título venga primero, luego haz clic en Vista previa.",
          },
        },
        {
          slug: "ajouter-son-et-video",
          title: { fr: "Ajouter du son et de la vidéo", ht: "Ajoute son ak videyo", en: "Adding sound and video", es: "Añadir sonido y video" },
          videoId: "",
          content: {
            fr: "Une présentation peut aussi contenir du son et de la vidéo, pour illustrer un propos de façon vivante. Tout se passe dans l'onglet « Insertion », à droite, avec les boutons « Audio » et « Vidéo ». Ces éléments s'ajoutent sur une diapositive comme une image, mais ils se lisent pendant le diaporama.\n\nPour insérer une vidéo enregistrée sur ton ordinateur, clique sur « Vidéo » puis « Vidéo sur mon PC », et choisis le fichier. La vidéo apparaît dans un cadre que tu peux redimensionner et déplacer. Un petit lecteur, avec un bouton de lecture, s'affiche dessous. Pour du son, « Audio » puis « Audio sur mon PC » ajoute une petite icône de haut-parleur, sur laquelle on clique pour écouter.\n\nQuand tu sélectionnes un son ou une vidéo, un onglet « Lecture » apparaît en haut. Il te permet de régler comment le média démarre : « Au clic » (tu cliques pour lancer) ou « Automatiquement » (dès que la diapositive s'affiche). Tu peux aussi régler le volume et couper les parties inutiles au début ou à la fin avec « Découper ».\n\nDeux précautions importantes. D'abord, une vidéo alourdit beaucoup le fichier : garde des extraits courts et vérifie que la présentation reste facile à copier ou à envoyer. Ensuite, teste toujours le son avant le jour J : assure-toi que les haut-parleurs de la salle fonctionnent et que le volume est suffisant, car un média muet gâche l'effet recherché.",
            ht: "Yon prezantasyon ka gen son ak videyo tou, pou ilistre yon pwopo nan yon fason vivan. Tout bagay fèt nan onglè « Insertion » a, adwat, ak bouton « Audio » ak « Vidéo ». Eleman sa yo ajoute sou yon diapozitiv tankou yon imaj, men yo jwe pandan diaporama a.\n\nPou mete yon videyo ki anrejistre sou òdinatè ou, klike sou « Vidéo » apre « Vidéo sur mon PC », epi chwazi fichye a. Videyo a parèt nan yon kad ou ka chanje gwosè epi deplase. Yon ti lektè, ak yon bouton lekti, afiche anba a. Pou son, « Audio » apre « Audio sur mon PC » ajoute yon ti ikòn opalè, ke ou klike sou li pou koute.\n\nLè ou chwazi yon son oswa yon videyo, yon onglè « Lecture » parèt anwo. Li pèmèt ou regle kijan medya a kòmanse : « Au clic » (ou klike pou lanse) oswa « Automatiquement » (depi diapozitiv la afiche). Ou ka tou regle volim nan epi koupe pati ki initil yo nan kòmansman oswa nan fen ak « Découper ».\n\nDe presksyon enpòtan. Dabò, yon videyo aloudi fichye a anpil : kenbe ekstrè kout epi verifye prezantasyon an rete fasil pou kopye oswa voye. Apre sa, teste toujou son an anvan gwo jou a : asire w opalè sal la mache epi volim nan sifi, paske yon medya bèbè gate efè w t ap chèche a.",
            en: "A presentation can also contain sound and video, to illustrate a point vividly. It all happens in the \"Insert\" tab, on the right, with the \"Audio\" and \"Video\" buttons. These elements are added to a slide like an image, but they play during the slideshow.\n\nTo insert a video saved on your computer, click \"Video\" then \"Video on my PC\", and choose the file. The video appears in a frame you can resize and move. A small player, with a play button, shows below it. For sound, \"Audio\" then \"Audio on my PC\" adds a small speaker icon, which you click to listen.\n\nWhen you select a sound or video, a \"Playback\" tab appears at the top. It lets you set how the media starts: \"On Click\" (you click to launch) or \"Automatically\" (as soon as the slide appears). You can also adjust the volume and cut off unnecessary parts at the start or end with \"Trim\".\n\nTwo important precautions. First, a video makes the file much heavier: keep clips short and check that the presentation stays easy to copy or send. Second, always test the sound before the big day: make sure the room's speakers work and the volume is enough, because a silent media ruins the intended effect.",
            es: "Una presentación también puede contener sonido y video, para ilustrar un punto de forma viva. Todo ocurre en la pestaña «Insertar», a la derecha, con los botones «Audio» y «Video». Estos elementos se añaden a una diapositiva como una imagen, pero se reproducen durante la presentación.\n\nPara insertar un video guardado en tu computadora, haz clic en «Video» y luego «Video en mi PC», y elige el archivo. El video aparece en un marco que puedes redimensionar y mover. Un pequeño reproductor, con un botón de reproducción, se muestra debajo. Para el sonido, «Audio» y luego «Audio en mi PC» añade un pequeño icono de altavoz, en el que se hace clic para escuchar.\n\nCuando seleccionas un sonido o un video, aparece una pestaña «Reproducción» arriba. Te permite ajustar cómo empieza el medio: «Al hacer clic» (haces clic para lanzarlo) o «Automáticamente» (en cuanto aparece la diapositiva). También puedes ajustar el volumen y cortar las partes innecesarias al principio o al final con «Recortar».\n\nDos precauciones importantes. Primero, un video hace el archivo mucho más pesado: mantén los clips cortos y comprueba que la presentación siga siendo fácil de copiar o enviar. Segundo, prueba siempre el sonido antes del gran día: asegúrate de que los altavoces de la sala funcionan y el volumen es suficiente, porque un medio mudo arruina el efecto buscado.",
          },
          keyPoints: {
            fr: ["Insertion > Audio ou Vidéo pour ajouter un média", "L'onglet Lecture règle le démarrage (au clic ou automatique)", "« Découper » enlève le début ou la fin inutiles", "La vidéo alourdit le fichier ; tester le son avant le jour J"],
            ht: ["Insertion > Audio oswa Vidéo pou ajoute yon medya", "Onglè Lecture regle demaraj (au clic oswa otomatik)", "« Découper » retire kòmansman oswa fen initil la", "Videyo aloudi fichye a ; teste son anvan gwo jou a"],
            en: ["Insert > Audio or Video to add a media", "The Playback tab sets the start (on click or automatic)", "\"Trim\" removes the useless start or end", "Video makes the file heavier; test the sound before the big day"],
            es: ["Insertar > Audio o Video para añadir un medio", "La pestaña Reproducción ajusta el inicio (al hacer clic o automático)", "«Recortar» quita el principio o el final inútiles", "El video hace el archivo más pesado; probar el sonido antes del gran día"],
          },
          exercise: {
            fr: "Insère une courte vidéo ou un fichier audio depuis ton ordinateur sur une diapositive. Dans l'onglet « Lecture », règle son démarrage sur « Au clic », baisse un peu le volume, puis lance le diaporama pour vérifier qu'il se lance bien.",
            ht: "Mete yon ti videyo oswa yon fichye son soti nan òdinatè ou sou yon diapozitiv. Nan onglè « Lecture », regle demaraj li sou « Au clic », bese volim nan yon ti kras, apre lanse diaporama a pou verifye li lanse byen.",
            en: "Insert a short video or an audio file from your computer on a slide. In the \"Playback\" tab, set its start to \"On Click\", lower the volume a little, then start the slideshow to check it launches properly.",
            es: "Inserta un video corto o un archivo de audio desde tu computadora en una diapositiva. En la pestaña «Reproducción», ajusta su inicio a «Al hacer clic», baja un poco el volumen, luego inicia la presentación para comprobar que se lanza bien.",
          },
        },
      ],
    },
    {
      title: { fr: "Présenter et partager", ht: "Prezante epi pataje", en: "Present and share", es: "Presentar y compartir" },
      lessons: [
        {
          slug: "mode-diaporama",
          title: { fr: "Lancer et piloter le diaporama", ht: "Lanse ak dirije diaporama a", en: "Starting and controlling the slideshow", es: "Iniciar y controlar la presentación" },
          videoId: "",
          content: {
            fr: "Une fois tes diapositives prêtes, il faut les présenter en plein écran : c'est le mode « Diaporama ». Pour le lancer, appuie sur la touche F5 pour commencer à la première diapositive, ou clique sur l'icône diaporama en bas de la fenêtre pour démarrer à la diapositive actuelle. L'écran se remplit entièrement avec ta première diapositive, sans les menus.\n\nPour avancer, appuie sur la barre d'espace, sur la flèche droite ou clique simplement avec la souris ; chaque appui passe à la diapositive ou à l'animation suivante. La flèche gauche revient en arrière. Pour quitter le diaporama à tout moment, appuie sur la touche Échap (Esc) : tu reviens à l'écran de travail.\n\nUn outil très utile est le « Mode Présentateur ». Si tu es branché à un projecteur, il affiche sur ton écran à toi tes notes, la diapositive suivante et un minuteur, tandis que le public ne voit que la diapositive en cours. Cela t'aide à garder le fil sans lire l'écran de projection, et à gérer ton temps avec assurance.\n\nPendant le diaporama, tu peux taper le numéro d'une diapositive puis Entrée pour y sauter directement, ou appuyer sur la touche B pour afficher un écran noir quand tu veux capter l'attention sur tes paroles. Ces petits raccourcis te donnent le contrôle total du déroulement, sans jamais quitter le plein écran.",
            ht: "Yon fwa diapozitiv ou yo pare, ou dwe prezante yo an plen ekran : se mòd « Diaporama » a. Pou lanse l, peze bouton F5 pou kòmanse nan premye diapozitiv la, oswa klike sou ikòn diaporama anba fenèt la pou kòmanse nan diapozitiv aktyèl la. Ekran an ranpli nèt ak premye diapozitiv ou, san meni yo.\n\nPou avanse, peze bar espas la, flèch dwat la oswa klike senpleman ak sourit la ; chak peze pase nan diapozitiv oswa animasyon ki vin apre a. Flèch goch la tounen anyè. Pou kite diaporama nenpòt kilè, peze bouton Échap (Esc) : ou retounen nan ekran travay la.\n\nYon zouti ki itil anpil se « Mode Présentateur » a. Si ou branche sou yon pwojektè, li montre sou pwòp ekran pa ou nòt ou yo, pwochen diapozitiv la ak yon minitè, pandan piblik la wè sèlman diapozitiv aktyèl la. Sa ede ou kenbe fil la san li ekran pwojeksyon an, epi jere tan ou ak konfyans.\n\nPandan diaporama a, ou ka tape nimewo yon diapozitiv apre Entrée pou sote dirèkteman ladan, oswa peze bouton B pou afiche yon ekran nwa lè ou vle atire atansyon sou pawòl ou. Ti rakousi sa yo ba ou kontwòl total sou deroulman an, san janm kite plen ekran an.",
            en: "Once your slides are ready, you present them in full screen: this is \"Slideshow\" mode. To start it, press the F5 key to begin at the first slide, or click the slideshow icon at the bottom of the window to start at the current slide. The screen fills entirely with your first slide, without the menus.\n\nTo move forward, press the space bar, the right arrow or simply click with the mouse; each press moves to the next slide or animation. The left arrow goes back. To leave the slideshow at any time, press the Escape (Esc) key: you return to the working screen.\n\nA very useful tool is \"Presenter View\". If you are connected to a projector, it shows on your own screen your notes, the next slide and a timer, while the audience sees only the current slide. This helps you keep your train of thought without reading the projection screen, and manage your time with confidence.\n\nDuring the slideshow, you can type a slide number then Enter to jump straight to it, or press the B key to show a black screen when you want to draw attention to your words. These small shortcuts give you total control of the flow, without ever leaving full screen.",
            es: "Una vez listas tus diapositivas, hay que presentarlas a pantalla completa: es el modo «Presentación». Para iniciarlo, pulsa la tecla F5 para empezar en la primera diapositiva, o haz clic en el icono de presentación en la parte inferior de la ventana para empezar en la diapositiva actual. La pantalla se llena por completo con tu primera diapositiva, sin los menús.\n\nPara avanzar, pulsa la barra espaciadora, la flecha derecha o simplemente haz clic con el ratón; cada pulsación pasa a la siguiente diapositiva o animación. La flecha izquierda retrocede. Para salir de la presentación en cualquier momento, pulsa la tecla Escape (Esc): vuelves a la pantalla de trabajo.\n\nUna herramienta muy útil es la «Vista del moderador». Si estás conectado a un proyector, muestra en tu propia pantalla tus notas, la siguiente diapositiva y un cronómetro, mientras que el público solo ve la diapositiva actual. Esto te ayuda a no perder el hilo sin leer la pantalla de proyección, y a gestionar tu tiempo con seguridad.\n\nDurante la presentación, puedes escribir el número de una diapositiva y luego Enter para saltar directamente a ella, o pulsar la tecla B para mostrar una pantalla negra cuando quieras captar la atención sobre tus palabras. Estos pequeños atajos te dan el control total del desarrollo, sin salir nunca de la pantalla completa.",
          },
          keyPoints: {
            fr: ["F5 lance le diaporama en plein écran ; Échap pour quitter", "Espace / flèche droite / clic pour avancer, flèche gauche pour reculer", "Le Mode Présentateur montre tes notes et la diapo suivante", "L'icône diaporama en bas démarre à la diapositive actuelle"],
            ht: ["F5 lanse diaporama an plen ekran ; Échap pou kite", "Espas / flèch dwat / klik pou avanse, flèch goch pou rekile", "Mode Présentateur montre nòt ou ak pwochen diapo a", "Ikòn diaporama anba a kòmanse nan diapozitiv aktyèl la"],
            en: ["F5 starts the slideshow full screen; Esc to exit", "Space / right arrow / click to advance, left arrow to go back", "Presenter View shows your notes and the next slide", "The slideshow icon at the bottom starts at the current slide"],
            es: ["F5 inicia la presentación a pantalla completa; Esc para salir", "Espacio / flecha derecha / clic para avanzar, flecha izquierda para retroceder", "La Vista del moderador muestra tus notas y la siguiente diapositiva", "El icono de presentación abajo inicia en la diapositiva actual"],
          },
          exercise: {
            fr: "Lance ton diaporama avec F5, avance avec la barre d'espace jusqu'à la fin, puis reviens en arrière avec la flèche gauche. Active enfin le Mode Présentateur et repère où s'affichent tes notes et la diapositive suivante.",
            ht: "Lanse diaporama ou ak F5, avanse ak bar espas la jiska fen, apre tounen anyè ak flèch goch la. Anfen aktive Mode Présentateur epi jwenn kote nòt ou yo ak pwochen diapozitiv la afiche.",
            en: "Start your slideshow with F5, advance with the space bar to the end, then go back with the left arrow. Finally enable Presenter View and locate where your notes and the next slide appear.",
            es: "Inicia tu presentación con F5, avanza con la barra espaciadora hasta el final, luego retrocede con la flecha izquierda. Por último, activa la Vista del moderador y localiza dónde aparecen tus notas y la siguiente diapositiva.",
          },
        },
        {
          slug: "exporter-et-partager",
          title: { fr: "Enregistrer, exporter et partager", ht: "Anrejistre, ekspòte epi pataje", en: "Saving, exporting and sharing", es: "Guardar, exportar y compartir" },
          videoId: "",
          content: {
            fr: "Une fois ton travail terminé, il faut l'enregistrer pour ne pas le perdre. Va dans le menu « Fichier » puis « Enregistrer sous », choisis un dossier et donne un nom clair au fichier. PowerPoint enregistre au format « .pptx » : c'est le format modifiable, celui que tu rouvriras pour continuer à travailler. Enregistre souvent, ou active « Enregistrement automatique » si ta version le propose.\n\nSelon ce que tu veux faire, un autre format est parfois préférable. Pour envoyer ta présentation à quelqu'un qui n'a pas PowerPoint, exporte-la en « PDF » : chacun peut l'ouvrir, les diapositives gardent leur apparence exacte, mais on ne peut plus les modifier. Va dans « Fichier » puis « Exporter » et choisis « Créer un document PDF ».\n\nD'autres exports sont utiles selon le besoin. Le format « diaporama » (.ppsx) ouvre le fichier directement en plein écran, prêt à présenter. Tu peux aussi exporter chaque diapositive en image (PNG ou JPG) pour l'utiliser ailleurs, ou même créer une vidéo de la présentation qui se déroule toute seule, très pratique à publier ou à envoyer.\n\nEnfin, pour travailler à plusieurs ou présenter à distance, enregistre le fichier sur un espace en ligne comme OneDrive : tu obtiens un lien à partager, et plusieurs personnes peuvent ouvrir la même présentation. Pense aussi à l'impression : « Fichier » puis « Imprimer » permet de sortir des « documents » avec plusieurs diapositives par page, utiles à distribuer au public.",
            ht: "Yon fwa travay ou fini, ou dwe anrejistre l pou pa pèdi l. Ale nan meni « Fichier » apre « Enregistrer sous », chwazi yon dosye epi bay fichye a yon non klè. PowerPoint anrejistre nan fòma « .pptx » : se fòma ki ka modifye a, sa ou pral rouvri pou kontinye travay. Anrejistre souvan, oswa aktive « Enregistrement automatique » si vèsyon ou an pwopoze l.\n\nSelon sa ou vle fè, yon lòt fòma pafwa pi bon. Pou voye prezantasyon ou bay yon moun ki pa gen PowerPoint, ekspòte l an « PDF » : tout moun ka ouvri l, diapozitiv yo kenbe aparans egzak yo, men yo pa ka modifye yo ankò. Ale nan « Fichier » apre « Exporter » epi chwazi « Créer un document PDF ».\n\nGen lòt ekspò ki itil selon bezwen an. Fòma « diaporama » (.ppsx) ouvri fichye a dirèkteman an plen ekran, pare pou prezante. Ou ka tou ekspòte chak diapozitiv an imaj (PNG oswa JPG) pou sèvi ak li lòt kote, oswa menm kreye yon videyo prezantasyon an ki dewoule pou kont li, trè pratik pou pibliye oswa voye.\n\nAnfen, pou travay ak plizyè moun oswa prezante a distans, anrejistre fichye a sou yon espas anliy tankou OneDrive : ou jwenn yon lyen pou pataje, epi plizyè moun ka ouvri menm prezantasyon an. Panse tou ak enprime : « Fichier » apre « Imprimer » pèmèt sòti « documents » ak plizyè diapozitiv pou chak paj, itil pou distribye bay piblik la.",
            en: "Once your work is finished, you must save it so you do not lose it. Go to the \"File\" menu then \"Save As\", choose a folder and give the file a clear name. PowerPoint saves in the \".pptx\" format: this is the editable format, the one you will reopen to keep working. Save often, or turn on \"AutoSave\" if your version offers it.\n\nDepending on what you want to do, another format is sometimes preferable. To send your presentation to someone who does not have PowerPoint, export it as a \"PDF\": everyone can open it, the slides keep their exact look, but they can no longer be edited. Go to \"File\" then \"Export\" and choose \"Create PDF Document\".\n\nOther exports are useful depending on the need. The \"slideshow\" format (.ppsx) opens the file directly in full screen, ready to present. You can also export each slide as an image (PNG or JPG) to use elsewhere, or even create a video of the presentation that plays on its own, very handy to publish or send.\n\nFinally, to work with several people or present remotely, save the file to an online space like OneDrive: you get a link to share, and several people can open the same presentation. Also think about printing: \"File\" then \"Print\" lets you output \"handouts\" with several slides per page, useful to hand out to the audience.",
            es: "Una vez terminado tu trabajo, hay que guardarlo para no perderlo. Ve al menú «Archivo» y luego «Guardar como», elige una carpeta y dale un nombre claro al archivo. PowerPoint guarda en el formato «.pptx»: es el formato editable, el que reabrirás para seguir trabajando. Guarda a menudo, o activa «Autoguardado» si tu versión lo ofrece.\n\nSegún lo que quieras hacer, otro formato a veces es preferible. Para enviar tu presentación a alguien que no tiene PowerPoint, expórtala como «PDF»: todos pueden abrirla, las diapositivas conservan su aspecto exacto, pero ya no se pueden modificar. Ve a «Archivo» y luego «Exportar» y elige «Crear documento PDF».\n\nOtras exportaciones son útiles según la necesidad. El formato «presentación» (.ppsx) abre el archivo directamente a pantalla completa, listo para presentar. También puedes exportar cada diapositiva como imagen (PNG o JPG) para usarla en otro lugar, o incluso crear un video de la presentación que se desarrolla solo, muy práctico para publicar o enviar.\n\nPor último, para trabajar entre varios o presentar a distancia, guarda el archivo en un espacio en línea como OneDrive: obtienes un enlace para compartir, y varias personas pueden abrir la misma presentación. Piensa también en la impresión: «Archivo» y luego «Imprimir» permite sacar «documentos» con varias diapositivas por página, útiles para repartir al público.",
          },
          keyPoints: {
            fr: ["Fichier > Enregistrer sous : le .pptx reste modifiable", "Exporter en PDF pour un fichier lisible par tous, non modifiable", "Exports possibles : diaporama (.ppsx), images, vidéo", "En ligne (OneDrive) : lien de partage ; Imprimer pour des documents"],
            ht: ["Fichier > Enregistrer sous : .pptx la rete modifyab", "Ekspòte an PDF pou yon fichye tout moun ka li, ki pa modifyab", "Ekspò posib : diaporama (.ppsx), imaj, videyo", "Anliy (OneDrive) : lyen pataj ; Imprimer pou documents"],
            en: ["File > Save As: the .pptx stays editable", "Export to PDF for a file everyone can read, not editable", "Possible exports: slideshow (.ppsx), images, video", "Online (OneDrive): share link; Print for handouts"],
            es: ["Archivo > Guardar como: el .pptx sigue editable", "Exportar a PDF para un archivo que todos pueden leer, no editable", "Exportaciones posibles: presentación (.ppsx), imágenes, video", "En línea (OneDrive): enlace para compartir; Imprimir para documentos"],
          },
          exercise: {
            fr: "Enregistre ta présentation au format .pptx avec un nom clair, puis exporte-la en PDF via « Fichier > Exporter ». Ouvre le PDF pour vérifier que les diapositives gardent bien leur apparence, et repère l'option « Imprimer » des documents.",
            ht: "Anrejistre prezantasyon ou an fòma .pptx ak yon non klè, apre ekspòte l an PDF atravè « Fichier > Exporter ». Ouvri PDF la pou verifye diapozitiv yo kenbe aparans yo byen, epi jwenn opsyon « Imprimer » documents yo.",
            en: "Save your presentation in .pptx format with a clear name, then export it as a PDF via \"File > Export\". Open the PDF to check that the slides keep their look, and find the \"Print\" handouts option.",
            es: "Guarda tu presentación en formato .pptx con un nombre claro, luego expórtala como PDF mediante «Archivo > Exportar». Abre el PDF para comprobar que las diapositivas conservan su aspecto, y localiza la opción «Imprimir» documentos.",
          },
        },
        {
          slug: "reussir-sa-presentation",
          title: { fr: "Réussir sa présentation orale", ht: "Reyisi prezantasyon alowal ou", en: "Delivering a successful talk", es: "Lograr una buena exposición oral" },
          videoId: "",
          content: {
            fr: "Les diapositives ne sont qu'un support : c'est toi, l'orateur, qui portes le message. La meilleure présentation échoue si l'on se contente de lire l'écran à voix haute. Les diapositives donnent les grandes idées ; ton rôle est de les expliquer, de les illustrer par des exemples et de faire le lien entre elles.\n\nPrépare-toi en répétant à voix haute, si possible plusieurs fois, en te chronométrant. Cela te donne de l'assurance, révèle les passages trop longs et t'évite de découvrir les problèmes devant le public. Connaître ta première et ta dernière phrase par cœur aide à démarrer et à conclure avec force.\n\nLe jour venu, regarde ton public plutôt que l'écran, parle lentement et clairement, et fais des pauses. Une diapositive doit apparaître au moment où tu en parles, pas avant. Termine par une diapositive de conclusion qui résume l'essentiel et, s'il y a lieu, invite aux questions.\n\nGère aussi le trac : respire profondément avant de commencer, tiens-toi droit et souris. Si tu perds le fil, un simple coup d'œil à tes notes en Mode Présentateur suffit à te reprendre. Souviens-toi : une présentation claire et sincère vaut mieux qu'une présentation surchargée d'effets. Ce n'est pas la perfection qui touche le public, mais la conviction avec laquelle tu portes ton message.",
            ht: "Diapozitiv yo se yon sipò sèlman : se ou menm, oratè a, ki pote mesaj la. Pi bon prezantasyon an echwe si ou jis li ekran an awotvwa. Diapozitiv yo bay gwo lide yo ; wòl ou se eksplike yo, ilistre yo ak egzanp epi fè lyen ant yo.\n\nPrepare tèt ou lè w repete awotvwa, si posib plizyè fwa, epi mezire tan ou. Sa ba ou konfyans, montre pasaj ki twò long yo epi anpeche ou dekouvri pwoblèm yo devan piblik la. Konnen premye ak dènye fraz ou pa kè ede ou kòmanse epi konkli ak fòs.\n\nJou a rive, gade piblik ou olye ekran an, pale dousman epi klè, epi fè poz. Yon diapozitiv dwe parèt nan moman w ap pale de li a, pa anvan. Fini ak yon diapozitiv konklizyon ki rezime esansyèl la epi, si sa nesesè, envite kesyon.\n\nJere kè sote a tou : respire fon anvan ou kòmanse, kanpe dwat epi souri. Si ou pèdi fil la, yon senp kout je sou nòt ou nan Mode Présentateur ase pou reprann ou. Sonje : yon prezantasyon klè epi sensè pi bon pase yon prezantasyon ki chaje ak efè. Se pa pèfeksyon ki touche piblik la, men konviksyon avèk ki ou pote mesaj ou.",
            en: "The slides are only a support: it is you, the speaker, who carries the message. The best presentation fails if you just read the screen aloud. The slides give the main ideas; your role is to explain them, illustrate them with examples and connect them together.\n\nPrepare by rehearsing aloud, if possible several times, timing yourself. This gives you confidence, reveals passages that run too long and keeps you from discovering problems in front of the audience. Knowing your first and last sentence by heart helps you start and finish strongly.\n\nWhen the day comes, look at your audience rather than the screen, speak slowly and clearly, and pause. A slide should appear at the moment you talk about it, not before. End with a conclusion slide that sums up the essentials and, if appropriate, invites questions.\n\nAlso manage stage fright: breathe deeply before you start, stand up straight and smile. If you lose your train of thought, a simple glance at your notes in Presenter View is enough to recover. Remember: a clear, sincere presentation is worth more than one overloaded with effects. It is not perfection that touches the audience, but the conviction with which you carry your message.",
            es: "Las diapositivas son solo un apoyo: eres tú, el orador, quien lleva el mensaje. La mejor presentación fracasa si te limitas a leer la pantalla en voz alta. Las diapositivas dan las grandes ideas; tu papel es explicarlas, ilustrarlas con ejemplos y conectarlas entre sí.\n\nPrepárate ensayando en voz alta, si es posible varias veces, cronometrándote. Esto te da seguridad, revela los pasajes demasiado largos y te evita descubrir los problemas delante del público. Saber de memoria tu primera y tu última frase ayuda a empezar y a concluir con fuerza.\n\nLlegado el día, mira a tu público en vez de la pantalla, habla despacio y claro, y haz pausas. Una diapositiva debe aparecer en el momento en que hablas de ella, no antes. Termina con una diapositiva de conclusión que resuma lo esencial y, si procede, invite a preguntas.\n\nGestiona también los nervios: respira profundamente antes de empezar, mantente derecho y sonríe. Si pierdes el hilo, un simple vistazo a tus notas en la Vista del moderador basta para recuperarte. Recuerda: una presentación clara y sincera vale más que una sobrecargada de efectos. No es la perfección lo que conmueve al público, sino la convicción con la que llevas tu mensaje.",
          },
          keyPoints: {
            fr: ["Les diapos soutiennent ; c'est l'orateur qui porte le message", "Répéter à voix haute et se chronométrer avant le jour J", "Regarder le public, parler lentement, finir par une conclusion", "Une diapositive apparaît au moment où tu en parles, pas avant"],
            ht: ["Diapo yo sipòte ; se oratè a ki pote mesaj la", "Repete awotvwa epi mezire tan anvan gwo jou a", "Gade piblik la, pale dousman, fini ak yon konklizyon", "Yon diapozitiv parèt nan moman w ap pale de li a, pa anvan"],
            en: ["Slides support; the speaker carries the message", "Rehearse aloud and time yourself before the big day", "Look at the audience, speak slowly, end with a conclusion", "A slide appears at the moment you talk about it, not before"],
            es: ["Las diapositivas apoyan; el orador lleva el mensaje", "Ensayar en voz alta y cronometrarse antes del gran día", "Mirar al público, hablar despacio, terminar con una conclusión", "Una diapositiva aparece en el momento en que hablas de ella, no antes"],
          },
          exercise: {
            fr: "Répète ta présentation à voix haute en te chronométrant. Note la durée, repère une diapositive trop chargée à alléger, et apprends par cœur ta première et ta dernière phrase.",
            ht: "Repete prezantasyon ou awotvwa epi mezire tan ou. Note dire a, jwenn yon diapozitiv ki twò chaje pou alèje, epi aprann premye ak dènye fraz ou pa kè.",
            en: "Rehearse your presentation aloud while timing yourself. Note the duration, spot a slide that is too crowded to lighten, and learn your first and last sentence by heart.",
            es: "Ensaya tu presentación en voz alta cronometrándote. Anota la duración, detecta una diapositiva demasiado cargada para aligerarla, y aprende de memoria tu primera y tu última frase.",
          },
        },
      ],
    },
  ],
};

export default powerpoint;
