import { CourseContent } from "./types";

const word: CourseContent = {
  slug: "word",
  intro: {
    fr: "Apprendre à utiliser Microsoft Word pour créer, mettre en forme, illustrer et imprimer des documents professionnels, pas à pas.",
    ht: "Aprann sèvi ak Microsoft Word pou kreye, byen ranje, ilistre ak enprime dokiman pwofesyonèl, etap pa etap.",
    en: "Learn to use Microsoft Word to create, format, illustrate and print professional documents, step by step.",
    es: "Aprender a usar Microsoft Word para crear, dar formato, ilustrar e imprimir documentos profesionales, paso a paso.",
  },
  modules: [
    {
      title: { fr: "Découvrir Word et les documents", ht: "Dekouvri Word ak dokiman yo", en: "Discovering Word and documents", es: "Descubrir Word y los documentos" },
      lessons: [
        {
          slug: "creer-enregistrer-document",
          title: { fr: "Créer et enregistrer un document", ht: "Kreye ak anrejistre yon dokiman", en: "Creating and saving a document", es: "Crear y guardar un documento" },
          videoId: "",
          content: {
            fr: "Microsoft Word est un logiciel de traitement de texte : il sert à écrire des lettres, des rapports, des CV ou tout document composé de texte. Quand tu ouvres Word, choisis « Document vierge » pour partir d'une page blanche, ou un modèle déjà prêt (lettre, CV) si tu veux gagner du temps. La grande zone blanche au centre est la page où tu tapes ton texte.\n\nPour écrire, clique dans la page et commence à taper au clavier. Le curseur clignotant indique où le texte va s'insérer. Appuie sur la touche Entrée pour aller à la ligne et commencer un nouveau paragraphe. Si tu fais une erreur, la touche Retour arrière efface le caractère à gauche du curseur.\n\nEnregistrer ton travail est essentiel pour ne rien perdre. Va dans le menu « Fichier » puis « Enregistrer sous », choisis un dossier, donne un nom clair à ton document (par exemple « Lettre-Marie »), et clique sur « Enregistrer ». Word crée alors un fichier avec l'extension .docx.\n\nEnsuite, pense à enregistrer souvent avec le raccourci Ctrl+S (Cmd+S sur Mac). Prends l'habitude d'appuyer sur Ctrl+S après chaque paragraphe important : ainsi, même en cas de coupure de courant, tu ne perds presque rien de ton travail.",
            ht: "Microsoft Word se yon lojisyèl pou trete tèks : li sèvi pou ekri lèt, rapò, CV oswa nenpòt dokiman ki gen tèks ladan. Lè ou ouvri Word, chwazi « Document vierge » (dokiman vid) pou kòmanse ak yon paj blan, oswa yon modèl ki deja pare (lèt, CV) si ou vle pran mwens tan. Gwo zòn blan nan mitan an se paj kote ou tape tèks ou.\n\nPou ekri, klike nan paj la epi kòmanse tape sou klavye a. Kurseur k ap klete a montre kote tèks la pral antre. Peze bouton Entrée a pou desann yon liy epi kòmanse yon nouvo paragraf. Si ou fè yon erè, bouton Retour arrière a efase lèt ki agoch kurseur a.\n\nAnrejistre travay ou enpòtan anpil pou ou pa pèdi anyen. Ale nan meni « Fichier » epi « Enregistrer sous », chwazi yon dosye, bay dokiman an yon non klè (pa egzanp « Lèt-Mari »), epi klike sou « Enregistrer ». Konsa Word kreye yon fichye ki gen ekstansyon .docx.\n\nApre sa, sonje anrejistre souvan ak rakoursi Ctrl+S (Cmd+S sou Mac). Pran abitid peze Ctrl+S apre chak paragraf enpòtan : konsa, menm si kouran koupe, ou preske pa pèdi anyen nan travay ou.",
            en: "Microsoft Word is a word-processing program: it is used to write letters, reports, resumes or any document made of text. When you open Word, choose \"Blank document\" to start from an empty page, or a ready-made template (letter, resume) to save time. The large white area in the center is the page where you type your text.\n\nTo write, click on the page and start typing on the keyboard. The blinking cursor shows where text will be inserted. Press the Enter key to move to a new line and start a new paragraph. If you make a mistake, the Backspace key erases the character to the left of the cursor.\n\nSaving your work is essential so you don't lose anything. Go to the \"File\" menu, then \"Save As\", choose a folder, give your document a clear name (for example \"Letter-Mary\"), and click \"Save\". Word then creates a file with the .docx extension.\n\nAfter that, remember to save often with the shortcut Ctrl+S (Cmd+S on Mac). Get into the habit of pressing Ctrl+S after each important paragraph: that way, even if the power goes out, you lose almost nothing of your work.",
            es: "Microsoft Word es un programa de procesamiento de texto: sirve para escribir cartas, informes, currículums o cualquier documento formado por texto. Cuando abres Word, elige «Documento en blanco» para empezar desde una página vacía, o una plantilla ya lista (carta, currículum) si quieres ahorrar tiempo. La gran zona blanca del centro es la página donde escribes tu texto.\n\nPara escribir, haz clic en la página y empieza a teclear. El cursor parpadeante indica dónde se insertará el texto. Pulsa la tecla Enter para pasar a una nueva línea y empezar un nuevo párrafo. Si cometes un error, la tecla Retroceso borra el carácter a la izquierda del cursor.\n\nGuardar tu trabajo es esencial para no perder nada. Ve al menú «Archivo», luego «Guardar como», elige una carpeta, dale un nombre claro a tu documento (por ejemplo «Carta-María») y haz clic en «Guardar». Word crea entonces un archivo con la extensión .docx.\n\nDespués, acuérdate de guardar a menudo con el atajo Ctrl+S (Cmd+S en Mac). Adopta la costumbre de pulsar Ctrl+S después de cada párrafo importante: así, aunque se corte la luz, no pierdes casi nada de tu trabajo.",
          },
          keyPoints: {
            fr: ["Word sert à créer des documents texte (lettres, rapports, CV)", "Cliquer dans la page pour taper ; Entrée = nouveau paragraphe", "Enregistrer avec Fichier > Enregistrer sous, puis Ctrl+S souvent", "Un document Word porte l'extension .docx"],
            ht: ["Word sèvi pou kreye dokiman tèks (lèt, rapò, CV)", "Klike nan paj la pou tape ; Entrée = nouvo paragraf", "Anrejistre ak Fichier > Enregistrer sous, epi Ctrl+S souvan", "Yon dokiman Word gen ekstansyon .docx"],
            en: ["Word is used to create text documents (letters, reports, resumes)", "Click on the page to type; Enter = new paragraph", "Save with File > Save As, then Ctrl+S often", "A Word document has the .docx extension"],
            es: ["Word sirve para crear documentos de texto (cartas, informes, CV)", "Haz clic en la página para escribir; Enter = nuevo párrafo", "Guarda con Archivo > Guardar como, luego Ctrl+S a menudo", "Un documento de Word tiene la extensión .docx"],
          },
          exercise: {
            fr: "Ouvre Word, choisis « Document vierge » et tape une courte lettre de trois lignes à un ami. Enregistre-la sous le nom « Ma-premiere-lettre » dans le dossier Documents, puis ajoute une quatrième ligne et appuie sur Ctrl+S pour enregistrer la modification.",
            ht: "Ouvri Word, chwazi « Document vierge » epi tape yon ti lèt twa liy pou yon zanmi. Anrejistre l sou non « Premye-lèt-mwen » nan dosye Documents la, epi ajoute yon katriyèm liy epi peze Ctrl+S pou anrejistre chanjman an.",
            en: "Open Word, choose \"Blank document\" and type a short three-line letter to a friend. Save it as \"My-first-letter\" in the Documents folder, then add a fourth line and press Ctrl+S to save the change.",
            es: "Abre Word, elige «Documento en blanco» y escribe una carta corta de tres líneas a un amigo. Guárdala con el nombre «Mi-primera-carta» en la carpeta Documentos, luego añade una cuarta línea y pulsa Ctrl+S para guardar el cambio.",
          },
        },
        {
          slug: "se-reperer-ruban",
          title: { fr: "Se repérer dans le ruban et les onglets", ht: "Byen jwenn wout ou nan ruban an", en: "Finding your way in the ribbon and tabs", es: "Orientarse en la cinta y las pestañas" },
          videoId: "",
          content: {
            fr: "En haut de la fenêtre de Word se trouve le « ruban » : une barre remplie de boutons, organisée en onglets. Chaque onglet regroupe des outils qui vont ensemble. L'onglet « Accueil » contient la mise en forme du texte (gras, taille, couleur). L'onglet « Insertion » sert à ajouter des images, tableaux ou pages. L'onglet « Mise en page » gère les marges et l'orientation de la page.\n\nPour utiliser un bouton, il suffit de cliquer dessus. Beaucoup de boutons agissent sur le texte que tu as d'abord sélectionné. Pour sélectionner du texte, clique juste avant le premier mot, maintiens le bouton de la souris enfoncé et glisse jusqu'à la fin : le texte apparaît alors surligné en bleu.\n\nEn haut à gauche se trouve la « barre d'outils Accès rapide », avec les boutons les plus utilisés comme Enregistrer. Juste au-dessus des onglets, la barre de titre affiche le nom de ton document.\n\nDeux outils sont à connaître dès le début : la flèche « Annuler » (en haut à gauche, ou Ctrl+Z) qui revient en arrière si tu te trompes, et « Rétablir » qui refait l'action annulée. N'aie pas peur d'expérimenter : tu peux toujours annuler.",
            ht: "Anwo fenèt Word la gen « ruban » an : yon bar ki plen ak bouton, ki òganize an onglè. Chak onglè gwoupe zouti ki ale ansanm. Onglè « Accueil » la gen mizanfòm tèks la (gra, gwosè, koulè). Onglè « Insertion » la sèvi pou ajoute imaj, tablo oswa paj. Onglè « Mise en page » la jere maj yo ak oryantasyon paj la.\n\nPou sèvi ak yon bouton, ou jis klike sou li. Anpil bouton aji sou tèks ou chwazi anvan an. Pou chwazi tèks, klike jis anvan premye mo a, kenbe bouton sourit la peze epi glise jouk nan fen an : tèks la ap parèt make an ble.\n\nAnwo agoch gen « barre d'outils Accès rapide » la, ak bouton yo pi sèvi yo tankou Enregistrer. Jis anwo onglè yo, bar tit la montre non dokiman ou.\n\nGen de zouti pou ou konnen depi nan kòmansman : flèch « Annuler » a (anwo agoch, oswa Ctrl+Z) ki tounen anyè si ou fè yon erè, ak « Rétablir » ki refè aksyon ou te anile a. Pa pè eseye : ou ka toujou anile.",
            en: "At the top of the Word window is the \"ribbon\": a bar full of buttons, organized into tabs. Each tab groups tools that belong together. The \"Home\" tab contains text formatting (bold, size, color). The \"Insert\" tab is used to add images, tables or pages. The \"Layout\" tab manages margins and page orientation.\n\nTo use a button, simply click it. Many buttons act on the text you have first selected. To select text, click just before the first word, hold down the mouse button and drag to the end: the text then appears highlighted in blue.\n\nAt the top left is the \"Quick Access Toolbar\", with the most-used buttons such as Save. Just above the tabs, the title bar shows the name of your document.\n\nTwo tools are worth knowing from the start: the \"Undo\" arrow (top left, or Ctrl+Z), which goes back if you make a mistake, and \"Redo\", which repeats the undone action. Don't be afraid to experiment: you can always undo.",
            es: "En la parte superior de la ventana de Word está la «cinta»: una barra llena de botones, organizada en pestañas. Cada pestaña agrupa herramientas que van juntas. La pestaña «Inicio» contiene el formato del texto (negrita, tamaño, color). La pestaña «Insertar» sirve para añadir imágenes, tablas o páginas. La pestaña «Diseño de página» gestiona los márgenes y la orientación de la página.\n\nPara usar un botón, basta con hacer clic en él. Muchos botones actúan sobre el texto que hayas seleccionado antes. Para seleccionar texto, haz clic justo antes de la primera palabra, mantén pulsado el botón del ratón y arrastra hasta el final: el texto aparecerá resaltado en azul.\n\nArriba a la izquierda está la «barra de herramientas de acceso rápido», con los botones más usados como Guardar. Justo encima de las pestañas, la barra de título muestra el nombre de tu documento.\n\nDos herramientas conviene conocer desde el principio: la flecha «Deshacer» (arriba a la izquierda, o Ctrl+Z), que retrocede si te equivocas, y «Rehacer», que repite la acción deshecha. No tengas miedo de experimentar: siempre puedes deshacer.",
          },
          keyPoints: {
            fr: ["Le ruban est organisé en onglets (Accueil, Insertion, Mise en page)", "Sélectionner le texte en glissant avant d'appliquer un outil", "Ctrl+Z annule une erreur, Ctrl+Y la rétablit", "La barre d'accès rapide garde les boutons les plus utiles"],
            ht: ["Ruban an òganize an onglè (Accueil, Insertion, Mise en page)", "Chwazi tèks la lè w glise anvan ou aplike yon zouti", "Ctrl+Z anile yon erè, Ctrl+Y refè l", "Bar aksè rapid la kenbe bouton ki pi itil yo"],
            en: ["The ribbon is organized in tabs (Home, Insert, Layout)", "Select text by dragging before applying a tool", "Ctrl+Z undoes a mistake, Ctrl+Y redoes it", "The Quick Access Toolbar keeps the most useful buttons"],
            es: ["La cinta está organizada en pestañas (Inicio, Insertar, Diseño)", "Selecciona el texto arrastrando antes de aplicar una herramienta", "Ctrl+Z deshace un error, Ctrl+Y lo rehace", "La barra de acceso rápido guarda los botones más útiles"],
          },
          exercise: {
            fr: "Dans ton document, tape la phrase « Bonjour tout le monde ». Sélectionne-la en glissant la souris, puis clique tour à tour sur les onglets Accueil, Insertion et Mise en page pour observer les boutons de chacun. Applique le gras, puis appuie sur Ctrl+Z pour annuler.",
            ht: "Nan dokiman ou, tape fraz « Bonjou tout moun ». Chwazi l lè w glise sourit la, epi klike youn apre lòt sou onglè Accueil, Insertion ak Mise en page pou obsève bouton chak. Aplike gra a, epi peze Ctrl+Z pou anile.",
            en: "In your document, type the sentence \"Hello everyone\". Select it by dragging the mouse, then click in turn on the Home, Insert and Layout tabs to observe the buttons of each. Apply bold, then press Ctrl+Z to undo.",
            es: "En tu documento, escribe la frase «Hola a todos». Selecciónala arrastrando el ratón, luego haz clic uno por uno en las pestañas Inicio, Insertar y Diseño para observar los botones de cada una. Aplica la negrita y luego pulsa Ctrl+Z para deshacer.",
          },
        },
        {
          slug: "ouvrir-selectionner-copier",
          title: { fr: "Ouvrir, sélectionner et copier-coller", ht: "Ouvri, chwazi ak kopye-kole", en: "Opening, selecting and copy-pasting", es: "Abrir, seleccionar y copiar-pegar" },
          videoId: "",
          content: {
            fr: "Pour retravailler un document déjà écrit, il faut d'abord l'ouvrir. Va dans « Fichier » puis « Ouvrir » et « Parcourir » pour retrouver le fichier dans tes dossiers, ou clique directement sur son nom dans la liste des « Documents récents ». Tu peux aussi simplement double-cliquer sur le fichier depuis l'explorateur de ton ordinateur.\n\nPour te déplacer vite dans un long texte, utilise la molette de la souris ou la barre de défilement à droite. Le raccourci Ctrl+Début te ramène tout en haut du document, et Ctrl+Fin t'emmène tout en bas. Pour sélectionner, tu as plusieurs astuces : double-clique sur un mot pour le sélectionner, triple-clique dans un paragraphe pour le sélectionner en entier, et Ctrl+A sélectionne tout le document d'un coup.\n\nCopier-coller permet de réutiliser du texte sans le retaper. Sélectionne le passage, appuie sur Ctrl+C pour le copier, place le curseur à l'endroit voulu, puis Ctrl+V pour le coller. Si tu veux déplacer le texte au lieu de le dupliquer, utilise Ctrl+X (couper) à la place de Ctrl+C.\n\nEnfin, pour retrouver ou remplacer un mot dans tout le document, l'outil « Rechercher et remplacer » est très pratique. Appuie sur Ctrl+H, tape le mot à chercher, puis le mot de remplacement, et clique sur « Remplacer tout » : Word corrige toutes les occurrences en une seule fois.",
            ht: "Pou retravay yon dokiman ki deja ekri, ou dwe ouvri l anvan. Ale nan « Fichier » epi « Ouvrir » epi « Parcourir » pou jwenn fichye a nan dosye ou yo, oswa klike dirèk sou non li nan lis « Documents récents » la. Ou ka jis double-klike sou fichye a depi eksploratè òdinatè ou.\n\nPou deplase vit nan yon tèks long, sèvi ak wou sourit la oswa bar defilman adwat la. Rakoursi Ctrl+Début la mennen ou tout anwo dokiman an, epi Ctrl+Fin mennen ou tout anba. Pou chwazi, ou gen plizyè astis : double-klike sou yon mo pou chwazi l, triple-klike nan yon paragraf pou chwazi l antye, epi Ctrl+A chwazi tout dokiman an yon sèl kou.\n\nKopye-kole pèmèt reitilize tèks san retape l. Chwazi pasaj la, peze Ctrl+C pou kopye l, mete kurseur a kote ou vle a, epi Ctrl+V pou kole l. Si ou vle deplase tèks la olye double l, sèvi ak Ctrl+X (koupe) nan plas Ctrl+C.\n\nAnfen, pou jwenn oswa ranplase yon mo nan tout dokiman an, zouti « Rechercher et remplacer » a pratik anpil. Peze Ctrl+H, tape mo pou chèche a, epi mo ranplasman an, epi klike sou « Remplacer tout » : Word korije tout kote mo a parèt yon sèl kou.",
            en: "To rework a document you already wrote, you first have to open it. Go to \"File\", then \"Open\" and \"Browse\" to find the file in your folders, or click directly on its name in the \"Recent Documents\" list. You can also simply double-click the file from your computer's file explorer.\n\nTo move quickly through a long text, use the mouse wheel or the scroll bar on the right. The Ctrl+Home shortcut takes you to the very top of the document, and Ctrl+End takes you to the very bottom. To select, you have several tricks: double-click a word to select it, triple-click in a paragraph to select the whole thing, and Ctrl+A selects the entire document at once.\n\nCopy-paste lets you reuse text without retyping it. Select the passage, press Ctrl+C to copy it, place the cursor where you want it, then Ctrl+V to paste it. If you want to move the text instead of duplicating it, use Ctrl+X (cut) instead of Ctrl+C.\n\nFinally, to find or replace a word throughout the document, the \"Find and Replace\" tool is very handy. Press Ctrl+H, type the word to search for, then the replacement word, and click \"Replace All\": Word corrects every occurrence at once.",
            es: "Para volver a trabajar un documento ya escrito, primero hay que abrirlo. Ve a «Archivo», luego «Abrir» y «Examinar» para encontrar el archivo en tus carpetas, o haz clic directamente en su nombre en la lista de «Documentos recientes». También puedes simplemente hacer doble clic en el archivo desde el explorador de tu computadora.\n\nPara moverte rápido por un texto largo, usa la rueda del ratón o la barra de desplazamiento de la derecha. El atajo Ctrl+Inicio te lleva a la parte superior del documento, y Ctrl+Fin te lleva al final. Para seleccionar, tienes varios trucos: haz doble clic en una palabra para seleccionarla, triple clic en un párrafo para seleccionarlo entero, y Ctrl+A selecciona todo el documento de una vez.\n\nCopiar-pegar permite reutilizar texto sin volver a escribirlo. Selecciona el pasaje, pulsa Ctrl+C para copiarlo, coloca el cursor donde quieras y luego Ctrl+V para pegarlo. Si quieres mover el texto en vez de duplicarlo, usa Ctrl+X (cortar) en lugar de Ctrl+C.\n\nPor último, para encontrar o reemplazar una palabra en todo el documento, la herramienta «Buscar y reemplazar» es muy práctica. Pulsa Ctrl+H, escribe la palabra que buscar, luego la palabra de reemplazo, y haz clic en «Reemplazar todo»: Word corrige todas las apariciones de una sola vez.",
          },
          keyPoints: {
            fr: ["Fichier > Ouvrir, ou double-clic sur le fichier ; liste des récents", "Double-clic = un mot, triple-clic = un paragraphe, Ctrl+A = tout", "Copier Ctrl+C, coller Ctrl+V, couper Ctrl+X pour déplacer", "Ctrl+H remplace un mot partout dans le document"],
            ht: ["Fichier > Ouvrir, oswa double-klik sou fichye a ; lis resan yo", "Double-klik = yon mo, triple-klik = yon paragraf, Ctrl+A = tout", "Kopye Ctrl+C, kole Ctrl+V, koupe Ctrl+X pou deplase", "Ctrl+H ranplase yon mo toupatou nan dokiman an"],
            en: ["File > Open, or double-click the file; recent documents list", "Double-click = one word, triple-click = a paragraph, Ctrl+A = all", "Copy Ctrl+C, paste Ctrl+V, cut Ctrl+X to move", "Ctrl+H replaces a word everywhere in the document"],
            es: ["Archivo > Abrir, o doble clic en el archivo; lista de recientes", "Doble clic = una palabra, triple clic = un párrafo, Ctrl+A = todo", "Copiar Ctrl+C, pegar Ctrl+V, cortar Ctrl+X para mover", "Ctrl+H reemplaza una palabra en todo el documento"],
          },
          exercise: {
            fr: "Ouvre le document « Ma-premiere-lettre » enregistré plus tôt. Triple-clique sur un paragraphe pour le sélectionner, copie-le avec Ctrl+C et colle-le à la fin du document avec Ctrl+V. Ensuite, ouvre Rechercher et remplacer (Ctrl+H) et remplace un prénom par un autre partout.",
            ht: "Ouvri dokiman « Premye-lèt-mwen » ou te anrejistre pi bonè a. Triple-klike sou yon paragraf pou chwazi l, kopye l ak Ctrl+C epi kole l nan fen dokiman an ak Ctrl+V. Apre sa, ouvri Rechercher et remplacer (Ctrl+H) epi ranplase yon prenon ak yon lòt toupatou.",
            en: "Open the \"My-first-letter\" document you saved earlier. Triple-click a paragraph to select it, copy it with Ctrl+C and paste it at the end of the document with Ctrl+V. Then open Find and Replace (Ctrl+H) and replace one first name with another everywhere.",
            es: "Abre el documento «Mi-primera-carta» que guardaste antes. Haz triple clic en un párrafo para seleccionarlo, cópialo con Ctrl+C y pégalo al final del documento con Ctrl+V. Luego abre Buscar y reemplazar (Ctrl+H) y reemplaza un nombre por otro en todas partes.",
          },
        },
      ],
    },
    {
      title: { fr: "Mettre en forme le texte", ht: "Byen ranje tèks la", en: "Formatting text", es: "Dar formato al texto" },
      lessons: [
        {
          slug: "police-gras-couleur",
          title: { fr: "Police, taille, gras et couleur", ht: "Font, gwosè, gra ak koulè", en: "Font, size, bold and color", es: "Fuente, tamaño, negrita y color" },
          videoId: "",
          content: {
            fr: "Mettre en forme le texte, c'est changer son apparence pour le rendre clair et agréable à lire. Tous les outils de base se trouvent dans l'onglet « Accueil ». Avant d'appliquer une mise en forme, sélectionne d'abord le texte concerné : sans sélection, rien ne se passe.\n\nLa « police » est le style des lettres (par exemple Calibri, Arial ou Times New Roman). À côté, un nombre indique la taille : 11 ou 12 conviennent pour un texte normal, un titre peut monter à 16 ou 20. Le bouton « G » met le texte en gras pour le faire ressortir, « I » le met en italique, et « S » le souligne. Ces trois boutons fonctionnent aussi avec Ctrl+G, Ctrl+I et Ctrl+U.\n\nPour changer la couleur, utilise le bouton « Couleur de police » (un A avec une barre colorée) et choisis une teinte. À côté, le « surligneur » (une sorte de feutre) permet de mettre un mot en évidence sur fond jaune, comme sur du papier.\n\nUtilise la couleur avec modération : un texte trop coloré devient fatigant. Pour un document propre, garde le noir pour le corps du texte et réserve une couleur ou le gras pour les titres. Le bouton « Reproduire la mise en forme » (le petit pinceau) copie l'apparence d'un texte pour l'appliquer ailleurs.",
            ht: "Byen ranje tèks la vle di chanje aparans li pou l klè epi bèl pou moun li. Tout zouti de baz yo nan onglè « Accueil ». Anvan ou aplike yon mizanfòm, chwazi tèks la anvan : san seleksyon, anyen p ap pase.\n\n« Police » a se estil lèt yo (pa egzanp Calibri, Arial oswa Times New Roman). Akote l, yon nimewo montre gwosè a : 11 oswa 12 bon pou yon tèks nòmal, yon tit ka monte 16 oswa 20. Bouton « G » la mete tèks la an gra pou l parèt plis, « I » mete l an italik, epi « S » souliye l. Twa bouton sa yo mache tou ak Ctrl+G, Ctrl+I ak Ctrl+U.\n\nPou chanje koulè, sèvi ak bouton « Couleur de police » a (yon A ak yon bar ki gen koulè) epi chwazi yon koulè. Akote l, « surligneur » a (yon kalite makè) pèmèt make yon mo sou yon fon jòn, tankou sou papye.\n\nSèvi ak koulè ak modon : yon tèks ki gen twòp koulè vin fatige je. Pou yon dokiman pwòp, kenbe nwa pou kò tèks la epi rezève yon koulè oswa gra pou tit yo. Bouton « Reproduire la mise en forme » a (ti penso a) kopye aparans yon tèks pou aplike l yon lòt kote.",
            en: "Formatting text means changing its appearance to make it clear and pleasant to read. All the basic tools are in the \"Home\" tab. Before applying formatting, first select the text you want to change: without a selection, nothing happens.\n\nThe \"font\" is the style of the letters (for example Calibri, Arial or Times New Roman). Next to it, a number shows the size: 11 or 12 works for normal text, a title can go up to 16 or 20. The \"B\" button makes text bold to make it stand out, \"I\" makes it italic, and \"U\" underlines it. These three buttons also work with Ctrl+B, Ctrl+I and Ctrl+U.\n\nTo change the color, use the \"Font Color\" button (an A with a colored bar) and choose a shade. Next to it, the \"highlighter\" (a kind of marker) lets you emphasize a word on a yellow background, as on paper.\n\nUse color sparingly: text with too much color becomes tiring. For a clean document, keep black for the body text and reserve a color or bold for the titles. The \"Format Painter\" button (the little brush) copies the look of one text to apply it elsewhere.",
            es: "Dar formato al texto significa cambiar su apariencia para que sea claro y agradable de leer. Todas las herramientas básicas están en la pestaña «Inicio». Antes de aplicar un formato, selecciona primero el texto que quieres cambiar: sin selección, no ocurre nada.\n\nLa «fuente» es el estilo de las letras (por ejemplo Calibri, Arial o Times New Roman). A su lado, un número indica el tamaño: 11 o 12 sirve para un texto normal, un título puede subir a 16 o 20. El botón «N» pone el texto en negrita para destacarlo, «K» lo pone en cursiva y «S» lo subraya. Estos tres botones también funcionan con Ctrl+N, Ctrl+K y Ctrl+S.\n\nPara cambiar el color, usa el botón «Color de fuente» (una A con una barra de color) y elige un tono. A su lado, el «resaltador» (una especie de marcador) permite destacar una palabra sobre un fondo amarillo, como en el papel.\n\nUsa el color con moderación: un texto con demasiado color cansa la vista. Para un documento limpio, mantén el negro para el cuerpo del texto y reserva un color o la negrita para los títulos. El botón «Copiar formato» (el pincelito) copia la apariencia de un texto para aplicarla en otro lugar.",
          },
          keyPoints: {
            fr: ["Sélectionner le texte avant toute mise en forme", "Police = style, le nombre à côté = taille (11-12 pour le corps)", "Gras, italique, souligné : Ctrl+G / Ctrl+I / Ctrl+U", "Le pinceau reproduit la mise en forme d'un texte à l'autre"],
            ht: ["Chwazi tèks la anvan tout mizanfòm", "Police = estil, nimewo akote a = gwosè (11-12 pou kò a)", "Gra, italik, souliye : Ctrl+G / Ctrl+I / Ctrl+U", "Penso a repwodui mizanfòm yon tèks sou yon lòt"],
            en: ["Select the text before any formatting", "Font = style, the number beside it = size (11-12 for body)", "Bold, italic, underline: Ctrl+B / Ctrl+I / Ctrl+U", "The brush copies formatting from one text to another"],
            es: ["Selecciona el texto antes de cualquier formato", "Fuente = estilo, el número al lado = tamaño (11-12 para el cuerpo)", "Negrita, cursiva, subrayado: Ctrl+N / Ctrl+K / Ctrl+S", "El pincel copia el formato de un texto a otro"],
          },
          exercise: {
            fr: "Tape un titre et deux phrases. Sélectionne le titre, mets-le en Arial taille 18, en gras et en bleu. Sélectionne ensuite un mot important dans une phrase et mets-le en évidence avec le surligneur jaune.",
            ht: "Tape yon tit ak de fraz. Chwazi tit la, mete l an Arial gwosè 18, an gra epi an ble. Apre sa chwazi yon mo enpòtan nan yon fraz epi make l ak surligneur jòn lan.",
            en: "Type a title and two sentences. Select the title and make it Arial size 18, bold and blue. Then select an important word in a sentence and emphasize it with the yellow highlighter.",
            es: "Escribe un título y dos frases. Selecciona el título y ponlo en Arial tamaño 18, en negrita y en azul. Luego selecciona una palabra importante en una frase y destácala con el resaltador amarillo.",
          },
        },
        {
          slug: "alignement-listes-titres",
          title: { fr: "Alignement, listes et titres", ht: "Aliyman, lis ak tit", en: "Alignment, lists and titles", es: "Alineación, listas y títulos" },
          videoId: "",
          content: {
            fr: "L'alignement décide comment le texte se place dans la largeur de la page. Dans l'onglet « Accueil », quatre boutons le règlent : aligner à gauche (le plus courant), centrer (utile pour un titre), aligner à droite, ou justifier (le texte forme des bords nets des deux côtés). Sélectionne un paragraphe, puis clique sur l'alignement voulu.\n\nLes listes rendent une énumération plus lisible. Le bouton « Puces » place un point devant chaque ligne, idéal pour une liste de courses ou de tâches. Le bouton « Numérotation » ajoute 1, 2, 3… automatiquement, parfait pour des étapes à suivre dans l'ordre. Appuie sur Entrée pour créer un nouvel élément, et sur Entrée deux fois pour sortir de la liste.\n\nTu peux choisir la forme des puces (point, tiret, flèche) en cliquant sur la petite flèche à côté du bouton Puces. Pour décaler une ligne vers la droite à l'intérieur d'une liste, utilise le bouton « Augmenter le retrait ».\n\nPour un document long, les « Styles » (à droite de l'onglet Accueil) donnent un aspect professionnel en un clic. Applique le style « Titre 1 » à tes grands titres et « Titre 2 » aux sous-titres : la mise en forme est cohérente partout, et Word peut même générer une table des matières automatiquement.",
            ht: "Aliyman an deside kijan tèks la plase nan lajè paj la. Nan onglè « Accueil », kat bouton regle l : aliyen agoch (sa ki pi kouran), mete nan mitan (itil pou yon tit), aliyen adwat, oswa jistifye (tèks la fè bò byen dwat de kote). Chwazi yon paragraf, epi klike sou aliyman ou vle a.\n\nLis yo fè yon lis vin pi fasil pou li. Bouton « Puces » la mete yon pwen devan chak liy, ideyal pou yon lis makèt oswa yon lis travay. Bouton « Numérotation » la ajoute 1, 2, 3… otomatikman, pafè pou etap pou swiv nan lòd. Peze Entrée pou kreye yon nouvo eleman, epi Entrée de fwa pou soti nan lis la.\n\nOu ka chwazi fòm pin yo (pwen, tirè, flèch) lè w klike sou ti flèch akote bouton Puces la. Pou dekale yon liy nan dwat andedan yon lis, sèvi ak bouton « Augmenter le retrait » a.\n\nPou yon dokiman long, « Styles » yo (adwat nan onglè Accueil) bay yon aspè pwofesyonèl ak yon sèl klik. Aplike style « Titre 1 » sou gwo tit ou yo epi « Titre 2 » sou sou-tit yo : mizanfòm nan menm toupatou, epi Word ka menm fè yon tab dèmatyè otomatikman.",
            en: "Alignment decides how text sits across the width of the page. In the \"Home\" tab, four buttons control it: align left (the most common), center (useful for a title), align right, or justify (the text forms clean edges on both sides). Select a paragraph, then click the alignment you want.\n\nLists make an enumeration easier to read. The \"Bullets\" button places a dot in front of each line, ideal for a shopping or task list. The \"Numbering\" button adds 1, 2, 3… automatically, perfect for steps to follow in order. Press Enter to create a new item, and Enter twice to leave the list.\n\nYou can choose the shape of the bullets (dot, dash, arrow) by clicking the little arrow next to the Bullets button. To shift a line to the right inside a list, use the \"Increase Indent\" button.\n\nFor a long document, the \"Styles\" (on the right of the Home tab) give a professional look in one click. Apply the \"Heading 1\" style to your main titles and \"Heading 2\" to subtitles: the formatting is consistent everywhere, and Word can even generate a table of contents automatically.",
            es: "La alineación decide cómo se coloca el texto en el ancho de la página. En la pestaña «Inicio», cuatro botones la controlan: alinear a la izquierda (lo más común), centrar (útil para un título), alinear a la derecha, o justificar (el texto forma bordes rectos a ambos lados). Selecciona un párrafo y luego haz clic en la alineación que quieras.\n\nLas listas hacen que una enumeración sea más fácil de leer. El botón «Viñetas» coloca un punto delante de cada línea, ideal para una lista de compras o de tareas. El botón «Numeración» añade 1, 2, 3… automáticamente, perfecto para pasos que seguir en orden. Pulsa Enter para crear un nuevo elemento y Enter dos veces para salir de la lista.\n\nPuedes elegir la forma de las viñetas (punto, guion, flecha) haciendo clic en la pequeña flecha junto al botón Viñetas. Para desplazar una línea a la derecha dentro de una lista, usa el botón «Aumentar sangría».\n\nPara un documento largo, los «Estilos» (a la derecha de la pestaña Inicio) dan un aspecto profesional con un clic. Aplica el estilo «Título 1» a tus títulos principales y «Título 2» a los subtítulos: el formato es coherente en todas partes, y Word puede incluso generar una tabla de contenido automáticamente.",
          },
          keyPoints: {
            fr: ["Quatre alignements : gauche, centré, droite, justifié", "Puces pour une liste, numérotation pour des étapes ordonnées", "Entrée = nouvel élément, Entrée deux fois = sortir de la liste", "Le retrait décale une ligne vers la droite dans la liste"],
            ht: ["Kat aliyman : agoch, mitan, adwat, jistifye", "Puces pou yon lis, numewo pou etap nan lòd", "Entrée = nouvo eleman, Entrée de fwa = soti nan lis la", "Retrè a dekale yon liy nan dwat nan lis la"],
            en: ["Four alignments: left, centered, right, justified", "Bullets for a list, numbering for ordered steps", "Enter = new item, Enter twice = leave the list", "Indent shifts a line to the right within the list"],
            es: ["Cuatro alineaciones: izquierda, centrado, derecha, justificado", "Viñetas para una lista, numeración para pasos ordenados", "Enter = nuevo elemento, Enter dos veces = salir de la lista", "La sangría desplaza una línea a la derecha en la lista"],
          },
          exercise: {
            fr: "Écris un titre et centre-le. En dessous, tape une liste de courses de cinq articles avec des puces, puis crée en dessous une liste numérotée de trois étapes pour préparer un repas. Justifie enfin un paragraphe de ton choix.",
            ht: "Ekri yon tit epi mete l nan mitan. Anba l, tape yon lis makèt senk atik ak pin, epi kreye anba a yon lis nimewote twa etap pou prepare yon manje. Anfen jistifye yon paragraf ou chwazi.",
            en: "Write a title and center it. Below it, type a shopping list of five items with bullets, then create below a numbered list of three steps to prepare a meal. Finally justify a paragraph of your choice.",
            es: "Escribe un título y céntralo. Debajo, escribe una lista de compras de cinco artículos con viñetas, luego crea debajo una lista numerada de tres pasos para preparar una comida. Por último, justifica un párrafo de tu elección.",
          },
        },
        {
          slug: "interligne-retraits-espacement",
          title: { fr: "Interligne, retraits et espacement", ht: "Espas ant liy, retrè ak espasman", en: "Line spacing, indents and spacing", es: "Interlineado, sangrías y espaciado" },
          videoId: "",
          content: {
            fr: "L'espacement entre les lignes rend un texte plus ou moins aéré. Dans l'onglet « Accueil », section Paragraphe, le bouton « Interligne » (deux flèches verticales avec des lignes) propose 1,0, 1,5 ou 2,0. Un interligne de 1,5 est souvent plus confortable à lire qu'un interligne serré de 1,0. Sélectionne d'abord le paragraphe, puis choisis la valeur.\n\nBeaucoup de débutants appuient deux fois sur Entrée pour créer un espace entre les paragraphes ; c'est une mauvaise habitude. Le mieux est de régler l'« espacement avant » et « espacement après » le paragraphe. Ouvre la petite flèche en bas à droite de la section Paragraphe pour afficher la boîte de dialogue et fixer, par exemple, 6 points d'espace après chaque paragraphe.\n\nLe retrait décale le paragraphe par rapport à la marge. Le bouton « Augmenter le retrait » pousse le texte vers la droite, « Diminuer le retrait » le ramène vers la gauche. C'est utile pour mettre en valeur une citation.\n\nLa règle graduée, en haut de la page (active-la via Affichage > Règle), permet de régler finement les retraits en glissant les petits triangles. Le triangle du haut règle le retrait de la première ligne, celui du bas le retrait du reste du paragraphe. Ces réglages donnent à ton texte une allure soignée et professionnelle.",
            ht: "Espas ant liy yo fè yon tèks pi lejè oswa pi sere. Nan onglè « Accueil », seksyon Paragraphe, bouton « Interligne » a (de flèch vètikal ak liy) pwopoze 1,0, 1,5 oswa 2,0. Yon espas 1,5 souvan pi konfòtab pou li pase yon espas sere 1,0. Chwazi paragraf la anvan, epi chwazi valè a.\n\nAnpil debitan peze Entrée de fwa pou kreye yon espas ant paragraf yo ; sa se yon move abitid. Pi bon an se regle « espacement avant » ak « espacement après » paragraf la. Ouvri ti flèch anba adwat seksyon Paragraphe la pou montre bwat dyalòg la epi fikse, pa egzanp, 6 pwen espas apre chak paragraf.\n\nRetrè a dekale paragraf la parapò ak maj la. Bouton « Augmenter le retrait » a pouse tèks la nan dwat, « Diminuer le retrait » ranmennen l nan goch. Sa itil pou mete yon sitasyon an valè.\n\nRèg gradye a, anwo paj la (aktive l ak Affichage > Règle), pèmèt regle retrè yo byen fen lè w glise ti triyang yo. Triyang anwo a regle retrè premye liy la, sa anba a regle retrè rès paragraf la. Reglaj sa yo bay tèks ou yon aparans swaye epi pwofesyonèl.",
            en: "The spacing between lines makes a text more or less airy. In the \"Home\" tab, Paragraph section, the \"Line Spacing\" button (two vertical arrows with lines) offers 1.0, 1.5 or 2.0. A line spacing of 1.5 is often more comfortable to read than a tight 1.0. First select the paragraph, then choose the value.\n\nMany beginners press Enter twice to create a gap between paragraphs; that is a bad habit. It is better to set the \"space before\" and \"space after\" the paragraph. Open the small arrow at the bottom right of the Paragraph section to show the dialog box and set, for example, 6 points of space after each paragraph.\n\nThe indent shifts the paragraph relative to the margin. The \"Increase Indent\" button pushes the text to the right, \"Decrease Indent\" brings it back to the left. This is useful for setting off a quotation.\n\nThe ruler at the top of the page (turn it on via View > Ruler) lets you fine-tune the indents by sliding the little triangles. The top triangle sets the first-line indent, the bottom one the indent of the rest of the paragraph. These settings give your text a neat, professional look.",
            es: "El espaciado entre líneas hace que un texto sea más o menos aireado. En la pestaña «Inicio», sección Párrafo, el botón «Interlineado» (dos flechas verticales con líneas) ofrece 1,0, 1,5 o 2,0. Un interlineado de 1,5 suele ser más cómodo de leer que uno apretado de 1,0. Selecciona primero el párrafo y luego elige el valor.\n\nMuchos principiantes pulsan Enter dos veces para crear un espacio entre párrafos; es una mala costumbre. Es mejor ajustar el «espacio antes» y el «espacio después» del párrafo. Abre la pequeña flecha de la esquina inferior derecha de la sección Párrafo para mostrar el cuadro de diálogo y fijar, por ejemplo, 6 puntos de espacio después de cada párrafo.\n\nLa sangría desplaza el párrafo respecto al margen. El botón «Aumentar sangría» empuja el texto a la derecha, «Disminuir sangría» lo devuelve a la izquierda. Es útil para destacar una cita.\n\nLa regla graduada, en la parte superior de la página (actívala con Vista > Regla), permite ajustar con precisión las sangrías arrastrando los pequeños triángulos. El triángulo de arriba ajusta la sangría de la primera línea, el de abajo la sangría del resto del párrafo. Estos ajustes dan a tu texto un aspecto cuidado y profesional.",
          },
          keyPoints: {
            fr: ["Bouton Interligne : 1,0, 1,5 ou 2,0 pour aérer les lignes", "Régler l'espacement avant/après plutôt que taper deux fois Entrée", "Augmenter/diminuer le retrait décale le paragraphe", "La règle affine les retraits de première ligne et de paragraphe"],
            ht: ["Bouton Interligne : 1,0, 1,5 oswa 2,0 pou lejè liy yo", "Regle espasman avan/apre olye peze Entrée de fwa", "Ogmante/diminye retrè a dekale paragraf la", "Règ la byen regle retrè premye liy ak retrè paragraf"],
            en: ["Line Spacing button: 1.0, 1.5 or 2.0 to air out the lines", "Set space before/after instead of pressing Enter twice", "Increase/decrease indent shifts the paragraph", "The ruler fine-tunes first-line and paragraph indents"],
            es: ["Botón Interlineado: 1,0, 1,5 o 2,0 para airear las líneas", "Ajusta el espacio antes/después en vez de pulsar Enter dos veces", "Aumentar/disminuir sangría desplaza el párrafo", "La regla ajusta las sangrías de primera línea y de párrafo"],
          },
          exercise: {
            fr: "Prends un texte de deux paragraphes. Sélectionne tout et applique un interligne de 1,5. Ouvre la boîte de dialogue Paragraphe et règle 6 points d'espacement après chaque paragraphe. Enfin, augmente le retrait du second paragraphe pour le décaler vers la droite.",
            ht: "Pran yon tèks de paragraf. Chwazi tout epi aplike yon espas 1,5. Ouvri bwat dyalòg Paragraphe la epi regle 6 pwen espasman apre chak paragraf. Anfen, ogmante retrè dezyèm paragraf la pou dekale l nan dwat.",
            en: "Take a two-paragraph text. Select all and apply 1.5 line spacing. Open the Paragraph dialog box and set 6 points of space after each paragraph. Finally, increase the indent of the second paragraph to shift it to the right.",
            es: "Toma un texto de dos párrafos. Selecciona todo y aplica un interlineado de 1,5. Abre el cuadro de diálogo Párrafo y ajusta 6 puntos de espaciado después de cada párrafo. Por último, aumenta la sangría del segundo párrafo para desplazarlo a la derecha.",
          },
        },
      ],
    },
    {
      title: { fr: "Styles, images et tableaux", ht: "Style, imaj ak tablo", en: "Styles, images and tables", es: "Estilos, imágenes y tablas" },
      lessons: [
        {
          slug: "appliquer-styles",
          title: { fr: "Appliquer et modifier les styles", ht: "Aplike ak chanje style yo", en: "Applying and editing styles", es: "Aplicar y modificar los estilos" },
          videoId: "",
          content: {
            fr: "Un « style » est un ensemble de mises en forme enregistré sous un nom : police, taille, couleur, espacement, tout est réglé d'avance. Au lieu de mettre chaque titre en gras, en taille 16 et en bleu à la main, tu appliques simplement le style « Titre 1 » d'un clic. La galerie de styles se trouve à droite de l'onglet « Accueil ».\n\nLe style « Normal » est celui du texte courant. Pour un rapport, applique « Titre 1 » à tes grandes parties et « Titre 2 » à leurs sous-parties : clique dans la ligne du titre (pas besoin de tout sélectionner pour un titre d'une ligne), puis clique sur le style dans la galerie. Tous tes titres auront exactement la même apparence, ce qui rend le document cohérent.\n\nSi la couleur ou la police d'un style ne te plaît pas, tu peux la modifier une fois pour toutes. Fais un clic droit sur le style dans la galerie, choisis « Modifier », change la police ou la couleur, et valide : tous les textes portant ce style se mettent à jour automatiquement.\n\nLe grand avantage des styles apparaît avec la table des matières. Va dans l'onglet « Références », clique sur « Table des matières » et choisis un modèle : Word liste automatiquement tous tes Titre 1 et Titre 2 avec leurs numéros de page. Si tu ajoutes une partie plus tard, un clic sur « Mettre à jour la table » suffit à tout recalculer.",
            ht: "Yon « style » se yon ansanm mizanfòm yo anrejistre sou yon non : police, gwosè, koulè, espasman, tout regle davans. Olye pou w mete chak tit an gra, gwosè 16 ak ble alamen, ou senpleman aplike style « Titre 1 » an ak yon klik. Galri style yo nan dwat onglè « Accueil » la.\n\nStyle « Normal » an se pou tèks kouran an. Pou yon rapò, aplike « Titre 1 » sou gwo pati ou yo epi « Titre 2 » sou sou-pati yo : klike nan liy tit la (ou pa bezwen chwazi tout pou yon tit yon sèl liy), epi klike sou style a nan galri a. Tout tit ou yo ap gen egzakteman menm aparans, sa fè dokiman an koyeran.\n\nSi koulè oswa police yon style pa fè ou plezi, ou ka chanje l yon fwa pou tout. Fè yon klik dwat sou style a nan galri a, chwazi « Modifier », chanje police oswa koulè a, epi valide : tout tèks ki gen style sa a mete ajou otomatikman.\n\nGwo avantaj style yo parèt ak tab dèmatyè a. Ale nan onglè « Références », klike sou « Table des matières » epi chwazi yon modèl : Word fè lis tout Titre 1 ak Titre 2 ou yo otomatikman ak nimewo paj yo. Si ou ajoute yon pati pita, yon klik sou « Mettre à jour la table » ase pou rekalkile tout.",
            en: "A \"style\" is a set of formatting saved under a name: font, size, color, spacing, everything set in advance. Instead of making each title bold, size 16 and blue by hand, you simply apply the \"Heading 1\" style with one click. The style gallery is on the right of the \"Home\" tab.\n\nThe \"Normal\" style is the one for regular text. For a report, apply \"Heading 1\" to your major parts and \"Heading 2\" to their subparts: click in the title line (no need to select everything for a one-line title), then click the style in the gallery. All your titles will have exactly the same look, which makes the document consistent.\n\nIf you don't like a style's color or font, you can change it once and for all. Right-click the style in the gallery, choose \"Modify\", change the font or color, and confirm: all texts using that style update automatically.\n\nThe big advantage of styles appears with the table of contents. Go to the \"References\" tab, click \"Table of Contents\" and choose a model: Word automatically lists all your Heading 1 and Heading 2 with their page numbers. If you add a part later, one click on \"Update Table\" is enough to recalculate everything.",
            es: "Un «estilo» es un conjunto de formatos guardado bajo un nombre: fuente, tamaño, color, espaciado, todo está definido de antemano. En lugar de poner cada título en negrita, tamaño 16 y azul a mano, simplemente aplicas el estilo «Título 1» con un clic. La galería de estilos está a la derecha de la pestaña «Inicio».\n\nEl estilo «Normal» es el del texto corriente. Para un informe, aplica «Título 1» a tus partes principales y «Título 2» a sus subpartes: haz clic en la línea del título (no hace falta seleccionar todo para un título de una línea), luego haz clic en el estilo de la galería. Todos tus títulos tendrán exactamente el mismo aspecto, lo que hace el documento coherente.\n\nSi no te gusta el color o la fuente de un estilo, puedes cambiarlo de una vez por todas. Haz clic derecho en el estilo de la galería, elige «Modificar», cambia la fuente o el color, y confirma: todos los textos con ese estilo se actualizan automáticamente.\n\nLa gran ventaja de los estilos aparece con la tabla de contenido. Ve a la pestaña «Referencias», haz clic en «Tabla de contenido» y elige un modelo: Word lista automáticamente todos tus Título 1 y Título 2 con sus números de página. Si añades una parte más tarde, un clic en «Actualizar tabla» basta para recalcularlo todo.",
          },
          keyPoints: {
            fr: ["Un style = police, taille, couleur, espacement enregistrés sous un nom", "Appliquer Titre 1 et Titre 2 pour une structure cohérente", "Clic droit > Modifier change le style partout d'un coup", "Références > Table des matières se génère à partir des titres"],
            ht: ["Yon style = police, gwosè, koulè, espasman anrejistre sou yon non", "Aplike Titre 1 ak Titre 2 pou yon estrikti koyeran", "Klik dwat > Modifier chanje style la toupatou yon sèl kou", "Références > Table des matières fèt apati tit yo"],
            en: ["A style = font, size, color, spacing saved under a name", "Apply Heading 1 and Heading 2 for a consistent structure", "Right-click > Modify changes the style everywhere at once", "References > Table of Contents is built from the headings"],
            es: ["Un estilo = fuente, tamaño, color, espaciado guardados con un nombre", "Aplica Título 1 y Título 2 para una estructura coherente", "Clic derecho > Modificar cambia el estilo en todas partes a la vez", "Referencias > Tabla de contenido se genera a partir de los títulos"],
          },
          exercise: {
            fr: "Crée un petit rapport avec deux grandes parties et un sous-titre dans chacune. Applique le style « Titre 1 » aux deux grandes parties et « Titre 2 » aux sous-titres. Puis, dans l'onglet Références, insère une table des matières automatique en haut du document.",
            ht: "Kreye yon ti rapò ak de gwo pati epi yon sou-tit nan chak. Aplike style « Titre 1 » sou de gwo pati yo epi « Titre 2 » sou sou-tit yo. Apre sa, nan onglè Références, mete yon tab dèmatyè otomatik anwo dokiman an.",
            en: "Create a short report with two major parts and a subtitle in each. Apply the \"Heading 1\" style to the two major parts and \"Heading 2\" to the subtitles. Then, in the References tab, insert an automatic table of contents at the top of the document.",
            es: "Crea un informe corto con dos partes principales y un subtítulo en cada una. Aplica el estilo «Título 1» a las dos partes principales y «Título 2» a los subtítulos. Luego, en la pestaña Referencias, inserta una tabla de contenido automática en la parte superior del documento.",
          },
        },
        {
          slug: "inserer-images-tableaux",
          title: { fr: "Insérer des images et des tableaux", ht: "Mete imaj ak tablo", en: "Inserting images and tables", es: "Insertar imágenes y tablas" },
          videoId: "",
          content: {
            fr: "Un document ne contient pas que du texte : une image ou un tableau peut le rendre plus clair et plus vivant. Tout se passe dans l'onglet « Insertion ». Place d'abord ton curseur à l'endroit où tu veux ajouter l'élément, puis clique sur le bouton correspondant.\n\nPour ajouter une photo, clique sur « Images », choisis « Cet appareil » et sélectionne le fichier sur ton ordinateur. L'image apparaît dans le document. Clique dessus pour la sélectionner : de petits carrés apparaissent aux coins ; tire un coin pour la redimensionner sans la déformer. L'option « Habillage du texte » permet de faire couler le texte autour de l'image.\n\nUn tableau organise des informations en lignes et colonnes, comme un planning ou une liste de prix. Clique sur « Tableau », puis glisse la souris pour choisir le nombre de cases (par exemple 3 colonnes sur 4 lignes). Le tableau s'insère ; clique dans une case et tape pour la remplir, et utilise la touche Tab pour passer à la case suivante.\n\nUne fois le tableau créé, deux onglets « Création de tableau » et « Disposition » apparaissent. Ils permettent d'ajouter ou supprimer une ligne, de choisir un style de couleurs prêt à l'emploi, ou de fusionner plusieurs cases en une seule pour un titre qui s'étale sur toute la largeur.",
            ht: "Yon dokiman pa gen sèlman tèks : yon imaj oswa yon tablo ka fè l pi klè epi pi vivan. Tout bagay pase nan onglè « Insertion ». Mete kurseur ou anvan kote ou vle ajoute eleman an, epi klike sou bouton ki koresponn lan.\n\nPou ajoute yon foto, klike sou « Images », chwazi « Cet appareil » epi chwazi fichye a nan òdinatè ou. Imaj la parèt nan dokiman an. Klike sou li pou chwazi l : ti kare parèt nan kwen yo ; rale yon kwen pou chanje gwosè l san defòme l. Opsyon « Habillage du texte » a pèmèt tèks la koule antoure imaj la.\n\nYon tablo òganize enfòmasyon an liy ak kolòn, tankou yon orè oswa yon lis pri. Klike sou « Tableau », epi glise sourit la pou chwazi konbyen kaz (pa egzanp 3 kolòn sou 4 liy). Tablo a antre ; klike nan yon kaz epi tape pou ranpli l, epi sèvi ak bouton Tab pou pase nan pwochen kaz la.\n\nYon fwa tablo a kreye, de onglè « Création de tableau » ak « Disposition » parèt. Yo pèmèt ajoute oswa efase yon liy, chwazi yon style koulè ki pare, oswa fizyone plizyè kaz an yon sèl pou yon tit ki gaye sou tout lajè a.",
            en: "A document does not contain only text: an image or a table can make it clearer and more lively. Everything happens in the \"Insert\" tab. First place your cursor where you want to add the element, then click the matching button.\n\nTo add a photo, click \"Pictures\", choose \"This Device\" and select the file on your computer. The image appears in the document. Click on it to select it: small squares appear at the corners; drag a corner to resize it without distorting it. The \"Wrap Text\" option lets the text flow around the image.\n\nA table organizes information into rows and columns, like a schedule or a price list. Click \"Table\", then drag the mouse to choose the number of cells (for example 3 columns by 4 rows). The table is inserted; click in a cell and type to fill it, and use the Tab key to move to the next cell.\n\nOnce the table is created, two tabs \"Table Design\" and \"Layout\" appear. They let you add or delete a row, choose a ready-made color style, or merge several cells into one for a title that spans the whole width.",
            es: "Un documento no contiene solo texto: una imagen o una tabla puede hacerlo más claro y vivo. Todo ocurre en la pestaña «Insertar». Coloca primero el cursor donde quieras añadir el elemento y luego haz clic en el botón correspondiente.\n\nPara añadir una foto, haz clic en «Imágenes», elige «Este dispositivo» y selecciona el archivo en tu computadora. La imagen aparece en el documento. Haz clic en ella para seleccionarla: aparecen pequeños cuadrados en las esquinas; arrastra una esquina para cambiar su tamaño sin deformarla. La opción «Ajuste del texto» permite que el texto fluya alrededor de la imagen.\n\nUna tabla organiza información en filas y columnas, como un horario o una lista de precios. Haz clic en «Tabla», luego arrastra el ratón para elegir el número de celdas (por ejemplo 3 columnas por 4 filas). La tabla se inserta; haz clic en una celda y escribe para rellenarla, y usa la tecla Tab para pasar a la siguiente celda.\n\nUna vez creada la tabla, aparecen dos pestañas «Diseño de tabla» y «Presentación». Permiten añadir o eliminar una fila, elegir un estilo de colores ya listo, o combinar varias celdas en una sola para un título que se extiende por todo el ancho.",
          },
          keyPoints: {
            fr: ["Onglet Insertion : placer le curseur avant d'insérer", "Image : tirer un coin pour redimensionner sans déformer", "Tableau : lignes et colonnes ; Tab passe à la case suivante", "Les onglets Création/Disposition ajoutent lignes et styles"],
            ht: ["Onglè Insertion : mete kurseur la anvan ou insere", "Imaj : rale yon kwen pou chanje gwosè san defòme", "Tablo : liy ak kolòn ; Tab pase nan pwochen kaz la", "Onglè Création/Disposition ajoute liy ak style"],
            en: ["Insert tab: place the cursor before inserting", "Image: drag a corner to resize without distorting", "Table: rows and columns; Tab moves to the next cell", "The Design/Layout tabs add rows and styles"],
            es: ["Pestaña Insertar: coloca el cursor antes de insertar", "Imagen: arrastra una esquina para redimensionar sin deformar", "Tabla: filas y columnas; Tab pasa a la siguiente celda", "Las pestañas Diseño/Presentación añaden filas y estilos"],
          },
          exercise: {
            fr: "Insère une image depuis ton ordinateur et redimensionne-la en tirant un coin. Puis, en dessous, insère un tableau de 3 colonnes et 4 lignes. Remplis l'en-tête avec « Article », « Quantité » et « Prix », et complète deux lignes en utilisant la touche Tab pour passer de case en case.",
            ht: "Mete yon imaj depi òdinatè ou epi chanje gwosè l lè w rale yon kwen. Apre sa, anba a, mete yon tablo 3 kolòn ak 4 liy. Ranpli tèt la ak « Atik », « Kantite » ak « Pri », epi konplete de liy lè w sèvi ak bouton Tab pou pase kaz an kaz.",
            en: "Insert an image from your computer and resize it by dragging a corner. Then, below it, insert a table of 3 columns and 4 rows. Fill the header with \"Item\", \"Quantity\" and \"Price\", and complete two rows using the Tab key to move from cell to cell.",
            es: "Inserta una imagen desde tu computadora y cambia su tamaño arrastrando una esquina. Luego, debajo, inserta una tabla de 3 columnas y 4 filas. Rellena el encabezado con «Artículo», «Cantidad» y «Precio», y completa dos filas usando la tecla Tab para pasar de celda en celda.",
          },
        },
        {
          slug: "entetes-pieds-numeros",
          title: { fr: "En-têtes, pieds de page et numéros", ht: "Tèt paj, pye paj ak nimewo", en: "Headers, footers and page numbers", es: "Encabezados, pies de página y números" },
          videoId: "",
          content: {
            fr: "L'en-tête est la zone située tout en haut de chaque page, et le pied de page celle tout en bas. Ce qu'on y écrit se répète automatiquement sur toutes les pages du document. C'est l'endroit idéal pour afficher le titre du document, le nom de l'auteur ou la date.\n\nPour l'ajouter, va dans l'onglet « Insertion » et clique sur « En-tête ». Choisis une présentation simple : Word ouvre la zone du haut et place ton curseur dedans. Tape ton texte, par exemple le titre de ton rapport. Le corps du document devient grisé, ce qui est normal : tu travailles dans une zone à part.\n\nPour numéroter les pages, clique sur « Numéro de page » dans le même onglet, puis choisis la position (en haut, en bas, à gauche, au centre ou à droite). Word numérote alors toutes les pages automatiquement : si tu ajoutes ou supprimes du texte, la numérotation reste juste toute seule.\n\nQuand tu as fini, double-clique dans le corps du document, ou clique sur « Fermer l'en-tête et le pied de page », pour revenir à ton texte normal. En-tête, pied de page et numéros donnent tout de suite une allure sérieuse à un rapport ou un mémoire.",
            ht: "Tèt paj la se zòn ki tou anwo chak paj, epi pye paj la se sa ki tou anba. Sa ou ekri ladan repete otomatikman sou tout paj dokiman an. Se kote ki ideyal pou montre tit dokiman an, non otè a oswa dat la.\n\nPou ajoute l, ale nan onglè « Insertion » epi klike sou « En-tête ». Chwazi yon prezantasyon senp : Word ouvri zòn anwo a epi mete kurseur ou ladan. Tape tèks ou, pa egzanp tit rapò ou. Kò dokiman an vin gri, sa nòmal : ou ap travay nan yon zòn apa.\n\nPou nimewote paj yo, klike sou « Numéro de page » nan menm onglè a, epi chwazi pozisyon an (anwo, anba, agoch, nan mitan oswa adwat). Word nimewote tout paj yo otomatikman lè sa a : si ou ajoute oswa efase tèks, nimewotasyon an rete kòrèk pou kont li.\n\nLè ou fini, double-klike nan kò dokiman an, oswa klike sou « Fermer l'en-tête et le pied de page », pou tounen nan tèks nòmal ou. Tèt paj, pye paj ak nimewo bay yon rapò oswa yon memwa yon aparans serye touswit.",
            en: "The header is the area at the very top of every page, and the footer the one at the very bottom. What you write there repeats automatically on all the pages of the document. It is the ideal place to show the document title, the author's name or the date.\n\nTo add it, go to the \"Insert\" tab and click \"Header\". Choose a simple layout: Word opens the top area and places your cursor in it. Type your text, for example the title of your report. The body of the document turns gray, which is normal: you are working in a separate area.\n\nTo number the pages, click \"Page Number\" in the same tab, then choose the position (top, bottom, left, center or right). Word then numbers all the pages automatically: if you add or remove text, the numbering stays correct on its own.\n\nWhen you are done, double-click in the body of the document, or click \"Close Header and Footer\", to return to your normal text. Header, footer and numbers instantly give a report or thesis a serious look.",
            es: "El encabezado es la zona situada en la parte superior de cada página, y el pie de página la de la parte inferior. Lo que se escribe ahí se repite automáticamente en todas las páginas del documento. Es el lugar ideal para mostrar el título del documento, el nombre del autor o la fecha.\n\nPara añadirlo, ve a la pestaña «Insertar» y haz clic en «Encabezado». Elige una presentación sencilla: Word abre la zona superior y coloca tu cursor dentro. Escribe tu texto, por ejemplo el título de tu informe. El cuerpo del documento se vuelve gris, lo cual es normal: estás trabajando en una zona aparte.\n\nPara numerar las páginas, haz clic en «Número de página» en la misma pestaña, luego elige la posición (arriba, abajo, izquierda, centro o derecha). Word numera entonces todas las páginas automáticamente: si añades o quitas texto, la numeración se mantiene correcta por sí sola.\n\nCuando termines, haz doble clic en el cuerpo del documento, o haz clic en «Cerrar encabezado y pie de página», para volver a tu texto normal. Encabezado, pie de página y números dan de inmediato un aspecto serio a un informe o una tesis.",
          },
          keyPoints: {
            fr: ["En-tête = haut de page, pied de page = bas ; répétés partout", "Insertion > En-tête ouvre la zone à remplir", "Insertion > Numéro de page numérote automatiquement", "Double-clic dans le corps ferme l'en-tête et le pied"],
            ht: ["Tèt paj = anwo, pye paj = anba ; repete toupatou", "Insertion > En-tête ouvri zòn pou ranpli a", "Insertion > Numéro de page nimewote otomatikman", "Double-klik nan kò a fèmen tèt ak pye paj la"],
            en: ["Header = top of page, footer = bottom; repeated everywhere", "Insert > Header opens the area to fill in", "Insert > Page Number numbers pages automatically", "Double-click in the body closes the header and footer"],
            es: ["Encabezado = parte superior, pie = parte inferior; repetidos en todas partes", "Insertar > Encabezado abre la zona para rellenar", "Insertar > Número de página numera automáticamente", "Doble clic en el cuerpo cierra el encabezado y el pie"],
          },
          exercise: {
            fr: "Dans un document de plusieurs pages, ajoute un en-tête contenant le titre « Rapport de stage » et ton nom. Puis insère un numéro de page en bas au centre. Vérifie qu'ils apparaissent bien sur toutes les pages, puis reviens au corps du texte en double-cliquant.",
            ht: "Nan yon dokiman ki gen plizyè paj, ajoute yon tèt paj ki gen tit « Rapò estaj » ak non ou. Apre sa mete yon nimewo paj anba nan mitan. Verifye yo parèt byen sou tout paj yo, epi tounen nan kò tèks la lè w double-klike.",
            en: "In a multi-page document, add a header containing the title \"Internship Report\" and your name. Then insert a page number at the bottom center. Check that they appear on all pages, then return to the body of the text by double-clicking.",
            es: "En un documento de varias páginas, añade un encabezado que contenga el título «Informe de prácticas» y tu nombre. Luego inserta un número de página abajo en el centro. Comprueba que aparecen en todas las páginas y luego vuelve al cuerpo del texto haciendo doble clic.",
          },
        },
      ],
    },
    {
      title: { fr: "Mise en page, impression et publipostage", ht: "Mizanpaj, enprime ak piblipostaj", en: "Layout, printing and mail merge", es: "Diseño, impresión y combinación de correspondencia" },
      lessons: [
        {
          slug: "mise-en-page-marges",
          title: { fr: "Marges, orientation et sauts de page", ht: "Maj, oryantasyon ak so paj", en: "Margins, orientation and page breaks", es: "Márgenes, orientación y saltos de página" },
          videoId: "",
          content: {
            fr: "La mise en page décide de l'aspect général de la feuille avant l'impression. Tout se règle dans l'onglet « Mise en page » (parfois appelé « Disposition »). Le premier bouton, « Marges », fixe l'espace blanc autour du texte. Le réglage « Normales » convient à la plupart des documents ; « Étroites » laisse plus de place au texte, utile pour économiser du papier.\n\nLe bouton « Orientation » propose deux choix : « Portrait », la feuille debout, idéale pour une lettre ou un rapport, et « Paysage », la feuille couchée, pratique pour un large tableau ou une affiche. Juste à côté, « Taille » permet de choisir le format du papier, le plus souvent A4 ou Letter selon ton pays.\n\nLe bouton « Colonnes » divise ta page en plusieurs colonnes, comme dans un journal. Choisis « Deux » pour répartir le texte sur deux colonnes ; c'est utile pour un dépliant ou un bulletin.\n\nEnfin, quand tu veux qu'une partie commence obligatoirement sur une nouvelle page, ne tape pas plusieurs fois sur Entrée : utilise un « saut de page » avec le raccourci Ctrl+Entrée. Ainsi, même si tu ajoutes du texte plus haut, ton titre restera toujours en haut d'une page propre.",
            ht: "Mizanpaj la deside aspè jeneral fèy la anvan enprime. Tout regle nan onglè « Mise en page » a (kèk fwa yo rele l « Disposition »). Premye bouton an, « Marges », fikse espas blan ki antoure tèks la. Reglaj « Normales » a bon pou pifò dokiman ; « Étroites » kite plis plas pou tèks, itil pou ekonomize papye.\n\nBouton « Orientation » an pwopoze de chwa : « Portrait », fèy la kanpe, ideyal pou yon lèt oswa yon rapò, epi « Paysage », fèy la kouche, pratik pou yon gwo tablo oswa yon afich. Jis akote, « Taille » pèmèt chwazi fòma papye a, pi souvan A4 oswa Letter selon peyi ou.\n\nBouton « Colonnes » divize paj ou an plizyè kolòn, tankou nan yon jounal. Chwazi « Deux » pou separe tèks la sou de kolòn ; sa itil pou yon depliyan oswa yon bilten.\n\nAnfen, lè ou vle yon pati kòmanse obligatwaman sou yon nouvo paj, pa peze Entrée plizyè fwa : sèvi ak yon « saut de page » ak rakoursi Ctrl+Entrée. Konsa, menm si ou ajoute tèks pi wo, tit ou ap toujou rete anwo yon paj pwòp.",
            en: "The layout decides the general look of the sheet before printing. Everything is set in the \"Layout\" tab. The first button, \"Margins\", sets the white space around the text. The \"Normal\" setting suits most documents; \"Narrow\" leaves more room for the text, useful to save paper.\n\nThe \"Orientation\" button offers two choices: \"Portrait\", the sheet standing up, ideal for a letter or report, and \"Landscape\", the sheet lying down, handy for a wide table or a poster. Right next to it, \"Size\" lets you choose the paper format, most often A4 or Letter depending on your country.\n\nThe \"Columns\" button divides your page into several columns, as in a newspaper. Choose \"Two\" to spread the text over two columns; this is useful for a leaflet or a newsletter.\n\nFinally, when you want a section to start on a new page for sure, do not press Enter several times: use a \"page break\" with the shortcut Ctrl+Enter. That way, even if you add text higher up, your title will always stay at the top of a clean page.",
            es: "El diseño decide el aspecto general de la hoja antes de imprimir. Todo se ajusta en la pestaña «Diseño de página». El primer botón, «Márgenes», fija el espacio en blanco alrededor del texto. El ajuste «Normal» sirve para la mayoría de documentos; «Estrecho» deja más espacio al texto, útil para ahorrar papel.\n\nEl botón «Orientación» ofrece dos opciones: «Vertical», la hoja de pie, ideal para una carta o un informe, y «Horizontal», la hoja acostada, práctica para una tabla ancha o un cartel. Justo al lado, «Tamaño» permite elegir el formato del papel, casi siempre A4 o Carta según tu país.\n\nEl botón «Columnas» divide tu página en varias columnas, como en un periódico. Elige «Dos» para repartir el texto en dos columnas; es útil para un folleto o un boletín.\n\nPor último, cuando quieras que una parte empiece obligatoriamente en una página nueva, no pulses Enter varias veces: usa un «salto de página» con el atajo Ctrl+Enter. Así, aunque añadas texto más arriba, tu título siempre quedará en la parte superior de una página limpia.",
          },
          keyPoints: {
            fr: ["Marges : espace blanc autour du texte (Normales, Étroites)", "Orientation : Portrait (debout) ou Paysage (couché)", "Colonnes divise la page comme un journal", "Ctrl+Entrée insère un saut de page propre"],
            ht: ["Maj : espas blan otou tèks la (Normales, Étroites)", "Oryantasyon : Portrait (kanpe) oswa Paysage (kouche)", "Colonnes divize paj la tankou yon jounal", "Ctrl+Entrée mete yon so paj pwòp"],
            en: ["Margins: white space around the text (Normal, Narrow)", "Orientation: Portrait (upright) or Landscape (sideways)", "Columns splits the page like a newspaper", "Ctrl+Enter inserts a clean page break"],
            es: ["Márgenes: espacio en blanco alrededor del texto (Normal, Estrecho)", "Orientación: Vertical (de pie) u Horizontal (acostado)", "Columnas divide la página como un periódico", "Ctrl+Enter inserta un salto de página limpio"],
          },
          exercise: {
            fr: "Ouvre un document et passe ses marges en « Étroites ». Change l'orientation en Paysage puis reviens en Portrait pour comparer. Écris deux paragraphes, place le curseur avant le second et appuie sur Ctrl+Entrée pour l'envoyer sur une nouvelle page.",
            ht: "Ouvri yon dokiman epi mete maj li yo an « Étroites ». Chanje oryantasyon an an Paysage epi tounen an Portrait pou konpare. Ekri de paragraf, mete kurseur a anvan dezyèm nan epi peze Ctrl+Entrée pou voye l sou yon nouvo paj.",
            en: "Open a document and set its margins to \"Narrow\". Change the orientation to Landscape then back to Portrait to compare. Write two paragraphs, place the cursor before the second and press Ctrl+Enter to send it to a new page.",
            es: "Abre un documento y pon sus márgenes en «Estrecho». Cambia la orientación a Horizontal y luego vuelve a Vertical para comparar. Escribe dos párrafos, coloca el cursor antes del segundo y pulsa Ctrl+Enter para enviarlo a una página nueva.",
          },
        },
        {
          slug: "verifier-imprimer",
          title: { fr: "Vérifier l'orthographe et imprimer", ht: "Tcheke òtograf ak enprime", en: "Checking spelling and printing", es: "Revisar la ortografía e imprimir" },
          videoId: "",
          content: {
            fr: "Avant de partager un document, il faut le relire. Word t'aide en soulignant en rouge les mots qu'il ne reconnaît pas et en bleu certaines fautes de grammaire. Fais un clic droit sur un mot souligné : Word propose des corrections ; clique sur la bonne pour la remplacer aussitôt. Attention, l'ordinateur ne voit pas tout : relis-toi toi-même pour le sens.\n\nTu peux aussi lancer une vérification complète depuis l'onglet « Révision » en cliquant sur « Grammaire et orthographe » : Word parcourt tout le document et te propose les corrections une par une. C'est utile pour un long texte.\n\nPense aussi à vérifier la mise en page avant d'imprimer, en particulier l'orientation et les marges vues précédemment.\n\nPour imprimer, va dans « Fichier » puis « Imprimer ». Un aperçu à droite montre exactement ce qui sortira sur le papier : profites-en pour vérifier avant de gaspiller de l'encre. Choisis ton imprimante, indique le nombre de copies, puis clique sur « Imprimer ». Si tu n'as pas d'imprimante, tu peux aussi choisir « Enregistrer au format PDF » pour créer un fichier facile à envoyer par courriel.",
            ht: "Anvan ou pataje yon dokiman, ou dwe reli l. Word ede ou lè l souliye an wouj mo li pa rekonèt yo epi an ble kèk fot gramè. Fè yon klik dwat sou yon mo ki souliye : Word pwopoze koreksyon ; klike sou bon an pou ranplase l touswit. Atansyon, òdinatè a pa wè tout bagay : reli tèt ou pou sans lan.\n\nOu ka lanse yon verifikasyon konplè tou depi onglè « Révision » lè w klike sou « Grammaire et orthographe » : Word pase nan tout dokiman an epi pwopoze ou koreksyon yo youn pa youn. Sa itil pou yon tèks long.\n\nSonje tcheke mizanpaj la tou anvan ou enprime, sitou oryantasyon ak maj nou te wè anvan yo.\n\nPou enprime, ale nan « Fichier » epi « Imprimer ». Yon apèsi adwat montre egzakteman sa k ap soti sou papye a : pwofite pou tcheke anvan ou gaspiye lank. Chwazi enprimant ou, endike konbyen kopi, epi klike sou « Imprimer ». Si ou pa gen enprimant, ou ka chwazi « Enregistrer au format PDF » tou pou kreye yon fichye ki fasil pou voye pa imèl.",
            en: "Before sharing a document, you should proofread it. Word helps by underlining in red the words it does not recognize and in blue certain grammar mistakes. Right-click an underlined word: Word suggests corrections; click the right one to replace it instantly. Be careful, the computer does not catch everything: reread it yourself for meaning.\n\nYou can also run a full check from the \"Review\" tab by clicking \"Spelling & Grammar\": Word goes through the whole document and offers the corrections one by one. This is useful for a long text.\n\nAlso remember to check the layout before printing, especially the orientation and margins seen earlier.\n\nTo print, go to \"File\" then \"Print\". A preview on the right shows exactly what will come out on paper: use it to check before wasting ink. Choose your printer, set the number of copies, then click \"Print\". If you don't have a printer, you can also choose \"Save as PDF\" to create a file that is easy to send by email.",
            es: "Antes de compartir un documento, hay que revisarlo. Word te ayuda subrayando en rojo las palabras que no reconoce y en azul ciertos errores de gramática. Haz clic derecho sobre una palabra subrayada: Word propone correcciones; haz clic en la correcta para reemplazarla al instante. Cuidado, la computadora no lo ve todo: relee tú mismo para revisar el sentido.\n\nTambién puedes lanzar una revisión completa desde la pestaña «Revisar» haciendo clic en «Ortografía y gramática»: Word recorre todo el documento y te propone las correcciones una por una. Esto es útil para un texto largo.\n\nAcuérdate también de revisar el diseño antes de imprimir, en especial la orientación y los márgenes vistos antes.\n\nPara imprimir, ve a «Archivo» y luego «Imprimir». Una vista previa a la derecha muestra exactamente lo que saldrá en el papel: aprovéchala para comprobar antes de gastar tinta. Elige tu impresora, indica el número de copias y haz clic en «Imprimir». Si no tienes impresora, también puedes elegir «Guardar como PDF» para crear un archivo fácil de enviar por correo.",
          },
          keyPoints: {
            fr: ["Rouge = orthographe, bleu = grammaire ; clic droit pour corriger", "Révision > Grammaire et orthographe vérifie tout le document", "Fichier > Imprimer : vérifier l'aperçu avant d'imprimer", "Enregistrer au format PDF pour envoyer par courriel"],
            ht: ["Wouj = òtograf, ble = gramè ; klik dwat pou korije", "Révision > Grammaire et orthographe tcheke tout dokiman an", "Fichier > Imprimer : tcheke apèsi a anvan ou enprime", "Anrejistre an PDF pou voye pa imèl"],
            en: ["Red = spelling, blue = grammar; right-click to correct", "Review > Spelling & Grammar checks the whole document", "File > Print: check the preview before printing", "Save as PDF to send by email"],
            es: ["Rojo = ortografía, azul = gramática; clic derecho para corregir", "Revisar > Ortografía y gramática revisa todo el documento", "Archivo > Imprimir: revisar la vista previa antes de imprimir", "Guardar como PDF para enviar por correo"],
          },
          exercise: {
            fr: "Tape volontairement un texte avec deux ou trois fautes. Corrige-les avec le clic droit sur les mots soulignés, puis lance « Grammaire et orthographe » depuis l'onglet Révision. Ouvre enfin Fichier > Imprimer, observe l'aperçu, et enregistre le document au format PDF.",
            ht: "Tape yon tèks espre ak de oswa twa fot. Korije yo ak klik dwat sou mo ki souliye yo, epi lanse « Grammaire et orthographe » depi onglè Révision. Anfen ouvri Fichier > Imprimer, gade apèsi a, epi anrejistre dokiman an an PDF.",
            en: "Deliberately type a text with two or three mistakes. Correct them by right-clicking the underlined words, then run \"Spelling & Grammar\" from the Review tab. Finally open File > Print, look at the preview, and save the document as a PDF.",
            es: "Escribe a propósito un texto con dos o tres errores. Corrígelos con clic derecho en las palabras subrayadas, luego lanza «Ortografía y gramática» desde la pestaña Revisar. Por último, abre Archivo > Imprimir, observa la vista previa y guarda el documento como PDF.",
          },
        },
        {
          slug: "publipostage-base",
          title: { fr: "Le publipostage de base", ht: "Piblipostaj de baz", en: "Basic mail merge", es: "Combinación de correspondencia básica" },
          videoId: "",
          content: {
            fr: "Le publipostage sert à créer d'un coup plusieurs lettres identiques mais personnalisées, à partir d'une liste. Imagine que tu doives envoyer la même invitation à cinquante personnes, chacune avec son nom : au lieu de retaper la lettre cinquante fois, tu écris un seul modèle et Word remplace le nom automatiquement.\n\nCommence par écrire ta lettre normalement, en laissant vides les endroits qui changeront (le nom, la ville…). Va ensuite dans l'onglet « Publipostage », clique sur « Démarrer la fusion et le publipostage » et choisis « Lettres ». Puis, sur « Sélectionner les destinataires », choisis « Utiliser une liste existante » pour pointer vers un fichier Excel de noms, ou « Entrer une nouvelle liste » pour taper les noms directement.\n\nPlace ton curseur là où le nom doit apparaître, clique sur « Insérer un champ de fusion » et choisis le champ voulu, par exemple « Nom ». Word insère un repère comme «Nom» qui sera remplacé par chaque valeur de ta liste. Répète pour chaque information variable.\n\nClique sur « Aperçu des résultats » pour voir les lettres se remplir une par une avec les vrais noms. Quand tout est correct, clique sur « Terminer et fusionner » : tu peux alors imprimer toutes les lettres d'un coup ou générer un document contenant une lettre par personne. C'est un gain de temps énorme pour un courrier en nombre.",
            ht: "Piblipostaj sèvi pou kreye yon sèl kou plizyè lèt ki menm men pèsonalize, apati yon lis. Imajine ou dwe voye menm envitasyon an bay senkant moun, chak ak non pa yo : olye pou w retape lèt la senkant fwa, ou ekri yon sèl modèl epi Word ranplase non an otomatikman.\n\nKòmanse pa ekri lèt ou nòmalman, kite vid kote k ap chanje yo (non an, vil la…). Apre sa ale nan onglè « Publipostage », klike sou « Démarrer la fusion et le publipostage » epi chwazi « Lettres ». Epi, sou « Sélectionner les destinataires », chwazi « Utiliser une liste existante » pou pwente sou yon fichye Excel non, oswa « Entrer une nouvelle liste » pou tape non yo dirèkteman.\n\nMete kurseur ou kote non an dwe parèt la, klike sou « Insérer un champ de fusion » epi chwazi chan ou vle a, pa egzanp « Nom ». Word mete yon repè tankou «Nom» ki pral ranplase ak chak valè nan lis ou. Repete pou chak enfòmasyon ki chanje.\n\nKlike sou « Aperçu des résultats » pou wè lèt yo ranpli youn pa youn ak vrè non yo. Lè tout bagay kòrèk, klike sou « Terminer et fusionner » : ou ka enprime tout lèt yo yon sèl kou oswa kreye yon dokiman ki gen yon lèt pou chak moun. Se yon gwo ekonomi tan pou yon kourye an kantite.",
            en: "Mail merge is used to create at once several identical but personalized letters, from a list. Imagine you have to send the same invitation to fifty people, each with their own name: instead of retyping the letter fifty times, you write a single model and Word replaces the name automatically.\n\nStart by writing your letter normally, leaving blank the parts that will change (the name, the city…). Then go to the \"Mailings\" tab, click \"Start Mail Merge\" and choose \"Letters\". Then, on \"Select Recipients\", choose \"Use an Existing List\" to point to an Excel file of names, or \"Type a New List\" to enter the names directly.\n\nPlace your cursor where the name should appear, click \"Insert Merge Field\" and choose the field you want, for example \"Name\". Word inserts a marker like «Name» that will be replaced by each value in your list. Repeat for each variable piece of information.\n\nClick \"Preview Results\" to watch the letters fill in one by one with the real names. When everything is correct, click \"Finish & Merge\": you can then print all the letters at once or generate a document containing one letter per person. It is a huge time-saver for bulk mail.",
            es: "La combinación de correspondencia sirve para crear de una vez varias cartas idénticas pero personalizadas, a partir de una lista. Imagina que debes enviar la misma invitación a cincuenta personas, cada una con su nombre: en vez de volver a escribir la carta cincuenta veces, escribes un solo modelo y Word reemplaza el nombre automáticamente.\n\nEmpieza por escribir tu carta normalmente, dejando vacíos los lugares que cambiarán (el nombre, la ciudad…). Luego ve a la pestaña «Correspondencia», haz clic en «Iniciar combinación de correspondencia» y elige «Cartas». Después, en «Seleccionar destinatarios», elige «Usar una lista existente» para apuntar a un archivo de Excel con nombres, o «Escribir una nueva lista» para escribir los nombres directamente.\n\nColoca tu cursor donde debe aparecer el nombre, haz clic en «Insertar campo combinado» y elige el campo que quieras, por ejemplo «Nombre». Word inserta una marca como «Nombre» que será reemplazada por cada valor de tu lista. Repite para cada dato variable.\n\nHaz clic en «Vista previa de resultados» para ver las cartas rellenarse una por una con los nombres reales. Cuando todo esté correcto, haz clic en «Finalizar y combinar»: puedes entonces imprimir todas las cartas de una vez o generar un documento con una carta por persona. Es un ahorro de tiempo enorme para correo en cantidad.",
          },
          keyPoints: {
            fr: ["Publipostage = une lettre modèle + une liste de destinataires", "Onglet Publipostage > Démarrer la fusion > Lettres", "Insérer un champ de fusion là où l'info change (Nom, Ville)", "Aperçu des résultats, puis Terminer et fusionner pour imprimer"],
            ht: ["Piblipostaj = yon lèt modèl + yon lis destinatè", "Onglè Publipostage > Démarrer la fusion > Lettres", "Mete yon chan fizyon kote enfo a chanje (Non, Vil)", "Aperçu des résultats, epi Terminer et fusionner pou enprime"],
            en: ["Mail merge = one model letter + a list of recipients", "Mailings tab > Start Mail Merge > Letters", "Insert a merge field where the info changes (Name, City)", "Preview Results, then Finish & Merge to print"],
            es: ["Combinación = una carta modelo + una lista de destinatarios", "Pestaña Correspondencia > Iniciar combinación > Cartas", "Insertar un campo combinado donde cambia el dato (Nombre, Ciudad)", "Vista previa de resultados, luego Finalizar y combinar para imprimir"],
          },
          exercise: {
            fr: "Écris une courte lettre d'invitation. Dans l'onglet Publipostage, démarre une fusion de type « Lettres » et crée une nouvelle liste de trois personnes avec leur nom. Insère le champ « Nom » après « Cher/Chère », puis utilise « Aperçu des résultats » pour vérifier les trois lettres.",
            ht: "Ekri yon ti lèt envitasyon. Nan onglè Publipostage, kòmanse yon fizyon tip « Lettres » epi kreye yon nouvo lis twa moun ak non yo. Mete chan « Nom » an apre « Chè », epi sèvi ak « Aperçu des résultats » pou verifye twa lèt yo.",
            en: "Write a short invitation letter. In the Mailings tab, start a \"Letters\" merge and create a new list of three people with their names. Insert the \"Name\" field after \"Dear\", then use \"Preview Results\" to check the three letters.",
            es: "Escribe una carta de invitación corta. En la pestaña Correspondencia, inicia una combinación de tipo «Cartas» y crea una nueva lista de tres personas con su nombre. Inserta el campo «Nombre» después de «Estimado/a», luego usa «Vista previa de resultados» para revisar las tres cartas.",
          },
        },
      ],
    },
  ],
};

export default word;
